### ISSUE TITLE
Questions on how the cors middleware works

### ISSUE THREAD

**Issue by motss** [honojs/hono#1002]
In the following LoC, `cors` defaults to the 1st origin in a provided list of origins when it is not able to find a match.

https://github.com/honojs/hono/blob/ea67919b8215ef9eed4f91fc85e4fda71c70d482/src/middleware/cors/index.ts#L30

 It is mainly due to the request URL does not have `origin`/ `Origin` header set. However, this raises a few questions:

1. Should an incoming request be allowed when it is not one of the allowed origins?
1. Why is the 1st origin being used as the default origin?
1. While HTTP headers are not case sensitive, does the middleware also need to look for the request origin from the `Origin` header instead of just `origin`, like `c.req.headers.get('Origin')`?

   https://github.com/honojs/hono/blob/ea67919b8215ef9eed4f91fc85e4fda71c70d482/src/middleware/cors/index.ts#L39

Thanks in advance.

**Comment by yusukebe** [comment]
Hi @motss !

> 1. Should an incoming request be allowed when it is not one of the allowed origins?

I'm not sure I understand the question, but probably no.

> 2. Why is the 1st origin being used as the default origin?

It's just the way it is. Since we cannot set multiple origins to `Access-Control-Allow-Origin`, we have decided to use the first one registered.

> 3. While HTTP headers are not case sensitive, does the middleware also need to look for the request origin from the Origin header instead of just origin, like c.req.headers.get('Origin')?

`c.req.headers.get('origin')` can match `Origin`, not only `origin`.
