### ISSUE TITLE
Feature Request: Get output of JWT payload

### ISSUE THREAD

**Issue by Skye-31** [honojs/hono#1005]
In my application, we need the payload from the validated JWT, however the util currently just returns `true` if it's been validated. This is a feature request to either:

- Allow it to return the payload (this might be breaking though?)
- Put it in the context, using `c.set()` with a key that the user defines as one of the options

This would allow people to use the JWT module more effectively 🙂

**Comment by yusukebe** [comment]
Hi @Skye-31 !

If we will do it, I would use `c.set()`. We will consider supporting it. Thanks!

**Comment by Skye-31** [comment]
Awesome, let me know if there's anything I can do to help 😄

**Comment by yusukebe** [comment]
Hi @Skye-31 !

Since "v3.1.5", we can get the payload with `c.get('jwtPayload')`:

```ts
import { Hono } from 'hono'
import { jwt } from 'hono/jwt'

const app = new Hono()

app.post(
  '/auth/abc',
  jwt({
    secret: 'a-secret',
  }),
  (c) => {
    const payload = c.get('jwtPayload')
    // ...
  }
)
```

Try it!

**Comment by Skye-31** [comment]
Awesome, thanks!
