### ISSUE TITLE
Decode URL params

### ISSUE THREAD

**Issue by sergiocarneiro** [honojs/hono#1006]
Since query params are passed in the URL, the data is encoded (e.g. `@` becomes `%40`).

This breaks the **validators** in cases like having a Regex to validate an email.

Also the data received in the **handlers** is encoded.

### Current Behavior
```ts
const query = c.req.valid('query')
// { email: 'example%40gmail.com' }
```

### Expected Behavior
```ts
const query = c.req.valid('query')
// { email: 'example@gmail.com' }
```

**Comment by yusukebe** [comment]
Hi @sergiocarneiro !

Thanks for creating the issue. I've released the new version `v3.1.3`, which includes the change to resolve this issue. Try it!
