### ISSUE TITLE
hono 3.1.4 brings new query utils which breaks some query use cases

### ISSUE THREAD

**Issue by tangye1234** [honojs/hono#1022]
Let's see the case:

`?pretty&foo=bar` should be resolved with `{ foo: 'bar', pretty: '' }` or `{ foo: 'bar', pretty: undefined }`.
> Which I think the former one is more precise.

![screenshot](https://user-images.githubusercontent.com/447084/229032684-4047d929-82d6-44bb-88c4-7a2042c29f02.png)

But with current hono implementations, this resolved as `{ 'pretty$foo': 'bar' }`
![screenshot](https://user-images.githubusercontent.com/447084/229033661-57b50e2a-2a24-4ac3-b3b1-5c82f7f2705e.png)

**Comment by tangye1234** [comment]
I suggest all to continue use 3.1.3 version unless this bug is fixed

**Comment by yusukebe** [comment]
Hi @tangye1234 !

Thank you for reporting!

@usualoma 

What do you think?

**Comment by usualoma** [comment]
Hi @tangye1234

Thanks for the report.
This issue will be fixed in #1023.
