### ISSUE TITLE
[Question] How Can I set a header key in a Middleware?

### ISSUE THREAD

**Issue by EFEXP** [honojs/hono#1028]
Just Question.
This code tries to convert jwtsub into a header user-id key.
But header is Immutable.
Are there alternative ways to compute the incoming request header keys?
The following middlewares need to computed requests.

```typescript
export const setTenantIdMiddleware: MiddlewareHandler = async (ctx, next) => {
    const jwtPayload = ctx.get('jwtPayload');

  
    if (!jwtPayload) {
      const res = new Response('Unauthorized', {
        status: 401,
        headers: {
          'WWW-Authenticate': `Bearer realm="${ctx.req.url}",error="invalid_request",error_description="jwtPayload is missing"`,
        },
      });
      throw new HTTPException(401, { res });
    }
  
    const sub = jwtPayload.sub;
    ctx.req.headers.set('user-id', sub);
  
    await next();
  };
```

```log
  Trace: TypeError: immutable
    at Headers.set (/home/vscode/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/node_modules/undici/lib/fetch/headers.js:379:13)
```

**Comment by yusukebe** [comment]
Hi @EFEXP !

We can't modify the "request" headers. It's immutable. This is a Cloudflare Workers (and other runtimes) issue, not Hono. Instead, how about using `c.get()`/`c.set()` to pass the values to the handler?

```ts
type Variables = {
  userId: string
}

const app = new Hono<{ Variables: Variables }>()

export const middleware: MiddlewareHandler<{ Variables: Variables }> = async (c, next) => {
  c.set('userId', 'foo')
  await next()
}

app.get('/', middleware, (c) => {
  return c.text(`Hello ${c.get('userId')}`) // <== Hello foo
})
```

Or does it have to be a request "header"?

**Comment by EFEXP** [comment]
header.
This Workers is the root of the service binding and acts as an authentication proxy.
I want the downstream Workers to look as if they were set from the beginning.
It is possible to set it once in ctx and then take it out later and put it in Header, but it is not smart.

**Comment by yusukebe** [comment]
If you use Service Bindings, you can use the response header instead of setting the value in the request header.

```ts
// auth.ts
app.get('*', (c) => {
  // authenticate
  c.header('userId', 'foo')
  return c.text('Authorized')
})
```

```ts
// app.ts
type Bindings = {
  auth: Fetcher
}

const app = new Hono<{ Bindings: Bindings }>()

app.get('/', async (c) => {
  const authResponse = await c.env.auth.fetch(c.req.raw.clone())
  const userId = authResponse.headers.get('userId')
  //
})
```

**Comment by EFEXP** [comment]
Thank you for your assistance!
Based on your suggestion, should I restructure my worker stack as follows?

```
gateway
- auth
- downstream
```

Currently, my worker stack is arranged like this:

```
gateway (including auth)
- downstream
```

Your guidance has been very helpful to me.

**Comment by yusukebe** [comment]
I'm not super familiar with Service Bindings, but I think you can do it without restructuring. For example, if we use Bearer Auth with Service Bindings, we can write `gateway (including auth)` like the following:

```ts
import { Hono } from 'hono'
import { bearerAuth } from 'hono/bearer-auth'

type Bindings = {
  application: Fetcher // downstream
}

const app = new Hono<{ Bindings: Bindings }>()

app.get('/', bearerAuth({ token: 'your token' }), async (c) => {
  return await c.env.application.fetch(c.req.raw.clone())
})
```

**Comment by EFEXP** [comment]
Thank you for quick response !
I'll try it :)
