### ISSUE TITLE
Support `Host` as part of route matching?

### ISSUE THREAD

**Issue by jbergstroem** [honojs/hono#1032]
For applications such as proxies or any application that accepts multiple hostnames as part of routing logic it would be useful if each route also could match on `Request.Host`. Not sure if this is out of scope for Hono?

**Comment by yusukebe** [comment]
Hi @jbergstroem !

It's an interesting idea to use `Host` for routing, but it's out of the score for Hono. To implement it, we have to add not a few codes, and it can lead to performance degradation. If you run it on Cloudflare Workers, you could use Service Bindings.

**Comment by jbergstroem** [comment]
> It's an interesting idea to use `Host` for routing, but it's out of the score for Hono. To implement it, we have to add not a few codes, and it can lead to performance degradation. If you run it on Cloudflare Workers, you could use Service Bindings.

I can understand if its out of scope. In many proxy scenarios you don't always control your DNS zone but tell your clients to point a domain as a CNAME to yours; which makes it hard to scale this on for instance Cloudflare or Deno cloud, but works great in environments where you have less boundary checks (self hosting, fly.io, ..). I think Fastify might be a better pick to get more tooling around http parsing in this case.

**Comment by yusukebe** [comment]
Hi @jbergstroem 

I've started to rethink this issue. Actually, previously, I was trying to create an application using Cloudflare Workers that could handle various subdomains. If the application is on a custom domain, it can use multiple subdomains. If that's the case, the current Hono router becomes less useful, as mentioned above.

Hono has several routers. Not all routers need to support this, but it would be great if one or two routers could support host names. This would provide more flexibility when dealing with applications that use multiple subdomains.

Let's leave this issue open.

**Comment by yusukebe** [comment]
Hi @usualoma 

Whether we implement it or not, what do you think about this feature? Do you think it's important?

**Comment by jbergstroem** [comment]
> Hono has several routers. Not all routers need to support this, but it would be great if one or two routers could support host names. This would provide more flexibility when dealing with applications that use multiple subdomains.

Makes sense. If it helps, I would not be deploying on workers or deno cloud since these are very limited in how you  can manage domain name pointers outside of the ones you own (which is totally fine, I understand why). Consider for instance `myservice.myclient.com CNAME myservice.com`. You can't achieve this on workers unless you control both zones.

**Comment by usualoma** [comment]
Hi @yusukebe 

I think we can support routing, including hostnames, by allowing getPath to be replaced as follows.
(How hostnames can be specified is a matter of debate.)

Also, by allowing getPath to be replaced, request headers and other information other than hostnames could be referenced for routing. This feature would take advantage of “hono’s fast routers."

This change may slightly increase bundle size, but I don't think there will be any performance degradation.

#1061

However, I wonder if this feature is essential for the hono. It may be something that is optional.

**Comment by yusukebe** [comment]
@usualoma

That's fantastic! I love your idea of creating `getPath()`!

Everything seems good. I think it's acceptable to slightly increase the bundle size, and making `getPath` an option for `new Hono()` is great. I'd like to proceed with this approach.

If possible, please create a PR targeting the "next" branch. Thank you!

**Comment by usualoma** [comment]
@yusukebe Thanks!
Rebased and created a PR for the "next" branch.
#1064

**Comment by jbergstroem** [comment]
Fixed with https://github.com/honojs/hono/pull/1064

Lets keep documentation as a separate issue/thing to work on.
