### ISSUE TITLE
We can use environment variables inside middleware but how to access them in middleware options?

### ISSUE THREAD

**Issue by topperspal** [honojs/hono#1035]
How to access environment variables in middlewares options for `jwt({secret: env.JWT_SECRET})`

I have to use this trick to get this done
```ts
export const authMiddleware: MiddlewareHandler = async (c, next) => {
  await jwt({ secret: c.env.JWT_SECRET })(c, next);
};

app.get("/", authMiddleware, (c) => {
  return c.text("Authorized!!!");
});
```

**Comment by yusukebe** [comment]
Hi @topperspal !

Your way is almost right! Please refer to the following documentation; you can do it the same way for JWT.

https://hono.dev/getting-started/cloudflare-workers#using-variables-in-middleware

**Comment by topperspal** [comment]
You are right.
