### ISSUE TITLE
Range error  Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by arthurvanl** [honojs/hono#1044]
I keep geting this error
`RangeError: Maximum call stack size exceeded.`

`index.ts`
```ts
import { Hono } from "hono";
import { Logger } from "./utils/logger/index.js";

const port = parseInt(process.env.PORT as string) || 3000;

const logger = new Logger();

const app = new Hono();

app.get("/test", (c) => {
    return c.json({ message: "Hello World!" }, 200);
});

logger.log(`Running at http://localhost:${port}`);

const server = Bun.serve({
    port,
    fetch: app.fetch,
    // development: process.env.DEVELOPMENT ? true : false,
});

export default server;
```

**Comment by yusukebe** [comment]
Hi @arthurvanl !

I can't to reproduce the error. Could you try running it after removing the `Logger`?

**Comment by arthurvanl** [comment]
> Hi @arthurvanl !
> 
> 
> 
> I can't to reproduce the error. Could you try running it after removing the `Logger`?

I asked the developer of Bun. He told me that it was almost certainly Buns fault. I tried removing the logger. Did not make a change

**Comment by yusukebe** [comment]
How about a minimal app?

```ts
// index.ts
import { Hono } from 'hono'

const app = new Hono()

app.get('/', (c) => c.text('Hello Bun!'))

Bun.serve(app)
```

```
bun run index.ts
```

**Comment by arthurvanl** [comment]
It's actually a Bun.sh issue and not hono's fault

**Comment by yusukebe** [comment]
We can close this.
