### ISSUE TITLE
Reading from "fastly:env" is not handled by plugins

### ISSUE THREAD

**Issue by shyim** [honojs/hono#1052]
Hey,

I am trying to bundle hono with webpack and it explodes due to something with fastly:

```
Module build failed: UnhandledSchemeError: Reading from "fastly:env" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "fastly:" URIs.
    at C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\webpack\lib\NormalModule.js:837:25
    at Hook.eval [as callAsync] (eval at create (C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\tapable\lib\Hook.js:18:14)
    at Object.processResource (C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\webpack\lib\NormalModule.js:834:8)
    at processResource (C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\loader-runner\lib\LoaderRunner.js:398:2)
    at NormalModule._doBuild (C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\webpack\lib\NormalModule.js:824:3)
    at NormalModule.build (C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\webpack\lib\NormalModule.js:968:15)
    at C:\Users\shyim\Downloads\FroshAppWebDav\node_modules\webpack\lib\Compilation.js:1371:12
 @ ./node_modules/hono/dist/cjs/context.js 228:22-43
 @ ./node_modules/hono/dist/cjs/hono.js 25:21-41
 @ ./node_modules/hono/dist/cjs/index.js 24:18-35
 @ ./src/index.ts 3:15-30

webpack 5.81.0 compiled with 1 error in 1038 m
```

This line seems let it explode https://github.com/honojs/hono/blob/f0777321ae43ad5b605c583aed556e00f73ce15f/src/adapter.ts#L27

**Comment by yusukebe** [comment]
Hi @shyim !

Thank you for raising the issue. It's not good to throw an error, whether the code is important or not. I'll fix it later.

**Comment by JakeChampion** [comment]
Another possible approach is to configure webpack to not attempt to bundle `fastly:` namespaced modules, which can be done like this:

https://github.com/fastly/compute-starter-kit-javascript-default/blob/e02f0f178efca7691dd31729f76abbaf43d82160/webpack.config.js#L28-L37

**Comment by yusukebe** [comment]
@JakeChampion 

I think there is another issue from [how to know whether it runs on Fastly or not](https://github.com/fastly/js-compute-runtime/issues/517). With [this adapter](https://github.com/honojs/hono/blob/f0777321ae43ad5b605c583aed556e00f73ce15f/src/adapter.ts), we want to get "user-defined values" similar to environment values from `NODE_ENV`. For Fastly Compute@Edge, `fastly:env` has values like `FASTLY_HOSTNAME`, but these are not user-set values. I would like to know if Fastly has any way for users to set and get these values.

By the way, I've used Edge dictionaries for VCL configuration before. If there isn't a good way to share variables for Compute@Edge, I'll request it from you :)

**Comment by JakeChampion** [comment]
User defined configuration/environment parameters are possible via Fastly Config Stores 👍 They can be modified without having to redeploy your Fastly Compute application ☺️ 

Config Store announcement: <https://www.fastly.com/blog/introducing-config-store-storing-and-updating-configuration-data-at-the-edge>

JS Documentation for Config Store: <https://js-compute-reference-docs.edgecompute.app/docs/fastly:config-store/ConfigStore/>

**Comment by yusukebe** [comment]
@JakeChampion 

I did not know that! Thanks!

---

However, once we will remove the `fastly:*` from the `adapter` to avoid a `webpack` error. I will look for a better way to get the Config Store value from `adapter` later!

**Comment by JakeChampion** [comment]
> @JakeChampion 
> 
> I did not know that! Thanks!
> 
> ---
> 
> However, once we will remove the `fastly:*` from the `adapter` to avoid a `webpack` error. I will look for a better way to get the Config Store value from `adapter` later!
> 

`globalThis.ConfigStore` should work 😃

**Comment by yusukebe** [comment]
@JakeChampion 

!?!?!?!?!! Greaaaat!

**Comment by shyim** [comment]
thank you for your fast fix ❤️
