### ISSUE TITLE
Hono auto replace the latest set header when have mutiple values with the same header key

### ISSUE THREAD

**Issue by harrytran998** [honojs/hono#1055]
If you use ChatGPT, in their sever --> They can set multiple `Set-Cookie` headers in login with google step. I tried in Hono too, but not luck 😆. Hope anyone can take a look.

![image](https://user-images.githubusercontent.com/24296018/235353550-00e058d8-3e05-48d8-baef-8f0bfbd96d21.png)

Here is my code

```ts
const auth = new Hono<{ Bindings: EnvBindings }>();
export const authRoute = auth.post('/auth/auth0/token', (c) => {
	... handle business logic
	c.header('Set-Cookie', 'XYZ');
	c.header('Set-Cookie', 'ABC'); --> Response header only return this value
})
```

**Comment by yusukebe** [comment]
Use `c.cookie()` or `c.heaer('foo', 'bar', { append: true })`.

**Comment by harrytran998** [comment]
Oh, thank you for suggesting! I use `c.cookie` and it worked!
