### ISSUE TITLE
Tasks for v4

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1059]
Tasks for the major upgrade to version "v4". The following items may be edited:

- [x] Remove HTTP status messages and remove status code Unions from `utils/http-status.ts`. #1037 
- [x] PatternRourter
- [x] LinearRouter
- [ ] HonoBase
- [x] `hono/tiny`
- [ ] `hono/quick`
- [ ] Node Adapter supports Node.js native web standard API
- [ ] PatternRouter as default ?
- [x] Allow routings with hostname

**Comment by yusukebe** [comment]
I'm reconsidering the versioning strategy. Perhaps, these features will be released as v3.2, and we may not release v4 soon.

**Comment by donchev7** [comment]
Why? Some of these are not backwards compatible, or? (c.cookie, c.req.cookie, query validation)

**Comment by yusukebe** [comment]
@donchev7 

Ah, we won't remove them immediately in v3.2. We'll mark them as deprecated.

**Comment by yusukebe** [comment]
We decided to release v4 immediately. Therefore, I'll close this issue.
