### ISSUE TITLE
serve static error

### ISSUE THREAD

**Issue by lane711** [honojs/hono#1067]
the docs here seem to be a bit incomplete:
https://hono.dev/getting-started/nodejs#serve-static-files

```
app.use('/images/*', serveStatic({ root: './assets/images' }))
```

gives me this error:
```
✘ [ERROR] Error on remote worker: ParseError: A request to the Cloudflare API (/accounts/f9d6328dc3115e621758a741dda3d5c4/workers/scripts/graphql-yoga/edge-preview) failed.

      at throwFetchError
  (/Users/a/Dev/sonicjs-workers/yoga/node_modules/wrangler/wrangler-dist/cli.js:130684:17)
      at fetchResult
  (/Users/a/Dev/sonicjs-workers/yoga/node_modules/wrangler/wrangler-dist/cli.js:130651:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async createPreviewToken
  (/Users/a/Dev/sonicjs-workers/yoga/node_modules/wrangler/wrangler-dist/cli.js:132627:29)
      at async createWorkerPreview
  (/Users/a/Dev/sonicjs-workers/yoga/node_modules/wrangler/wrangler-dist/cli.js:132648:17)
      at async start
  (/Users/a/Dev/sonicjs-workers/yoga/node_modules/wrangler/wrangler-dist/cli.js:151221:34) {
    text: 'A request to the Cloudflare API
  (/accounts/f9d6328dc3115e621758a741dda3d5c4/workers/scripts/graphql-yoga/edge-preview) failed.',
    notes: [
      {
        text: 'Uncaught Error: No such module "__STATIC_CONTENT_MANIFEST".\n' +
          '  imported from "index.js"\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }
```

do I also need to add something like this to the wrangler.toml file?
```
[site]
bucket = "./assets"
```

**Comment by yusukebe** [comment]
Hi @lane711 !

Try a minimal code:

```ts
import { Hono } from 'hono'
import { serveStatic } from 'hono/cloudflare-workers'

const app = new Hono()

app.use('/images/*', serveStatic({ root: './assets/images' }))

export default app
```

**Comment by lane711** [comment]
ok got it working, but only after adding:
```
[site]
bucket = "./assets"
```
I'm assuming that is required?

**Comment by yusukebe** [comment]
@lane711 

Yes. See: https://developers.cloudflare.com/workers/platform/sites/configuration/

**Comment by yusukebe** [comment]
@lane711 

Is this issue fixed?

**Comment by lane711** [comment]
Yes it is fixed thanks. For anyone else trying to do this, Cloudflare pages is a better solution for my situation. Pages is the newer solution when trying to host static assets.

**Comment by appsdevpk** [comment]
i have a little confusion here. i used the below code
app.use('/assets/*', serveStatic({ root: './' }));
and then this
app.use('/assets/*', serveStatic({ root: './assets' }));

and a lot of other variations but whenever i reference some static file in jsx like below image tag

<img src="/assets/img/me.jpg" alt="" />
OR
<img src="/img/me.jpg" alt="" />

i always get 404 not found.

so how can i reference my static files in jsx? or should i change my serveStatic call or what?
