### ISSUE TITLE
dangerouslySetInnerHTML always returns Error

### ISSUE THREAD

**Issue by mountainash** [honojs/hono#1068]
The following code snippet throws the error **"Can only set one of `children` or `props.dangerouslySetInnerHTML`."**

```javascript
import { Hono } from 'hono';

const app = new Hono();

app.get('/', (c) => {
  const inner = { __html: 'JSX &middot; SSR' };
  return c.html(<div dangerouslySetInnerHTML={inner} />);
});

const port = Number(process.env.PORT) || 3000;
console.log(`🚀 Running at http://localhost:${port}`);

export default {
  port,
  fetch: app.fetch
};
```

This is based on the Docs at https://hono.dev/middleware/builtin/jsx#dangerouslysetinnerhtml

The error is coming from https://github.com/honojs/hono/blob/21f4c196e7914a5d11348d8591a23a094dee15bd/src/middleware/jsx/index.ts#L125 but it's condition of `(children.length > 0)` should not be passing.

**Comment by yusukebe** [comment]
Hi @mountainash !

I was able to reproduce the issue in my environment. We might be able to fix it, so please wait!

**Comment by appsdevpk** [comment]
is it resolved? because i am also facing the same issue

**Comment by yusukebe** [comment]
@appsdevpk 

Yes, resolved. But new version which includes this change is not been released yet.

Please wait a moment or you can use `hono@3.2.0-rc.3` as a workaround.

**Comment by yusukebe** [comment]
@appsdevpk 

You have to write like this:

```ts
const Descr = () => <h2 dangerouslySetInnerHTML={text} />
```

**Comment by appsdevpk** [comment]
Thanks, it worked
