### ISSUE TITLE
Trying to get simple test working, ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by lane711** [honojs/hono#1092]
I am following your example test here:
https://github.com/honojs/hono-minimal/blob/main/src/index.test.ts

I have pretty much the same simple test here:
https://github.com/lane711/yoga/blob/feature/hono2/src/index.test.ts

but when I run it I get:
` FAIL  src/index.test.ts
  ● Test the application › Should return 200 response

    ReferenceError: Request is not defined

       6 | describe('Test the application', () => {
       7 |   it('Should return 200 response', async () => {
    >  8 |     const res = await app.request(`${baseUrl}/test`)
         |                           ^
       9 |     expect(res.status).toBe(200)
      10 |   })
      11 | })

      at Hono.request (node_modules/hono/dist/cjs/hono.js:66:28)
      at Object.<anonymous> (src/index.test.ts:8:27)`

**Comment by lane711** [comment]
nvm I was able to get this working by starting with the honor minimal project

**Comment by dmitryshelomanov** [comment]
@lane711 How did you solve it ?

**Comment by dmitryshelomanov** [comment]
minimal example not working

```js
import { Hono } from 'hono';
import { testClient } from 'hono/testing';

describe('@/server/controllers', () => {
  it('GET /metrics', async () => {
    const app = new Hono().get('/search', c => c.json({ hello: 'world' }));

    const res = await testClient(app).search.$get();

    console.log(res);
  });
});
```

jest

**Comment by EdamAme-x** [comment]
What specific problems do you see?
