### ISSUE TITLE
[Feature suggestion] Adding End To End Type safety

### ISSUE THREAD

**Issue by hamza1312** [honojs/hono#1094]
Adding end to end type safety can improve user experience, There's an implementation of that already it's called [tRPC](https://trpc.io/), and a Bun framework called elysia js already implemented their own "plugin" for using to fetch with type safety!

I consider this feature very interesting since i'll help developers integrate their backend **easily** with the frontend.
Thanks

**Comment by yusukebe** [comment]
Hi @hamza1312 !

We already have it!
https://hono.dev/concepts/stacks

**Comment by hamza1312** [comment]
WHAT, Amazing!

**Comment by yusukebe** [comment]
Yes. So, I'll close this issue.
