### ISSUE TITLE
Add options to pass custom replacer to json function

### ISSUE THREAD

**Issue by divyam234** [honojs/hono#1096]
Sometimes people want to remove null values from response .It will be good if json function accepts custom replacer like below

JSON.stringify(x, (k, v) => v ?? undefined)

Although I can manually send Response Object but it will be good if its added in api itself. If its fine I can raise a pull request

**Comment by yusukebe** [comment]
Hi @divyam234 

That could be a good idea indeed. But, we would need to carefully discuss the API design for it. I'd be interested to hear your thoughts on this.
