### ISSUE TITLE
jsx

### ISSUE THREAD

**Issue by lane711** [honojs/hono#1097]
Hi, I am trying to incorporate the jsx middelware into my project:

https://hono.dev/middleware/builtin/jsx

My code is here
https://github.com/lane711/hono-pages2/blob/main/src/cms/admin/test.tsx

Getting this error:
`Cannot find name 'React'.ts(2304)`
on the `<html>` and other tags

I must have something misconfigured?

**Comment by yusukebe** [comment]
@lane711 

Rename `tsconfig.ts` to `tsconfig.json`.

**Comment by lane711** [comment]
Thanks that works
