### ISSUE TITLE
`hono/quick` is really quick?

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1109]
We are planning to release `v3.2.0` soon! In this version, we are introducing a new feature called "preset". If you use `hono/quick`, the application will use `LinearRouter`, which is the fastest during the registration phase. Therefore, I believe using `hono/quick` is most suitable for **Fastly Compute@Edge**.

You can already use `hono/quick` by installing the RC release:

```
yarn add hono@3.2.0-rc.4
```

Then, you can use it by importing `hono/quick`.

```ts
import { Hono } from 'hono/quick'
```

I'm interested in knowing the performance of `hono/quick` in the Fastly Compute@Edge environment.

**Comment by yusukebe** [comment]
Hi @JakeChampion !

If you are interested in this issue, could you try using `hono/quick` in the Compute@Edge. It would be great if you could also provide some benchmark results.

**Comment by yusukebe** [comment]
Great! Thank you! This score is encouraging for us!

**Comment by riderx** [comment]
Quick question about this, I use Cloudflare workers with super simple routes:
https://github.com/Cap-go/capgo/blob/development/cloudflare_workers/index.ts
Do switch to tiny or quick preset, would have interest in that case ?
