### ISSUE TITLE
HTTPException type not available in nodejs

### ISSUE THREAD

**Issue by BrianMaldoPinata** [honojs/hono#1116]
I am trying to implement the error handling per the documentation [here](https://hono.dev/api/hono#error-handling) in node however there doesn't appear to be a HTTPException type.

**Comment by yusukebe** [comment]
Hi @BrianMaldoPinata 

You have to import `HTTPException`:

```ts
import { HTTPException } from 'hono/http-exception'

// ...
```

**Comment by itswil** [comment]
If you created an Hono project using `bun create hono ./myapp`
Then you may have an older version (2.2.5) of Hono installed

See https://www.npmjs.com/package/@bun-examples/hono?activeTab=code

Updating your Hono version may fix the issue

**Comment by yusukebe** [comment]
I'll close this issue. If you have any problem, feel free to reopen. Thanks.
