### ISSUE TITLE
Cache middleware is not working

### ISSUE THREAD

**Issue by ytkg** [honojs/hono#1118]
I don't think the cache is working after v3.1.0.

```typescript
import { Hono } from 'hono'
import { cache } from 'hono/cache'

const app = new Hono()

app.use(
  '/',
  cache({ cacheName: 'hello', cacheControl: 'max-age=360'}),
  async (c) => c.text('Hello, Hono!')
)

export default app
```

I have confirmed that it works up to v3.0.5.

I'm sorry if I'm wrong.

**Comment by yusukebe** [comment]
Hi @ytkg !

It seems to work fine in my environment, Cloudflare Workers + Custom domain. By the way, on Cloudflare Workers, it doesn't work on *.workers.dev` domain.

> However, any Cache API operations in the Cloudflare Workers dashboard editor, Playground previews, and any *.workers.dev deployments will have no impact.
> https://developers.cloudflare.com/workers/runtime-apis/cache/

Are you not running on `*.workers.dev`?

**Comment by ytkg** [comment]
Thanks for the confirmation!

I am using a custom domain.

You may be using the wrong confirmation method.
In the Network tab of Chrome's Developer Tools, the status code always returns 200!

Let me know if there is a correct way to check.

**Comment by yusukebe** [comment]
@ytkg 

The status code isn't related to whether it is cached or not. You can check the cache status via the `Cf-Cache-Status` response header.

<img width="467" alt="SS" src="https://github.com/honojs/hono/assets/10682/d1cec1af-ce80-4946-8694-9b1a62e996ab">

The status code `304` means "Not Modified". If we use the "Etag" middleware, it's possible to return `304`.

**Comment by ytkg** [comment]
So it was! I didn't know that!

We have confirmed that the cache is working!
Thanks!
