### ISSUE TITLE
Unexpected 500 Error, Instead of 401 in Basic Auth Middleware.

### ISSUE THREAD

**Issue by Tomohiro-Honda** [honojs/hono#1121]
Basic Authentication Middleware returns a 500 error when passed an Authorization header containing a string that is not correctly Base64 encoded.

```
app.use(
  '*',
  basicAuth({
    username: 'hono',
    password: 'acoolproject',
  })

app.get('/auth/page', (c) => {
  return c.text('You are authorized')
})
```

This header is 200 OK  (hono:acoolproject)
Authorization: Basic aG9ubzphY29vbHByb2plY3Q=

And This header is 500 Internal Server Error (removed  "a" after "Basic")
Authorization: Basic G9ubzphY29vbHByb2plY3Q=

It seems that an invalid value was passed to the Base64 decoding process( atob ), resulting in a 500 error.
https://github.com/honojs/hono/blob/1c44c6ec460142536217e508f8e6a4eac516a74b/src/utils/encode.ts#L16-L25

At any rate, I deal with it by checking if value is Base64 string before calling function of this line.
https://github.com/honojs/hono/blob/1c44c6ec460142536217e508f8e6a4eac516a74b/src/middleware/basic-auth/index.ts#L16

It is one idea, but there may be other good ideas.
```
const BASE64_REGEXP = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4})$/
const isBase64 = BASE64_REGEXP.exec(match[1])
if(!isBase64) {
  return undefined
}
```

**Comment by yusukebe** [comment]
Hi @Tomohiro-Honda !

Thank you for raising the issue.

This bug was hard to detect because our primary test environment does not throw an exception when `atob()` is used :(

So, I wrote a test for this in Deno and fixed the bug with `try`. You can see the details in PR #1122. If it's OK, I'll merge it into the main.

**Comment by Tomohiro-Honda** [comment]
Hi @yusukebe !
Thank you for your prompt response !
Fix using try-catch seems simple and safe.
