### ISSUE TITLE
Typing Handler returns

### ISSUE THREAD

**Issue by iliketowritecode** [honojs/hono#1136]
New to Hono and TypeScript here so this is probably a dumb question but... how do I define the return type on a specific app handler endpoint. For example:

```ts
const route = app
  // Get a todo by id
  .get('/:id', zValidator('param', getTodo), async (c) => {
    const { id } = c.req.valid('param')
    const db = getDB('read', c.get('geo'))
    const todo = await db
      .selectFrom('todo')
      .selectAll()
      .where('id', '=', id)
      .executeTakeFirst()
    if (!todo) {
      throw new ApiError(httpStatus.NOT_FOUND, 'Todo not found')
    }
    return c.jsonT<Todo>(todo)
  })
  // Update a todo by id
  .put(
    '/:id',
    zValidator('param', getTodo),
    zValidator('json', createTodo),
    async (c) => {
      const { id } = c.req.valid('param')
      const todo = c.req.valid('json')
      const db = getDB('write')
      const updated = await db
        .updateTable('todo')
        .set(todo)
        .where('id', '=', id)
        .executeTakeFirst()
      if (!updated.numUpdatedRows || Number(updated.numUpdatedRows) < 1) {
        throw new ApiError(httpStatus.NOT_FOUND, 'Todo not found')
      }
      return c.jsonT<Todo>({ id, ...todo })
    }
  )
```

As I don't really know TypeScript very well... I believe what i'm doing below is called `Explicitly` typing?
```ts
return c.jsonT<Todo>({ id, ...todo }) // Added <Todo> to validate my return
```

But I want the return type to be `Implicitly` inferred by the Handler (I think?)... so I can just do this below:
```ts
return c.jsonT({ id, ...todo })
```

Any assistance or guidance would be appreciated! :)

**Comment by yusukebe** [comment]
Hi @iliketowritecode,

You don't need to specify the types explicitly. Just write this:

```ts
return c.jsonT({ id, ...todo })
```

Here's the entire code:

```ts
const app = new Hono()

const route = app.put(
  '/:id',
  zValidator(
    'json',
    z.object({
      name: z.string(),
    })
  ),
  async (c) => {
    const { id } = c.req.param()
    const todo = c.req.valid('json')
    // ...
    return c.jsonT({ id, ...todo })
  }
)

const client = hc<typeof route>('/')
const res = await client[':id'].$put({
  json: {
    name: 'foo',
  },
  param: {
    id: '123',
  },
})

const data = await res.json()
```

Then it can be inferred:

<img width="557" alt="SS" src="https://github.com/honojs/hono/assets/10682/9cd5d59a-51e6-466e-9fdf-4edb76abe4d8">

**Comment by iliketowritecode** [comment]
@yusukebe the issue isn't inference here... what i'm trying to do is not allow unwanted fields in my return:
```ts
return c.jsonT({ id, ...todo, hacks: false }) // hacks field isn't on Todo so it shouldn't be able to be returned
```

Hence why I was asking if this is the recommended approach
```ts
return c.jsonT<Todo>({ id, ...todo })
```

Or if there's a better way of typing the return (Maybe a custom Handler type or something..idk) :)

**Comment by yusukebe** [comment]
Ah, yeah, I think your approach is good for a type checking.

```ts
return c.jsonT<Todo>({ id, ...todo })
```

**Comment by iliketowritecode** [comment]
Awesome! Thanks for your time @yusukebe 👍🏻

**Comment by OverHash** [comment]
Is there any thoughts on making this more ergonomic? This is particularly painful if you have various return points possible in your route handler. If one forgets to type a single `.json` call, then no immediate error is shown in the route handler file.

**Comment by ctsstc** [comment]
As a heads up to anyone stumbling upon this: `jsonT` has been deprecated, just use `json` now. I normally throw a `satisfies` on my return, but it still doesn't solve the problem that @OverHash brings up with multiple exit points. One could argue if you have that much logic/branching logic in your route handler it should be abstracted into a service instead which would define that contract and make it more easily testable and follow the SOLID principal. That's a semi-viable answer, but still not a great one to a problem at hand.

Introspection of the return type shows it's quite complex in structure with 22 overloads.
Ultimately returning a `JSONRespondReturn` which I'm not certain is exposed. 
Likely some helper needs to be exposed from the library to help facilitate this all.

**Comment by ctsstc** [comment]
I know this ticket is closed, so maybe this is a good jumping point: #4522 

(new comment so it tags/links properly)
