### ISSUE TITLE
REST Client VSCODE extension - error on request body

### ISSUE THREAD

**Issue by kuncung38** [honojs/hono#1155]
From what I have seen from example, getting the body from request is done by:
`const body = await c.req.json()`

If I use postman to fill the body, it works just fine
![image](https://github.com/honojs/hono/assets/99525837/67845a75-350a-452a-ba65-5565857f5611)
![image](https://github.com/honojs/hono/assets/99525837/337f1c94-de9c-41ed-ba59-fefdd14c035b)

But when I use REST Client, weird error happened
![image](https://github.com/honojs/hono/assets/99525837/9ac435f3-4e5d-4e8c-a4da-f66a46dd436e)

I'm using the latest bun as the runtime and latest hono by the way.

**Comment by yusukebe** [comment]
Hm, I think the body is invalid JSON strings. Check it again.

**Comment by kuncung38** [comment]
Turns out we just need 
`###` in the end of the request

![image](https://github.com/honojs/hono/assets/99525837/ba937f82-3584-4194-b56e-573dd79af572)

And it works just fine.
