### ISSUE TITLE
Allow using interface in `ctx.jsonT()`

### ISSUE THREAD

**Issue by ayame113** [honojs/hono#1158]
I'm using Hono's RPC mode.
I tried to pass the type of interface to the argument of `context.jsonT()`, but I get a type error.

```ts
interface Data {
  data: string;
}
function getData(): Data {
  return { data: "foo" };
}


import { Hono } from "$hono/mod.ts";
const app = new Hono();
const route = app
  .get(
    "/api",
    (c) => {
      const data = getData();
      return c.jsonT(data); // Type 'Data' is not assignable to type 'JSONObject'.
    },
  );
export type AppType = typeof route;
```

```
No overload matches this call.
  Overload 1 of 2, '(object: JSONValue, status?: number | undefined, headers?: HeaderRecord | undefined): TypedResponse<never>', gave the following error.
    Argument of type 'Data' is not assignable to parameter of type 'JSONValue'.
      Type 'Data' is not assignable to type 'JSONObject'.
        Index signature for type 'string' is missing in type 'Data'.  Overload 2 of 2, '(object: JSONValue, init?: ResponseInit | undefined): TypedResponse<never>', gave the following error.
    Argument of type 'Data' is not assignable to parameter of type 'JSONValue'.deno-ts(2769)
```

I know that changing `interface Data {}` to `type Data = {}` will eliminate the type error, but there are types provided by other libraries, so changing everything from `interface` to `type` is not realistic.
How about relaxing the restrictions on the JSONValue type here so that we can return a response of the type defined by the interface?
I think that types (such as `MyClass` / `Function`) that clearly cannot be serialized to JSON can be treated as type errors, and anything else can be considered valid as an argument.

**Comment by yusukebe** [comment]
Hi @ayame113, thank you for using Hono!

Since #939, we have added validation with `JSONValue` for the values returned from `jsonT()`. As mentioned in the PR, we don't allow certain types of objects, like `Date`, to be returned.

```ts
app.get('/hello', (c) => {
  return c.jsonT({
    message: 'Hello',
    datetime: new Date(), // This will cause an error!
  })
})
```

However, in your case, it seems that the `Data` type should be allowed. Although it's challenging to relax the type constraints, there's a workaround you can use by changing the type:

```ts
type InterfaceToType<T> = { [K in keyof T]: T[K] }

function getData(): InterfaceToType<Data> {
  return { data: 'foo' }
}
```

How about this approach?

**Comment by ayame113** [comment]
@yusukebe Thank you for your reply!

The solution you suggested worked. thank you!
(In my case, I had nested interfaces, so I had to recursively convert to type as below.)

```ts
type InterfaceToType<T> = T extends Function ? T : { [K in keyof T]: InterfaceToType<T[K]> };

interface Result<T> {
  value: T
};
interface Data {
  data: string;
}
const data: InterfaceToType<Result<Data>> = getData(); // This works fine!
```

By the way, if I do this, the type used on the client side will also be the type after conversion from interface to type.
Would it be possible to use `InterfaceToType` on the Hono side to get around this limitation?
For example, can you do something like:
```ts
class Context {
  jsonT = <T>(
    object: InterfaceToType<T> extends JSONValue ? T : JSONValue,
    ...
  ): TypedResponse<
    InterfaceToType<T> extends JSONValue
      ? (JSONValue extends InterfaceToType<T> ? never : T)
      : never
  > => {
    ...
  };
}
```

**Comment by yusukebe** [comment]
Hi @ayame113 !

Thank you for your suggestion.

So, you're suggesting that currently it looks like this:

<img width="351" alt="SS" src="https://github.com/honojs/hono/assets/10682/cb990281-c02a-4e1c-971f-19578f68be28">

But with your proposed change, it would look like this:

<img width="311" alt="SS" src="https://github.com/honojs/hono/assets/10682/9792ddf6-03f1-4d35-a45b-29045bcd310b">

Is that correct?

If so, I think it's a good change. Please create a PR!
