### ISSUE TITLE
[aws-lambda] probrem on implicit conversion binary to base64

### ISSUE THREAD

**Issue by Kanahiro** [honojs/hono#1160]
Thank you for the nice framework!

I'm trying hono in AWS Lambda and found a small issue in conversion to base64.

https://github.com/honojs/hono/blob/main/src/adapter/aws-lambda/handler.ts

It seems that return value is automatically converted into base64 when content-type means binary type.
The conversion seems to support only `ReadableStream` but in my usecase need to response from `ArrayBuffer` like this (using node-fetch).

```javascript
const data = await fetch(
    'https://pass/to/image.png'
).then((res) => res.arrayBuffer());
c.status(200);
c.header('Content-Type', 'image/png');
return c.body(data);
```

However, this snipet doesn't work, error occurs in the conversion. We need other conversion like:

```javascript
function base64Encode(buf: ArrayBuffer) {
    let string = '';
    new Uint8Array(buf).forEach((byte) => {
        string += String.fromCharCode(byte);
    });
    return btoa(string);
}
```

In my opinion we would have some options.

1. modify current function to support ArrayBuffer: https://github.com/honojs/hono/blob/main/src/adapter/aws-lambda/handler.ts#L143
    a. but not only ArrayBuffer needs support: e.g.) Buffer
2. pass base64 string to res.body and skip conversion to base64 in handle().
    a. may able to skip when content-type is binary and res.body is String
    b. or quit automatic conversion. 

How do you think?

**Comment by yusukebe** [comment]
Hi @Kanahiro 

Thank you for raising the issue.

Perhaps we can solve this in a simpler way.

My suggestion is to handle the binary using `res.arrayBuffer()`, and then pass the resulting buffer to the `encodeBase64()` method from `utils/encode`:

```ts
import { encodeBase64 } from '../../utils/encode'

//...

const buffer = await res.arrayBuffer()
const base64String = encodeBase64(buffer)
// ... 
```

However, I can't confirm if this works correctly in my AWS environment. If you can, please try the above method and share the results.

**Comment by Kanahiro** [comment]
Thanks you for advice, `encodeBase64()` works good for ArrayBuffer and Buffer.

Then, I'd like to make endpoints like following

```typescript
app.get('/binary', async (c) => {
    const res = await fetch('path/to/resource')
    const buf = await res.arrayBuffer();

    c.status(200);
    c.header('Content-Type', 'image/png'); // this occurs implicit conversion to base64
    return c.body(buf);
});
```

This doesn't work in current hono with following error.

```
    InvalidCharacterError: Invalid character

      153 |   }
      154 |
    > 155 |   return btoa(string)
          |          ^
      156 | }
      157 |
      158 | export const isContentTypeBinary = (contentType: string) => {

      at fromReadableToString (../../src/adapter/aws-lambda/handler.ts:155:10)
      at createResult (../../src/adapter/aws-lambda/handler.ts:75:34)
      at Object.<anonymous> (index.test.ts:74:22)
```

The method `fromReadableToString` doesn't seem to support `ArrayBufferLike`:
https://github.com/honojs/hono/blob/main/src/adapter/aws-lambda/handler.ts#L143

and we cannot `return c.body(encodeBase64(buf))` because this string encodeBase64(buf) will be encoded to base64 (we want to convert buf to base64).

So, I am thinking there are two options:

> 1. modify the encoding method to support ArrayBufferLike
2. pass base64-encoded string to res.body with a option to skip base64 conversion even when content-type means binary.

**Comment by yusukebe** [comment]
@Kanahiro 

How about replacing it with `fromReadableToString()`?

```diff
--- a/src/adapter/aws-lambda/handler.ts
+++ b/src/adapter/aws-lambda/handler.ts
@@ -72,7 +72,13 @@ const createResult = async (res: Response): Promise<APIGatewayProxyResult> => {
   const contentType = res.headers.get('content-type')
   const isBase64Encoded = contentType && isContentTypeBinary(contentType) ? true : false

-  const body = isBase64Encoded ? await fromReadableToString(res) : await res.text()
+  let body
+  if (isBase64Encoded) {
+    const buffer = await res.arrayBuffer()
+    body = encodeBase64(buffer)
+  } else {
+    body = await res.text()
+  }
```

**Comment by Kanahiro** [comment]
Thanks, looks good.
I wrote draft-PR #1165 and will add tests for some cases uncoverd yet.
