### ISSUE TITLE
`setCookie`'s `signed` option is not being used

### ISSUE THREAD

**Issue by dnlsandiego** [honojs/hono#1164]
Hey folks! I noticed that `setCookie` has a `signed` option and I assumed it was for getting the cookie value signed before it's set as a header. But after looking into [setCookie](https://github.com/honojs/hono/blob/main/src/middleware/cookie/index.ts) and the [serialize](https://github.com/honojs/hono/blob/main/src/utils/cookie.ts#L25) util it uses, they are not reading or doing anything for the `signed` option.

I suggest that setCookie should get updated to sign cookies if that option is set as it's a core best practice for protecting cookies from being tampered. [cookie-signature](https://github.com/tj/node-cookie-signature) is a good library to do so. I can submit a PR if this makes sense.

**Comment by yusukebe** [comment]
Hi @dnlsandiego!

You're absolutely right! It's defined but not used 😇

> I suggest that setCookie should get updated to sign cookies if that option is set as it's a core best practice for protecting cookies from being tampered.

That makes sense. It should be implemented.

> I can submit a PR if this makes sense.

Yes, please! But there's one thing to consider. Hono is built using only Web Standard APIs. So we should not use external libraries. "cookie-signature" seems like a good library but we can't use it. So, you'll need to write the code from scratch or port it from that library.

Anyway, thanks for creating the issue.

**Comment by chrisbrocklesby** [comment]
Just notice the signed cookie issue myself (Came here to report the issue)... Would love to use signed cookies with Hono. Thanks.

**Comment by chrisbrocklesby** [comment]
Hey Guys,
Any news or joy with this...

Also, I don't know if this would help but this seems to be a great library to port or base from : https://www.npmjs.com/package/sign

Thanks,
Chris.

**Comment by yusukebe** [comment]
Hi @chrisbrocklesby  !

As of now, we haven't made any progress on this issue. However, you're right that we can use the library you shared as a reference. When I get the chance, I'll tackle this issue. Until then, any contributions are always welcome :)

**Comment by yusukebe** [comment]
Closed!
