### ISSUE TITLE
Create constant response objects without using Context

### ISSUE THREAD

**Issue by Mahamed-Belkheir** [honojs/hono#1171]
I'm trying to define some constant responses for common API responses e.g (created successfully, no permissions, etc).

there doesn't seem to be a not-context-bound .json, .body method alternatives, is that on purpose? I know they return the default node Response interface, but building my own object to Response seems a lot of repeated code that is already done by Hono in the Context object.

**Comment by yusukebe** [comment]
Hi @Mahamed-Belkheir,

> there doesn't seem to be a not-context-bound .json, .body method alternatives, is that on purpose?

Yes, it is on purpose. Hono should not provide them. If you want them, write that yourself.

**Comment by Mahamed-Belkheir** [comment]
What are the cons of refactoring those methods to not be context bound? the context methods would use them, and you'd have the option to define constant responses

**Comment by yusukebe** [comment]
That's outside of Hono's scope. We aim to keep our codebase as lean and focused as possible, so we won't be incorporating this feature.

**Comment by Mahamed-Belkheir** [comment]
I kind of disagree, this is all stuff hono is already doing, it just couples it to the context object for whatever reason, I don't see how this would be out of focus or introduce more code to simply abstract into another class exposed from Hono directly.

Looking at https://github.com/honojs/hono/blob/main/src/context.ts I don't see what part of creating the response actually relies on the current context aside from reusing previously set headers/using JSON preprocessors. what we could do is simply move the response creation logic to another file, and have context class reference that + header setting / json pre.

If you're interested in how it would look, I can contribute a PR for this.

**Comment by yusukebe** [comment]
@Mahamed-Belkheir 

I understand what you mean, but indeed, I can't envision the implementation. So, could you create a PR? Even though it may not be merged immediately, it would be helpful for further discussion. Thanks!

**Comment by Mahamed-Belkheir** [comment]
Finally got time to work on this, and I now understand why you were confused, the implementation for context and response are quite coupled together.

I'm currently confused by the existence of headers and prepared headers, why the distinct difference between the two? and why do we need them, rather than only using the built in response's header object? it seems we already merge headers when using the _res setter. so it's not like we need this to keep headers between different response objects.

**Comment by Mahamed-Belkheir** [comment]
What I had in mind was different to this, but due to all the lazy loading of header objects, I thought inheritance in this case would be the cleaner/closer to the original implementation.

Here's the draft PR: #1260  let me know what you think

**Comment by yusukebe** [comment]
> I'm currently confused by the existence of headers and prepared headers, why the distinct difference between the two? and why do we need them, rather than only using the built in response's header object?

The reason we have both the Header instance and the prepared header object is for performance. Using an object instead of a Header instance is faster. Therefore, we try to use the object instead of the Header instance as much as possible.

**Comment by Mahamed-Belkheir** [comment]
Since the PR was rejected I'll be closing this, can't think of another approach that wouldn't add more code
