### ISSUE TITLE
Form validator receives empty value on Bun

### ISSUE THREAD

**Issue by spiffytech** [honojs/hono#1179]
I've tested the same code with Node and there's no issue.

Under bun, `req.formData()` returns a promise, which Hono doesn't `await`. I don't know why the promise has a `forEach()` method, that seems pretty weird, but it performs zero iterations.

```ts
import { Hono } from "hono";
import { validator } from "hono/validator";

const app = new Hono();

app.post(
  "/",
  validator("form", (value, ctx) => console.log(value)),
  (c) => c.text("Hello Hono!")
);

export default app
```

```
$ curl 'http://localhost:3000' -X POST  -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'foo=bar'
```

Result: 
```
{}
```

**Comment by yusukebe** [comment]
Hi @spiffytech !

This is a known issue. It's caused by the cloned request object not working correctly on Bun.

https://github.com/honojs/middleware/issues/81#issuecomment-1509457656

**Comment by yusukebe** [comment]
This was fixed!
