### ISSUE TITLE
Support AWS Function URL Streaming

### ISSUE THREAD

**Issue by RichiCoder1** [honojs/hono#1183]
AWS Lambda recently added support for Response Streaming (https://docs.aws.amazon.com/lambda/latest/dg/configuration-response-streaming.html).

This is a much more natural fit for Hono as most environments it supports do response streaming by default. The catches are:

1. It uses a magic global "awslambda.streamifyResponse" to handle the streamification
2. It uses NodeJS writable instead of web streams

**Comment by yusukebe** [comment]
Hi @RichiCoder1 

I'm aware of that and I agree with the idea of supporting streaming for AWS Lambda in Hono. If I find the time, I'll attempt to implement it. However, I must admit that I'm not very familiar with AWS. Hence, I hope that someone else might undertake this task.

**Comment by yusukebe** [comment]
Hi @watany-dev 

Is this issue resolved by recent changes around streaming things?

**Comment by watany-dev** [comment]
@yusukebe 

Yes, here are the next development targets!

**Comment by yusukebe** [comment]
Hi @watany-dev 

Can we close this issue?

**Comment by watany-dev** [comment]
@yusukebe 
Yes, this feature is working successfully in v3.10.0.

**Comment by yusukebe** [comment]
Okay, closing. Thanks a lot!
