### ISSUE TITLE
TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by aniruddhnishad** [honojs/hono#1185]
using deno, deno-postgres and neontech database;

when i trying to c.json(result)  where "result" is the rows from database

**Comment by yusukebe** [comment]
Hi @aniruddhnishad !

`c.json()` simply uses `JSON.stringify()`, so whether the "result" is parsed or not depends on `JSON.stringify()`. Therefore, I recommend trying it out with `JSON.stringify()` directly before using `c.json()` in your Hono application.

**Comment by liuhuapiaoyuan** [comment]
Can't users be allowed to customize serialization?

**Comment by vanya2h** [comment]
@liuhuapiaoyuan 
> Can't users be allowed to customize serialization?

I guess the reason because c.json() means content-type is must be json compatible because some client might not know how to properly deserialize your custom serialized json.
