### ISSUE TITLE
AWS Lambda: No access to custom request context

### ISSUE THREAD

**Issue by denisw** [honojs/hono#1197]
AWS API Gateway allows adding custom request context values, such as [through lambda authorizers](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-output.html). However, Hono's `aws-lambda` authorizer throws away all context values other than the ones it needs to create the `Request` passed to the app.

It would be great if there were some way for the adapter to preserve and make available the custom context somehow - perhaps by offering a `getLambdaContext` function from the `'hono/aws-lambda'` module.

**Comment by yusukebe** [comment]
@watany-dev

Has this issue been resolved?

**Comment by yusukebe** [comment]
Hi @watany-dev!

We should implement this using pattern "1" as shown below:

```ts
const context = getLambdaContext(c);
```

In our policy, we prefer pattern "1" over "2". For example, [Cookie Middleware](https://hono.dev/middleware/builtin/cookie) (which will be renamed Cookie Helper) is used as follows:

```ts
app.get('/cookie', (c) => {
  const yummyCookie = getCookie(c, 'yummy_cookie');
  // ...
  setCookie(c, 'delicious_cookie', 'macha');
  deleteCookie(c, 'delicious_cookie');
  // ...
})
```

Thanks!

**Comment by watany-dev** [comment]
Hi @watany-dev!

We should implement this using pattern "1" as shown below:

const context = getLambdaContext(c);
In our policy, we prefer pattern "1" over "2". For example, Cookie Middleware (which will be renamed Cookie Helper) is used as follows:

app.get('/cookie', (c) => {
  const yummyCookie = getCookie(c, 'yummy_cookie');
  // ...
  setCookie(c, 'delicious_cookie', 'macha');
  deleteCookie(c, 'delicious_cookie');
  // ...
})
Thanks!

**Comment by watany-dev** [comment]
You're welcome! I'll try making the improvements based on pattern "1."
