### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite deno-ts(2589)

### ISSUE THREAD

**Issue by fro-profesional** [honojs/hono#1216]
<img width="1238" alt="Screenshot 2023-07-01 at 23 41 42" src="https://github.com/honojs/hono/assets/97365498/53c82565-497d-409b-9b17-3d874fe560f2">

**Comment by yusukebe** [comment]
This issue might be due to a mismatch between `hono` and `zod-validator`. As a possible solution, you could try using the `npm:` specifier as follows:

```ts
import { Hono } from 'npm:hono'
import { zValidator } from 'npm:@hono/zod-validator'
```

**Comment by jtmueller** [comment]
@yusukebe I don't find that getting both `hono` and `zod-validator` from npm makes any difference. Nor does getting zod-validator from esm.sh.

@hectorAguero I'm not finding that even version 0.1.3 of zod-validator avoids this error. 😢

**Comment by yusukebe** [comment]
This code will work correctly:

```ts
import { Hono } from 'npm:hono'
import { zValidator } from 'npm:@hono/zod-validator'
import { z } from 'npm:zod'

const app = new Hono()

const schema = z.object({
  foo: z.string()
})

app.get('/', zValidator('query', schema), (c) => {
  return c.json(c.req.valid('query'))
})

Deno.serve(app.fetch)
```

If errors still occur, try clearing the cache:

```txt
deno cache --reload hello.ts
```

Or you may need to specify the version as the latest version.

**Comment by hectorAguero** [comment]
Just to say, I'm having the same problem with @hono/zod-openapi the linter give me an error, but the code still run, if I switch to npm import the error is not showing

The error is `No overload matches this call`

**Both type of imports works in Deno Deploy.**

```ts
import { OpenAPIHono, z, createRoute } from 'https://esm.sh/@hono/zod-openapi@0.9.5';
// import { OpenAPIHono, z, createRoute } from 'npm:@hono/zod-openapi';

import { prettyJSON } from 'https://deno.land/x/hono@v3.11.9/middleware.ts';
//import { prettyJSON } from 'npm:hono/pretty-json';

const app = new OpenAPIHono();

app.use('/doc/*', prettyJSON())

const UserSchema = z
  .object({
    id: z.string().openapi({
      example: '123',
    }),
    name: z.string().openapi({
      example: 'John Doe',
    }),
    age: z.number().openapi({
      example: 42,
    }),
  })
  .openapi('User')

const sampleRoute = createRoute({
  method: 'get',
  path: '',
  responses: {
    200: {
      content: {
        'application/json': {
          schema: UserSchema,
        },

      },
      description: 'Retrieve user',
    },

  },

});

app.openapi(sampleRoute, async (c) => {
  //fake await
  const user = await Promise.resolve({
    id: '123',
    name: 'John Doe',
    age: 42,
  });
  console.log(user)
  const { id, name, age } = user;
  return c.json({
    id: id,
    name: name,
    age: age,
  })
});

// The OpenAPI documentation will be available at /doc
app.doc('/doc', {
  openapi: '3.0.0',
  info: {
    version: '1.0.0',
    title: 'My API',
  },
})

Deno.serve(app.fetch)
```

**Comment by yusukebe** [comment]
@fro-profesional 

Mixing `esm.sh` and `deno.land` will result in a type error because each refers to a different `hono`. This is unavoidable due to the limitations of TypeScript.

**Comment by jyotman** [comment]
@yusukebe are we open to adding support for deno for zod-validator?

**Comment by yusukebe** [comment]
@jyotman 

Zod Validator is supporting Deno.

**Comment by lisez** [comment]
My workaround in Deno:
1. copy source code from `packages/zod-validator/src/index.ts` in `honojs/middleware` repo.
2. modify `import` as below:

from:
```typescript
import type { Context, MiddlewareHandler, Env, ValidationTargets, TypedResponse, Input } from 'hono'
import { validator } from 'hono/validator'
import type { z, ZodSchema, ZodError } from 'zod'
```

to:
```typescript
import type {
  Env,
  Input,
  MiddlewareHandler,
  TypedResponse,
  ValidationTargets,
} from 'hono/types.ts';
import type { Context } from 'hono/context.ts';
import type { ZodSchema } from 'zod/types.ts';
import type { z, ZodError } from 'zod/mod.ts';
import { validator } from 'hono/validator/index.ts';
```

**Comment by KiritaniAyaka** [comment]
It is also necessary to use `zod` by `npm:` specifier

**Comment by fro-profesional** [comment]
Yeah, making zod external with esm.sh or using npm fixes the issue, thanks!

**Comment by vidz1979** [comment]
Related: https://github.com/StefanTerdell/zod-to-json-schema/issues/69#issuecomment-1572954056
