### ISSUE TITLE
Idea: Use `AsyncLocalStorage` for context

### ISSUE THREAD

**Issue by jokull** [honojs/hono#1219]
Could be opt in. 

https://developers.cloudflare.com/workers/runtime-apis/nodejs/asynclocalstorage/

If the Hono context object would be an AsyncLocalStorage you could retrieve whatever is inside it *without passing `c` around*. If you have a function somewhere and you want to, for example, elegantly handle a failure but log the error to Sentry, you would have to pass `c` potentially very deep down into you stack.

**Comment by Mahamed-Belkheir** [comment]
Can't you do this with a middleware already?
```ts
const ctxStore = new AsyncLocalStorage<Context>();

app.use((ctx, next) => {
   ctxStore.run(ctx, next);
})
```
or something similar

**Comment by jokull** [comment]
Let me try. I'll re-open if needed.

**Comment by banjo** [comment]
Any news on this? 

I tried the example but it gave this error:

```
Error: Context is not finalized. You may forget returning Response object or `await next()`
```

**Comment by LorisSigrist** [comment]
Also tried it + a few variations and got the same error. Being able to provide a "context" for a request via AsyncLocalStorage would be very useful for using [ParaglideJS](https://inlang.com/m/gerre34r/library-inlang-paraglideJs) with Hono. 

Can this be reopened?

**Comment by yusukebe** [comment]
Using AsyncLocalStorge is a good idea. You can see the example middleware using it:

https://github.com/yusukebe/async-local-storage-middleware

Either way, we generally do not need it since we have a context.

**Comment by marceloverdijk** [comment]
@yusukebe as my app is growing I noticed that I'm passing the `c` from the handle to other functions, multiple layer deeps.

```
import { Hono } from 'hono'

const app = new Hono<AppType>()

app.get('/', (ctx) => {
  ..
  doSomething(c, foo, bar) // which calls then another function passing the c as well
  doSomethingElse(c)
  ..
})

export default app
```

I've looked at the https://github.com/yusukebe/async-local-storage-middleware example, 
but I'm wondering if it would be possible to create a middleware that "mimics" the whole `c` by putting it in the `AsyncLocalStorage`?

And that in other files in the app we could do an import like:

```
import { c } from '..'
```

and use it similar as the `c` argument from the handler:
```
c.env.KV_NAMESPACE
c.var.requestId
```

This would give a consistent way of accessing the context anywhere.

**Comment by yusukebe** [comment]
@marceloverdijk 

I can't say whether we can do it immediately, but it's a good idea. It's enough to use Hono's `c` in almost all cases. But it's alright that there is another way to access `c` globally.

**Comment by marceloverdijk** [comment]
Thx @yusukebe !

FWIW I'm using this currently:

`ctx.ts`:
```
import { AsyncLocalStorage } from 'node:async_hooks';
import { createMiddleware } from 'hono/factory';
import { Context } from 'hono';
import { AppEnv } from '@/env';

type Callback = (ctx: Context<AppEnv>) => Context<AppEnv>;

const asyncLocalStorage = new AsyncLocalStorage<Context<AppEnv>>();

export const setCtx = (callback: Callback) =>
  createMiddleware(async (ctx, next) => {
    const obj = callback(ctx);
    return asyncLocalStorage.run(obj, next);
  });

export const getCtx = () => {
  return asyncLocalStorage.getStore() as Context<AppEnv>;
};

export const ctx = new Proxy(
  {},
  {
    get: (_, prop) => {
      const context = getCtx();
      return context ? context[prop as keyof Context<AppEnv>] : undefined;
    },
  },
) as Context<AppEnv>;
```
Note that is currently tight to my custom `AppEnv`.

`index.ts`:
```
import { ctx, setCtx } from '@/ctx';

const app = new Hono<AppEnv>();

app.use(setCtx((ctx) => ctx));
app.use(requestId());
app.use(
  logger((message: string, ...rest: string[]) => {
    ctx.var.logger.debug(`${message.trim()}`, ...rest);
  }),
);
app.use(async (ctx: Context<AppEnv>, next) => {
  ctx.set('logger', createPinoLogger());
  // other c.set variables.
  await next();
});
```
Note that the logger middleware is already using the "global" ctx as the `PrintFunc` has no access to the context directly.

`other.ts`:
```
import { ctx } from '@/ctx';

export const doSomething() = () => {
  // we can now access the global ctx
  c.var.logger.debug('The request id = %s', c.var.requestId);
}
```

If you see some issues or improvements I appreciate your feedback.

As you mentioned
> But it's alright that there is another way to access c globally

should we re-open this issue or create a new issue to "Access c globally" so I can track the progress?

**Comment by marceloverdijk** [comment]
@yusukebe 
I went a bit further and extracted the code above in a standalone `context-holder` middleware (inspired on https://github.com/yusukebe/async-local-storage-middleware).

`/middleware/context-holder/index.ts`:
```
import { AsyncLocalStorage } from 'node:async_hooks';
import { createMiddleware } from 'hono/factory';
import { Context, Env } from 'hono';

const asyncLocalStorage = new AsyncLocalStorage<Context>();

export const contextHolder = <E extends Env = Env>() => {
  return {
    setContext: createMiddleware(async (c, next) => {
      return asyncLocalStorage.run(c, next);
    }),
    getContext: () => {
      const store = asyncLocalStorage.getStore() as Context<E>;
      return store;
    },
  };
};

export const getContext = <E extends Env = Env>() => {
  return contextHolder<E>().getContext();
};
```

This can be used like:

```
import { contextHolder } from '@/middleware/context-holder';

const app = new Hono<AppEnv>();

const { setContext, getContext } = contextHolder<AppEnv>();

app.use(setContext);
app.use(requestId());

app.use(async (c: Context<AppEnv>, next) => {
  const city = (c.req.raw.cf?.city ?? 'nowhere') as string;
  c.set('city', city);
  await next();
});

app.get('/', async (c) => {
  return c.json(`${getContext().var.requestId} is from ${getContext().var.city}`)
})
```

or in another file:

```
import { getContext } from '@/middleware/context-holder';

export const doSomething() = () => {
  // we can now access the global context
  const requestId = getContext<AppEnv>().var.requestId;
  console.log(`requestId = ${requestId}`;
}
```

or

```
import { contextHolder } from '@/middleware/context-holder';

const { getContext } = contextHolder<AppEnv>();

export const doSomething() = () => {
  // we can now access the global context
  const requestId = getContext().var.requestId;
  console.log(`requestId = ${requestId}`;
}
```

`getContext<AppEnv>()` might still be a bit verbose ;-) but we need the type.

In my own project I created a `ctx.ts` helper file with:

```
import { getContext } from '@/middleware/context-holder';

export const c = new Proxy(
  {},
  {
    get: (_, prop) => {
      const context = getContext();
      return context ? context[prop as keyof Context<AppEnv>] : undefined;
    },
  },
) as Context<AppEnv>;
```

and it allows me to use:

```
import { c } from '@/ctx';

export const doSomething() = () => {
  // we can now access the global context
  const requestId = c.var.requestId;
  console.log(`requestId = ${requestId}`;
}
```

This works quite well so far.

@yusukebe Would you be interested in a PR that provides the above `context-holder` middleware? (or let me know if you prefer another name)

**Comment by yusukebe** [comment]
@marceloverdijk Looks good!

I remember we did a similar thing in HonoX: https://github.com/honojs/honox/pull/168

**Comment by yusukebe** [comment]
cc: @usualoma If you have any ideas, please share them.

**Comment by yusukebe** [comment]
About naming, I prefer `context-storage` because it uses `AsyncLocalStorage`.

**Comment by marceloverdijk** [comment]
> @marceloverdijk
> 
> Anyway, can you create a PR? And let's discuss it on the PR!

Sure, I will do that later today.

**Comment by marceloverdijk** [comment]
PR created to further discuss: https://github.com/honojs/hono/pull/3335
