### ISSUE TITLE
wrangler 3.1.2 with `local_protocol = "https"` errors

### ISSUE THREAD

**Issue by imri29** [honojs/hono#1227]
Just installed wrangler 3.1.2 so i could use local https, but i'm getting these errors:

```workerd/util/symbolizer.c++:95: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
kj/compat/tls.c++:501: error: error accepting tls connection; kj::mv(e) = kj/compat/tls.c++:74: failed: OpenSSL error; message = error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST
stack: 1057cd25f 1057d14ff 1057d1a03 1057d1f88 1057da250 1057db568
kj/compat/tls.c++:501: error: error accepting tls connection; kj::mv(e) = kj/compat/tls.c++:74: failed: OpenSSL error; message = error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST
stack: 1057cd25f 1057d14ff 1057d1a03 1057d1f88 1057da250 1057db568
kj/compat/tls.c++:501: error: error accepting tls connection; kj::mv(e) = kj/compat/tls.c++:74: failed: OpenSSL error; message = error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST
stack: 1057cd25f 1057d14ff 1057d1a03 1057d1f88 1057da250 1057db568```

Is this something Hono needs to support for?

**Comment by yusukebe** [comment]
Hi @imri29 

I think this is not a Hono matter. You can find the similar issues or create your issue on this repo:

* https://github.com/cloudflare/workers-sdk

**Comment by imri29** [comment]
thanks @yusukebe, will try there. closing.
