### ISSUE TITLE
Cache Middleware not compatible with middleware modifying headers

### ISSUE THREAD

**Issue by KeKs0r** [honojs/hono#1231]
I just upgraded to hono 3 and are observing that cached responses lead to errors when used with other middleware modifying response headers.
Affected Middlewares:
- poweredBy
- Cors
- etag
- .....

This error is also reported and the potential solution in this comment:
https://github.com/honojs/hono/issues/820#issuecomment-1427331886

However in #820 (the original issue) I think the solution is actually to do a `res.clone()` in user code.
In the issue I am reporting here, I want to point out that it is vanilla middleware that does not work well together. I think we should probably clone the response that is returned from hono cache middleware, to prevent this category of options. Or maybe give the hono cache middleware an option to configure response cloning.

Update:
I actually saw there is a PR that addresses the same issue:
https://github.com/honojs/hono/pull/686

**Comment by yusukebe** [comment]
Okay, I'll see it later.

**Comment by yusukebe** [comment]
Hi @KeKs0r 

I've create the PR #1232 based on #686. This will resolve this issue.

**Comment by yusukebe** [comment]
This may be resolved by #1232
