### ISSUE TITLE
Consider export `utils`

### ISSUE THREAD

**Issue by katopz** [honojs/hono#1233]
`utils` have ton of cool things but I can't use it elsewhere.
It would be nice if `Hono` export it for external use somehow.

So I can use it like this.
```js
import { utils } from 'hono'
```

**Comment by yusukebe** [comment]
Hi @katopz 

While there is a possibility of sudden breaking changes due to its internal use, you can import it from `hono/utils/*`:

```ts
import { sha256 } from 'hono/utils/crypto'
```

**Comment by katopz** [comment]
Cool thanks! it work 👍
