### ISSUE TITLE
Unexpected value in `c.req.url` when running locally with wildcard routes in `wrangler.toml`

### ISSUE THREAD

**Issue by cd-slash** [honojs/hono#1239]
I have defined some simple workers routes in my `wrangler.toml` config:
```ts
routes = [
	{ pattern = "*/signup", zone_name = "mydomain.com" },
        // other routes
]
```
When I deploy to Cloudflare, this works as expected: 
```ts
console.log("c.req.url: ", c.req.url)
const domain = new URL(c.req.url).hostname
console.log("domain: ", domain)
```
```
c.req.url:  http://mydomain.com/signup
domain:  mydomain.com
```
When developing locally, this does something strange:
```
c.req.url:  http://signup/signup
domain:  signup
```
This seems to be returning the path parameter in place of the hostname.

For reference, when I remove the routes definition from `wrangler.toml` the return is what I would expect:
```
c.req.url:  http://127.0.0.1:8787/signup
domain:  127.0.0.1
```

Is this expected behavior?

**Comment by yusukebe** [comment]
@cd-slash 

I think this is not a Hono matter. You can also try it without Hono:

```ts
export default {
  fetch: (req: Request) => {
    console.log('req.url: ', req.url)
    const domain = new URL(req.url).hostname
    console.log('domain: ', domain)
    return new Response('Foo')
  },
}
```

**Comment by Codinak** [comment]
> When developing locally, this does something strange:
c.req.url:  http://signup/signup
domain:  signup

What exactly is strange about this? It is the domain of the url. I don't see any different behavior between both examples.

**Comment by cd-slash** [comment]
Agreed @yusukebe - I have opened [this issue](https://github.com/cloudflare/workers-sdk/issues/3635#issuecomment-1653337360) in the Cloudflare repo, though there's some debate about whether this is actually expected behavior.

This issue should be closed as it's not a Hono problem.
