### ISSUE TITLE
Middlewares on a nested root route isn't executed

### ISSUE THREAD

**Issue by lacolaco** [honojs/hono#1240]
In my app, a middleware isn't executed on a nested "root" route.

my routes

```
  const userRoutes = new Hono<UserRouteContext>();
  userRoutes.use('*', setUserMiddleware());   <---- this is not called on "/users/:id" route
  userRoutes.get('/', handleGetPerson);
  userRoutes.get('/inbox', handleGetInbox);
  userRoutes.post('/inbox', handlePostInbox);
  userRoutes.get('/outbox', handleGetOutbox);
  userRoutes.get('/followers', handleGetFollowers);
  userRoutes.get('/following', handleGetFollowing);
  app.route('/users/:id', userRoutes);
```

`app.showRoutes()`

```
ALL       /users/:id/*         <---- this is not called on "/users/:id" route
GET       /users/:id
GET       /users/:id/inbox
POST      /users/:id/inbox
GET       /users/:id/outbox
GET       /users/:id/followers
GET       /users/:id/following
```

- on `/users/foobar`, the middleware is **NOT** executed properly.
- on `/users/foobar/inbox` and other non-root handlers in the nested router, the middleware is executed properly.

Question

- Is this by design?

**Comment by lacolaco** [comment]
`userRoutes.use('', setUserMiddleware());` works well, but I'm not sure this is a proper use.

```
userRoutes.use('', setUserMiddleware());
```

```
ALL       /users/:id
GET       /users/:id
GET       /users/:id/inbox
POST      /users/:id/inbox
POST      /users/:id/inbox
GET       /users/:id/outbox
GET       /users/:id/followers
GET       /users/:id/following
``

**Comment by yusukebe** [comment]
Hi @lacolaco !

The route `/users/:id/*` should match `/users/foobar`:

```ts
// Routing:
ALL       /users/:id/*

// Request:
GET /users/foobar => Matched!
```

Using my minimal code to reproduce it, it works well:

```ts
const userRoutes = new Hono()
userRoutes.use('*', async (c, next) => {
  console.log('userRoutes *')
  await next()
})
userRoutes.get('/', (c) => c.text('userRoutes /'))

const app = new Hono()
app.route('/users/:id', userRoutes)
```

<img width="447" alt="SS" src="https://github.com/honojs/hono/assets/10682/e776b8e8-b5fd-401b-908c-0a73d378c705">

In your case, if accessing `/users/foobar`, `setUserMiddleware()` should be executed. But, as you said it will not be executed, that's weird. Could you verify the above code and your code again?

**Comment by lacolaco** [comment]
@yusukebe Thank you for your support. I've found a minimal app can work as well as I expected, too. But my app doesn't yet.

And I've also found a trigger for this problem. I'm adding another route, `/admin/users/:hostname/:username`. If I remove this route, `/users/:id/*` middleware works again.

```
export function getUserRoutes () {
  const userRoutes = new Hono();
  userRoutes.use('*', ...);
  userRoutes.get('/, async (c) => {
    ...
  });

  return userRoutes;
};

export function getAdminRoutes () {
  const adminRoutes = new Hono();
  adminRoutes.get('/users/:hostname/:username', async (c) => {
    ...
  });

  return adminRoutes;
};

app.routes("/users/:id", getUserRoutes());
app.routes("/admin", getAdminRoutes())
```

```
ALL       /users/:id/*
GET       /users/:id
GET       /admin/users/:hostname/:username
```

**Comment by lacolaco** [comment]
@yusukebe Thank you for your support. I could confirm a minimal app works well as I expected, too. But my app doesn't yet.

I've found what triggers that. This is a minimal situation of my app that has the problem.

```
ALL       /users/:id/*    <-- middleware I want to execute
GET       /users/:id   <-- route I want to visit
GET       /admin/users/:hostname/:username    <-- (a)
GET       /admin/users/list                                    <-- (b)
```

If I remove either route (a) or (b), `/users/:id/*` middleware is executed on `GET /users/foobar`. That problem is happening only when both (a) and (b) exist.

**Comment by yusukebe** [comment]
Hi @lacolaco!

Thank you for the detailed explanation. I now understand that there are inconsistencies in the routers. My previous statement:

> The route `/users/:id/*` should match `/users/foobar`

May have been incorrect, given that the results of handling `/users/:id/*` vary between different routers used in Hono. We will start discussions on the specification and how we implement them in #1243. Please wait until this issue is resolved. Thanks again!

**Comment by yusukebe** [comment]
Hi @lacolaco !

I've released v3.3.2 which includes the fix for issue #1243. Starting with this release, the routing results should be as you expected. Could you please check it?

**Comment by lacolaco** [comment]
Sorry for the late reply! To be honest, I can't immediately confirm that my old issue has been resolved in the new version, as I already rewrote the app to avoid that behavior. If you think it is better than it was before you found the bug, please close it as resolved!

**Comment by baygeldin** [comment]
@yusukebe I think the bug is still present in the latest version (I'm on `3.4.1`). Here's the minimal reproduction:
```ts
import { Hono } from 'hono'
import { logger } from 'hono/logger'

import { Env } from 'types'

const app = new Hono<{ Bindings: Env }>({
  getPath: (req) => {
    const url = new URL(req.url)
    // NOTE: custom `getPath` is needed because the worker serves multiple subdomains.
    // BTW, it would be *really* great if it was possible to access the bindings here,
    // so that we could do `url.host === ctx.env.FOO_APP_HOST` instead of hardcoding
    // (because staging and prod environments might have different `FOO_APP_HOST` values).
    const prefix = url.host.startsWith('foo.') ? '/FOO' : ''

    return `${prefix}${url.pathname}`
  },
})

const foo = new Hono<{ Bindings: Env }>()

app.use('*', logger())

foo.get('/', (c) => c.text('FOO'))
foo.get('*', (c) => c.text('BAR'))

app.route('/FOO', foo)

export default app
```

The above code results in:
```
GET / -> BAR (but should be FOO)
GET /whatever -> BAR
```

On the other hand, if we don't use nested routes:
```ts
import { Hono } from 'hono'
import { logger } from 'hono/logger'

import { Env } from 'types'

const app = new Hono<{ Bindings: Env }>()

app.use('*', logger())

app.get('/', (c) => c.text('FOO'))
app.get('*', (c) => c.text('BAR'))

export default app
```

It works as expected:
```
GET / -> FOO
GET /whatever -> BAR
```

---

My current workaround is doing something like this:
```ts
foo.get('*', (c) => {
  const url = new URL(c.req.url)

  if (url.pathname === '/') {
    return c.text('FOO')
  } else {
    return c.text('BAR')
  }
})
```

P.S: taking this opportunity to say thank you for the exceptional support @yusukebe :) the issue is not urgent since the workaround works, just wanted to let you know that it's still present

**Comment by yusukebe** [comment]
Hi @baygeldin!

It's not a bug; the issue is with your `getPath` logic.

For the given code:

```ts
foo.get('/', (c) => c.text('FOO'))
foo.get('*', (c) => c.text('BAR'))

app.route('/FOO', foo)

app.showRoutes()
```

The routes displayed will be:

```
GET       /FOO
GET       /FOO/*
```

Therefore, when accessing `/FOO/`, it will be handled by `BAR`. According to your `getPath` method, accessing `/` will resolve as `/FOO/`, and thus it returns `BAR`. 

To fix this, you can adjust your code as follows:

```ts
const path = url.pathname === '/' ? prefix : `${prefix}${url.pathname}`
```

**Comment by yusukebe** [comment]
@baygeldin 

Taking `env` (Cloudflare Bindings) in `getPath` is a good idea. It can't pass the "Context" because it is created after a path is resolved. But it can pass the `env` values into a `getPath` callback. So, there is a possibility to implement the feature. If you can, could you create the issue for it as feature request?

**Comment by baygeldin** [comment]
> ```ts
> const path = url.pathname === '/' ? prefix : `${prefix}${url.pathname}`
> ```
Ooh, nice idea! And it totally worked, thanks a lot!

However, I still think that this behavior is unintuitive:

> The routes displayed will be:
> ```
> GET       /FOO
> GET       /FOO/*
> ```

When I add a handler on the root route in the subapp (i.e. `foo.get('/', (c) => c.text('FOO'))`) I'd expect the routes to look like this:
```
GET       /FOO/
GET       /FOO/*
```

To match the behavior of the main app which routes look like this (when similarly defined):
```
GET       /
GET       *
```

In other words, `app.get('/', ...)` behaves differently depending on whether it's used in a subapp or the main app.

**Comment by yusukebe** [comment]
@baygeldin 

I understand what you are saying, but I think the current behavior is fine.

For instance, I want to merge the sub app like the following:

```ts
api.get('/', (c) => c.json({ books: [] }))
app.route('/api', api)
```

be:

```
GET       /api
```

The merge rules are defined in `utils/url`:

https://github.com/honojs/hono/blob/5320ed6c57074de82693ded8f0f59b020da5ba9d/src/utils/url.test.ts#L118-L126

Furthermore, if you're uncertain about the current routing at a glance, the `app.showRoutes()` feature is there to assist you.
