### ISSUE TITLE
Why is it called hono.fetch?

### ISSUE THREAD

**Issue by bryiac** [honojs/hono#1245]
I never understood why the method to handle the request is **hono.fetch**? shouldn't it be called **hono.handle**?

**Comment by yusukebe** [comment]
In the case of Cloudflare Workers, `fetch` serves as the entry point:

```ts
export default {
  fetch: (req) => {
    return new Response('foo')
  }
}
```

So, Hono instance's `fetch` will be called.

**Comment by bryiac** [comment]
Thank you for the response ~ you should consider renaming the method and releasing on a minor version to break everything and cause destruction 😈 ~ jokes aside thanks for the insight
