### ISSUE TITLE
Support Cloudflare Pages advance mode: _worker.js

### ISSUE THREAD

**Issue by abhishiv** [honojs/hono#1247]
Hello, 

I just wanted to point that right now hono doesn't support advance mode with cloudflare pages. As you can see in advance mode the signature of function is a bit different so the existing handle function from `hono/cloudflare-pages` won't work here. 

https://developers.cloudflare.com/pages/platform/functions/advanced-mode/#set-up-a-function

```
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname.startsWith('/api/')) {
      // TODO: Add your custom /api/* logic here.
      return new Response('Ok');
    }
    // Otherwise, serve the static assets.
    // Without this, the Worker will error and no assets will be served.
    return env.ASSETS.fetch(request);
  },
}
```

**Comment by yusukebe** [comment]
@abhishiv 

You can build your Cloudflare **Workers** code into `_worker.js` and deploy it as advanced mode. Please refer to this repo:

https://github.com/yusukebe/pages-workerjs

**Comment by abhishiv** [comment]
Hey @yusukebe  thanks for you reply! It works perfectly!

**Comment by yusukebe** [comment]
Great!
