### ISSUE TITLE
Handling of lambda@edge response events

### ISSUE THREAD

**Issue by watany-dev** [honojs/hono#1249]
I have a problem I'm having trouble solving regarding the Lambda@Edge adapter It is now possible that these simple renovations may not be enough. 

1. the following code you were referring to deals with event.Records[0].cf.response instead of event.Records[0].cf.request
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-overriding-response-header
2. there is a case like this where both event.Records[0].cf.request and event.Records[0].cf.response are handled. In the case of viewer-response and origin-response
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-update-error-status-examples

If only 1. is used, it is fine to create handlers for request and response, or branch, but I don't know the best practice when both are used as in 2. I hope there is an adapter somewhere that uses the two together.

**Comment by yusukebe** [comment]
Hi @watany-dev!

This is a complex issue concerning how to specify the API for the handler you've highlighted.

I realized that you can get the CloudFront Response using the following code:

```ts
const cloudFrontResponse = c.env.event.Records[0].cf.response
```

Wouldn't this be a good start to solving the problem?

**Comment by watany-dev** [comment]
Thank you very much! I just wish I could do this.
```ts
type Bindings = {
  callback: Callback
  request: CloudFrontRequest
  response: CloudFrontResponse
}
```

**Comment by watany-dev** [comment]
@yusukebe 

Yes, I have resolved the issue and will close this. Thanks for the review.
