### ISSUE TITLE
Hono JSX rendering as [Object object] on fly.io

### ISSUE THREAD

**Issue by terrabythia** [honojs/hono#1252]
I have a super simple app using bun and hono. I use `hono/jsx` to render html on the server (like explained in the hono docs: https://hono.dev/middleware/builtin/jsx). When I run `bun src/index.tsx` locally, everything works fine, I see rendered html (see screenshot), but when I deploy the same application to fly.io, the server always responds with `[Object object]` when trying to render JSX. Routes that don't render JSX (but just plain text) render just fine. Maybe this is an issue with fly.io, but I have no idea what could be wrong.

You can see my routes and their coresponding urls on fly.io here:

https://bun-hono-htmx.fly.dev/
```jsx
app.get("/", (c) => {
  return c.html(<App />);
});
```

https://bun-hono-htmx.fly.dev/list
```jsx
app.get("/list", (c) => { 
  return c.text(<List />)
});
```

https://bun-hono-htmx.fly.dev/hello
```jsx
app.get("/hello", (c) => {
  return c.text("Hello World!");
});
```

Screenshot of the route `/` working locally:
<img width="446" alt="screenshot" src="https://github.com/honojs/hono/assets/1402868/e781e36b-a923-4b53-9b8d-d1bd1c88c251">

**Comment by yusukebe** [comment]
Hi @terrabythia !

I haven't fully investigated this yet, but it appears to potentially be a bug with Bun. Could you please provide the version numbers of Bun in both your local environment and on fly.io?

**Comment by terrabythia** [comment]
Hi @yusukebe, thanks for your reply!

I have version `v0.6.14` installed locally, and from the logs I got from `fly deploy` I can see it's also using `v0.6.14` 

`=> [internal] load metadata for docker.io/oven/bun:0.6.14`.

**Comment by sor4chi** [comment]
Hi, @yusukebe @terrabythia 
I was able to reproduce it.
Even locally, if I bun start with NODE_ENV=production, it seems to become [Object object].

**Comment by yusukebe** [comment]
@sor4chi Thank you for sharing it!

This seems to be a Bun's bug. I've already reported: https://github.com/oven-sh/bun/issues/3753

**Comment by yusukebe** [comment]
Hi @terrabythia @sor4chi,

That was a bug in Bun, but it has now been fixed. The next version of Bun, which is likely to include this fix, will be released soon.

**Comment by terrabythia** [comment]
@yusukebe @sor4chi bun 0.7.1 has been released and it contains the fix. My website on fly.io is working now! https://bun-hono-htmx.fly.dev/

So this issue can be closed.

**Comment by yusukebe** [comment]
Great!!
