### ISSUE TITLE
`strict` option is ignored when specified with `getPath`.

### ISSUE THREAD

**Issue by todesking** [honojs/hono#1254]
To reproduce:
```javascript
import { Hono } from "hono";

const app = new Hono({
  strict: false,
  getPath: (req) => req.url.slice(req.url.indexOf('/', 8))
})

app.get('/foo', (c) => c.text('no slash'))
app.get('/foo/', (c) => c.text('slash'))

function assert(x: boolean) { if(!x) throw new Error("assertion failed") }

async function test() {
  const noSlash = await app.request('/foo')
  assert(await noSlash.text() === 'no slash')

  const slash = await app.request('/foo/')
  assert(await slash.text() === 'slash')
}

test()
```

There is some options to fix it:

* Strip trailing slash of custom `getPath` result when `strict: false`
* Specify it as intended:
  * Add jsdoc to `Hono` constructor
  * Fix `Hono` constructor type to prevent simultaneous specification of `getPath` and `strict`(if possible)
  * Add a note about the restriction to document([1](https://hono.dev/api/routing#routing-with-with-hostname), [2](https://hono.dev/api/hono#strict-mode))

**Comment by yusukebe** [comment]
Hi @todesking!

Thank you for raising this issue and providing detailed information that helped me understand the problem quickly. This was indeed a bug, and it has been addressed in PR #1259. A new version that includes this fix will be released soon.
