### ISSUE TITLE
Reasoning behind deprecating context.req.cookie

### ISSUE THREAD

**Issue by bryiac** [honojs/hono#1261]
You appear to be deprecating `context.req.cookie` and moving the methods into their own **middleware** ~ yet its not really a **middleware**? 

it adds a little **weirdness/clairty** to the **url import** `import { ... } from "https://deno.land/x/hono/middleware.ts"`

Is there any reason why people wouldn't want this functionality already in the request context? Maybe it's just me, but this change seems like more bad than good.

**Comment by yusukebe** [comment]
We aim to keep the Hono core minimal and compact. If we include 'cookie' within the Request object, it will increase the bundle size. Not everyone uses cookies, so it's reasonable to have it as middleware.

**Comment by yusukebe** [comment]
Related #965
