### ISSUE TITLE
ServeStaticOptions

### ISSUE THREAD

**Issue by jeesus-bock** [honojs/hono#1268]
The documentation talks about `rewriteRequestPath`that can be set as a ServeStaticOptions, but the type doesn't seem to support it.
```typescript
(alias) type ServeStaticOptions = {
    root?: string;
    path?: string;
}
import ServeStaticOptions
```

**Comment by Codinak** [comment]
It does:

```ts
export declare type ServeStaticOptions = {
    root?: string;
    path?: string;
    rewriteRequestPath?: (path: string) => string;
};
```

I assume you might have the wrong version. Try 3.3.3 (might be 3+)

**Comment by jeesus-bock** [comment]
Upgraded to 3.3.4 and now the whole serverStatic doesn't seem to be available under hono/

**Comment by yusukebe** [comment]
@jeesus-bock 

Can you share the snippets or a minimal code for reproduce it?

**Comment by jeesus-bock** [comment]
1. npm create hono@latest my-app 
2. try to add the import
```typescript
import { serve } from '@hono/node-server';
import { serveStatic } from 'hono/serve-static';
import { Hono } from 'hono';

const app = new Hono();
app.get('/', (c) => c.text('Hello Hono!'));

serve(app);
```
Gives out error `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './serve-static' is not defined by "exports" in /home/jpesonen/honotest/node_modules/hono/package.json`

**Comment by Codinak** [comment]
@jeesus-bock you might have done this, but I to be sure: did you check the actual version **installed**? You might have older version based on version constraints and lock file content.

**Comment by jeesus-bock** [comment]
I created that test project from scratch no no lockfile there. After running npm install, the lockfile is created and the hono version there too is 3.3.4. I don't know where else it could defined to be anything else?

**Comment by jeesus-bock** [comment]
And node_modules/hono/package.json also is 3.3.4

**Comment by jeesus-bock** [comment]
Going back the Tags in this repository 2.7.8 still had src/middlewares/serve-static but after that there's no such directory.

**Comment by yusukebe** [comment]
@jeesus-bock 

You have to write:

```ts
import { serveStatic } from "@hono/node-server/serve-static"
```

**Comment by jeesus-bock** [comment]
Works fine with the correct import path.
