### ISSUE TITLE
File-base routing

### ISSUE THREAD

**Issue by ysm-dev** [honojs/hono#1277]
It would be nice to have official middleware to easily apply file-base routing like Next.js.

What do you think?

**Comment by yusukebe** [comment]
Hi @ysm-dev!

Yeah, having file-based routing for Hono is great. But the difficult point is that edge runtime, such as Cloudflare Workers/Pages and Fastly Compute@Edge, does not have a file system, or it is not unified. So, it's almost impossible to make file-based routing as JIT for all platforms.

However, we can bundle them, such as using Vite. Actually, I'm now creating a file-based web framework using Hono; it's like Next.js but much simpler:

https://github.com/yusukebe/sonik

It's using Preact now, but it would be good to use `hono/jsx`. Then, it will be composed of pure Hono's components.

**Comment by joshamaju** [comment]
Hi @ysm-dev , @yusukebe  been working on something along those lines, you can check it out [here](https://github.com/joshamaju/hono-mvc). I'd love to hear your feedback

**Comment by sandys** [comment]
@yusukebe i would like to ask another perspective here. file based routing will help a lot for cloud/edge deployment...especially for large projects right ?

you would not need to ship the router (which scales with number of apis) for each lambda. I think opennext/sst also does this. same with unjs/nitro

**Comment by yusukebe** [comment]
@sandys 

Yes, exactly right. When you create a large application, you have to split files, and with a file-base routing meta framework like Sonik, you don't have to think about "how to split files"! You can see an example of this below:

https://github.com/yusukebe/sonik/tree/main/examples/api

**Comment by sandys** [comment]
> @sandys
> 
> Yes, exactly right. When you create a large application, you have to split files, and with a file-base routing meta framework like Sonik, you don't have to think about "how to split files"! You can see an example of this below:
> 
> https://github.com/yusukebe/sonik/tree/main/examples/api

@yusukebe this is VERY VERY COOL! three questions:
1. how does the file based routing work ? is this feature coming from sonik ... or is it built into hono ? cos the link u shared seems to be doing everything using sonik's `createApp`
2. how will this build and deploy to cloudflare workers ? that wasnt clear - especially if we have many file based routes - each route will become a different lambda and deployed separately right ?
3. im looking to build an internal framework (at my workplace), that is why i was hoping this can be done in hono. do you suggest that we use sonik as the base framework. im not looking for frontend...only backend api.

**Comment by sandys** [comment]
@yusukebe thank you for replying!

so im kind of wondering if people like me should switch focus to sonik. or whether you are using sonik as a scratchpad and will backport the changes back into honojs ?
because if sonik has all these extra things - would that be your primary recommended framework ?

**Comment by yusukebe** [comment]
@sandys 

> so im kind of wondering if people like me should switch focus to sonik. or whether you are using sonik as a scratchpad and will backport the changes back into honojs ?

For now, Sonik is like a experimental place, cutting out the common parts from Sonik's features and porting them to the `honojs`. [@hono/vite-dev-server](https://github.com/honojs/vite-plugins/tree/main/packages/dev-server) is one such example. Next, I'm thinking about porting the file-based routing functionality of Sonik to `honojs`.

> because if sonik has all these extra things - would that be your primary recommended framework ?

Sonik may be the best option, but it's one of frameworks. Perhaps we will see a better framework than Sonik, but I think that would be good.

**Comment by fayazara** [comment]
+1 

File based routing definitely adds a lot of abstraction, but it could act as a opt-in plugin maybe. This will make creating servers so easy and so fast.

**Comment by kashalls** [comment]
It would be pretty useful as a feature for my development workflow. Definitely as an add-on plugin.
