### ISSUE TITLE
Return empty 200 Response as default

### ISSUE THREAD

**Issue by chientrm** [honojs/hono#1280]
Like `itty-router`, just return an empty 200 Response as default if there's no response specified.

`http` methods include GET/POST/PUT/PATCH/DELETE. Most of the time only the `GET` method return a details response, other methods return an empty 200 Response.

So that, by implementing this feature, we can remove redundant `return c.body()` from the routes.

**Comment by yusukebe** [comment]
Hi @chientrm,

I don't think it's a good idea to return a 200 Response as the default. There is possibility that users don't desire it to be 200, but 404 or throwing the error instead. And, basically, we designed it so that the "handler should return a Response object."

**Comment by yusukebe** [comment]
@usualoma @metrue @ThatOneBro or others:

What do you think about it?

**Comment by usualoma** [comment]
Hi @chientrm @yusukebe

If a handler returns `undefined`, it means "the handler did not process anything" and not "success, but the response is empty." This is a necessary specification for the routing fallback mechanism.

Also, in general, it is preferable to return a meaningful response from even other than GET.

Thus, I think no need to return an empty 200 response.

**Comment by ThatOneBro** [comment]
I agree with @usualoma, it can lead to unexpected behavior and false positives that a route is working. Probably better not to default to a 200 response.

**Comment by yusukebe** [comment]
We could close this.
