### ISSUE TITLE
`c.json()` but my Date is stringify with 3 digits of `ms`

### ISSUE THREAD

**Issue by chientrm** [honojs/hono#1286]
When I using `itty-router`, the date is stringified correctly with 6 digits of `ms`.
This loss of information break my api 🩴🩴🩴

**Comment by yusukebe** [comment]
Can you share the short code returning Response in your itty-router app?

**Comment by chientrm** [comment]
> 

It's like this:

```ts
import { json } from "itty-router-extras";

return json({ audios });
```

**Comment by chientrm** [comment]
Nvm, I found the bug.

When I replace `itty` with `hono`, I also moved my database from `PlanetScale` to `D1`. While the `PlanetScale` play with `iso8601`, the `D1` recognize `date.toString` better.

**Comment by yusukebe** [comment]
It's not the same itty-router's `json` function and Hono's `c.json()`. It's not a bug.

**Comment by chientrm** [comment]
> It's not the same itty-router's `json` function and Hono's `c.json()`. It's not a bug.

Yep. It was a bug with my database, neither `itty` or `hono`.
