### ISSUE TITLE
`notFound` requires a `Response` when returning `jsonT`

### ISSUE THREAD

**Issue by NuroDev** [honojs/hono#1291]
### What is the issue?

Currently when using the `.notFound` method returning `.json` is typed correctly & works fine.
However `.jsonT` can be used as well but this returns the following type error:
```
Type 'TypedResponse<{ success: boolean; }>' is not assignable to type 'Response | Promise<Response>'.(2322)
```
It seems that `.jsonT` does not return the correct type when used inside a `.notFound` method.

### Ways to fix it.

Realistically I am unsure if `.jsonT` is needed to be used inside of the `.notFound` method? So, unless I am missing something, this method could be removed or disallowed?

However if not then it should just be a case of needing to update & fix the required return type(s) for `.notFound`.

### Playground

[Link](https://tsplay.dev/mbag2N)

```ts
import { Hono } from "hono";

const app = new Hono();

app.get("/", (c) => c.text("Hono!"));

// This works
app.notFound((c) => c.json({ success: false }, 404));

// This throws a type error
app.notFound((c) => c.jsonT({ success: false }, 404));

export default app;
```

**Comment by yusukebe** [comment]
Hi @NuroDev !

> It seems that `.jsonT` does not return the correct type when used inside a `.notFound` method.

I think `notFound()` should not return `TypedResponse`, the type definition is the following:

```ts
type NotFoundHandler<E extends Env = any> = (c: Context<E>) => Response | Promise<Response>
```

So, you don't have to use `jsonT()` in a `notFound()`.

**Comment by NuroDev** [comment]
Hey @yusukebe 

Okay that makes sense, I'll do that in future.

In regards to DX though, is removing `jsonT` from being allowed to be called or omitted from the types inside `.notFound` to consider? That way a user doesn't have to either look up this issue or "discover" that `jsonT` is preferred to be used?

**Comment by yusukebe** [comment]
@NuroDev

> is removing `jsonT` from being allowed to be called or omitted from the types inside `.notFound` something to consider?

That might be a better solution, but I think it's challenging to implement.

<img width="319" alt="Screenshot 2023-08-08 at 13 39 02" src="https://github.com/honojs/hono/assets/10682/a315ffda-c890-406b-8ab8-b96dcf39f250">

Currently, if you attempt to return values with `jsonT()` in `app.notFound()`, it will display warnings with red underlines. I think that's sufficient.
