### ISSUE TITLE
 `zValidator` doesn't work when colocating outside the handler with custom `Bindings`

### ISSUE THREAD

**Issue by NuroDev** [honojs/hono#1292]
### What is the issue?

If you currently try to use the `zValidator` & extract out the actual resulting validator, maybe to share it across multiple handlers, then it will work fine.

However, if you try & do that while providing custom a custom type argument / generic to the `new Hono` instance then it will throw a type error when trying to pass it to the handler.

It seems to be that the `zValidator` function expects or requires a certain `Bindings` and/or `Variables` structure.

### Ways to fix it

I don't know if there is a way to instead infer the `Bindings` and/or `Variables` from the parent handler rather than having them fixed & hard coded?

Or at least allow us to manually pass these `Bindings` and/or `Variables` as a type argument/generic?

### Playground

[Link](https://tsplay.dev/mAg41w)

```ts
import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { z } from "zod";

// This will work fine
const foo = zValidator(
  "form",
  z.object({
    body: z.string(),
  })
);
new Hono().post("/posts", foo, (c) =>
  c.json({
    success: true,
  })
);

// This will throw a type error when trying to pass it to `app.post`
const bar = zValidator(
  "form",
  z.object({
    body: z.string(),
  })
);
new Hono<{
  Bindings: { foo: string };
}>().post("/posts", bar, (c) =>
  c.json({
    success: true,
  })
);

// But if you inline it it works fine
new Hono<{
  Bindings: { foo: string };
}>().post(
  "/posts",
  zValidator(
    "form",
    z.object({
      body: z.string(),
    })
  ),
  (c) =>
    c.json({
      success: true,
    })
);
```

**Comment by yusukebe** [comment]
Hi @NuroDev 

As you mentioned, that doesn't work well because it can't infer the correct types. Fixing this might be too difficult or even impossible, so I think it might be better to abandon trying to write it that way.
