### ISSUE TITLE
How to make Hono work with `json-server`?

### ISSUE THREAD

**Issue by arnonrdp** [honojs/hono#1293]
I have this simple `server.js` file and I am trying to make it work with Hono:
```js
const jsonServer = require('json-server')
const auth = require('json-server-auth')

const app = jsonServer.create()
const router = jsonServer.router('db.json')
const middlewares = jsonServer.defaults({ noCors: false })

const port = process.env.PORT || 3333

app.db = router.db

app.use(middlewares)
app.use(auth)
app.use(router)
app.listen(port)
```

How can I integrate this with `const app = new Hono()`?

ps.: Here is an example of JSON Server running in production: https://jsonplaceholder.typicode.com/

**Comment by adoublef** [comment]
Have you tried using the mount method?

https://hono.dev/api/hono#mount

**Comment by yusukebe** [comment]
@arnonrdp 

`json-server` seems to be an Express-based Node.js framework. So, it can't be integrated with Hono.

Although, you may mount your Hono app on `json-server` with `@hono/node-server`.

```ts
import { getRequestListener } from '@hono/node-server'

// ...

const app = jsonServer.create()

const hono = new Hono()
app.use("/hono", getRequestListener(hono.fetch))
```

**Comment by arnonrdp** [comment]
@yusukebe, this is an interesting approach.

I will definitely try it. Thanks.
