### ISSUE TITLE
match on `/foo` and `foo.json`

### ISSUE THREAD

**Issue by adoublef** [honojs/hono#1299]
I was wondering if there is a way to achieve similar results to this Go middleware where you are able to match on `foo` as well as anything that matches beyond the dot delimiter `foo.json`, `foo.img` [chi/middleware/url\_format.go at master · go-chi/chi (github.com)](https://github.com/go-chi/chi/blob/master/middleware/url_format.go)

**Comment by yusukebe** [comment]
Hi @adoublef 

You can use a regexp for the routing:

```ts
app.get('/file/:name{foo.*}', (c) => {
  return c.text(c.req.param('name'))
})
```
