### ISSUE TITLE
File uploads?

### ISSUE THREAD

**Issue by xokaido** [honojs/hono#1300]
Hello, first of thank you for this wonderful piece of software. I am very new here but I'm quickly falling in love with this tiny thing that does a lot.
I am sorry if this was already discussed before, how do we do file uploads in Hono, do we have any examples?
Thanks for your help in advance.

**Comment by yusukebe** [comment]
HI @xokaido !

You can refer to this : https://github.com/honojs/hono/issues/848#issuecomment-1556806066

**Comment by xokaido** [comment]
Thank you for your reply @yusukebe but the solution from your link did work for me.
`app.post('/upload', async (c) => {
    const { image } = await c.req.parseBody()

    if (image instanceof File) {

        console.log(image.name) // show the file name
        const buffer = await image.arrayBuffer()
        // do something with the buffer
    }

    return c.json({ status: 'Uploaded!', request: c.req.parseBody() })
})`
This code didn't work for me, I am getting this result:
![image](https://github.com/honojs/hono/assets/6562281/5436ace6-a44b-402d-a442-1ee527d33722)
And nothing on the console.
Do you have any idea why this could happen?

**Comment by xokaido** [comment]
My bad, I was tired and made multiple mistakes. The key is wrong here and the return doesn't do "await"...
Thank you for your help @yusukebe

**Comment by yusukebe** [comment]
Great! Closing the issue.
