### ISSUE TITLE
How to escape colon in path

### ISSUE THREAD

**Issue by juanpmarin** [honojs/hono#1301]
Hi! I'm using hono for building a rest API following the [google aip guidelines](https://google.aip.dev/136), they say that when you need to run a non standard method, you use colon for define the method name, for example:

`publishers/juan/books/123:archive`

I've tried scaping colon with bach slash, like this:

```
get"/publisher/:publisherId/books/:bookId\\:archive", handler) 
```

But it does not work, what's the right way to escape colon?

**Comment by yusukebe** [comment]
Hi @juanpmarin 

Try using regexp routing. You can extract the `bookId`:

```ts
app.get('/publishers/:publisherId/books/:slug{[0-9]+:archive}', (c) => {
  const slug = c.req.param('slug') // 123:archive
  const id = slug.replace(/\:archive$/, '')
  return c.text(`id is ${id}`)
})
```

**Comment by yusukebe** [comment]
I'll close this issue. If you have any problem, feel free to reopen.
