### ISSUE TITLE
Optional path characters with wildcards

### ISSUE THREAD

**Issue by leesus** [honojs/hono#1306]
Is it possible to capture optional path characters as well as wildcards in middleware paths? I am trying to allow for path pluralisation.

```
app.use('/cars?/*', middlewareHandler);
app.get('/cars?/:brand', routeHandler);
app.get('/cars?/:brand/:model', routeHandler);
```

While the route matches for e.g.`/car/ford`, `/cars/ford`, `/car/ford/escort` and `/cars/ford/escort`, the middleware is not called at all.

Is this unsupported, or have I just got the syntax wrong?

**Comment by yusukebe** [comment]
Hi @leesus 

The usage of "optional parameter" is the following:

```ts
app.get('/cars/:brand?', (c) => {
  return c.text(`${c.req.param('brand') || 'no brand'}`)
})
```

I think you don't need to use `?`.

**Comment by leesus** [comment]
I need to support legacy singular paths while upgrading to pluralised paths, so being able to support `/car/whatever` and `/cars/whatever` without having to repeat middleware/route definitions.

I'll just go with doubling up for now, e.g.

```
app.use('/car/*', middlewareHandler);
app.use('/cars/*', middlewareHandler);

app.get('/car/:brand', routeHandler);
app.get('/cars/:brand', routeHandler);

app.get('/car/:brand/:model', routeHandler);
app.get('/cars/:brand/:model', routeHandler);
```

**Comment by yusukebe** [comment]
@leesus 

You can use regexp routings:

```ts
app.use('/:slug{cars?/.+}', async (c, next) => {
  console.log('m')
  await next()
})
app.get('/:slug{cars?}/:brand', (c) => {
  return c.text(`${c.req.param('brand')}`)
})
app.get('/:slug{cars?}/:brand/:model?', (c) =>
  c.text(`${c.req.param('brand')}, ${c.req.param('model')}`)
)
```

**Comment by leesus** [comment]
Great, thanks!

**Comment by robingenz** [comment]
I have a similar problem with the following route:

```ts
app.get("/:workspace{(@[\\dA-Za-z]*)?}/:user", async (context) => {
  
});
```

I would expect this route to match `/@myworkspace/myuser` and `/myuser`. However, it only matches with `/@myworkspace/myuser`. Any idea?

I'm running `hono@3.12.0`.
