### ISSUE TITLE
jsonT response type is infered incorrectly when adding lib option to tsconfig.json

### ISSUE THREAD

**Issue by rosahaj** [honojs/hono#1310]
### Problem

When adding the `lib` option under `compilerOptions` of either tsconfig.json or deno.jsonc, the response type of a route which returns a jsonT response is incorrectly infered as `{}`. This issue occurs in both node and deno environments.

### Steps to reproduce

The example below throws the following TypeScript error:
```
Property success does not exist on type {}
```

That's because TypeScript incorrectly infers the route's type as `{}`:

```ts
Hono<Env, Schema<"get", "/", {
    json: {
        id?: string;
    };
}, {}>, "/">
```

When removing the lib option, the type is correctly inferred as `{success: boolean}`:

```ts
Hono<Env, Schema<"get", "/", {
    json: {
        id?: string;
    };
}, {
    success: boolean;
}>, "/">
```

At least in node environments, the error occurs regardless of the lib option set. I have tested this with numerous lib options.

**Code:**

```ts
// index.ts

import { zValidator } from "@hono/zod-validator";
import { Hono } from "hono";
import { hc } from "hono/client";
import z from "zod";

const app = new Hono();
const route = app.get(
  "/",
  zValidator(
    "json",
    z.object({
      id: z.string(),
    })
  ),
  (c) =>
    c.jsonT({
      success: true,
    })
);

const client = hc<typeof route>("");
const response = await client.index.$get({ json: { id: "1" } });
const { success } = await response.json();
```

```ts
// tsconfig.json

{
  "compilerOptions": {
    "lib": ["es2023"],
    "target": "es2022",
    "module": "Node16",
    "skipLibCheck": true
  },
  "include": ["index.ts"],
  "exclude": ["node_modules/"]
}
```

In deno environments:
```ts
// deno.jsonc

{
  "compilerOptions": {
    "lib": ["es2023"]
  }
}
```

**Comment by sor4chi** [comment]
Hello @rosahaj, I think it will be fixed to add ﻿`types: ["@cloudflare/workers-types”]` to compilerOptions in tsconfig.json.

**Comment by sor4chi** [comment]
Hi, @rosahaj 
I added "DOM" or "WebWorker" to the Compiler Options lib and the type error disappeared.
I think the condition is that the `ResponseInit` Type defined in the web standard must exist globally.

https://github.com/honojs/hono/blob/ba346a4b63c33155d4efcecdcef922d5ed6aa6e8/src/context.ts#L324-L328

**Comment by yusukebe** [comment]
This can be closed. If you have a problem, feel free to reopen.
