### ISSUE TITLE
Support for Firebase Functions

### ISSUE THREAD

**Issue by RobertSasak** [honojs/hono#1358]
### What is the feature you are proposing?

I think Deno is a perfect to be used as a dynamic router in Firebase functions. Currently Express is the main choise. 

Firebase function expect `(request, reponse)=>void` function which should not be so difficult to provide from Deno. I have looked into _nodejs-server_ implementaion but I might need some more hints.

**Comment by RobertSasak** [comment]
It was not so hard in the end. Import _node-server_ package and use `getRequestListener` around `app.fetch`.
```ts
import { getRequestListener } from '@hono/node-server'
import { onRequest } from 'firebase-functions/v2/https'
import { Hono } from 'hono'

const app = new Hono()
app.get('/**', (c) => c.text('Hello Node.js!'))

export const web = onRequest(getRequestListener(app.fetch))
```

**Comment by yusukebe** [comment]
Great!

**Comment by RobertSasak** [comment]
There is an silent error 500 when doing a POST request with payload. 
```sh
TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:6433:17)
    at new Request (node:internal/deps/undici/undici:7314:48)
    at /<path>/functions/node_modules/@hono/node-server/dist/listener.js:48:33
    at /<path>/functions/lib/functions/src/index.js:79:64
    at /<path>/functions/node_modules/firebase-functions/lib/v2/providers/https.js:57:29
    at cors (/<path>/functions/node_modules/cors/lib/index.js:188:7)
    at /<path>/functions/node_modules/cors/lib/index.js:224:17
    at originCallback (/<path>/functions/node_modules/cors/lib/index.js:214:15)
    at /<path>/functions/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/<path>/functions/node_modules/cors/lib/index.js:199:9)
```
It is exactly the same error as in https://github.com/honojs/node-server/issues/84

**Comment by yusukebe** [comment]
@RobertSasak 

Could you create the issue on [`honojs/node-server` issues](https://github.com/honojs/node-server/issues) with the minimal code for reproduce it?

**Comment by RobertSasak** [comment]
Yes, lets move conversation to https://github.com/honojs/hono/issues/1695
