### ISSUE TITLE
How do I remove x-served-by header?

### ISSUE THREAD

**Issue by geekyayush** [honojs/hono#1369]
### What version of Hono are you using?

3.5.1

### What runtime/platform is your app running on?

Nodejs

### What steps can reproduce the bug?

Just simple hono server setup with node.js and then use `secureHeader()` middleware.

### What is the expected behavior?

x-served-by header should not come

### What do you see instead?

"x-served-by" header is coming with my domain name.

**Comment by yusukebe** [comment]
@geekyayush 

Maybe this is not Hono matter. Hono does not add the header `x-served-by`. Perhaps, you can remove it with this code:

```ts
app.use('*', async (c, next) => {
  await next()
  c.res.headers.delete('x-served-by')
})
```

**Comment by geekyayush** [comment]
> Maybe this is not Hono matter. Hono does not add the header `x-served-by`. Perhaps, you can remove it with this code:

Thanks for the reply. I had the same exact setup but with Cloudflare worker (using Hono only). There, I didn't have this x-served-by header. But recently, I changed it to node.js using hono node.js adapter and started getting that header.

I will try the fix. Thanks a lot!

**Comment by yusukebe** [comment]
Okay. I'll close this. Thanks!
