### ISSUE TITLE
Return type of route has "unknown" as response type for async handler

### ISSUE THREAD

**Issue by banjo** [honojs/hono#1383]
### What version of Hono are you using?

3.5.5

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

The type of the route has a different return type whether the handler is async or not.

When it is sync, it has the correct return type:

```
const route = app.get("/test", c => {
    return c.jsonT({ test: "test" });
});
```
<img width="525" alt="CleanShot 2023-08-28 at 22 06 25@2x" src="https://github.com/honojs/hono/assets/21983557/1052285c-27e4-453f-aca2-3daf3d4fa6d3">

When it is async, it has `unknown` as return type:

```
const route = app.get("/test", async c => {
    return c.jsonT({ test: "test" });
});
```

<img width="641" alt="CleanShot 2023-08-28 at 22 06 37@2x" src="https://github.com/honojs/hono/assets/21983557/9bec464b-d410-47df-b125-35876aeb61d5">

### What is the expected behavior?

It should always show the inferred type, instead of `unknown`

### What do you see instead?

`unknown`

**Comment by yusukebe** [comment]
Hi @banjo !

This will be fixed in v3.5.6 which I've just released now. Try it!
