### ISSUE TITLE
Avoid `denoify` API rate limit

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1398]
### What is the feature you are proposing?

If call `denoify` many times in CI at once, it will throw ther error:

> API rate limit exceeded for 13.88.99.209. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more **details.**

https://github.com/honojs/hono/actions/runs/6062770394/job/16449345495#step:6:18

We can fix it by setting a GitHub token.

**Comment by watany-dev** [comment]
I'm sure this is it? I'll fix it.

https://docs.github.com/ja/actions/security-guides/automatic-token-authentication

**Comment by yusukebe** [comment]
Hi @watany-dev 

Maybe yes. The `denoify` document is here:

https://docs.denoify.land/deal-with-github-api-rate-limit-exceeded
