### ISSUE TITLE
Deprecate `c.req.headers` (not `c.req.header`) and others

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1399]
Sometimes it's good to have options, but at other times too many options can confuse users.

In the case of Hono, `c.req.header` and `c.req.headers` have similar names and are used in similar contexts:

```ts
const contentType = c.req.header('Content-Type')
// Or
const contentType = c.req.headers.get('Content-Type')
```

I've felt for a while that this isn't ideal. There are redundant properties in `HonoRequest` that aren't frequently used or particularly significant.

The reason `HonoRequest` has so many properties is that `c.req` was previously defined as `Request`. To maintain backward compatibility, we haven't removed these properties:

```ts
get headers() {
  return this.raw.headers
}
get body() {
  return this.raw.body
}
get bodyUsed() {
  return this.raw.bodyUsed
}
get integrity() {
  return this.raw.integrity
}
get keepalive() {
  return this.raw.keepalive
}
get referrer() {
  return this.raw.referrer
}
get signal() {
  return this.raw.signal
}
```

With this issue, I propose that we deprecate these methods and remove them in v4, recommending instead that properties be accessed directly from `c.req.raw`, like `c.req.raw.body`.

This is a significant change, but it's necessary to make Hono cleaner and more intuitive.

**Comment by ThatOneBro** [comment]
I think this makes sense. It's a breaking change but a minimal one. I think writing a codemod (code migration) script may be easy with this one.
