### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by janat08** [honojs/hono#1400]
### What version of Hono are you using?

3.5.4

### What runtime/platform is your app running on?

cloudflare workers

### What steps can reproduce the bug?

import { Context, Hono } from 'hono'
import { logger } from 'hono/logger'
import { HtmlEscapedString } from 'hono/utils/html'
import { DrizzleD1Database, drizzle } from 'drizzle-orm/d1';
import * as schema from './schema';

export interface Env {
  DB: D1Database;
}
type Variables ={
  db: DrizzleD1Database
}
type Bindings = {
  DB: D1Database;
}
const {log} = console
const app = new Hono<{ Variables: Variables, Bindings: Bindings}>()

app.use('*', async (c: Context, next)=>{
  const db = drizzle(c.env.DB, {schema} );  
  c.set('db', db)
  await next()
})

function dbc (c: Context){
  return drizzle(c.env.DB, {schema} )
}

app.use('*', logger())

app.get('/', (c) => {
  return c.html(<Index />)
})

app.get('/search', async (c) => {
  const keywords = c.req.query("keywords")
  // const db = c.get('db');  

  const result = await db.query.apis.findMany()
  log(result)
  return c.html(<Search />)
})

### What is the expected behavior?

No type errors

### What do you see instead?

Typeerror that the db instance is missing a generic.

### Additional information

Using dbc function within a route will not have the same error.

**Comment by yusukebe** [comment]
It's not a bug. Don't use `Context` type directly:

```ts
app.use('*', async (c, next) => { // remove `Context`
  const db = drizzle(c.env.DB, { schema })
  c.set('db', db)
  await next()
})
```
