### ISSUE TITLE
Use `ExpectTypeOf` to test types

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1429]
We are now using Vitest. There is an [ExceptTypeOf API](https://vitest.dev/api/expect-typeof.html) in Vitest which can be used for testing types instead of `Expect` and `Equal` in `utils/types.ts`

**Comment by vadhe** [comment]
the issue is updating this file, right?

- src/hono.test.ts
- src/types.test.ts

<img width="1069" alt="Jepretan Layar 2023-09-13 pukul 12 00 40" src="https://github.com/honojs/hono/assets/36479850/565dcba5-2457-40a1-b20c-2ed1efdd3aba">

**Comment by yusukebe** [comment]
@vadhe 

Yes, right!

**Comment by vadhe** [comment]
@yusukebe 
Okay then I will try to work on this issue

**Comment by vadhe** [comment]
kindly check this PR  https://github.com/honojs/hono/pull/1458
