### ISSUE TITLE
Hono client ignores route with middleware

### ISSUE THREAD

**Issue by bsfranca2** [honojs/hono#1431]
### What version of Hono are you using?

3.5.8

### What runtime/platform is your app running on?

Web and Bun

### What steps can reproduce the bug?

```typescript
// server.ts
import { Hono } from 'hono';
import { jwt } from 'hono/jwt';

const app = new Hono()
  .get('/users', (c) => c.jsonT({ users: [] }))
  .get('/posts', jwt({ secret: 'my-secret' }), (c) => c.jsonT({ posts: [] }));

export type AppType = typeof app;
```

```typescript
// client.ts
import { hc } from 'hono/client';
import type { AppType } from './server';

const client = hc<AppType>('/api');
client. // auto complete doesnt works
```

### What is the expected behavior?

Hono client working

### What do you see instead?

Types not working

### Additional information

I initially had this error with Bun, but I was able to reproduce the error on StackBlitz as well.
https://stackblitz.com/edit/typescript-cc7vpy?file=index.ts

This error is for middleware in method function only, when I use `.use('*', middleware)` works well
```typescript
// working
const postsRoute = new Hono()
  .use('*', jwt({ secret: 'my-secret' }))
  .get('/', (c) => c.jsonT({ posts: [] }));

const app = new Hono()
  .get('/users', (c) => c.jsonT({ users: [] }))
  .route('/', postsRoute);
```

**Comment by yusukebe** [comment]
Hi @bsfranca2 !

Thanks for raising the issue.

This is a known issue, though it hasn't been documented yet. To address this, we'd need to add some type definitions to middleware like `jwt`. We're considering adding support for this in the future. Until then, please use the following workaround:

> This error is for middleware in method function only, when I use `.use('*', middleware)` works well

**Comment by emersonlaurentino** [comment]
@yusukebe I've the same issue, but with a custom middleware. do u have any workaround?

```ts
export const authenticate = createMiddleware(async (c, next) => {
  const authRequest = auth.handleRequest(c);
  const session = await authRequest.validateBearerToken();
  if (!session) {
    return c.json(
      {
        error: {
          code: "unauthorized",
          issues: [{ message: "This endpoint requires a Bearer token." }],
        },
      },
      401
    );
  }
  c.set("session", session);
  await next();
});
```

```ts
const app = new Hono<{ Variables: { session: Session } }>()
  .get('/', authenticate, (c) => c.json({ session: c.get('session') }))
```

**Comment by yusukebe** [comment]
Hi @emersonlaurentino !

You also have to pass the "Env" generics to `createMiddleware()`:

```ts
type Env = { Variables: { session: Session } }

export const authenticate = createMiddleware<Env>(async (c, next) => {
  // ...
}

const app = new Hono<Env>()
  .get('/', authenticate, (c) => c.json({ session: c.get('session') }))
```
