### ISSUE TITLE
Can't access context.env on vercel edge runtime

### ISSUE THREAD

**Issue by kevbook** [honojs/hono#1433]
### What version of Hono are you using?

3.5.8

### What runtime/platform is your app running on?

Vercel

### What steps can reproduce the bug?

On vercel edge runtime, `context.env` isn't a thing. 
Env variables can be accessed via `process.env` - Or - using `import { env } from 'hono/adapter'`

The vercel adaptor needs a fix, and should have this baked in so `ctx.env` should work as documented here https://hono.dev/api/context#env

Sample code below:

```js
app.get('/', async function (c) {
  console.log(c.env, process.env);
  return c.json({ message: 'Hello Hono!' });
});
```

**Comment by yusukebe** [comment]
Hi @kevbook 

This is not a bug. `c.env` is only for Cloudflare Workers / Pages. Please use the `env` imported from the `hono/adapter`. Thanks.
