### ISSUE TITLE
Create a set of JWT helpers 

### ISSUE THREAD

**Issue by julianpoma** [honojs/hono#1443]
### What is the feature you are proposing?

This proposal aims to create a small set of JWT helpers similar to [what is offered for Cookies](https://hono.dev/helpers/cookie).

I am currently developing an API server with JWT authorization. While the provided JWT middleware is incredibly useful for handling incoming tokens, my application also requires the capability to issue new JWTs.

Hono currently includes some methods within its codebase that serve this purpose, [as discussed in this PR](https://github.com/honojs/hono/pull/169#issuecomment-1714706459). However, these methods lack documentation, and their API is not considered stable.

By exposing these functions as an official set of helpers, we can save not only myself but also potentially other developers from the need to add another dependency to our applications or create our own JWT utility functions.

I propose that these helpers remain small and straightforward, encompassing only three primary functions: `sign`, `verify`, and `decode`.

**Comment by yusukebe** [comment]
This can be closed!
