### ISSUE TITLE
Return type inferred as "never" for a route

### ISSUE THREAD

**Issue by banjo** [honojs/hono#1446]
### What version of Hono are you using?

3.6.0

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

This code currently returns `never` as a return type:

<img width="414" alt="CleanShot 2023-09-12 at 09 24 55@2x" src="https://github.com/honojs/hono/assets/21983557/33726d07-9a72-4609-9ac2-24474288e3dc">

```ts
const getDraw = drawController.get("/draw/:slug", async c => {
    const slug = c.req.param("slug");

    const drawing = await DrawRepository.getDrawingBySlug(slug);

    if (!drawing.success) {
        return c.jsonT(Result.error(drawing.message, drawing.type));
    }

    return c.jsonT(Result.ok(drawing.data));
});
type GetDrawRoute = typeof getDraw;
```

The `Result` object that causes the error looks like this:

```ts
export const Result = {
    ok: <T>(data: T): SuccessResult<T> => ({
        success: true,
        data,
    }),
    okEmpty: (): SuccessResult<void> => ({
        success: true,
        data: undefined,
    }),
    error: (message: string, type: ErrorType): ErrorResult => ({
        success: false,
        type,
        message,
        status: ErrorStatus[type],
    }),
};
```

---

It does however work if I change the return on the error to this:

```ts
const getDraw = drawController.get("/draw/:slug", async c => {
    const slug = c.req.param("slug");

    const drawing = await DrawRepository.getDrawingBySlug(slug);

    if (!drawing.success) {
        return c.jsonT({ hello: "world" });
    }

    return c.jsonT(Result.ok(drawing.data));
});
```
<img width="334" alt="CleanShot 2023-09-12 at 09 27 30@2x" src="https://github.com/honojs/hono/assets/21983557/c4f4c6a7-13dc-4719-9f17-1f8d586e8584">

---

I guess it somehow messes up when `Result.ok` and `Result.error` is returned in the same method?

---

Here is the model for result:

```ts
export type SuccessResult<T> = {
    success: true;
    data: T;
};

export type ErrorResult = {
    success: false;
    type: ErrorType;
    message: string;
    status: number;
};


export type ResultType<T> = SuccessResult<T> | ErrorResult;

```

### What is the expected behavior?

It should infer the correct type

### What do you see instead?

`never`

**Comment by yusukebe** [comment]
Hi @banjo,

The issue arises because there's a possibility that `success` can be either `true` or `false`. You should set `success` as a `boolean`.

**Comment by banjo** [comment]
Yeah, but when you set conditional types, it is a perfectly valid case to set them directly to `true` or `false` to help Typescript infer the type.

```ts
type Result =
    | {
          success: true;
          data: any;
      }
    | {
          success: false;
          message: string;
      };

if (someResult.success) {
    // inferred type expets data
    console.log(someResult.data);
} else {
    // inferred type expects message
    console.log(someResult.message);
}
```

Some more about that [here](https://basarat.gitbook.io/typescript/type-system/discriminated-unions).

I don't know if this might be difficult to implement but I believe it is a very important part to make for a good developer experience with the RPC feature.
