### ISSUE TITLE
Multiple use of `new Hono()` leads to a type error

### ISSUE THREAD

**Issue by Oreki-Dev** [honojs/hono#1453]
### What version of Hono are you using?

3.6.0

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```
// main.ts/index.ts 
import { Hono } from 'hono';
import { app as router } from './router';

const app = new Hono();

app.route('/route', router)
```

```
// router.ts 
import { Hono } from 'hono':

export const app = new Hono();
```

After creating multiple sub apps (around 5-6) when I try to create more I get a wierd type error 
```
The inferred type of 'app' cannot be named without a

reference to '../../../node_modules/hono/dist/types/types'. This is likely not portable. A type annotation is necessary.
```

I found a temp fix to use `moduleResolution` in `tsconfig.json` as `node`

**Comment by yusukebe** [comment]
Hi @Oreki-Dev 

Thanks for creating the issue.

As you said (in Discord), this seems to be a TypeScript setting issue. If it is resolved with that way, we can close this issue. If you have still problem, feel free to reopen it.

**Comment by movahhedi** [comment]
I had the same problem.
Setting `"declaration": false` in `tsconfig.json` fixed it.
