### ISSUE TITLE
Using middlewares with different env variables

### ISSUE THREAD

**Issue by huv1k** [honojs/hono#1460]
### What version of Hono are you using?

3.6.0

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

Create two middlewares that have different ﻿`env` variables, as shown in
```tsx
import { Hono } from 'hono'
import type { MiddlewareHandler } from 'hono'

const mw1: MiddlewareHandler<{
  Bindings: {
    ENVIRONMENT: 'prod' | 'staging' | 'dev'
  }
}> = async (c, next) => await next()

const mw2: MiddlewareHandler<{
  Bindings: {
    CLOUDFLARE_WORKER_SHA: string
  }
}> = async (c, next) => await next()

const app = new Hono<{
  Bindings: {
    ENVIRONMENT: 'prod' | 'staging' | 'dev'
    CLOUDFLARE_WORKER_SHA: string
  }
}>()

app.use(mw1)
app.use(mw2)
```
When defining both `env` variables inside `Hono` app, it should have no TS error. We would need to define each missing variable inside middleware, but these middleware should be independent. 

### What is the expected behavior?

Having multiple different middlewares with different `env` variables should work. Merged types from the `Hono` app should work out of the box.

**Comment by yusukebe** [comment]
Hi @huv1k 

This might be fixed in new version "v3.6.2". Cloud you try it?

**Comment by huv1k** [comment]
I tried it, and it somehow works, but now when your app env variables are incorrect, you don't get a type error. So it can happen that you don't provide `env` variables required from middleware.

**Comment by yusukebe** [comment]
Hi @huv1k 

That is an expected behavior. It may indeed be that an error should be thrown, but the type checking is intentionally loose here. The following cases are allowed:

```ts
const mw: MiddlewareHandler<{
  Bindings: {
    ENVIRONMENT: 'prod' | 'staging' | 'dev'
  }
}> = async (c, next) => await next()

const app = new Hono()

app.use(mw)
```

The reason for this is to maintain backward compatibility. Also, middleware may override Env type definitions:

```ts
const echoMw: MiddlewareHandler<{
  Variables: {
    echo: (str: string) => string
  }
}> = async (c, next) => await next()

const app = new Hono()

app.get('/', echoMw, (c) => {
  return c.text(c.var.echo('Hi'))
})
```

**Comment by huv1k** [comment]
I get it, I would rather have something stricter to make it bullet proof 😅 but what can one man do 🤷
