### ISSUE TITLE
Single route router

### ISSUE THREAD

**Issue by Soviut** [honojs/hono#1475]
### What is the feature you are proposing?

I'm building a CloudFlare Worker that only does a single task (sends email) and therefore doesn't really need a router. I'm using Hono because I want nicer request/response handling and middleware.

I'm proposing a "no router" or "single route router" to keep things even lighter.

If something like this is already possible, then documenting it would be useful since I'm not the only one who would want to use Hono for their single-task workers.

**Comment by zisra** [comment]
```js
app.get('*', (c) => c.text('Hono!'))
``` 
This should do the trick

**Comment by Soviut** [comment]
@zisra Thanks, but this is what I'm already doing. I'm suggesting a special router be made that only does the above so that deployment could be even lighter.

**Comment by yusukebe** [comment]
Hi @Soviut 

Thank you. That's a good idea.

However, Hono is already lightweight. `PatternRouter` is about 1KB and [`hono/tiny`](https://hono.dev/api/presets#hono-tiny) using only that is 12KB. Also, if you take fewer routes, the performance is not bad.

<img width="594" alt="Screenshot 2023-09-17 at 18 50 04" src="https://github.com/honojs/hono/assets/10682/dfc2d4e3-e613-44a8-85fa-99774d37a3d7">

Is this not good enough?

**Comment by Soviut** [comment]
It's definitely good enough, I just figured that there might be an opportunity to entirely avoid a router in this case.

**Comment by yusukebe** [comment]
This issue can be closed!
