### ISSUE TITLE
Select which endpoint is protected with jwt

### ISSUE THREAD

**Issue by fjpedrosa** [honojs/hono#1477]
### What is the feature you are proposing?

Basicaly, I see [here](https://hono.dev/middleware/builtin/bearer-auth) how to protect a single endpoint with a bearer token. In addition, I see [this](https://hono.dev/middleware/builtin/jwt) to implement authentication by verifying the token with JWT. 
However, while in the first case you can select one by one the endpoints that you want to protect, in the second case it is established that all endpoints with a route `/auth/*` will be protected, It would be nice to implement jwt token verification as in the first case.

**Comment by kielingraphael** [comment]
Do you mean?

```js
app.get('/auth/page', jwt({ secret: 'it-is-very-secret' }), (c) => {
  const payload = c.get('jwtPayload')
  return c.json(payload)
})
```

If yes, `jwt` it's just a middleware you can do it.

**Comment by fjpedrosa** [comment]
ahhh thank so much!

**Comment by yusukebe** [comment]
This issue seems to be closed. If you have still problem, please reopen.
