### ISSUE TITLE
make context available within JSX similar to children

### ISSUE THREAD

**Issue by RussellSanders1** [honojs/hono#1478]
### What is the feature you are proposing?

Unless there is already a way to manage globals that isn't just an actual global `let`, I'm thinking it might be nice to have things like`c.get` within JSX for shared variables to get around things like prop-drilling that would normally be handled by React's Context API.

Interested to hear what others think about this idea, or if this is an obviously bad idea.  There are probably other ways to achieve this result, but I thought it could be handled by the JSX middleware.

example typedef: `type FC<T = Props> = (props: T & { children?: Child; c: Context }) => HtmlEscapedString`

**Comment by yusukebe** [comment]
Hi @RussellSanders1 

This is a very interesting proposal and a feature I would like to have. However, I feel it is difficult to pass `Context` to a component.

@usualoma :

What do you think?

**Comment by sjc5** [comment]
We do something similar in Hwy for page components (passing in Hono Context by default). See [Page Components](https://hwy.dev/docs#page-components).

I think the problem with doing this as a built-in feature though is that it would conflict with any real-world usage of props named `c`. That is probably a little too heavy handed for Hono in my opinion, as convenient as it would be. I think Hono's JSX renderer should be as agnostic and cross-compatible as possible.

So I would recommend not building this in, but I'd love to hear if others disagree.

**Comment by usualoma** [comment]
Hi @yusukebe!

When I solve this problem I implement it like #1496.

### Introduce "Context" API for JSX.

First, implement the same API as React to handle "context". This will allow us to pass contexts without passing properties in the general API.

### Introduce jsx renderer.

Since we want to hide the context initialization process and simplify it, we provide this process with something called jsx-renderer. 

### Result

As shown below, any component can retrieve and output values from the context of the current request.

```ts
import { jsx, type FC } from './jsx'
import { createRenderer, useRequestContext } from './jsx-renderer'

const RequestUrl: FC = () => {
  const c = useRequestContext()
  return html`${c.req.url}`
}

app.use('/*', async (c, next) => {
  c.setRenderer(
    createRenderer(c, (children, head) => (
      <html>
        <head>{head.title}</head>
        <body>{children}</body>
      </html>
    ))
  )
  await next()
})

app.get('/page', (c) => {
  return c.render(
    <h1>
      <RequestUrl />
    </h1>,
    { title: 'page title' }
  )
})
```

**Comment by yusukebe** [comment]
Hi @usualoma 

Very interesting approach, and a good solution as I was trying to figure out how to get the `Context` in the Function Component. We'll have to spend some time thinking about this, including whether to adopt it. I will try to use this feature from now on. Thanks!

**Comment by yusukebe** [comment]
@usualoma 

I have a few minor comments, but generally agree! I have tried it on my other projects and it looks good.

cc: @yudai-nkt 

What do you think of this feature?

I think it's not a bad idea for `hono/jsx` to become more React-like.

**Comment by yudai-nkt** [comment]
Basically LGTM. The return type of `useRequestContext` is `Context<any, any, {}>` and my two cents is if this could be more specific by passing type parameters like `useRequestContext<T, U, V>`. This might be useful when users want to define components that are only used in limited routes (e.g., those with a certain named path parameters). However I'm not sure whether there will be such use cases and it might be not worth the implementation effort.

**Comment by yusukebe** [comment]
@yudai-nkt Thanks!

I thought the same thing. I will comment on that later in #1496.

@usualoma I will comment later in #1496.

**Comment by yusukebe** [comment]
Hi @usualoma 

How about creating a JSX Renderer **Middleware**?

```tsx
import { createRenderer } from 'hono/jsx-renderer'

app.get(
  '*',
  createRenderer(({ children, head }) => (
    <html>
      <head>
        <title>{head.title}</title>
      </head>
      <body>{children}</body>
    </html>
  ))
)
```

**Comment by usualoma** [comment]
@yusukebe @yudai-nkt
Thanks for the feedback.
I updated https://github.com/honojs/hono/pull/1496

I was thinking that if we were to change "jsx-renderer" to middleware format, we could export the "Renderer" from "context.ts" and use that to make it look like this.
0a333f6 f5fa2f5

As for the `Context<any, any, {}>` issue, how about a simplified implementation like this? I felt that if we could pass the first parameter, Env, for the time being, there would be some use case.
3c1fe4e

**Comment by yusukebe** [comment]
@usualoma 

**JSX Renderer Middleware**  is so cool! I like this API:

```tsx
app.get(
  '/pages/*',
  jsxRenderer(({ children }) => (
    <html>
      <body>{children}</body>
    </html>
  ))
)
```

It is also nice to be able to specify the `jsxRenderer` type with `ContextRenderer`.

I think the implementation is good for the `Context<any, any, {}>` issue as well. Since we can do the following:

```tsx
const fc: FC = () => {
  const c = useRequestContext<{ Variables: Variables }>()
  return <p>{c.var.foo}</p>
}
```

**Comment by yusukebe** [comment]
Hi @usualoma 

I want to go with #1496 . Could you complete it?

**Comment by janat08** [comment]
Was this suppose to support use of useRequestContext within the layout component itself, or am I suppose to extend it with params for context? I'm trying to show conditional login/logout buttons depending on if user is logged in.

**Comment by usualoma** [comment]
Hi, @janat08!

The `createContext()` and `useContext()` can be used anywhere without using `jsxRenderer()`.
https://github.com/honojs/hono/blob/main/src/jsx/index.test.tsx#L491-L544

If you are using `jsxRenderer()`, `useContext()` will be called in it to set the `Context`, so you can call `const c = useRequestContext()` in the JSX component returned from the handler to get the current Context.
https://github.com/honojs/hono/blob/main/src/middleware/jsx-renderer/index.test.tsx#L238-L281

**Comment by janat08** [comment]
[ERROR] Error: RequestContext is not provided.  
app.get(
  '/page/*',
  jsxRenderer(Layout)
)
    console.log('context', useRequestContext())

**Comment by mipopon** [comment]
@janat08 you can use `setRenderer` and access the request context.

```typescript
app.get('page/*', async (c, next) => {
        const isLoggedIn = getCookie(c, 'isLoggedIn');

        c.setRenderer((content) => c.html(<Layout isLoggedIn={isLoggedIn}>{content}</Layout>));
        await next();
    })
```
