### ISSUE TITLE
Request for Next.js App router mode support

### ISSUE THREAD

**Issue by nabeken5** [honojs/hono#1479]
## Overview
The current `hono/vercel` doesn't appear to support the App Router mode of Next.js 13.
App Router is recommended by Vercel and should be supported.

## Detail
In App router mode in Next.js 13, I got this error with `/api` route created as [documented](https://hono.dev/getting-started/vercel).
```
- error Detected default export in '{MASKED}/hono-next13-support-repro/src/app/api/[...route]/route.ts'. Export a named export for each HTTP method instead.
- error No HTTP methods exported in '{MASKED}/hono-next13-support-repro/src/app/api/[...route]/route.ts'. Export a named export for each HTTP method.
```
(but moved the file location from `/pages/api/[...route].ts` to `/app/api/[...route]/route.ts`. See [this document](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) for details.)

I think this error is caused by the transition from App Routes to Route Handlers, where the function that does the export has been changed from handler() to GET(), etc.

Keep in mind that if this problem is corrected, it will no longer be compatible with Page Router.

I've created a [repository](https://github.com/nabeken5/hono-next13-support-repro) that reproduces this issue, please refer to it.

## Proposed Solution

- Rename the current `handle` function to something like `legacyHandle`.
- Create a new `handle` function that exports a function that resolves requests per mesot.
  I don't think it is very cool to import & export handle functions separately for each method used.
  It would be nice if it could be solved with one function as it is now, but I don't know of any way to do that.

**Comment by yusukebe** [comment]
Simply rewrite as follows:

```ts
export const GET = handle(app)
```

**Comment by yusukebe** [comment]
Or, you can write it without the adapter as follows.

```ts
import { Hono } from 'hono'

export const config = {
  runtime: 'edge'
}

const app = new Hono().basePath('/api')

app.get('/hello', (c) => {
  return c.json({
    message: 'Hello Next.js!'
  })
})

export const GET = app.fetch
```

**Comment by nabeken5** [comment]
My problem is now solved. Thank you so much. I will close this Issue.
May I submit a PR to add this method to the documentation?

**Comment by yusukebe** [comment]
Hi @nabeken5 

That was great!

> May I submit a PR to add this method to the documentation?

Ah, yes please! You can add the description to [this page](https://hono.dev/getting-started/vercel) and the repo is [here](https://github.com/honojs/website).

Thanks!
