### ISSUE TITLE
Add support for reverse proxy

### ISSUE THREAD

**Issue by allmors** [honojs/hono#1491]
### What is the feature you are proposing?

I hope to add support for reverse proxy. It supports functions similar to http-proxy-middilware in hono app.use. If someone can tell me how hono implements the reverse proxy function of cfworkers, it would also be great.

**Comment by yusukebe** [comment]
Hi @allmors 

I think it is not needed. We can write a reverse proxy with this code:

```ts
import { Hono } from 'hono'

const app = new Hono()

app.all('*', async (c) => {
  const res = await fetch(c.req.raw)
  // ...
  const newResponse = new Response(res.body, res)
  // ...
  return newResponse
})

export default app
``

Related: #1414

**Comment by yusukebe** [comment]
@allmors 

Which platform do you run it on? Perhaps, you don't set up an "origin". If you don't have it, you can specify a url:

```ts
app.all('*', async (c) => {
  const res = await fetch('http://example.com') // <==
  console.log(res.status)
  // ...
  const newResponse = new Response(res.body, res)
  // ...
  return newResponse
})
```

**Comment by yusukebe** [comment]
For Cloudflare Workers, the following will not work without an origin.

```ts
const res = await fetch(c.req.raw)
```

However, if you just want to proxy, the following may be sufficient, what do you think?

```ts
const res = await fetch('https://fabfilters.online/', c.req.raw)
```

**Comment by kongminh113** [comment]
> For Cloudflare Workers, the following will not work without an origin.
> 
> ```ts
> const res = await fetch(c.req.raw)
> ```
> 
> However, if you just want to proxy, the following may be sufficient, what do you think?
> 
> ```ts
> const res = await fetch('https://fabfilters.online/', c.req.raw)
> ```

Hi, I have tried the above code on Nodejs but it not proxy to example.com URL. Is it only work in Cloudfare ??

**Comment by yusukebe** [comment]
Hi @kongminh113 !

Thanks! It seems to be a bug! I've created the issue: https://github.com/honojs/node-server/issues/121
