### ISSUE TITLE
Cannot set statusText and default HTTP statusText per status not supplied

### ISSUE THREAD

**Issue by runspired** [honojs/hono#1503]
### What version of Hono are you using?

3.7.2

### What runtime/platform is your app running on?

Bun, Node

### What steps can reproduce the bug?

return a new `Response` from any handler, for instance

```ts
return new Response('I am the payload', {
    status: 200,
    statusText: 'OK,
 });
```

make a request to this endpoint, observe statusText returned as `''`

### What is the expected behavior?

statusText should be used from the supplied `Response` if available and default to the spec values https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

### What do you see instead?

and empty string

**Comment by NicoPlyley** [comment]
I just tested statusText and it is working. You can see the test [here](https://github.com/honojs/hono/blob/731957aea20b63099b5d39a735fe9f0ea8c81bca/src/hono.test.ts#L46). And how it was implemented on lines 25 - 30.

However, unless there is a specific need, like for compatibility, I would recommend using the response body for any custom messages. The statusText is deprecated in http/2 and up.

**Comment by NicoPlyley** [comment]
Can you also specify the exact runtime you have the issue on, is it specific to node, bun, or both?

**Comment by runspired** [comment]
I'm running mostly in node due to lack of http/2 support in Bun. I should remove Bun from the report I didn't go confirm it there since there wasn't http/2 support. Didn't realize http/2 had removed the statusText property.
