### ISSUE TITLE
File Objects posted with `multipart/form-data` are not parsed into a File

### ISSUE THREAD

**Issue by sor4chi** [honojs/hono#1508]
### What version of Hono are you using?

3.7.2 (latest)

### What runtime/platform is your app running on?

Cloudflare Workers (miniflare)

### What steps can reproduce the bug?

repro repo: https://github.com/sor4chi/hono-repro-file-parse-body

```ts
const app = new Hono()

app.post('/', async (c) => {
  const formData = await c.req.parseBody()
  const file = formData['file']

  if (file instanceof File) {
    return c.text('File!')
  }
  return c.text('Not File!')
})

const formData = new FormData()
const file = new File(['Hello Hono Storage 1\n'], 'sample1.txt')
formData.append('file', file)

const res = await app.request('http://localhost/', {
  method: 'POST',
  body: formData,
})

console.log(await res.text()) // expected: "File!", actual: "Not File!"
```

### What is the expected behavior?

The posted files parse to File object.

### What do you see instead?

The posted files parse to File string.

### Additional information

https://twitter.com/monica18_pr/status/1706194484864958708

**Comment by yusukebe** [comment]
Hi @sor4chi 

This is not a Hono problem, but probably a `vitest-environment-miniflare` problem. If you remove the following line in `vitest.config.ts` and use the native Node.js API, the test should pass.

https://github.com/sor4chi/hono-repro-file-parse-body/blob/f34bea873fe2b88d185fd972aaf978529d203fce/vitest.config.ts#L7

Also, the following apps that do not use Hono behave the same way.

```ts
const app = {
  fetch: async (req: Request) => {
    const formData = await req.formData()
    const file = formData.get('file') as unknown
    if (file instanceof File) {
      return new Response('File!')
    }
    return new Response('Not File!')
  }
}
```

**Comment by sor4chi** [comment]
Hi @yusukebe 
Thanks for answering it!

Yeah... I seemed to have made a wrong assumption

remove miniflare environment and change like this

```diff
+ new File(['Hello Hono Storage 1\n'], 'sample1.txt')
- new Blob(["Hello Hono Storage 1"], { type: "text/plain" });
```

it resolved!
