### ISSUE TITLE
ctx.response helper

### ISSUE THREAD

**Issue by vanodevium** [honojs/hono#1515]
### What is the feature you are proposing?

First of all, I want to thank you for a great and functional framework! I enjoy using it.

--- 

I think it would be very useful to have a `ctx.response()` method that would receive a fetch call promise and return immediately the formed response, including content, headers, status, etc.

For example, the following queries:

- `return ctx.response(fetch('https://super.site.com'));` will return html with correct content-type
- `return ctx.response(fetch('https://super.site.com/some/path'));` will return html with correct content-type
- `return ctx.response(fetch('https://super.site.com/app.js'));` will return js content with correct content-type
- `return ctx.response(fetch('https://super.site.com/app.css'));` will return css content with correct content-type
- `return ctx.response(fetch('https://super.site.com/app.png'));` will return image content with correct content-type

--- 

I completely understand that this can be done manually using the `new Response()`, but it will be much more comfortable that way.

**Comment by vanodevium** [comment]
@yudai-nkt 

Sure. Thanks!

But my point is another.

Let's imagine that I want to return a large file, say 1GB, in this way.

It seems to me that the pipe will not work like that. I would like to.
Because RAM isn't unlimited anyway.

**Comment by yudai-nkt** [comment]
I'm afraid I don't quite understand how it relates to the requested feature. Could you elaborate on that?

**Comment by vanodevium** [comment]
Maybe I really explained poorly, sorry for that.

I will try again.

I want a **ctx.response()** helper to which we can simply pass an URL, and the function itself can already return the entire file or the entire html via a pipe. Perhaps with the use of streams.

It's very similar to a proxy, I understand that.

Example:

```js
return ctx.response('https://video-server.com/an-1gb-video.file')
```

And this big file would returned to browser without full download to server RAM.

**Comment by yusukebe** [comment]
Hi @vanodevium 

Isn't the following good enough?

```ts
app.get('/video', () => {
  return fetch('https://video-server.com/an-1gb-video.file')
})
```

**Comment by vanodevium** [comment]
@yusukebe 

I found answer for my question on [this](https://github.com/honojs/node-server/blob/main/src/listener.ts#L81) and [this](https://github.com/honojs/node-server/blob/main/src/listener.ts#L83) lines in the node adapter.

Thanx!
