### ISSUE TITLE
typo on site

### ISSUE THREAD

**Issue by vanodevium** [honojs/hono#1521]
### What version of Hono are you using?

latest

### What runtime/platform is your app running on?

web

### What steps can reproduce the bug?

[on site](https://hono.dev/api/routing#including-slashes) 

I see example

```js
app.get('/posts/:filename{.+.png$}', (c) => {
  //...
})
```

But this regexp is incorrect because when we want paths with `.png`, we have to escape dot

So example have to be

```js
app.get('/posts/:filename{.+\\.png$}', (c) => {
  //...
})
```

**Comment by vanodevium** [comment]
@NicoPlyley 

> However, you do have and additional '' in your example.

Sorry, I don't understand. Please describe what is additional

**Comment by NicoPlyley** [comment]
@vanodevium  It was a backslash, GitHub didn't like how I formatted it I guess.

**Comment by vanodevium** [comment]
Without this double backslash regex will not work. I tested.

**Comment by vanodevium** [comment]
I'll create PR for website. Thanks!

**Comment by NicoPlyley** [comment]
@vanodevium My mistake, I forgot javascript you have to use 2 for escapes.
