### ISSUE TITLE
Response headers get discarded without using context

### ISSUE THREAD

**Issue by joshamaju** [honojs/hono#1526]
### What version of Hono are you using?

3.7.2

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

Sending a response using any context method i.e `html`, `text` etc doesn't work the same way when you just return a `Response` object. Headers don't get set when using `Response`

```js
const app = new Hono();

app.get('/', ctx => {
  setCookie(ctx, 'cookie', 'value');
  return ctx.text('html')
})
```

The cookie header gets discarded in the example below, while it works fine in the example above

```js
const app = new Hono();

app.get('/', ctx => {
  setCookie(ctx, 'cookie', 'value');
  return new Response('html', {'Content-Type': 'text/html'})
})
```

### What is the expected behavior?

There should be not difference in behaviour, cookies should get set in both scenarios

### What do you see instead?

Cookies get discarded in the other example

### Additional information

[Reproduction](https://github.com/joshamaju/hono-handler-response-issue)

**Comment by EdamAme-x** [comment]
It seems to me that the object created by `new Response` is different from the response created by `context`, is it not...?

**Comment by yusukebe** [comment]
@joshamaju 

It's not a bug, expected behavior. If a `Response` object is returned, it will be used as the response.

**Comment by joshamaju** [comment]
Yes, but the headers set to the context object should be included in the response

**Comment by joshamaju** [comment]
Are you saying no one can use the cookie helper library unless they use the context object to send responses? Which doesn't make sense to me

**Comment by EdamAme-x** [comment]
The Response object should be able to contain cookie information. However, the context and Response objects are completely different, so you probably cannot use them, although I am not sure what the wrapper is referring to.

**Comment by joshamaju** [comment]
The context object attaches any headers set using, for example the cookie helper. Why can't the same be done when generating a response without using the context object.

There's no explanation why this is difficult to implement, or why it would be a bad design, just a hastiness to close the issue. And just to be sure I'm not asking for something ridiculous, I checked sveltekit and h3, they handle this easily.

**Comment by joshamaju** [comment]
And your stance is confusing @yusukebe , you refuse to make it possible for 3rd-party libraries to extend the context object to attach additional helper methods. And when users decide they're going to find a work around, you screw them over by discarding everything else they can do with other built-in helper libraries.

**Comment by yusukebe** [comment]
The `setCookie()` affects the Context object. The Context object holds the headers information and returns a `Response` object with the those headers when `c.text()` or `c.json()` is called. That is why Context exists.

On the other hand, `new Response()` is a low-layer API for Hono; it has nothing to do with Context.

[Response - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/Response)

So please use `c.text()` or `c.json()`.

**Comment by joshamaju** [comment]
So are you saying when a handler returns a response hono cannot attach headers to the response before delivering it to the client? And if that's the case, what makes that impossible?

hattip and h3 allow you to send a custom `Response` object and they still set headers applied to the `event`/`context` object.

**Comment by yusukebe** [comment]
@joshamaju 

You can use middleware to modify response headers:

https://hono.dev/guides/middleware

**Comment by joshamaju** [comment]
I don't understand your suggestion, I don't see how that solves the problem. And you're not addressing anything that was said.

**Comment by erwin-kort** [comment]
Hello, here's how I got around this:
```javascript
c.res = c.newResponse(null, {
  status: 101,
  webSocket: client,
})

setCookie(c, 'GID', gid, {
  path: '/',
  secure: true,
  domain: 'redacted',
  httpOnly: true,
  maxAge: 2592000,
  sameSite: 'Strict',
})

return c.res
```

**Comment by pilcrowOnPaper** [comment]
Agree with @joshamaju here. It should be explicitly mentioned in the docs that none of the `Context` helpers won't work when you return a raw `Response`.Major frameworks that provide a cookie helper (including SvelteKit, Next.js, Astro) set cookies even when a `Response` is returned so many users have that expectation. IMO, response helpers shouldn't be inside of the `Context` object if you can't modify that request context under certain conditions. It's just confusing API design. Separating it to a separate `res` object from example makes the distinction clear:

```ts
app.get("/", (context, res) => {
  if (condition) {
    return new Response();
  }
  res.headers("Set-Cookie", cookie.serialize());
  return res.json();
}
```

**Comment by revskill10** [comment]
I think it's elegant design. Because it's explicit.

What if you return `new Reponse` and suddenly a bunch of "implicit headers" is set ? How can you "unset" them ?

**Comment by pilcrowOnPaper** [comment]
@revskill10 I don't see it see a bug per se, just that it should be mentioned in the docs for clarity and that we could improvise the API to make the intent more clear

**Comment by wesleycoder** [comment]
Just my 2 cents here is that this is common behavior on other libs like oak, Koa, express, fastify. An example in the docs would be welcome, but maybe not required.
This behavior is intended and useful.
Being able to send a totally new response is what enable us to for example make a transparent bridge or proxy to another service.
To add a cookie on a new response you can definitely set a cookie on the new response object directly using their headers prop (https://developer.mozilla.org/en-US/docs/Web/API/Response/headers) and some lib that can create cookies for a response object like https://www.npmjs.com/package/cookie
