### ISSUE TITLE
Rename `middleware` to `createMiddleware`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1530]
### What is the feature you are proposing?

I want to rename `middleware()` in `hono/factory` to `createMiddleware()`. That way it is easier to understand what we want to do.

```ts
import { createMiddleware } from 'hono/factory'

const mw = createMiddleware<{ Variables: Variables }>(async (c, next) => {
  // ...
  await next()
})
```

It is an `experimental` API, so we can change it without an announcement.

BTW, you should use this method when creating middleware. With the following method, you need to write the type, and it may not be able to infer well.

```ts
/// Not so good:
const mw = async (c: Context<{ Variables: Variables }>, next: Next) => {
  // ...
  await next()
}
```

**Comment by arunavabasu-03** [comment]
@yusukebe can I work on this !

**Comment by yusukebe** [comment]
@arunavabasu-03 Yes you can do it!

**Comment by yusukebe** [comment]
We can close this! Thanks.
