### ISSUE TITLE
Add `basePath` option for the constructor of Hono

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1531]
### What is the feature you are proposing?

Now, to set the "basePath”, we use the `basePath()` function:

```ts
const app = new Hono().basePath('/api')
```

I propose that we can set the "basePath" by passing the `basePath` option to the constructor of `Hono`:

```ts
const app = new Hono({
  basePath: '/api'
})
```

With this way, we don't have to do `clone()`.

Also, since most use cases, user set `basePath()` when instantiating `Hono`, how about deprecating `basePath()` and making it obsolete in v4? We can also remove `clone()`.

**Comment by yusukebe** [comment]
@usualoma 

What do you think about this? I think we should do this to simplify the code.

**Comment by arunavabasu-03** [comment]
@yusukebe  it is great , can I do this one ?

**Comment by yusukebe** [comment]
Hi @arunavabasu-03 !

This feature needs to be implemented carefully, so I will do it. But thanks!
