### ISSUE TITLE
bun build --target=bun displays [object Object] for JSX

### ISSUE THREAD

**Issue by Spioune** [honojs/hono#1534]
### What version of Hono are you using?

3.7.3

### What runtime/platform is your app running on?

Bun 1.0.3

### What steps can reproduce the bug?

index.tsx
```
import { Hono } from "hono";
const app = new Hono();

app.get("/", async (c) => c.html(<div>hello</div>));

export default {
  port: 3000,
  fetch: app.fetch,
};
```
tsconfig.json
```
{
  "compilerOptions": {
    "jsx": "preserve",
    "jsxFactory": "jsx",
    "jsxFragmentFactory": "Fragment",
    "jsxImportSource": "hono/jsx"
  }
}
```
`bun build ./index.tsx --target=bun --outdir ./build`
`bun run ./build/index.js`
```
// http://localhost:3000
[object Object]
```

### What is the expected behavior?

I expect the webpage to show `hello`

### What do you see instead?

The webpage return `[object Object]`

### Additional information

This issue only happens with target=bun

`bun build ./index.tsx --target=node --outdir ./build` OK
`bun build ./index.tsx --target=browser --outdir ./build` OK
`bun build ./index.tsx --target=bun --outdir ./build` NOT OK

**Comment by NicoPlyley** [comment]
@Spioune How are you running the application? I am having no issues with it at all using `bun build ./index.tsx --target=bun --outdir ./build`

**Comment by Spioune** [comment]
after `bun build ./index.tsx --target=bun --outdir ./build`
I run the app with `bun run ./build/index.js`

**Comment by NicoPlyley** [comment]
@Spioune I have followed everything including the versions on bun and hono and I cannot replicate it. To confirm the url you are going to is `http://localhost:3000/` correct?

Can you try changing the port to see if there is some caching issues you having from using that port before

**Comment by NicoPlyley** [comment]
And to confirm using `bun run dev` works just fine?

**Comment by Spioune** [comment]
Just to make sure I created a new folder,
`bun add hono`,
listen on port 3001,
clear cache,
use safari,
but still show `[object Object]`
weird...

`bun run dev`(which is a script for `bun run --watch index.tsx` in my package.json) works as expected

**Comment by Spioune** [comment]
here is the resulting built index.js file https://pastebin.com/bfbVKryS

**Comment by Spioune** [comment]
oops, the index.js pastebin listens on port 3002.
If you `bun run index.js` and go to localhost:3002, do you see `hello` ?

**Comment by NicoPlyley** [comment]
What os are you using. I am getting the same error.

Mine outputs

```js
app.get("/", async (c) => c.html(jsxDEV("div", {
  children: "hello"
}, undefined, false, undefined, this)));
```

While yours does

```js
app.get("/", (c) => c.html({
  $$typeof,
  type: "div",
  key: null,
  ref: null,
  props: {
    children: "hello"
  },
  _owner: null
}));
```

**Comment by Spioune** [comment]
I am on macos ventura 13.5.
I uninstall bun (I had the homebrew version) and reinstalled with `curl -fsSL https://bun.sh/install | bash`
now Bun version is 1.0.4 but still same problem

**Comment by Spioune** [comment]
OK, after installing Bun 1.0.4 with the bash script I initially said that it didn't fix the issue.
But now it is working... (maybe needed to close the terminal between uninstalling/reinstalling ?)
But, to double-check, I uninstalled bun 1.04 and reinstalled 1.0.3 WITH HOMEBREW
...and it is still working
I don't know what happened here. Maybe a cache issue.

Sorry for wasting your time and thank you for you help
