### ISSUE TITLE
waitUntil (executionCtx) issue - [TypeError: Cannot read properties of undefined (reading 'push')]

### ISSUE THREAD

**Issue by dihmeetree** [honojs/hono#1538]
### What version of Hono are you using?

3.7.3

### What runtime/platform is your app running on?

Vercel Edge Functions (Cloudflare Workers)

### What steps can reproduce the bug?

I have a Vercel Edge Function that looks like this:
```js
export const createTodo = async (c: Context) => {
  // ... other code here
  // Send event to Inngest
  c.executionCtx.waitUntil(
    inngest.send({
      name: 'todo.process',
      data: {
        id: 'id_here',
      },
    })
  )
  // Return the data instantly (without waiting for event to finish sending)
  return { data: ... }
}
```

This sends an event to Inngest (https://www.inngest.com) using their client.

However, if I do the following (without Hono), it works just fine (no error):
```js
import type { NextFetchEvent } from 'next/server'
import { Inngest } from 'inngest'

export const config = {
  runtime: 'edge',
}

const inngest = new Inngest({ name: 'test' })

export default function MyEdgeFunction(
  request: Request,
  context: NextFetchEvent
) {
  context.waitUntil(
    inngest.send({
      name: 'todo.process',
      data: {
        id: 'id_here',
      },
    })
  )
  return new Response(`Hello, from ${request.url} I'm an Edge Function!`)
}
```

So i'm assuming this is a Hono specific issue.

### What is the expected behavior?

The Inngest event should be sent just fine (with no error)

### What do you see instead?

I'm getting the following error:

```
[TypeError: Cannot read properties of undefined (reading 'push')]
```

Nothing else besides this.

**Comment by yusukebe** [comment]
Hi @dmitryyankowski 

Thanks for the detailed explanation. I've release v3.7.4 just now. It includes the fix for this issue. Try it.

**Comment by yusukebe** [comment]
Cool!
