### ISSUE TITLE
getCookie can't handle JSON Objects as cookie value

### ISSUE THREAD

**Issue by niklasgrewe** [honojs/hono#1551]
### What version of Hono are you using?

3.7.5

### What runtime/platform is your app running on?

Nodejs

### What steps can reproduce the bug?

set a cookie clientside with the following code:

```js
function setCookie(cName, cValue, expDays) {
  let date = new Date();
  date.setTime(date.getTime() + expDays * 24 * 60 * 60 * 1000);
  const expires = "expires=" + date.toUTCString();
  document.cookie = cName + "=" + cValue + "; " + expires + "; path=/";
}

const device = { type: "desktop", mode: "browser"};

setCookie("device", JSON.stringify(device), 30);
```
read the cookie serverside using `getCookie` function:

```js
app.get('/', async (c) => {
   console.log(getCookie(c, "device"));
})
```

### What is the expected behavior?

get the following output:
```
'{"type":"desktop","mode":"browser"}'
```

### What do you see instead?

output:
```
{}
```

### Additional information

it still worked in version `v3.4.3`

**Comment by yusukebe** [comment]
Hi @niklasgrewe 

I can't reproduce the bug. Can you show me the minimal project to reproduce this bug?

Just for setting and getting JSON value, it works well:

```ts
app.get('*', async (c, next) => {
  setCookie(
    c,
    'key',
    JSON.stringify({
      foo: 'bar',
    })
  )
  await next()
})

app.get('/', (c) => {
  return c.text(getCookie(c, 'key') ?? '')
})
```

**Comment by ItsWendell** [comment]
@yusukebe I'm running into the exact same issue:

![image](https://github.com/honojs/hono/assets/591280/447e9aa3-272c-47a4-937b-447dc1e81fa4)

Code:
```
api.get("/__cookies", (ctx) => {
  const cookies = getCookie(ctx);
  return ctx.json({
    cookies: cookies,
  });
});
```

The same is the case for objects `{}` or arrays `[]`

**Comment by yusukebe** [comment]
Hi @ItsWendell 

One question. Do you use `setCookie` imported from `hono/cookie`?

```ts
import { setCookie } from 'hono/cookie'
```

**Comment by ItsWendell** [comment]
> One question. Do you use `setCookie` imported from `hono/cookie`?

I've actually directly changed the cookie in this example above that I posted within Chrome Dev Tools, but good chance indeed that it doesn't serialize it properly there, in another script I used a very simple setCookie function (it's a webflow website I was working in doing this, so this simply as header script):

```js
function setCookie(name, value, daysToExpire) {
  var expires = "";
  if (daysToExpire) {
    var date = new Date();
    date.setTime(date.getTime() + daysToExpire * 24 * 60 * 60 * 1000);
    expires = "; expires=" + date.toGMTString();
  }
  document.cookie =
    name + "=" + (value || "") + expires + "; domain=.haaven.com; path=/";
}
```

**Comment by yusukebe** [comment]
@ItsWendell Thanks! I see.

Hey @Jxck , do you have any thoughts about this issue?

**Comment by Jxck** [comment]
as @ItsWendell mentioned above. DQUOTE SHOULD NOT be in cookie octet (say cookie value).
It means JSON is not suitable for Cookie value. You can encode in other ways like base64, urlencode, structured-field-values, JWT etc etc .

**Comment by yusukebe** [comment]
@Jxck 

Thanks. Understood well!
