### ISSUE TITLE
[create-hono] Make the app name change based on a project name

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1563]
### What is the feature you are proposing?

Currently, the application name of a project created by `create-hono` is fixed as `my-app`. This is bad for DX as we can only use a fixed name. Therefore, we need to modify `create-hono` so that the application name is based on the directory name.

**Comment by sor4chi** [comment]
Hi, @yusukebe 
Does that mean that all the parts inside of the template app that are `my-app` should be dynamic?

**Comment by sor4chi** [comment]
As for the directory name, like this video

Unspecified -> asking (default is `my-app`)
specified -> folder name (`. `)

How about this?

https://github.com/honojs/hono/assets/80559385/a5dc7fb4-a0c9-433b-bf68-c3b7792ee848

**Comment by yusukebe** [comment]
Hi @sor4chi,
 
Super cool! I love it.

**Comment by yusukebe** [comment]
> Does that mean that all the parts inside of the template app that are my-app should be dynamic?

Ideally, yes. But actually, we don't do that.

As you mentioned, the `name` field in `wrangler.toml` should be dynamic:

https://github.com/honojs/starter/blob/main/templates/cloudflare-workers/wrangler.toml#L1

Alternatively, we could make the `name` field in `package.json` dynamic. However, since Deno has no config files, we don't apply that to all templates.

Anyway, I think we should make it flexible.

**Comment by sor4chi** [comment]
In my plan.

Create a `REPLACE_FILE_LIST` and put some paths like `. /package.json` or `. /wrangler.toml`.

I would like to set `[DYNAMIC_APP_NAME]` for the part of `my-app` and try to replace `[DYNAMIC_APP_NAME]` in `REPLACE_FILE_LIST`.

What do you think?

**Comment by yusukebe** [comment]
Using "magic strings" like `[DYNAMIC_APP_NAME]` is good!

I think we can make a "hook". The hook will be fired after `clone`. The following is pseudo code:

```ts
type Hook = (args: { projectName: string; templateName: string; directoryPath: string }) => void

const cloudflareWorkersHook:Hook = (arg) => {
  if (arg.templateName !== 'cloudflare-workers') return
  const wranglerTomlPath = getWranglerTomlPath(arg.directoryPath)
  rewriteNameInWranglerToml(wranglerTomlPath, arg.projectName)
}
```

**Comment by sor4chi** [comment]
wow, nice idea! I will get on with it for now!

**Comment by yusukebe** [comment]
This can be closed! Thanks @sor4chi !
