### ISSUE TITLE
Allow object in SSE data

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1580]
### What is the feature you are proposing?

Currently, it only allows a string, but it would be useful if it allowed an object that will be serialized.

**Comment by sor4chi** [comment]
Does it mean such as `StreamAPI.log` written here?
https://github.com/honojs/hono/issues/914#issuecomment-1437900760

or like`c.objectStream()`?

**Comment by yusukebe** [comment]
It's only about SSE. I think it's useful if the content of `data` is an object, not a string, as it would be automatically serialized to JSON. But, it might not be necessary since users can encode it themselves.

```ts
stream.writeSSE({ data: JSON.stringify(dataObject) })
```

**Comment by sor4chi** [comment]
I understand.
I agree that it should be added only to Helper.

**Comment by yusukebe** [comment]
I think this is not needed for the helper. I'll close this now.
