### ISSUE TITLE
Validator doesn't support optional schemas

### ISSUE THREAD

**Issue by MonsterDeveloper** [honojs/hono#1583]
### What version of Hono are you using?

3.7.6

### What runtime/platform is your app running on?

-

### What steps can reproduce the bug?

Initially, I intended to report this issue to the `middleware` repository, but upon closer examination, it appears to impact all validators, not just the `zod-validator`. Currently, when an optional schema (e.g., `z.object({}).optional()`) is passed into the `zValidator`, the input type is inferred as follows:

```ts
{
  // or any other validation target
  query: {} | undefined
}
```

### What is the expected behavior?

Optional input type when a passed schema is optional.

### Additional information

Upon investigation, I have identified the root cause of this issue as the [`RemoveBlankRecord` type](https://github.com/honojs/hono/blob/b6c0e45d5f141f00578191f912d755230936eda2/src/utils/types.ts#L14).

Thus when calling a method with `hc`, it will still require the object to be present, even though it is optional: `client.index.$get({query: {}});`

Even if the function type of `zValidator` is adjusted to return an optional input (by adding `?`), the `RemoveBlankRecord` type inadvertently removes this optional type:
<img width="618" alt="CleanShot 2023-10-16 at 15 27 00@2x" src="https://github.com/honojs/middleware/assets/16190582/93512d51-c114-4b71-ba14-a7fcbb58f1b9">
[*Link to Playground*](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAIgAt0JiBuAKFElkTlIGNs8CiyKB6FgG2ABTNDGp1w0eDACeYIUwDC6GEIAeMADRwAssAAm+-kIDuAQyhDkZtEaFRtAUTQA3bQDUzg-WZjB0ACoWAOZCMADO2gFyQvoASkLhkGjhQtqKgiIwCQCOAK6JMADyYH7okXAAyiykQiBm7PiEcADk5BgtEgzwSC5eBr7QjZyt7RA8fd6DUJ30UnCy8kwAWhD61bX12qv6jlAEUMPNLQBea7OSjAgnOE1cZ-ric1dwGcKiCUnlCrcj3Bg8fTAcIwHiLRJ8TKiMExcLiGjqboLGIoCAQADWAB4Ak44OpVLZwnBnG44AAFPEaET6IkgqDANDBbRFOAAXkQWAAfGy4AAKGhwOCWcJ5fgwABcTBFLBYiXCkpgUAKVDgPhgZklAXYAB8pXkZXLJbgvKkVfYDpKdnsDiq1Rq4FqsJoBXAWJLlKJ8ZjHNoyZyaABKNncz7JVJwXVkzjAoSY0Pfbm6lwQAwR8nR1JxxJhhRJlP6RMOmLxbPfTFFf00cEoMzhACqtiEuAZsWx3PZeUbzbQsUpBJpDrgAH4FkqFEaTUIaAi1EiWOV4CdPFMYEN2ZiXVr8dSiTsNnUzM7BUEoKF4NvCXB0UIZBBcHBlwMymgT2fIi7HH2d8TXEfyV-LzpBkmRdABJHkTgAOgZMA8hgNs-xZdkoIgODYPggJOT-dwAIHBAXUFBlJWsesuxbfRMVA7kLwHRUCgIwVhyYABtABpOAGQdEIwgAXSHSVwKwBjBUlJA2I4tAuNPXiBOwWhGLgVCJRY9jONfGS4BZLB5PYdl8IUoia1I-Qm3IyjqKpS86KnBTBRHMTVMk9SYD42ShNsuBRLgcS1O4ly3J0wUlK8nynL8njJS0nSnRoTl+UFdVpOU5y-3CGoD01P9yAxfjUQxTEoIZXB7AQ4lfX9ANJT0QxjHMSxrFsYwoG9X0PHbf1BUmJ9oF5RKz20WsZDQNheUmAptBYINWW5fTGPnFJ4GFUV4HZMxzGAeA0s2MxIPCMxirJCxUgAQXCIaWFGrwCgDacDPvXlsvRINZoU+aQWYNF0U+ZaeUe3kkDtSUxrSOBILBpaxWwCabo84B7se76xWe4TGLhvkEcSH6GRBGxZTvOB4xSXNdQxkVIex9VhqEfGo0IGNkY8hTLBgPIoEk0nlpRwV3MZtHeRaYUcxaCSPoxRGYAZxnBWZ1n2c+8XIMF74uewFGee527UfugBCCGYF2-VZXCcJJaZsJZddSCACtwnQXk9e0AAWAAGZ2YcYoSGLe+A7R5PXIN92s4EKtBiuazCGJltnVV8MwXSwG7pxob24C2g8IMgiAACMraEFgYH+uA0DMEAhElKCgMZXkA0z0p-GL-hq+wGuIDr9AvGr2hk4XIvTEfNU12D-vpl5Yh8nsGRiG0NP6gDLuU7MMAwB5HsTFRDBq5dSCz1Hngp97kxh9XBxXWDS2bcCf6E7n6dqziJTEh5cF8cXsB557gR3hW5gWDjB-wjimQGAMAwDih4DwfgEAWBeHICCcUAAOAA7EgveN8FLgLgAAPSHNOFOZ4eSfyyNBRsahIIABIzwugwdg2+KIEggAgC4IQAAhfgNgvp52gBRTCPItyWQHAkecUAKJFXsHAVi2hOzogwCYNAHUmLsRorSRUwEGIjgCAxSUPYmFQBdFooQOiu7VgAOobVICUZ8XhQJoHQjyehjCWFsLQBwoRFEkDjygDIXKSBi6l0lJXYIOo4CdhMt2WIXIdLUJwSYsxuQ8jAEsPoaxtj2QEzqA41h7DBFcMxO4gonivK+LLqnFRjIgkhNMj2fQESqE8CwTgoAA)

## Proposed Solution
I suggest modifying the `RemoveBlankRecord` type. However, before making any changes, I would appreciate more details on its usage and purpose, as it appears to be used in several other places. I want to be sure that any modifications do not inadvertently break anything.

**Comment by yusukebe** [comment]
Hi @MonsterDeveloper 

Is this issue a problem when using `hc`?

**Comment by MonsterDeveloper** [comment]
Yes, this is an issue with `hc`. Using `req.valid` on the server works fine.

**Comment by yusukebe** [comment]
I see. Then, we'll need to rewrite the code in `src/client/*` only.

**Comment by yusukebe** [comment]
Hi @MonsterDeveloper,

I've resolved this issue on the Hono core side in the latest release, v3.8.3. Could you create a PR to address the issue on the `zod-validator` side in the middleware repository?

**Comment by MonsterDeveloper** [comment]
@yusukebe sure, please see honojs/middleware#208

**Comment by MonsterDeveloper** [comment]
I've just checked everything with the latest versions of `zod-validator` and `hono`, but the issue appears to be only partially resolved.

Even though the `query` (or `json`, etc) params are not required anymore thanks to the latest fixes, the main `args` param is still required and has to be passed as `{}` ([Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAIgAt0JiBuAKFElkTlIGNs8CiyKB6FgG2ABTNDGp1w0eEgBe7fIRIyIAE3H0pTGQDUAhoJW6Y0eZxIABchh7KVAWgBu+4IeNRiNGi3QBneD5ZSIRBdOABeOBkAOggAIwArIRYYAAokNF0QIQAuSKi-KGA0AHMUgEoYsBhgdH1y7AqIKpqM-nLaL194JwMjEwidZ1doFOIARwBXISgAT2IAGjgAoJCyju80PzhdMDBwuDQhAHcUCnKaODgo4qFU4h4FuB6XPqhFtjCAPjgWKPifdAAFTSWDKa08MBmYCEcAAShAJjAhD59pDoRBcNtdusuj9BCJ4BFWAAeeGI5GfUakGAwMDZHg8fgQFj6ch+bIADgA7NyHuCaAy4DBSAQjijdGg4NMCFA4MBMSz+PwhCo4EdgMKEfAAAa6KDFHzazqbeA3Ql44SiKJFFRCAAeUQAJGbaJdBQA9AD8QA)).

This seems to be caused by [this line](https://github.com/honojs/hono/blob/046767afd6a875d6d04c81f03c505fb58432e176/src/client/types.ts#L21C7-L21C7) in `hc`'s types. No matter the contents of the `input` object in the schema, it makes the `args` param required.

I would suggest adding a check to see whether the input has required keys, and if yes, then `args` should be required as well. [Example here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAIgAt0JiBuAKFElkTlIGNs8CiyKB6FgG2ABTNDGp1w0eEgBe7fIRIyIAE3H0pTGQDUAhoJW6Y0eZxIABchh7KVAWgBu+4IeNRiEhtLgAlISAgHIQAhfl00AGs-FmgVU0VuawBXGGB+AGceGABPMCF09UlGJABhQREYPwBHJPyYAHkwVPR0gBo4MuFRP3TINHSheK4rCB4VYHSYLNz8vnLRabyC2k9NJGRddOqk4CghFQBpIWz0oZIcvLtcOo8aGP74dJZSf104AF44GQA6CAAjABWQhYMAAFEg0LoQEIAFxfb6TKDANAAc1BAEpfk1gOh9BjsJiINjcfwMSt7pM4E4DEYTJ8dM5XNBQcQakIoNliO0ni8QLp0eSWvBdGAwB84GghAB3FAUDE0OBwb4ooRg4g8LlUxm0qDtNjvAB8cBY3wB6XQABVwVh0QKaDQLoN6vwVJ0Kts6gAeADKcCEAA8YCIVKdvc9XkbPggFXAANoAWTgyLgEWOEFwcG9AF04d6E1m-YHg6ckMiwCk4cjrlBfFQ4BAUuWYJW0NW4PVsDHFQB+Xz+QIhMKRaKxT3bXb7McGo0BoNoEMSoRBKBdxVwXug3RQFHpbtwhBYdpE5r9PcdeaVIRsyaNE-pdEfI0ABU4EyEnrd3XyfQGnvq09XRU4U3bd0jhHwj2JU84U-S9rwaKD70fOAX0IN8PwvHof3ff8DVXOFJWXGgcAAMkQGMABIkigfhgIfQ04AAVR8AAZYj7UdOAADlpVgj1Jh9Qs5wXMNeV0SNyMVBMkzQFM0wzbNc3zITiyYMsKxktsfDrBsYCbFs2w7LBV17PwAiCUJwiiYFR3HPYVCnGci3nU5CPZQD1zgECdzPA9ILvM8+KvWob0Q+jn1fX8gt6FocIAtc13AlSXPrQFgXgDyexQTY7P2I4TinZKFxgKBajgTK1w3Lcd3A-ycWg88ujgkKELvcKUMi99ouwv9p3KhKBrgYDqt3Wr60QwLMOCupb3qpCGNQkB0O62LeqNCqCKXdyEs2ojSMkuAqJoujkOYtjjIdGY4AAUUDKBdBBUTXk9C0JItIrTlQDBPXCbJ2irdlM3aX6jV7X1dvZFZOKevlxVukqHpgGHdE9R10zgEUwDwmgeB4OAABF0AAcngJb5zgGAXj9KACBXTjgiEXBoEGT5nVdKb4J9cM+VjdViCzA1aE4gBBXAgxrT4eKlILOeR3mNQFqggA)

@yusukebe what do you think?

**Comment by yusukebe** [comment]
Hi @MonsterDeveloper 

> I would suggest adding a check to see whether the input has required keys, and if yes, then `args` should be required as well.

I believe this approach is good. If possible, please create a PR. I'll review it.
