### ISSUE TITLE
Error when using Postgresjs with Hono: "error: ResolveMessage"

### ISSUE THREAD

**Issue by Alexandrsv** [honojs/hono#1585]
### What version of Hono are you using?

3.7.6

### What runtime/platform is your app running on?

3.4.0

### What steps can reproduce the bug?

I created a connection to Postgres 16 and tried to return the data

https://github.com/Alexandrsv/hono-bug

### What is the expected behavior?

Сorrect response to HTTP request

### What do you see instead?

![image](https://github.com/honojs/hono/assets/15097064/f7b9f5be-3883-4933-9a63-96094cbe16b1)

![image](https://github.com/honojs/hono/assets/15097064/c81ace67-5f1e-41a8-a444-41e896acfe6f)
**ResolveMessage**

Stack trace:
```js

  λ()
  λ()
  λ()
  λ()
  λ()
  λ()
  λ()
  λ()
```
Info:
  > bun v1.0.6
  > linux #1 SMP PREEMPT_DYNAMIC Thu Sep 28 10:59:52 UTC 2023 (x64)
  > User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
  > Pathname: /

### Additional information

Connection with prisma js works
Postgresjs works without hono

**Comment by Alexandrsv** [comment]
Now I checked again, the problem is with postgres, everything is fine with hono
"postgres": "3.3.5" is work

**Comment by yusukebe** [comment]
@Alexandrsv 

So, can we close this issue?

**Comment by Alexandrsv** [comment]
@yusukebe 
Yes thank you.
