### ISSUE TITLE
Top level middleware is not applied on non-root route

### ISSUE THREAD

**Issue by rimai4** [honojs/hono#1587]
### What version of Hono are you using?

3.7.6

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```
import { Hono, MiddlewareHandler } from 'hono';

const app = new Hono();

export const middleware: MiddlewareHandler = async (c, next) => {
  console.log('middleware');
  await next();
};

app.use(middleware);

app.get('', async (c) => {
  console.log('root route');
  return c.text('root');
});

app.get('/users/:username', async (c) => {
  console.log('users/:username route');
  return c.text('username');
});

export default app;
```

### What is the expected behavior?

Middleware is executed for both routes.

### What do you see instead?

Middleware is not executed for the `/users/:username` route.

### Additional information

I know about the route param in `app.use` and if I set it to `*` the middleware does execute for both routes.

But I was under the impression that if this is omitted, the middleware should always be applied (and not only on the root route).

**Comment by yusukebe** [comment]
Hi @rimai4,

It's not a bug. The default path is `/`, so if you don't set the path like `app.use(middleware)`, it will only apply to `/`.

**Comment by rimai4** [comment]
I see, thanks for the explanation.

I was trying to build a reusable middleware stack that could be applied to multiple route groups (https://hono.dev/api/routing#grouping).

I'm not sure whether this is possible at the moment (without specifying the path) but I'll close this for now.

Thanks for a cool framework.
