### ISSUE TITLE
Allow trailing slash for routing

### ISSUE THREAD

**Issue by justinwride** [honojs/hono#1592]
### What is the feature you are proposing?

Optional parameters are great, but they don't work with a trailing slash.

The documentation shows the example here: https://hono.dev/api/routing#optional-parameter
```js
// Will match `/api/animal` and `/api/animal/:type`
app.get('/api/animal/:type?', (c) => c.text('Animal!'))
```

When making a request from my application, it would be great if Hono could match the route with a **trailing slash** included:
```js
// Hono:
app.get('/api/animal/:type?', (c) => c.text('Animal!'))

// Application:
// can be accessed using the following requests
const animalType = 'dog';
fetch(`/api/animal/${animalType || ''}`)

// also
const animalType = null;
fetch(`/api/animal/${animalType || ''}`)
```

**Comment by usualoma** [comment]
Hi @justinwride

You would get the expected behavior by setting "strict-mode" to `false`.

https://hono.dev/api/hono#strict-mode

```ts
const app = new Hono({ strict: false })
```

**Comment by yusukebe** [comment]
This can be closed.
