### ISSUE TITLE
Can’t modify immutable headers

### ISSUE THREAD

**Issue by vickyRathee** [honojs/hono#1606]
### What version of Hono are you using?

3.8.3

### What runtime/platform is your app running on?

Cloudflare pages

### What steps can reproduce the bug?

Getting error `Can't modify immutable headers` in `ASSETS.fetch`

```
app.get("/public/*", async (ctx) => {
  return await ctx.env.ASSETS.fetch(ctx.req.raw);
});
```

### What is the expected behavior?

The static assets should be returned.

### What do you see instead?

![image](https://github.com/honojs/hono/assets/6106479/cb0935cc-7811-4f3c-8d44-513321be57df)

**Comment by vickyRathee** [comment]
I also tried to use `ctx.req`

```
app.get('/public/*', async (ctx) => {
  return await ctx.env.ASSETS.fetch(ctx.req as any);
});
```

But it throw a new error: `Fetch API cannot load: [object Object]   `

![image](https://github.com/honojs/hono/assets/6106479/4b552619-6971-46a4-bc2a-4721f6700c7c)


let me know if anyone managed to serve static assets with Cloudflare Pages on Hono?

Here is my code structure - 

![image](https://github.com/honojs/hono/assets/6106479/ffcdf803-f410-4615-b68b-de5920057c69)

**Comment by yusukebe** [comment]
This might be a bug.

**Comment by vickyRathee** [comment]
Any workaround or older version I can downgrade for temporarily fix?

**Comment by yusukebe** [comment]
@vickyRathee

Can you provide snippets or a project to reproduce it?

**Comment by vickyRathee** [comment]
@yusukebe 

Sure, here is an example project - https://stackblitz.com/edit/stackblitz-starters-9jmhfz?file=functions%2Findex.ts

**Comment by yusukebe** [comment]
@vickyRathee Thanks!

You need to place `ctx.env.ASSETS.fetch` above `cors` as the `cors` middleware attempts to modify headers that have already been finalized. Try the following code:

```ts
app.get('/styles.css', async (ctx, next) => {
  return await ctx.env.ASSETS.fetch(ctx.req.raw)
})

app.use(
  '*',
  cors({
    maxAge: 86400,
    origin: '*'
  })
)
```

**Comment by vickyRathee** [comment]
The `headers` error has been fixed by moving `cors` settings down, but I am still getting 404 for all the assets. 
Is there some additional setting or some flag I need to enable CF advance mode for pages, I am just running `wrangler pages dev --directory=./public` and the assets request return 404

Can you please suggest the changes or [update on Stackblitz](https://stackblitz.com/edit/stackblitz-starters-9jmhfz?file=functions%2Findex.ts) to make it work with assets?

![image](https://github.com/honojs/hono/assets/6106479/fabca698-884f-4f1c-845f-a1aa4d3181ec)
