### ISSUE TITLE
Auto-generate exports at build time

### ISSUE THREAD

**Issue by ashtonsix** [honojs/hono#1611]
### What is the feature you are proposing?

I recently encountered and fixed an issue related to some types not being included in the package.json exports: https://github.com/honojs/hono/pull/1610

Just after that was merged I noticed a very similar issue:

<img width="318" alt="image" src="https://github.com/honojs/hono/assets/6740947/c2bfc531-ded1-49fc-89d7-c4a5f62e4377">

<img width="476" alt="image" src="https://github.com/honojs/hono/assets/6740947/66c3bdf8-c42c-42a4-b5a1-6e8a1c0cd789">

This can be easily fixed by adding to `hono/package.json`:

```
"./client/types": {
  "types": "./dist/types/client/types.d.ts",
  "import": "./dist/client/types.js",
  "require": "./dist/cjs/client/types.js"
},
"./context": {
  "types": "./dist/types/context.d.ts",
  "import": "./dist/context.js",
  "require": "./dist/cjs/context.js"
},
```

However I think a more cohesive solution is in order, and would suggest that every `.d.ts` file in Hono be included in the `package.json` exports to avoid this category of tooling issues. To reduce the maintenance burden here, I suggest auto-generating the exports and updating `package.json` at build time (modification to `build.ts` required).

Is my suggestion wanted? If so, I'd be happy to create a PR.

**Comment by ashtonsix** [comment]
Hi sorry, I have to retract my offer to create the PR myself. After encountering https://github.com/honojs/hono/issues/1542 within a few minutes of this issue I've come to form the opinion that Hono is not yet production-ready, and can neither recommend my company adopt it or dedicate time to improving it at this stage.

**Comment by ashtonsix** [comment]
here's how i adapted the ideas from Hono & ported them to Express, sharing in case this inspires:

<img width="618" alt="image" src="https://github.com/honojs/hono/assets/6740947/ae5b847c-8a96-4a71-a1a0-810d904e579e">

**Comment by yusukebe** [comment]
Hi @ashtonsix 

#1542 is already fixed by this PR #1555.

**Comment by yusukebe** [comment]
> To reduce the maintenance burden here, I suggest auto-generating the exports and updating `package.json` at build time (modification to `build.ts` required).

This seems to be good, but I'd prefer something like a linter that would throw the error, rather than rewriting the file directly.

**Comment by yusukebe** [comment]
I can close this Issue for now.
