### ISSUE TITLE
AWS Lambda Adapter only keeps requestContext from API GW event and loses the rest

### ISSUE THREAD

**Issue by dbain-texada** [honojs/hono#1620]
### What version of Hono are you using?

3.8

### What runtime/platform is your app running on?

NodeJS

### What steps can reproduce the bug?

I've deployed my hono app to AWS lambda, however, it seems we lose the cookies from the request. I'm looking at this file: https://github.com/honojs/hono/blob/main/src/adapter/aws-lambda/handler.ts. Comparing a log of a lambda using hono vs log of a regular lambda, my hono lambda only has the requestContext while the regular lambda has the entire API GW event. Why doesn't the adapter retain the cookies?
![image](https://github.com/honojs/hono/assets/136749565/cde04137-e464-42f0-8df3-048403391ee2)

### What is the expected behavior?

I want hono context to retain more info from the API GW event rather than just the requestContext. What is the purpose of stripping this info?

### What do you see instead?

Only the requestContext remains on the hono context after using the aws-lambda hono adapter

**Comment by yusukebe** [comment]
cc: @watany-dev

**Comment by watany-dev** [comment]
As you pointed out, APIGatewayProxyEventV2 and other events are not capturing the complete event.
https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

@yusukebe 
Would you like to transcribe everything using this repository as a reference?
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/aws-lambda

**Comment by yusukebe** [comment]
@watany-dev 

> Should we address this by transcribing everything using this repository as a reference? I can handle it if it's from next week onward.

Is that a lot of it?

**Comment by watany-dev** [comment]
@yusukebe 

Actually, if it is just the cookie in this case, this PR will fix it.

https://github.com/honojs/hono/pull/1613

I don't know how much to port all the lambda event interfaces, but it might not be that much, so I'll try to make a PR somewhere.

**Comment by yusukebe** [comment]
@watany-dev

I see!

Once things are done, I'll merge #1613 into main. And if you can, please create the PR to port all Lambda event interfaces. Thanks!

**Comment by watany-dev** [comment]
@yusukebe 
I think this issue should be closed. What do you think?

**Comment by yusukebe** [comment]
Yeah, we can close it!
