### ISSUE TITLE
Typescript transpiler

### ISSUE THREAD

**Issue by acrodrig** [honojs/hono#1627]
### What is the feature you are proposing?

Hello. I created (mainly for myself) a typescript middleware that will automatically transpile TS files to JS on the fly. It's  simple, and you can see the code in the module page [Hono Typescript](https://deno.land/x/hono_typescript@0.1.2#hono-typescript) and in the [Github Repo](https://github.com/acrodrig/hono_typescript). 

It's very similar to how the [Pretty JSON](https://hono.dev/middleware/builtin/pretty-json) middleware works (used that code for inspiration). It essentially enables this type of server:

```typescript
import { Hono } from "hono";
import { serveStatic } from "hono/middleware.ts";
import { transpiler } from "hono_typescript/mod.ts";

const app = new Hono();

// Add the transpiler middleware to the app
// IT WILL TRANSFORM A TS FILE INTO JS FOR BROWSER CONSUMPTION
app.use("*", transpiler());

app.use("/static/*", serveStatic({ root: "./" }));
app.use("/favicon.ico", serveStatic({ path: "./favicon.ico" }));
app.get("/", (c) => c.text("This is Home! You can access: /static/hello.txt"));
```

My questions/comments are:

- Is this something that would be of interest to the Hono maintainers?
- Is it possible to achieve the same result already via another middleware?
- This will obviously not work on the browser. Is that a deal breaker?

If the answer is on the positive I would need to see how to make it work for Node.js as well, which should not be too difficult because I believe the `emit` package is node-first.

Cheers.

**Comment by yusukebe** [comment]
Hi @acrodrig,

I think this is a super cool feature. I've tried it and it works well!

<img width="912" alt="Screenshot 2023-10-30 at 7 14 07" src="https://github.com/honojs/hono/assets/10682/c030d60e-ac5a-49ed-b560-014adc32ea81">

> Is this something that would be of interest to the Hono maintainers?

Absolutely!

> Is it possible to achieve the same result already via another middleware?

Perhaps.

> This will obviously not work on the browser. Is that a deal breaker?

Do you mean an app using this middleware would really work on a browser like Chrome? If so, it's not necessary.

I want to move forward with this! This middleware depends on the `emit` package, so it will be a third-party middleware. We need to figure out how to make it support both Node.js and Deno, or maybe Bun or Cloudflare?

Anyway, I love this.

**Comment by acrodrig** [comment]
> I think this is a super cool feature. I've tried it and it works well!

Cool. will prepare a PR.

> Do you mean an app using this middleware would really work on a browser like Chrome? If so, it's not necessary.

Scratch my original comment (does not make even make sense for Hono). The transpiled JS will work on browers.

> I want to move forward with this! This middleware depends on the `emit` package, so it will be a third-party middleware. We need to figure out how to make it support both Node.js and Deno, or maybe Bun or Cloudflare?

Yes, I was actually wrong, emit is deno only. Let me see how to achieve the same result on Node/Bun.

**Comment by acrodrig** [comment]
@yusukebe I created a PR (see https://github.com/honojs/middleware/pull/224). 

Please let me know if this is what you had in mind.

Notes:

- Uses SWC (instead of emit) to be agnostic to Deno/Node/Bun/etc
- Removed ignored test to make it work on TSX (adds complexity for now)

Cheers.

**Comment by yusukebe** [comment]
@acrodrig 

Okay, I'll take a look and use it to know how I feel later. Thanks.

**Comment by yusukebe** [comment]
Hey @acrodrig,

I have an idea for implementing a transpiler middleware. Please give me a minute until I create a PR.

**Comment by yusukebe** [comment]
@acrodrig

I've created the PR for "esbuild Transpiler Middleware": https://github.com/honojs/middleware/pull/231

This middleware serves the same purpose and some code is copied from your implementation. However, it uses esbuild and supports wasm for edge platforms. I believe using esbuild is a good choice because esbuild's wasm side is smaller than SWC's. Moreover, esbuild is used in [Fresh](https://fresh.deno.dev/).

Could you review it? I've added you as a co-author.

**Comment by acrodrig** [comment]
Looks good @yusukebe. My only comment is that the name should be more generic and not mention the particular compiler/transpiler used. The use of `esbuild` is an implementation detail and makes the abstraction conceptually leaky IMO.  The goal is to transpile typescript, regardless of how it is achieved.

However if you feel it is aligned with how you want to manage the middlewares and your project, I would not want to go against that.

Cheers.

**Comment by yusukebe** [comment]
Hi @acrodrig,

Thank you for responding.

I intentionally included `esbuild` in the name because the API interface relies on `esbuild`:

```ts
import { esbuildTranspiler } from '@hono/esbuild-transpiler/wasm'
import wasm from '../node_modules/esbuild-wasm/esbuild.wasm'

// ...

app.get('/static/:scriptName{.+.tsx?}', esbuildTranspiler({ wasmModule: wasm }))
```

While generalizing the name isn't a bad idea, if we switch from the esbuild transpiler to SWC, the API will change entirely, even though the name remains just "transpiler." It would be fitting to create "SWC Transpiler Middleware" in that scenario. Therefore, I believe using `esbuild` in the name is better.

**Comment by acrodrig** [comment]
Makes sense. Please proceed.

**Comment by yusukebe** [comment]
Okay!

**Comment by yusukebe** [comment]
@acrodrig 

I've released `@hono/esbuild-transpiler@0.1.0` now. Try it.

**Comment by acrodrig** [comment]
Awesome, very nice to have it be part of Hono's third party middleware. Will report any findings. Thanks for the quick turnaround and for the willingness to try new things. It makes for a dynamic project.

**Comment by yusukebe** [comment]
So, I'll close this issue although I think it's OK if there are other implementations. We can create another issue if we want to address it. Thanks.
