### ISSUE TITLE
feat: support route's cleanup feature like `app.clean()` or `app.reset()`

### ISSUE THREAD

**Issue by sor4chi** [honojs/hono#1628]
### What is the feature you are proposing?

I thought that if there was a function to cleanup of route at test time, the test could be written more concisely.

## Behavior

```ts
const app = new Hono()

app.get("/aaa", (c) => c.text("aaa"))

app.showRoutes()
// GET       /aaa

app.clean()

app.showRoutes()
// no routes
```

## In Test

```ts
const app = new Hono()

afterEach(() => {
  app.clean()
})
```

**Comment by yusukebe** [comment]
Hi @sor4chi,

Just a simple question, isn't it sufficient to initialize Hono every time? I believe clearing the routing would be difficult without re-creating instances of routers.

**Comment by sor4chi** [comment]
Sure, we could initialize it every time, but I thought it would be useful to duplicate Hono in a way that inherits the basePath and any options that might be added in the future.

```ts
let app = new Hono();

beforeEach(() => {
  app = new Hono();
});
```

I am writing this now, but unless you have a special setup, this is sufficient.
Thanks for responding!
