### ISSUE TITLE
get Cookies from a Middleware

### ISSUE THREAD

**Issue by emersonlaurentino** [honojs/hono#1631]
### What version of Hono are you using?

3.8.2

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

I'm running the project locally with wrangler, so I've 2 routes: `/sign-in` and `/me`.

At the first, I sign with and return the token as cookie.

At the second, I have a middleware `authenticate` that check if has cookie and throw or continue...

The issue is in this middleware.

```ts
// ...
const { token } = getCookie(c);
// ...
```

Token is never getted using `getCookie` or `c.cookies` (as I know that is will deprecated on v4).

### What is the expected behavior?

I want to get the cookies from the domain.

### What do you see instead?

the empty object from `c.cookies` or `getCookie(c)`

**Comment by yusukebe** [comment]
Hi @emersonlaurentino 

Could you show me the code to reproduce it. It can be minimal.

**Comment by emersonlaurentino** [comment]
Sure, here is a minimal example:

```ts
// routers.ts
app.post("/sign-in", signIn);
app.get("/me", authenticate(), userLogged);
```

```ts
// signIn.tsx
// ...
setCookie(ctx, "access_token", access_token);
setCookie(ctx, "refresh_token", refresh_token);
// ...
```

```ts
// middlewares.ts
export function authenticate(): MiddlewareHandler {
  return async (ctx: Context, next) => {
    const cookies = getCookie(ctx);
    console.log('cookies', cookies);
    await next();
  }
}
```

**Comment by emersonlaurentino** [comment]
@yusukebe I found the issue, As I am using setCookie within the `/sign-in` route, the cookie is only available for this `path`, so I added `path` as `/` in the options and the cookie is available for all routes.

Thanks for your help.
