### ISSUE TITLE
prettyJSON middleware doesn't work

### ISSUE THREAD

**Issue by x-tropy** [honojs/hono#1638]
### What version of Hono are you using?

3.9.1

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

import { prettyJSON } from 'hono/pretty-json';

app.use('/api/*', prettyJSON({ space: 4 }));
app.get('/api/hello', (c) => c.json({ message: 'Hello World' }));

### What is the expected behavior?

should return indented JSON data on the cloudflare workers site.

### What do you see instead?

unindented plain string.

**Comment by yusukebe** [comment]
Hi @x-tropy 

It's not a bug. Add  a `pretty` query param to the URL:

```
http://localhost:8787/api/hello?pretty
```

**Comment by x-tropy** [comment]
> Hi @x-tropy
> 
> It's not a bug. Add a `pretty` query param to the URL:
> 
> ```
> http://localhost:8787/api/hello?pretty
> ```

Thanks! Didn't notice that when browsing the doc.

**Comment by flyingduck92** [comment]
> Hi [@x-tropy](https://github.com/x-tropy)
> 
> It's not a bug. Add a `pretty` query param to the URL:
> 
> ```
> http://localhost:8787/api/hello?pretty
> ```

this should be written on the docs
