### ISSUE TITLE
'basePath' doesn't work

### ISSUE THREAD

**Issue by x-tropy** [honojs/hono#1640]
### What version of Hono are you using?

3.9.1

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

const api = new Hono().basePath('/api');

api.get('/test', (c) => {
	return c.text(c.req.path);
});

### What is the expected behavior?

when visiting http://127.0.0.1:8787/api/test with browser, the page should return the path.

### What do you see instead?

I see '404 Not Found' only. It means the route '/api/test' isn't working.

**Comment by chimame** [comment]
It seems that routing works correctly when you store the instance in a variable and then set the `basePath`.

```typescript
import { Hono } from 'hono'

const app = new Hono()
const api = app.basePath('/api')

api.get('/test', (c) => {
  return c.text(c.req.path);
});
app.get('/', (c) => c.text('Hello Hono!'))

export default app
```

However, in the code you provided, routing does not work correctly, and all access results in a 404 error. This issue occurred not only with Bun but also in Node.js.

**Comment by chimame** [comment]
I tried it again, and it worked with the following code. It seems like I had a misunderstanding.

![image](https://github.com/honojs/hono/assets/7520815/c486422a-e7b1-46a2-9c82-d2844e037397)

**Comment by x-tropy** [comment]
> I tried it again, and it worked with the following code. It seems like I had a misunderstanding.
> 
> ![image](https://user-images.githubusercontent.com/7520815/280064833-c486422a-e7b1-46a2-9c82-d2844e037397.png)

hmmm... not sure why, but it didn't work for me.

**Comment by chimame** [comment]
What version of bun are you using? I will try to match the version too.

**Comment by x-tropy** [comment]
> What version of bun are you using? I will try to match the version too.

v1.0.7

Cheers.

**Comment by chimame** [comment]
I upgraded Bun to version 1.0.7 and tried launching it, and it worked without any issues. I can't reproduce the problem. 😥

![image](https://github.com/honojs/hono/assets/7520815/e7f9707b-0a09-4cd8-8699-5d680f6f571a)

**Comment by x-tropy** [comment]
@chimame Sorry for the delay. I have a mis-understanding here:
It's the slashes ('/'), easy to get it wrong. I may have accidentally added one more slash to the end of URL in the browser.

**Comment by lanten** [comment]
I spent an hour troubleshooting this issue and was confused as to why app.basePath didn't work. Is this by design?

**Comment by EdamAme-x** [comment]
We always help you, if you provide us with minimal reproduction code.

**Comment by filipfalcon** [comment]
In my case it works only with `basePath('/api/')`, using `basePath('/api')` fails with 404 error.
