### ISSUE TITLE
Catch-All segments route

### ISSUE THREAD

**Issue by fineshop** [honojs/hono#1644]
### What is the feature you are proposing?

Routing for catch all segments:

```ts
app.get("/app/:paths+", async ({ env, req }) => {
  const paths = req.param("paths"); // => string[]
});
```

[GET] /app/foo/bar
```ts
const paths = req.param("paths"); // => ["foo", "bar"]
```

**Comment by yusukebe** [comment]
Hi @fineshop 

We will not implement it, but you can achieve it by writing the following.

```ts
app.get('/app/:path{.+}', (c) => {
  const paths = c.req.param('path').split('/')
  return c.json({
    paths
  })
})
```

**Comment by fineshop** [comment]
> Hi @fineshop 
> 
> We will not implement it, but you can achieve it by writing the following.
> 
> ```ts
> app.get('/app/:path{.+}', (c) => {
>   const paths = c.req.param('path').split('/')
>   return c.json({
>     paths
>   })
> })
> ```

Thank you!
