### ISSUE TITLE
Get requests with a body return a TypeError

### ISSUE THREAD

**Issue by stevenosse** [honojs/hono#1649]
### What version of Hono are you using?

^3.9.2

### What runtime/platform is your app running on?

Vercel

### What steps can reproduce the bug?

1. Create a "GET" endpoint 
2. Make a call to that endpoint from Postman and give the endpoint a body
3. Run the call, and then you get the error

Generated code (from Postman):
```cURL
curl --location --request GET 'localhost:3000/api/ai/summarize' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic cGFwZXJhaTpNY0gzMTIhQ1t4XQ==' \
--data '{
    "textContent": "aloa"
}'
```

### What is the expected behavior?

The body should be ignored

### What do you see instead?

```
TypeError: fetch failed
    at fetch (user/node_modules/undici/index.js:109:13)
    at async file:///user/node_modules/@vercel/node/dist/dev-server.mjs:732:22
    at async Server.onDevRequest (file:///user/node_modules/@vercel/node/dist/dev-server.mjs:1146:48)
```

**Comment by chimame** [comment]
I also looked into it out of curiosity. Normally, you don't include a body in a GET request. However, there is no specific specification in HTTP that prohibits including a body in a GET request.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

Additionally, if you include a body in a GET request, it results in an error in `undici`. It might be better to resolve this issue fundamentally using `vercel` or `undici` wouldn't it?

Or what are your expectations regarding Hono?


This is the code I created to cause the error.

```typescript
import { fetch } from "undici";

async function main() {
  const res = await fetch("https://example.com", { body: "Hello world!" });
  console.log('res.status', res.status);
}

main();
```

**Comment by stevenosse** [comment]
Thank you for your reply @chimame 

Sorry, I only discovered Hono today and it was during my tests that I got this
On Postman, I tested a POST request, then changed the request type to GET (forgetting to remove the body) and I got the error, it took me a while to figure out where it was coming from
With express, the body would have been ignored and I thought it wise to point it out here

**Comment by yusukebe** [comment]
Hi,

This issue is not related to Hono, but rather to the Vercel dev server or the `undici` library used within it. When I run it on other platforms like Cloudflare, Bun, and other runtimes, it functions correctly. It also works well in the deployment environment.

I haven't found a workaround for it in issues on repositories such as Vercel's, but it's a significant problem.

I'll close this issue. Thanks.
