### ISSUE TITLE
Context has any type in Deno

### ISSUE THREAD

**Issue by oscarehrling** [honojs/hono#1655]
### What version of Hono are you using?

3.9.2

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

Creating a new Hono project:
```bash
npm create hono@latest hono-with-deno

# and choosing template
> deno
```

On Hono 3.9.2 and Deno 1.38 I get this:

<img width="700" alt="Screenshot 2023-11-08 at 09 49 52" src="https://github.com/honojs/hono/assets/10611239/5162079b-b894-404b-a8dd-6458596c8310">

---

But switching to Hono 3.9.0, `c` is properly typed again:

<img width="671" alt="Screenshot 2023-11-08 at 09 54 57" src="https://github.com/honojs/hono/assets/10611239/0baa798d-9527-435b-bf83-fc161d50399c">

**Comment by yusukebe** [comment]
Hi @oscarehrling 

It might not be a bug, the problem could be caused by the cache. Could you run this command?

```
deno cache --reload hello.ts
```

**Comment by oscarehrling** [comment]
> Hi @oscarehrling
> 
> It might not be a bug, the problem could be caused by the cache. Could you run this command?
> 
> ```
> deno cache --reload hello.ts
> ```

That did the trick, and now I feel stupid 😅
For some reason I've never run into this cache issue before 🤷‍♂️

Thank you for the quick reply! Closing this.
