### ISSUE TITLE
Remove experimental flag mount API

### ISSUE THREAD

**Issue by Code-Hex** [honojs/hono#1667]
### What is the feature you are proposing?

I'm curious how long the experiment flag will remain on.
Our company uses [`mount`](https://hono.dev/api/hono#mount) API. I would be in trouble if this flag was removed, but when will this flag be removed?

**Comment by yusukebe** [comment]
Now! #1669 (It will be merge into the "next" branch and will be included in the `v3.10.0`)

**Comment by Code-Hex** [comment]
Let's gooo!! 🔥

**Comment by yusukebe** [comment]
It's released!
