### ISSUE TITLE
AWS Lambda streaming works correctly?

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1678]
### What version of Hono are you using?

next

### What runtime/platform is your app running on?

AWS Lambda

### What steps can reproduce the bug?

```ts
import { Hono } from 'hono'
import { streamHandle } from 'hono/aws-lambda'

const app = new Hono()

app.get('/stream', (c) => {
  return c.streamText(async (stream) => {
    for (let i = 0; i < 10; i++) {
      const message = `It is ${new Date().toISOString()}`
      await stream.writeln(message)
      await stream.sleep(1000)
    }
  })
})

export const handler = streamHandle(app)
```

### What is the expected behavior?

The Lambda function returns a stream immediately.

### What do you see instead?

It returns a stream, but there is a lag the first time. It does not return it immediately.

https://github.com/honojs/hono/assets/10682/e70d1760-7125-4195-befd-2dc0b6574971

### Additional information

The same behavior occurs with the AWS samples:

https://github.com/aws-samples/serverless-patterns/tree/main/lambda-streaming-ttfb-write-sam

This returns an HTML stream response, but there is a time lag the first time.

So, it might be an issue with AWS or there could be something wrong with my configuration.

**Comment by watany-dev** [comment]
Apparently, this is the phenomenon. 

https://betterdev.blog/lambda-response-streaming-flush-content/

Certainly, running the two codes helped me understand this.

```ts
exports.handler = awslambda.streamifyResponse(
  async (event, responseStream) => {
    responseStream.setContentType("text/html");

    responseStream.write(generateChunk(1));
    await new Promise(r => setTimeout(r, 1000));
    responseStream.write(generateChunk(2));
    await new Promise(r => setTimeout(r, 1000));
    responseStream.write(generateChunk(3));
    await new Promise(r => setTimeout(r, 1000));
    responseStream.write(generateChunk(4));

    responseStream.end();
  }
);

const generateChunk = (n) => {
  const serverTime = new Date();
  return `
    Chunk: ${n}<br>
    Server time: ${serverTime.toISOString()}<br>
    <script>
      const clientTime${n} = new Date();
      document.write("Client time: " + clientTime${n}.toISOString() + "<br>");
      document.write("Difference (ms): " + (clientTime${n}.getTime() - ${serverTime.getTime()}) + "<br><br>");
    </script>
  `;
}
```

```ts
const bigStr = " ".repeat(100_000); // generate 100 KB string

exports.handler = awslambda.streamifyResponse(
  async (event, responseStream) => {
    responseStream.setContentType("text/html");

    responseStream.write(generateChunk(1) + bigStr); // add it
    await new Promise(r => setTimeout(r, 1000));
    responseStream.write(generateChunk(2) + bigStr); // to
    await new Promise(r => setTimeout(r, 1000));
    responseStream.write(generateChunk(3) + bigStr); // every
    await new Promise(r => setTimeout(r, 1000));
    responseStream.write(generateChunk(4) + bigStr); // chunk

    responseStream.end();
  }
);

const generateChunk = (n) => {
  const serverTime = new Date();
  return `
    Chunk: ${n}<br>
    Server time: ${serverTime.toISOString()}<br>
    <script>
      const clientTime${n} = new Date();
      document.write("Client time: " + clientTime${n}.toISOString() + "<br>");
      document.write("Difference (ms): " + (clientTime${n}.getTime() - ${serverTime.getTime()}) + "<br><br>");
    </script>
  `;
}
```

**Comment by watany-dev** [comment]
@yusukebe 
Oh. This spec is why renderToReadableStream didn't work. My sample implementation was "too small."

```ts
app.get('/jsx', (c) => {
  let space: string = ' '; 
  const title: string = 'SSR' + space.repeat(100000)
  return c.body(
    renderToReadableStream(
      <html><body>
      <h1>`${title}`</h1>
      <Suspense fallback={<div>loading...</div>}><Component /></Suspense>
      </body></html>
    ),
    {
       headers: {
         'Content-Type': 'text/html; charset=UTF-8',
         'Transfer-Encoding': 'chunked'
       }
    }
  )
})
```

**Comment by yusukebe** [comment]
@watany-dev 

Wow, you are right! That example works as expected and truly streams. Then, perhaps this issue can be closed and we can consider the "Streaming Support for Lambda" as completed. What are your thoughts?

**Comment by watany-dev** [comment]
@watany-dev 

Yes, this is a normal feature of Adaptor, so I guess we can consider the development complete.
If any more questions arise on how to use it, I will add this feature to the adaptor documentation.

**Comment by yusukebe** [comment]
@watany-dev 

Okay! I'll close this issue and the new minor version will be release tomorrow!

**Comment by rschick** [comment]
@yusukebe I ran into this this week too. I think it's a bug in AWS' function URL implementation. It is possible to work around it by writing an additional chunk to the stream:

```
const textEncoder = new TextEncoder()

export const renderToReadableStream = (
  str: HtmlEscapedString | Promise<HtmlEscapedString>
): ReadableStream<Uint8Array> => {
  const reader = new ReadableStream<Uint8Array>({
    async start(controller) {
      const resolved = str instanceof Promise ? await str : await str.toString()
      controller.enqueue(textEncoder.encode(resolved))

      // write an extra space so function URL sends previous chunks
      controller.enqueue(textEncoder.encode(' '))

      let resolvedCount = 0
      const promises: Promise<void>[] = []
      const then = (promise: Promise<string>) => {
        promises.push(
          promise
            .catch((err) => {
              console.trace(err)
              return ''
            })
            .then((res) => {
              if ((res as HtmlEscapedString).promises) {
                const resPromises = (res as HtmlEscapedString).promises || []
                resPromises.forEach(then)
              }
              resolvedCount++
              controller.enqueue(textEncoder.encode(res))

              // write an extra space so function URL sends previous chunks
              controller.enqueue(textEncoder.encode(' '))
            })
        )
      }
      ;(resolved as HtmlEscapedString).promises?.map(then)
      while (resolvedCount !== promises.length) {
        await Promise.all(promises)
      }

      controller.close()
    }
  })
  return reader
}
```

I'm not sure what the best way to implement this would be in practice. There could be an option passed to `renderReadableStream`, or we could have an alternate implementation just for Lambda, or we could have this as part of the adapter. What do you think?

**Comment by watany-dev** [comment]
@rschick 
Thank you for the comment. This is the implementation I have done. I wrote about this issue earlier, but it seems that the problem of not flashing below a certain data amount is on the AWS side. In fact, it can be reproduced even when implemented outside of the adapter. Since this threshold value is not published either, I don't think it's appropriate to arbitrarily add data to the user's data. How about drawing attention to this information in the documentation as a precaution, and having the user explicitly add it themselves?

**Comment by yusukebe** [comment]
Hi @rschick 

@watany-dev is right. Streaming work well or not depending on the amount of data.

@watany-dev 

> How about drawing attention to this information in the documentation as a precaution, and having the user explicitly add it themselves?

This is a good idea. Could you create a PR for it on our website if you have time?
