### ISSUE TITLE
  `c.req.raw.referrer` is missing

### ISSUE THREAD

**Issue by bruceharrison1984** [honojs/hono#1683]
### What version of Hono are you using?

3.9.2

### What runtime/platform is your app running on?

Cloudflare Worker

### What steps can reproduce the bug?

Attempting to use `c.req.referrer` results in a deprecation warning, and advises to use `c.req.raw.referrer` instead. The problem is that  `c.req.raw.referrer` appears to not exist!

### What is the expected behavior?

`c.req.raw.referrer` should be available, or the deprecation warning should point to the correct location.

### What do you see instead?

The  `c.req.raw.referrer` property does not exist.

**Comment by chimame** [comment]
Certainly, I couldn't retrieve the `referrer` from `c.req.raw` or `c.req`. Upon examining the code, it seems that `c.req.referrer` ultimately references `c.req.raw.referrer`. However, obtaining the referrer from the Request object of `c.req.raw` is not possible.
https://github.com/honojs/hono/blob/db3387353f23e0914faf8169323c06e9d9658c20/src/request.ts#L239-L241

In the Web API, the referrer is defined in the Request object, but it appears to be different on the server side.
https://developer.mozilla.org/en-US/docs/Web/API/Request/referrer

To retrieve the `referrer`, I attempted to obtain it from the `headers`.

```tsx
import type { FC } from 'hono/jsx'
import { Hono } from 'hono'

const app = new Hono()

const Test: FC = () => {
  return (
    <html>
      <body>
        <a href='/'>to top</a>
      </body>
    </html>
  )
}
app.get('/', (c) => {
  console.log(c.req.raw) // The c.req.raw is a Request object, but it does not have the referrer attribute.
  return c.text(c.req.raw.headers.get('referer') || 'no referrer')
})
app.get('/test', (c) => c.html(<Test />))

export default app
```

**Comment by chimame** [comment]
@yusukebe 

Is it correct to assume that you believe obtaining the referrer from the request header is the appropriate method? Is there a specific reason for attempting to retrieve it from the properties of the request object? Would it be acceptable to make the change to obtain it from the request header?

**Comment by yusukebe** [comment]
We use the `referrer` property to maintain compatibility with the Web API.

https://developer.mozilla.org/en-US/docs/Web/API/Request/referrer

Whether a Request has the `referrer` property depends on the implementation. For instance, Cloudflare Workers seem not to have it, but the DOM does.

Anyway, `c.req.referrer` will become obsolete, so there's no need to implement `c.req.referrer`. If the `Request` in the runtime you want to run your app doesn't have the `referrer` property, you'll need to implement a function to retrieve it from the header values.

**Comment by chimame** [comment]
> If the Request in the runtime you want to run your app doesn't have the referrer property, you'll need to implement a function to retrieve it from the header values.

Thank you for your response. I wasn't aware of such intentions. If there is no policy to support obtaining referrers in any runtime in Hono, would it be advisable to write it in the source code comments?

**Comment by chimame** [comment]
Is it acceptable to make a change in Hono to retrieve the referrer from the header if the referrer does not exist in the Request's properties?

**Comment by yusukebe** [comment]
@chimame

I don't think we need to implement this in Hono. Users should create it themselves. It's important to keep the code small, especially for the Hono core object, including `HonoRequest`.

**Comment by bruceharrison1984** [comment]
@yusukebe, thanks for clearing this up. I'm going to go ahead and close this issue.
