### ISSUE TITLE
Change default HTTP status of c.redirect to 307

### ISSUE THREAD

**Issue by htunnicliff** [honojs/hono#1684]
### What is the feature you are proposing?

Would there be openness to changing the default status code for `c.redirect` from [302 Found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302) to [307 Temporary Redirect](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307)?

There are a few differences between these codes, but here is a brief summary from MDN:

<blockquote>
  The only difference between <code>307</code> and <a href="/en-US/docs/Web/HTTP/Status/302"><code>302</code></a> is that
  <code>307</code> guarantees that the method and the body will not be changed when the
  redirected request is made. With <code>302</code>, some old clients were incorrectly
  changing the method to <a href="/en-US/docs/Web/HTTP/Methods/GET"><code>GET</code></a>: the behavior with non-<code>GET</code>
  methods and <code>302</code> is then unpredictable on the Web, whereas the behavior with
  <code>307</code> is predictable. For <code>GET</code> requests, their behavior is
  identical.
</blockquote>

The immediate benefit from switching to `307` would be that redirects used for non-GET routes would function as expected.

**Comment by htunnicliff** [comment]
Another way to go about this could be making the default redirect HTTP status code configurable on the Hono instance.

**Comment by yusukebe** [comment]
I think it's not necessary; we can just specify the status number as an argument.

```ts
return c.redirect('/foo', 307)
```
