### ISSUE TITLE
Deno Type Error: Parameter 'c' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by JetLua** [honojs/hono#1691]
### What version of Hono are you using?

3.10.0

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

```ts
import { Hono } from 'https​://deno.land/x/hono​@v3.10.0/mod.ts'

const app = new Hono()

app.get('/', (c) => c.text('Hello Deno!')) // Parameter 'c' implicitly has an 'any' type.

Deno.serve(app.fetch)
```

**Comment by chimame** [comment]
I have a type defined for `Context`, not `any`. Could it be an environmental issue?
![image](https://github.com/honojs/hono/assets/7520815/bddcaf41-d844-463f-9ffb-37f29f5d4de3)

```bash
$ deno --version
deno 1.37.2 (release, aarch64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2
```

**Comment by yusukebe** [comment]
@JetLua 

Try:

```txt
deno cache --reload hello.ts
```

**Comment by haehgeuwhveaw** [comment]
amazing, thank you :)

**Comment by hansSchall** [comment]
It might be required to restart the Deno Language Server after `deno cache --reload`
