### ISSUE TITLE
Using Context.status() does not work when using Context.text()

### ISSUE THREAD

**Issue by sant123** [honojs/hono#1699]
### What version of Hono are you using?

3.10.0

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

```ts
import { Hono } from "https://deno.land/x/hono@v3.10.0/mod.ts";

const app = new Hono();

app.get("/", (c) => {
  c.status(403);
  return c.text("Message received!");
});

Deno.serve(app.fetch);

```

### What is the expected behavior?

The status code should be 403.

### What do you see instead?

It is 200.

### Additional information

Other responses work good.

```ts
import { Hono } from "https://deno.land/x/hono@v3.10.0/mod.ts";

const app = new Hono();

app.get("/", (c) => {
  c.status(403);
  return c.html("<h1>Message received!</h1>");
});

Deno.serve(app.fetch);
```

It returns 403 status code.

**Comment by yusukebe** [comment]
Hi @sant123,

Thank you for raising the issue and creating the PR.

Your PR is good, but I've created another PR, #1702, with a different approach to fix this.

My PR offers a slightly faster performance compared to the app with your PR. Therefore, I'll merge #1702. Thanks!
