### ISSUE TITLE
`notFound` doesn't seem to work with Cloudflare Pages

### ISSUE THREAD

**Issue by bruceharrison1984** [honojs/hono#1703]
### What version of Hono are you using?

3.10.1

### What runtime/platform is your app running on?

Cloudflare Pages

### What steps can reproduce the bug?

Create a basic Hono api:

```ts
//index.ts
import { OpenAPIHono } from '@hono/zod-openapi';
import { notFoundRoute } from './routes/_404';
import { renderer } from './renderer';

const app = new OpenAPIHono();
app.use('*', renderer)
app.notFound(notFoundRoute);

//routes/_404.tsx
import { NotFoundHandler } from 'hono';

export const notFoundRoute: NotFoundHandler = (ctx) =>
  ctx.render(
    <div class="grid h-full place-items-center">
      404 Not Found
    </div>,
    {
      title: 'Not Found',
    }
  );
```

This works fine locally, but once deployed to CF Pages, the `notFound` handler stops working and you just receive `404 Not Found` as the response.

Adding a 404.html page to the uploaded `dist` doesn't seem to solve the issue either, and the same `text/plain` response is served.

```sh
.
└── dist/
    ├── static/
    │   └── styles.css
    ├── _worker.js
    └── 404.html
```

Using logs, it appears the the `notFound` handler is never invoked. I presumed adding a 404.html file would fix the issue, yet it still persists.

### What is the expected behavior?

I would expect either the `notFound` handler to fire, or default to the 404.html page per the CF Pages documentation.

### What do you see instead?

A `text/plain` response, which appears to be the default Hono 404 response.

### Additional information

[CF Pages 404 Docs](https://developers.cloudflare.com/pages/platform/serving-pages/#not-found-behavior)

This is a similar issue, but in my case I am not using `fetch`, I am serving pages via `ctx.render`. https://github.com/honojs/hono/issues/855

**Comment by yusukebe** [comment]
Hi @bruceharrison1984 

Thanks for raising the issue. I've found the cause of it. I'll create a PR to fix this bug later.

**Comment by yusukebe** [comment]
@bruceharrison1984 

This might be fixed with [`@hono/vite-cloudflare-pages@v0.1.1`](https://github.com/honojs/vite-plugins/releases/tag/%40hono%2Fvite-cloudflare-pages%400.1.1) which is released now.

Could you upgrade it and re-build it?

**Comment by bruceharrison1984** [comment]
Yep, I'll give it a shot once I get started for the day and let you know the results.

**Comment by bruceharrison1984** [comment]
@yusukebe That corrected the issue, thank you for the fast fix!
