### ISSUE TITLE
Param value of "keys" resolves to a function, not the value "keys"

### ISSUE THREAD

**Issue by AverageHelper** [honojs/hono#1713]
### What version of Hono are you using?

3.10.1

### What runtime/platform is your app running on?

Node, Cloudflare Workers

### What steps can reproduce the bug?

Create a Hono app with multiple nested routes:

```ts
// Adapted from Hono's own hono.test.ts, 'Routing' -> 'Nested route' test:

const book = app.basePath("/book");
book.get("/:id", c => {
	// PROBLEM HERE:
	return c.text(`get /book/${c.req.param("id")}`);
});

const user = app.basePath("/user");
user.get("/login", c => c.text("get /user/login"));

const appForEachUser = user.basePath(":id");
appForEachUser.get("/profile", c => c.text(`get /user/${c.req.param("id")}/profile`));
```

### What is the expected behavior?

When a caller requests a route where the `:id` param value is `"keys"`, the result of `c.req.param("id")` should be `"keys"`.

### What do you see instead?

`c.req.param("id")` returns a function instead.

### Additional information

The function seems to be `Array.prototype.keys`. I'm not sure yet under exactly which circumstances this happens, but at some point, when constructing the request context, the params get constructed such that Hono tries to access the `"keys"` property of an array, rather than of an object, and finding a value (the `keys` method of the array), returns it instead of the expected string value.

I have a minimal reproduction of this issue at https://github.com/AverageHelper/hono-bug-param-keys

A failing test for this test may be added to Hono at [src/hono.test.ts](https://github.com/honojs/hono/blob/1ed742bdb80518437e6d6f9c6ec7a5fbe300f254/src/hono.test.ts#L296), around line 296, like so:
```ts
// ...

    res = await app.request('http://localhost/book/123', { method: 'GET' })
    expect(res.status).toBe(200)
    expect(await res.text()).toBe('get /book/123') // currently works

    res = await app.request('http://localhost/book/keys', { method: 'GET' })
    expect(res.status).toBe(200)
    expect(await res.text()).toBe('get /book/keys') // currently fails, as described

// ...
```

**Comment by AverageHelper** [comment]
I have [a fork](https://github.com/AverageHelper/hono/tree/avg/param-keys) where I've already added a failing test as described.

The issue seems primarily to occur in src/request.ts:56: https://github.com/honojs/hono/blob/1ed742bdb80518437e6d6f9c6ec7a5fbe300f254/src/request.ts#L56

I don't know enough yet about Hono internals to get more concrete details than this, much less work out a proper fix.

**Comment by usualoma** [comment]
Hi @AverageHelper!

Thanks for the bug report. I appreciate it.
We will fix it.

**Comment by yusukebe** [comment]
@usualoma Thanks for handling!
