### ISSUE TITLE
bunx create-hono hangs

### ISSUE THREAD

**Issue by noahehall** [honojs/hono#1718]
### What version of Hono are you using?

latest

### What runtime/platform is your app running on?

aws-lambda

### What steps can reproduce the bug?

```sh

poop@spaceship:~/git/private/ogobar
11:58 AM 
$ bunx create-hono nirvgraph

create-hono version 0.3.2
✔ Using target directory … nirvgraph
✔ Which template do you want to use? › aws-lambda
cloned honojs/starter#main to /home/poop/git/private/ogobar/nirvgraph
✔ Copied project files
^C

poop@spaceship:~/git/private/ogobar
12:00 PM 
$ ls nirvgraph/
package.json  README.md  src

```

### What is the expected behavior?

exit process when finished

### What do you see instead?

nothing

### Additional information

all the files seems to be created

**Comment by sor4chi** [comment]
Hi, @noahehall @yusukebe

It worked correctly in my environment.

```
Apple M2 Pro
Bun v1.0.1
create-hono v0.3.2
````

Could you tell me your environment?

**Comment by noahehall** [comment]
@sor4chi 

Linux 6.2.0-37-generic x86_64 x86_64

it worked for me too, just never exited.

However, I ended up switching to the bun template (instead of aws-lambda) and it didnt hang

**Comment by sor4chi** [comment]
Hmm..., I think it's not like we're doing anything differently, especially just for the "aws-lambda" template.
Wish I could reproduce that.
