### ISSUE TITLE
Is it possible to omit the default error handling?

### ISSUE THREAD

**Issue by Mushus** [honojs/hono#1734]
### What is the feature you are proposing?

I am considering a middleware implementation of the Tracing mechanism with reference to the following URL
https://docs.powertools.aws.dev/lambda/typescript/latest/core/tracer/#lambda-handler

This would require passing a `segment` instance to the `Hono.onError` event or error handling by the middleware.

Fortunately, I was able to disable the `Hono.onError` event with the following code. However, it is a bit hacky.
```ts
hono.use("*", async (ctx, next) => {
    console.log("start")
    try {
        await next();
    } catch (e) {
        // works good
        console.error("error");
        throw e;
    } finally {
        console.log("end")
    }
});

app.onError(undefined as any);
// or
app.onError((err) => { throw err; });
```

Since the onError event seems to be allowed to be undefined on the HONO codebase, is it possible to allow the use of `unidefined` as an argument to `Hono.onError` or to omit the default error handling?

日本語:
私は次のURLを参考にTracingの仕組みをミドルウェアでの実装を検討しています。
https://docs.powertools.aws.dev/lambda/typescript/latest/core/tracer/#lambda-handler

これには`Hono.onError` イベントに `segment` インスタンスを渡すか、ミドルウェアによるエラーハンドリングが必要です。

幸いにも以下のコードで `Hono.onError` イベントを無効化することができました。ただし少々ハッキーです。
```ts
hono.use("*", async (ctx, next) => {
    console.log("start")
    try {
        await next();
    } catch (e) {
        // works good
        console.error("error");
        throw e;
    } finally {
        console.log("end")
    }
});

hono.onError(undefined as any);
// or
hono.onError((err) => { throw err; });
```

honoのコードベース上ではonErrorイベントがundefinedであることが認められているようですので、 `Hono.onError` の引数に `unidefined` の利用を認めるか、デフォルトのエラーハンドリングをオミットすることはできますか？

**Comment by usualoma** [comment]
Hi @Mushus!

The following is a non-hacky way to trace a request in Hono. Can you still achieve what you want to do in this way?

```ts
const app = new Hono()

app.use('*', async (c, next) => {
  console.log('start')

  await next()

  const status = c.res.status
  if (c.error) { // `c.error` holds an error object thrown by handler
    console.log(`error: ${c.error.message}`)
    c.res = new Response('custom error', {status}) // Error messages can also be customized. Only required if customized.
  } else if (status >= 500) {
    // Some error occurred, but exception has been handled
    console.log('something wrong')
  }

  console.log('end')
})

// same as middleware/powered-by.ts
app.use('*', async (c, next) => {
  await next()
  c.res.headers.set('X-Powered-By', 'Hono')
})

app.get('/noerror', (c) => c.text('hi'))
app.get('/error', () => {
  throw new Error('Error')
})
```

Hono catches errors in handlers immediately with onError to make it easier to write middleware that behaves like X-Powered-By in the code above. If the exception is propagated middleware chain, it is cumbersome to do `try` and `re-throw` the exception in each middleware. It seems to me that the modification to allow `app.onError(undefined)` is not a good one.

### If you still want to omit the default error handler

Even if the above code produces the desired results, if you use middleware to handle errors, you may want to omit the following message output from the default error handler.

```
start
23 |   c.res.headers.set('X-Powered-By', 'Hono')
24 | })
25 | 
26 | app.get('/noerror', (c) => c.text('hi'))
27 | app.get('/error', () => {
28 |   throw new Error('Error')
            ^
error: Error
      at /Users/taku/src/github.com/honojs/hono/handle-error.ts:28:8
      at /Users/taku/src/github.com/honojs/hono/src/compose.ts:45:22
      at dispatch (/Users/taku/src/github.com/honojs/hono/src/compose.ts:20:51)
      at /Users/taku/src/github.com/honojs/hono/handle-error.ts:22:8
      at /Users/taku/src/github.com/honojs/hono/handle-error.ts:21:20
      at /Users/taku/src/github.com/honojs/hono/src/compose.ts:45:22
      at dispatch (/Users/taku/src/github.com/honojs/hono/src/compose.ts:20:51)
      at /Users/taku/src/github.com/honojs/hono/handle-error.ts:7:8
      at /Users/taku/src/github.com/honojs/hono/handle-error.ts:5:20
      at /Users/taku/src/github.com/honojs/hono/src/compose.ts:45:22

error: Error
end
```

This can be omitted by registering a handler with Hono's way.

```ts
app.onError((_, c) => c.text('', 500))
```

**Comment by Mushus** [comment]
Thank you very much.
My knowledge of how to use `Context.error` was insufficient.
That seems to make a lot of sense.
