### ISSUE TITLE
[Refactor] using `#`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1738]
I used to compare using `#` with using only `private` and `#` was slower for accessing properties in a `class`, but I think I was wrong. I might be wrong, wrong?

If it's wrong, we can refactor the code with replacing `private _foo` with `#foo`.

**Comment by metrue** [comment]
> `#` was slower for accessing properties in a class

It's a little counterintuitive to me, as we know property access is slow, but  if I understand it correctly, the `#` does not increase the extra information (like the object type) checking. 

And I came across with this [thread](https://stackoverflow.com/questions/59641564/what-are-the-differences-between-the-private-keyword-and-private-fields-in-types), overall I think go with `#` is a good to go which can help us avoid unexpected behavior and result in huge performance problems.

**Comment by yusukebe** [comment]
Thanks, I understand.

**Comment by yusukebe** [comment]
We can close this.
