### ISSUE TITLE
Develop under the organization?

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#174]
Now Hono is developed in `yusukebe/hono`. But: 

* Project is getting bigger.
* There are some related projects such as "starter template", "for the website", and "examples"...

So, It is a good idea to make the organization for Hono. And transfer this project under the organization.

**Comment by metrue** [comment]
I think it's a good idea to do that, maybe we can have a [Koa-like structure](https://github.com/koajs).

**Comment by yusukebe** [comment]
Moved to <https://github.com/honojs> !
