### ISSUE TITLE
Absolute imports break `typeof app` for rpc client.

### ISSUE THREAD

**Issue by nvsd** [honojs/hono#1746]
### What version of Hono are you using?

3.10.2

### What runtime/platform is your app running on?

bun

### What steps can reproduce the bug?

I have a separate file that has a single test route in it
```typescript
// test-route.ts
import { Hono } from 'hono';

export const route = new Hono().get('/', async (c) => c.text('Hello World!'));
```
in the below code notice `import { route } from 'test-route';` is an absolute import which breaks the type (see screenshot)
```typescript
// index.ts
import { Hono } from 'hono';
import { route } from 'test-route';

const app = new Hono().route('/test', route);

export type AppType = typeof app;

export default app;
```
in the below code, notice that `import { route } from './test-route';` is a relative import which works (see screenshot)
```typescript
import { Hono } from 'hono';
import { route } from './test-route';

const app = new Hono().route('/test', route);

export type AppType = typeof app;

export default app;
```

### What is the expected behavior?
I get strong types with relative imports. I would expect the same behavior with absolute imports.
<img width="710" alt="image" src="https://github.com/honojs/hono/assets/7391612/3dfe7ffd-be88-4429-948f-3fc546aff26a">

### What do you see instead?
I have a broken type with absolute imports.
<img width="710" alt="image" src="https://github.com/honojs/hono/assets/7391612/34c01582-b8ac-4d80-a698-e80260079c60">

**Comment by Holmes-EH** [comment]
I have found that this also happens when using path aliases.
Version 4.0.10

**Comment by sang-au** [comment]
this also happen when I using mono repos, in this case, the api was move to api-package and the client side - react app import the api-package

**Comment by yusukebe** [comment]
I am not ignoring the issue because I don't see a good solution. If anyone knows of a better way, please let me know.

**Comment by fzn0x** [comment]
I think add the `test-route` module from `node_modules` to paths mapping can help this to work @yusukebe 

This is not something that must be handled by Hono.

```ts
// Path mapping
"paths": {
  "@lib/*": ["lib/*"],
  "test-route": ["node_modules/test-route-lib"] // Maps all imports starting with "~/" to "./lib/"
},
```

Also check: https://github.com/zerkalica/zerollup/tree/master/packages/ts-transform-paths#typescript-transform-paths-plugin, basically the idea is to transform absolute imports to relative imports.

![Screenshot 2024-05-06 224325](https://github.com/honojs/hono/assets/50759463/c95b5c5b-d443-4c12-8a11-f782cb821a2b)

**Comment by GabrielHangor** [comment]
Any ides how to approach this in the monorepo setup with separate client/server folders?

I got the similar problem...

![image](https://github.com/user-attachments/assets/6195c97b-4871-4690-8645-e9f9ed2f26b3)

**Comment by GabrielHangor** [comment]
I've finally fixed the issue, it was related to tsconfig in my monorepo...
I had to enable composite: true in the server subrepo and add path reference in the client pointing to tsconfig in the server

**Comment by yusukebe** [comment]
I'll close this issue since it's stale. Thanks.
