### ISSUE TITLE
Chained route with validator loses Env type

### ISSUE THREAD

**Issue by hmnd** [honojs/hono#1755]
### What version of Hono are you using?

3.10.3

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

1. Chain 2 routes, each with a validator
2. Attempt to access variable with `c.get(...)`

See playground [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAIgAt0JiBuAKFElkTgDcBDAG2ABNWZps8BIgHJyGAPRtOPPlGG0aAY3QBneAQCuMAKZQ4AXjhptAdxQUAPAgBqrKMFYAjdtpUAuJjrW2oHtfbQAc2wsAD4ACgBKBU0dKBo4OAA6SDVw4XFhABoWDm5eaHSAKxV0bLhw5kiDUJZInNYVAE80RQrFav1ahATEuEUkwO0YdK8YH2Fo3sSoYY0oNH6kkvQAFXCkFQ1FRVd3OBgoDW1sSN6sM8SU3kVSdMycqXzZYtK0csrO2qqG5tb2r6IaZLIYjYRjCZTPpwWYweaLAYrNDrTbbXYqfaHY6nc5TIA) for repro.

### What is the expected behavior?

Second route retains Env type from router.

### What do you see instead?

Second route loses Env type information.

**Comment by yusukebe** [comment]
Hi @hmnd 

This issue might be fixed in the latest version. Please try it.

**Comment by hmnd** [comment]
That does indeed fix it - thanks for the quick turnaround!
