### ISSUE TITLE
Allow `any` in the eslint

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1758]
I suggest that the ESLint configuration defined in the following link should permit the use of `any`:

https://github.com/honojs/hono/blob/main/.eslintrc.cjs

On the user side, we should avoid using `any` as much as possible. However, in our library development, the frequent use of `any` is often necessary due to potential type mismatches. This situation commonly arises when the type definition and implementation are authored separately, we have to use `any` on the implementation side.

Currently, we avoid this issue using comments like `eslint-disable-next-line @typescript-eslint/no-explicit-any`, but I think it's acceptable to allow the use of `any` throughout the entire project.

**Comment by yossydev** [comment]
@yusukebe
Should I create a PR with a correspondence to add any in eslint settings?

I would like to work on this issue if possible!

**Comment by yusukebe** [comment]
@yossydev 

Please wait a minute! I'd like to consider it a little more time.

**Comment by yossydev** [comment]
@yusukebe 
Yes, sir!

**Comment by yossydev** [comment]
@yusukebe 
I apologize for the delay! I didn't notice that the label was set to `on hols`...!!🙏🏻 

Instead of allowing 'any' on the package side (https://github.com/honojs/middleware/blob/main/packages/eslint-config/index.js), would it be acceptable to modify the eslint file within this repository (https://github.com/honojs/hono/blob/main/.eslintrc.cjs) to allow 'any'?

**Comment by yusukebe** [comment]
Hi @yossydev 

The `on hold` label does not mean to do this immediately, but to leave it unattended. So, let's leave this Issue open for a while!

**Comment by yossydev** [comment]
Hi @yusukebe 

Sorry! I mistakenly thought you were waiting for your own response!

**Comment by yusukebe** [comment]
I think we don't have to allow `any`. So closing this issue now.
