### ISSUE TITLE
"Unable to resolve module hono/client" in expo (react native)

### ISSUE THREAD

**Issue by nvsd** [honojs/hono#1773]
### What version of Hono are you using?

3.10.5

### What runtime/platform is your app running on?

bun

### What steps can reproduce the bug?

- bunx create-expo-app@latest --template tabs@4
- name app "test"
- `cd test`
- `bun add hono`
- edit `(tabs)/index.ts` to include `import {hc} from 'hono/client'`
- add `const api = hc();`
- `bun start` in terminal
- observe error pictured below

### What is the expected behavior?

I would expect to be able to import from hono/client successfully

### What do you see instead?

![image](https://github.com/honojs/hono/assets/7391612/8ecbf65f-99a1-40a7-8c00-eae529edbcb5)

**Comment by Armster15** [comment]
Ran into the same issue but found that enabling package exports broke a couple of React Native packages. So instead of enabling package exports I'm just using `require` to import hono/client
```ts
const { hc } = require("hono/dist/client") as typeof import("hono/client");
```
