### ISSUE TITLE
TypeScript argument type for `showRoutes()` incompatible with Env variables

### ISSUE THREAD

**Issue by hanneswidrig** [honojs/hono#1777]
### What version of Hono are you using?

3.11.0

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

When the `Env` is provided as a generic type parameters on the App instantiation, the showRoutes method has a type error.

```typescript
type Bindings = {
  event: LambdaEvent;
  context: LambdaContext;
};

type Env = { Bindings?: Bindings };

export const publishingApi = new Hono<Env>().basePath("/publishing");
```

For now, I can cast the api as such to remove the TypeScript errors.

`showRoutes(publishingApi as Hono);`

### What is the expected behavior?

No errors

### What do you see instead?

![image](https://github.com/honojs/hono/assets/3399497/22d95041-6c94-4954-a254-1fda9505b1c1)

**Comment by ahmetbicer** [comment]
I'm facing a similar type error when providing the 'Variables' generic type.

`const app = new Hono<{ Variables: ContextVariables }>();`

**Comment by yusukebe** [comment]
Thanks to @NuroDev, it should be fixed in latest version!
