### ISSUE TITLE
Incorrect return type when using custom fetch function with Hono Client

### ISSUE THREAD

**Issue by nvsd** [honojs/hono#1782]
### What version of Hono are you using?

3.10.5

### What runtime/platform is your app running on?

Bun/Expo

### What steps can reproduce the bug?

Given the code below
```typescript
const fetcher = async (input: RequestInfo | URL, init?: RequestInit | undefined) => {
  const token = await getItemAsync(localStorageKey);
  const headers = new Headers(init?.headers);
  if (token) headers.set('Authorization', `Bearer ${token}`);

  return fetch(input, { ...init, headers }).then(async (response) => {
    if (response.ok) {
      return await response.json();
    } else {
      const errorMessage = await response.text();
      return Promise.reject(new Error(errorMessage));
    }
  });
};

export const api = hc<AppType>(url, {
  fetch: fetcher,
});
```
The resulting type is `Promise<ClientResponse<InferResponseType<T>>>`

### What is the expected behavior?

I would expect to get the type `Promise<InferResponseType<T>>`

### What do you see instead?

The returned type is `Promise<ClientResponse<InferResponseType<T>>>` where the `ClientResponse` isn't correct.

### Additional information

~~I believe the `Fetch` type is incorrect at `hono/src/client/types.ts :48`~~
```
export type Fetch<T> = (
  args?: InferRequestType<T>,
  opt?: ClientRequestOptions
) => Promise<ClientResponse<InferResponseType<T>>>
```
~~If I'm reading this correctly, no matter what fetch returns, it's always assumed to have the base `ClientResponse` structure. Could be wrong though.~~
See below comment

**Comment by nvsd** [comment]
Actually, it has to do with this.
```
type ClientRequest<S extends Schema> = {
  [M in keyof S]: S[M] extends { input: infer R; output: infer O }
    ? R extends object
      ? HasRequiredKeys<R> extends true
        ? (args: R, options?: ClientRequestOptions) => Promise<ClientResponse<O>>
        : (args?: R, options?: ClientRequestOptions) => Promise<ClientResponse<O>>
      : never
    : never
} & {
  $url: () => URL
}
```
Just messing around with the declaration file if I change 
`(args?: R, options?: ClientRequestOptions) => Promise<ClientResponse<O>>` 
to 
`(args?: R, options?: ClientRequestOptions) => Promise<O>` 
I get the correct result type, but only because I'm returning the result of `res.json()`, which just so happens to be O in this case. 

You'd obviously want to infer the passed-in fetch function's return type or provide some way for the developer to signal to HC what the function will return.

My TS isn't the best, or I'd PR something. that being said I'd be happy to fix it if someone could steer me in the right direction. In the meantime, I can continue to research to see if I can figure it out.

**Comment by nvsd** [comment]
> You'd obviously want to infer the passed-in fetch function's return type

This actually doesn't make sense, as the return type of fetch is unknown. Hmm.

**Comment by nvsd** [comment]
To try and match what you did, I added a call below where I register the routes
<img width="816" alt="image" src="https://github.com/honojs/hono/assets/7391612/0292b650-4dc1-4931-a552-2d03e72b6285">

**Comment by yusukebe** [comment]
@nvsd 

How about calling a `json()` function?

```ts
const data = await res.json()
```

I think `data` will have the correct type.

**Comment by nvsd** [comment]
`json` doesn't exist due to me returning `response.json()` from the fetcher function.

The type in my screenshots isn't correct.
The type is actually:
```
type User = {
    user: {
        createdAt: string
        id: string
        name: string
        email: string
        picture: string
    }
}
```

**Comment by yusukebe** [comment]
It's not a bug. `fetch` should return `Promise<Response>`.

**Comment by nvsd** [comment]
I'm not claiming that there is a problem with fetch. Hono client is inferring the return type of `api.users.$get()` as `ClientResponse<T>` when it is in fact `T`. In your message above it even confuses you

> @nvsd
> 
> How about calling a `json()` function?
> 
> ```ts
> const data = await res.json()
> ```
> 
> I think `data` will have the correct type.

`json()` doesn't exist on the return of `api.users.$get` because it's incorrect. I've replaced the fetch function with a function that will return the result of `response.json()` so when I call `api.users.$get` the resulting type should be `T`.

**Comment by nvsd** [comment]
Just to call out a bit more explicitly what I'm talking about

```typescript
const fetcher = async (input: RequestInfo | URL, init?: RequestInit | undefined) => {
  const token = await getItemAsync(localStorageKey);
  const headers = new Headers(init?.headers);
  if (token) headers.set('Authorization', `Bearer ${token}`);

  return fetch(input, { ...init, headers }).then(async (response) => {
    if (response.ok) {
    // Because I'm calling res.json() here the type should no longer be ClientResponse<T> but T
      return await response.json();
    } else {
      const errorMessage = await response.text();
      return Promise.reject(new Error(errorMessage));
    }
  });
};

export const api = hc<AppType>(URL, {
  fetch: fetcher,
});
``

**Comment by yusukebe** [comment]
> `json()` doesn't exist on the return of `api.users.$get` because it's incorrect. I've replaced the fetch function with a function that will return the result of `response.json()` so when I call `api.users.$get` the resulting type should be `T`. 

You can't do that. The type of the fetch function must return `Promise<Response>`. You can get `T` by only using `response.json()`. This is because it is impossible or too difficult to infer types from the return values of fetch.

The type of `ClientRequest` is defined in this line, so the fetch function does not affect the type definition.

https://github.com/honojs/hono/blob/0afb5e1bbaeb250be95559bdc59af52ca89efa1e/src/client/types.ts#L88-L90

**Comment by nvsd** [comment]
Ok that makes sense. Thanks for taking the time.
