### ISSUE TITLE
Do not calculate `Content-Length`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#179]
I notice that calculating `Content-Length` makes returning a response slowly.

[This section](https://github.com/honojs/hono/blob/ac713c065924d30b0943ec28a107541057eb363c/src/context.ts#L70):

```js
    let length = 0
    if (data) {
      if (data instanceof ArrayBuffer) {
        length = data.byteLength
      } else if (typeof data == 'string') {
        const Encoder = new TextEncoder()
        length = Encoder.encode(data).byteLength || 0
      }
    }
```

Wrangler, Miniflare, or Cloudflare calculate `Content-Length` and add to a header automatically. So, we do not have to do it by ourselves. So, how about removing this section?

If we remove it, `logger` middleware can not show `Content-Length`.

**Comment by metrue** [comment]
Yeah, the `Content-Length` is normally only useful in debugging, so it makes sense to remove it since Cloudflare already does it.
