### ISSUE TITLE
Environment variables are not accessible via `c.env` in Bun

### ISSUE THREAD

**Issue by insumanth** [honojs/hono#1799]
### What version of Hono are you using?

3.11.4

### What runtime/platform is your app running on?

Bun - 1.0.15

### What steps can reproduce the bug?

Save an Environmental Variable in ENV File `.env` `.env.local` etc.,
Try to read the value from the Hono using `c.env`

```sh
$ cat .env 
FOO=world
BAR=hello$FOO
```

```ts
$ cat src/index.ts 
import { Hono } from 'hono'
const app = new Hono()
app.get('/', (c) =>  c.json({ hono: `${c.env.FOO}`, bun: `${process.env.FOO}`  }) )
export default app

```

```bash
$ curl http://localhost:3000
{"hono":"undefined","bun":"world"}
```

### What is the expected behavior?

Environmental Variables should be available in `c.env` in Hono as they are available in `process.env`

### What do you see instead?

`c.env` is empty object without any values even though there are many Environmental variables.

### Additional information

Attaching Whole `c` value
```ts
{"c":{"env":{},"_var":{},"finalized":false,"req":{"routeIndex":0,"bodyCache":{},"raw":{},"path":"/c"}}}
```

**Comment by yusukebe** [comment]
Hi @insumanth 

In Bun, you can use the `env()` from `hono/adapter` to get variables:

https://hono.dev/helpers/adapter#env

**Comment by insumanth** [comment]
Thanks for pointing it.
I was trying to convert Existing Cloudflare Worker to Run on Bun and faced this issue.

It was a little unclear in the [Hono context env docs](https://hono.dev/api/context#env) docs. I think it is better to mention that this works only in Cloudflare Workers.

If you think the same, I would love create a PR with the changes in [honojs/website](https://github.com/honojs/website)

**Comment by yusukebe** [comment]
@insumanth 

> If you think the same, I would love create a PR with the changes in [honojs/website](https://github.com/honojs/website)

Please do!

**Comment by insumanth** [comment]
Created Pull Request with Changes at honojs/website#175

**Comment by yusukebe** [comment]
@insumanth 

Thanks! I'll close this issue.
