### ISSUE TITLE
allow c.stream to receive raw readable stream

### ISSUE THREAD

**Issue by sor4chi** [honojs/hono#1807]
### What is the feature you are proposing?

Currently, to return a readable stream in Hono, you have to write a raw response object. In this case, `setCookie` cannot be used.

Therefore, I think it will be useful to be able to pass a readable stream directly to `c.stream` and return the stream from context via `newResponse`.

**Comment by yusukebe** [comment]
> Currently, to return a readable stream in Hono, you have to write a raw response object. In this case, `setCookie` cannot be used.

If my understanding is correct, this is a bug. I'm working on fixing it now.

**Comment by sor4chi** [comment]
That's a bug, not a spec, I understand. But wouldn't it be easier if you could pass a readable stream to `c.stream` because you don't have to write a response object?

like: 

```ts
const s = renderToReadableStream(<App />)
return c.stream(s, {
  'X-Hoge': 'Hi'
})
```

**Comment by yusukebe** [comment]
You can do it with the `c.body()`.

**Comment by sor4chi** [comment]
Oh, I forgot that, sorry. Thank  you.
