### ISSUE TITLE
404 Not Found on route

### ISSUE THREAD

**Issue by frogconn** [honojs/hono#1813]
### What version of Hono are you using?

3.11.5

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

update to v3.11.5 and call the same route every request returns 404.

![image](https://github.com/honojs/hono/assets/2070583/8ed1dbea-e71b-494f-9673-b8e5bcf5e79e)

![image](https://github.com/honojs/hono/assets/2070583/3f6097eb-4dda-473e-9958-6e9b2b09b976)

![image](https://github.com/honojs/hono/assets/2070583/c0f9d5d7-7692-45ae-8e72-e0307ea2d92d)

**Comment by yusukebe** [comment]
Hi @frogconn 

Can you share the code?

**Comment by frogconn** [comment]
> Hi @frogconn
> 
> Can you share the code?

After re-produce problem can be with this line

![image](https://github.com/honojs/hono/assets/2070583/c1021132-7ea1-4f16-a87a-ff5bd2b342f9)

If my comment 

```
app.use('/*', cors({ origin: ['http://localhost:3003'] }))
```

all request is return to

**Comment by frogconn** [comment]
My test on default template

**This case is work.**
Code
![image](https://github.com/honojs/hono/assets/2070583/4ce367e5-c2e9-4f8a-9611-b1ec8ee10fe3)

Result
![image](https://github.com/honojs/hono/assets/2070583/406a4070-bc2f-4588-b58a-ba8d97d80c56)


**This case is a problem**
Code
![image](https://github.com/honojs/hono/assets/2070583/cb74140c-e088-4f09-afd3-584031ed3762)

Result
![image](https://github.com/honojs/hono/assets/2070583/fe837b3f-098e-4aaf-8ae2-2bb68bb37e53)

**Comment by yusukebe** [comment]
@frogconn

Thanks! That was the bug which is produced by the change to fix another bug in `v3.11.5`.

I've fix this and released the `v3.11.6`. Please try it out!
