### ISSUE TITLE
Post Request Returns 404 when using `app.request`

### ISSUE THREAD

**Issue by patrickkabwe** [honojs/hono#1840]
### What version of Hono are you using?

^3.11.8

### What runtime/platform is your app running on?

Node, Bun, Deno and Cloudflare

### What steps can reproduce the bug?

```js
import { Hono } from "hono";
const app = new Hono().basePath("/api/v1/");
authRouter.post("login", userHandlers.login);

 it("POST /login - should login user", async () => {
    const res = await app.request("/auth/login", {
      method: "POST",
      body: JSON.stringify({
        email: "test@gmail.com",
        password: "test",
      }),
    });

    expect(res.status).toBe(200); // returns 404 
  });
```

### What is the expected behavior?
```js
import { Hono } from "hono";

const app = new Hono().basePath("/api/v1/");
authRouter.post("login", userHandlers.login);

 it("POST /login - should login user", async () => {
    const res = await app.request("/auth/login", {
      method: "POST",
      body: JSON.stringify({
        email: "test@gmail.com",
        password: "test",
      }),
    });

    expect(res.status).toBe(200); // should work fine 
  });
```

### What do you see instead?

![image](https://github.com/honojs/hono/assets/64147010/d6c15086-b2e0-43a4-b15f-18ef9bbf0229)

### Additional information

I have a fix for this i can work on it @yusukebe should i open a PR for it?

**Comment by yusukebe** [comment]
Hi @patrickkabwe 

Could you share the workable code to reproduce the bug? The following works fine:

```ts
import { Hono } from 'hono'

const app = new Hono().basePath('/api/v1/')
app.post('/foo', (c) => c.text('Hi'))

const res = await app.request('/api/v1/foo', {
  method: 'POST',
  body: JSON.stringify({}),
})

console.log(res.status) // 200
```

**Comment by patrickkabwe** [comment]
Hi @yusukebe, 

I appreciate the code snippet you provided earlier. I realized that I wasn't including the basePath in the request method. My assumption was that since the basePath is defined on the Hono instance, the router would automatically append it to the request. i guess this shouldn't be a bug but may be an `enhancement` would be nice to have. I'd like to hear your thoughts on this.

**Comment by yusukebe** [comment]
@patrickkabwe 

> the router would automatically append it to the request.

That is not a bad idea. But, I think some users may think of writing `basePath`, so there is no need to implement it additionally.

**Comment by sikaili99** [comment]
Hi @yusukebe,

I think @patrickkabwe has a point, if the Hono instance takes a basePath, I am not expecting to keeping adding the basePath on every request I am making. I will definitely think that the basePath was added when Hono was initialized.

**Comment by yusukebe** [comment]
@sikaili99 

I know that. However, since `app.request()` can also receive a Request object, we must consider how to handle the request URL of that Request object.

Either way, we might not be able to use `basePath()` anymore because of the following changes to the API.

https://github.com/honojs/hono/issues/1843

**Comment by yusukebe** [comment]
I will follow the current following specifications.

> I know that. However, since `app.request()` can also receive a Request object, we must consider how to handle the request URL of that Request object.

This can be closed.
