### ISSUE TITLE
v3.11.5 breaks typed routes on the client

### ISSUE THREAD

**Issue by MonsterDeveloper** [honojs/hono#1842]
### What version of Hono are you using?

v3.11.9

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

[Link to TS Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBSBlA8gOQApQCWAtoTIQG6oC8cAzjEQHYDmcAPnAEYQQA2wAIZMOcJgFdiXYFFES+fUeKYATYADNCTYCoBQoSLATJUmXAEEoUQYji0AFGfxFS5KqKdYuAK2ABjeE4nS2tEAEoAbQBdfXBoeCQUdGwcL18AuzgAbzgIgGtgRAAuekYtFiiSpwISMkpUIJSQmw8UtP9AuAgfDrgAX1jDBJNk3AA1QT5xGlHUnozGiysWxedat2BB+OMk6sEoOh0AHgAVAD5MrN04XLy4LTgCxAh1OBPKt-youFAYYFU6LMJlNUAB+T55b4lBjMFi6Ab6CTEOAYQTEMACACiSOy1zgwOmAEZMgAiCiTIkkgA0eIJwAATKTySD6dT4bpdFo-lB1II-KgALLAGCCXE3YjCwQqQQikpXG43AAWUA00LKrAA3HibnQ0RjgNjJCVUeisUitTcBgiuTJefyUXqBABJJjcu2oeX0CASoWyuC+wRahGJVAAJWAdHEfHgtD2B2OJv1LrdfOAZwtcAA9Jm4AA9UEczno7Yh7LoOgQJiEdSIKn9ODqKDeuAkkMAWnUEZgJK1JCGOw9GD7fGriAAIsBgGA+g2m8jWyYO13MxXxFB+ZmJVAWMA22opz2OaW0BWq5odJkT5XR0dE87XbbU+m8dm8wXdMfT9XCDoh6bvzotB-hio4TlORxXmeiC3o6wDJo+-JnGcL45vmQA)

### What is the expected behavior?

Client should correctly transform the type of objects.

### Additional information

After an update to v3.11.9, the types for Hono client's responses in my app are now broken. The bug was introduced in v3.11.5 in PR #1806 

Although transforming types to JSON works fine with simple objects, once you start using nested objects and interfaces, it falls apart.

The `Jsonify` utility from [type-fest](https://github.com/sindresorhus/type-fest) works fine, however. In the end of the playground I showed the correct types using this utility.

I believe the fix should be easy to implement (i.e. just use the code from `type-fest`).

**Comment by yusukebe** [comment]
Hi @MonsterDeveloper 

Thanks for raising the issue. To think about this more deeply, can you show me the minimal code to reproduce your problem?

**Comment by yusukebe** [comment]
Related to https://github.com/orgs/honojs/discussions/1824

**Comment by MonsterDeveloper** [comment]
@yusukebe here's a [link to a playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAIgAt0JiBuAKFElkTlIGNs8CiyKB6FgG2ABTNDGp1w0eEgDK9QbgCe7fIRIxFYIQFpcQgM5jaNFukNwAhmDBwAvHDRCA7igoAKAJTGRAVyIyLcH4hAFE0P0QaODgANQt+HyEARjsSADd4xKTiABoo2MyhACZU4gyE4tyaLBo6USEoXAsWITgAWSEYC0jokE6LABMLLoAuHujmKCFcMcMoYDQAc1oJuH1AsGCwvzGAoNDwkBXsatqFmAamlrg9zaEASXrG5taEfP1CIQ7R9v7aGpMZng632AHkAEYAKyELBguw2wUeF2e13sb2iHz63wsY3REz6XSGPzxq1IUxmJCqqwxCIOOxutO2IAAdHEKkl8tEalzqsZTGhzAQfBd9KkrGBmYtOm5iDxcnB+RcAB7wWwAPgV6GVMGZkI+aDcILuEOhsI8XlqGi0cAAShBhQZUlahBBcHAhSK+UCFYIRKrmCwADx2h36NUy4gWwEC+BTfSQAWtewWJwWYDwATCUTMhYDIRK5kAEilME8tH55iJ3WTqfT7oMCf0Ql1+rL+R4PDgAD0APy1Ds3eTAJRwHxNgZ4aBwYD8BJzYbAdBwMA+KCQJuimCYXPAFjDVowUjDOAAA0xX36J7giwg8Bgq8cE-OmDmC0WNGdg6Cw+EAwAIsM1Zfpsw6KIGzqunAVZqscA69kAA) with a simple Hono app.

Please note how `someMeta` got turned into `string` for some reason, although the `SampleInterface` surely is losslessly jsonifiable.

![CleanShot 2023-12-23 at 14 01 04](https://github.com/honojs/hono/assets/16190582/e736f0af-75e6-4f31-a754-8dffd79dd2c6)

**Comment by MonsterDeveloper** [comment]
It seems to me this is the issue with interfaces only. Plain types are transformed correctly.

I think [this remark](https://github.com/sindresorhus/type-fest/blob/00233da395d208a9f7044ff6692caa432305b187/source/jsonify.d.ts#L45C1-L45C153) from `type-fest`'s `Jsonify` is related to this behavior.

I'm not sure whether it is possible at all to make json transforms work with interfaces.

**Comment by yusukebe** [comment]
@MonsterDeveloper 

How about using the `JSONParsed` as below?

```ts
export type JSONParsed<T> = T extends { toJSON(): infer J }
  ? (() => J) extends () => JSONObject
    ? J
    : JSONParsed<J>
  : T extends JSONPrimitive
  ? T
  : T extends Array<infer U>
  ? Array<JSONParsed<U>>
  : T extends JSONObject | {}
  ? { [K in keyof T]: JSONParsed<T[K]> }
  : never
```

**Comment by MonsterDeveloper** [comment]
Seems to be working just fine. Thanks!
