### ISSUE TITLE
The X day is Feb 9th (maybe)

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1844]
This is just an announcement.

We/I will release Hono version `v4.0.0` on **February 9, 2024**.

This release includes two major changes.

One is **the removal of deprecated features**. Breaking changes are painful but necessary to keep Hono small and simple.

The other is to **implement file-based routing**. I don't know if this will work, but it is worth a try. We are implementing this within the internal project and will make it public at or shortly before the `v4.0.0` release.

Looking forward to it!

**Comment by harrytran998** [comment]
Love to see your efforts and v4 🔥

**Comment by chillbrodev** [comment]
Nice to see continued support! Recently found Hono and have been enjoying it immensely. 🎉

**Comment by bruceharrison1984** [comment]
> The other is to implement file-based routing. I don't know if this will work, but it is worth a try. We are implementing this within the internal project and will make it public at or shortly before the v4.0.0 release.

Does that mean this project will be taking over for what `Sonik` was providing?

**Comment by yusukebe** [comment]
@bruceharrison1984 

> Does that mean this project will be taking over for what `Sonik` was providing?

Exactly!

**Comment by soulchild** [comment]
I recently fell in love with Hono (especially with the zod-openapi middleware) my only **minor** gripe right now is the fact that the validation errors do not end up at the global error handler, as proposed in https://github.com/honojs/hono/issues/1441. I really like having only one central error handler to make all errors as uniformly as possible. This would possibly also fix https://github.com/honojs/middleware/issues/323. Any chance this is gonna make it into v4? If not, do you still think this will be implemented in the near future? Thank you for creating Hono! ❤️

**Comment by yusukebe** [comment]
> This would possibly also fix https://github.com/honojs/middleware/issues/323. Any chance this is gonna make it into v4?

Yeah. I'll implement it soon and include the fix in v4!

**Comment by airyland** [comment]
Wow. I have done a file-based routing myself.
