### ISSUE TITLE
v3.11.7 breaks some router params

### ISSUE THREAD

**Issue by gourgouris** [honojs/hono#1847]
### What version of Hono are you using?

3.11.7

### What runtime/platform is your app running on?

node

### What steps can reproduce the bug?

Upgrading to the latest recommended Security Update breaks path patterns that used to work.
Not all of them. But I managed to narrow it down to the following repro

```
import { serve } from '@hono/node-server'
import { Hono } from 'hono'

const app = new Hono()
app.get('/a/b/cc/:d?', (c) => c.text('Hello Hono!'))

app.get('/a/:bb/cc/dd', (c) => {
    const { bb } = c.req.param();
    return c.text(bb ?? "PROBLEM");
});

serve(app)
```

run http://localhost:3000/a/abcd/cc/dd and you'll see "PROBLEM"
run it with 3.11.6 and you'll see "abcd"

### What is the expected behavior?

With 3.11.6, the `bb` param had the value populated from path

### What do you see instead?

`undefined`

### Additional information

It is unfortunate that we can't pull the latest recommended security update as it breaks the routing unexpectedly

**Comment by yusukebe** [comment]
Hi @gourgouris 

Thank you for raising the issue. This was exactly a bug. I've fixed it and released a new version, `v3.11.10,` including the fix. Please update and try it out.
