### ISSUE TITLE
add hono+prisma example

### ISSUE THREAD

**Issue by zuohuadong** [honojs/hono#1866]
### What is the feature you are proposing?

Prisma is a very useful ORM library

I would like to provide an example of hono + prisma being used.

**Comment by enemaliwilliam** [comment]
Here's an [Example](https://github.com/enemaliwilliam/hono-prisma). Let me know if you need any help

**Comment by zuohuadong** [comment]
@enemaliwilliam It's so exciting.
But I want localized Prisma, not Prisma Cloud. Also, can I add appllographql or graphql API?

**Comment by enemaliwilliam** [comment]
Should be same steps except the migration part `npx prisma migrate dev`.  You also can't use templates that are deployed on edge runtime like cloudflare workers

**Comment by yusukebe** [comment]
This is not actually Hono's issues, e.g., bugs or features. So, now, closing.
