### ISSUE TITLE
showRoutes() emits escape codes when running in deployment

### ISSUE THREAD

**Issue by begoon** [honojs/hono#1881]
### What version of Hono are you using?

3.11.11

### What runtime/platform is your app running on?

Deno/CloudRun

### What steps can reproduce the bug?

Use `showRoutes()` function when the code runs in a cloud deployment.

### What is the expected behavior?

It should not use escape codes because they only make sense when running locally in the console.

### What do you see instead?

![image](https://github.com/honojs/hono/assets/84461/e4407c37-e880-4b1d-80c9-d5f69701d179)

**Comment by yusukebe** [comment]
Hi @begoon 

Thank you for raising the issue.

The code is included to color the text in the development environment. `showRoutes()` is a development function as exported from `hono/dev`, and is not intended for use in the deployment environment.

However, if you have the ability to customize the output of `showRoutes()`, your request can be fulfilled, so I made a PR #1883.

**Comment by begoon** [comment]
Fixed in 3.12.0.
