### ISSUE TITLE
Remove Lagon runtime tests

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1888]
### What is the feature you are proposing?

Lagon has joined Vercel!

Lagon will be closed. So, ~~the adapter~~ the runtime tests are not needed. We can make remove them in v4.

**Comment by yusukebe** [comment]
cc: @QuiiBz 

We will do that!

**Comment by QuiiBz** [comment]
Sounds good, thanks for flagging this!

**Comment by yusukebe** [comment]
Closed by #1971
