### ISSUE TITLE
Bad status from server - handle in then block

### ISSUE THREAD

**Issue by taykachess** [honojs/hono#1908]
### What version of Hono are you using?

3.11.12

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

Just sent to endpoint with header Authtorization needed. 
honoClient.user.me.$get().then(console.log).catch(console.log)
return status 401

### What is the expected behavior?

Console in catch block.

### What do you see instead?

Console in then block.

**Comment by yusukebe** [comment]
Hi @taykachess 

It's not a bug. The return from `client.user.me.$get()` is a `Response` object, so it is not caught by the `catch` block. The following code is the correct behavior.

```ts
const client = hc<typeof route>('http://localhost:3000')
const res = await client.user.me.$get()
console.log(res.status) // 401
```

**Comment by taykachess** [comment]
Ok, I see, thank you!
