### ISSUE TITLE
Wrong type definitions when using zod validation

### ISSUE THREAD

**Issue by Arctomachine** [honojs/hono#1912]
### What version of Hono are you using?

3.12.0

### What runtime/platform is your app running on?

Node, but it is not platform specific

### What steps can reproduce the bug?

1. Set up project, install zod and create schema (any fields)
2. Create new endpoint and apply validator (default validator, not zValidator) with json target. Inside validation function use safeParse method and return data on success
3. Inside endpoint main function create new variable like this `const data = c.req.valid('json')`
4. Now try to access properties of data - this is part 1 of this bug
5. For part 2 of this bug go to schema definition. Add field `type`, it can be string, enum of strings
6. Try to access properties of data again

### What is the expected behavior?

Show all properties defined in schema

### What do you see instead?

1. The only available property is json. Selecting it will show `TS2339: Property json does not exist on type`
![image](https://github.com/honojs/hono/assets/29041820/9dc2e134-49e3-4ecc-a783-b3cbd2508aec)
2. The only available property is type. It merged type from schema with ResponseType
![image](https://github.com/honojs/hono/assets/29041820/95563bac-020e-4c92-a601-3943a197d0c3)
Only inside typeguard to exclude possibility of ResponseType it finally shows all properties from schema
![image](https://github.com/honojs/hono/assets/29041820/eff2881a-2d9f-4ce8-b3c3-4c936111c038)

**Comment by yusukebe** [comment]
Hi @Arctomachine 

Please share your code!

**Comment by Arctomachine** [comment]
Here is complete reproduction on default template.
I found the issue. Line 22, early return in validator function. If it is set to text (as in docs example), everything works. But if it is set to json, this bug happens.
```ts
import { serve } from '@hono/node-server'
import { Hono } from 'hono'
import { z } from 'zod'
import { validator } from 'hono/validator'

const app = new Hono()

const testSchema = z.object({
	name: z.string(),
	age: z.number(),
	// uncomment next line for bug with type (in addition to line 22)
	// type: z.enum(['a']),
})

app.post(
	'/posts',
	validator('json', (value, c) => {
		const parsed = testSchema.safeParse(value)
		if (!parsed.success) {
			return c.text('Invalid!', 401)
			// comment previous line and uncomment next line to trigger bug
			// return c.json({ errors: parsed.error.issues }, 401)
		}
		return parsed.data
	}),
	(c) => {
		const data = c.req.valid('json')

		console.log(data)

		return c.json(
			{
				message: 'Created!',
			},
			201,
		)
	},
)

const port = 3000
console.log(`Server is running on port ${port}`)

serve({
	fetch: app.fetch,
	port,
})
```
