### ISSUE TITLE
Cache middleware ignores handler Cache-Control settings

### ISSUE THREAD

**Issue by eduardvercaemer** [honojs/hono#1915]
### What version of Hono are you using?

3.12.0

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

1. Create new hono app
2. Add cache middleware (i.e. max-age=3600)
3. Inside of some handler that returns user data, do `c.header("Cache-Control", "private", { append: true })`

### What is the expected behavior?

Individual handlers should be able to append extra directives to cache-control header.

### What do you see instead?

The cache middleware always overrides the response cache-control to a static header.

### Additional information

The fix is real easy: In https://github.com/honojs/hono/blob/main/src/middleware/cache/index.ts#L13 change to
```
  const addHeader = (c: Context) => {
    if (options.cacheControl)
      c.header("Cache-Control", options.cacheControl, { append: true });
  };
```

I can make a PR if needed.

**Comment by yusukebe** [comment]
Hi @eduardvercaemer !

Thank you for reporting, it's a bug!

> I can make a PR if needed.

Please!
