### ISSUE TITLE
Optional parameter is ignored

### ISSUE THREAD

**Issue by robingenz** [honojs/hono#1919]
### What version of Hono are you using?

3.12.0

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

Create the following route:

```ts
app.get("/:workspace{(@[\\dA-Za-z]*)?}/:user", async (context) => {
  console.log("Hello!");
});
```

### What is the expected behavior?

I would expect this route to match `/@myworkspace/myuser` and `/myuser`. 

### What do you see instead?

However, it only matches with `/@myworkspace/myuser`.

**Comment by yusukebe** [comment]
Hi @robingenz 

You can write like the following, but it does not match `/myuser`, though it will match `/@myuser`. 

```ts
app.get('/:workspace{@[\\dA-Za-z]*}/:user?', (c) => {
  return c.json({
    params: c.req.param(),
  })
})
```

**Comment by yusukebe** [comment]
I think you will have to separate the route into two to achieve what you want to do.

```ts
app.get('/:workspace{@[\\dA-Za-z]*}/:user', (c) => c.text(c.req.routePath))
app.get('/:user', (c) => c.text(c.req.routePath))
```

**Comment by robingenz** [comment]
Thank you for your fast response!

> You can write like the following, but it does not match /myuser, though it will match /@myuser.

That doesn't help me, unfortunately. In this case, I will split the routes and wait until #1901 is implemented.

**Comment by yusukebe** [comment]
@robingenz 

Understood. However, it is not a bug about this Issue, but the expected behavior. We do not plan to implement #1901 immediately, but will consider it.

**Comment by robingenz** [comment]
Alright, i will close this issue.
