### ISSUE TITLE
setCookie middleware is not working with 2 or more cookies in deno deploy

### ISSUE THREAD

**Issue by diecodev** [honojs/hono#1927]
### What version of Hono are you using?

3.11.12

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

Create a endpoint, use the setCookie middleware to set 2 cookies or more, deploy the project and make the request to the endpoint url.

### my code:
![image](https://github.com/honojs/hono/assets/51871681/fad50b82-c242-4249-b153-3c2bb166767b)

## The server response
![image](https://github.com/honojs/hono/assets/51871681/bbd88059-8dac-40c7-a0b8-653e2041d4c6)

As you can see, only the last cookie y set in response headers. I have checked if the token_name is added to the environment variables and is reading it correctly.

### What is the expected behavior?

Two cookies in the response headers.

### What do you see instead?

Only the last cookie is set.

### Additional information

this is my deno.json file with the hono imports:
![image](https://github.com/honojs/hono/assets/51871681/cffc7d74-897b-4465-94e9-464c014d0942)

I'm using the helper, so I am importing setCookie middleware from: https​://deno.land/x/hono​@v3.11.12/helper/cookie/index.ts

**Comment by yusukebe** [comment]
Hi @diecodev 

I can't reproduce it. I can set two cookies with `setCookie()` in the cookie helper on Deno Deploy. Could share us minimal code to reproduce the bug?

**Comment by diecodev** [comment]
hi @yusukebe

After bunch of local testing it seems like the [compress() middleware](https://hono.dev/middleware/builtin/compress) is the cause of the problem, i let you a link to the [reproduction link and code](https://dash.deno.com/playground/share-cobra-63)

**Comment by yusukebe** [comment]
@diecodev 

Thank you very much! I'll see it later.
