### ISSUE TITLE
Document for `Env` variables

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#194]
Write a document on how to handle Environment variables for Cloudflare Workers. Like this:

```ts
app.post('/posts', async (c, next) => {
  const auth = basicAuth({ username: c.env.NAME, password: c.env.PASS })
  await auth(c, next)
})
```

**Comment by codenoid** [comment]
why @yusukebe didn't mention the pull request?

**Comment by yusukebe** [comment]
@codenoid 

Which pull request? This topic is already documented:
https://hono.dev/getting-started/cloudflare-workers#using-variables-in-middleware

**Comment by codenoid** [comment]
@yusukebe I want to read env var outside the handler, is it possible?

**Comment by yusukebe** [comment]
On Cloudflare Workers, If you use a Module Worker mode, you can't read the variables outside the handler.

**Comment by fujohnwang** [comment]
So I have to create instance at request each time?

**Comment by yusukebe** [comment]
If you are using Cloudflare Workers, I recommend creating an instance every time. The process may run for a while, but it could disappear at any time.

**Comment by Sammy3102** [comment]
@yusukebe how do you create env variables in hono for cloudflare examples , like do we create a .env file?? 
The below code is only about how to access the env variable but not about how to create them
`app.post('/posts', async (c, next) => {
  const auth = basicAuth({ username: c.env.NAME, password: c.env.PASS })
  await auth(c, next)
})`

**Comment by yusukebe** [comment]
Hi @Sammy3102 

Write them on wrangler.toml: https://developers.cloudflare.com/workers/configuration/environment-variables/

**Comment by NaingAungLuu** [comment]
Hello guys.
I had the same issue while trying to access the environment variables that were stored in `.dev.vars`.
My setup was using `workerd` runtime and took me a long time to figure out.

The problem with my setup is that I was starting my `Hono` app with the `app.fire()` as follows:

```typescript
const app = new Hono<{ Bindings: Bindings}>();
app.fire()
```

After updating my code to start the app with `export default app;`, the cloudflare workers start to recognize the environment variables.
```typescript
const app = new Hono<{ Bindings: Bindings}>();
// Can't access env var
app.fire()

// Can access env var
export default app;
```

The particular information was mentioned in Documentation, in [Cloudflare Workers](https://hono.dev/getting-started/cloudflare-workers) page, but wasn't easily noticeable in the docs.

**Comment by dev-rajm** [comment]
Added your env variables in `wrangler.jsonc` or `wrangler.toml` file and you good to go.

**Comment by vivek-79** [comment]
is  there a way to access the env variables out of context in hono ? as i need sone keys out of functions

**Comment by vehm** [comment]
> is there a way to access the env variables out of context in hono ? as i need sone keys out of functions

Ever find anything for this @vivek-79? I'm aware I can use `process.env`, but for the sake of being runtime agnostic...

**Comment by vivek-79** [comment]
no

**Comment by mderazon** [comment]
I was just looking for the same thing - How to read env outside a request handler in a runtime agnostic manner.

But to be fair, it's probably not for Hono to solve. At this point in time, it looks like it's still undecided:
https://github.com/WinterTC55/environment-metadata/issues/1

Someone mentions this in the comments in the meantime:
https://github.com/unjs/std-env
