### ISSUE TITLE
missing async in docs

### ISSUE THREAD

**Issue by mvolkmann** [honojs/hono#1958]
### What version of Hono are you using?

3.12.3

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

See the docs at https://hono.dev/api/routing. They show passing a regular function to `app.post`, `app.put`, and `app.delete`, but the function must be `async`. For example, this will NOT work:

```ts
app.post('/dog', (c: Context) => {
  return c.text('in post');
});
```

But this WILL work:

```ts
app.post('/dog', async (c: Context) => {
  return c.text('in post');
});
```

So I think the docs need to be updated to show where `async` is needed.

### What is the expected behavior?

Update the documentation.

### What do you see instead?

Incorrect documentation.

**Comment by yusukebe** [comment]
Hi @mvolkmann 

In that case, `async` is not needed.

**Comment by mvolkmann** [comment]
Ah, that makes sense. I only needed `async` because I was calling `c.req.json` which requires `await`.
