### ISSUE TITLE
SSG: Handling when `response.text()` can not parse

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#1962]
This line uses `response.text()`. However, it is better to handle ArrayBuffer and other contents that cannot be parsed with `text()`.

https://github.com/honojs/hono/blob/04b686ca39421d28d3aa3f8491c13e1f7d1c8de1/src/helper/ssg/index.ts#L37

**Comment by watany-dev** [comment]
Regarding the SSG issue, I'll tackle it here first
