### ISSUE TITLE
Cron Middleware

### ISSUE THREAD

**Issue by sor4chi** [honojs/hono#1972]
### What is the feature you are proposing?

I think it would be useful to be able to manage Cronjobs in Hono.

For example, I am thinking of an interface like this.

```ts
app.use(
  cron('hello-cron', {
    cron: '* * * * * *',
    enable: true, // this is an option
    handler: () => {
      console.log('Hello World') // every seconds
    },
  })
)

app.get('/enable', (c) => {
  c.var.cron.enable('hello-cron') // enable timer
})

app.get('/disable', (c) => {
  c.var.cron.disable('hello-cron') // disable timer
})

app.post('/trigger', (c) => {
  c.var.cron.trigger('hello-cron') // trigger at any time
})

app.post('/create-job', (c) => {
  c.var.cron.set('goodbye-cron', {
    cron: '* * * * * *',
    handler: () => {
      console.log('Goodbye World')
    },
  }) // add to cron jobs
})

app.post('/delete-job', (c) => {
  c.var.cron.delete('goodbye-cron') // remove form cron jobs
})
```

**Comment by sor4chi** [comment]
This project would be helpful.
https://github.com/hexagon/croner

**Comment by yusukebe** [comment]
At first glance, this is out of Hono's scope.

**Comment by sor4chi** [comment]
HI, @yusukebe

Indeed, it should have been put up on Hono/middleware instead of Hono in the first place.
How about putting the croner wrapper as @hono/cron?

**Comment by yusukebe** [comment]
I don't like it much; Hono is for the web, so cron is not the target.

**Comment by sor4chi** [comment]
I understand. I respect your opinion.

**Comment by AustinZhu** [comment]
Hi @sor4chi 
You may want to take a look at this project! It's inspired by Hono but for Cloudflare Workers cronjobs. I hope it's useful to you.
https://github.com/AustinZhu/kuron
