### ISSUE TITLE
No detailed type support for Deno.

### ISSUE THREAD

**Issue by itsfuad** [honojs/hono#1998]
### What version of Hono are you using?

3.12.3

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

I need to use // @deno-types="npm:hono" to get the proper type suggestion.

**Comment by linhub15** [comment]
I was able to get detailed type support when importing the Deno module from `import { Hono } from "https://deno.land/x/hono@v3.12.4/"`.

**Comment by itsfuad** [comment]
![image](https://github.com/honojs/hono/assets/49100463/f9139410-0437-4f26-8079-3e57d748c1d2)
There is no type for `ctx` here.
![image](https://github.com/honojs/hono/assets/49100463/11b18c30-5500-4ede-a723-affa12e5020e)

**Comment by linhub15** [comment]
Likely not an issue with Hono, because they published directly to the Deno 3rd party modules.

Check and upgrade Deno version, VSCode version, VSCode Deno extension version and if you have any `tsconfig.json` files that could overwrite default behavior.

![image](https://github.com/honojs/hono/assets/10420994/3ead907c-2f41-4cde-bb4a-65dfa34edd59)

**Comment by itsfuad** [comment]
Still not sure what's the problem. I have no tsconfig files, Updated deno, vscode, extensions. May be other extensions are causing problems. 
Thanks anyway!

**Comment by emonadeo** [comment]
Issue returned upon upgrading to v4. Can we reopen this?

<img width="663" alt="Screenshot 2024-02-21 at 02 01 18" src="https://github.com/honojs/hono/assets/13782948/445ebb62-a885-4991-8184-f0f9697de78d">

<img width="740" alt="Screenshot 2024-02-21 at 02 01 45" src="https://github.com/honojs/hono/assets/13782948/7a7dfb21-b402-4c9c-b802-7058c108558b">

(Same for both Neovim using denols and VSCode using the deno extension)

**Comment by kevinfiol** [comment]
I have this same problem, but on `4.0.5`.

Deno (1.40.5)
VSCode (1.85.1)

**Comment by yusukebe** [comment]
Try to clear the cache:

```
deno cache --reload main.ts
```

**Comment by emonadeo** [comment]
Thanks for the quick reply, that fixed it. I thought I cleared the cache. 🙈

**Comment by kevinfiol** [comment]
Likewise, that was the fix for me. I was not aware of that command. Thank you @yusukebe .
