### ISSUE TITLE
SSG: Certain extensions go wrong.

### ISSUE THREAD

**Issue by watany-dev** [honojs/hono#2028]
### What version of Hono are you using?

4.0.0-rc.1

### What runtime/platform is your app running on?

any

### What steps can reproduce the bug?

toSSG `app.get('/about', (c) => c.text('About Page'))`.
  

### What is the expected behavior?

Output is index.html

### What do you see instead?

The output is indexhtml. This is a bug that occurs only in the determineExtension case.

**Comment by watany-dev** [comment]
I think I have an idea. I'll fix it.

**Comment by yusukebe** [comment]
Fixed by #2029
