### ISSUE TITLE
Review of Hono/SSG names

### ISSUE THREAD

**Issue by watany-dev** [honojs/hono#2043]
### What is the feature you are proposing?

I've named it, hono/ssg, should I think of a cooler name than toSSG or before GA?

**Comment by yusukebe** [comment]
I like the name `hono/ssg` and I like the use of the words `ssg` and `ssr`.

And, I like short names, so I prefer `toSSG()` to names like `renderStaticToFiles()`.

**Comment by watany-dev** [comment]
Thank you. I personally like it, so I'll see what the users want and think about it.
