### ISSUE TITLE
NotFound Handler + Compress does not return body

### ISSUE THREAD

**Issue by sebastianwessel** [honojs/hono#2061]
### What version of Hono are you using?

3.12.6

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

```typescript
import { serve } from '@hono/node-server'
import { Hono } from 'hono'
import { compress } from 'hono/compress'

const app = new Hono()
app.use('*', compress())
app.notFound((c) => c.json({ message: 'error message' }, 400))

serve({
  fetch: app.fetch,
  port: 3000,
})
```

### What is the expected behavior?

Returns error body:
```json
{ "message": "error message" }
```

### What do you see instead?

No body content - browser default error page

### Additional information

Might be an issue in hono + compress or maybe in `@hono/node-server` package, as there were similar issues in regular handlers in older versions

**Comment by ariskemper** [comment]
@sebastianwessel i tested with 3.12.6 and wrote this test, it works as expected

`describe('Not Found JSON', () => {
  const app = new Hono()
  app.use('*', compress())
  app.notFound((c) => {
    return c.json({ message: 'error message' }, 400)
  })

  it('Custom 404 Not Found', async () => {
    const res = await app.request('http://localhost/foo')
    expect(res.status).toBe(400)
    expect(await res.json()).toEqual({ message: 'error message' })
  })
})`

**Comment by ariskemper** [comment]
@sebastianwessel issue was that compress + hono + hono/node-server were not working correctly, when middleware compress is used. I fixed this so when content-encoding is gzip, deflate it needs compressing the body with specific encoding. Hono currently implements gzip and deflates. Tomorrow i will issue PR for this fix.

**Comment by ariskemper** [comment]
@usualoma indeed it solves this bug, but there is another bug, when running with this test:

```
  const app = new Hono()

  app.use('*', compress())

  app.notFound((c) => {
    return c.json({ message: 'error message' }, 400)
  })

  it('custom error message 400 Not Found', async () => {
    const res = await app.request('http://localhost/err', {
      method: 'GET',
      headers: new Headers({ 'Accept-Encoding': 'gzip' }),
    })
    expect(res.status).toBe(400)
    expect(res.headers.get('Content-Encoding')).toEqual('gzip')
    expect(res.headers.get('Content-Length')).toBeNull()
    expect(await res.json()).toEqual({ message: 'error message' })
  })
```
test fails with SyntaxError: Unexpected token  in JSON at position 0

**Comment by usualoma** [comment]
Hi @ariskemper 
Thank you for your comment.

I haven't actually tried it, but I think in this case you need to do the gunzip process yourself. I think you are getting an error because you are not doing that here.

```ts
expect(JSON.parse(zlib.gunzipSync(await res.text())))
```

**Comment by ariskemper** [comment]
@usualoma compression should be done by the server and not, when you receive response from the server.

**Comment by usualoma** [comment]
@ariskemper Thank you. I am happy to have the test added.
