### ISSUE TITLE
`mimes` option for serve-static

### ISSUE THREAD

**Issue by ryuapp** [honojs/hono#2067]
### What is the feature you are proposing?

This feature supports rarely used content-types and great amount of types.
Also, I think to remove unnecessary default MIME to make it lighter in the future.
```ts
// HLS
const mimes = {
  m3u8: 'application/x-mpegURL',
  ts: 'video/mp2t'
}
app.use('/video/*', serveStatic({mimes}))
```

**Comment by yusukebe** [comment]
Hi @ryuapp 

I think this will be a good feature. If you can create the PR, please make it based on the "[v4](https://github.com/honojs/hono/tree/v4)" branch. We are now making all new features in v4.
