### ISSUE TITLE
Handler stuck when awaiting aborted SSE stream

### ISSUE THREAD

**Issue by jonasb** [honojs/hono#2068]
### What version of Hono are you using?

3.12.6

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

Start the following server and run this command `curl http://localhost:8000/sse`. After a few seconds stop the curl command.

```js
import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { streamSSE } from "hono/streaming";

const app = new Hono();

let testId = 0;

app.get("/sse", (c) =>
  streamSSE(c, async (stream) => {
    try {
      const currentTestId = ++testId;
      let aborted = false;
      stream.onAbort(() => {
        aborted = true;
      });

      for (let i = 0; i < 10; i++) {
        console.log(currentTestId, "Iteration", i, aborted ? "(aborted)" : "");
        // If I await the writeSSE like this, it sometimes never returns when the stream is aborted
        await stream.writeSSE({ data: JSON.stringify({ iteration: i }) });
        await stream.sleep(1000);
      }
      console.log("Done");
    } catch (error) {
      console.error("Error", error);
    }
  })
);

const port = 8000;
console.log(`Server is running on port ${port}`);

serve({
  fetch: app.fetch,
  port,
});

```

### What is the expected behavior?

I expect either the `await stream.writeSSE()` to "succeed" or to throw an exception. Now the call never completes after a for writes after the stream is aborted.

### What do you see instead?

The server logging stops after a few writes and the handler never finishes.

Example output:
```
1 Iteration 0 
1 Iteration 1 
1 Iteration 2 
1 Iteration 3 
1 Iteration 4 (aborted)
1 Iteration 5 (aborted)
```
(it doesn't complete all the iterations and Done is not logged)

### Additional information

For my use case I want to continue with all iterations even if the stream is closed. I think I have two workarounds:

1) Skip awaiting `stream.writeSSE()`
2) Skip calling `stream.writeSSE()` when the stream is aborted

Not sure if there are any drawbacks of not awaiting the writes (1). And I'm a bit worried that handler can be stuck if there are issues with writing.

**Comment by yusukebe** [comment]
@watany-dev or @sor4chi Can you see this?

**Comment by watany-dev** [comment]
streamSSE is a function designed to return a stream to the client. Therefore, if the client disconnects, the process within streamSSE will also terminate. If you want to separate the processing process from the stream and not make the processing process dependent on the client connection, you can achieve this separation by using a queue as shown in the example.

```ts
app.get("/sse-queue", (c) => {
  let resultsQueue = [];

  function simulateBackgroundProcess() {
    setInterval(() => {
      const result = { timestamp: new Date().toISOString(), data: 'Some data' };
      console.log(result)
      resultsQueue.push(result);
    }, 1000); 
  }
  simulateBackgroundProcess()

  return streamSSE(c, async (stream) => {
    try {
      while (true) {
        if (resultsQueue.length > 0) {
          const result = resultsQueue.shift();
          await stream.writeSSE({ data: JSON.stringify(result) });
        }
        await stream.sleep(500); 
      }
    } catch (error) {
      console.error("Error", error);
    }
  });
});
```

**Comment by jonasb** [comment]
Thanks, I will try it out!
