### ISSUE TITLE
req.raw.cf types broken in 3.12.4

### ISSUE THREAD

**Issue by berzanskaite** [honojs/hono#2078]
### What version of Hono are you using?

3.12.4

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

```
import { Hono } from 'hono';

const app = new Hono();

type Variables = { userConfig: DataSchema }

app.use('*', async (c, next) => {
        const userConfig = { userCountry: c.req.raw.cf.country };
	c.set('userConfig', userCountry);
        await next();
});

export default app;
```

### What is the expected behavior?

To get user country without type errors

### What do you see instead?

In version 3.12.4, the following TypeScript error is thrown:
`Property 'cf' does not exist on type 'Request'.     ts(2339)`

### Additional information

[This was mentioned before on 3.7.4](https://github.com/honojs/hono/issues/1546), but it was fixed.

**Comment by yusukebe** [comment]
Hi @berzanskaite 

I can't reproduce it. It's not a bug.

<img width="636" alt="Screenshot 2024-01-25 at 5 32 34" src="https://github.com/honojs/hono/assets/10682/09fa3dc5-70b3-490b-9328-b553580c46ba">

Maybe your project setting is wronge. Try to make your project with `npm create hono@latest`.

**Comment by Zerebokep** [comment]
I have the same issue in my project, also `create hono` seems to fail on codesandbox:

```
✔ Which template do you want to use? › cloudflare-workers
/usr/local/share/.config/yarn/global/node_modules/create-hono/bin:10787
          throw new DegitError(`could not find commit hash for ${repo.ref}`, {
```

**Comment by Zerebokep** [comment]
No I mean I have the same issue as @berzanskaite, the create hono thing was just a sidenote as I wanted to try it on a fresh installation.

**Comment by yusukebe** [comment]
Sorry! The `tsconfig.json` is right? Should include `"@cloudflare/workers-types"` to `types`.

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "lib": [
      "ESNext"
    ],
    "types": [
      "@cloudflare/workers-types"
    ],
    "jsx": "react-jsx",
    "jsxImportSource": "hono/jsx"
  },
}
```

**Comment by Zerebokep** [comment]
Yes, the tsconfig is fine, I've also installed the `"@cloudflare/workers-types": "4.20240129.0",`  package and using hono 3.12.12.

**Comment by yusukebe** [comment]
@Zerebokep 

Hmm. Weird. I will let you know if I find out.

**Comment by sunneydev** [comment]
@yusukebe problem exists if you have `webworker` in `lib`
