### ISSUE TITLE
`helper/ssg/index.test.tsx` does not close well

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#2090]
### What version of Hono are you using?

latest https://github.com/honojs/hono/tree/b98e85092474ebc11884fc76ddf27fb29365cea1

### What runtime/platform is your app running on?

CI/main

### What steps can reproduce the bug?

Run tests on CI.

### What is the expected behavior?

Passed.

### What do you see instead?

https://github.com/honojs/hono/actions/runs/7654663888/job/20880284814

**Comment by EdamAme-x** [comment]
thanks.
As additional information I also encountered this within Gitpod.io.

**Comment by EdamAme-x** [comment]
However, there seem to be times when it fails and times when it succeeds.

**Comment by EdamAme-x** [comment]
It also occurred here.
https://github.com/honojs/hono/pull/2087

**Comment by watany-dev** [comment]
@yusukebe @EdamAme-x 
After checking the vitest community, it appears that with the default pools:threads, the test may become unstable and fail.
I was able to confirm errors like this one.
https://github.com/vitest-dev/vitest/pull/5047

As a suggestion, how about putting pool: 'forks' in vitest.config.ts and WATCH to see if this case is resolved? I have tried this locally and so far it has not reoccurred.

**Comment by yusukebe** [comment]
It may be that the problem is not on the test side, but on the code side.

I'm still investigating, but the following changes will stop the hang.

```ts
diff --git a/src/helper/ssg/index.ts b/src/helper/ssg/index.ts
index 721eb9f..b4a0af6 100644
--- a/src/helper/ssg/index.ts
+++ b/src/helper/ssg/index.ts
@@ -140,7 +140,7 @@ export const fetchRoutesContent = async <

     for (const param of forGetInfoURLRequest.ssgParams) {
       const replacedUrlParam = replaceUrlParam(route.path, param)
-      let response = await app.request(replacedUrlParam, forGetInfoURLRequest)
+      let response = await app.request(new URL(replacedUrlParam, baseURL))
       if (afterResponseHook) {
         const maybeResponse = afterResponseHook(response)
         if (!maybeResponse) continue
```

I suspect that performing `fetch` twice on a single request object.

https://github.com/honojs/hono/blob/b98e85092474ebc11884fc76ddf27fb29365cea1/src/helper/ssg/index.ts#L134

**Comment by yusukebe** [comment]
Sending a request twice is not a good implementation, so I am trying to figure out a way to do `ssgParams` but not make the request.

**Comment by yusukebe** [comment]
@watany-dev 

You are right, we should merge #2098 first so that the test does not hang.

**Comment by yusukebe** [comment]
@watany-dev 

Thanks for investigating and the PR. Since the test no longer hangs, we can close this Issue.
