### ISSUE TITLE
Path params are not inferred correctly

### ISSUE THREAD

**Issue by siriscmv** [honojs/hono#2100]
### What version of Hono are you using?

3.12.7

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```ts
import { Hono } from 'hono';
import { hc } from 'hono/client';

const app1 = new Hono().get('/c/:d', async (c) => c.json({ message: c.req.param('d') }));
const app2 = new Hono().route('/a/:b', app1);

const client = hc<typeof app2>('http://localhost:80');
client.a[':b'].c[':d'].$get({ param: { b: '123', d: '456' } });
```

### What is the expected behavior?

Parameter `b` must be allowed

### What do you see instead?

Parameter `b` is not allowed
<img width="925" alt="image" src="https://github.com/honojs/hono/assets/40269790/a0e17d9f-8cc0-45d9-83df-61ef8a825198">

**Comment by yusukebe** [comment]
Hi @siriscmv 

Thanks for raising the issue. This is a bug. I'll fix it later.
