### ISSUE TITLE
"Uncaught TypeError: child.vR is not iterable (cannot read property undefined)" in jsx/dom

### ISSUE THREAD

**Issue by EdamAme-x** [honojs/hono#2106]
### What version of Hono are you using?

v4.0.0-rc.3

### What runtime/platform is your app running on?

Node.js v21

### What steps can reproduce the bug?

It occurs when `react-swc` is selected in **vite** and the `React` application is rewritten with `hono/jsx`.

### What is the expected behavior?

Counter works as usual.

### What do you see instead?

<img width="957" alt="image" src="https://github.com/honojs/hono/assets/121654029/501b9b86-6950-40f9-a7f7-9878c1052203">

### Additional information

```tsx
// main.ts
import App from './App.tsx'
import './index.css'
import { render } from 'hono/jsx/dom'

render(<App />, document.getElementById('root')!)
```

```tsx
// App.tsx
import { useState } from 'hono/jsx'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  const [count, setCount] = useState<number>(0)

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => {
          setCount((count) => count + 1)
        }}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App

```

**Comment by EdamAme-x** [comment]
hi @usualoma 
I honestly don't know if this is a Bug since there is no documentation, what do you think?

**Comment by EdamAme-x** [comment]
CSS and other assets are loaded correctly by the **vite** bundler.

**Comment by EdamAme-x** [comment]
<img width="397" alt="image" src="https://github.com/honojs/hono/assets/121654029/0dd9b7f9-7cf5-4726-80c0-887181da323a">

**Comment by usualoma** [comment]
Hi @EdamAme-x 
Thanks for the report. Can you create a simple project to reproduce?

**Comment by EdamAme-x** [comment]
understood.
Please wait a moment...

**Comment by EdamAme-x** [comment]
hi @jamesarosen 
prepared by
https://stackblitz.com/edit/stackblitz-starters-wl5uss?file=src%2Fmain.tsx

**Comment by usualoma** [comment]
Thank you!

As Obi-Wan says, "Use the jsxImportSource, @EdamAme-x".

```diff
diff --git a/vite.config.ts b/vite.config.ts
index 861b04b..1287205 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -3,5 +3,7 @@ import react from '@vitejs/plugin-react-swc'
 
 // https://vitejs.dev/config/
 export default defineConfig({
-  plugins: [react()],
+  plugins: [react({
+    jsxImportSource: 'hono/jsx'
+  })],
 })
```

**Comment by EdamAme-x** [comment]
thanks @usualoma

**Comment by EdamAme-x** [comment]
@usualoma 
thanks. it works

<img width="959" alt="image" src="https://github.com/honojs/hono/assets/121654029/3327788c-efc9-4053-8ba0-039701002226">
