### ISSUE TITLE
Environment variable documentation not clear 

### ISSUE THREAD

**Issue by jamiehaywood** [honojs/hono#2117]
### What version of Hono are you using?

3.12.8

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

It's not clear in the documentation how to type and access environment variables in Hono.

```ts
type Env = {
  Variables: {
    FOO: string
  }
  Bindings:{
    BAR: string
  }
}

const middleware = createMiddleware<Env>(async (c)=>{
  const foo1 = c.var.FOO // type string inferred
  const foo2 = c.get('FOO') // type string inferred
  const { FOO } = env(c) // typeof FOO is not inferred from `c`, but `BAR` is? 
});
```

A couple of things:
1. I would expect that `FOO` to be inferred from the `c` variable (alongside `BAR`), given the documentation says:
> retrieving environment variables across different runtimes, extending beyond just Cloudflare Workers' Bindings.
2. It's not clear if I should use the `env()` helper, use `c.var` or `c.get()`. Could you explain the differences, and what the best practice should be? I'm happy to raise a PR to update the documentation to this effect.

**Comment by yusukebe** [comment]
Hi @jamiehaywood 

`Bindings` are type definitions for Cloudflare environment variables.

If you want to access Cloudflare's environment variables or Cloudflare-product, write the definitions in `Bindings`. And you can access them with `c.env` or `env(c)`. But, I think you have to use `c.env` because `c.env` is designed for Cloudflare.

```ts
const middleware = createMiddleware<Env>(async (c) => {
  c.env.MY_KV // KVNamespace
  const { MY_KV } = env(c) // MY_KV is KVNamespace
})
```

`env` is a function that allows you to get the environment variables for each runtime with the same function.

`Variables` are type definitions for use with [`c.set`/`c.get`](https://hono.dev/api/context#set-get).

**Comment by jamiehaywood** [comment]
when you say
> ...access Cloudflare's environment variables

are you referring to environment variables set by the user in the `wrangler.toml` file or system environment variables set by Cloudflare? or both?

> env is a function that allows you to get the environment variables for each runtime with the same function.

so how do I declare environment variables so that I can use them in as suggested (`const { FOO } = env(c)`)

**Comment by yusukebe** [comment]
> are you referring to environment variables set by the user in the wrangler.toml file or system environment variables set by Cloudflare? or both?

Only `wrangler.toml` file.

> so how do I declare environment variables so that I can use them in as suggested `(const { FOO } = env(c))`

If you use Wrangler, declare the values in `wrangler.toml`.

**Comment by jamiehaywood** [comment]
I'm sorry, but this still isn't clear.

Deployment platform aside, how do I add types for my environment variables?

**Comment by yusukebe** [comment]
`Bindings`.

The value that can be retrieved with `env(c)` is the value specified in `wrangler.toml` for Cloudflare and in `process.env` for Node.js and Bun.

We can specify the types with `Bindings` for that value.

```ts
type Env = {
  Bindings: {
    BAR: string
  }
}

const middleware = createMiddleware<Env>(async (c) => {
  // foo is process.env.foo on Node.js or Bun
  // foo is the value written in `wrangler.toml` on Cloudflare
  const foo = env(c)
})
```

**Comment by jamiehaywood** [comment]
great thanks! would be happy to raise a PR for the docs if you would like?

**Comment by yusukebe** [comment]
> great thanks!

Good!

> would be happy to raise a PR for the docs if you would like?

Indeed, that was confusing, and it would be helpful if you could write a clear explanation😀

**Comment by kirtirajsinh** [comment]
I'm building a Discord bot and need to add the Environment variable outside of the Function. How can I use it in the production?
