### ISSUE TITLE
`useRequestContext` returns incorrect URL

### ISSUE THREAD

**Issue by bruceharrison1984** [honojs/hono#2118]
### What version of Hono are you using?

3.12.3

### What runtime/platform is your app running on?

CF Workers

### What steps can reproduce the bug?

For a given component that is part of a larger layout:
```tsx
export const NavBar: FC = async () => {
  const ctx = useRequestContext();
  console.log(ctx.req.url);

  return (
    <div
      id="topNav"
      class="navbar sticky top-0 z-50 border-b border-base-300 bg-base-100 shadow-sm"
    >CONTENT</div>
  )
};
```

The URL that is returned is always the same as the first request that was made. For example, if your first request is to `http://localhost:5173/test`, all subsequent requests will have `ctx.req.url` provided from `useRequestContext` as that same value, regardless of if you change routes.

It should be noted that this behavior was observed during local development, and I have not tested it against a deployed CF Pages.

### What is the expected behavior?

I would expect `ctx.req.url` to always reflect the current URL that is being displayed.

### What do you see instead?

The value is always the URL of the first page that was accessed.

**Comment by usualoma** [comment]
Hi @bruceharrison1984 
Thanks for the report.
I can't reproduce it in my environment, can you create a project that can reproduce it?

**Comment by bruceharrison1984** [comment]
@usualoma 

Here's a tiny example. The root issue seems to be, if nested layout components call `useRequestContext`, the URL that is returned will differ from the value that the parent layout component reports.

```tsx
// jsx renderer
export const adminRenderer = jsxRenderer(
  ({ children, title = 'MyApp' }) => {
    return (
      <html lang="en" class="h-full w-full" data-theme="light">
        <head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link href="/static/styles.css" rel="stylesheet" />
          <link href="/static/torch-auth.svg" rel="icon" />
          <title>{title}</title>
        </head>
        <body class="h-full w-full">
          <AdminPageLayout>{children}</AdminPageLayout>     <--- Layout component
        </body>
      </html>
    );
  },
  {
    docType: true,
  }
);
```

```tsx
// layout component
export const AdminPageLayout: FC = async ({ children }) => {
  const ctx = useRequestContext();
  console.log(ctx.req.url);     <--- this always returns the correct value

  return (
    <div id="layoutContainer" class="flex h-full flex-col">
      <NavBar />      <--- this component will also call `useRequestContext`
      <div class="flex h-full w-full flex-row">
        <div
          id="sideBar"
          class="w-max-48 hidden w-48 flex-col space-y-2 border-r border-base-300 bg-base-100 p-4 shadow-md lg:flex lg:min-h-full"
        >
          <button class="btn w-full">
            Button 1
          </button>
          <button class="btn w-full">
            Button 2
          </button>
          <div class="flex-1" />
          <div class="mx-auto">
            <ThemeSwitcher />
          </div>
        </div>
        <main id="content" class="h-full min-h-full w-full flex-1 p-4">
          {children}
        </main>
      </div>
    </div>
  );
};

```
```tsx
export const NavBar: FC = async () => {
  const ctx = useRequestContext();
  console.log(ctx.req.url);    <--- this value will differ from the value the parent component reports

  return (
    <div
      id="topNav"
      class="navbar sticky top-0 z-50 border-b border-base-300 bg-base-100 shadow-sm"
    >
      NAVBAR
    </div>
  );
};
```

**Comment by usualoma** [comment]
@bruceharrison1984 
Thank you!
Give me a minute to check it out.

**Comment by usualoma** [comment]
@bruceharrison1984 

In #2124, we fixed a bug that we believe is related.
Can you please have them check to see if v3.12.9 will fix the problem?
