### ISSUE TITLE
Cannot access `req.param` in middleware

### ISSUE THREAD

**Issue by oladayo21** [honojs/hono#2126]
### What version of Hono are you using?

3.12.9

### What runtime/platform is your app running on?

aws-lambda

### What steps can reproduce the bug?

The `req.param` method returns an empty object `{}`in the middleware but works in the handler.
```javascript
import { Hono } from 'hono';
import { createMiddleware } from 'hono/factory';

const partnerIdMiddleware = createMiddleware(async (c, next) => {
  console.log('in middleware', c.req.param());

  await next();
});

const app = new Hono();
app.use('/purchases/*', partnerIdMiddleware);
app.get('/purchases/:partnerId/activate', (c) => {
  console.log('in handler', c.req.param());

  return c.text(c.req.param('partnerId'));
});

async function test() {
  const res = await app.request('/purchases/PARTNER234/activate');
  console.log(res.status);
}

test();
//logs:
in middleware {}
in handler { partnerId: 'PARTNER234' }
```

### What is the expected behavior?

Expected that the params are also accessible in the middleware

### What do you see instead?

Empty object `{}`

### Additional information

Minimal reproduction here: https://stackblitz.com/edit/stackblitz-starters-yrrbsq?file=index.js

**Comment by yusukebe** [comment]
Hi @oladayo21 

It's not a bug. You can't access `:partnerId` from `partnerIdMiddleware`. It means that only handlers or middleware registered with the route containing the path parameter can access it.

Otherwise, it cannot handle the case that both have the same path parameter named `id`, such as the following:

```ts
const middleware = createMiddleware(async (c, next) => {
  console.log('in middleware', c.req.param())
  await next()
})

const app = new Hono()

app.use('/:id/:id2/comments', middleware)
app.get('/posts/:id/comments', (c) => {
  console.log('in handler', c.req.param())
  return c.text(c.req.param('id'))
})

async function test() {
  const res = await app.request('/posts/123/comments')
}

test()
```

Result:

```ts
in middleware {
  id: "posts",
  id2: "123",
}
in handler {
  id: "123",
}
```

**Comment by oladayo21** [comment]
Alright, thanks for the explanation.

**Comment by JianJroh** [comment]
> Hi [@oladayo21](https://github.com/oladayo21)
> 
> It's not a bug. You can't access `:partnerId` from `partnerIdMiddleware`. It means that only handlers or middleware registered with the route containing the path parameter can access it.
> 
> Otherwise, it cannot handle the case that both have the same path parameter named `id`, such as the following:
> 
> const middleware = createMiddleware(async (c, next) => {
>   console.log('in middleware', c.req.param())
>   await next()
> })
> 
> const app = new Hono()
> 
> app.use('/:id/:id2/comments', middleware)
> app.get('/posts/:id/comments', (c) => {
>   console.log('in handler', c.req.param())
>   return c.text(c.req.param('id'))
> })
> 
> async function test() {
>   const res = await app.request('/posts/123/comments')
> }
> 
> test()
> Result:
> 
> in middleware {
>   id: "posts",
>   id2: "123",
> }
> in handler {
>   id: "123",
> }

```ts
const app = new Hono()
  .basePath('/:id/:id2/comments')
  .use(async (c, next) => {
    const params = c.req.param() // type: {}
    await next()
  })
```
