### ISSUE TITLE
`HonoRequest`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#213]
To make that Response supports the shortcuts such as `c.req.param`, `c.req.query`, and `c.req.header`, we use `declare global`.

```ts
declare global {
  interface Request<ParamKeyType = string> {
    param: (key: ParamKeyType) => string
    query: (key: string) => string
    header: (name: string) => string
  }
}
```

This is good, but not better. We can use these methods in the Hono app, but in other environments, a `Request` object does not have `params`, `query`, and `header`, naturally. 

So, I'm planning to make `HonoRequest` extending `Request` object. It is not necessary to make `HonoResponse`.

**Comment by g-wozniak** [comment]
How to use Hono with [Clerk backend client](https://clerk.com/docs/backend-requests/handling/manual-jwt) then because if `HonoRequest` is truly a wrapper I should not be getting:

```
TS2345: Argument of type HonoRequest<string, unknown> is not assignable to parameter of type Request<unknown, CfProperties<unknown>>
Type HonoRequest<string, unknown> is missing the following properties from type Request<unknown, CfProperties<unknown>>: cache, credentials, destination, headers, and 12 more.
```

right?

**Comment by EdamAme-x** [comment]
@g-wozniak 
How about using `c.req.raw` instead?
HonoRequest should not currently inherit Request.
