### ISSUE TITLE
Drop HONO_COMPONENT feature

### ISSUE THREAD

**Issue by usualoma** [honojs/hono#2133]
### What is the feature you are proposing?

HONO_COMPONENT was an idea to make hydration easier, but is no longer used. It would make more sense to write this process on the build system side. Therefore, I think this code should be removed before v4 is released.

https://github.com/usualoma/hono/blob/61202eda1453da8265c076ae80665ccc3e2e6d21/src/jsx/index.ts#L29-L30

**Comment by yusukebe** [comment]
Hi @usualoma 

Agree. We can remove them.

**Comment by yusukebe** [comment]
Fixed by #2139
