### ISSUE TITLE
Merge main into v4

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#2137]
Hi @usualoma !

Could you merge `main` into `v4`? I can probably do it, but there will be a conflict at JSX things and maybe I will have an accident.

**Comment by usualoma** [comment]
@yusukebe 
OK, I think there is a lot of conflict in "jsx", so I think it is better for me to do it!
If we were to merge https://github.com/honojs/hono/pull/2132 into v4, then after that, I would like to merge the main into v4. What do you think?

**Comment by yusukebe** [comment]
Yeah. That's OK. Now, I'm checking #2132.

**Comment by yusukebe** [comment]
Fixed by #2145
