### ISSUE TITLE
Tests are failed on Node v18.x

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#214]
Throw the errros about `crypto` on Node v18.x

```
 FAIL  src/utils/jwt/jwt.test.ts
  ● JWT › HS256 sign & verify & decode

    TypeError: Value of "this" must be of type SubtleCrypto

      73 |   alg: AlgorithmTypes = AlgorithmTypes.HS256
      74 | ): Promise<ArrayBuffer> => {
    > 75 |   const cryptoKey = await crypto.subtle.importKey(
         |                                         ^
      76 |     CryptoKeyFormat.RAW,
      77 |     utf8ToUint8Array(secret),
      78 |     param(alg),

      at signing (src/utils/jwt/jwt.ts:75:41)
      at Object.sign (src/utils/jwt/jwt.ts:95:64)
      at Object.<anonymous> (src/utils/jwt/jwt.test.ts:74:17)
...
```

**Comment by metrue** [comment]
This root cause it there're changes in  type chacking in webcrypto. someone already did a partial [fix](https://github.com/cloudflare/miniflare/pull/216)
But this issue may need this MR to be merged and release https://github.com/cloudflare/miniflare/pull/259

**Comment by robinlahtinen** [comment]
[cloudflare/miniflare#259](https://github.com/cloudflare/miniflare/pull/259) works and fixed the issue for my use case.

**Comment by metrue** [comment]
@robinlahtinen Great, let's wait for it to be merged and released.
