### ISSUE TITLE
Regression: type error when using `param` validation and `.route`

### ISSUE THREAD

**Issue by MonsterDeveloper** [honojs/hono#2148]
### What version of Hono are you using?

3.12.10

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

[Link to TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAIgAt0JiBuAKFElkTgC8A1AQwBtgATdmaNjwEixAALkMAemYQeAWgBuXXv2jU64aPCTMh+QiVk8NNAMboAzvHZgwAJQgBXGAFMocALxw0rgO4oFAAUAJS0FmjWcJZOAEaOLu5ePv6BGKG05lbwBImWyTHxzm5QAHQA5q4wQcRSAFy8xAA0LBzcfAJQNWDsUOwgzSylELEAVq5m1Ug0cHC8dUPWUMBo5aFNNFghIS3slgCeaGZwEW4AHvCeAHwn6OcwpaOW6DWkwMTbmRFRtg7FrvlvL8EiVSrk3DUpM8QFU3qtBuCAWEaCj6NomKRjjgDKJJBApGZuK40DBTN94ITgMTLnBMQAeGD7MCuCC4ODA-6WK41D5fIkk0rQ2ErcoAbWIDRMAF1SgASSpTGZwHp9EALBBK2bzEhLEXEJVYTZhIA)

When using `.route` method to attach routes and validators for `param`, `hc` infers params type as `never`:

![CleanShot 2024-02-04 at 19 08 01@2x](https://github.com/honojs/hono/assets/16190582/92fec28c-2f34-4d1e-aa28-c3a60361ec2c)

### What is the expected behavior?

The input type for client should be `{ id: string }`, and not `never`

### Additional information

This is a regression introduced in [`v3.12.9`](https://github.com/honojs/hono/releases/tag/v3.12.9) (confirmed by downgrading to `v3.12.8`). Probably PR to blame is #2122.

This type error only occurs when using `.route` method.

**Comment by yusukebe** [comment]
@MonsterDeveloper 

Thanks. I'm now fixing it.

**Comment by MonsterDeveloper** [comment]
@yusukebe thanks! Params seem to be working fine now, but now `json` is the one causing troubles:
![CleanShot 2024-02-05 at 17 38 19@2x](https://github.com/honojs/hono/assets/16190582/b8a62c12-6d65-4ec5-89c2-2dc030d3b386)

[Link to Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAIgAt0JiBuAKFElkTgC8A1AQwBtgATdmaNjwEixAALkMAemYQeAWgBuXXv2jU64aPCTMh+QiVk8NNAMboAzvHZgwAJQgBXGAFMocALxw0rgO4oFAAUAJS0FmjWcJZOAEaOLu5ePv6BGKG05lbwBImWyTHxzm5QAHSQ1kHEUgBcvMQANCwc3HwCUFVg7FDsII0spRCxAFauZjBBSDRwcLw1A9ZQwGgA5qENNFghIU1sKm3QVcOW6P3MgyNjEwjTcKSunJwQ8+fcJVxVftCcJjub2012JYAJ5oMxwCJuAAe8E8AD4IehoTBSsd0FVSMBiNtMhEorYHMVXPlvASEiVSrk3FUpCcQK4YJjVv0qcSwjQOfRtExSOCcAZRJIIFIzNxXGgYKY8fBRcBxbC7mYADwwYFgVwQXBwMlEyxwqrY3FiiWlOkMpkrADaxDqJgAuqUACQVa63Lo9EDzG4zGZzEiLZYrYi3LAbGZotBe24ze6PZ4kL5QH7BmZYf5UIA)

I can open a new issue if you want.

**Comment by yusukebe** [comment]
@MonsterDeveloper 

Thanks for reporting. This will be fixed by #2154.
