### ISSUE TITLE
Hono Client AppType broken after update 

### ISSUE THREAD

**Issue by nvsd** [honojs/hono#2155]
### What version of Hono are you using?

3.12.11

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

Simply importing the result of `export type AppType = typeof app;` from the server project in a client project should trigger the error

### What is the expected behavior?

Fully typed hono client

### What do you see instead?

Type 'Hono<Env, MergeSchemaPath<ToSchema<"get", "/:id", { param: { id: string; }; }, { createdAt: string; id: number; position: number; userId: string; type: string; workoutId: number; } | undefined> & ToSchema<...> & ToSchema<...> & ToSchema<...> & ToSchema<...>, "/activities"> & ... 5 more ... & MergeSchemaPath<...>, "/">' does not satisfy the constraint 'Hono<any, any, any>'.
  Property '#private' in type 'Hono' refers to a different member that cannot be accessed from within type 'Hono'.

<img width="1449" alt="image" src="https://github.com/honojs/hono/assets/7391612/a59f7426-edab-44d3-8954-742f25a3ff5a">

**Comment by nvsd** [comment]
Hmm looks like nuking node_modules and reinstalling fixed the issue  for now

**Comment by alexfaber2011** [comment]
@chrisyalamov I'm experiencing the same exact issue as you.

**Comment by michael-harvey** [comment]
Make sure the installed hono version on the frontend is the same as that on the server. Hope this helps ✌🏼
