### ISSUE TITLE
Type Inference Not Working with `@hono/zod-openapi` in RPC Mode

### ISSUE THREAD

**Issue by poteboy** [honojs/hono#2158]
### What version of Hono are you using?

^3.12.9

### What runtime/platform is your app running on?

Node.js(Next.js)

### What steps can reproduce the bug?

1. Define a route using `@hono/zod-openapi` that includes path parameters, as shown in the code snippet below.
2. Attempt to use the defined route with Hono's RPC mode client.
3. Observe that the type completion for `param` in the `$get` method does not work as expected, resulting in a `never` type being inferred.

```ts
// Routing Definition
const app = new OpenAPIHono().basePath("/users").openapi(
  createRoute({
    method: "get",
    path: "/:id/exist",
    responses: {
      200: {
        content: {
          "application/json": {
            schema: z.boolean(),
          },
        },
      },
    },
    request: {
      params: z.object({
        id: z.string(),
      }),
    },
  }),
  async (c) => {
    const id = c.req.param("id");
    const userExists = await new UserServerService()
      .getUserById(id)
      .then((user) => !!user)
      .catch(() => false);
    return c.json(userExists);
  },
);

type AppType = typeof app;

// Use in RPC mode on the client
const client = hc<AppType>('/').users[":id"].exist.$get({
  param: { id: "1" } as never, // The type does not work here and becomes `param: never`
});
```

### What is the expected behavior?

The type of the argument for `$get` should be inferred to require `id` in `param`.

### What do you see instead?

When executing `hc<AppType>('/').users[":id"].exist.$get`, the type of the argument for `$get` is inferred as `param: never`, indicating that the expected type completion is not functioning.

### Additional information

When using `@hono/zod-openapi` with Hono's RPC mode, the type inference for param does not seem to work as expected. This issue does not occur with standard Hono routing; it is specific to when `@hono/zod-openapi` is utilized.

**Comment by yusukebe** [comment]
Hello @poteboy !

I've tried it, but I can't reproduce it. [The playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeTAUwHYEEAKBJACQgwgBo4BjKNAQxjQCUIBXeuAXzgDMoIQ4A5AAEAFsQgB6AF4QAJgFoI6DDTDABAKFCRYiOCIoduvfgLEkJFADbBMMTdujwkUozz6CZszRorEAzvCqYHAAvHAYaADuKMq4hOIAFACUAHQARjT+aDh0IokCEszZUP4CaUqYqsCJGnCU1HSMLPSJCHX1cCBoMGKyAFyCAOY9AqQd9WB5g4X9wLISaAAewIFjE3DU-pAY2f6D7Z2dAEwADKcHG0d+GPS3l0ePgsE2FHTAxBIAVv7EAg9PR7+CgiNAgGiDKQZCAQKy0DApK6PdhI+rscaAuCyNDAqDAMAwD4YGZcGGaJ4oo7ojbUACOzBxMABRymUBoIH2cChEHSXzQFBgbVRcHmkNSgTxGCGiIpyQ2lI4yQxcCyAE8MIZEhRkmEAHyIDY3QIi2RhSipOmpVnsgrzco0nrMKAYc0-YiJGBQBlytEaOUaGCq9BwLBgMAAFSDaDNgfQEC4KrDGg0EgkcAAqtkRS6GDgAMJdOTR4hwXrR6y2W6+ALwCt2M0GAA8oYjUd1BQk9uru3gWzNNCiNGAtZsdgA2v87QBdVLLVYwVIAEhGgsOcGtIGZJpJZI6KPY-qN8FkdBo-cHw82ONSboRcqAA) works fine.

Certainly there have been recent changes about that type, but I think 3.12.9 will work as well. You could try checking your settings again.

**Comment by poteboy** [comment]
Thank you for the quick response, @yusukebe .

I copy & pasted the exact code from [The playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeTAUwHYEEAKBJACQgwgBo4BjKNAQxjQCUIBXeuAXzgDMoIQ4A5AAEAFsQgB6AF4QAJgFoI6DDTDABAKFCRYiOCIoduvfgLEkJFADbBMMTdujwkUozz6CZszRorEAzvCqYHAAvHAYaADuKMq4hOIAFACUAHQARjT+aDh0IokCEszZUP4CaUqYqsCJGnCU1HSMLPSJCHX1cCBoMGKyAFyCAOY9AqQd9WB5g4X9wLISaAAewIFjE3DU-pAY2f6D7Z2dAEwADKcHG0d+GPS3l0ePgsE2FHTAxBIAVv7EAg9PR7+CgiNAgGiDKQZCAQKy0DApK6PdhI+rscaAuCyNDAqDAMAwD4YGZcGGaJ4oo7ojbUACOzBxMABRymUBoIH2cChEHSXzQFBgbVRcHmkNSgTxGCGiIpyQ2lI4yQxcCyAE8MIZEhRkmEAHyIDY3QIi2RhSipOmpVnsgrzco0nrMKAYc0-YiJGBQBlytEaOUaGCq9BwLBgMAAFSDaDNgfQEC4KrDGg0EgkcAAqtkRS6GDgAMJdOTR4hwXrR6y2W6+ALwCt2M0GAA8oYjUd1BQk9uru3gWzNNCiNGAtZsdgA2v87QBdVLLVYwVIAEhGgsOcGtIGZJpJZI6KPY-qN8FkdBo-cHw82ONSboRcqAA) on my project and I still encounter this error:

```ts
(property) ":id": {
    exist: ClientRequest<{
        $get: {
            input: {
                param: never;
            };
            output: boolean;
        };
    }>;
}
```
It seems like the issue might be on my side as you suggested. I will close this issue for now and will reopen it if I find the root cause. Thank you for your assistance!
