### ISSUE TITLE
Add a "cause" option to HTTPException

### ISSUE THREAD

**Issue by Karibash** [honojs/hono#2170]
### What is the feature you are proposing?

The JavaScript Error class can be passed the [cause option](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause).
This is a property that indicates the cause of the error and is used to catch the error and construct the error including the original error when it is thrown again.

The [HTTPException class](https://github.com/honojs/hono/blob/main/src/http-exception.ts) defined by Hono does not have a cause property.
This makes it impossible for monitoring tools such as Sentry to determine the detailed cause of the error when throwing an HTTPException error.
It would be easier to debug if the cause property could be passed to HTTPException as well.

**Comment by Karibash** [comment]
@yusukebe 
What do you think about this?

**Comment by yusukebe** [comment]
Hi @Karibash 

Sounds good!

To enable `cause`, we have to update the `compilerOptions.target` to such as `ES2022` or `ESNext` in `tsconfig.json`, but I think it's good.

https://github.com/honojs/hono/blob/06cb43aa8e256977ccc497e091087a4330060c9d/tsconfig.json#L3

Can you create the PR to support it?

**Comment by Karibash** [comment]
@yusukebe 
Thanks for the reply.
Sounds easy enough, I'll give it a try.
I think I can get a PR out by the end of tomorrow.

**Comment by yusukebe** [comment]
This can be closed. Thanks!
