### ISSUE TITLE
Allow sending `retry` for SSE connection

### ISSUE THREAD

**Issue by etcd** [honojs/hono#2172]
### What is the feature you are proposing?

Adding a `retry` field to the SSEMessage interface, which Hono has defined as the following:

```
export interface SSEMessage {
    data: string;
    event?: string;
    id?: string;
}
```

This interface is incomplete, as there is also [a `retry` field](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#retry) (also, here's a [link to the actual standard](https://html.spec.whatwg.org/multipage/server-sent-events.html#event-stream-interpretation)).

**Comment by watany-dev** [comment]
You are right, let's address `retry` as well!
