### ISSUE TITLE
Can't Run Cloudflare Pages Template On Fresh Initialization on Windows

### ISSUE THREAD

**Issue by Luzefiru** [honojs/hono#2182]
### What version of Hono are you using?

4.0

### What runtime/platform is your app running on?

Cloudflare Pages

### What steps can reproduce the bug?

```bash
$ npm create hono@latest # create a new cloudflare-pages template hono app

create-hono version 0.3.2
√ Target directory ... test
√ Which template do you want to use? » cloudflare-pages
cloned honojs/starter#main to ${pwd}/test

$ cd test # navigate to the folder
$ npm i
$ npm run build # create the `/dist/` directory for preview
$ npm run preview
```

### What is the expected behavior?

The worker should work locally and it should run successfully and let me `GET http://127.0.0.1:8788` to return a `<h1>Hello!</h1>`.

### What do you see instead?

An error stating `service core:user:worker: Uncaught Error: Can't import modules from ['/srcindex.tsx','/appserver.ts']`.

Here are my logs:
````bash
$ npm run preview

> preview
> wrangler pages dev dist

▲ [WARNING] No compatibility_date was specified. Using today's date: 2024-02-09.

  Pass it in your terminal:
  ```
  --compatibility-date=2024-02-09
  ```
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.


✨ Compiled Worker successfully
 ⛅️ wrangler 3.28.1
-------------------
⎔ Starting local server...
[wrangler:inf] Ready on http://127.0.0.1:8788
X [ERROR] service core:user:worker: Uncaught Error: Can't import modules from ['/srcindex.tsx','/appserver.ts']

    at null.<anonymous> (bundledWorker-0.49025778765513106.js:904:9)
````

### Additional information

I was originally testing it on Windows, but after switching to my Ubuntu WSL development environment, deleting `node_modules` and doing `npm i` again, I managed to make it work.

Perhaps there is a compatibility issue with Windows machines, for anyone getting the same error as me, try initializing the project on a Linux-based environment (delete `node_modules` and reinstall) and see if the issue still persists.

**Comment by yusukebe** [comment]
Hi @Luzefiru 

This is a bug of `@hono/vite-cloudflare-pages`. I've fixed it. Please try `npm create hono@latest` again.

**Comment by Luzefiru** [comment]
Works great now @yusukebe. Thanks!
