### ISSUE TITLE
SSG: Generate 404 page

### ISSUE THREAD

**Issue by taisan11** [honojs/hono#2189]
### What is the feature you are proposing?

Generate app.notFound page with toSSG() or vite-ssg.

**Comment by EdamAme-x** [comment]
If you use ssg, you would use a deployment service such as **netlify**. 
Those services can define it with a special file name such as 404.html as etc.
You just generate it as usual.
And if it is a hybrid, you can still run it as usual (.notFound).

**Comment by taisan11** [comment]
OK!!
Thanks.
