### ISSUE TITLE
setCookie didnt work with trpc middleware 

### ISSUE THREAD

**Issue by xmnlz** [honojs/hono#2199]
### What version of Hono are you using?

^4.0.1

### What runtime/platform is your app running on?

node.js v20.3.1

### What steps can reproduce the bug?

# I'm using trpc with hono, trying to set cookie in trpc query by using `setCookie` 
but it seems like `setCookie` didn't work properly, the `set-cookie` filed don't even exits in request 

```ts
export const helloWorld = publicProcedure.query(async ({ ctx }) => {
 // request cookie header didn't even exists
  setCookie(ctx.holoCtx, 'some_var', 'test');

  return 'Hello world!';
});
```
### Trpc middleware
```ts

// trpc.ts
export const createContext = (opts: FetchCreateContextFnOptions, holoCtx: Context) => ({
  ...opts,
  holoCtx,
  uid: '',
});

// main.ts
app.use('/trpc/*', (c) => {
  return fetchRequestHandler({
    req: c.req.raw,
    router: appRouter,
    endpoint: '/trpc',
    createContext: (opts) => createContext(opts, c),
    onError(opts) {
      const { error, type, path, input, ctx, req } = opts;
      if (error.code === 'INTERNAL_SERVER_ERROR') {
        console.log('Internal server error');
      }
      console.error('Error:', error);
    },
  });
});
```

### What do you see instead?

`set-cookie` didn't even exists on request headers

### Additional information

# I trayed to change `setCookie` 

## from 
```ts
const setCookie = (c, name, value, opt) => {
  const cookie = (0, import_cookie.serialize)(name, value, { path: "/", ...opt });
  c.header("set-cookie", cookie, { append: true });
};
```

## to 
```ts
const setCookie = (c, name, value, opt) => {
  const cookie = (0, import_cookie.serialize)(name, value, { path: "/", ...opt });
  c.res.headers.set("set-cookie", cookie)
  // c.header("set-cookie", cookie, { append: true });
};
```

and after this change `setCookie` start working, i have some guesses that it's duo to context headers method implementation

**Comment by xmnlz** [comment]
# I investigate further and wrote a little test for `c.header()`


![image](https://github.com/honojs/hono/assets/63904972/dd5354b0-e1b0-40a9-b22c-c6d8f4617fd0)

## Source
```ts
describe('c.header() with middleware', () => {
  const app = new Hono()

  app.use('*', async (c, next) => {
    c.header('X-Foo', 'Bar')

    await next()
  })

  app.get('/hello', async () => {
    return new Response('hello', {
      status: 200,
      statusText: 'Hono is OK',
    })
  })

  it('GET http://localhost/hello with right middleware header value', async () => {
    const res = await app.request('http://localhost/hello')
    expect(res).not.toBeNull()
    expect(res.status).toBe(200)
    expect(res.headers.get('X-Foo')).toBe('Bar')
    expect(await res.text()).toBe('hello')
  })
})
```

**Comment by yusukebe** [comment]
Hi @xmnlz 

It may not be a bug of Hono's core.

The `res.headers.get('X-Foo')` should be `null`. If it returns the `Response` object with `new Response`, Hono does not add the headers specified by a user. You have to use the Context object to make it work with expected behavior.

```ts
app.get('/hello', async () => {
  return c.body('hello', {
    status: 200,
    statusText: 'Hono is OK',
  })
})
```

To resolve your problem, I think you can write like this:

```ts
app.use('/trpc/*', (c) => {
  c.res = fetchRequestHandler({ //... });
});
```

If your problem is not resolved, please share the project to reproduce it.

**Comment by xmnlz** [comment]
> Hi @xmnlz
> 
> It may not be a bug of Hono's core.
> 
> The `res.headers.get('X-Foo')` should be `null`. If it returns the `Response` object with `new Response`, Hono does not add the headers specified by a user. You have to use the Context object to make it work with expected behavior.
> 
> ```ts
> app.get('/hello', async () => {
>   return c.body('hello', {
>     status: 200,
>     statusText: 'Hono is OK',
>   })
> })
> ```
> 
> To resolve your problem, I think you can write like this:
> 
> ```ts
> app.use('/trpc/*', (c) => {
>   c.res = fetchRequestHandler({ //... });
> });
> ```
> 
> If your problem is not resolved, please share the project to reproduce it.

I changed trpc middleware to 

```ts
app.use('/trpc/*', async (c) => {
  const res = await fetchRequestHandler({
    req: c.req.raw,
    router: appRouter,
    endpoint: '/trpc',
    createContext: (opts) => createContext(opts, c),
    onError(opts) {
      const { error, type, path, input, ctx, req } = opts;
      if (error.code === 'INTERNAL_SERVER_ERROR') {
        console.log('Internal server error');
      }
      console.error('Error:', error);
    },
  });

  c.res = res;

  return res;
});
```
and i trayed thee same query
```ts
export const helloWorld = publicProcedure.query(async ({ ctx }) => {
 // request cookie header didn't even exists
  setCookie(ctx.holoCtx, 'some_var', 'test');

  return 'Hello world!';
});
```  
but i still don't have expected `set-cookie` in request header

**Comment by yusukebe** [comment]
@xmnlz 

Thanks. Could you share the project to reproduce it?

**Comment by xmnlz** [comment]
> @xmnlz
> 
> Thanks. Could you share the project to reproduce it?

I created temporary repo for repro https://github.com/xmnlz/hono-repro-2199/tree/master

**Comment by yusukebe** [comment]
@xmnlz 

This is not a bug on the Hono side, and maybe your usage is wrong.

You should not modify the header values in `publicProcedure.query()`. So, if you want to add cookies, add a response header to the Response object returned from `fetchRequestHandler`.

```ts
app.use('/trpc/*', async (c) => {
  const res = await fetchRequestHandler({
    req: c.req.raw,
    router: appRouter,
    endpoint: '/trpc',
    createContext: (opts) => createContext(opts, c),
    onError(opts) {
      const { error, type, path, input, ctx, req } = opts
      if (error.code === 'INTERNAL_SERVER_ERROR') {
        console.log('Internal server error')
      }
      console.error('Error:', error)
    }
  })
  c.res = res
  setCookie(c, 'some_var', 'test')
})
```

**Comment by xmnlz** [comment]
@yusukebe 

Is there any way to set cookie in query, for example i have a login route and i want a cookie with access token, what solution i should use for that particular scenario?

**Comment by yusukebe** [comment]
@xmnlz 

Hmm. It may be a tRPC matter, and I'm not so familiar with tRPC. I can't answer it.

**Comment by xmnlz** [comment]
Giant Thanks, I'll close the issue
