### ISSUE TITLE
Get response [object Promise] in async await jsxRenderer

### ISSUE THREAD

**Issue by Code-Hex** [honojs/hono#2207]
### What version of Hono are you using?

4.0.1

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

This code will render `[object Promise]`

```ts
app
    .use(
      '/test',
      jsxRenderer(async ({ children }) => { // w/o async, await, will be successful
        return await (<div>{children}</div>);
      }),
    )
    .get('/test', async (c) => {
      return await c.render(<span>Hello</span>);
    });
```

### What is the expected behavior?

Get response like below:
```
<div><span>Hello</span></div>
```

### What do you see instead?

[object Promise]

**Comment by yusukebe** [comment]
Hi @Code-Hex !

This was fixed by #2211. I'll release a patch release, including this change, later!
