### ISSUE TITLE
Chain `c.status()`

### ISSUE THREAD

**Issue by missinglink** [honojs/hono#2212]
### What is the feature you are proposing?

Apologies if this has been discussed before, I searched GH and couldn't find a corresponding issue.

Would you consider returning `this` from `c.status()` so that it could be chained:

```js
c.status(500)
return c.json({ error: 'error message' })
```

vs.

```js
c.status(500).json({ error: 'error message' })
```

https://github.com/honojs/hono/blob/4c9d50f212ab0330415491e0cf5f42c77ceac29b/src/context.ts#L293-L296

**Comment by Code-Hex** [comment]
@missinglink You can write code such as

```ts
c.json({ error: 'error message' }, 500)
```

**Comment by missinglink** [comment]
Thank you!
