### ISSUE TITLE
Re-export `Context` type from `./types`

### ISSUE THREAD

**Issue by aldy505** [honojs/hono#2214]
### What is the feature you are proposing?

Hello! I like Hono APIs for building... APIs. One nitpick is that while I've read the best practice on the docs page to not create a controller-like handler, for some reason I can't avoid creating one because of some reasons. I'm using Typescript, so I would need something like:

```ts
import { Hono } from "hono";
import type { Context } from "hono/types";

const app = new Hono();

function handler(c: Context): Promise<Response> {
  return c.text("Hello world");
}

app.get("/", (c) => handler(c));
```

I saw the code that exports the types to the end-users here:
https://github.com/honojs/hono/blob/4c9d50f212ab0330415491e0cf5f42c77ceac29b/package.json#L42-L46

The `Context` type is imported here:
https://github.com/honojs/hono/blob/4c9d50f212ab0330415491e0cf5f42c77ceac29b/src/types.ts#L4

Yet it never got re-exported. The closest thing that I can use is the `Handler` type, yet that is not what I'm aiming for, it's not compatible with my current code. 
https://github.com/honojs/hono/blob/4c9d50f212ab0330415491e0cf5f42c77ceac29b/src/types.ts#L52-L57

So...
1. Can we have  `Context` type re-exported?
2. If the answer is "no", is there any specific reason on why not?

**Comment by yusukebe** [comment]
Hi @aldy505 !

Is it not enough to import from `hono`?

```ts
import type { Context } from 'hono'
```

The reason for not exporting from `hono/types` is that you can just use `Context`, which is exported from `hono`.

**Comment by aldy505** [comment]
Hi. Last night I got an import error saying `Context` is not a named export from "hono". But I've read the source (saw `Context` is exported) and it might be a problem on my end. I'll check again soon.

**Comment by aldy505** [comment]
Ah it turns out I used the wrong import. I used
```ts
import { Context } from "hono";
```
Instead of
```ts
import type { Context } from "hono";
```

Thanks!
