### ISSUE TITLE
Improvement of extension determination

### ISSUE THREAD

**Issue by usualoma** [honojs/hono#2239]
### What is the feature you are proposing?

With #2236, the presence or absence of extensions is now automatically determined, but I think this behavior should be improved.

### Test

Currently, adding the following test succeeds, but is this the expected result?

```diff
diff --git a/src/helper/ssg/index.test.tsx b/src/helper/ssg/index.test.tsx
index dde90e5a..07726d04 100644
--- a/src/helper/ssg/index.test.tsx
+++ b/src/helper/ssg/index.test.tsx
@@ -297,6 +297,10 @@ describe('saveContentToFiles function', () => {
       ['/about/', { content: 'About Page', mimeType: 'text/html' }],
       ['/bravo/index.html', { content: 'About Page', mimeType: 'text/html' }],
       ['/bravo/index.tar.gz', { content: 'About Page', mimeType: 'application/gzip' }],
+      ['/bravo/release-4.0.0', { content: 'Release 4.0.0', mimeType: 'text/html' }],
+      ['/bravo/2024.02.18-sweet-memories', { content: 'Sweet Memories', mimeType: 'text/html' }],
+      ['/bravo/deep.dive.to.html', { content: 'Deep Dive To HTML', mimeType: 'text/html' }],
+      ['/bravo/alert.js', { content: 'alert("evil content")', mimeType: 'text/html' }],
       ['/bravo.text/index.html', { content: 'About Page', mimeType: 'text/html' }],
       ['/bravo.text/', { content: 'Bravo Page', mimeType: 'text/html' }],
     ])
@@ -312,6 +316,10 @@ describe('saveContentToFiles function', () => {
     expect(fsMock.writeFile).toHaveBeenCalledWith('static/bravo/index.tar.gz', 'About Page')
     expect(fsMock.writeFile).toHaveBeenCalledWith('static/bravo.text/index.html', 'About Page')
     expect(fsMock.writeFile).toHaveBeenCalledWith('static/bravo.text/index.html', 'Bravo Page')
+    expect(fsMock.writeFile).toHaveBeenCalledWith('static/bravo/release-4.0.0', 'Release 4.0.0')
+    expect(fsMock.writeFile).toHaveBeenCalledWith('static/bravo/deep.dive.to.html', 'Deep Dive To HTML')
+    expect(fsMock.writeFile).toHaveBeenCalledWith('static/bravo/2024.02.18-sweet-memories', 'Sweet Memories')
+    expect(fsMock.writeFile).toHaveBeenCalledWith('static/bravo/alert.js', 'alert("evil content")')
   })
 
   it('should correctly create directories if they do not exist', async () => {

```

#### Consideration of additional settings

To begin with, is this something that should be inferred from the file path, as is the current implementation? It seems to me that there are very few cases where "only a part of the site we are trying to export has a URL extension, and we want that extension to be exported as it is.

I think it is usually the scope of the "entire site" or "entire routing" that determines whether the URL already contains the extension or not.

```ts
toSSG(app, fs, {
  guessExtension: true,
})
```

or

```ts
app.get(
  '/shops/:id',
  ssgConfig(() => ({ // new method
    guessExtension: false,
    params: [ ... ], // works the same way as ssgParams
  })),
  async (c) => { ... }
)
```

#### Consideration of conditions

If we do not want to add the settings I have indicated above, but want the decision to be automatic, as in the current implementation, I think we need to make the conditions a bit stricter. I think it is very problematic for this to be exported in .js.

```
['/bravo/alert.js', { content: 'alert("evil content")', mimeType: 'text/html' }],
```

If an URL has an extension that does not match the mime type, I think the mime type should be given priority for SSG. The reason is that in many cases, when the exported file is served from a web server, the mime type is guessed from the file extension, so it will differ from the mime type specified when output from the app.

As an aside. 
This is the same problem as https://github.com/honojs/hono/issues/2180. In #2180, "app returns 404, but when the exported file is served, it is 200".

**Comment by watany-dev** [comment]
@usualoma 

## Pattern
1. Path without Extension:
Based on the MIME type, an appropriate file extension is added, and the file is generated. This ensures that files are saved in a format that web servers can correctly interpret and serve.

2. Path with Extension, Same as MIME Type:
If the extension already included in the URL matches the MIME type, that extension is used as is to generate the file. This approach respects the original extension specified in the route, ensuring consistency between the route definition and the generated file.

3. Path with Extension, Different from MIME Type:
When the extension in the URL does not match the MIME type, a new file name with an appropriate extension based on the MIME type is generated. This helps in avoiding content type mismatches when the file is served by a web server.

4. Path with Extension, Different from MIME Type, but Using the Path's Extension:
In certain cases, even if the extension in the URL does not match the MIME type, the extension included in the path may be prioritized and used. This option allows for flexibility in handling special cases where the extension is critical for the file's usage or interpretation.

---
In this case, scenarios 1 and 3 have been achieved as of Hono v4.0.0. Regarding scenario 2, it was insufficient in the last commit, but it can be re-implemented. For those who want to use extensions like .html.html, they can simply specify it explicitly in the Route :) As for scenario 4, as you mentioned, we can add an option to prioritize the extension specified in the Route. I'm still contemplating whether to implement this up to the middleware level.

**Comment by yusukebe** [comment]
@usualoma @watany-dev 

Can we close this since #2243 was merged?

**Comment by usualoma** [comment]
👍 
> Can we close this since https://github.com/honojs/hono/pull/2243 was merged?

**Comment by yusukebe** [comment]
Okay! Closing.
