### ISSUE TITLE
On incorrect Content-Type, Validator should inform client instead of throwing 500.

### ISSUE THREAD

**Issue by Leonss23** [honojs/hono#2266]
### What is the feature you are proposing?

If I send a request with an empty body or incorrect Content-Type to a route that validates some JSON schema, it should inform the client of the expected content type and data schema instead of throwing HTTPException and sending 500.

**Comment by yusukebe** [comment]
Hi @Leonss23 

This is related to #1441. It used to be that way, but after some discussion, we now handle errors with `app.onError`.
