### ISSUE TITLE
Returning context.notFound() on a route breaks client typing

### ISSUE THREAD

**Issue by zolboo-gtn** [honojs/hono#2280]
### What version of Hono are you using?

4.0.6

### What runtime/platform is your app running on?

nextjs route/handler

### What steps can reproduce the bug?

app.ts
```
export const app = new Hono()
  .basePath("/api")
  .get("/users/:id", async (context) => {
    const { id } = context.req.param();

    const user = await getUserById(id);
    if (!user) {
      // commenting out this line fixes the issue
      return context.notFound();
    }

    return context.json(user);
  });
export type AppType = typeof app
```
client.ts
`export const client = hc<AppType>("http://localhost:3000").api;`

page.ts
```
const response = await client.users[":id"].$get({
  param: { id },
});
// user type is inferred as never
const user = await response.json();
```

### What is the expected behavior?

response type is inferred correctly with context.notFound().

### What do you see instead?

response type is inferred as never.

**Comment by yusukebe** [comment]
This is a known issue, not a bug. Please use `c.json` instead of `c.notFound`.

**Comment by alex-grover** [comment]
can this be documented, if it's a known issue? it's not mentioned on the RPC page or the `notFound` reference in the docs.

**Comment by yusukebe** [comment]
Hi @alex-grover 

Adding this to the docs is a good idea. I've added it: https://github.com/honojs/website/pull/515 Thanks!

**Comment by ptts** [comment]
For anyone finding this, as a potential workaround, you can do this:

```ts
function handleNotFound(c: Context) {
  return c.json({ ok: false, error: "not_found" } as const, 404);
}

type Env = {
  Variables: {
    notFound: typeof handleNotFound;
  };
};

const app = new Hono<Env>();

app.use((c, next) => {
  c.set("notFound", handleNotFound);
  return next();
});

const route = app.get("/", (c) => {
  // ❌ Does not work - breaks all types in the client for the given route
  // return c.notFound();

  // ✅ Correctly inferred in the client
  return c.var.notFound(c);
});

const client = hc<typeof route>("");
const data = await (await client.index.$get()).json();
//      ^? const data: { readonly ok: false; readonly error: "not_found"; }

```
