### ISSUE TITLE
Vite HMR fails for client components

### ISSUE THREAD

**Issue by emirotin** [honojs/hono#2286]
### What version of Hono are you using?

4.0.8

### What runtime/platform is your app running on?

dev

### What steps can reproduce the bug?

Refer to this repository: https://github.com/emirotin/hono-vite-repro
_Note:_ it's using PNPM, but you should see the same results with NPM

1. Run `npm run dev` and open the app in the browser. You should see two H1's, one from the server, another from the client component
2. Edit the `src/App.tsx` file. The second header will disappear in the browser

# What is happening

This repository was created using the hono `create hono`, then the client component was added following https://hono.dev/guides/jsx-dom and https://hono.dev/getting-started/cloudflare-pages#client-side, finally, the App component was moved to a separate file.

When you first load the page, the `App.tsx` file is loaded as http://localhost:5174/src/App.tsx
When the file is edited, Vite (?) adds the cache busting param and tries to load the file as http://localhost:5174/src/App.tsx?t=1709163721558

This ultimately fails, giving 404. Any query prams in that URL result in the same.

**Comment by emirotin** [comment]
Interesting enough

I have tried reproducing it vanilla Vite app with React. It uses the same cache busting, and things work as expected

However, 
* if loading http://localhost:5174/src/App.jsx or http://localhost:5174/src/App.jsx?t=1709163880000 (cache busting param as added by Vite), it delivers the transpiled file with th source map
* if loading http://localhost:5174/src/App.jsx?t=x (any other param value), it delivers the original source

**Comment by yusukebe** [comment]
Hi @emirotin 

This is a `@hono/vite-dev-server` matter. I've released `hono/vite-dev-server@0.8.1`, which includes the fix now. Please try it.

**Comment by emirotin** [comment]
Yes that was it!
Arigato @yusukebe 🙇‍♂️

**Comment by emirotin** [comment]
A related note.
I think the same needs to be done for `.css`. And potentially for more files? Which makes this config looks a bit fragile to me.

## Context

I am using Tailwind, both server- and client-side, so my index.css is just 

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

For it to work, I
1. import it from the front-end entrypoints, resulting in
  a. it being properly built by Vite, and
  b. having HMR
2. link to it from the renderer, resulting in it
  a. loading on initial page load in dev, and
  b. being properly linked in prod

For 2 I'm following suite as with the JS/TS/TSX entrypoints:
```html
<link
  rel="stylesheet"
  href={import.meta.env.PROD ? "/static/index.css" : "/src/index.css"}
/>
```

In dev I get 404 for `/src/index.css`. I have patched your package, using `pnpm patch`, and it has fixed the issue. Patch below, but basically I just added the css regex. I think I could skip 2.a., but then styles wouldn't work for some purely SSR page without any client-side components. This is not the case for me right now, but it can become one as I add some help/info pages to the service.

## Patch

```diff
diff --git a/dist/dev-server.cjs b/dist/dev-server.cjs
index d610a803ad924504f2bc583c5535d2b781fa738a..de0d40af1313336d3a91c13027fbca6eed8ce633 100644
--- a/dist/dev-server.cjs
+++ b/dist/dev-server.cjs
@@ -30,6 +30,7 @@ const defaultOptions = {
   export: "default",
   injectClientScript: true,
   exclude: [
+    /.*\.css$/,
     /.*\.ts$/,
     /.*\.tsx$/,
     /^\/@.+$/,
diff --git a/dist/dev-server.js b/dist/dev-server.js
index a8b2f679e0187df9bf4dfc88ac7363d437b94c30..78e8c84f2ccc49756101e503b675195a6a3f37db 100644
--- a/dist/dev-server.js
+++ b/dist/dev-server.js
@@ -6,6 +6,7 @@ const defaultOptions = {
   export: "default",
   injectClientScript: true,
   exclude: [
+    /.*\.css$/,
     /.*\.ts$/,
     /.*\.tsx$/,
     /^\/@.+$/,
```

**Comment by yusukebe** [comment]
Hi @emirotin 

You can pass the `/.*\.css$/` to the `exclude` option with default values like the following:

```ts
import devServer, { defaultOptions } from '@hono/vite-dev-server'
import { defineConfig } from 'vite'

export default defineConfig(() => {
  return {
    plugins: [
      devServer({
        entry: 'src/index.tsx',
        exclude: [/.*\.css$/, ...defaultOptions.entry] // <===
      })
    ]
  }
})
```

Will this solve your problem?

But, putting CSS files as default for the `exclude` is not a bad idea. Will you create a PR for the `@hono/vite-dev-server`?

**Comment by emirotin** [comment]
Ah, I was short-sighted, I have even seen the mention of this being configurable, but somehow didn't figure out it should fix my problem :)

And yes, I can open a PR

**Comment by yusukebe** [comment]
> And yes, I can open a PR

Okay! please!
