### ISSUE TITLE
Why is onAbort returning a promise?

### ISSUE THREAD

**Issue by gunhaxxor** [honojs/hono#2289]
Perhaps I'm uninformed, but my understanding is that the onAbort is unnecessarily marked as async which can confuse consumers of the `StreamingApi`

https://github.com/honojs/hono/blob/81264a9cf5837462c9af6b5653ea1675759fa8db/src/utils/stream.ts#L68

**Comment by yusukebe** [comment]
@sor4chi Can't you handle this?

**Comment by sor4chi** [comment]
This was a complete mistake but I didn't notice it.If there is no problem, I will remove async, but what do you think?

**Comment by yusukebe** [comment]
Hi @sor4chi 

Please create the PR to remove it.

**Comment by sor4chi** [comment]
@gunhaxxor Thank you for this mention!
