### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by patotoma** [honojs/hono#230]
Hey guys,

after updating hono from v1.1.1 to 1.2.1, I'm getting the following error:

<img width="468" alt="Screen Shot 2022-05-14 at 10 44 40 PM" src="https://user-images.githubusercontent.com/3104587/168439051-1b63957d-7ecb-4e92-80c4-4e14b347dacf.png">

**Comment by yusukebe** [comment]
Could you show me the summary of the code `/user/me` including the middleware used in?

**Comment by patotoma** [comment]
Thanks for checking @yusukebe , but found the problem on my side.

In one of my handlers I had `return next()` and it caused this.

Removing `return` fixed this.
