### ISSUE TITLE
Add `hydrateRoot` function to `hono/jsx/dom`

### ISSUE THREAD

**Issue by pomdtr** [honojs/hono#2301]
### What is the feature you are proposing?

Currently the hydration mechanism is located in the `honox`. However, I would like to have access to it from the hono package. 

I'm currently building an [island util in val.town](https://val.town/v/pomdtr/island_demo), and I would love to switch from react to hono for rendering jsx.

**Comment by usualoma** [comment]
Hi @pomdtr 
Thank you for your comment!

The `honox` hydration with `hono/jsx/dom` is actually quite simple compared to what React does. It just renders a DOM by static HTML and overwrites it with [render](https://hono.dev/guides/jsx-dom#render) (similar to React's old render).

It's a very simple way of doing things, not clever, but the runtime size is small. We think this will work well enough for less large components.

Thus, if you want the same behavior as `honox`, you can use [render](https://hono.dev/guides/jsx-dom#render).
Or, do you need something more the same as `hydrateRoot` provided by React?

**Comment by pomdtr** [comment]
Interesting, I'll play with it. 

Would something like this work (adapted from [this val](https://www.val.town/v/pomdtr/hydrate_islands)) ?

```ts
const islands = Array.from(document.querySelectorAll("[data-hydration-src]"));
if (islands.length > 0) {
  const { render } = await import("https://esm.sh/hono/jsx");
  const { jsx: _jsx } = await import("https://esm.sh/hono/jsx/jsx-runtime");
  for (const island of islands) {
    const src = island.getAttribute("data-hydration-src");
    console.log(`hydrating ${src}`);
    const { default: Component } = await import(src);
    const props = JSON.parse(island.getAttribute("data-hydration-props"));
    render(island, _jsx(Component, props));
  }
}
```

**Comment by usualoma** [comment]
Okay, if you write the following, maybe it will work with hono/jsx.

```js
const islands = Array.from(document.querySelectorAll("[data-hydration-src]"));
if (islands.length > 0) {
  const { render } = await import("https://esm.sh/hono/jsx/dom"); // from hono/jsx/dom

  // this works fine, but the following line is better. hono/jsx/jsx-runtime includes server-side rendering support
  // const { jsx: _jsx } = await import("https://esm.sh/hono/jsx/jsx-runtime");
  const { jsx: _jsx } = await import("https://esm.sh/hono/jsx/dom/jsx-runtime"); // dom-specific version. this doesn't include server-side rendering support

  for (const island of islands) {
    const src = island.getAttribute("data-hydration-src");
    console.log(`hydrating ${src}`);
    const { default: Component } = await import(src);
    const props = JSON.parse(island.getAttribute("data-hydration-props"));
    render(island, _jsx(Component, props));
  }
}
```

**Comment by pomdtr** [comment]
I tried to implement it, but I encounter a weird error:

```
render.js:139 Uncaught TypeError: i.vR is not iterable (cannot read property undefined)
    at render.js:139:26
    at Array.forEach (<anonymous>)
    at F (render.js:130:11)
    at V (render.js:197:3)
    at j (render.js:173:3)
    at le (render.js:387:3)
    at hydrate_hono_islands?v=3:11:9
```

Any idea about what could be causing this ?

demo link: https://pomdtr-hono_island_demo.web.val.run/
val link: https://www.val.town/v/pomdtr/hono_island

**Comment by usualoma** [comment]
@pomdtr 
Ah, the order of passing the arguments is the other way around, as with React's render, you pass the JSX elements first, then the DOM elements.

It would work if I wrote the following.

```ts
render(_jsx(Component, props), island);
```

**Comment by pomdtr** [comment]
Yep, it works! 

Thanks for your help on this ❤️

**Comment by yusukebe** [comment]
@pomdtr 

Can we close this issue?

**Comment by pomdtr** [comment]
As you want. Using the render function is a good workaround, but I'm not sure how much it differs from a proper `hydrate` function

**Comment by yusukebe** [comment]
@pomdtr Thanks!

I think we don't need the React-compatible hydrate function like `hydrateRoot` right now. @usualoma What do you think?

**Comment by usualoma** [comment]
@yusukebe 
I, too, do not believe that additional implementation is necessary now since there is no apparent need. I'd like to think about it after everyone has used it a little more.

**Comment by yusukebe** [comment]
Thanks @usualoma !

Thus closing this issue.
