### ISSUE TITLE
app.mount doesn't include formData

### ISSUE THREAD

**Issue by taisan11** [honojs/hono#2304]
### What version of Hono are you using?

4.0.8

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```tsx
// index.tsx
import { Hono } from 'hono'
import test from './test'

const app = new Hono()

app.get('/', (c) => {
  return c.html(
  <form method="post">
    <button type="submit">submit</button>
    <label htmlfor="name">Name</label>
    <input type="text" id="name" name="name" />
  </form>
  )
})
app.post('/', async (c) => {
  const body = await c.req.formData()
  const name = String(body.get('name'))
  return c.text(name)
})

app.mount('/test', test.fetch)

export default app
```
```tsx
// test.tsx
import { Hono } from 'hono'

const app = new Hono()

app.get('/', (c) => {
  return c.html(
  <form method="post">
    <button type="submit">submit</button>
    <label htmlfor="name">Name</label>
    <input type="text" id="name" name="name" />
  </form>
  )
})
app.post('/', async (c) => {
  const body = await c.req.formData()
  const name = String(body.get('name'))
  return c.text(name)
})

export default app
```
![err](https://github.com/honojs/hono/assets/131413638/3fb5a1b3-75a8-4508-8b98-e749e9a4afdc)

### What is the expected behavior?

c.req.formData() can be obtained

### What do you see instead?

Null

**Comment by yusukebe** [comment]
Hi @taisan11 

I've ivenstigating this issue. This is a bug that only occurs when you run on Bun. Maybe there is a problem with Bun, but it is behaving weirdly and I haven't figured it out yet.

But you don't have to use `app.mount()`, you can use `app.route()`.

**Comment by taisan11** [comment]
Thank you.
I will try to use app.route().
Can I close this issues?

**Comment by yusukebe** [comment]
@taisan11 

Ah, yeah. If we need to solve the problem again, let's reopen it.

**Comment by yuniruyuni** [comment]
Hiya, I have faced same issue so I have tried to fix this problem.
Then I have noticed the reason why such bug has happen is bun's Request's clone doesn't work properly for body data:  https://github.com/oven-sh/bun/issues/1381
The bun's bug made `replaceRequest()`(`src/hono-base.ts` 354-362)'s `new Request(url, request)` don't work properly (it lost body data).
So we should wait for bun's fix, ...or we can use my workaround code below.

```typescript
    replaceRequest ||= (() => {
      const mergedPath = mergePath(this._basePath, path)
      const pathPrefixLength = mergedPath === '/' ? 0 : mergedPath.length
      return (request) => {
        const url = new URL(request.url)
        url.pathname = url.pathname.slice(pathPrefixLength) || '/'
        return new Request(url, {
            method: request.method,
            keepalive: request.keepalive,
            headers: request.headers,
            body: request.body,
            redirect: request.redirect,
            integrity: request.integrity,
            signal: request.signal,
            credentials: request.credentials,
            mode: request.mode,
            referrer: request.referrer,
            referrerPolicy: request.referrerPolicy,
        })
      }
    })()
```
