### ISSUE TITLE
 API rate limit exceeded

### ISSUE THREAD

**Issue by anhtuank7c** [honojs/hono#2311]
### What version of Hono are you using?

latest

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

```
yarn create hono
deno run -A npm:create-hono
```

Unable to initialize a brand new project

### What is the expected behavior?

Able to initialize project

### What do you see instead?

Error: API rate limit exceeded for 104.28.254.74. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Comment by yusukebe** [comment]
This is a known issue for the create-hono. Please try it after a while.

**Comment by yusukebe** [comment]
Duplicated https://github.com/honojs/create-hono/issues/15
