### ISSUE TITLE
`basicAuth` and `bearerAuth` should support dynamic users

### ISSUE THREAD

**Issue by tcurdt** [honojs/hono#2316]
### What is the feature you are proposing?

Having a fix set of credentials that never changes during the course of the process lifetime is not particular realistic.
With the current implementation I don't see a good way to connect the auth implementations to a database.
They both would need some form of a callback function instead of just passing in all the date in as config.

https://github.com/honojs/hono/blob/4ca5f60def726731b3afbf3f6137f0a4b92d8b27/src/middleware/bearer-auth/index.ts#L8

**Comment by yusukebe** [comment]
Hi @tcurdt 

I don't know exactly what you want to do, but you could write something like this:

```ts
app.get('/', async (c, next) => {
  const newToken = generateToken(c)
  const auth = bearerAuth({
    token: newToken,
  })
  return auth(c, next)
})
```

Anything more than this would be outside the scope of Basic Auth and Bearer Auth.

**Comment by tcurdt** [comment]
I want to inject the logic whether some auth is valid, not push credentials into the middleware.

```
async function validate (token) {
    return false // or true
}

async function validate (username, password) {
    return false // or true
}
```

Right now it looks like I would have to write a customer middleware for this.
But I have the feeling I am missing something.

**Comment by yusukebe** [comment]
@tcurdt 

I think the best solution is making custom middleware.

**Comment by tcurdt** [comment]
> I think the best solution is making custom middleware.

Hm. OK.
But how many times are user credentials NOT coming from a database?
Feels a little weird that `basicAuth` and `bearerAuth` are not supporting such a use case.

**Comment by yusukebe** [comment]
> But how many times are user credentials NOT coming from a database?
> Feels a little weird that `basicAuth` and `bearerAuth` are not supporting such a use case.

This is a built-in middleware that allows users to easily add authentication, so if you have any doubts, don't use it, create your own middleware. Or make a PR with specific specs and implementation.

**Comment by sor4chi** [comment]
Hello, I agree with this opinion.
Since `bearerAuth` is used dynamically in most cases, it seems like a hurdle to require many users to create custom middleware.

What about a policy of providing a lambda function that accepts a context as an argument, as the current implementation has `bearerAuth` accepting only a Config object?

```ts
// format
bearerAuth<Env>(async (c) => {
  return {}; // config
})

// usage with context env
app.get("/private", bearerAuth<Env>((c) => ({ token: c.env.token })), (c) => {
  return c.text("This message is secret!");
})

// usage with db auth
app.get(
    "/private",
    basicAuth<Env>(async (c) => {
        const client = db(c.env.DB);
        const res = await client.query(
            "SELECT * FROM basic_auth_users",
        );
        const users = res.rows;
        return { users };
    }),
    (c) => {
        return c.text("This message is secret!");
    },
)
```

How do you think?

**Comment by yusukebe** [comment]
Hi @sor4chi 

Is the example I mentioned before not enough?

```ts
app.get('/', async (c, next) => {
  const newToken = generateToken(c)
  const auth = bearerAuth({
    token: newToken,
  })
  return auth(c, next)
})
```

**Comment by tcurdt** [comment]
> Is the example I mentioned before not enough?

Not really. A token is not generated but provided.
And everyone would have to write their own middleware for such a common use case.

It should be a pull not be a push API.

Pushing data into the middleware is just not applicable for a real world scenario.
Imagine the app has 1M users. You don't really want to push all users credentials into the middleware.


```
async function validateBearer (c, token) {
    return false // or true
}

async function validateBasic (c, username, password) {
    return false // or true
}

app.get("/private", bearerAuth((c, token) => (validateBearer(c, token))), (c) => {
  return c.text("This message is secret!");
})

app.get("/private", bearerBasic((c, username, password) => (validateBasic(c, username, password))), (c) => {
  return c.text("This message is secret!");
})
```

or more simple


```
async function validateBearer (c) {
    // check provided token
    return false // or true
}

async function validateBasic (c) {
    // check provided username and password
    return false // or true
}

app.get("/private", bearerAuth((c) => (validateBearer(c))), (c) => {
  return c.text("This message is secret!");
})

app.get("/private", bearerBasic((c) => (validateBasic(c))), (c) => {
  return c.text("This message is secret!");
})
```

**Comment by yusukebe** [comment]
@tcurdt 

Hmm. If you implement `validateBearer` or `validateBasic` yourself, I don't think you need to use Bearer Auth Middleware and Basic Auth Middleware.

**Comment by yusukebe** [comment]
You can write like the following without built-in middleware:

```ts
import { Hono } from 'hono'
import { createMiddleware } from 'hono/factory'
import { HTTPException } from 'hono/http-exception'

const app = new Hono()

const customAuth = createMiddleware(async (c, next) => {
  const isValid = validate(c)
  if (!isValid) {
    const res = new Response('Unauthorized', {
      status: 401,
      headers: {
        //...
      },
    })
    throw new HTTPException(400, { res })
  }
  await next()
})

app.get('/private', customAuth, (c) => {
  return c.text('This message is secret!')
})
```

**Comment by tcurdt** [comment]
If you put it that way you got a point.
I am fine to use a custom middleware.

So feel free to close.

That said: I do feel like the current `basicAuth` and `bearerAuth` implementation are are some odd ducklings as is.

Question is, whether the username/password/token extraction or dealing with the realm could/should be abstracted away from the user. If `hono` comes with auth helpers, I think it should support passing in functions. But I am also fine without.

**Comment by yusukebe** [comment]
@tcurdt 

> Question is, whether the username/password/token extraction or dealing with the realm could/should be abstracted away from the user. If `hono` comes with auth helpers, I think it should support passing in functions. But I am also fine without.

Yeah, I think you are right, we can abstract the common parts of Basic Auth and Bearer Auth. That is a good idea.

But as I said, we can create own middleware, so I don't think we need to make abstract too much.

Now, let's close this Issue once. If there are similar needs, we can reopen it. Thanks for the discussion!

**Comment by osseonews** [comment]
Agree with the comments above to make basicAuth dynamic. I am sort of a hobby coder and can generally figure out most stuff from docs and examples, but and I was looking to use basicAuth, but store the username and passwords in ENV variables, as opposed to hardcoding them in the actual call to basicAuth as all the examples do. Been working for an hour and can't figure out how the heck to do that, as can't pass c.env to the same middleware function that basicAuth is called in. Keep getting errors. Only thing that works is hardcoding the usernames and passwords into basicAuth, which seems like a poor solution. Anyway, i'm sure it's easy, but I can't figure it out. btw, one of my attempts is below. 

```
app.use('/admin/*', async (c,next) => {
  
  async function verifyFn(user,pw) {
    return basicAuth({
      username: user,
      password: pw,
    })
  }
  const user = `${c.env.ADMIN_USER}1`
  const pw = c.env.ADMIN_PW
  const verify = await verifyFn(user,pw)

}
)
```

**Comment by tcurdt** [comment]
@osseonews I don't think this closed issue is the right place to ask for these kind of support questions.

FWIW, passing env variables is only semi dynamic. It depends whether you are running on node or on edge. If you are running on node you could just pass the env variables from the process and not the context to the standard middleware.

> Edit, is this the correct way to do it??

Have you tried it? Your lasst code snippet looks like it should work.

It still pushed the data into the middleware though and creating a new middleware on every request also feels wrong.

**Comment by osseonews** [comment]
Sorry, about that. I didn't realize I couldn't post a comment here as the topic completely related to the same issue I had. Anyway, in case anyone ever finds this post and has the same issue, my 2nd snippet works fine, if you are using Hono in Cloudflare Workers (edge). 

As regards to the 2nd comment: " creating a new middleware on every request also feels wrong." I don't understand this comment. That's actually the whole point of middleware, it runs on every request for the path specified. I dno't see why that is wrong. It's just another function. In Hono examples, they have a logger middleware, which you can run on every request irregardless of the path. 

Anyway, thanks all for your help. Appreciate it. Hono has been an amazing library for me.

**Comment by yusukebe** [comment]
Hi @osseonews 

Quick response. This is good way which we recommend:

```ts
app.use('/admin/*', async (c, next) => {
  const auth = basicAuth({
    username: c.env.ADMIN_USER,
    password: c.env.ADMIN_PW,
  })
  return auth(c, next)
})
```
