### ISSUE TITLE
Improvement Suggestion for CORS Configuration Documentation on Hono

### ISSUE THREAD

**Issue by Rishiraj8** [honojs/hono#2318]
### Comparison: CORS Configuration for Hono

Most of the learners like me encountering challenges with the provided CORS configuration documentation. After exploring the documentation and implementing the suggested setup, I faced errors that hindered the seamless integration of my applications with the API. To enhance the user experience and prevent similar issues for future users, I suggest refining the documentation 

Actual Provided Code:

```javascript
app.use(
  '/api2/*',
  cors({
    origin: 'http://example.com',
    allowHeaders: ['X-Custom-Header', 'Upgrade-Insecure-Requests'],
    allowMethods: ['POST', 'GET', 'OPTIONS'],
    exposeHeaders: ['Content-Length', 'X-Kuma-Revision'],
    maxAge: 600,
    credentials: true,
  })
);
```
<img width="946" alt="HonoApi" src="https://github.com/honojs/hono/assets/136100903/0fef6a4a-dca7-46f1-9b5c-db0fc51aea99">

Suggested code

```javascript
app.use('*', async (c, next) => {
  const corsMiddleware = cors({
    origin: 'http://example.com',
    allowedHeaders: ['Origin', 'Content-Type', 'Authorization'],
    allowMethods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'],
    credentials: true,
  });
  return await corsMiddleware(c, next);
});

```

I might Suggest to give <code>async</code> and <code>return await</code>
So that Learner's like me who have struggled with CORS error can overcome :)
Thank you.....Hono

**Comment by damianpumar** [comment]
Hi @Rishiraj8 

What do you think with something like this: 

```
app.use(
  "*",
  cors({
    origin: "http://example.com",
    allowHeaders: ["Origin", "Content-Type", "Authorization"],
    allowMethods: ["OPTIONS", "GET", "POST", "PUT", "DELETE"],
    credentials: true,
  })
);
```
Firstly
* The prop is `allowHeaders` not `allowedHeaders`
Secondly
* I think it is better to put “Options” as a first element in the array.

And also I think it would be good idea to add the wildcard for this!

Let me know what do you think!

**Comment by damianpumar** [comment]
Hello @Rishiraj8.
I think your contribution was great! maybe you can improve it for sure! 
Try to re-open if you want and improve this little details!

Thanks!
