### ISSUE TITLE
Session flash?

### ISSUE THREAD

**Issue by typicode** [honojs/hono#2321]
### What is the feature you are proposing?

I don't have a strong opinion on this and I'm fine with the way Hono currently works.

However, I'm wondering if something for making flash messages easier would make sense to be in the core? For example, to show a message after a successful POST request and a redirect.

Here are three options that I see:

1. Create a `setFlash` and `getFlash`
2. Make `deleteCookie` return the deleted value
3. No changes and keep Hono core small

What do you think?

**Comment by yusukebe** [comment]
Hi @typicode !

I think that is a great idea. I also wanted the feature like session flashing, as you said.

I'd like to hear others' opinions.

@usualoma @watany-dev @Code-Hex @sor4chi @nakasyou  and others, how do you feel?

**Comment by Code-Hex** [comment]
My personal preference is either 2 or 3!

**Comment by sor4chi** [comment]
I prefer 2 because it is the least destructive, intuitive, and extensible.

**Comment by nakasyou** [comment]
I like 2 because it is expandable and smart.

**Comment by sor4chi** [comment]
Hi all, I commented once because the discussion had stopped.
I think 2 would be a quick and easy category to implement.

If it's okay with you if we continue to submit PR, we'll get to work on it.

**Comment by yusukebe** [comment]
Hi @sor4chi 

> If it's okay with you if we continue to submit PR, we'll get to work on it.

Will you do it? Please!

**Comment by yusukebe** [comment]
This has been fixed by #2512 . Thanks!
