### ISSUE TITLE
showRoutes print `undefined`

### ISSUE THREAD

**Issue by damianpumar** [honojs/hono#2328]
### What version of Hono are you using?

latest

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

the showRoutes function print `undefined`
<img width="357" alt="Screenshot 2024-03-07 at 23 08 48" src="https://github.com/honojs/hono/assets/7398909/edd0a887-fc05-4185-919e-daa2e79d49f1">

**Comment by damianpumar** [comment]
Hello! I can fix it if you want!

**Comment by yusukebe** [comment]
Hi @damianpumar! Please!

**Comment by damianpumar** [comment]
Hello @yusukebe sorry it was my mistake. I had a console.log(showRoutes(app)); instead to use just showRoutes(app);

**Comment by yusukebe** [comment]
Okay! No problem.
