### ISSUE TITLE
No req.header() in version 4

### ISSUE THREAD

**Issue by augustblack** [honojs/hono#2332]
### What version of Hono are you using?

4.0.10

### What runtime/platform is your app running on?

cloudflare workers

### What steps can reproduce the bug?

I have a simple example that works with Hono v3.  This is a websocket example, but the issue seems to be that there are no req.header() when fetching on /ws when using Hono v4

src/index.ts
```
import { Hono } from 'hono'
export { SignalServer } from './signalserver'

type Bindings = {
  SIGNAL_SERVER: DurableObjectNamespace
}
const app = new Hono<{ Bindings: Bindings }>()
app.use('*', (c) => {
  const id = c.env.SIGNAL_SERVER.idFromName('A')
  const obj = c.env.SIGNAL_SERVER.get(id)
  // console.log('url:', c.req.url, c.req.header()). // HEADERS EXIST HERE
  return obj.fetch(c.req.url, c.req)
})

export default app
```

src/signalServer.ts
```
import { Hono } from 'hono'
import RX from './rx.html'


export class SignalServer {
  state: DurableObjectState
  app: Hono = new Hono()

  constructor(state: DurableObjectState) {
    this.state = state

    this.app.get('/ws', async (c) => {
      const upgradeHeader = c.req.header('Upgrade')
      console.log('headers:', c.req.header()) //  IN V3,  HEADERS EXIST.  IN V4, THERE ARE NO HEADERS HERE
      if (upgradeHeader !== 'websocket') {
        console.log('NO upgrade HEADER', upgradeHeader)
        return c.text('Expected websocket', 400)
      }

      let currentValue = await this.state.storage?.get<number>('count') || 0
      currentValue = currentValue + 1
      await this.state.storage?.put('count', currentValue)

      const [client, server] = Object.values(new WebSocketPair())

      this.state.acceptWebSocket(server, ['signal'])
      return new Response(null, {
        status: 101,
        webSocket: client,
      })
    })

    this.app.get('/', async () => {
      return new Response('<html><head></head><body>hello</body></html>', { headers: { 'Content-Type': 'text/html;charset=UTF-8' } })
    })
    this.app.get('/rx', async () => {
      return new Response(RX, { headers: { 'Content-Type': 'text/html;charset=UTF-8' } })
    })
  }
  async fetch(request: Request) {
    return this.app.fetch(request)
  }
}
```

src/rx.html
```
<html>
  <head>
    <style>
      body {
        margin: 1rem;
        font-family: monospace;
      }
    </style>
    </head>
<body>
RX
<script>
 
  let ws

  async function websocket(url) {
    console.log('url', url)
    ws = new WebSocket(url)

    if (!ws) {
      throw new Error("server didn't accept ws")
    }

    ws.addEventListener("open", () => {
      console.log('Opened websocket')
    })

    ws.addEventListener("message", ({ data }) => {
      try {
        const msg = JSON.parse(data)
        console.log('msg', msg)
      } catch (error) {
        console.log('msg decode error:', error)
      }
    })

    ws.addEventListener("close", () => {
      console.log('Closed websocket')
    })
  }    ws.addEventListener("close", () => {
      console.log('Closed websocket')
    })
  }

  const url = new URL(window.location)
  url.protocol =  url.protocol === 'https:' ? "wss" : "ws"
  url.pathname = "/ws"
  console.log('url', url.href)
  websocket(url.href)

  </script>
 </body>
</html>
```

### What is the expected behavior?

I would expect Hono V3 and V4 to be identical here and pass the headers through.

### What do you see instead?

In Hono V4, the `c.req.header()` is empty on `this.app.get('/ws', async (c) => ....`

**Comment by yusukebe** [comment]
Hi @augustblack 

I'll investigate it, but your reproducing code is a bit complex. So, could you provide a minimal example or GitHub project?

**Comment by augustblack** [comment]
sorry for the long delay.
please see the repo at https://github.com/augustblack/hono_issue_2332

and specifically this line: https://github.com/augustblack/hono_issue_2332/blob/ba48f3ca61981e93947f84dfa9b300f2ead0063a/src/signalserver.ts#L68

In v3, all is fine.

In v4, there are no headers on the c.req  when making the inital websocket GET request.

**Comment by yusukebe** [comment]
Hi @augustblack 

Thank you for creating the project. I've tried it. But it seems to work fine:

![CleanShot 2024-04-14 at 09 24 55@2x](https://github.com/honojs/hono/assets/10682/325c3702-2db3-49f9-b916-afa5923e3e72)

Or is my way wrong?

**Comment by augustblack** [comment]
Hi  @yusukebe 

Thanks for taking a look and thanks for the wonderful hono.js project.

the package.json uses Hono v3, which is working.

If you upgrade the package.json to use to hono v4, does it still work for you?

**Comment by yusukebe** [comment]
@augustblack 

> the package.json uses Hono v3, which is working.

Ah, thanks!

You can use `c.req.raw` for `fetch` in `src/index.ts`:

```ts
// src/index.ts

app.use('*', (c) => {
  const id = c.env.SIGNAL_SERVER.idFromName('A')
  const obj = c.env.SIGNAL_SERVER.get(id)
  return obj.fetch(c.req.url, c.req.raw) // use c.req.raw
})
```

**Comment by augustblack** [comment]
okay, thank you.  It is working now.

it would be great to update the examples for version 4.

**Comment by yusukebe** [comment]
We can close this. Thanks!
