### ISSUE TITLE
Missing 'end' event listeners for ctx.res in Deno runtime

### ISSUE THREAD

**Issue by itsfuad** [honojs/hono#2336]
### What is the feature you are proposing?

In some situations, we often have to do some work right after the response is fully sent to the client. It even gets worse when we send response as stream. For readable stream, we also don't have any way to know when the stream is done loading.

Deno has a lot of missing thing that Hono also suffers from.

**Comment by yusukebe** [comment]
Hi @itsfuad 

Is that a feature that is available in other runtimes? Is that something [Web Standards](https://developer.mozilla.org/en-US/docs/Web/API) can do?

**Comment by itsfuad** [comment]
That's a big issue. Sadly there is no solution. But I tried to do some alternative ways to mimic my need. 
for example, when user downloads a file from the API route '/download:id:userId' I count the downloads. And after maximum downloads is done, let's say In a chat room there are 10 users. One has uploaded a file, 9 others has to download. So after all of them has downloaded the file we do not need to store the file in the server anymore. So we delete the file right after the last person downloaded it. 

My first approach was,

```ts
ctx.newResponse(file.readable) //sends as stream

Deno.remove(...) //file delete logic.
```

This code has issue like ctx is not finalized and the file gets deleted while it is being sent to the client. if I write `return ctx.newResponse(...)` then the next lines won't be executed.

We could have,
```ts
ctx.newResponse(file.readable) //sends as stream

ctx.res.on('end', ()=> {
  Deno.remove(...) //file delete logic.
});
```


So I used `finally` block and put the file detetion code on that block as finally will always run no matter I used `return` in the try block or not.



Thanks for your great project! You can close this issue. 🤜🤛

**Comment by yusukebe** [comment]
@itsfuad 

I'm pleased you've resolved your issue.

But if `ctx.res` is a Response object, then there is no `on` method. Did you use `ctx.res.on`?

```ts
ctx.res.on('end', ()=> { // <=== If ctx.res is Response, it does not have `on`.
})
```
