### ISSUE TITLE
Add expires to JWT helper

### ISSUE THREAD

**Issue by amiftachulh** [honojs/hono#2349]
### What is the feature you are proposing?

Hello, I would like to request a feature to add an "expires" parameter to the JWT sign function. This would help me implement access tokens and refresh tokens more effectively. Thank you.

**Comment by NicoPlyley** [comment]
If you make you payload on object you can 

```ts
const token = await sign({id: 123, exp: 17105349494}, secret)
```

The expiration needs to be epoch time without milliseconds.

You can see all the parameter here https://hono.dev/helpers/jwt#payload-validation

**Comment by amiftachulh** [comment]
Thanks, @NicoPlyley, it really helped me.
