### ISSUE TITLE
StatusCode type not exported

### ISSUE THREAD

**Issue by rmuchall** [honojs/hono#2354]
### What version of Hono are you using?

4.1.0

### What runtime/platform is your app running on?

NodeJs

### What steps can reproduce the bug?

// Argument of type number is not assignable to parameter of type StatusCode | undefined
const httpStatusCode: number = 500;
return c.json({success: true}, httpStatusCode);

// TS2305: Module "hono" has no exported member StatusCode
import {StatusCode} from "hono";

// TS2307: Cannot find module hono/utils/http-status.js or its corresponding type declarations.
import {StatusCode} from "hono/utils/http-status.js";

// TS2307: Cannot find module hono/utils or its corresponding type declarations.
import {StatusCode} from "hono/utils";

### What is the expected behavior?

c.json() should accept type "number" for HTTP status codes or Hono's type StatusCode should be exported.

### What do you see instead?

If attempting to use a number in place of a StatusCode:
Argument of type number is not assignable to parameter of type StatusCode | undefined

If attempting to import StatusCode:
TS2305: Module "hono" has no exported member StatusCode

**Comment by NicoPlyley** [comment]
You can import `import { StatusCode } from 'hono/utils/http-status'` and it should work. You added .js at the end.
Also if you use a const like in your example, if you let ts infer the type it will work.

So rather than doing 
```js
const httpStatusCode: number = 500;

// Use 
const httpStatusCode = 500;

// Which will result
const httpStatusCode: 500 = 500;
```

**Comment by rmuchall** [comment]
That worked, many thanks. 

This seems to be a problem with my IDE (JetBrains Webstorm) rather than Hono. For some reason Intellisense/auto imports are broken hence the erroneous bug report. My apologies :)
