### ISSUE TITLE
Uploading does not work as mentioned in docs

### ISSUE THREAD

**Issue by RiadhAdrani** [honojs/hono#2366]
### What version of Hono are you using?

4.1.0

### What runtime/platform is your app running on?

node v20

### What steps can reproduce the bug?

Create a new project using `yarn create hono` and copy this code in `src/index.ts`

```ts
import { serve } from '@hono/node-server';
import { Hono } from 'hono';

const app = new Hono();

app
  .get('/', (c) => {
    return c.text('Hello Hono!');
  })
  .post('/upload', async (c) => {
    // form
    const form = await c.req.formData(); // error
    const file = form.get('file');
    console.log(file);

    // or body
    const body = await c.req.parseBody();
    console.log(body); // {}

    return c.text('file upload');
  });

const port = 3000;
console.log(`Server is running on port ${port}`);

serve({
  fetch: app.fetch,
  port,
});

```

![image](https://github.com/honojs/hono/assets/54232641/b308a198-0c99-455c-ada7-497006f7fa14)

### What is the expected behavior?

I should get a `File` in the form or at least in the body as you described in the docs [here](https://hono.dev/snippets/file-upload).

## Body
I get an empty object `{}`.

## Form
I get an error :

```bash
TypeError: Request.formData: Could not parse content as FormData.
    at webidl.errors.exception (node:internal/deps/undici/undici:1581:14)
    at Request.formData (node:internal/deps/undici/undici:5276:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Array.<anonymous> (/home/ri/workspace/hono-upload/src/index.ts:12:18)
    at responseViaResponseObject (/home/ri/workspace/hono-upload/node_modules/@hono/node-server/dist/index.js:347:13)
```

### Additional information

I am using `WSL 2`.

**Comment by yusukebe** [comment]
Hi @RiadhAdrani 

Hmm. I can't reproduce it.

<img width="1183" alt="Screenshot 2024-03-17 at 9 25 11" src="https://github.com/honojs/hono/assets/10682/d906ec4c-d402-4b5b-973f-40f2338ce5c5">

**Comment by RiadhAdrani** [comment]
I tested it directly on windows and ubuntu, it works.
The problem is that I am browsing a file from `Windows` into `WSL`, and I think that's the problem.
