### ISSUE TITLE
Hono with Vercel gives error on start: Unhandled Runtime Error Error: Objects are not valid as a React child (found: object with keys {isEscaped, tag, props, children, key}). If you meant to render a collection of children, use an array instead.

### ISSUE THREAD

**Issue by xkeshav** [honojs/hono#2367]
### What version of Hono are you using?

4.0.1

### What runtime/platform is your app running on?

Vercel

### What steps can reproduce the bug?

just run the command

> npm run dev 

it flash the main page for a second then throw error on page

Unhandled Runtime Error
Error: Objects are not valid as a React child (found: object with keys {isEscaped, tag, props, children, key}). If you meant to render a collection of children, use an array instead.

### What is the expected behavior?

it shoukd load the page which was running fine few hrs back. I have installed tsx and try to make some changes in hono server route file but revert back the changes ; also some changes in tsconfig.json

### What do you see instead?

I see this error page on localhost:3000

![image](https://github.com/honojs/hono/assets/415219/1a7d53c5-efab-4881-ac08-45e305d5f99e)

### Additional information

here is the repo detail. https://github.com/xkeshav/honor

**Comment by yusukebe** [comment]
Hi @xkeshav 

How can I reproduce it? I've cloned your repo and run `npm run dev`, but it works well.

<img width="804" alt="Screenshot 2024-03-17 at 21 10 28" src="https://github.com/honojs/hono/assets/10682/98cd4b8d-4e21-415e-be19-7f5bcb6f39a3">

**Comment by xkeshav** [comment]
Is it?  Its not working in my system might be I have do clear cache or npm install again. Thanks for confirming

**Comment by yusukebe** [comment]
@xkeshav 

How about trying to remove `npm_modules` and rerun `npm i`?

**Comment by xkeshav** [comment]
> @xkeshav
> 
> How about trying to remove `npm_modules` and rerun `npm i`?



it worked.
