### ISSUE TITLE
Deno middleware does not export a JWT helper (e.g., sign).

### ISSUE THREAD

**Issue by danewalters** [honojs/hono#2379]
### What version of Hono are you using?

4.1.2

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

hono jwt middleware cannot export sign and other auxiliary functions in deno environment。
```ts
import { sign } from 'https://deno.land/x/hono/middleware.ts'
```

https://github.com/honojs/hono/blob/main/deno_dist/middleware.ts#L12

**Comment by danewalters** [comment]
@yusukebe

**Comment by NicoPlyley** [comment]
That's the intended purpose, this is a middleware function for validating the JWT before it hits a route. 

If you want to use the other function you need to use JWT helper which is `import { decode, sign, verify } from 'hono/jwt'`

**Comment by yusukebe** [comment]
Hi @danewalters !

Actually, they were not exported for Deno! I've fixed it, and you can import them like the following with a new version that will be released soon.

```ts
import { jwtDecode, jwtSign, jwtVerify } from 'https://deno.land/x/hono@v4.1.1/helper.ts'
```

@NicoPlyley Thanks for handling! This issue was a deno.land matter (we have to support JSR! for Deno).

**Comment by danewalters** [comment]
> Hi @danewalters !
> 
> Actually, they were not exported for Deno! I've fixed it, and you can import them like the following with a new version that will be released soon.
> 
> ```ts
> import { jwtDecode, jwtSign, jwtVerify } from 'https://deno.land/x/hono@v4.1.2/helper.ts'
> ```
> 
> @NicoPlyley Thanks for handling! This issue was a deno.land matter (we have to support JSR! for Deno).

Thank you!!!
