### ISSUE TITLE
If path parameter is an encoded URL, the request is not routed correctly

### ISSUE THREAD

**Issue by alvinsw** [honojs/hono#2386]
### What version of Hono are you using?

4.1.0

### What runtime/platform is your app running on?

Node.js

### What steps can reproduce the bug?

Add this to the route:
```
app.get('/entity/:id', async (c, next) => {
  console.log(c.req.param('id'));
  return c.json({});
}
```
And do HTTP GET /entity/https%3A%2F%2Ftest.com%2F123
That route handler will not be called.

### What is the expected behavior?

It should print `https://test.com/123` on the console

### What do you see instead?

Nothing in the console, and 404 response

### Additional information

The string passed to id parameter is generated using `encodeURLcomponent('https://test.com/123')` so I believe it should be treated just like a path component as a whole instead of being parsed before the route matching.
If I add a middleware to log the `req.path`, it will print `/entity/https:/test.com/123`.

**Comment by yusukebe** [comment]
Hi @alvinsw 

I can't reproduce it. It prints `https://test.com/123` correctly. Can you check it again to make sure it works?

**Comment by alvinsw** [comment]
Sorry my bad. I just traced it further and just found that it is caused by Nginx!! I am closing the issue.

**Comment by yusukebe** [comment]
@alvinsw Ah, Nginx!! No problem!
