### ISSUE TITLE
Support for `Vary` Header in Cache Middleware

### ISSUE THREAD

**Issue by naporin0624** [honojs/hono#2395]
### What is the feature you are proposing?

I suggest adding support for the `Vary` header in the cache middleware to improve content negotiation, particularly for image optimization use cases. This enhancement would allow serving different image formats based on the client's capabilities, enhancing compatibility across various browsers.

Here's a proposed change to include the `Vary` header:

```diff
export const cache = (options: {
  cacheName: string
  wait?: boolean
  cacheControl?: string,
+ vary?: string
}): MiddlewareHandler => {
  ```

```diff
await next()
if (!c.res.ok) {
  return
}
addHeader(c)
+ if (options.vary !== undefined) {
+   c.header('Vary', options.vary)
+ }
const res = c.res.clone()
```

Incorporating this option would allow for more flexible and efficient caching strategies, particularly for serving optimized images in formats like AVIF, which may not be supported by all browsers. This could be a simple yet impactful improvement to the middleware.

Would love to hear your thoughts on this addition.

**Comment by yusukebe** [comment]
Hi @naporin0624 !

This is not bad. But I think we can do the same thing by adding the following middleware manually:

```ts
app.get(
  '/cache/*',
  async (c, next) => {
    await next()
    c.header('Vary', 'Accept')
  },
  cache({
    cacheName: 'my-cache',
  })
)
```

If it doesn't work, I'm sorry, but could you try?

**Comment by naporin0624** [comment]
Hi, @yusukebe 

Yes, I have created the Vary middleware and use it in my projects.
Since Vary is a cache related header, I suggested adding it as an option in the cache middleware.

If this is redundant, I will close this issue.

thank you.

**Comment by yusukebe** [comment]
> Since Vary is a cache related header, I suggested adding it as an option in the cache middleware.

Yeah, I think so; the Vary is "cache related". But we may not have to include it in Cache Middleware.

> I will close this issue.

Can you give me some time to think about it? I'll give it some thought.

**Comment by yusukebe** [comment]
Hi @naporin0624 !

I've considered this. I think we should implement a supporting `Vary` header for Cache Middleware!

Can you create the PR? It may be a new feature in the next minor release. So please make it based on the [`next` branch](https://github.com/honojs/hono/tree/next). Thanks.

**Comment by naporin0624** [comment]
hi, @yusukebe

Thanks, I will start working on the PR!

I would like to confirm this in the creation of the PR!

We discussed once that there is no need to include `vary` in the cache middleware, but do you think that adding it as a support header means that the implementation policy is to include vary options in the cache middleware?

Thank you very much.

**Comment by yusukebe** [comment]
@naporin0624 

> but do you think that adding it as a support header means that the implementation policy is to include vary options in the cache middleware?

Yes!

**Comment by naporin0624** [comment]
PR created!
https://github.com/honojs/hono/pull/2426
