### ISSUE TITLE
Cloudflare queue and app routing

### ISSUE THREAD

**Issue by vickyRathee** [honojs/hono#2396]
### What version of Hono are you using?

4.1.2

### What runtime/platform is your app running on?

Cloudflare pages

### What steps can reproduce the bug?

I am hosting the same project in Cloudflare pages for API, and Cloudflare worker for `Queue()` and `Scheduled()`. So I used the provided example  - https://hono.dev/snippets/cloudflare-queue

```
const app = new Hono<{ Bindings: Bindings }>();

app.route('v1/campaigns', campaigns);

export default {
  fetch: app.fetch,
  async queue(batch: MessageBatch<Error>, env: Env) {
    try {
      batch.ackAll();
      for (const message of batch.messages) {
        //await startJob(env, message.body as any);
        console.log('m', message);
      }
    } catch (err: any) {
      console.error('Queue error', err);
    }
  },
};
```

For some reason, the routes doesn't work when I am using `export default`, while it was working fine when I was using the `export const onRequest = handle(app);`

![image](https://github.com/honojs/hono/assets/6106479/98f2dabb-75f3-4a11-8452-edea45d17cc9)

**Comment by vickyRathee** [comment]
Just to mention, my folder structure is `functions/[[server]].ts` instead `index.ts` as shown on hono docs

**Comment by yusukebe** [comment]
Hi @vickyRathee 

You can't receive queue messages with Cloudflare Pages, even though you can send queue messages. You should you Cloudflare Workers to receive messages.

**Comment by vickyRathee** [comment]
@yusukebe I am fine with receiving message on Worker, only thing I want to keep it same project in code-level. So that when I deploy on pages, the routes should work.

When I deploy on worker, the queue() should work.

**Comment by yusukebe** [comment]
@vickyRathee 

If you want to use it in `functions/[[server]].ts`, you have to write the following:

```ts
export const onRequest = handle(app)
```

**Comment by vickyRathee** [comment]
So, you mean the `queue()` won't be exported in that case?

**Comment by yusukebe** [comment]
How about writing this?

```ts
export default {
  async queue(batch: MessageBatch<Error>, env: Env) {
    try {
      batch.ackAll()
      for (const message of batch.messages) {
        //await startJob(env, message.body as any);
        console.log('m', message)
      }
    } catch (err: any) {
      console.error('Queue error', err)
    }
  },
}

export const onRequest = handle(app)
```

**Comment by vickyRathee** [comment]
@yusukebe I will give it a try and update you.

**Comment by vickyRathee** [comment]
@yusukebe Working fine, thank you!

Now, I can code everything in same project and deploy on Pages and Worker

**Comment by yusukebe** [comment]
@vickyRathee Great!

**Comment by yusukebe** [comment]
Closing!
