### ISSUE TITLE
An error occurred while inserting Google AdSense in jsx.

### ISSUE THREAD

**Issue by b0unt9** [honojs/hono#2402]
### What version of Hono are you using?

4.1.3

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

If you insert an ad using the old Google AdSense insertion method, the object disappears when you push the script and an error occurs in the browser.
```
<ins
  class='adsbygoogle adsbyadsense
  data-ad-client=''
  data-ad-slot=''
  data-ad-format='horizontal'
  data-full-width-responsive='false'></ins>
 <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
```
If you insert the above code into jsx, `{}` will disappear in the push of the `(adsbygoogle = window.adsbygoogle || []).push({});` script, and an error will occur in the browser.

### What is the expected behavior?

The empty object in the `(adsbygoogle = window.adsbygoogle || []).push({});` script should not disappear

### Additional information

My guess is that `{}` in `.push({})` is judged to be an empty object and is removed from hono

**Comment by b0unt9** [comment]
Using html and raw from hono/html
`(adsbygoogle = window.adsbygoogle || []).push(${raw({})});`
I tried writing the above type of script, but the same error occurs.

**Comment by b0unt9** [comment]
I solved it using hono/html

**Comment by nakasyou** [comment]
I think that it isn't a bug because it is included in JSX's feature.

You can resolve it if you use `dangerouslySetInnerHTML`:
```tsx
<script dangerouslySetInnerHTML={{
  __html: `(adsbygoogle = window.adsbygoogle || []).push({});`
}} />
```

**Comment by yusukebe** [comment]
This seems to be solved. Closing.
