### ISSUE TITLE
Less readable status for JWT mismatch and invalid JWT token

### ISSUE THREAD

**Issue by Devank-Sachdeva** [honojs/hono#2415]
### What is the feature you are proposing?

We receive the Status Code ```401 JwtTokenSignatureMismatched: token() signature mismatched``` whenever a token is mismatched during verification.
This long string compromises readability due to long token string that it appends in the status
May be we can strip it down to ```401 JwtTokenSignatureMismatched```

similar issue with ```401 JwtTokenInvalid```

![image](https://github.com/honojs/hono/assets/96934308/2bbc4e7d-b238-41d3-96ac-009314abc4bb)

I am using the jwt middleware 

```
const app = new Hono()
app.route("/api/v1",router)

```
```
router.use("/*", async (c, next) => {
    const middleware = jwt({secret: c.env.JWT_SECRET})
    return middleware(c, next)
})
```

**Comment by yusukebe** [comment]
Hi @Devank-Sachdeva 

Thanks for creating the issue.

@metrue @Code-Hex What do you think about this?

**Comment by metrue** [comment]
It's true different people have different preference about the readability, but I think exposing the `token` into the error message is not necessary though.

**Comment by Devank-Sachdeva** [comment]
Hi @Code-Hex 
when using the jwt middleware (https://hono.dev/middleware/builtin/jwt) during the jwt mismatch/or related error,  it doesn't throw an error but it send back a 401 response (which a middleware should) with the above status text hence, I don't think there is a easy way to change the status text of the middleware's response.
To change response's status text of the request I might have to write the middleware with verify function , which is basically rewriting a built-in jwt middleware which just defeats having a built-in jwt auth handler.

Also, I agree with @metrue that sending the `token` in the status text is not really necessary as 
`401 JwtTokenSignatureMismatched` is good enough to identify the problem with the request and also even if the token is invalid, exposing it in the response's status doesn't feel right

and also the response's header contains 
`WWW-Authenticate: Bearer realm="http://127.0.0.1:8787/api/v1/blog",error="invalid_token",error_description="token verification failure"`
which also address the error which occurred during the request

**Comment by Code-Hex** [comment]
@Devank-Sachdeva Thanks for your explanation. I understand.

I read source code for middleware, and I think it is better to throw HTTPExcection with cause option instead of convert to text. And edit status text to Error name.

https://github.com/honojs/hono/blob/d3403942c12c16847b0808cee1dcb0a2d6c81d1b/src/middleware/jwt/index.ts#L64

**Comment by Code-Hex** [comment]
Oops, on second thought, I don't think we should pass the reason for the error to the end user as a response. Because it will be a hint of an attack.

**Comment by metrue** [comment]
@Code-Hex  Yeah, some error name indeed tell reason of the failure authorization, so the error should be masked before response to client side, maybe a general '401 Unauthorized' message is enough.

**Comment by yusukebe** [comment]
I think adding a `JwtTokenInvalid` error object to `cause` option, as @Code-Hex  mentioned, is good:

```diff
diff --git a/src/middleware/jwt/index.ts b/src/middleware/jwt/index.ts
index 439405a..f40169e 100644
--- a/src/middleware/jwt/index.ts
+++ b/src/middleware/jwt/index.ts
@@ -57,18 +57,19 @@ export const jwt = (options: {
     }

     let payload
-    let msg = ''
+    let cause
     try {
       payload = await Jwt.verify(token, options.secret, options.alg as AlgorithmTypes)
     } catch (e) {
-      msg = `${e}`
+      cause = e
     }
     if (!payload) {
       throw new HTTPException(401, {
+        cause,
         res: unauthorizedResponse({
           ctx,
           error: 'invalid_token',
-          statusText: msg,
+          statusText: 'Unauthorized',
           errDescription: 'token verification failure',
         }),
       })
```

Any thoughts?

**Comment by Code-Hex** [comment]
LGTM

**Comment by Devank-Sachdeva** [comment]
Looks good ! 
Thank you for the fix @yusukebe

**Comment by yusukebe** [comment]
Okay! We can now close this now.
