### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by K4leri** [honojs/hono#2418]
### Discussed in https://github.com/orgs/honojs/discussions/2417

<div type='discussions-op-text'>

<sup>Originally posted by **K4leri** March 25, 2024</sup>
I found that _**hono/streaming**_ libriry is not accessable. Is their any way to implement streaming functionality ?

UPD: i found that streams are exactly the part of the hono libriry so in such case that is an error in docs
[This should be edited](https://hono.dev/helpers/streaming#streamsse)</div>

**Comment by yusukebe** [comment]
Hi @K4leri 

You can access like the following:

```ts
import { stream, streamText, streamSSE } from 'hono/streaming'
```

This issue can be closed.
