### ISSUE TITLE
hono/zod-openapi + RPC not working 

### ISSUE THREAD

**Issue by Octo8080X** [honojs/hono#2428]
### What version of Hono are you using?

Hono＠4.0.10, @hono/zod-openapi@0.9.9

### What runtime/platform is your app running on?

Deno(1.41.3)

### What steps can reproduce the bug?

I have prepared a minimally configured project in this repository.

https://github.com/Octo8080X/inspect-fresh-hono-openapi-rpc

Due to some issues, it appears that hono(RPC) + hono/zod-openapi is not working.

As one of the causes, there seems to be no `openapi()` in the object provided by the `z` method provided by `@hono/zod-openapi`.

```ts routes\api\[...path].ts
import { Handler } from "$fresh/server.ts";
import { OpenAPIHono, createRoute, z } from "@hono/zod-openapi";

const ParamsSchema = z.object({});

console.log(z.string());
// => ZodString {
//      spa: [Function: bound safeParseAsync] AsyncFunction,
//      _def: { checks: [], typeName: "ZodString", coerce: false },
//      parse: [Function: bound parse],
//      safeParse: [Function: bound safeParse],
//      parseAsync: [Function: bound parseAsync] AsyncFunction,
//      safeParseAsync: [Function: bound safeParseAsync] AsyncFunction,
//      refine: [Function: bound ],
//      refinement: [Function: bound refinement],
//      superRefine: [Function: bound superRefine],
//      optional: [Function: bound ],
//      nullable: [Function: bound ],
//      nullish: [Function: bound nullish],
//      array: [Function: bound array],
//      promise: [Function: bound promise],
//      or: [Function: bound or],
//      and: [Function: bound and],
//      transform: [Function: bound ],
//      brand: [Function: bound brand],
//      default: [Function: bound ],
//      catch: [Function: bound catch],
//      describe: [Function: bound describe],
//      pipe: [Function: bound pipe],
//      readonly: [Function: bound readonly],
//      isNullable: [Function: bound isNullable],
//      isOptional: [Function: bound isOptional]
//    }

const HeloWorldSchema = z
  .object({
    message: z.string().openapi({  // <= Property 'openapi' does not exist on type 'ZodString'.
      example: "Hello World!",
    }),
  })
  .openapi("HeloWorldResponse");  // <= Property 'openapi' does not exist on type 'ZodObject<{ message: any; }, "strip", ZodTypeAny, { [x: string]: any; message?: any; }, { [x: string]: any; message?: any; }>'

const route = createRoute({
  method: "get",
  path: "/api/hello_world",
  request: {
    params: ParamsSchema,
  },
  responses: {
    200: {
      content: {
        "application/json": {
          schema: HeloWorldSchema,
        },
      },
      description: "Retrieve the user",
    },
  },
});

const app = new OpenAPIHono();

const appRoutes = app.openapi(route, (c) => {
  return c.json({
    message: "Hello World!",
  });
});

export type AppRoutesType = typeof appRoutes;
```

Again, an error is made here by creating a client using a type created from a definition that is probably faulty in some way.

```ts islands\HelloWorld.tsx
import { useEffect, useState } from "preact/hooks";
import { hc } from "$hono/mod.ts";
import type { AppRoutesType } from "../routes/api/[...path].ts";
const client = hc<AppRoutesType>("http://localhost:8000/");   //  <= Type mismatch

export default function HelloWorld() {
  // omission
}
```

RPC with openapi removed works correctly.

### What is the expected behavior?

RPC can be used without causing type errors.

### Additional information

Perhaps this issue illustrates the same problem.
https://github.com/honojs/hono/issues/1784

**Comment by yusukebe** [comment]
Hi @Octo8080X 

Thanks for creating the issue.

I've tried your project. The first problem is the `z` is not typed well:

<img width="797" alt="Screenshot 2024-03-28 at 5 51 17" src="https://github.com/honojs/hono/assets/10682/548664c7-d85b-41ea-98c6-f25808e6bada">

I think this will happen when using Zod OpenAPI on Deno, and it's not a bug for Zod OpenAPI itself.

**Comment by nakasyou** [comment]
If you run this command, you may able to resolve it:
```shell
deno cache --reload fresh.gen.ts
```
This command reloads `fresh.gen.ts`'s dependencies. Them includes all routes and islands.
So you can reload almost project dependencies.
When you reload cache on Deno, there is a possibility that the problem with the library type will be solved.

**Comment by yusukebe** [comment]
Thanks @nakasyou 

But it does not resolve it. Hmm.

**Comment by nakasyou** [comment]
In my environment, `HelloWorldSchema` is successfully defined without `deno cache --reload`

Deno version: 1.41.3, Fresh version: v1.6.8

**Comment by yusukebe** [comment]
@nakasyou 

Is RPC-mode working well?

**Comment by nakasyou** [comment]
@yusukebe 
> Is RPC-mode working well?

I tested, the answer is no.
But RPC-mode working well when I replaced `https://deno.land/x/hono/mod.ts` to `npm:hono/client`.
I think the reason is that the `hono` referenced by `@hono/zod-openapi` is not `https://deno.land/x/hono/mod.ts`, but on npm.

**Comment by yusukebe** [comment]
@nakasyou 

> But RPC-mode working well when I replaced `https://deno.land/x/hono/mod.ts` to `npm:hono/client`.
> I think the reason is that the `hono` referenced by `@hono/zod-openapi` is not `https://deno.land/x/hono/mod.ts`, but on npm.

Yeah, exactly!

@Octo8080X 

So if you want to use RPC-mode, you can use the modules with npm specifier like `npm:hono/client`.

**Comment by Octo8080X** [comment]
@yusukebe san @nakasyou san

Thank you very much.
I will try the method of using npm:hono/client.
I will report the results again within 12 hours.

**Comment by Octo8080X** [comment]
@yusukebe san @nakasyou san

Sorry it took so long.
It didn't work and it took a long time.

As it turns out, it is not working.

Repository updated.
https://github.com/Octo8080X/inspect-fresh-hono-openapi-rpc

I have also cleared the cache, but the situation has not changed.
Am I misunderstanding something?

**Comment by Octo8080X** [comment]
I hope this is helpful.

![SnapCrab_NoName_2024-3-29_7-39-50_No-00](https://github.com/honojs/hono/assets/64694349/5f094da1-0ca8-49b1-9f10-ba5883c294f8)
![SnapCrab_NoName_2024-3-29_7-39-12_No-00](https://github.com/honojs/hono/assets/64694349/7c8526f3-c2c0-4a1b-8075-048c9234ef29)

**Comment by yusukebe** [comment]
Not sure, but it may be because `@asteasolutions/zod-to-openapi` only supports CommonJS and not ESM.

@nakasyou Can you take a look?

**Comment by Octo8080X** [comment]
I have not been able to figure out the cause of all this, but it may be the use of `extendZodWithOpenApi`.

https://github.com/honojs/middleware/blob/9e9c326c734ee2489d53213cdf739ae57a65bbd5/packages/zod-openapi/src/index.ts#L431

`z` is extended in the entity, but may not be interpreted as extended in the type.

**Comment by nakasyou** [comment]
Hmm, I can't understand for it.
I tried https://github.com/Octo8080X/inspect-fresh-hono-openapi-rpc, it doesn't work well.

But, I created minimal sample https://github.com/nakasyou/hono-openapi-deno, it's working well.

**Comment by Octo8080X** [comment]
@nakasyou san CC: @yusukebe 

Thank you very much.

I have referred to the source code for the minimum configuration you provided.
I wrote npm: directly once since it seemed that importmap was not used as a comparison.

I also removed the option to use node_modules and re-cached it again, and it now works.

Once normalized, using importmap again also works.

Perhaps the cache and the option to use node_modules in the default settings of fresh were incompatible.

hono I don't think that in itself is a problem.
Thanks for confirming.

**Comment by yusukebe** [comment]
@Octo8080X goood!

**Comment by Octo8080X** [comment]
Addendum.

I additionally applied `"nodeModulesDir": true` to deno.json of hono-openapi-deno, which was provided by @nakasyou san , and this also resulted in an error.

I am now convinced that this is a Deno node compatibility issue, regardless of fresh.
I would like to contact Deno with an Issue.

**Comment by yusukebe** [comment]
@Octo8080X Thanks. Can we close this issue?

**Comment by Octo8080X** [comment]
@yusukebe 
OK, I will close it myself.

**Comment by Octo8080X** [comment]
fix issue.
