### ISSUE TITLE
Serve static site with a proxy

### ISSUE THREAD

**Issue by charl-kruger** [honojs/hono#243]
Im trying to serve a static site as well as use a proxy of the same domain.

```
hono.use('/*', serveStatic({ root: './' }))
hono.use(
  '/proxy/*',
  cors({
    origin: 'http://exampleapi.com,
    allowHeaders: ['X-Custom-Header', 'Upgrade-Insecure-Requests'],
    allowMethods: ['POST', 'GET', 'OPTIONS'],
    exposeHeaders: ['Content-Length', 'X-Kuma-Revision'],
    maxAge: 600,
    credentials: true,
  })
)
```

However the requests to `proxy` are trying to serve the static files, is there a way i can do this?

**Comment by yusukebe** [comment]
Hi @charl-kruger !

This issue has been fixed on 1.3.2 released just now. Maybe, it will work well.

I know ***workers-site dir*** issue, but it is not reproduced in my environment with the latest Wrangler.
