### ISSUE TITLE
hc with dynamic headers

### ISSUE THREAD

**Issue by niko-gardenanet** [honojs/hono#2460]
### What is the feature you are proposing?

It would be very handy if you could pass a function to `hc` that gets called on every request and returns the headers. My use case would be to get the JWT from localStorage on every request because the JWT is managed by another library and can change at any time.

```ts
const client = hc<App>("https://example.com", {
  headers: () => ({
    Authorization: `Bearer ${localStorage.getItem("jwt")}`,
  }),
});
```

This would eliminate the need to create a new client whenever the JWT changes.

**Comment by anishkumar127** [comment]
Thanks <3
