### ISSUE TITLE
Error on .jsx file

### ISSUE THREAD

**Issue by cdtut** [honojs/hono#2463]
### What version of Hono are you using?

4.2.1

### What runtime/platform is your app running on?

nodejs

### What steps can reproduce the bug?

In starter template I choose nodejs and rename file index.js to index.jsx and update package.json. When I go to route I get error on line with `c` from line with `return c.html()` that render JSX.

### What is the expected behavior?

.jsx should be supported like .tsx.

### What do you see instead?

```
ReferenceError: React is not defined
    at Array.<anonymous> (my-app/src/index.jsx:29:16)
    at Hono.dispatch (my-app/node_modules/.pnpm/hono@4.2.1/node_modules/hono/dist/cjs/hono-base.js:198:38)
    at fetch (my-app/node_modules/.pnpm/hono@4.2.1/node_modules/hono/dist/cjs/hono-base.js:224:17)
    at Server.<anonymous> (my-app/node_modules/.pnpm/@hono+node-server@1.9.1/node_modules/@hono/node-server/dist/index.js:404:13)
```

### Additional information

This is tsconfig.json

```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "types": [
      "node"
    ],
    "jsx": "react-jsx",
    "jsxImportSource": "hono/jsx",
  }
}
```

**Comment by NicoPlyley** [comment]
Can you post the code too to verify this error is not do to something there

**Comment by cdtut** [comment]
Run `pnpm create hono my-app` then select `nodejs` and `pnpm`. Replace line in index.ts to `return c.html(<div>test</div>)`. Change index.ts to index.jsx and update package.json then `pnpm run dev` and access localhost:3000 and you'll get the error.

**Comment by NicoPlyley** [comment]
Since you not using typescript with a `.jsx` file its not added to the compiler. You need to add in the pragma directives

```js
/** @jsx jsx */
/** @jsxImportSource hono/jsx */
```

Then you will need to import `jsx` as well

```js
import { jsx } from 'hono/jsx';
```

**Comment by cdtut** [comment]
For first change this is already in tsconfig.json, which file do I need to add pragma?

```
"jsx": "react-jsx",
"jsxImportSource": "hono/jsx",
```

Where to import `jsx` and how to use it? I didn't import `tsx` so nowhere to replace it.

**Comment by NicoPlyley** [comment]
Yes, but the `tsconfig.json` only works when you are using typescript. If you have a `.jsx` file you are no longer using typescript.

You need to import jsx in any `.jsx` file, just like in React you used to have to import it even thought it was not used.

**Comment by NicoPlyley** [comment]
Ultimately, you should use`.tsx`. Typescript is working as the compiler, and using pragma directives will work but there may be bugs. In order to use vanilla javascript you would want to have a compiler like babel

**Comment by cdtut** [comment]
Javascript is valid typescript so typescript should still work as compiler instead of babel. Files that are .jsx should work as easy as .tsx.

**Comment by NicoPlyley** [comment]
Yes JavaScript is valid typescript but JavaScript files are usually ignored by TypeScript.

However, a good point I didn't consider is allowing plain js to run with typescript. If you add `allowJs: true, checkJs: true` to your tsconfig.json that should allow it to work as well

**Comment by NicoPlyley** [comment]
@cdtut Did this work for you? Can we close this issue?
