### ISSUE TITLE
hc ClientResponse<T>.json() method removes null from T union

### ISSUE THREAD

**Issue by niko-gardenanet** [honojs/hono#2465]
### What version of Hono are you using?

4.2.1

### What runtime/platform is your app running on?

Node.js

### What steps can reproduce the bug?

```ts
// server.ts
const app = new Hono();
app.get("/", async c => {
  return c.json(null);
})

export type AppType = typeof app;
```

```ts
// client.ts
import type { AppType } from "./server.ts";
const client = hc<AppType>("http://example.com")

const result = await client.index.$get().then(x => x.json());
//    ^? never
```

### What is the expected behavior?

The type of `result` should be `null`

### What do you see instead?

The type of `result` is `never`

### Additional information

This also happens for unions. For example if my route can return either a json object or null the result type will remove null from this union

**Comment by yusukebe** [comment]
Hi @niko-gardenanet 

Thanks for raising the issue. I've fixed it and released a new version, `v4.2.2,` which includes the change. Try it.
