### ISSUE TITLE
Error in execution of project Cloudflare workers

### ISSUE THREAD

**Issue by madhurx** [honojs/hono#2474]
### What version of Hono are you using?

4.2.2

### What runtime/platform is your app running on?

Cloudflare workers

### What steps can reproduce the bug?

npm run dev

### What is the expected behavior?

it should start a server

### What do you see instead?

![image](https://github.com/honojs/hono/assets/116882181/7299eb50-9993-4e96-916b-60fe15b005cd)

### Additional information

Check error in discussion also.
[Error in execution of project #2473
](https://github.com/orgs/honojs/discussions/2473)

**Comment by NicoPlyley** [comment]
I responded in the discussion as well. But I think it's important to note I found two instances of this error happening outside Hono as well

**Comment by yusukebe** [comment]
I think we can close this issue. Thanks.
