### ISSUE TITLE
onlySSG middleware not support Cloudflare worker

### ISSUE THREAD

**Issue by iflamed** [honojs/hono#2476]
### What version of Hono are you using?

4.2.2

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

Demo Code:
```typescript
import { Hono } from 'hono'
import { onlySSG } from 'hono/ssg'

const app = new Hono()

app.get('/', onlySSG(), (c) => {
  return c.html('<h2>Hello Hono!</h2>')
})

export default app
```

Run command: `npm run dev`, will got error.

### What is the expected behavior?

Miniflare start normal without error.

### What do you see instead?

✘ [ERROR] service core:user:pagereader: Uncaught Error: Disallowed operation called within global scope. Asynchronous I/O (ex: fetch() or connect()), setting a timeout, and generating random values are not allowed within global scope. To fix this error, perform this operation within a handler. https://developers.cloudflare.com/workers/runtime-apis/handlers/

    at null.<anonymous> (index.js:1521:29)

✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.

### Additional information

I has install the vite-ssg plugin with this command: `npm i -D vite @hono/vite-ssg`

**Comment by usualoma** [comment]
Hi @iflamed 

Thanks for the report!

There seems to be an error in the following line. We will look into how to fix it.
https://github.com/honojs/hono/blob/e428a053161e6c7f29d7e9776675fa1f7e7cceec/src/helper/ssg/middleware.ts#L5
