### ISSUE TITLE
Cloudflare worker SSG build failed with serveStatic use

### ISSUE THREAD

**Issue by iflamed** [honojs/hono#2478]
### What version of Hono are you using?

4.2.2

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

Demo code:
```typescript
import { Hono } from 'hono'
import { serveStatic } from 'hono/cloudflare-workers'
import manifest from '__STATIC_CONTENT_MANIFEST'

const app = new Hono()

app.get('/assets/*', serveStatic({ root: './', manifest }))

export default app
```

### What is the expected behavior?

No error, sucessfully build.

### What do you see instead?

When run npm run build, report an error with below:
```shell
error during build:
Error: Cannot find module '__STATIC_CONTENT_MANIFEST' imported from '/project/src/index.ts'
```

### Additional information

These command `npm run dev` and `npm run deploy` is normal without error.

**Comment by iflamed** [comment]
If you has seem issue, you can do this will fix it. There maybe a better way to do it. But I only found this.
Add a plugin to the `vite.config.ts` like below. @yusukebe  May be you can add this plugin to the ssg plugin.
```typescript
import { defineConfig } from 'vite'
import ssg from '@hono/vite-ssg'

function cloudflareManifest() {
  const virtualModuleId = '__STATIC_CONTENT_MANIFEST'
  const resolvedVirtualModuleId = '\0' + virtualModuleId

  return {
    name: 'cloudflare-manifest',
    resolveId(id: string) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId
      }
    },
    load(id: string) {
      if (id === resolvedVirtualModuleId) {
        return `import m from '__STATIC_CONTENT_MANIFEST';export default m;`
      }
    },
  }
}

export default defineConfig({
  plugins: [
    cloudflareManifest(),
    ssg({
      entry: 'src/index.ts'
    }),
  ],
})
```

**Comment by yusukebe** [comment]
Hi @iflamed !

Thanks for the suggestion. That seems to be good! However, honesty, I'm not very eager on this one. Because Workers Site which you are using with `__STATIC_CONTENT_MANIFEST` is now deprecated.

https://developers.cloudflare.com/workers/configuration/sites/

Therefore, I would recommend using Cloudflare Pages instead of creating this.

**Comment by iflamed** [comment]
> Hi @iflamed !
> 
> Thanks for the suggestion. That seems to be good! However, honesty, I'm not very eager on this one. Because Workers Site which you are using with `__STATIC_CONTENT_MANIFEST` is now deprecated.
> 
> https://developers.cloudflare.com/workers/configuration/sites/
> 
> Therefore, I would recommend using Cloudflare Pages instead of creating this.

It's OK, I will use `Pages`  in my next project too.
