### ISSUE TITLE
Typesafe enum query param in RPC client?

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#2481]
### Discussed in https://github.com/orgs/honojs/discussions/2475

<div type='discussions-op-text'>

<sup>Originally posted by **branislav-brincko** April  8, 2024</sup>
This is my backend: 

![image](https://github.com/honojs/hono/assets/118365024/fa8f6652-24d2-47ec-918a-3cbcdbd7c65f)

And this is my frontend: 

![image](https://github.com/honojs/hono/assets/118365024/4355660c-8ad5-46d7-9206-1d74ae90aff2)

Is there a way how to make "order" on the frontend inferred not as string | string[] but as a "asc" | "desc"? (In other words, how to make typescript check if I passed the correct value?) 
</div>

**Comment by ViewableGravy** [comment]
Noticed this as well. As far as I can tell, the only thing that actually has proper client side type safety is json, everything else seems to just infer as `string | string[]`. Looking forward to this being fixed

**Comment by azezsan** [comment]
is this a difficult issue or it hasn't been attempted?

**Comment by yusukebe** [comment]
This is a Zod Validator - side issue. I may fix it.

**Comment by yusukebe** [comment]
Hi all.

This may be resolved with the new version [@hono/zod-validator@0.4.1](https://github.com/honojs/middleware/releases/tag/%40hono%2Fzod-validator%400.4.1). Please try it.

**Comment by danieljvdm** [comment]
Hey, is this actually fixed? All my query params are typed as `string | string[] | undefined` still - E.g.

![Image](https://github.com/user-attachments/assets/5ac78c0b-91c3-4e2a-90ad-215ce395e7bd)

So I have to coerce myself:

```
const queryFn = async (args: QueryArgs) => {
  const response = await fetcher.posts.$get({
    query: {
      pageSize: String(10),
      ...(args.after && { after: args.after }),
    },
  });
```

Obviously query params _are_ always strings but I'd expect the hono client to do this coercion from number to string for me and respect the types that the server has for the query params. E.g.:

```
export const paginationSchema = z
  .object({
    page: z.coerce.number().int().positive().optional().default(defaultPage),
    pageSize: z.coerce.number().int().positive().optional().default(defaultPageSize),
    after: z.string().nullable().optional(),
    before: z.string().nullable().optional(),
  })
  .default({ page: defaultPage, pageSize: defaultPageSize, after: null, before: null });
```

**Comment by Pyakz** [comment]
<img width="476" height="252" alt="Image" src="https://github.com/user-attachments/assets/7793bfcc-31a3-42ab-8db2-3b555e52b976" />

any updates?

**Comment by GrahamQuan** [comment]
still not correct types on `"@hono/zod-validator": "^0.7.5",`

**Comment by yusukebe** [comment]
It seems to work well. If not, can you provide a minimal project to reproduce it?

```ts
import { Hono } from 'hono'
import * as z from 'zod'
import { zValidator } from '@hono/zod-validator'

const app = new Hono()

const schema = z.object({
  order: z.enum(['asc', 'desc'])
})

app.get('/', zValidator('query', schema), (c) => {
  const { order } = c.req.valid('query')
  return c.text(`Order is ${order}`)
})

export default app
```

<img width="866" height="554" alt="Image" src="https://github.com/user-attachments/assets/42da8f22-4b50-4fe0-85ea-ad9f82f5b4d7" />

**Comment by GrahamQuan** [comment]
`c.req.valid()` is correct typing

`export type AppType = typeof app;` for rpc is not when some field is enum

```ts
// client side
const testGetBlogs = async () => {
  const res = await client.api.blogs.$get({
    query: {
      pageNum: '1', // should be number; but got (property) sort?: string | string[] | undefined
      pageSize: '10', // should be number; but got (property) sort?: string | string[] | undefined
      sort: 'new', // should be 'new' | 'old'; but got (property) sort?: string | string[] | undefined
    },
  });
  const data = await res.json();
  console.log(JSON.stringify(data, null, 2));
};

// server side
export const blogQuerySchema = z.object({
  pageNum: z.coerce.number().int().positive().default(1),
  pageSize: z.coerce.number().int().positive().default(10),
  sort: z.enum(['new', 'old']).default('new'),
  filter: z.string().optional(),
});
```

not really a minimal project, but my code for learning hono
https://github.com/GrahamQuan/learn-hono-drizzle-sql

client side test file: `src/__test__/hono-client.test.ts`
server file: `src/routes/blogs/blogs.schema.ts`

**Comment by yusukebe** [comment]
@GrahamQuan 

It works well on the client as well.

<img width="1220" height="1090" alt="Image" src="https://github.com/user-attachments/assets/08705b5b-ae93-45ed-88fb-ab7d0107074a" />

**Comment by GrahamQuan** [comment]
@yusukebe 

your demo is correct, works on my editor

i found the issue, when `z.number()` and `z.enum()` together, types not correct

```ts
import { zValidator } from '@hono/zod-validator';
import { Hono } from 'hono';
import { hc } from 'hono/client';
import * as z from 'zod';
import { AppEnv } from '@/context';

// 1. correct types
// const schema = z.object({
//   page: z.string(),
//   orderBy: z.enum(['new', 'old']).default('new'),
// });

// 2. correct types
// const schema = z.object({
//   page: z.string(),
//   orderBy: z.enum(['new', 'old']),
// });

// 3. error types
// const schema = z.object({
//   page: z.number(),
//   orderBy: z.enum(['new', 'old']),
// });

// 4. error types
const schema = z.object({
  page: z.number(),
  orderBy: z.enum(['new', 'old']).default('new'),
});

const router = new Hono<AppEnv>().get('/', zValidator('query', schema), async (c) => {
  const query = c.req.valid('query');
  return c.json({ message: query.orderBy });
});

const app = new Hono<AppEnv>().route('/api', router);

const client = hc<typeof app>('http://localhost:3000');

const res = await client.api.$get({
  query: {
    page: '1',
    orderBy: 'new',
  },
});

console.log(res.json());
```

i guess thats why my old schema is wrong types
```ts
export const blogQuerySchema = z.object({
  pageNum: z.coerce.number().int().positive().default(1),
  pageSize: z.coerce.number().int().positive().default(10),
  sort: z.enum(['new', 'old']).default('new'),
  filter: z.string().optional(),
});
```

**Comment by yusukebe** [comment]
@GrahamQuan 

The problem may be fixed in the latest version of Zod Validator `@hono/zod-validator@0.7.6`.

**Comment by GrahamQuan** [comment]
@yusukebe 

i upgrade to `"@hono/zod-validator": "^0.7.6",`

my zod: `"zod": "^4.1.12"`

z.enum() is correct now
z.number() still not number, is `string | string[]`
z.string() will be `string`, if we set `page: z.string()`


<img width="864" height="532" alt="Image" src="https://github.com/user-attachments/assets/a504e053-65a6-490b-b8f0-b1343ff776ec" />

**Comment by yusukebe** [comment]
@GrahamQuan 

It's expected behavior. The `number` will be `string | string[]`. Because the client can send only strings as query parameters. See: https://hono.dev/docs/guides/rpc#path-parameters

**Comment by muezz** [comment]
@yusukebe Coming from tRPC, this seems like a simple problem to resolve. I am sure it would be relatively simple to use something like `superjson`. Or maybe we could optionally pass custom serializers and deserializers to `hc` and it could use some clever defaults.

For instance, it should be the responsibility of the dev to ensure that zod is able to parse `"10"` via `z.coerce.number<number>()`. Hono can just throw a validation error otherwise.
