### ISSUE TITLE
`serve-static` middleware for ES Module mode

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#249]
Now, the `serve-static` middleware is enabled only in Service Worker mode. #247 
We have to make the `serve-static` supports ES module mode.
But, in ES module mode, `__STATIC_CONTENT_MANIFEST` is not global variable. We have to `import`:

```ts
import manifest from '__STATIC_CONTENT_MANIFEST'
```

So, we want to do

```
Service Workers mode --> get variables from `__STATIC_CONTENT_MANIFEST`
ES module mode --> do import `__STATIC_CONTENT_MANIFEST`
```

But, it's difficult to switch the behavior, because dynamic import is not supported Cloudflare Workers.

I have the strategy. Emit two pattern js file: `js` and `mjs`. And write like this to `package.json`

```json
    "./serve-static": {
      "require": "./dist/middleware/serve-static/index.js",
      "import": "./dist/middleware/serve-static/index.mjs"
    },
```

Then...

```
`js` ---> will be loaded Service Worker mode,
`mjs` --->  will be loaded ES module mode
```

I think we can make it depending on the TS settings.

**Comment by charl-kruger** [comment]
can you show an example of how to use serve static now with the import manifests please?

**Comment by yusukebe** [comment]
Hm...

Both `Service Worker`/`ES module` are calling `.mjs`.

**Comment by yusukebe** [comment]
There are two ways or both:

1. `import`*__STATIC_CONTENT_MANIFEST* in your script.

```ts
import { serveStatic } from 'hono/serve-static'
import manifest from '__STATIC_CONTENT_MANIFEST'

const app = new Hono()

app.use('*', serveStatic({ root: './', manifest: manifest }))
export default app
```

2. make another middleware.

```ts
import { serveStatic } from 'hono/serve-static.esm'

const app = new Hono()

app.use('*', serveStatic({ root: './' }))
export default app
```
