### ISSUE TITLE
How to send HTTP requests? in @cloudflare/workers

### ISSUE THREAD

**Issue by maoweifan** [honojs/hono#2526]
### What version of Hono are you using?

4.2.5

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

AxiosError: There is no suitable adapter to dispatch the request since :
  - adapter xhr is not supported by the environment
  - adapter http is not available in the build

### What is the expected behavior?

I need to send HTTP requests to other servers, and I am planning to use Axios, but it has failed. What do I need to do to send HTTP requests? (Note: I am sending HTTP requests to other servers)

**Comment by ktKongTong** [comment]
maybe you can check the [cloudflare worker's documentation about fetch api](https://developers.cloudflare.com/workers/runtime-apis/fetch/) first.

cloudflare worker is not running in normally node or browser env. some libraries can't functioning as expected.
