### ISSUE TITLE
onError not called for async errors

### ISSUE THREAD

**Issue by spiree** [honojs/hono#2533]
### What version of Hono are you using?

4.2.3

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

The URL /sync_error triggers the onError() function. 
The URL /async_error doesn't. It does result in a HTTP 500 response.

const app = new Hono();
app.onError((, c) => c.text('caught error', 200));
app.get('/sync_error', () => {  throw new Error('Error'); });
app.get('/async_error', async () => Promise.reject('Error'));

### What is the expected behavior?

That onError is also called for async functions.

### What do you see instead?

For async functions the onError is not called. Instead a HTTP 500 is returned.

**Comment by sor4chi** [comment]
Hi, @spiree. How about this changes? This worked right for me.

```diff
- app.get('/async_error', async () => Promise.reject('Error'));
+ app.get('/async_error', async () => Promise.reject(new Error('Error')));
```
