### ISSUE TITLE
Modify request

### ISSUE THREAD

**Issue by fzn0x** [honojs/hono#2538]
### What is the feature you are proposing?

How to modify request? I want to sanitize input without zod or hono validator.

```ts
app.use(async (c, next) => {
  const json = await c.req.json();
  for (let key in json) {
    if (json.hasOwnProperty(key)) {
      if (typeof json[key] === "string") {
        json[key] = sanitize.parse(json[key]);
      }
    }
  }

  // How to modify request?
  c.setJson(json);

  await next();
});
```

**Comment by NicoPlyley** [comment]
Request cannot/should not be updated. In web standards the Request object is immutable.

You can use [context variables](https://hono.dev/api/context#set-get) instead when you update data and send it to your route that way. 

If you have other questions, please post them in the discussions tab or join the Discord

**Comment by sor4chi** [comment]
How about this?
```ts
app.use(async (c, next) => {
  const json = await c.req.json();
  for (let key in json) {
    if (json.hasOwnProperty(key)) {
      if (typeof json[key] === "string") {
        json[key] = sanitize.parse(json[key]);
      }
    }
  }

  c.set("sanitized", jsonSanitize);
  await next();
});

app.json("/", (c) => {
  const sanitized = c.var.sanitized;
  // ...
});
```

**Comment by fzn0x** [comment]
> Request cannot/should not be updated. In web standards the Request object is immutable.
> 
> You can use [context variables](https://hono.dev/api/context#set-get) instead when you update data and send it to your route that way.
> 
> If you have other questions, please post them in the discussions tab or join the Discord

I think it's common to sanitize Request inputs before the real request.

I use Middleware for DRY.

**Comment by fzn0x** [comment]
> How about this?
> 
> ```ts
> app.use(async (c, next) => {
>   const json = await c.req.json();
>   for (let key in json) {
>     if (json.hasOwnProperty(key)) {
>       if (typeof json[key] === "string") {
>         json[key] = sanitize.parse(json[key]);
>       }
>     }
>   }
> 
>   c.set("sanitized", jsonSanitize);
>   await next();
> });
> 
> app.json("/", (c) => {
>   const sanitized = c.var.sanitized;
>   // ...
> });
> ```

Is it foolproof from memory leaks?

It changed the way we get the data too.

**Comment by NicoPlyley** [comment]
It may be common and libraries like Express, will let you do it. I don't speak for Hono, but based off what I know, Hono follows web standards which do state the Request object is read only. Correct me if I'm wrong @yusukebe 

The option I gave which is the same as the example @sor4chi provided would be your best option.

**Comment by yusukebe** [comment]
Hi @fzn0x 

This method is used internally by Hono's Validator. We do not recommend that users use it directly, but you may do it this way.

```ts
app.use(async (c, next) => {
  const json = await c.req.json()

  // ...

  c.req.bodyCache.json = modifiedJson
  await next()
})
```

**Comment by fzn0x** [comment]
> Hi @fzn0x
> 
> This method is used internally by Hono's Validator. We do not recommend that users use it directly, but you may do it this way.
> 
> ```ts
> app.use(async (c, next) => {
>   const json = await c.req.json()
> 
>   // ...
> 
>   c.req.bodyCache.json = modifiedJson
>   await next()
> })
> ```

Cool!!

**Comment by fzn0x** [comment]
Thanks for anyone participated in this issue.
