### ISSUE TITLE
A way to pass RequestInit on hc instance

### ISSUE THREAD

**Issue by AlexisWalravens** [honojs/hono#2542]
### What is the feature you are proposing?

Hi,

I'm using NextJS and I would like to be able to pass the `RequestInit` param of the fetch instance on individual calls.

## Why ?
Because NextJS overrides `fetch`'s `RequestInit` type to also include the `next` key to handle cache at the fetch level:
```ts
fetch('https://...', {
  next: { 
    revalidate: 3600,
    tags: ['some', 'tags'],
    cache: '...'
  }
})
```

> https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#time-based-revalidation

For now we only can override the whole fetch function, but I would like to be able to only override it's params with maybe something like this:
```ts
  const res = await hc.my.request.$get(undefined, {
    fetchOptions: {
      next: {
        revalidate: 3600
      }
    }
  })
```
It makes sense to me that since `hc` is just a fetch wrapper around `fetch` we should be able to pass it the same params.

### For reference
I'm used to use [`ofetch`](https://github.com/unjs/ofetch) (which is **not** NextJs related) which is a wrapper of fetch with some built in features like retries, errors on non 200/300 statusCode, json parsing, etc...

And as [`ofetch`](https://github.com/unjs/ofetch) just extends `RequestInit` params from `fetch` I can use the `next` key directly in it just like I would with the basic `fetch`:

```ts
  const res = await ofetch('https://...', {
    method: 'GET',
    next: {
      revalidate: 3600
    }
  }) 
```

Maybe we could extends `RequestInit` and exclude the `method` & `body` keys since they are already defined by the hc method.

Thanks for reading me,
And Keep up with the good stuff 🔥 !

**Comment by AlexisWalravens** [comment]
I think it should work yes!

For reference, here is how NextJs override `RequestInit`
https://github.com/vercel/next.js/blob/850f4b9d8e31601ff9383fd11d79f67650fcc9e8/packages/next/types/global.d.ts#L25

**Comment by yusukebe** [comment]
@AlexisWalravens 

Sorry for the late response.

I've thought it. A method like `client.index.$get` can receive the `fetch` option, so perhaps you can pass the `next` option though the type warning is thrown. Can try it?

```ts
client.index.$get(
  {},
  {
    fetch(input, requestInit) {
      return fetch(input, {
        ...requestInit,
        next: {
          revalidate: 3600,
        },
      })
    },
  }
)
```

**Comment by AlexisWalravens** [comment]
It works, but I think having to redeclare the entire fetch function every time is hurting the DX.

Also one more thing since we are talking about fetch, as I said above I'm used to use `ofetch` so I don't have to `await res.json()` or check if `res.ok` is true in case of 4xx/5xx responses.

I would like to propose a `fetchRequester` parameter to the hono client init:

That `fetchRequester` would be a function that would be used to make the requests instead of the default fetch.
And would of type:
```ts
type Requester<C = Record<string, never>> = <TResponse = unknown>(
  input: RequestInfo,
  init: RequestInit,
  options?: C
) => Promise<TResponse>
```

Here I would create fetchRequester that would use ofetch instead of fetch
```ts
type ExcludedFetchOptions<ExtraTypes = Record<string, unknown>> = Omit<
  FetchOptions,
  'method' | 'body' | 'responseType'
> &
  ExtraTypes

const fetchRequester: Requester = async <TResponse = unknown>(
  input: RequestInfo,
  init: RequestInit,
  options?: ExcludedFetchOptions
) => {
  return await ofetch<TResponse>(input, {
    ...init,
    ...options
  })
}

const client = hc<AppType>('https://api.example.com', {
  fetchRequester: fetchRequester
})
```

Where `options` would be typed directly from the `fetchRequester`'s `options` parameter
So here it would be typed as `ExcludedFetchOptions` instead of `RequestInit` since it's what I defined in the `fetchRequester` function
```ts
const res = await hc.my.request.$get({}, options)
```

// If not fetchRequest is passed, it will use the default fetch
const client = hc<AppType>('https://api.example.com')
const res = await hc.my.request.$get({}, options)
// and `options` in each endpoint request would just be typed as `RequestInit`
// Also if options is directly a `RequestInit` object, headers can be passed directly to it instead of a separate object


// Here I used ofetch, but it could be any other library that makes requests, like axios, ky, etc.. Since we are able to get everything we need from the `RequestInfo` and `RequestInit` parameters


// The only thing missing now, would the ability to pass headers to the hono client initialization.
// But we could make the params of `hc` like this:
type ExcludedRequestInit<ExtraTypes = Record<string, unknown>> = Omit<
  RequestInit,
  'method' | 'body' | 'responseType'
> &
  ExtraTypes

type HonoClientParams = {
  fetchRequester?: Requester
  requestInit?: ExcludedRequestInit
}

const hc = <T>(basePath: string, params?: HonoClientParams) => {
  // ...
}

// And then we could pass headers like this:
const client = hc<AppType>('https://api.example.com', {
  requestInit: {
    headers: {
      Authorization: `Bearer ${token}`
    }
  }
})

// In that way the requestInit from the hc init would be the default passed to each request, but they could be overriden in each request if needed

**Comment by yusukebe** [comment]
Hi @AlexisWalravens 

Thank you for suggesting and explaining!

> It works, but I think having to redeclare the entire fetch function every time is hurting the DX.

The `hc` function can receive `fetch` option which can set custom `fetch` method when `client` is initialized. Is it not enough?

```ts
const client = hc<typeof app>('http://localhoste', {
  fetch: (input, requestInit) => {
    return fetch(input, {
      ...requestInit,
      next: {
        revalidate: 3600,
      },
    })
  },
})
```

> Also one more thing since we are talking about fetch, as I said above I'm used to use `ofetch` so I don't have to `await res.json()` or check if `res.ok` is true in case of 4xx/5xx responses.

Does this mean that if you use `ofetch` as `fetchRequester`, the `res` will not be `fetch` s Response? What will be assigned?

```ts
const res = await hc.my.request.$get({}, options) // If fetchRequester uses ofetch, res is not Response??
```

We designed the client by `hc`, which should return `Response` for `fetch` compatibility.

**Comment by devjmetivier** [comment]
@yusukebe Found this Issue with the same needs as @AlexisWalravens.

I find that your suggestions satisfy the need, but I wonder if there's some sort of higher order abstraction that could make this easier? Like a separate hono client that accepts Next's custom fetch options and passes them downstream?

```ts
export const client = hcNext<ApiType>('[baseUrl]');

//...

await client.your.route.here.$get({ query: {} }, { next: { tags: [...] } })
```

**Comment by yusukebe** [comment]
Hi @devjmetivier and @AlexisWalravens !

#2592 introduced `init` option to each method:

```ts
const res = await client.about.me.$get(
  {},
  {
    init: {
      next: {
        revalidate: 3600,
      },
    },
  }
)
```

Does it not satisfy your request?

**Comment by devjmetivier** [comment]
> #2592 introduced `init` option to each method:

Works perfectly! Thanks 😁

**Comment by yusukebe** [comment]
@devjmetivier 

Goood! I think we can close this issue. If you have any problem with this, feel free to re-open it.

**Comment by Innei** [comment]
@AlexisWalravens Hi.

How are you using ofetch but the TypeScript type is correct.

There is no `json()` method on the response to ofetch, as you know.

``
const data = await ofetch<Res>() // data is final response type `Res`.

data.json() // error
```

But in fetch we need to invoke `json()` manually. 

In hono hc, fetch is used by default instead of ofetch, e.g. with a call like this

``
await hc.subscriptions.$get({ query: { view: String(view) } })
```

Its return type is `ClientResponse<InferedType>` but if I were to use ofetch, this would be the unwrapped type, which would be `InteredType`.

Translated with DeepL.com (free version)

**Comment by kpyszkowski** [comment]
So as long as I understand, Hono Client uses the `fetch` function under the hood so in NextJS environment it uses its' `fetch` implementation. We have NextJS caching out of the box?

**Comment by feliche93** [comment]
> So as long as I understand, Hono Client uses the `fetch` function under the hood so in NextJS environment it uses its' `fetch` implementation. We have NextJS caching out of the box?

yeah I think this is correct and how I understand it.

@AlexisWalravens do you have some example of how `hc` client can be wrapped with `ofetch`.

I am currently at the same path that I wanna reduce the code down from this res ok check:

```
  const res = await honoAdminClient.api.v1.admin.onboarding.surveys.$get(
    {
      query: {
        page: '1',
        pageSize: '10',
      },
    },
    {
      // @ts-ignore
      next: {
        tags: ['onboarding-surveys'],
        revalidate: 3600, // Cache for 1 hour
      },
    },
  )

  if (!res.ok) {
    throw new Error('Failed to fetch onboarding surveys')
  }

  const onboardingSurveys = await res.json()

```

to:

```
  const data = await honoAdminClient.api.v1.admin.onboarding.surveys.$get(
    {
      query: {
        page: '1',
        pageSize: '10',
      },
    },
    {
      // @ts-ignore
      next: {
        tags: ['onboarding-surveys'],
        revalidate: 3600, // Cache for 1 hour
      },
    },
  )
```

I saw @Innei you also had a look at this, do you have some example of how you implemented itß

**Comment by fortezhuo** [comment]
@feliche93 / @Innei 

```
import { $fetch } from "ofetch"

export const api = hc<AppRouter>("endpoint", {
  fetch(input, requestInit, _, __) {
    return $fetch(input instanceof URL ? input.toString() : input, requestInit)
  },
})
```

```
const result = await api.person.save.$post({
        json: {
          name:"lorem"
        },
      })

console.log(result)
type Result = typeof result // ClientResponse
```
The result will return correctly, but typescript type not happy due to result always refers to ClientResponse type.

@yusukebe
Any suggestion how to correct typescript type when we use another library like ofetch / ky for fetch ?

**Comment by 1yasa** [comment]
+1 Is there a method to solve type problems?

**Comment by fortezhuo** [comment]
> +1 Is there a method to solve type problems?
@1yasa 
I forgot to update

We can do like this.. using ky library

```
import ky from "ky"

export const fetch = ky.extend({
  hooks: {
    afterResponse: [
      async (_, __, response: Response) => {
        if (response.ok) {
          return response
        } else {
          throw await response.json()
        }
      },
    ],
  },
})

export const api = hc<ApiRouter>(`https://endpoint/api/`, {
  fetch,
  init: { credentials: "include" },
})
```
Still ugly, because we still need to call ```await res.json()``` but we don't need to crosscheck response.ok anymore.

Hope it helps

**Comment by 1yasa** [comment]
> > +1 Is there a method to solve type problems?
> 
> I forgot to update @1yasa We can do like this.. using ky library
> 
> ```
> import ky from "ky"
> 
> export const fetch = ky.extend({
>   hooks: {
>     afterResponse: [
>       async (_, __, response: Response) => {
>         if (response.ok) {
>           return response
>         } else {
>           throw await response.json()
>         }
>       },
>     ],
>   },
> })
> 
> export const api = hc<ApiRouter>(`https://endpoint/api/`, {
>   fetch,
>   init: { credentials: "include" },
> })
> ```
> 
> Still ugly, because we still need to call `await res.json()` but we don't need to crosscheck response.ok anymore.
> 
> Hope it helps

Thanks reply, my idea is that there is no need for res.json(), how can I inform Hono of this situation? In fact, ofetch can already achieve this:

```ts
import { hc } from 'hono/client'

import { BASE_URL } from './env'
import { request } from './ofetch'

import type { Api } from '@server/apis'
import type { FetchOptions, FetchResponse } from 'ofetch'

type ExcludedFetchOptions<ExtraTypes = Record<string, unknown>> = Omit<
	FetchOptions,
	'method' | 'body' | 'responseType'
> &
	ExtraTypes

type Requester<C = Record<string, never>> = <TResponse = unknown>(
	input: RequestInfo | URL,
	init?: RequestInit,
	options?: C
) => Promise<FetchResponse<TResponse>>

const fetchRequester: Requester = <TResponse = unknown>(
	input: RequestInfo | URL,
	init?: RequestInit,
	options?: ExcludedFetchOptions
) => {
	return request.raw<TResponse>(input as string, {
		...init,
		...options
	})
}

export default hc<Api>(BASE_URL + '/api', { fetch: fetchRequester })
```

ofetch request:

```ts
import to from 'await-to-js'
import { ofetch } from 'ofetch'

import { goLogin } from './auth'
import { BASE_URL } from './env'

import type { FetchContext } from 'ofetch'

const onRequestError = (res: FetchContext) => {
	const { response, error } = res
	const { status } = response!

	$message.error(`${status}: ${error?.message}`)
}

const onResponseError = async (res: FetchContext) => {
	const response = res.response!
	const { status } = response

	let err: unknown

	const [err_json, res_json] = await to(response.clone().json())

	if (err_json) {
		err = await response.clone().text()
	} else {
		err = res_json
	}

	switch (status) {
		case 401:
			goLogin()

			break
		case 429:
			$message.error($t('app.too_many_req'))

			break
		case 400:
			if (Array.isArray(err)) {
				err.forEach(item => {
					const data = item.error.data

					Object.keys(data).forEach(key => {
						$message.error(`${key}: ${data[key]}`)
					})
				})
			}

			break
		default:
			$message.error(err as string)
			break
	}

	return Promise.reject(res)
}

export const request = ofetch.create({
	responseType: 'stream',
	onRequestError,
	onResponseError
})

export const api = ofetch.create({
	baseURL: BASE_URL + '/api',
	onRequestError,
	onResponseError
})
```
