### ISSUE TITLE
SyntaxError: Unexpected end of JSON input on return bodyCache[key] = raw[key]();

### ISSUE THREAD

**Issue by fzn0x** [honojs/hono#2544]
### What version of Hono are you using?

^4.2.6

### What runtime/platform is your app running on?

Bun 1.1.3

### What steps can reproduce the bug?

You can try modify request like this to get this error.

```ts
import { z } from "zod";

const escapeHtml = (text: string) => {
  const map: Record<string, string> = {
    "<": "&lt;",
    ">": "&gt;",
    "&": "&amp;",
    "'": "&#39;",
    '"': "&quot;",
    "/": "&#47;",
  };
  return text.replace(/[<>&'"\/]/g, (char: string): string => map[char]);
};

const safeHtmlString = z.string().transform((str) => escapeHtml(str));

export default safeHtmlString;
```

```ts
app.use(async (c, next) => {
  const json = await c.req.json();
  for (let key in json) {
    if (json.hasOwnProperty(key)) {
      if (typeof json[key] === "string") {
        json[key] = sanitize.parse(json[key]);
      }
    }
  }

  // Modify request like hono/validator
  c.req.bodyCache.json = json;

  await next();
});
```

### What is the expected behavior?

json request modified and no error while running server with Bun.

### What do you see instead?

79 |           return await new Response(body)[key]();
80 |         })();
81 |       }
82 |     }
83 |
84 |     return bodyCache[key] = raw[key]();
                                 ^
SyntaxError: Unexpected end of JSON input

**Comment by fzn0x** [comment]
I suspect it related with `request.clone()` issue from Bun because it also returns `SyntaxError: Unexpected end of JSON input`,

https://github.com/oven-sh/bun/pull/6468

**Comment by yusukebe** [comment]
Hi @fzn0x 

Maybe the body is blank or not a valid JSON string. So, you have to handle the error yourself.

**Comment by fzn0x** [comment]
It's happen after I call `const json = await c.req.json();`

@yusukebe

**Comment by fzn0x** [comment]
Is that did request cloning underhood?
