### ISSUE TITLE
Regression caused by multiHeaderValue handling on Lambda

### ISSUE THREAD

**Issue by kbrandwijk** [honojs/hono#2550]
### What version of Hono are you using?

4.2.5

### What runtime/platform is your app running on?

AWS

### What steps can reproduce the bug?

https://github.com/honojs/hono/pull/2494 introduced the handling of multiHeaderValues. However, this seemed to have caused header duplication. On AWS, using API Gateway, a header is put both in `headers` and in `multiValueHeaders` when using proxy integration (even single value ones). The handling introduced in #2494 adds both to the headers array, causing duplicates. As a result, header values are concatenated with commas.

Example output from API Gateway test console:
```
Wed Apr 24 00:49:47 UTC 2024 : Endpoint request body after transformations: {"resource":"/{proxy+}","path":"/follows","httpMethod":"GET","headers":{"test":"123"},"multiValueHeaders":{"test":["123"]},"queryStringParameters":null,"multiValueQueryStringParameters":null,"pathParameters":{"proxy":"follows"},"stageVariables":null,"requestContext":
```
As you can see, the same header is in both collections, even though provided only once.

### What is the expected behavior?

No header value duplication.

### What do you see instead?

Duplicate header values:

```js
c.req.Header("test") // value: '123,123'
```

**Comment by ShaneYu** [comment]
Yes, we have also experienced this and is a particular issue as we're using the JWT middleware. In thew JWT middleware it validates that the `Authorization` header is a string matching `Bearer <token>` but splitting on space and checking the length is 2. This of course fails as the header value now contains two copies of the same value and thus has a length of 4 when splitting.

https://github.com/honojs/hono/blob/main/src/middleware/jwt/index.ts#L33

To work around this particular issue, we're using the following "hacky" code in a wrapper middleware before it runs the JWT middleware.

```ts
c.req.raw.headers.set('Authorization', c.env.event.headers['Authorization']);
```

**Comment by watany-dev** [comment]
Thanks for your comment. I will fix this.

**Comment by Amorim33** [comment]
Same bug here

Maybe @ShaneYu 's approach would be good

**Comment by hanneswidrig** [comment]
I'm also facing issues related to this bug.
