### ISSUE TITLE
Middleware order of definition

### ISSUE THREAD

**Issue by mathysth** [honojs/hono#2557]
### What version of Hono are you using?

4.2.7

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

I'm not sure if it's a bug but I don't really understand why it work this way:
Middleware are used to run code before and after execution as said [here](https://hono.dev/concepts/middleware)
So for me no matter where I create a global Middleware it should work on all routes if i'm not mistaking.

When I was trying to add my middleware I did something like this and it was not working.
Then I created this sample and when I was defining my middleware before the get route, it was working. 
I just wanted to know if it was a normal behavior
```ts
import { Hono } from 'hono';
import { rateLimiter } from 'hono-rate-limiter';

const app = new Hono()
const limiter = rateLimiter({
  windowMs: 60 * 1000, // 1 minute
  limit: 5,
  standardHeaders: "draft-6", // draft-6: `RateLimit-*` headers;
  keyGenerator: (c) => {
    return "<unique_key>";
  }
});

app.get('/', (c) => {
  return c.text('Hello Hono!')
})
app.use(limiter)

export default {
  port: 3002,
  fetch: app.fetch,
} 
```

**Comment by NicoPlyley** [comment]
Add the `app.use(limiter)` above the routes and that should fix it

**Comment by mathysth** [comment]
I know but my question was why I am forced to `.use` before the `.get` when I globally set my middleware even if it's after the route definition

**Comment by NicoPlyley** [comment]
I see, I would assume it's based off how Hono registers your routes. Because it would go line by line the routes would already be registered before it sees the middleware

**Comment by mathysth** [comment]
Thanks for the info I think it would be cool to add a feature like this.

**Comment by NicoPlyley** [comment]
That would introduce breaking changes though. If someone is using it in between routes to only effect the routes under it
