### ISSUE TITLE
c.Var types unknown

### ISSUE THREAD

**Issue by janat08** [honojs/hono#2559]
### What version of Hono are you using?

4.2.7

### What runtime/platform is your app running on?

CF Workers

### What steps can reproduce the bug?

`
  const redirectHtmx: MiddlewareHandler<{
    Variables: {
      redirectHtmx: (url: string) => Response
    }
  }> = async (c, next) => {
    c.set('redirectHtmx', (url: string) => new Response(null, {headers: {'HX-Location': url}}))
    await next()
  }
  app.use('*', redirectHtmx)

c.var.redirectHtmx('/page') is of type unkown
`

### What is the expected behavior?

https://hono.dev/api/context#var

### What do you see instead?

 is of type unkown on additional methods

**Comment by sor4chi** [comment]
I think you have to write the env generics to Hono instance.
![Screenshot 2024-04-25 at 15 48 15](https://github.com/honojs/hono/assets/80559385/1422daed-8865-44cc-a6fb-0136521284e9)

**Comment by janat08** [comment]
Makes sense, but then the docs are wrong.

**Comment by sor4chi** [comment]
That's true. I'll fix it later!

**Comment by sor4chi** [comment]
Hi, @janat08 
The website has been updated! Thanks!

**Comment by yusukebe** [comment]
@janat08 @sor4chi Thanks!

Closing the issue.
