### ISSUE TITLE
RPC does not work with optional parameter

### ISSUE THREAD

**Issue by NamesMT** [honojs/hono#2575]
### What version of Hono are you using?

4.2.9

### What runtime/platform is your app running on?

Node v20

### What steps can reproduce the bug?

Declare multiple routes, include one route using optional parameter like `/api/:a/:b?`

### What is the expected behavior?

RPC mode should work normally

### What do you see instead?

RPC got fallback to match any string, with no known HTTP methods 
![image](https://github.com/honojs/hono/assets/23612546/6dc54e67-d522-4f4a-8b54-ad033ba0b712)

**Comment by yusukebe** [comment]
This is fixed by #2576
