### ISSUE TITLE
`c.text()` is not typed for RPC

### ISSUE THREAD

**Issue by NamesMT** [honojs/hono#2578]
### What version of Hono are you using?

4.2.9

### What runtime/platform is your app running on?

Node v20

### What steps can reproduce the bug?

Declare a route with a return of `c.text('anything')`

### What is the expected behavior?

The `Response` type should intersect `TypedResponse<text>`

### What do you see instead?

The `Response` is not typed

### Additional information

Image:
![image](https://github.com/honojs/hono/assets/23612546/7b43eff8-e813-4e3d-bdd3-6bb9925c17f0)

**Comment by yusukebe** [comment]
Fixes by #2581. Thanks!
