### ISSUE TITLE
Allow stream helper arguments callback and onError to be synchronous functions

### ISSUE THREAD

**Issue by sor4chi** [honojs/hono#2586]
### What is the feature you are proposing?

Current:

![Screenshot 2024-05-02 at 3 42 21](https://github.com/honojs/hono/assets/80559385/ae079538-8f5e-486c-ae3c-b49bd9e51175)
![Screenshot 2024-05-02 at 3 42 29](https://github.com/honojs/hono/assets/80559385/cbfffa04-78d6-4504-9df6-d4912f9a5485)

How to resolve:

Simply change `Promise<void>` to `Promise<void> | void`

If it is good, I'll start developing it.

**Comment by yusukebe** [comment]
Hi @sor4chi 

> Simply change `Promise<void>` to `Promise<void> | void`

Though I might not understand what you meant completely, I think `cb` has to `await`, so it should be `Promise<void>`:

https://github.com/honojs/hono/blob/main/src/helper/streaming/stream.ts#L13

**Comment by sor4chi** [comment]
Oops, I forgot that stream.write is asynchronous to begin with. Sorry!
