### ISSUE TITLE
Add support for AbortController signal in hono/client

### ISSUE THREAD

**Issue by davbauer** [honojs/hono#2593]
### What is the feature you are proposing?

I would like to be able to abort ongoing requests made through the hono client by using the AbortController. Currently, there is no way to pass the AbortController.signal to the requests made by the client.
Supporting the AbortController would allow us to cancel ongoing requests when needed, providing more control over the request lifecycle.
For example, I should be able to do something like this:

```ts
const abortController = new AbortController();
const response = await hClient.jwt.someEndpoint.$post({
  json: { /* request body */ },
  signal: abortController.signal, // Pass the signal here
});

// Later, if needed:
abortController.abort(); // This would cancel the ongoing request
```

By adding support for the AbortController.signal, we can improve the flexibility and control over requests made through the hono client.

**Comment by yusukebe** [comment]
Hi @davbauer 

Thank you for the issue. This will be resolved by #2592 and will be merged soon. What do you think?

**Comment by davbauer** [comment]
> Hi @davbauer 
> 
> Thank you for the issue. This will be resolved by #2592 and will be merged soon. What do you think?

Thank for the quick reply, I currently do not have time to look more detailed into the code, sorry. But can this be used with for example axios in the fetch method in the hono client initialization?

Thank you!

**Comment by NamesMT** [comment]
Hi @davbauer the PR adds an `init` option to pass in fetch's `RequestInit` options and will work with axios (and other libraries compatible with fetch), an example to abort a request is:
```js
const abortController = new AbortController();
const response = await hClient.jwt.someEndpoint.$post(
  {
    json: { /* request body */ },
  },
  {
    init: { signal: abortController.signal, // Pass the signal here }
    // fetch: axios // will work with custom fetch method
);

// Later, if needed:
abortController.abort(); // This would cancel the ongoing request
```

**Comment by davbauer** [comment]
@NamesMT Just looked into the PR from #2592 even more..

This is perfect, and therefore I will close the issue. 🎉
