### ISSUE TITLE
Add support for getting current request progress in hono/client

### ISSUE THREAD

**Issue by davbauer** [honojs/hono#2594]
### What is the feature you are proposing?

I would love to have a way to get the current progress of an ongoing request made through the hono client. This would allow monitoring and displaying the progress of requests, especially for large data transfers or long-running operations.

**Comment by NamesMT** [comment]
`hc` is fetch `Response` compatible, would existing libraries like [fetch-progres](https://www.npmjs.com/package/fetch-progress), [fetch-api-progress](https://www.npmjs.com/package/fetch-api-progress) suite your needs?

**Comment by davbauer** [comment]
I reckon using existing libraries like fetch-progres or fetch-api-progress might not quite fit the bill.

What I'm envisioning is for the hono client to support callbacks, maybe even custom ones. This way, I could track progress and handle it based on my own logic.

Just as an example, [this](https://javascript.info/fetch-progress) is what I would code into my fetch function and then be able to use callbacks where I initially called a fetch via the hono client.

If this functionality already exists in some form or its not clear what I am proposing here, do let me know.

**Comment by yusukebe** [comment]
Hi @davbauer 

As @NamesMT said, the `hc` returns a `Response` object compatible with `fetch` so you can write the code with `response.body.getReader()` written in [the document](https://javascript.info/fetch-progress).

We designed `hc` as a thin wrapper of `fetch`. So, we don't want to add many functions to it.

**Comment by davbauer** [comment]
I understand that it makes total sense to not over-implement already implemented stuff, I think the issue might be on my side, since I am using axios inside the fetch of the hono client initialization.

I will try to use native fetch and then test If I am able to get it working on my side and depending on that give feedback / close the issue.
