### ISSUE TITLE
inconsistent route response

### ISSUE THREAD

**Issue by sonigeez** [honojs/hono#2612]
### What version of Hono are you using?

4.3.1

### What runtime/platform is your app running on?

node

### What steps can reproduce the bug?

1. Basic template 
2. add this code snippet 
```
app.get('/api/v1/users', (c) => {
  return c.json({ message: 'Hello World' });
});
```

### What is the expected behavior?

return `{"message":"Hello World"}` in both "/api/v1/users" and "/api/v1/users/" routes

### What do you see instead?

404 on "/api/v1/users/" route

**Comment by sor4chi** [comment]
Try this option and see!

```ts
new Hono({
  strict: false,
})
```

**Comment by sonigeez** [comment]
thanks
