### ISSUE TITLE
[Bug]: form validator does not return all data

### ISSUE THREAD

**Issue by ParasSolanki** [honojs/hono#2625]
### What version of Hono are you using?

4.3.2

### What runtime/platform is your app running on?

Node 20.10.0 / Windows 10 Pro

### What steps can reproduce the bug?

The form validator in hono does not return all data when using with zod-validator.

When you use zod-validator to validate multiple uploaded file of request form data then it only returns last file data. It should  return all the files with the same key as an array,

![validate-body-data](https://github.com/honojs/hono/assets/62164346/3fcdb6a5-6747-4f09-a6c6-9074faa48440)

1. Start a new Hono project using `create-hono` with `pnpm` and select NodeJS template. `pnpm create hono my-app`
1. Install `@hono/zod-validator` and `zod` to validate incoming request body and params. `pnpm add @hono/zod-validator zod`.
1. Now, in `index.ts` create a `POST /upload` route for file upload without using zod-validator.
1. Create another `POST /validate-upload` route for file upload to accepts data as `FormData` in which use zod-validator to validate incoming data.

Github Repro Link: https://github.com/ParasSolanki/hono-multi-file-upload-validation-bug.

If i use `c.req.parseBody()` as mentioned [here](https://hono.dev/snippets/file-upload#snippets) then i do get all the multiple uploaded files in an array.

![parse-body-data](https://github.com/honojs/hono/assets/62164346/5d6d921e-160b-4655-a920-d1e4b962c66a)

### What is the expected behavior?

If key is ending with "[]" then it should return data in an array form after the validation. Same logic as we have for the `parseBody()` [here](https://github.com/honojs/hono/blob/main/src/utils/body.ts#L70).

### Additional information

In the [validator.ts](https://github.com/honojs/hono/blob/main/src/validator/validator.ts#L96) we should handle logic for key ending with "[]". Instead of returning last value it should return it as an array.

**Comment by fzn0x** [comment]
Can you try to use `{ all: true }` as arguments in parseBody?

```ts
await c.req.parseBody({ all: true });
```

also for validator there is a valid issue where Hono only validate the last file uploaded:

```ts
// my validator schema
export const PostUploadFileSchema = z
  .object({
    "image[]": z
      .custom<Blob>()
      .refine(
        (blob) => {
          return blob.size <= MAX_FILE_SIZE;
        },
        {
          message: `More than ${MAX_FILE_SIZE} are not allowed`,
        }
      )
      .refine((blob) => ACCEPTED_IMAGE_TYPES.includes(blob?.type), {
        message: "Only .jpg, .jpeg, .png and .webp formats are supported.",
      }),
  })
  .openapi("Post Upload File");
  
// for types do like this as Blob
const images = body["image[]"] as Blob;
```

I'm trying to upload 2 files, first file is the invalid one, but both is uploaded and pass the validator.

![Screenshot 2024-05-07 025229](https://github.com/honojs/hono/assets/50759463/7da3a9ed-0fc7-4439-8171-e14958a4b3ac)

**Comment by ParasSolanki** [comment]
@fzn0x Yeah, It is working for `c.req.parseBody()`. The issue is in validator that it does not return all data in an array.

**Comment by yusukebe** [comment]
Hi @ParasSolanki 

Thank you for the issue. This is not an unimplemented thing rather than a bug. But it should be implemented. I'll work on it later.

**Comment by yusukebe** [comment]
Hi @ParasSolanki 

This might be fixed in #2639 and released the new version `v4.3.3` including the fix. Let me know if it still has a problem!

**Comment by ParasSolanki** [comment]
That's great! I'll definitely test out the new version and let you know if the issue persists.

**Comment by ParasSolanki** [comment]
Yeah the issue is resolved now its successfully validating and we get the data in an array.

![image](https://github.com/honojs/hono/assets/62164346/4037c6a4-f8cb-47ef-bc31-d40ffa21a51d)
