### ISSUE TITLE
Next is called multiple times

### ISSUE THREAD

**Issue by cendyne** [honojs/hono#264]
Hello, I've had a lot of fun with this framework!

One issue I ran into was when I tried to make a dynamic handler, here is an example

```ts
import { Hono } from 'hono'
interface Environment {}
const app = new Hono<Environment>();

app.get('/:id', async (c, next) => {
  let id = c.req.param('id');
  if (id == 'hello') {
    return c.text('Hi!');
  } else {
    return await next();
  }
});
app.notFound((c) => {
  console.log(`${c.req.url} not found`)
  return c.text('NOT FOUND', 404)
});
export default app;
```

There are two issues
1. Typescript does not like a handler with type `Promise<Response | void>`
2. Next is called multiple times

```
Error: next() called multiple times
    at dispatch (index.js:245:35)
    at index.js:262:21
    at async Hono2.dispatch (index.js:625:21)
```

I would expect that it continues and runs the not found handler.

When it matches, this handler works
<img width="298" alt="image" src="https://user-images.githubusercontent.com/83187359/169738908-7ae3aaf5-9801-4503-9773-f3d08818bc81.png">

But otherwise it responds with Internal Server Error

**Comment by yusukebe** [comment]
Hi @cendyne 

Sorry for the lack of clarity. You can write like this:

```ts
const app = new Hono()

app.get('/:id', async (c) => {
  const id = c.req.param('id')
  if (id == 'hello') {
    return c.text('Hi!')
  }
  return c.notFound()
})

app.notFound((c) => {
  console.log(`${c.req.url} not found`)
  return c.text('NOT FOUND', 404)
})

export default app
```

* You don't have to use `next()` in your hander.
* In the handler, you have to return the Response object using `c.text()`, `c.json()`, or `c.notFound()` ...

Thank you for creating the issue!

**Comment by cendyne** [comment]
Understood, thank you for the rapid reply!
