### ISSUE TITLE
[jsx/dom] Support `getServerSnapshot`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#2640]
### What is the feature you are proposing?

It would be great if `getServerSnapshot` is supported. If so, my favorite library [`swr`](https://swr.vercel.app) will work!

Like this code:

```tsx
import { render } from 'hono/jsx/dom'
import { hc } from 'hono/client'
import api from './api'

import useSWR from 'swr'

const client = hc<typeof api>('/api')

function App() {
  const $get = client.index.$get
  const fetcher = async () => {
    const res = await $get()
    return await res.json()
  }

  const { data, error, isLoading } = useSWR('api', fetcher)

  if (isLoading) return <h1>Loading...</h1>
  if (error) return <h1>Error: {error.message}</h1>
  return <h1>Hello {data?.name}</h1>
}

const domNode = document.getElementById('root')!
render(<App />, domNode)
```

**Comment by yudai-nkt** [comment]
This would be a nice addition! FWIW, this will make Hono compatible with [`@tanstack/react-query`](https://tanstack.com/query/latest/docs/framework/react/overview) as well (I've been toying around with TanStack libraries at [yudai/hono-jsx-dom-with-tanstack-table@tanstack-query](https://github.com/yudai-nkt/hono-jsx-dom-with-tanstack-table/tree/tanstack-query) these days and found that it was currently incompatible).
