### ISSUE TITLE
WebSocket Helper not working

### ISSUE THREAD

**Issue by mathysth** [honojs/hono#2645]
### What version of Hono are you using?

4.1.1

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

I'm using [Hono websocket helper](https://hono.dev/helpers/websocket) but it return me and error when I try to connect to it
![image](https://github.com/honojs/hono/assets/38434126/6be818ca-fea7-43ee-b71e-6db50d05d0d5)
I cheked if my setup was good and for me it was 
![image](https://github.com/honojs/hono/assets/38434126/43acae28-f9fa-4dc1-bfca-4221dfdc405c)
Here how I  setup the ws to hono
![image](https://github.com/honojs/hono/assets/38434126/b042fe79-2461-4dc4-acba-ad72ef6fc694)

**Comment by nakasyou** [comment]
Hi @mathysth
Could you show me that unhidden `fetch` function in 2nd screenshot?
I think that problem is in it.

**Comment by mathysth** [comment]
Hey @nakasyou here the full code that you ask
```ts
boostrapApp().then((httpConfig) => {
  const logger = IocContainer.container.get(LoggerService);
  const controllerRoot = IocContainer.container.get(ControllerRoot);
  const socket = IocContainer.container.get(SocketProvider);
  try {
    serve({
      async fetch(req, server) {
        const serverConfig = await httpConfig?.fetch(req, { ip: server.requestIP(req) });
        return serverConfig;
      },
      websocket,
      port: httpConfig?.port,
    });
    // Initialize the socket
    socket.initSocket();

    // Setup all controllers
    controllerRoot.setup();
    logger.pino.info(`Hono 🥟 Server Listening on port ${httpConfig?.port}`);
  } catch (e) {
    logger.pino.error(`An error occurred during server initialization, ${e}`);
  }
});
```

**Comment by mathysth** [comment]
@nakasyou I found the problem but I'm still searching for the anwser.
according to[ hono doc](https://hono.dev/getting-started/bun#obtaining-request-ip-address) you can retrieve user ip like the following :

```ts
const app = new Hono()

serve({
  fetch: (req, server) => {
    return app.fetch(req, { ip: server.requestIP(req) })
  },
  websocket,
  port: 3008,
});
```

But when you bind the ip as an env I think the server is not initialize... and then the websocket logic doesn't work anymore.
If I remove **{ ip: server.requestIP(req) }** it's working for me

**Comment by nakasyou** [comment]
@mathysth, this may also be a problem with Hono.

As a workaround, you can use that:
```ts
await httpConfig?.fetch(req, { upgrade: server.upgrade })
```
or
```ts
await httpConfig?.fetch(req, server)
```

**Comment by mathysth** [comment]
@nakasyou 

I got a new error  when doing 
```ts
await httpConfig?.fetch(req, { upgrade: server.upgrade })
-----
[01:24:23.425] ERROR (137329): Expected 'this' to be instanceof DebugHTTPServer
    err: {
      "type": "TypeError",
      "message": "Expected 'this' to be instanceof DebugHTTPServer",
      "stack":
          TypeError: Expected 'this' to be instanceof DebugHTTPServer
              at upgrade (native)
              at <anonymous> (/mnt/d/Geniqks/clients/elsa-m/applications/app/node_modules/hono/dist/adapter/bun/websocket.js:27:14)
              at processTicksAndRejections (:12:39)
      "originalLine": 26,
      "originalColumn": 27
    }
```
 I really need to access to the user ip for my rate limiter with
```ts
ip: server.requestIP(req)
``` 

I will try to bind all server value to an object. 
Is there any other way to bind env to hono I didn't found it on the doc

**Comment by mathysth** [comment]
@nakasyou I did this work around, it's working, hope hono could fix this somedays. Thanks again

```ts
serve({
      async fetch(req, server) {
        const untypedServer = server as unknown as any
        untypedServer.ip = server.requestIP(req)
        const serverConfig = await httpConfig?.fetch(req, untypedServer);
        return serverConfig;
      },
      websocket,
      port: httpConfig?.port,
    });
```

**Comment by nakasyou** [comment]
@mathysth
You can use 
```ts
return app.fetch(req, { ip: server.requestIP(req), server })
```
to resolve it.
