### ISSUE TITLE
Support for `deno serve` in Den oadapter

### ISSUE THREAD

**Issue by FilipJirsak** [honojs/hono#2653]
### What is the feature you are proposing?

Deno now supports a new `serve` command in the command line. It's syntactic sugar for `deno run`, which automatically starts an HTTP server. It works by expecting the executed script to be a module that exports an object with a `fetch` property. This property is an asynchronous function that expects one parameter of type `Request` and returns a `Response`.

The following code theoretically should work:

```typescript
const app = new Hono()

app.get('/', (c) => {
    return c.text('Hello Hono!')
})

export default {fetch: app.fetch};
```

Or even simply:
```typescript
export default app;
```

However, both this code fails when Deno checks if `fetch` is a function expecting one parameter.
Invalid type for fetch: must be a function with a single parameter

It's possible to rewrite the code as follows:

```typescript
const app = new Hono()

app.get('/', (c) => {
    return c.text('Hello Hono!')
})

export default {
    fetch: async (request: Request): Promise<Response> => await app.fetch(request)
};
```

But it would be good if the `fetch` function exported from `Hono` passed the Deno test, allowing the use of the abbreviated notation.

**Comment by ryuapp** [comment]
It's matter of types, but we can write it a little shorter:
```ts
export default {
  fetch(req: Request) {
    return app.fetch(req)
  }
}
```
https://x.com/honojs/status/1785592296307921040?s=46&t=rr9TarFB2Qfj7w-wfiF6dA
