### ISSUE TITLE
context.req.parseBody(): option for support dot notation

### ISSUE THREAD

**Issue by vanodevium** [honojs/hono#2656]
### What is the feature you are proposing?

For now this method has only option **all** for array support. It is awesome!

In my opinion, it would be very convenient to add an option to support dot notation (**dot: boolean**), which would greatly simplify the processing of nested objects.

Example:

```js
let formData = new FormData();
formData.append('obj.key1', 'value1');
formData.append('obj.key2', 'value2');

// processed without dot notation support, like `await context.req.parseBody()`
{
	"obj.key1": "value1",
    "obj.key2": "value2",
} 

// processed with dot notation support, like `await context.req.parseBody({ dot: true })`
{
	"obj": {
		"key1": "value1",
		"key2": "value2"
	}
}
```

**Comment by yusukebe** [comment]
Hi @vanodevium 

Are you talking about the "[FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData)"?

If so, it's standard Web API, and it's not Hono matter. There is nothing we can do about it.

**Comment by fzn0x** [comment]
It's something from the Browser API. For Hono, I think you can build a custom middleware for it.

```ts
app.use(async (c, next) => {
    const json = await c.req.parseBody();

    // do the dot notation logic

    c.req.bodyCache.parsedBody = parsedBody;
  } catch (_err) {
  } finally {
    await next();
  }
});
```

But becareful about modifying data in middleware, while modifying data in middleware is a common and often necessary practice in web development, it must be done responsibly, securely, and in compliance with legal and ethical standards.

**Comment by yusukebe** [comment]
Ah, I see. I miss understanding. This is proposing adding a `dot` option to `c.req.parseBody()`

That is a good proposal. I'd like to know if others want this feature.

**Comment by vanodevium** [comment]
@yusukebe 

I discussed this functionality with colleagues and programmer friends.

The answer is the same for everyone - it is a very convenient and useful thing.

Moreover, by default this thing will be turned off, so there will be no breaking changes for existing systems.

Of course, the decision is yours. Thank you!

**Comment by fzn0x** [comment]
> Ah, I see. I miss understanding. This is proposing adding a `dot` option to `c.req.parseBody()`
> 
> That is a good proposal. I'd like to know if others want this feature.

I think it's something great to add :)

**Comment by yusukebe** [comment]
Thanks to both. Let's add the feature. I'll do it, but now I'm busy working on other matters. Does anyone implement it?

**Comment by MathurAditya724** [comment]
Fine, I will do it. I am thinking about the API cause `{dot: true}` isn't expressive enough, maybe something like `{json: true}`?

**Comment by fzn0x** [comment]
Hi @MathurAditya724 actually I'm already building it, only unit tests left

**Comment by MathurAditya724** [comment]
@fzn0x Great! Do let me know when the PR is ready, maybe I can add some pointers

**Comment by fzn0x** [comment]
PR is ready! 👍

**Comment by fzn0x** [comment]
Hi @yusukebe I think we can close this issue :)

**Comment by yusukebe** [comment]
Yes. Closing:)
