### ISSUE TITLE
large requests (>~100MiB) fail before bodyLimit is called

### ISSUE THREAD

**Issue by BobbyRaduloff** [honojs/hono#2671]
### What version of Hono are you using?

4.3.6

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

I have a use-case where a user submits a POST request to a form with around 200 MiB of image files (large images, ~10MiB each). This is how I have it set up.

1. Set up an endpoint with `bodyLimit`:
```ts
app.post(
  "/dashboard/uploads",
  bodyLimit({
    maxSize: 1024 * 1024 * 200, // 200 MiB
    onError: (c) => c.html(<Error error="Files are too big!" />),
  }),
  routePostDashboardUpload,
);

export async function routePostDashboardUpload(c: Context) {
  // there is no omitted code here,
  // it actually just returns rendered jsx
  // (crash happens before endpoint)
  return c.html(
    <Success message="Files uploaded successfully. You can check their progress in the Files tab." />,
  );
}
```

2. Call the endpoint with a large multipart body (~180MiB in this case):
```sh
curl -v \
  --location 'http://localhost:3000/dashboard/uploads' \
  --form 'files=@"/home/boris/Downloads/img/1.png"' \
  --form 'files=@"/home/boris/Downloads/img/2.png"' \
  [...more files]
```

That's the smallest reproduction I can do.

### What is the expected behavior?

It should just call the endpoint and return it's return value if the total size of the body is less than `maxSize`.

If it isn't, it should return 413. It's my understanding from looking at `hono/src/middleware/body-limit/index.ts`, that the response body in such cases should be the string `Payload Too Large`.

### What do you see instead?

However, `curl` returns the following:
```
* processing: http://localhost:3000/dashboard/uploads
*   Trying [::1]:3000...
* Connected to localhost (::1) port 3000
> POST /dashboard/uploads HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/8.2.1
> Accept: */*
> Content-Length: 195543851
> Content-Type: multipart/form-data; boundary=------------------------ae2e9d88e58090c8
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 413 Request Entity Too Large
< Connection: close
< 
* we are done reading and this is set to close, stop send
* Closing connection
```

As you can see, several things are wrong.

1. The [docs suggest](https://hono.dev/middleware/builtin/body-limit) that if a content-length header is present, it will check whether it should error based on that. 195543851 is smaller than 1024 * 1024 * 200  = 209715200, yet 413 is still returned.

2. Neither a body of `Payload Too Large` or that defined in the `onError` handler is provided, which suggests the error originates somewhere other than the `bodyLimit` middleware.

3. The endpoint is not called. I tried adding a `console.log` to verify.

### Additional information

1. I tried with different bodies and the threshold for crashing seems to be between 100 and 120 MiB, regardless of `maxSize` (set to 2GiB during testing).

2. The `bodyLimit` middleware works fine when the `maxSize` value is less than said threshold. The `onError` handler is called when appropriate.

3. Adding some console logs in `hono/src/middleware/body-limit/index.ts` also leads me to believe the error originates before that middleware is even executed.

**Comment by BobbyRaduloff** [comment]
As is always with these issue reports, the solution arrived to me the moment I posted it.

The issue was with Bun.serve, and not with Hono.

For bun users, you have to make sure that Bun can handle that big of a request as well:
```ts
export default {
  port: process.env["PORT"] || 3000,
  fetch: app.fetch,
  maxRequestBodySize: 1024 * 1024 * 200, // your value here
};
```
or, depending on your setup:
```ts
Bun.serve({
  fetch(req, server) {
    return app.fetch(req, { ip: server.requestIP(req) })
  },
  maxRequestBodySize: 1024 * 1024 * 200, // your value here
})
```

I am closing this. Question for the maintainers, would you be interested for a PR to add this disclaimer to the `bodyLimit` docs at [https://hono.dev/middleware/builtin/body-limit](https://hono.dev/middleware/builtin/body-limit)? I can only write one about Bun because I don't use the other adapters, but it could be useful.

**Comment by yusukebe** [comment]
Hi @BobbyRaduloff 

> Question for the maintainers, would you be interested for a PR to add this disclaimer to the `bodyLimit` docs at [https://hono.dev/middleware/builtin/body-limit](https://hono.dev/middleware/builtin/body-limit)? I can only write one about Bun because I don't use the other adapters, but it could be useful.

Yes. We will be glad if you write it. Thanks!
