### ISSUE TITLE
FormData parse error missing final boundary

### ISSUE THREAD

**Issue by shishamo** [honojs/hono#2689]
### What version of Hono are you using?

4.3.7

### What runtime/platform is your app running on?

bun

### What steps can reproduce the bug?

Have following error when try to parse body from request
```
const body = await c.req.parseBody();
```

> FormData parse error missing final boundary

**Comment by fzn0x** [comment]
What fetch wrapper you use or just `fetch` ?

Can you give the fetch example code you use if you use `fetch`?

**Comment by shishamo** [comment]
I use the fetch wrapper as below

```
const app = new Hono();

Bun.serve({
      hostname: process.env.HOST,
      fetch(req, server) {
        return app.fetch(req, { ip: server.requestIP(req) });
      },
      port: process.env.PORT,
});
```

**Comment by fzn0x** [comment]
Looks like a problem with the fetch wrapper 

Did you upload the file from server or browser? 

If it's browser, I think Content-Type not automically change to form data with boundary.

**Comment by shishamo** [comment]
I am using Postman for testing 

> Content-Type: multipart/form-data; boundary=--------------------------759233921680071858886951

I have that header in the request

Actually i have that error as well when using `c.req.json()`

> Unexpected end of JSON input

The request body is send as following

```json
{
    "test": 1
}
```

**Comment by shishamo** [comment]
@fzn0x 

Sorry that error occuring on a `GET` method
Using `POST` was fine

I close that issue

**Comment by fzn0x** [comment]
Nps, thanks for your answer, it may help someone in the future :)
