### ISSUE TITLE
Type bug introduced in `v4.3.0` in `secureHeaders` middleware

### ISSUE THREAD

**Issue by MonsterDeveloper** [honojs/hono#2693]
### What version of Hono are you using?

4.3.0

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

1. Install version `4.3.0` of Hono.
2. Create a TS file with an app that uses `secureHeaders` middleware and another arbitrary middleware that sets the context (I used `@hono/clerk-auth` as an example). Also in this file you'll mount the routes from another file with `app.route()`.
3. In another file, create another app and try to access the context value with `context.get` from this other middleware, and see it fail, as the context only contains "secureHeadersNonce" variable.

`4.3.0` CodeSandbox with a bug: https://codesandbox.io/p/devbox/hono-4-3-0-not-working-9kg2s7

`4.2.9` CodeSandbox working fine: https://codesandbox.io/p/devbox/hono-4-2-9-working-vlx83h

### What is the expected behavior?

One can access the context variable in another file.

### Additional information

I confirmed that the issue lies in the `secureHeaders` middleware, as by commenting it out everything works fine as before. I suspect [these lines](https://github.com/honojs/hono/blob/d87d9964433a4777b09abff9360ff12643d00440/src/middleware/secure-headers/index.ts#L4) to be the issue from PR #2577:
```ts
declare module '../../context' {
  interface ContextVariableMap {
    secureHeadersNonce?: string
  }
}
```

It seems like this is overwriting the context variables set by other middleware, therefore it's impossible to access variables from other middleware without importing it directly (which would be an unused import technically).

**Comment by MonsterDeveloper** [comment]
As a matter of fact, I checked other built-in middleware (like `timing`) that also set context variables via `
declare module '../../context'` and the issue seems to also be present.

I assume this declaration overwrites 3rd party middleware variable as they set it via `declare module 'hono'`.

I guess changing the declaration method should help.

**Comment by MonsterDeveloper** [comment]
I can confirm that changing `declare module '../../context'` to `declare module 'hono'` solved the issue. Will create a PR now.

**Comment by yusukebe** [comment]
Hi @MonsterDeveloper !

I think this issue was fixed with the new version `v4.4.0`. Can you try it?

**Comment by MonsterDeveloper** [comment]
Seems to be working, thanks!

**Comment by yusukebe** [comment]
Yeess 🎉
