### ISSUE TITLE
WebSockets In Bun

### ISSUE THREAD

**Issue by NicoPlyley** [honojs/hono#2696]
### What version of Hono are you using?

4.3.7

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

If you `Bun.serve` and return `app.fetch()` it will not allow Bun to switch protocols, making web sockets unusable. The following is an example of that
```ts
Bun.serve({
  fetch(req, server) {
    return app.fetch(req, { ip: server.requestIP(req) }) // This return prevents protocol switching
  },
  websocket,
})
```

Now that is expected behavior in Bun, so here is how [Bun says it should be done instead](https://bun.sh/guides/websocket/simple):
```ts
const server = Bun.serve{
  fetch(req, server) {
    const success = server.upgrade(req);
    if (success) {
      // Bun automatically returns a 101 Switching Protocols
      // if the upgrade succeeds
      return undefined;
    }

    // handle HTTP request normally
    return app.fetch(req, { ip: server.requestIP(req) })
  },
  websocket,
  },
});

console.log(`Listening on ${server.hostname}:${server.port}`);
```

### What do you see instead?

This appears to be because since the `server.upgrade` was already ran, it is causing issues.
Here is the error that is received:

```bash
43 |       if (websocketListeners.onOpen) {
44 |         websocketListeners.onOpen(new Event("open"), createWSContext(ws));
45 |       }
46 |     },
47 |     close(ws, code, reason) {
48 |       const websocketListeners = websocketConns[ws.data.connId];
                                                     ^
TypeError: undefined is not an object (evaluating 'ws.data.connId')
      at close (/hono-test/node_modules/hono/dist/adapter/bun/websocket.js:48:49)
      at fetch (/hono-test/src/index.ts:41:16)
37 |       await next();
38 |     };
39 |   };
40 |   const websocket = {
41 |     open(ws) {
42 |       const websocketListeners = websocketConns[ws.data.connId];
                                                     ^
TypeError: undefined is not an object (evaluating 'ws.data.connId')
      at open (/hono-test/node_modules/hono/dist/adapter/bun/websocket.js:42:49)
      at fetch (/hono-test/src/index.ts:41:16)

22 |   const websocketConns = [];
23 |   const upgradeWebSocket = (createEvents) => {
24 |     return async (c, next) => {
25 |       const server = c.env;
26 |       const connId = websocketConns.push(await createEvents(c)) - 1;
27 |       const upgradeResult = server.upgrade(c.req.raw, {
                                 ^
TypeError: undefined is not an object (evaluating 'server.upgrade')
      at /hono-test/node_modules/hono/dist/adapter/bun/websocket.js:27:29

```

### Additional information

I've had two different people mention this issue, so I decided to investigate further. I think it is important and reasonable, for a user to need to access the IP, or set any env and be able to still use websockets

**Comment by yusukebe** [comment]
@NicoPlyley Thank you for raising the issue.

@nakasyou Could you see this?

**Comment by nakasyou** [comment]
Hi @NicoPlyley, thank you for sending.

I think it's the same cause as this: #2645.

If WebSocket helper will support `{ server: server }` like https://github.com/honojs/hono/pull/2595#discussion_r1590458007, this problem may be resolved.

**Comment by nakasyou** [comment]
@NicoPlyley 
You can use 
```ts
return app.fetch(req, { ip: server.requestIP(req), server })
```
to resolve it.

**Comment by NicoPlyley** [comment]
The new connInfo should solve it too, correct? I'm basing my issue based off what people on discord have had issues with

**Comment by nakasyou** [comment]
@NicoPlyley 
When you use ConnInfo helper, you can get conninfo.
As you said, ConnInfo Helper also supports 
```ts
return app.fetch(req, { ip: server.requestIP(req), server })
```
