### ISSUE TITLE
Add "Author should include JSDoc" to PR template

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#2718]
### What is the feature you are proposing?

Context: https://github.com/honojs/hono/pull/2615#issuecomment-2114090960

> I'm thinking we should improve the PR template to tell every PR that adding a new feature should add TSDoc/JSDoc (if it's necessary) @yusukebe This way we can slowly migrate codebase to use TSDoc/JSDoc

**Comment by EdamAme-x** [comment]
If this is to be implemented, we also need to add a guide on how to write it (jsdoc).

e.x.
JSDoc must includes description, **@see**, **@param**, **@returns**, optional **@throws**, **@example**

**Comment by fzn0x** [comment]
> If this is to be implemented, we also need to add a guide on how to write it (jsdoc).
> 
> e.x. JSDoc must includes description, **@ see**, **@ param**, **@ returns**, if needs **@ throws**, **@ example**

I have something simpler in mind will create a PR soon :)
