### ISSUE TITLE
Middleware is not properly isolated when multiple routes share the same path

### ISSUE THREAD

**Issue by gitblit** [honojs/hono#2759]
### What version of Hono are you using?

4.3.9

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

Middleware does not have proper route isolation when paths are shared leading to extra executions and new types of bugs.

Given this example code...

```typescript
import { Hono } from 'hono'
import { logger } from 'hono/logger';

const r1 = new Hono()
  .use(async (_, next) => {
    console.log('r1 start')
    await next()
    console.log('r1 end')
  }).
  get("/test", (c) => c.json({ message: "get" }));

const r2 = new Hono()
  .use(async (_, next) => {
    console.log('r2 start')
    await next()
    console.log('r2 end')
  }).post("/test", (c) => c.json({ message: "post" }));

const r3 = new Hono()
  .use(async (_, next) => {
    console.log('r3 start')
    await next()
    console.log('r3 end')
  }).put("/test", (c) => c.json({ message: "put" }));

const app = new Hono()
  .use(logger())
  .route("/", r1)
  .route("/", r2)
  .route("/", r3);

export default app
```

### What is the expected behavior?

When calling the `GET` endpoint, followed by the `POST` endpoint, and then followed by the `PUT` endpoint, I would expect:

- middleware for `r1` runs on `r1` route
- middleware for `r2` runs on `r2` route
- middleware for `r3` runs on `r3` route

### What do you see instead?

Instead, I see...
- the middleware for `r` running on the `r1` endpoint
- the middleware for `r1` & `r2` running on the `r2` endpoint
- the middleware for `r1` & `r2` & `r3` running on the `r3` endpoint

```
  <-- GET /test
r1 start
r1 end
  --> GET /test 200 1ms
  <-- GET /test
r1 start
r1 end
  --> GET /test 200 0ms
  <-- POST /test
r1 start
r2 start
r2 end
r1 end
  --> POST /test 200 0ms
  <-- PUT /test
r1 start
r2 start
r3 start
r3 end
r2 end
r1 end
  --> PUT /test 200 0ms
```

**Comment by yusukebe** [comment]
Hi @gitblit Thank you for the issue!

This seems to be a bug, but it's not. This behavior is expected, whether the DX is good or not.

In Hono, `app.use(mw)` is alias of `app.all('*', mw)`.

For example, if we have the following code:

```ts
const mw = function middleware() {}

const app = new Hono().use(mw).get('/test', (c) => c.json({ message: 'get' }))

showRoutes(app, {
  verbose: true,
})
```

The output is below:

```ts
ALL  /*
       middleware
GET  /test
       [handler]
```

To enable our expected behavior, you can write the following:

```ts
const app = new Hono().get('/test', mw, (c) => c.json({ message: 'get' }))
```

The output:

```
GET  /test
       middleware
       [handler]
```

I hope you will understand. And it's maybe difficult to understand, so we have to write this thing to the doc, or perhaps we might have to make limitations of the usage of `app.use()`, e.g., disabling changing to don't make confusing.

**Comment by gitblit** [comment]
@yusukebe thanks for the explanation! I'm glad there is an alternative approach in `Hono`.

For my actual use-case I am using `OpenApiHono`. Will I be able to do this?

```
app.openapi(route, mw, (c) => c.json({ message: 'get' });
```

**Comment by yusukebe** [comment]
@gitblit Thank you!

You can't write it that way (because inferring Types will be super complex if it will support that)  but you may use this option: https://github.com/honojs/middleware/tree/main/packages/zod-openapi#configure-middleware-for-each-endpoint

**Comment by gitblit** [comment]
```
middleware: [prettyJSON(), cache({ cacheName: 'my-cache' })],
```

This is perfect! I missed that in my read of the docs. Thank you and sorry for the noise.
