### ISSUE TITLE
Access path parameters from middleware

### ISSUE THREAD

**Issue by gitblit** [honojs/hono#2760]
### What is the feature you are proposing?

I have a use-case which requires knowing a route's path parameters from within middleware.

Given an app like this:
```typescript
const app = new Hono()
  .use(middleware())
  .get("/api/users/:userId/posts/:postId", () => "Future");
```

I'd like to be able to easily access `userId` and `postId` from within `middleware` which is unaware of the route and parameters declared in the `get` (same problem in `OpenApiHono`, but maybe even worse). I don't need these values to be correctly typed - string is fine - but I do want to easily grab them.

Ideally, I'd like to do this in middleware and have it work:
```
const { userId, postId } = c.req.param();
```

I can write that today, but it does not work (at least with `OpenApiHono`).

That has led me to do nasty things with identifying the matched route and manually splitting strings to derive the parameters the hard way. (Mining the matched routes actually led me to find #2759.) I am sure there is a more elegant way to achieve this result and it seems like this would be a nice improvement to have in Hono.

**Comment by yusukebe** [comment]
Hi @gitblit 

Regarding this issue, middleware can't get the parameters in another handler. This was discussed in #1542.

One of the ideas is passing the values to middleware with `c.set()`/`c.get()`:

```ts
const app = new Hono<{
  Variables: {
    userId: string
    postId: string
  }
}>().get(
  '/api/users/:userId/posts/:postId',
  async (c, next) => {
    await next()
  },
  (c) => {
    c.set('userId', c.req.param('userId'))
    c.set('postId', c.req.param('postId'))
    return c.text('post!')
  }
)
```

**Comment by gitblit** [comment]
I don't know if it's a bug or deliberate... but once I moved my middleware from `use` to nested (is that the right word?) then I was able to access my params (as `string`) in the middleware which is PERFECT.

```typescript
const { userId, postId} = c.req.param();
```

**Comment by gnllucena** [comment]
> I don't know if it's a bug or deliberate... but once I moved my middleware from `use` to nested (is that the right word?) then I was able to access my params (as `string`) in the middleware which is PERFECT.
> 
> ```ts
> const { userId, postId} = c.req.param();
> ```

hey, @gitblit would you mind explaining what you did? 

I'm facing the same issue, what do you mean by `nested` middleware?

**Comment by gitblit** [comment]
You got it, @gnllucena. I am using the OpenApi integration. In that plugin/extension, you can provide middleware in a second way. Instead of `.use(myMiddleWare())`, you can declare it like this:
```javascript
createRoute({
  method: 'POST',
  path: '/users/{id}',
  request: {
    params: ParamsSchema,
  },
  middleware: [myMiddleWare()]
});
```

Using this technique, I am able to get code completion on my named path parameters BUT they are of string type, regardless of how I may have typed them with the Zod params schema. This was close enough for me. HTH!

https://github.com/honojs/middleware/tree/main/packages/zod-openapi#configure-middleware-for-each-endpoint
