### ISSUE TITLE
LambdaContext and LambdaEvent bindings not working

### ISSUE THREAD

**Issue by penzur** [honojs/hono#2766]
### What version of Hono are you using?

4.3.7

### What runtime/platform is your app running on?

AWS Lambda

### What steps can reproduce the bug?

Followed the "Access AWS Lambda Object" instruction from the docs.

```typescript
import { Hono } from 'hono'
import type { LambdaEvent, LambdaContext } from 'hono/aws-lambda'
import { handle } from 'hono/aws-lambda'

type Bindings = {
  event: LambdaEvent
  context: LambdaContext 
}

const app = new Hono<{ Bindings: Bindings }>()

app.get('/aws-lambda-info/', (c) => {
  return c.json({
      isBase64Encoded: c.env.event.isBase64Encoded,
      awsRequestId: c.env.context.awsRequestId
  })
})

export const handler = handle(app)
```

### What is the expected behavior?

I should be able to get the values for `isBase64Encoded` and `awsRequestId`.

### What do you see instead?

I'm getting `undefined` for both properties.

**Comment by kazdegroot** [comment]
isBase64Encoded is working for me, but it seems like the contexts' name changed; this is my Bindings type:

```ts
type Bindings = {
  event: LambdaEvent;
  requestContext: LambdaEvent['requestContext'];
  lambdaContext: LambdaContext;
};
```

Tried your code with hono@4.3.8, and if I change env.context to env.lambdaContext, I get the expected result.

**Comment by penzur** [comment]
It worked!

I must've been reading the old docs.

Thank you so much!
