### ISSUE TITLE
Update ESLint rules

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#2772]
### What is the feature you are proposing?

I'll do it later!

**Comment by EdamAme-x** [comment]
I think eslint should allow these short hands, what do you think?
```ts
if (value) return value
```

**Comment by yusukebe** [comment]
It's done. Closing.

**Comment by yusukebe** [comment]
@EdamAme-x Sorry. No.

**Comment by EdamAme-x** [comment]
understood
