### ISSUE TITLE
CloudFrontResult needs to be exported?

### ISSUE THREAD

**Issue by ronster37** [honojs/hono#2778]
### What version of Hono are you using?

4.3.10

### What runtime/platform is your app running on?

Lambda@Edge

### What steps can reproduce the bug?

The linter is failing just following the tutorial. It's having an issue with the return type of the handle function (CloudFrontResult).

<img width="936" alt="Screenshot 2024-05-23 at 6 22 16 PM" src="https://github.com/honojs/hono/assets/2498495/fbec96d6-9d5a-43b7-ac9a-d1bef399992a">

I think CloudFrontResult may just need to be exported.

### What is the expected behavior?

No lint errors from the basic tutorial.

### What do you see instead?

Lint error on handle function.

**Comment by fzn0x** [comment]
What is your VSCode TypeScript version?

Or try `5.4.5` and see if the bug still exists

![Screenshot 2024-05-25 003251](https://github.com/honojs/hono/assets/50759463/a8742fe0-b8cb-4d22-8114-e122f6f239ff)

**Comment by yusukebe** [comment]
@ronster37 

Hmm..yes, strage. I think this is not a Node.js matter but a TypeScript problem. Can you try to create the project with the following command again?

```bash
npm create hono@latest -- --template lambda-edge
```

**Comment by ronster37** [comment]
Yes, that worked. The tsconfig.json file differs greatly from the one generated by following the documentation. Because of this, I was able to locate the issue.

Here is the tsconfig.json generated using `cdk init app -l typescript`:

```{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": [
      "es2020",
      "dom"
    ],
    "declaration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules",
    "cdk.out"
  ]
}
```

Removing (or setting to false) the `declaration` attribute solves the issue. I added "skipLibChecks" and "skipDefaultLibCheck" but it had no effect.

I think removing it might be ok since I will not be building a library.

**Comment by yusukebe** [comment]
@ronster37 

Thank you for sharing the `tsconfig.json`! But it is weird. It does not show the error in my environment with your config.

> I think removing it might be ok since I will not be building a library.

Yeah. It may be so.

**Comment by ronster37** [comment]
I'm going to close this out for now.

For anyone else who encounters this remove `"declaration": true` fixes this problem.
