### ISSUE TITLE
env vars with GraphQL

### ISSUE THREAD

**Issue by sirganya** [honojs/hono#278]
Hi,

Using module workers I don't have access to global environment variables. I can access them using `c.env`

I use env vars in a resolver for GraphQL How should I access `c.env` in module format using your GraphQL middleware?

```javascript

const schema = buildSchema(fileTypeDefs);

const viewResolver = ()=>{
  console.log(ENV_VAR_URL)
}

const rootValue = {
  view: viewResolver,
};

app.use(
  "/",
  graphqlServer({
    schema,
    rootValue,
  }),
);

export default app;
```

How would I get the value of ENV_VAR_URL in a module worker?

**Comment by yusukebe** [comment]
Hi @sirganya 

Going little bit tricky way:

```ts
app.use('/graphql', async (c, next) => {
  const viewResolver = () => {
    console.log(c.env.ENV_VAR_URL)
  }
  const rootValue = {
    hello: viewResolver,
  }
  const server = graphqlServer({
    schema,
    rootValue,
  })
  return await server(c, next)
})

export default app
```

**Comment by sirganya** [comment]
viewResolver is an imported module so it wouldn't have access to the scope of the async middleware as you have it here. Is there a solution to importing the resolver but also giving the resolver access to c.env? 
Otherwise I'd have to include the code for every resolver in the file.

**Comment by sirganya** [comment]
That's a nice solution. Thanks.
