### ISSUE TITLE
Missing pieces for React compatibility

### ISSUE THREAD

**Issue by usualoma** [honojs/hono#2792]
### version

In React we can get the version string as follows, but not in hono/jsx

```ts
import { version } from 'react';
```

https://github.com/facebook/react/blob/main/packages/shared/ReactVersion.js#L15

### react/dom/client

The createRoot and hydrateRoot APIs are not implemented in hono.

```ts
import { createRoot, hydrateRoot } from 'react-dom/client';
```

**Comment by yusukebe** [comment]
This was fixed by #2795.
