### ISSUE TITLE
Type of zod-validator not compatible with Context in Deno

### ISSUE THREAD

**Issue by KiritaniAyaka** [honojs/hono#2877]
### What version of Hono are you using?

4.4.2

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

Creating a .ts file and using the simple example from [documentation](https://hono.dev/guides/validation#zod-validator-middleware):

```ts
import { z } from 'https://deno.land/x/zod@v3.23.8/mod.ts';
import { Hono } from "jsr:@hono/hono@^4.4.2";
import { zValidator } from "npm:@hono/zod-validator@0.2.1";

const app = new Hono();

app.post(
  '/posts',
  zValidator(
    'form',
    z.object({
      body: z.string(),
    })
  ),
  (c) => {
    const validated = c.req.valid("form");
    // ... use your validated data
  }
)
```

and running in Deno to downloading all packages.

### What is the expected behavior?

All types are correct.

### What do you see instead?

TypeScript complained on line `zValidator(`:
```
Types of parameters 'c' and 'c' are incompatible.
          Property '#private' is missing in type 'Context<BlankEnv, "/posts", BlankInput>' but required in type 'Context<Env, string, { in: any; out: { form: { body: string; }; }; }>'.deno-ts(2769)
```

### Additional information

I tried clearing Deno's cache but no effect.

My Deno version:
```
❯ deno --version
deno 1.44.0 (release, x86_64-unknown-linux-gnu)
v8 12.6.228.3
typescript 5.4.5
```

and VS Code Deno extension version is `v3.37.1`.

I'm not sure if it is expected. I created the same project in Node.js, and there is no TypeScript error. It may also be a bug in Deno VS Code extension...?

**Comment by ryuapp** [comment]
maybe the same issue #1216
Ref: https://github.com/honojs/hono/issues/1216#issuecomment-1636747736

**Comment by KiritaniAyaka** [comment]
Thanks!
