### ISSUE TITLE
With typescript, type inference is lost if the json returned is not an object but an array

### ISSUE THREAD

**Issue by bosens-China** [honojs/hono#2878]
### What version of Hono are you using?

4.3.11"

### What runtime/platform is your app running on?

node

### What steps can reproduce the bug?

``` js
const app = new Hono()
  .get("/", async (c) => {
    const data = await readData();
    return c.json(data);
  })
  .get(
    "/filtration",
    zValidator(
      "query",
      z.object({
        pageSize: z.number().default(10),
      })
    ),
    async (c) => {
      const { pageSize } = c.req.valid("query");
      const data = await readData();
      const result = await splitArrayBySize(data, pageSize);
      return c.json(result);
    }
  );

export default app;

```

``` js
  client.api.issues.filtration.$get({ query: {} }).then((res) => {
    const value = res.json();
// never
  });
```

### What is the expected behavior?

Hopefully, the result will be returned correctly

### Additional information

If you return objects instead, everything is fine

``` js
const app = new Hono()
  .get("/", async (c) => {
    const data = await readData();
    return c.json(data);
  })
  .get(
    "/filtration",
    zValidator(
      "query",
      z.object({
        pageSize: z.number().default(10),
      })
    ),
    async (c) => {
      const { pageSize } = c.req.valid("query");
      const data = await readData();
      const result = await splitArrayBySize(data, pageSize);
      return c.json({result});
    }
  );

export default app;
```

**Comment by yusukebe** [comment]
Hi, @bosens-China 

I can't reproduce it. Could you provide the minimal project to reproduce it?

**Comment by bosens-China** [comment]
@yusukebe 

[bug like](https://codesandbox.io/p/devbox/bug-tw6ykf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clww6adgi00073b6m781xenkk%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clww6adgi00023b6m0rn5obxz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clww6adgi00043b6mme2fi106%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clww6adgi00063b6myxpyj1qf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clww6adgi00023b6m0rn5obxz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clww6adgi00013b6m260oae8y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clww6adgi00023b6m0rn5obxz%2522%252C%2522activeTabId%2522%253A%2522clww6adgi00013b6m260oae8y%2522%257D%252C%2522clww6adgi00063b6myxpyj1qf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clww6adgi00053b6m2ijyrm6t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clww6adgi00063b6myxpyj1qf%2522%252C%2522activeTabId%2522%253A%2522clww6adgi00053b6m2ijyrm6t%2522%257D%252C%2522clww6adgi00043b6mme2fi106%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clww6adgi00033b6m8fl7kwrt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clww6adgi00043b6mme2fi106%2522%252C%2522activeTabId%2522%253A%2522clww6adgi00033b6m8fl7kwrt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by yusukebe** [comment]
@bosens-China Thank you!

This problem caused by `result` type - `[number, IssuesDaum[]][]` will be treated by `never`:

![CleanShot 2024-06-06 at 18 00 10@2x](https://github.com/honojs/hono/assets/10682/43105600-997c-4dd6-b7a1-c1e929af732a)

![CleanShot 2024-06-06 at 18 01 22@2x](https://github.com/honojs/hono/assets/10682/aee0197f-5d9a-4964-8f6f-33a73348de99)

@NamesMT What do you think of this matter? `[number, IssuesDaum[]][]` should be valid JSON type?
