### ISSUE TITLE
netlify boilarplate doesnt comes up with package.json 

### ISSUE THREAD

**Issue by xkeshav** [honojs/hono#2882]
### What version of Hono are you using?

4.0.9

### What runtime/platform is your app running on?

Netlify

### What steps can reproduce the bug?

try to install new app using hono

> npm create hono@latest my-app

but in local I cant run it , also see there are import statment in  edge_functsions/index.ts

```ts
import { Hono } from 'jsr:@hono/hono'
import { handle } from 'jsr:@hono/hono/netlify'

const app = new Hono()

app.get('/', (c) => {
  return c.text('Hello Hono!')
})

export default handle(app)
```

but didnt see any package.json? 

Am i Missing something?

although netlify dev runs great

### What is the expected behavior?

there must be package.json so that we can run command and add other features

### Additional information

running on Ubuntu 24.04 and having netlify CLI insatted and logged in

**Comment by EdamAme-x** [comment]
hi @xkeshav.  
maybe, this problem related to `honojs/starter`

**Comment by NicoPlyley** [comment]
Hi @xkeshav,
As mentioned this would be on [honojs/starter](https://github.com/honojs/starter). However, I don't believe Netlify uses a package.json. They run their edge functions with Deno and to my understanding using `jsr:@hono/hono` is all that is needed to "install" packages, the rest of the settings would be in the `netlify.toml` file.

**Comment by yusukebe** [comment]
@xkeshav 

As you mentioned above, you don't need to install any npm packages. And, there is a bug that `create-hono` will run `npm install` for Nextlify, but it was solved with https://github.com/honojs/create-hono/pull/41.

**Comment by yusukebe** [comment]
I think we can close this. Thanks!
