### ISSUE TITLE
micro-template.js middleware

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#289]
We want to have template engines for server-side rendering. But, almost all are using `eval` or depending on node `fs`, so it does not work in Cloudflare Workers. *Mustache* is the only one to work. Another way, **micro-temple.js** may work. I'll try to make *micro-template middleware*.

ref: <https://github.com/cho45/micro-template.js>

**Comment by usualoma** [comment]
@yusukebe If we can return HTML from JSX syntax, can we solve some of the demands of the template engine?

https://github.com/honojs/hono/compare/master...usualoma:tsx-feature

**Comment by yusukebe** [comment]
@usualoma 

Exactly. JSX is one of the good ideas. When I tried to make a web page for *Sever-Side Rendering* with Hono, I've used **[nano-jsx](https://nanojsx.io)**. You can see the source code here: 

https://github.com/yusukebe/iekei/tree/nano-jsx/src

I want to do that. **nano-jsx** is great!. It's simple and easy to use. But I've noticed that it's pretty good to provide a more tiny JSX function on Hono.

Points:

* Just support for Sever-Side Rendering (Don't support browser side)
* Make it as middleware
* Zero-dependencies
* Use `c.render` method

I'm assuming a code like this:

```tsx
import { Hono } from 'hono'
import { jsx } from 'hono/jsx'
import { Header, Footer } from './component'

const app = new Hono()

const Layout = (props) => {
  <html>
    <body>{props.children}</body>
  </html>
}

type Props = {
  message: string
}

const Top = <Props>(props) => {
  return (
    <Layout>
      <Header />
        <h1>{ props.message }</h1>
      <Footer />
    </Layout>
  )
}

app.get('/', (c) => {
  const message = 'Hello Hono!'
  return c.render(<Top message={message} />)
})

app.fire()
```

**Comment by usualoma** [comment]
@yusukebe 

Thank you!
I think we can optimize for speed by focusing on server-side rendering.

We can memoize `<Header />` and `<Footer />` that don't take props (as strings, not virtual DOM), like the example you gave.

Let me think about this in another issue.

**Comment by yusukebe** [comment]
I think this issue could be fulfilled with *jsx* middleware. So, close this.
