### ISSUE TITLE
Improvement  a new logic for HTTPException

### ISSUE THREAD

**Issue by msensys** [honojs/hono#2893]
### What is the feature you are proposing?

Currently, the `HTTPException` class accepts HTTP status codes as numeric values directly. While this approach is functional, it has several drawbacks:

1. Readability: Numeric status codes are less readable and require the developer to remember or look up what each code represents.
2. Maintainability: Hardcoding numeric values throughout the codebase makes it more difficult to update or refactor error handling.
3. Type Safety: Direct use of numeric codes increases the risk of using invalid or incorrect status codes, leading to potential bugs and inconsistencies.

Here's an example of test:
```ts
  it('Should be 401 HTTP exception object', async () => {
    const exception = new HTTPException(HTTPException.CODES.UNAUTHORIZED, {
      message: 'unauthorized',
    });
    const res = exception.getResponse();

    expect(res.status).toBe(401);
    expect(await res.text()).toBe('Unauthorized');
    expect(exception.status).toBe(401);
    expect(exception.message).toBe('Unauthorized');
  });
  ```

**Comment by EdamAme-x** [comment]
The type of statuscode is provided exactly according to the RFC.
What can you suggest instead?

**Comment by yusukebe** [comment]
Hi @mgrithm thank you for the issue.

One of the ways to enable it is to make `HTTPException.CODES.UNAUTHORIZED` to a constant value of `401`. But, this approach was not accepted in the past: #2618  #1037

**Comment by mgrithm** [comment]
> One of the ways to enable it is to make `HTTPException.CODES.UNAUTHORIZED` to a constant value of `401`. But, this approach was not accepted in the past: #2618 #1037

I used an `enum` for this

**Comment by mgrithm** [comment]
I changed it and it passed all the tests
