### ISSUE TITLE
c.json() incomplete JSONRespond/TypedResponse implementation (data & format are undefined)

### ISSUE THREAD

**Issue by ajaishankar** [honojs/hono#2895]
### What version of Hono are you using?

4.3.8

### What runtime/platform is your app running on?

CloudFlare Workers

### What steps can reproduce the bug?

https://github.com/honojs/hono/blob/main/src/context.ts#L662

I understand that TypedResponse is mainly used for type inference.

```ts
app.get("/", (c) => {
  const res = c.json({ message: "hello hono" });
  console.log(res.data, res.format, res.status);
  return res;
});
```

The above outputs

```
undefined undefined 200
```

Is there any harm in attaching the data and format to the response?

```ts
  json: JSONRespond = <T extends JSONValue | Simplify<unknown>, U extends StatusCode>(
    object: T,
    arg?: U | ResponseInit,
    headers?: HeaderRecord
  ): ReturnType<JSONRespond> => {
    const body = JSON.stringify(object)
    this.#preparedHeaders ??= {}
    this.#preparedHeaders['content-type'] = 'application/json; charset=UTF-8'
    /* eslint-disable @typescript-eslint/no-explicit-any */
    const res = (
      typeof arg === 'number' ? this.newResponse(body, arg, headers) : this.newResponse(body, arg)
    ) as any

    // SET data & format
    res.data = object
    res.format = 'json'

    return res;
  }
```

### What is the expected behavior?

data & format should have valid values

### What do you see instead?

data & format are undefined

**Comment by yusukebe** [comment]
Hi @ajaishankar thank you for the issue.

Indeed, it was created just for type inference, but it may not be good if the actual values are different from the types.

@NamesMT what do you think about this matter?

**Comment by NamesMT** [comment]
Hi @yusukebe,

If needed, I will try to make an approach that will not put the types data into the Respond payload, changes could be big though.

Alternatively, @ajaishankar's propose could also work, I don't think actually assigning `data` and `format` into the Respond would cause any harm, it would also give the user a fast way to access the response's `data` and `format`:
```
const accessingRes = createMiddleware(async (c, next) => {
  await next()
  console.log(`Returning a ${c.res.format} Respond`)
})
```

**Comment by NamesMT** [comment]
Do note that if we go with ajaishankar's propose, we should make clear that those variable are read-only.

**Comment by yusukebe** [comment]
@NamesMT @ajaishankar 

How about adding `_` prefix to the non-actual value - `data`, `fomrat`, and `status`. Zod uses this approach:

```ts
const schema = z.string()
console.log(schema.parse) // [Function: parse]
console.log(schema._type) // undefined
```

This means defining the `TypedResponse` as below:

```ts
export type TypedResponse<
  T = unknown,
  U extends StatusCode = StatusCode,
  F extends ResponseFormat = T extends string
    ? 'text'
    : T extends JSONValue
    ? 'json'
    : ResponseFormat
> = {
  _data: T
  _status: U
  _format: F
}
```

If it does not cause breaking changes, it's a good idea.

**Comment by NamesMT** [comment]
That is a good approach!,
For @ajaishankar usecase, I think you could do something like `JSON.parse(c.res.body)` or use `c.set`/`c.get`

**Comment by ajaishankar** [comment]
@yusukebe @NamesMT yes, if other libraries like Zod use the same approach then perfectly fine 👍 

My use case can handle easily with a middleware and need not be part of hono
