### ISSUE TITLE
Allow throwing responses (like Remix) and automatically wrap them in HttpException

### ISSUE THREAD

**Issue by ajaishankar** [honojs/hono#2897]
### What is the feature you are proposing?

Having a conditional response like the following breaks type inference as a generic Response is inferred

```ts
app.get("/profile", (c) => {
  return c.var.user ? c.json(c.var.user) : c.redirect("/login");
});
```

Feel the documentation could be enhanced to avoid conditional responses and use HttpException instead

```ts
app.get("/profile", (c) => {
  if (!c.var.user) {
    throw new HTTPException(undefined, {
      res: c.redirect("/login"),
    });
  }
  return c.json(c.var.user);
});
```

Since we are throwing an exception for the redirect, the return type is inferred correctly for the happy path.

Even better maybe hono could support throwing responses similar to Remix?

https://remix.run/docs/en/main/utils/redirect
https://remix.run/docs/en/main/guides/not-found#how-to-send-a-404

```ts
app.get("/profile", (c) => {
  if (!c.var.user) {
    throw c.redirect("/login")
  }
  return c.json(c.var.user);
});
```

This can be achieved with a simple middleware, but feel this _might_ be a good enhancement?

**Comment by mgrithm** [comment]
hey @yusukebe, could you take a look at that?

**Comment by yusukebe** [comment]
Hi @ajaishankar 

One of the reasons why it occurs is the `c.redirect()` does not support the RPC. We can make it support it. How about like this?

```ts
const app = new Hono()

const flag = true

const routes = app.get('/profile', (c) => {
  if (!flag) {
    return c.redirect('/', 301)
  }
  return c.json({ name: 'abc' }, 200)
})

const client = hc<typeof routes>('/')

const res = await client.profile.$get()

if (res.status === 301) {
  console.log(res.headers.get('Location'))
} else {
  const data = await res.json()
  //    ^ { name: string }
}
```

**Comment by molives** [comment]
Will Hono implement this soon?

**Comment by yusukebe** [comment]
@molives yes.

@ajaishankar Can you check #2908?

**Comment by ajaishankar** [comment]
@yusukebe 

Commented on the PR, looks good...

Redirect is a common enough use case and nice to have support for this in hono RPC.

For something like Remix thrown response I'd suggested very easy to accomplish with a simple middleware. Again Hono makes everything super simple! 🙂

```ts
const thrownResponseToHttpException = createMiddleware(async (c, next) => {
  try {
    await next();
  } catch (e) {
    throw e instanceof Response ? new HTTPException(undefined, { res: e }) : e;
  }
});

```

**Comment by yusukebe** [comment]
Hi @ajaishankar 

Is this issue solved?

**Comment by ajaishankar** [comment]
Yes, no need to add this to Hono since it can be accomplished with a middleware..
