### ISSUE TITLE
JWT Middleware seems to expose secret

### ISSUE THREAD

**Issue by sdarnell** [honojs/hono#291]
The JWT middleware validates the token against the secret, but if the token is not present or there's an error, the secret is exposed to the client in the WWW-Authenticate header.

For example:
```
    if (parts.length !== 2) {
      ctx.res = new Response('Unauthorized', {
        status: 401,
        headers: {
          'WWW-Authenticate': 'Basic ${options.secret}',
        },
      })
      return
    }
```

There's a bit more info about what WWW-Authenticate should include: https://www.rfc-editor.org/rfc/rfc6750#section-3
Note the error fields.

**Comment by metrue** [comment]
Thanks a lot raising this out @sdarnell , it's a terrible bug, just creating a quick PR to fix it. https://github.com/honojs/hono/pull/294
