### ISSUE TITLE
RPC output type becomes `never` when returning an array of interface

### ISSUE THREAD

**Issue by cormojs** [honojs/hono#2912]
### What version of Hono are you using?

4.4.2

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```typescript
import { Hono } from "hono";
import { hc } from "hono/client";

// common
interface TestInterface {
  test: string
}
const testValue: TestInterface[] = [{ test: 'test' }]

// server

const testApi = new Hono()
  .get(
    '/test',
    async c => {
      return c.json(testValue)
    }
  )

export type Test = typeof testApi

// client
type WrongType = {
  wrong: string
}

const testFunction = (test: WrongType) => {
  console.log(test)
}

const client = hc<Test>('http://localhost')
const resp = await client.test.$get()
const result = await resp.json()

testFunction(testValue) // this case reports an error
testFunction(result)  // this case does not report any errors(type of result is never)
```

### What is the expected behavior?

Type checking should be failed in both case.

### What do you see instead?

The latter case does not report any type error.

### Additional information

The problems does not reproduce when using type alias instead of interface.

**Comment by EdamAme-x** [comment]
minimal project
https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAIgAt0JiBuAKFElkTlIGNs8CiyKB6FgG2ABTNDGo0aPHnBaEQ6OqKFRcAQxZC4AFSEBnGAEklK9ZoQ04cGHpgAuOPqjA0AcxpYastPqs2Aaqr8AK5C9jr6RtYmGgDaALpwALxwMUjW+vYA5OkwmdhxElIOygBuyhJePjkAgmDASXBoQgDuKBQAFACUFnAAdC5CMO09lpk8OZkANCNwqroAnmhsbIkAfIgzllCDQVBoMr0AVrro7TkBwULdlpYelt00QgAeDPAw82Ca4fDJ758QuF8+lqwEK0gEwlEND+mgA6gRXFoPppkuZLM0ES57I5nG4PJ50FUbAAxIJLGDAdANM42ezw9AuJGfTpJdZomSEiD8IS9fgQFw0-TdfGVeAQkQ-ZgsAA831W7UypBgMDAtikfJYgXI+ky3VFcG2ujADVUzVUwDFgglvRyvQAJAMhnrCfBDUF+JLTebXXowEcTmguhIcqTyZTA+dAiEWUUYKRgLoZHNNNtXonVPtlAQoNCSWSWBTTm6PSy4LH44nNbpNAATCB6RoQH2vWZoeZwLPQXRnZFwAEGvTu+AJxpCMpQTpAA

**Comment by EdamAme-x** [comment]
![image](https://github.com/honojs/hono/assets/121654029/87a2179c-0038-4181-a19f-b5923b207658)

**Comment by EdamAme-x** [comment]
![image](https://github.com/honojs/hono/assets/121654029/534a9603-ec71-4287-b610-2fc4567ca579)

**Comment by EdamAme-x** [comment]
![image](https://github.com/honojs/hono/assets/121654029/841e7aa7-8d9d-4a55-9b05-828089384b09)

**Comment by EdamAme-x** [comment]
https://github.com/honojs/hono/blob/0d851b689ceeb74f5df17a85e4c87f33c20075f1/src/client/types.ts#L52

it works.

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAQgNgQwHYGsBKEDGB7ATgEwBVsA5CANwlwB5CA+KAXikKggA9gIl8BnKZCABQUKAH4WbTtz5QkAVzhwRo8XMXLVUAFxQUEENgBmkjlx78kFKitESrlXLZ0sVuhzaGhIsEAHkAIwArLGAmWERUDBwCYjJHagBvBF0ARgBfOi9waBh-YND4qnD4ZHQsPCJSaxpEzOyfPIBBXFwEEBLI8piqopoAbQAiBEGAGihUgF0soA

**Comment by EdamAme-x** [comment]
cause
https://github.com/honojs/hono/blob/0d851b689ceeb74f5df17a85e4c87f33c20075f1/src/context.ts#L139-L143

**Comment by EdamAme-x** [comment]
Simplify is working
https://www.typescriptlang.org/play/?#code/C4TwDgpgBAyglgWzAGzgMxAHgCoD4oC8UA3lANoDSEI240cAdlANbUD2aU2AugFxeVqtSNygBfKADISYgFChIXCAGdgARkKxEKdFmIBDXmrG55dJaoBMm+ElQZMZNQBpLzgMzdTQA

**Comment by EdamAme-x** [comment]
JSONValue is working
https://www.typescriptlang.org/play/?#code/C4TwDgpgBAyglgWzAGzgMxAHgCoD4oC8UA3lANoDSEI240cAdlANbUD2aU2AugFxeVqtSNygBfKADISYgFChIXCAGdgARkKxEKdFmIBDXmrG55dJaoBMm+ElQZMZNQBpLzgMzdTZxQCkYAPIAcgAKAE6IcMBwAG7QRKoRDADmUAA+UABGbGzIEPpMGQwArgiZEGHpUCXIyFXFDAAmEGiMEI0+0P7BAIJhYfogmgAU3aERCFGx0BljAZkAVhAAxsBVY30DIACUZNydUHOLK2tEpGSsIPyJjMl8h4HjkdFx64+bg2-B80urVWzHP5yBRdR4ANX0yGK8Qe30Ba1m736n0RwXCz2msgOACUVMVkKctHZdI4XFA3FBPPgIAAPYAQJrKWFBCFQ6AAfigGn4liAA

**Comment by EdamAme-x** [comment]
https://www.typescriptlang.org/play/?#code/C4TwDgpgBAyglgWzAGzgMxAHgCoD4oC8UA3lANoDSEI240cAdlANbUD2aU2AugFxeVqtSNygBfKADISYgFChIXCAGdgARkKxEKdFmIBDXmrG55dJaoBMm+ElQZMZNQBpLzgMzdTZxQCkYAPIAcgAKAE6IcMBwAG7QRKoRDADmUAA+UABGbGzIEPpMGQwArgiZEGHpUCXIyFXFDAAmEGiMEI0+0P7BAIJhYfogmgAU3aERCFGx0BljAZkAVhAAxsBVY30DIACUZNydUHOLK2tEpGSsIPyJjMl8h4HjkdFx64+bg2-B80urVWzHP5yBRdR4ANX0yGK8Qe30Ba1m736n0RwXCz2msgOACUVMVkKctHZdI4XFA3FBPPgIAAPYAQJrKWFBCFQ6AAfigGn4lhxeIJ1iIY1Z0KgtPpjKJOgcTmc5LlVKgnO55KAAhttps://www.typescriptlang.org/play/?#code/C4TwDgpgBAyglgWzAGzgMxAHgCoD4oC8UA3lANoDSEI240cAdlANbUD2aU2AugFxeVqtSNygBfKADISYgFChIXCAGdgARkKxEKdFmIBDXmrG55dJaoBMm+ElQZMZNQBpLzgMzdTZxQCkYAPIAcgAKAE6IcMBwAG7QRKoRDADmUAA+UABGbGzIEPpMGQwArgiZEGHpUCXIyFXFDAAmEGiMEI0+0P7BAIJhYfogmgAU3aERCFGx0BljAZkAVhAAxsBVY30DIACUZNydUHOLK2tEpGSsIPyJjMl8h4HjkdFx64+bg2-B80urVWzHP5yBRdR4ANX0yGK8Qe30Ba1m736n0RwXCz2msgOACUVMVkKctHZdI4XFA3FBPPgIAAPYAQJrKWFBCFQ6AAfigGn4lhxeIJ1iIY1Z0KgtPpjKJOgcTmc5LlVKgnO55KAA

**Comment by EdamAme-x** [comment]
hmm...
https://www.typescriptlang.org/play/?#code/C4TwDgpgBAyglgWzAGzgMxAHgCoD4oC8UA3lANoDSEI240cAdlANbUD2aU2AugFxeVqtSNygBfKADISYgFChIXCAGdgARkKxEKdFmIBDXmrG55dJaoBMm+ElQZMZNQBpLzgMzdTZxQCkYAPIAcgAKAE6IcMBwAG7QRKoRDADmUAA+UABGbGzIEPpMGQwArgiZEGHpUCXIyFXFDAAmEGiMEI0+0P7BAIJhYfogmgAU3aERCFGx0BljAZkAVhAAxsBVY30DIACUZNydUHOLK2tEpGSsIPyJjMl8h4HjkdFx64+bg2-B80urVWzHP5yBRdR4ANX0yGK8Qe30Ba1m736n0RwXCz2msgOACUVMVkKctHZdI4XFA3FBPPgIAAPYAQJrKWFBCFQ6AAfigGn4lhxeIJ1iIY1Z0KgtPpjKJOgcTmc5LlVKgnO55KxIOZIX0YWU7Rw+CI2DFdIZjSZpGAbDGw22-EYaAqh3EsigSqgw2thHwvm2RolprdPoIXsePxOzpdrt84Zd-DGmu1ut8phjXF9JqZcYmUzi4c52HD-EN4vTUA+WDtDoAqsnXWXMHGtTrGphqzXC2nJQDfsBcyRyBQoIwWOxODxY49402cJQvE6UwwIHEwmrzLjlPjgO5NA2E83ZW4qSvFGuNwAWGzaexYfceWfFyXCyHQ6MRl2cx9sjv+2zS68uA9eC+r5vtUi4VEBwHjmija6jeh7ARG-ALkuEEuny64EgArNu4JPtA97+ucVA0OYQ6XBw5BkhSnj3LK8qUtwggkSIADc4iushDr8MMGgZFuGSWLs3BAA

**Comment by EdamAme-x** [comment]
If the type is primitive, it seems to be correctly inferred.
https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAIgAt0JiBuAKFElkTlIGNs8CiyKB6FgG2ABTNDGo0aPHnBaEQ6OqKFRcAQxZC4AFSEBnGAEklK9ZoQ04cGHpgAuOPqjA0AcxpYastPqs2Aaqr8AK5C9mhBIABGygDaALpwALxwMQCMADQATOkAzHESUg7KAG7KEl4+1voAgmDASXBoQgDuKBQAFACUFnAAdC5CMO09lgDkPFUwo+kjcKq6AJ5obGyJAHyIs5YV8FB6DSy9AFa66O2TAcFC3Za3cHswQVBo93qzHpbdNEIAHgzwMAWYE0Oh8yUBwIguF8NTqBWkAmEohoEM0AHUCK4tEDNMlzJZmpiXPZHM43B5POhKjYAGJBZYwYDoBrnGz2DHoFzY4GdJIbfEyKkQfhCXr8CAuVn6boUnYyQQieDJVgAHlBMDW7VGpBgMDAtik4pYgXI+lG3Tle10YAaqmaqmA8ERit6k16ABIBkMLVTdnogvwlXN7Y7Xtbjqc0F0JJM6QymVGLoEQrzCjBSMBdDJ5po9v8s6oXsoCFAUbT6SxGWcrQGYLy4GmM1njbpNAATCD7DB+-5zNALODF6C6c44uBQsO1uCZxpCUpQTpAA

**Comment by EdamAme-x** [comment]
https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAkgZzAeQEYCsIJjIDeAUMhcnAFzIgCuAtttKQL6mkID2IGqEDDnyE0tdFjwEwAbQC6yALzIZxGgEY2czmACeABxQBlYI30AbYDF0AeACoA+JSRUBpCLrsGUoZAGsPbhhkOzlaOxl3T28FNmQAMhIOPUMQwTB1ZxMzS2sbNWpNB1IUlDt0gCYs0wsrW1KggSEpUWKS72QAKSNMADkABShTYDBgADcUZQwhkABzZAAfZGxubnMIOBBFuiYWKG2Gc3Nt+hAAEwgYUAgz9tTuvoBBKCg4XWcACgeBocYR8ZQS2+wmk22+z1eugAlPI7ihgS0iMpiCoArpaNNQLMwl0ej9hqMJmC8RC3sS+iDCNtuIjkMkOt8AGpwcz0Sa4im0oEkl5k7l9QYEgE6DoAJUE9HMSOQ2VqeRk6gANMgKsqAMxyJwQAAekHOaA5vWZrJQAH5kJlaBU4chxWhJWAqsomSy2cgdXqzgbZblbArlarkBqnObLSqRfc8f04FA0Dd7E5lHZ3bqIPqXGBuN8PlDaKAYNAunTyMhzR8c0onJ0oSnPQaK4oq3jKWASxRzZ028haN9o7H451ihRwrW017DYK-oSICXzXYSyOPWODaTbPnCwBVIel5Crmy9mNxs42Lfbxep9M0kSt9suSLIXxoxqhHtRw-xiKuTXF4d0CATKAIxQO0HTVZwD37Y8GmCCQWzQNpSltCUpQAFmqHI6hsaCmkka94NHdMXRNLtKB3Ii3SXdMfUw7DYMReCSNIncQH-VgmKY18BXfKDvEaOi8O3djaBYgDOCAA

**Comment by EdamAme-x** [comment]
`Simplify<typeof testObjects> extends JSONValue` is falsy

**Comment by EdamAme-x** [comment]
`testObject extends JSONObject ? 1 : 2` is falsy (2)

https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAkgZzAeQEYCsIJjIDeAUMhcnAFzIgCuAtttKQL6mkID2IGqEDDnyE0tdFjwEwAbQC6yALzIZxGgEY2czmACeABxQBlYI30AbYDF0AeACoA+JSRUBpCLrsGUoZAGsPbhhkOzlaOxl3T28FNmQAMhIOPUMQwTB1ZxMzS2sbNWpNB1IUlDt0gCYs0wsrW1KggSEpUWKS72QAKSNMADkABShTYDBgADcUZQwhkABzZAAfZGxubnMIOBBFuiYWKG2Gc3Nt+hAAEwgYUAgz9tTuvoBBKCg4XWcACgeBocYR8ZQS2+wmk22+z1eugAlPI7ihgS0iMpiCoArpaNNQLMwl0ej9hqMJmC8RC3sS+iDCNtuIjkMkOt8AGpwcz0Sa4im0oEkl5k7l9QYEgE6DoAJUE9HMSOQ2VqeRk6gANMgKsqAMxyJwQAAekHOaA5vWZrJQAH5kJlaBU4chxWhJWAqsomSy2cgdXqzgbZblbArlarkBqnObLSqRfc8f04FA0Dd7E5lHZ3bqIPqXGBuN8PlDaKAYNAunTyMhzR8c0onJ0oSnPQaK4oq3jKWASxRzZ028haN9o7H451ihRwrW017DYK-oSICXzXYSyOPWODaTbPnCwBVIel5Crmy9mNxs42Lfbxep9M0kSt9suSLIXxoxqhHtRw-xiKuTXF4d0CATKAIxQO0HTVZwD37Y8GmCCQWzQNpSltCUpQAFmqHI6hsaCmkka94NHdMXRNLtKB3Ii3SXdMfUw7DYMReCSNInd1EY0jXwFd8oO8Ro6Lw7cmO7cMbRAqUAFZ0LlepuJg9I4K1C9x3Is0LUE61EJEsAADYJN9LDpJwuThOQsAAHZnF40FKMU5taVDVSgA

**Comment by EdamAme-x** [comment]
the cause
https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAkgZzMg3sgUMg5OALmQEZcBfXXMATwAcV0wAmZAXm30JPKpr0mqCBgDMnboWQBtANYQ6pDFFABzALqkQAVwC2AI2gDajFACVROgDZgyklsggAPSCAAmaEeOQB+csikrKbClmg2bA6ikS5unt5gEv72QbhAA

**Comment by EdamAme-x** [comment]
The type in interface is not a subtype of object.

**Comment by EdamAme-x** [comment]
This is most likely a specification issue.

https://typescript-jp.gitbook.io/deep-dive/type-system/index-signatures
