### ISSUE TITLE
Issue: dotenv configaration problem

### ISSUE THREAD

**Issue by imran1khan** [honojs/hono#2919]
# i use donenv for configaration like below

![Screenshot 2024-06-06 145016](https://github.com/honojs/hono/assets/107169527/b503ac4a-ef91-48c4-9afc-8e04de272ffe)

## but i am fasing this issue below

![Screenshot 2024-06-06 145304](https://github.com/honojs/hono/assets/107169527/562c6b55-b217-459d-a2ee-e4b3cd68fd59)

how can i configure env files using dotenv
pleases someone help

**Comment by MathurAditya724** [comment]
Cloudflare will load env variables automatically when you start the server. You don't need `dotenv` package.

**Comment by EdamAme-x** [comment]
@imran1khan resolved?

**Comment by imran1khan** [comment]
@MathurAditya724  then where should i supposed to put my env vars

**Comment by imran1khan** [comment]
@EdamAme-x  bro have you found any update, on my side i am still haveing the same issue,

**Comment by MathurAditya724** [comment]
You can place your env variables in the .env file and then access it from the context variable. The runtime will automatically load the file so you can remove the dotenv import.

**Comment by imran1khan** [comment]
@MathurAditya724  bro, look at this [Hono docs](https://hono.dev/docs/getting-started/cloudflare-workers#load-env-when-local-development) i gess this should work, please check it, if it works the i am going to close this issue.

**Comment by MathurAditya724** [comment]
Yes, it should
