### ISSUE TITLE
HTMX example is not working per v4.4

### ISSUE THREAD

**Issue by yvvki** [honojs/hono#2927]
### What version of Hono are you using?

4.4.4

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

- `bun create hono@latest` -> `x-basic`
- `bun i -D typed-htmx`
- Add the snippets from <https://hono.dev/snippets/htmx#typed-htmx>:
  ```ts
  import "typed-htmx";

  declare global {
    namespace Hono {
      interface HTMLAttributes extends HtmxAttributes {
      }
    }
  }
  ```

### What is the expected behavior?

When working with '.tsx' files, `hx-` attributes should be available.

### What do you see instead?

Typescript declaration merging failure.

### Additional information

Was working on v4.3.

**Comment by yvvki** [comment]
I found out that this is due to the `Hono` intrinsic namespace not being declared globally nor exported from the `hono/jsx` module.
A workaround would be importing the <https://github.com/honojs/hono/blob/v4.4.4/src/jsx/intrinsic-elements.ts> manually and declare it:
```ts
import type {} from "../node_modules/hono/dist/types/jsx/intrinsic-elements";
import type {} from "typed-htmx";

declare module "../node_modules/hono/dist/types/jsx/intrinsic-elements" {
	namespace Hono {
		interface HTMLAttributes extends HtmxAttributes {}
	}
}
```

Is there a plan to export the intrinsic namespace?

**Comment by fzn0x** [comment]
Looks like the scope needs to be reduced to intrinsic-elements, fixed by

```diff
130a131,135
>     "./jsx": {
>       "types": "./dist/types/jsx/index.d.ts",
>       "import": "./dist/jsx/index.js",
>       "require": "./dist/cjs/jsx/index.js"
>     },
```

Usage:

```ts
declare module "hono/jsx/intrinsic-elements" {
  namespace Hono {
    interface HTMLAttributes extends HtmxAttributes {}
  }
}
```

**Comment by EdamAme-x** [comment]
or https://github.com/honojs/hono/pull/2936

```ts
declare module "hono/jsx" {
  namespace Hono {
    interface HTMLAttributes extends HtmxAttributes {}
  }
}
```

**Comment by fzn0x** [comment]
Taking back my opinion, it seems there is a namespace error occurring in JSX as well 

This usage isn't working: https://hono.dev/guides/jsx#override-type-definitions

![Screenshot 2024-06-08 002528](https://github.com/honojs/hono/assets/50759463/0e0855a7-18a5-4eda-9b71-e8fc3c5e4c53)

**Comment by fzn0x** [comment]
It is working by export the `intrinsic-elements` declaration types, but ideally we should be able to declare it globally

**Comment by yusukebe** [comment]
Hi @yvvki, thank you for raising the issue. This should be fixed.

@EdamAme-x @fzn0x I've created the PR which implements the one way of resolving this #2937

**Comment by fzn0x** [comment]
Thanks @yusukebe !
