### ISSUE TITLE
`reusePort` in node server

### ISSUE THREAD

**Issue by owenizedd** [honojs/hono#2931]
### What is the feature you are proposing?

I've seen we have Bun.server({ reusePort: true }) but can we add it to node server too?

**Comment by brettimus** [comment]
hey! probably wanna file this on the node-server repo https://github.com/honojs/node-server

and it might be good to provide more context + motivation + links to docs on `reusePort`

as far as i understand, this would only be possible on linux machines

**Comment by fzn0x** [comment]
This is a cool feature, which allows you to run servers concurrently with the same port.

As brettimus says, it's only available in Linux as `SO_REUSEPORT` wasn't supported in MacOS or Windows environment (WSL also not supports it).

**Comment by owenizedd** [comment]
When I try to use `hono` with `pm2` it doesn't work, I read somewhere (couldn't recall), by adding this probably can solve it.

`pm2` can't run `hono` with multiple process that shares same port somehow.. I'm not sure if I'm missing something?

**Comment by fzn0x** [comment]
I think you can try to enable `SO_REUSEPORT` in your Linux environment, let me know if it works.

**Comment by owenizedd** [comment]
I am not sure, this leads to different machine has different experience. Also the approach you suggest I feel it's quite _hacky_ and too related to implementation details of Linux.
If Linux change it in the future, it will broke my production build.

I don't know why Hono can't do this? I mean another web framework - in this case, Express can do the same in my Mac machine:
<img width="335" alt="image" src="https://github.com/honojs/hono/assets/26961166/884319aa-e025-430a-a356-5921b288ffa3">

What do you think? Shouldn't this common clustering be accessible for every OS?

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by fzn0x** [comment]
Actually they just enable `SO_REUSEPORT` under the hood after validate if it's a supported Linux environment.

I don't think adding this to Hono is necessary.

**Comment by owenizedd** [comment]
Can you link me to that? because I can't find this `SO_REUSEPORT` anywhere in their source code.
I honestly it's very beneficial to Hono. This allows dev to have Hono in cluster mode.
Another thing I have to mention, I am not using Linux. So I wonder why it works if they really use something only supported in Linux?

**Comment by fzn0x** [comment]
I don't understand your requirements, but as the docs mentioned Bun reusePort only works in Linux  https://bun.sh/guides/http/cluster
![Screenshot 2024-06-08 221927](https://github.com/honojs/hono/assets/50759463/37960273-da83-4470-97db-bc166e79d87e)

**Comment by owenizedd** [comment]
I got you, I will clarify a little more, I am comparing Hono + Node Server
with ExpressJS.
In Express you can run cluster seamlessly in Mac.
However in Hono + Node Server this is not possible for now.

My guess is that there could be a way to do this in Nodejs http module
because Express already did it and maybe Hono doesn’t utilize it yet (I
could be wrong)

**Comment by fzn0x** [comment]
It's interesting if they have something to do without `SO_REUSEPORT` to implement it.

I will check once I have time, but anyone can assign this issue.

**Comment by owenizedd** [comment]
Im also interested actually to know how does express did it.
If by the time I know how still haven’t implemented, Ill try to make a pr.

**Comment by owenizedd** [comment]
I found out that this is so odd, suddenly I can run cluster in Hono in my Mac:
![image](https://github.com/honojs/hono/assets/26961166/038b970a-7880-476c-864c-34c2a8009972)

Probably this issue never existed, related to my local machine and I don't know what causes it sadly.
I will close this issue, thank you for the help!
