### ISSUE TITLE
CORS MW causes issues with Vary header.

### ISSUE THREAD

**Issue by fishcakeday** [honojs/hono#2932]
https://github.com/honojs/hono/blob/fe7cfcf719dd3107679ca42b5ffc046f71f42246/src/middleware/cors/index.ts#L92

CORS middleware overrides Vary headers without checking for existing ones and causes a lot of issues with variable image types served based on Accept header. Please consider making it so it either merges into existing headers or leaves it alone if it is present.

**Comment by fzn0x** [comment]
Fixed in my PR, review are appreciated.
