### ISSUE TITLE
To ensure that `PatternRouter` should receive only `HttpMethod` as a method for the route

### ISSUE THREAD

**Issue by msensys** [honojs/hono#2938]
### What is the feature you are proposing?

We should add a HttpMethod type at method param [here](https://github.com/honojs/hono/blob/fe7cfcf719dd3107679ca42b5ffc046f71f42246/src/router/pattern-router/router.ts#L10). Additionally, maybe may be good to create docs to this router.

PS: If this issue is approved, I will send a PR.

**Comment by fzn0x** [comment]
> We should add a HttpMethod type at method param [here](https://github.com/honojs/hono/blob/fe7cfcf719dd3107679ca42b5ffc046f71f42246/src/router/pattern-router/router.ts#L10).

I'm agree, I think we should only shows supported HttpMethod type instead of `string`

> maybe may be good to create docs to this router.

We're working for types generated API documentation, you can add JSDoc/TSDoc to your PR.

**Comment by fzn0x** [comment]
List of HTTP methods: https://github.com/for-GET/know-your-http-well/blob/master/methods.md

**Comment by fzn0x** [comment]
You may also need to add the HttpMethod types to other routers, not only `PatternRouter`

**Comment by msensys** [comment]
> You may also need to add the HttpMethod types to other routers, not only `PatternRouter`

I agree with it.

**Comment by msensys** [comment]
@fzn0x, @fzn0x, what do you think about us supporting uncommon HttpMethods? (e.g., `TRACE`)

**Comment by msensys** [comment]
Btw, it may be interesting to create other PR to resolve this

**Comment by usualoma** [comment]
@msensys @fzn0x 

Thanks for considering adding comments!

But do we actually need comments for each PatternRouter method?

I believe that a comment on the inherited source interface is sufficient for developers; the IDE will refer to the inherited source.

I can see the argument that 'routers are exported and should have documentation', but I think the more problematic aspect of 'commenting all inherited classes' is that it generates a lot of duplicate comments and is less maintainable.

In particular, for each router, the general users of hono do not directly call `add()` or `match()`, it is the internal developers who refer to these, and from that perspective, I think the current state where the IDE can check the reference source definitions is sufficient.

I think it is better not to add comments for each method in src/router/pattern-router/router.ts.

**Comment by msensys** [comment]
@usualoma, maybe I had another idea. 

What you said makes sense, but what do you think about us using [METHODS](https://github.com/honojs/hono/blob/fe7cfcf719dd3107679ca42b5ffc046f71f42246/src/router.ts#L17) type for the [method param](https://github.com/honojs/hono/blob/fe7cfcf719dd3107679ca42b5ffc046f71f42246/src/router.ts#L42)?

**Comment by msensys** [comment]
This way, we don't need to export `Method` to all routers.

**Comment by EdamAme-x** [comment]
hi @msensys 
https://github.com/msensys/hono/pull/1

**Comment by EdamAme-x** [comment]
I think adding a type is great, but what about adding a jsdoc? There is a cons to this.
I think the description defined by @module in jsr is sufficient.

**Comment by usualoma** [comment]
@msensys Thank you!

Yes, if we were to specify some type, you are right, the following is a good place to start.

https://github.com/honojs/hono/blob/fe7cfcf719dd3107679ca42b5ffc046f71f42246/src/router.ts#L42

However, allowing arbitrary strings to be specified for method is an intentional setting that is also done in app.on(), so limiting the type here is not the original design intent.

https://github.com/usualoma/hono/blob/ffe92bc45d5dd819d03f7562cf9cc307134c0fa5/src/hono-base.ts#L146

I understand the desire to add a type, but the design type is string, and I don't see how any developer could not understand the following comment, so I think it should remain a string.

https://github.com/usualoma/hono/blob/ffe92bc45d5dd819d03f7562cf9cc307134c0fa5/src/router.ts#L38

**Comment by EdamAme-x** [comment]
> @msensys Thank you!
> 
> Yes, if we were to specify some type, you are right, the following is a good place to start.
> 
> https://github.com/honojs/hono/blob/fe7cfcf719dd3107679ca42b5ffc046f71f42246/src/router.ts#L42
> 
> However, allowing arbitrary strings to be specified for method is an intentional setting that is also done in app.on(), so limiting the type here is not the original design intent.
> 
> https://github.com/usualoma/hono/blob/ffe92bc45d5dd819d03f7562cf9cc307134c0fa5/src/hono-base.ts#L146
> 
> I understand the desire to add a type, but the design type is string, and I don't see how any developer could not understand the following comment, so I think it should remain a string.
> 
> https://github.com/usualoma/hono/blob/ffe92bc45d5dd819d03f7562cf9cc307134c0fa5/src/router.ts#L38

I think same as thing.

**Comment by msensys** [comment]
> @msensys Thank you!
> 
> Yes, if we were to specify some type, you are right, the following is a good place to start.
> 
> https://github.com/honojs/hono/blob/fe7cfcf719dd3107679ca42b5ffc046f71f42246/src/router.ts#L42
> 
> However, allowing arbitrary strings to be specified for method is an intentional setting that is also done in app.on(), so limiting the type here is not the original design intent.
> 
> https://github.com/usualoma/hono/blob/ffe92bc45d5dd819d03f7562cf9cc307134c0fa5/src/hono-base.ts#L146
> 
> I understand the desire to add a type, but the design type is string, and I don't see how any developer could not understand the following comment, so I think it should remain a string.
> 
> https://github.com/usualoma/hono/blob/ffe92bc45d5dd819d03f7562cf9cc307134c0fa5/src/router.ts#L38

Hmm. Do you think we should add the type?

**Comment by usualoma** [comment]
As far as this is concerned, there is no need to put a mould on it. I see no need to add comments or change the code.

**Comment by msensys** [comment]
Ok. Thank you @usualoma @fzn0x @EdamAme-x
