### ISSUE TITLE
Retrive client `addressType` by ip address string

### ISSUE THREAD

**Issue by yasuaki640** [honojs/hono#2943]
### What is the feature you are proposing?

Hello.

I have a feature suggestion for the great getConnInfo helper that was recently added.

Currently, in Cloudflare Workers, the addressType always seems to return `unknown`.

https://github.com/honojs/hono/blob/e72787968fd19f56e5d7cbbc5637b5872e5a2a4a/src/adapter/cloudflare-workers/conninfo.ts#L6

Maybe a function like the following could be written to determine if the addressType is ipv4 or ipv6?

```typescript
function determineAddressType(ip: stirng) {
  if (ip.includes('.')) {
    return 'IPv4'; }
  } else if (ip.includes(':')) {
    return 'IPv6'; }
  } else {
    return 'unknown'; }
  }
}
```

**Comment by yasuaki640** [comment]
If there was some reason, please let me know.

**Comment by EdamAme-x** [comment]
I will try to implement this.
what do you think? @nakasyou

**Comment by fzn0x** [comment]
> If there was some reason, please let me know.
> 
> If you don't mind me correcting it, I will.

I think you can submit a PR for it, we need to sort the parameters correctly, but it will be breaking change, I think they will introduce it in `4.5`.

**Comment by usualoma** [comment]
If it cannot be retrieved from runtime, I feel that `undefined` is better than analogous from a string. I understand that in some cases it may be useful to have this set automatically, but in general, I don't think redundant data should be returned.

```diff
diff --git a/src/adapter/bun/conninfo.ts b/src/adapter/bun/conninfo.ts
index c160add1..2198e2be 100644
--- a/src/adapter/bun/conninfo.ts
+++ b/src/adapter/bun/conninfo.ts
@@ -21,7 +21,7 @@ export const getConnInfo: GetConnInfo = (c: Context) => {
   return {
     remote: {
       address: info.address,
-      addressType: info.family === 'IPv6' || info.family === 'IPv4' ? info.family : 'unknown',
+      addressType: info.family === 'IPv6' || info.family === 'IPv4' ? info.family : undefined,
       port: info.port,
     },
   }
diff --git a/src/adapter/cloudflare-workers/conninfo.ts b/src/adapter/cloudflare-workers/conninfo.ts
index 53d234a1..d2d1624d 100644
--- a/src/adapter/cloudflare-workers/conninfo.ts
+++ b/src/adapter/cloudflare-workers/conninfo.ts
@@ -3,6 +3,5 @@ import type { GetConnInfo } from '../../helper/conninfo'
 export const getConnInfo: GetConnInfo = (c) => ({
   remote: {
     address: c.req.header('cf-connecting-ip'),
-    addressType: 'unknown',
   },
 })
diff --git a/src/adapter/deno/conninfo.ts b/src/adapter/deno/conninfo.ts
index 3a39eaf2..e22bac12 100644
--- a/src/adapter/deno/conninfo.ts
+++ b/src/adapter/deno/conninfo.ts
@@ -12,7 +12,6 @@ export const getConnInfo: GetConnInfo = (c) => {
       address: remoteAddr.hostname,
       port: remoteAddr.port,
       transport: remoteAddr.transport,
-      addressType: 'unknown',
     },
   }
 }
diff --git a/src/helper/conninfo/types.ts b/src/helper/conninfo/types.ts
index ce0ef9fe..64fae2f7 100644
--- a/src/helper/conninfo/types.ts
+++ b/src/helper/conninfo/types.ts
@@ -1,6 +1,6 @@
 import type { Context } from '../../context'
 
-export type AddressType = 'IPv6' | 'IPv4' | 'unknown'
+export type AddressType = 'IPv6' | 'IPv4'
 
 export type NetAddrInfo = {
   /**
```

**Comment by nakasyou** [comment]
It looks good for me.

But I'm worrying, is there runtime what receives domain as ConnInfo? If it's exists, removing `unknown` is bad.

**Comment by yasuaki640** [comment]
If there are no other comments in particular, I will work on it this weekend.

**Comment by fzn0x** [comment]
Thanks @yasuaki640 !

**Comment by usualoma** [comment]
FYI

I've looked it up and made a note of it.

The IP address of the requestor in Deno is in remoteAddr.hostname, where hostname is a string as follows.

 https://deno.land/api@v1.44.1?s=Deno.NetAddr#prop_hostname

However, although it is named `hostname`, the value contained here is always a string of IP addresses. There is no such thing as a domain name in it.

https://github.com/denoland/deno/blob/31154ff95899166a2535fc859c1fca2cbf19d422/ext/http/request_properties.rs#L156-L161
https://github.com/denoland/deno/blob/31154ff95899166a2535fc859c1fca2cbf19d422/ext/http/00_serve.ts#L308-L327

**Comment by usualoma** [comment]
One more point, as an aside, "::ffff:127.0.0.1" is also a correct IPv6 IP address, which could be returned from getConnInfo(). If IPv4 or IPv6 is to be determined from a string, the code in the first comment needs to be modified.

**Comment by yasuaki640** [comment]
close for #2958
