### ISSUE TITLE
Default JSONRespond StatusCode generic arg

### ISSUE THREAD

**Issue by WillSmithTE** [honojs/hono#2953]
### What is the feature you are proposing?

Right now, if I want to specify the generic for context.json, I have to specify both types.

```
return c.json<GetBlogDTO[], StatusCode>(sorted);
```

Is it possible to default StatusCode so I can just specify the data type?

```
return c.json<GetBlogDTO[]>(sorted);
```

Would it be updating [this](https://github.com/honojs/hono/blob/main/src/context.ts#L664) to default `U` to `StatusCode`?

**Comment by EdamAme-x** [comment]
Thanks for the suggestion.
I think it is very good.
I will work on it.

**Comment by WillSmithTE** [comment]
nice 👍
