### ISSUE TITLE
Weird `#private` property in some classes

### ISSUE THREAD

**Issue by movahhedi** [honojs/hono#2955]
### What version of Hono are you using?

4.4.2

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

I've encountered a weird bug when using Hono in a monorepo with client and server.

```ts
// client
import { hc } from "hono/client";
import { type IAppType } from "../../../../../server/api";

const client = hc<IAppType>("http://localhost:3000");
```
On the `hc<IAppType>` it gives the error:
```
Type 'Hono<IHonoEnv, { "/ping": { $get: { input: {}; output: "pong"; outputFormat: "text"; status: 100 | 101 | 102 | 103 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226 | 300 | 301 | ... 47 more ... | -1; }; }; } & { ...; } & { ...; } & { ...; }, "/">' does not satisfy the constraint 'Hono<any, any, any>'.
  Property '#private' is missing in type 'Hono<IHonoEnv, { "/ping": { $get: { input: {}; output: "pong"; outputFormat: "text"; status: 100 | 101 | 102 | 103 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226 | 300 | 301 | ... 47 more ... | -1; }; }; } & { ...; } & { ...; } & { ...; }, "/">' but required in type 'Hono<any, any, any>'.ts(2344)
hono-base.d.ts(65, 5): '#private' is declared here.
```

I investigated more, checking both the "Hono repo (source)", and the "hono package from NPM (build)", it seems the word `#private` is NOT in the source, but is there in the build.
In the build it can be found in these files:
```
3 results - 3 files

dist\types\context.d.ts:
  159  export declare class Context<E extends Env = any, P extends string = any, I extends Input = {}> {
  160:     #private;
  161      /**

dist\types\hono-base.d.ts:
  64  declare class Hono<E extends Env = Env, S extends Schema = {}, BasePath extends string = '/'> {
  65:     #private;
  66      get: HandlerInterface<E, 'get', S, BasePath>;

dist\types\request.d.ts:
  15  export declare class HonoRequest<P extends string = '/', I extends Input['out'] = {}> {
  16:     #private;
  17      /**
```

I've also read the discussion https://github.com/orgs/honojs/discussions/2215 but, not surprisingly, moving it to devDependencies didn't work.

**Comment by insiderins** [comment]
any update? same issue here [](https://github.com/honojs/middleware/issues/567)

**Comment by movahhedi** [comment]
P.S. searching "`#private`" in GitHub isn't easy.

**Comment by insiderins** [comment]
can you help this issue mr @yusukebe

**Comment by yusukebe** [comment]
Can you share a miminal project to reproduce it?

**Comment by movahhedi** [comment]
I've been trying to do so for the last 4 hours.

Is there any reason `#private` exists only in build?

**Comment by yusukebe** [comment]
@movahhedi 

I am not sure about that, as that is what compilers do. But it throws an error if `hc` and `IAppType` do not refer to the same `hono`.

**Comment by fzn0x** [comment]
I'm investigating this issue, and still no clue after 2 hours, I don't know where the private property coming from, I hope with minimal reproductible example, it's easier to track the culprit.

**Comment by movahhedi** [comment]
So how should this be done a monorepo?
```
├───server
├──────package.json
├───client
├──────package.json
├───package.json

```
should we have a hono installed in the root?

**Comment by insiderins** [comment]
> This problem occurs when the `hono` referenced are different. So, if one of them refers to `hono` in path A and the other refers to `hono` in path B, a type mismatch will occur.

which mean
when i used 3rd middleware like OpenAPIHono can't using route from Hono ?

**Comment by yusukebe** [comment]
@insiderins 

> when i used 3rd middleware like OpenAPIHono can't use .route from Hono ?

You can use it. In my environment, it does not throw an error.

![CleanShot 2024-06-10 at 23 28 57@2x](https://github.com/honojs/hono/assets/10682/4b9f9736-bede-48e1-b240-3f2d82c33a12)

**Comment by insiderins** [comment]
> @insiderins
> 
> > when i used 3rd middleware like OpenAPIHono can't use .route from Hono ?
> 
> You can use it. In my environment, it does not throw an error.
> 
> ![CleanShot 2024-06-10 at 23 28 57@2x](https://private-user-images.githubusercontent.com/10682/338228523-4b9f9736-bede-48e1-b240-3f2d82c33a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzA1MTQsIm5iZiI6MTcxODAzMDIxNCwicGF0aCI6Ii8xMDY4Mi8zMzgyMjg1MjMtNGI5Zjk3MzYtYmVkZS00OGUxLWIyNDAtM2YyZDgyYzMzYTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE0MzY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYmEyNjk1ZjNiNmJlNTNhOTI0NzBhNjNmOGU5MzgwZDhkMDBhMmY2YjhiODk3MGY1YWYwNjU3ODY1ZThkYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KOpotHakqILxv-MvBN4bo_Md6W-l2hTTZEDXcCmjUn4)

try adding bindings in routing, and add some api like get, add in openapi routing and hono with same path

get /hello —> from hono
get /hello —> from openapi

**Comment by yusukebe** [comment]
@insiderins 

Sorry. To understand what is happening with your project, please share a minimal project to reproduce it.

**Comment by insiderins** [comment]
> @insiderins
> 
> Sorry. To understand what is happening with your project, please share a minimal project to reproduce it.

idk why mr @yusukebe i try to make minimal project with same method, and working fine.
but its my project with the error instead you can check in [here](https://github.com/insiderins/usman), i will private soon when you checked

**Comment by yusukebe** [comment]
Thank @insiderins !

I've cloned it, but I can't reproduce a bug. I can't run it because the following error is thrown, and the IDE may not show errors. Please tell me the instructions to reproduce it.

![CleanShot 2024-06-11 at 14 27 21@2x](https://github.com/honojs/hono/assets/10682/2dc31d1f-cce8-43c1-95fa-23b0995149a1)

**Comment by insiderins** [comment]
> Thank @insiderins !
> 
> I've cloned it, but I can't reproduce a bug. I can't run it because the following error is thrown, and the IDE may not show errors. Please tell me the instructions to reproduce it.
> 
> ![CleanShot 2024-06-11 at 14 27 21@2x](https://private-user-images.githubusercontent.com/10682/338448191-2dc31d1f-cce8-43c1-95fa-23b0995149a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODQ0MTYsIm5iZiI6MTcxODA4NDExNiwicGF0aCI6Ii8xMDY4Mi8zMzg0NDgxOTEtMmRjMzFkMWYtY2NlOC00M2MxLTk1ZmEtMjNiMDk5NTE0OWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA1MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2Y2RiNDdmYTNkNDFmNmViOTA4MmQ2OTVmNTgxNDA1MzNjYTBlNDRmNzY5OWY4MjU4ZTQwZjVlNDNkYTgxZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hgo2p2i0mGKyznjOmJrmf-HK-TU53sTtl-UPQmmBrn0)

you can set .env with DATABASE_URL="YOURCONNECTIONURL" you can check the document in [here](https://www.prisma.io/docs/orm/reference/connection-urls) 
and you set up database in my file .sql in src/prisma/migration/blabla/migration.sql or you can see in my schema prisma
when the db all set up you can run bunx prisma generate --schema=src/prisma/schema.prisma

**Comment by yusukebe** [comment]
> you can set .env with DATABASE_URL="YOURCONNECTIONURL" you can check the document in [here](https://www.prisma.io/docs/orm/reference/connection-urls) 

Should I run MySQL on my machine? Or I've tried to set it up with SQLite, but it will throw the type error on `schema.prisma`. Sorry, but I can't spend much time on it, If possible, please prepare a project where I can try it in my environment easily.

**Comment by insiderins** [comment]
> > you can set .env with DATABASE_URL="YOURCONNECTIONURL" you can check the document in [here](https://www.prisma.io/docs/orm/reference/connection-urls)
> 
> Should I run MySQL on my machine? Or I've tried to set it up with SQLite, but it will throw the type error on `schema.prisma`. Sorry, but I can't spend much time on it, If possible, please prepare a project where I can try it in my environment easily.

I'm sorry for disturbing your time mr, please check in src/application/web.ts have a error like this ?
![Screen Shot 2024-06-11 at 1 13 25 PM](https://github.com/honojs/hono/assets/147728736/fe24e252-b94b-4c6a-b4fa-cd95ffff7e12)

**Comment by yusukebe** [comment]
@movahhedi 

It does not throw the type errors:

![CleanShot 2024-06-11 at 15 34 18@2x](https://github.com/honojs/hono/assets/10682/e95199e4-3c77-4737-8845-b6ca2a16bfa6)

How about deleting `node_modules` and running `bun install` again?

```
rm -rf node_modules
bun run install
```

**Comment by insiderins** [comment]
> bun run install

i try to remove node_modules and bun run install the error still comeback
let me see your package.json, tsconfig.json, and your bun version mr @yusukebe

**Comment by yusukebe** [comment]
> let me see your package.json, tsconfig.json, and your bun version mr @yusukebe 

These are the same as yours. The Bun version is `1.1.8`. Can you try to clone the code on the remote repo and open it in your IDE?

**Comment by insiderins** [comment]
> > let me see your package.json, tsconfig.json, and your bun version mr @yusukebe
> 
> These are the same as yours. The Bun version is `1.1.8`. Can you try to clone the code on the remote repo and open it in your IDE?

Trying to clone remote not working, maybe create another project and replicate the coding again can solve the issue

**Comment by yusukebe** [comment]
@insiderins 

It's not good that your project contains both `package-lock.json` and `bun.lockb`. How about you remove these and re-install dependencies?

```
rm -rm node_modules bun.lockb package-lock.json
bun install
```

And restart your IDE.

**Comment by insiderins** [comment]
> rm -rm node_modules bun.lockb package-lock.json

ok thanks mr @yusukebe its worked and the error gone 👍 
package-lock.json is a trouble maker

**Comment by fzn0x** [comment]
Glad to hear it is fixed, oh my package-lock.json, good luck in your project 👍

**Comment by yusukebe** [comment]
The @insiderins 's issue might have been closed. But @movahhedi, is your problem solved?

**Comment by movahhedi** [comment]
First of all, thank you all for the help.

As you said, @yusukebe, Installing Hono only in the root of the monorepo fixed it; [Like this](https://github.com/honojs/hono/issues/2955#issuecomment-2158141613). However I still do believe this unknown `#private` issue has to be solved, or at least, we have to figure out how and why it is added at build.

So we can either keep this issue open, or close it and leave the commenting open. What ever you say.

**Comment by yusukebe** [comment]
@yusukebe 

I think this is not a bug in the actual "code." So, I'm removing the `bug` label. But someone may resolve it in the future. I'll leave this open now. Thanks!
