### ISSUE TITLE
jsx/dom : Improve compatibility with React 19

### ISSUE THREAD

**Issue by usualoma** [honojs/hono#2959]
### What is the feature you are proposing?

https://react.dev/blog/2024/04/25/react-19

* [x] [ref as a prop](https://react.dev/blog/2024/04/25/react-19#ref-as-a-prop)
* [x] [use](https://react.dev/blog/2024/04/25/react-19#new-feature-use) 
* [x] [&lt;Context&gt; as a provider ](https://react.dev/blog/2024/04/25/react-19#context-as-a-provider)
    * #2962
* [x] [Cleanup functions for refs ](https://react.dev/blog/2024/04/25/react-19#cleanup-functions-for-refs)
    * #2960 
* [x] [useDeferredValue initial value](https://react.dev/blog/2024/04/25/react-19#use-deferred-value-initial-value)
    * #2960
* [x] [Support for Document Metadata](https://react.dev/blog/2024/04/25/react-19#support-for-metadata-tags)
    * #2960
* [x] [Support for stylesheets](https://react.dev/blog/2024/04/25/react-19#support-for-stylesheets)
    * #2960
* [x] [Support for async scripts](https://react.dev/blog/2024/04/25/react-19#support-for-stylesheets)
    * #2960
* <del>[Support for preloading resources](https://react.dev/blog/2024/04/25/react-19#support-for-preloading-resources)</del>
* [x] [form](https://react.dev/blog/2024/04/25/react-19#form-actions) with useActionState, useFormStatus, useOptimistic
    * #2960
* [x] bump `reactAPICompatVersion`
    * #2963

**Comment by usualoma** [comment]
Hi @yusukebe 
Please create a "react-19-compat" branch. Merge each PR into it, and when it's all together, we can merge "react-19-compat" into "main" or "next".

**Comment by yusukebe** [comment]
@usualoma 

React 19!!!! Created https://github.com/honojs/hono/tree/react-19-compat

**Comment by yusukebe** [comment]
I want to have the [form](https://react.dev/reference/react-dom/components/form).

**Comment by usualoma** [comment]
@yusukebe

Thank you! > react-19-compat

I've added the "form with useActionState, useFormStatus, useOptimistic" to the to-do list!

**Comment by yusukebe** [comment]
Thanks @usualoma !

I like the `action` attribute in `form`, though I've never used React 19 so many times. This makes handling a form action very simple.

```tsx

export default function Form() {
  async function action(formData: FormData) {
    const query = formData.get('query')?.toString() ?? 'no query'
    console.log(query)
  }
  return (
    <form action={action}>
      <input name="query" />
      <button type="submit">Submit</button>
    </form>
  )
}
```

**Comment by usualoma** [comment]
'Support for preloading resources' is a bit tricky compared to the existing JSX behaviour, so I'd like to put it on the back burner and perfect the other features.

**Comment by yusukebe** [comment]
Hey @usualoma 

I think we can close this issue now.

**Comment by usualoma** [comment]
Yes, let's close this!

**Comment by usualoma** [comment]
The following was not implemented but will be considered separately if requested.
[Support for preloading resources](https://react.dev/blog/2024/04/25/react-19#support-for-preloading-resources)

I close this issue as the others have been implemented.

**Comment by sor4chi** [comment]
From React 19, there is an additional function for allocating arrays for caching used by React Compiler under the module name `react/compiler-runtime`, is it correct to assume that this does not directly affect React 19 compatibility and therefore is not provided?

The default value of the so-called React Compiler's `runtimeModule` option is `react/compiler-runtime`, which is the module to use there.
