### ISSUE TITLE
Routes with Path Parameter is overriding other routes with same HTTP method

### ISSUE THREAD

**Issue by mateussmohamed** [honojs/hono#2964]
### What version of Hono are you using?

4.4.5

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

- Create some routes like **ATTENTION, THE ROUTES ORDER SHOULD BE RESPECTED**
```typescript
export const categoriesApi = new Hono()
  .get("/", async (c) => {
    console.log("🚀 ~ .get ~ / ~ categories");
    return c.json({
      data: [
        {
          id: "xx5oa4v9a6sj16d04v646cx3",
          name: "Income",
        },
        {
          id: "g4vfb7e3smwccourud0tnwhh",
          name: "Rent",
        },
        {
          id: "jolfmjbj28r3r5mee4y4vnnz",
          name: "Food",
        },
        {
          id: "u7ce5w9pf3g08hkixupbpk4z",
          name: "Transport",
        },
        {
          id: "q2lmjn9kw8e8a6ft35h773ii",
          name: "Entertainment",
        },
        {
          id: "gsic7nba4d4tfzn5xsclaoj0",
          name: "Health",
        },
        {
          id: "baeep5fe80ui6smmp92wojs9",
          name: "Shopping",
        },
        {
          id: "m0dcult6ggeurnzfed48kw5f",
          name: "Bills",
        },
        {
          id: "vc11mk79xp9kt3ynh70wjsob",
          name: "Utilities",
        },
        {
          id: "du1xnp3zi8yqxqbusdaa7jcd",
          name: "Clothing",
        },
        {
          id: "n310irq9v7ddrqe8azzmrzep",
          name: "Uncategorized",
        },
      ],
    });
  })
  .get("/:id", async (c) => {
    console.log("🚀 ~ .get ~ /:id ~ categories");
    return c.json({
      data: {
        id: "xx5oa4v9a6sj16d04v646cx3",
        name: "Income",
      },
    });
  })
  .get("/top", async (c) => {
    console.log("🚀 ~ .get ~ /top ~ categories");
    return c.json({
      data: [
        {
          name: "Rent",
          value: 3724000,
        },
        {
          name: "Utilities",
          value: 2597000,
        },
        {
          name: "Transport",
          value: 2390000,
        },
      ],
    });
  });

```
- Run the server
- Try request `/` should be work and log `"🚀 ~ .get ~ / ~ categories"`
- Try request `/:id` should be work and log `"🚀 ~ .get ~ /:id ~ categories"`
- Try request `/top`  It will not work. Must call `/:id` route instead `/top` and log `"🚀 ~ .get ~ / ~ categories"` instead `"🚀 ~ .get ~ /:id ~ categories"`

### What is the expected behavior?

Should be call `/top` route instead call `/:id`

### What do you see instead?

I'm seeing the result of `:/id` route calling instead `/top` route call and expected result

### Additional information

One thing that I did to avoid this issue was change the order of the changing routes by adding `/top` before `/:id` declaration.
Another solution was adding a **Regexp** to validate if the id parameter has a minimum of 20 characters.

**Comment by fzn0x** [comment]
I believe no good solutions for this, instead:

> One thing that I did to avoid this issue was change the order of the changing routes by adding `/top` before `/:id` declaration

This is ok to do

---

> Another solution was adding a **Regexp** to validate if the id parameter has a minimum of 20 characters.

This is not good if the `id` could be below 20 characters, no way we implement that in Hono core.

---

Maybe we can try a neat solution to respect the orders:

```
// this parameter will put the path parameters routes before other routes
new Hono({ precedesPathParameters: true })
```

**Comment by fzn0x** [comment]
I believe no good solutions for this, instead:

> One thing that I did to avoid this issue was change the order of the changing routes by adding `/top` before `/:id` declaration

This is ok to do

---

> Another solution was adding a **Regexp** to validate if the id parameter has a minimum of 20 characters.

This is not good if the `id` could be below 20 characters, no way we implement that in Hono core.

---

Maybe we can try a neat solution to respect the orders:

```ts
// this parameter will put the path parameters routes after other routes
new Hono({ precedesPathParameters: true })
```

I can work on this if it is ok @yusukebe

**Comment by yusukebe** [comment]
Hi @mateussmohamed 

Do you want to match `'GET /:id'`

It's not a bug; it's expected behavior. You should write `/top` before `/:id`:

```ts
export const categoriesApi = new Hono()
  .get('/', async (c) => {
    console.log('🚀 ~ .get ~ / ~ categories')
    return c.json({
      //
    })
  })
  .get('/top', async (c) => {
    console.log('🚀 ~ .get ~ /top ~ categories')
    return c.json({
      //
    })
  })
  .get('/:id', async (c) => {
    console.log('🚀 ~ .get ~ /:id ~ categories')
    return c.json({
      //
    })
  })
```

With your code, the access to `GET /top` will match with `get('/:id', handler)`.  The order of route registration is meaningful for Hono routing.

**Comment by mateussmohamed** [comment]
Thanks @fzn0x and @yusukebe.
