### ISSUE TITLE
The date type is converted to string in route defs

### ISSUE THREAD

**Issue by MichailShcherbakov** [honojs/hono#2968]
### What version of Hono are you using?

4.4.5

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

The code below contains the `ts` error. I specified `ctx.json`, but it still doesn't work although it should. 

```ts
new OpenAPIHono()
.openapi(
    createRoute({
      method: "get",
      path: "/example",
      responses: {
        200: {
          content: {
            "application/json": {
              schema: z.object({
                updatedAt: z.date(),
              }),
            },
          },
          description: "",
        },
      },
    }),
    async (ctx) => {
      return ctx.json(
        { updatedAt: new Date(), },
        200
      );
    }
  )
```

### What is the expected behavior?

There shouldn't be any `ts` errors

### What do you see instead?

```
The types of '_data.updatedAt' are incompatible between these types.
          Type 'string' is not assignable to type 'Date'.ts(2345)
```

**Comment by MathurAditya724** [comment]
In JSON when you stringify the content with a `Date` Object it converts it into an ISO string because there is no `Date` primitive in JSON. So, even tho you have defined that the response will be a `Date` instance (because you can do that in `zod`), but in the response, it will be a string, that you can convert into a `Date` instance.

**Comment by MichailShcherbakov** [comment]
@MathurAditya724 The route described above works fine and returns the next response data:

```
{
  "updatedAt": "2024-06-14T09:53:45.546Z"
}
```

So, why should I convert all my dates to strings when `hono` already does it out of the box? Why not just improve the types?

**Comment by yusukebe** [comment]
Hi @MichailShcherbakov ( @MathurAditya724 thank you for handling)

This is not Hono core matter, but `@hono/zod-openapi` matter. I will try to figure out how to handle this issue. Please wait a bit. Thanks.

**Comment by yusukebe** [comment]
Hey @MichailShcherbakov 

Can you try it with `hono/zod-openapi@0.14.4`? It may be solved.

**Comment by MichailShcherbakov** [comment]
@yusukebe Yeah, there are no errors now, thank you

**Comment by adarshaacharya** [comment]
if i want  to share the schema between BE & FE . the backend schema defined has types as z.date() but gets converted into string type on fetching from FE.
