### ISSUE TITLE
typescript definition for `context.req` is broken, defaulting to `any`

### ISSUE THREAD

**Issue by UnsungHero97** [honojs/hono#297]
TS v4.7.2

Here's a small example of how the typescript definition for `context.req` is not correct:

```
const router = new Hono<Environment>();
router.get('/transfer/:token', (c) => {
  const token = c.req.param('token');
  return new Response(token);
})
```

VSCode autocomplete does not work because `.req` is defaulting to `any`.

https://user-images.githubusercontent.com/440299/171968643-bc5f903a-0e87-46a5-91c0-cbd2bdff06d4.mov

<img width="520" alt="Screen Shot 2022-06-03 at 5 04 20 PM" src="https://user-images.githubusercontent.com/440299/171968333-b3b9bc19-d316-45e8-89f3-2fe9da1f8748.png">

**Comment by yusukebe** [comment]
Hi @UnsungHero97 !
Thank you for your feedback. I'm investigating to fix it. Please wait a minute.

@usualoma 
This error has been started when PR is merged #292 . It seems to be about `global declare` for Request.
Do you have any idea?

**Comment by usualoma** [comment]
@yusukebe 
Sorry.

I am not familiar with good practices for exporting "declare global" externally, but I think #298 can fix that.

If Index.ts is to be split into index.js and index.d.ts, where the main modules and types are exported, then it seems reasonable to add it here.

It would be better if it could be written using import statements instead of `<reference path="..." />`, but I didn't know if that was possible.

**Comment by yusukebe** [comment]
@usualoma 

> I am not familiar with good practices for exporting "declare global" externally

I tried looking it up too, but couldn't figure it out. But I just checked #298 and it works. Thank you!

**Comment by yusukebe** [comment]
@UnsungHero97 

PR #298 fixed this issue. I'll release v1.4.4 including this fix soon.

**Comment by UnsungHero97** [comment]
Awesome! I can confirm v1.4.4 is working, thanks! A quick question ...

Why did you choose to extend the `Request` prototype? You already have the `Context` object that I will always need to interact with anyway ... why not attach `params` to the context object, similar to the environment object `c.env`? This way, you do not need to modify the `Request` object (which would have avoided this issue, I think).

**Comment by yusukebe** [comment]
@UnsungHero97 

You're welcome. Thank you for your feedback!

> why not attach params to the context object instead of extending Request?

It's a very good point. That's what I was wondering too. The answer is that I want to put everything about the request into the Request object. I think that would be easier for users to understand.

For example, the Request object has a `header`. Then, let us consider the case that we attach the method to get the header value into the Context object. What should we name the method? `c.header`? But we already use `c.header` to set header value like `c.header('x-custom', 'value')`. `c.getHeader`? Hmm.. I don't like **getThing**. I think it's better to use `c.req.header`. 

That's the reason.

>  It might also be easier to work with in typescript, something like this

Yes it's a good thing. Currently, we can still write following:

<img width="748" alt="" src="https://user-images.githubusercontent.com/10682/172035869-76d9ae5c-2995-4d2a-a915-e6461a65cfd2.png">
