### ISSUE TITLE
Having parameter and query in the same route is not possible

### ISSUE THREAD

**Issue by fishcakeday** [honojs/hono#2982]
### What version of Hono are you using?

4.4.6

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

```typescript
api.get('/:postsid', (c) => {
  const { postsid } = c.req.param()
  const { limit, offset } = c.req.query()
  const posts = getPosts({ postid, limit, offset })
  return c.json({ posts })
})
```

### What is the expected behavior?

I expect for both postid and parameters to work

### What do you see instead?

postid includes `?limit=1&offset=1`

### Additional information

Both '/' and '?' should be treated as a special separator

**Comment by ryuapp** [comment]
The expected behavior occurs. We can get both.

path: `/post/human?limit=1&offset=1`
```ts
import { Hono } from 'hono'

const app = new Hono()

app.get('/post/:postsid', (c) => {
  const { postsid } = c.req.param()
  const { limit, offset } = c.req.query()
  return c.json({postsid, limit, offset}) // result: {"postsid":"human","limit":"1","offset":"1"}
})
export default app
```
We need more information to investigate this issue.

**Comment by yusukebe** [comment]
Hi @fishcakeday 

Your `getPath` is not implemented correctly. It will include query strings `?w=100` as a path. Could you try the following `getPath`?

```ts
const worker = new Hono({
  getPath: (req) => req.url.replace(/^https?:\/(.+?)(?:\?.*)?$/, '$1'),
  strict: true,
})
```

**Comment by yusukebe** [comment]
@fishcakeday 

I've updated the website now. Thank you for making me realize! We can close this issue.

**Comment by yusukebe** [comment]
Or like this?

```ts
getPath: (req) => req.url.replace(/^https?:\/([^?]+).*$/, '$1'),
```

@usualoma How would you write it!?

**Comment by usualoma** [comment]
Hi @fishcakeday @yusukebe 

`replace()` is easy enough to understand and if it works as expected, it should be fine. Performance may be better with `match()`. (This may vary depending on the runtime.)

```ts
(req) => req.url.match(/^(?=https?:\/)([^?]+)/)[0]
```

[replace vs. match](https://perf.link/#eyJpZCI6ImF3dDE0aGM4Z3A2IiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBcImh0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9c1VzWWVJSktRcFVcIiIsInRlc3RzIjpbeyJuYW1lIjoicmVwbGFjZSIsImNvZGUiOiJkYXRhLnJlcGxhY2UoL15odHRwcz86XFwvKFteP10rKS4qJC8sICckMScpIiwicnVucyI6Wzg4NTAwMCwxMjQ4MDAwLDE0NzEwMDAsMzUzMDAwMCw0MTg1MDAwLDIwMDAsMTAwMCwyMDAwLDExNDQwMDAsMTI3NjAwMCwxMzE1MDAwLDg5NDAwMCwzODIwMDAsNzcxMDAwLDI1MjAwMCwxMjY2MDAwLDExMzgwMDAsMTM4MzAwMCw5NTkwMDAsMTAxNTAwMCwxMTA2MDAwLDEzMTUwMDAsMTEzNDAwMCwxMzc0MDAwLDExOTEwMDAsOTEyMDAwLDEzMTUwMDAsMTU5MjAwMCwyMjIwMDAsNjY4MDAwLDIwMDAsOTEwMDAwLDE0OTgwMDAsNjM0MDAwLDExODAwMDAsNzc3MDAwLDg4NjAwMCwxMTY4MDAwLDExNjIwMDAsMjkzNjAwMCw3NTgwMDAsMTIzMDAwMCwxNTQxMDAwLDEzMTUwMDAsNjgyMDAwLDQ5NjAwMCwxMzc3MDAwLDg2NjAwMCw5NjYwMDAsMTA1MjAwMCwxNDQwMDAwLDE0MDgwMDAsMTU5MDAwLDEzMTUwMDAsODUxMDAwLDEyNjUwMDAsMTEzMzAwMCw5ODgwMDAsMTUxNzAwMCwxMTIwMDAwLDc5MjAwMCw5NDMwMDAsMTI3MzAwMCwxMDE2MDAwLDEwNjQwMDAsODA0MDAwLDEzMTUwMDAsNzkyMDAwLDk1NTAwMCw5MzgwMDAsOTAzMDAwLDg3MTAwMCwxMzE1MDAwLDEwMzkwMDAsMTIzMzAwMCwxMzE1MDAwLDEzMTUwMDAsMTI0ODAwMCwxMzE1MDAwLDk5ODAwMCw5NDEwMDAsMTMxNTAwMCwxMzE1MDAwLDE3ODUwMDAsNDA4ODAwMCw0NDgxMDAwLDc4MTAwMCwxMDgyMDAwLDEzMTUwMDAsNDc0MDAwLDQwODAwMCw5MzYwMDAsNjI3MDAwLDcxNTAwMCw3MDMwMDAsNjAxMDAwLDEwMjUwMDAsMTE4MDAwMCwxMzE1MDAwLDcyOTAwMF0sIm9wcyI6MTEzODQwMH0seyJuYW1lIjoibWF0Y2giLCJjb2RlIjoiZGF0YS5tYXRjaCgvXig%2FPWh0dHBzPzpcXC8pKFteP10rKS8pWzBdIiwicnVucyI6WzIyMTQwMDAsMTIzOTAwMCwxMzAzMDAwLDY3ODYwMDAsNzI2MTAwMCw5NzgyMDAwLDkxMzAwMDAsMTAwMCw3ODIwMDAsMTMyNTAwMCw4NzQwMDAsMjMxMDAwLDE3MDAwLDM0MDAwLDczNTcwMDAsODgzMDAwLDY0ODAwMCwxMTQyMDAwLDExMDUwMDAsMjYwMDAwLDEwMjUwMDAsNDk3MDAwLDQ0NjAwMCw5NjcwMDAsOTkxMDAwLDE4MDAwLDEyMTYwMDAsMTMwMzAwMCwyMDAwLDEwMjMwMDAsMjAwMCw3MzIwMDAsMTE1NjAwMCw2MTYwMDAsMzcyMDAwLDExNjYwMDAsODYxMDAwLDEyMDMwMDAsNzU1MDAwLDQ5MDMwMDAsMTA3MzAwMCw1NTEwMDAsMTQ0MzAwMCw4MjEwMDAsNTUzMDAwLDkxNDAwMCwxMjQwMDAwLDEwMDAsMTEzNTAwMCw5MjQwMDAsMTMwMzAwMCwxMTU0MDAwLDg3MDEwMDAsMTMwMzAwMCw5MjY1MDAwLDEzMDMwMDAsMTc3MDAwLDM2NTAwMCwxMzAzMDAwLDExMjkwMDAsNjk0MDAwLDg2MzAwMCw1MTYwMDAsNjQ5MDAwLDEzMDMwMDAsMjI4MDAwLDEzMDMwMDAsNjExMDAwLDEwNzQwMDAsMTA1ODAwMCwzOTYwMDAsOTg2MDAwLDEzMTUwMDAsOTA1MDAwLDg3NzAwMCw3NDEwMDAsMTMwMzAwMCw2NTMwMDAsMTMwMzAwMCwyODUwMDAsNjUzMDAwLDEzMDIwMDAsOTY5MDAwLDE2MDcwMDAsNzI2MTAwMCw5MTQwMDAwLDIwMDAsMTkwMDAsMTMwMzAwMCwyMDAwLDIwMDAsMTgwMDAsMTQ1MDAwLDk2NzAwMCwyNzYwMDAsMjAwMCw4NzEwMDAsMTg3ODAwMCw3MjIwMDAsNTcwMDAwXSwib3BzIjoxNTEwNTgwfV0sInVwZGF0ZWQiOiIyMDI0LTA2LTE5VDEzOjExOjUxLjA0MVoifQ%3D%3D)

**Comment by yusukebe** [comment]
These are very interesting.

> This may vary depending on the runtime.

Yeah. The result may be different, such as between Chrome and Safari.
