### ISSUE TITLE
Routes Not Matching without Wildcard in Hono Framework

### ISSUE THREAD

**Issue by aakashsharma003** [honojs/hono#2986]
### What version of Hono are you using?

4.4.6

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

1. Define a route without a wildcard (e.g., `"/"`) in the routing configuration of Hono.
2. Send a request to the defined route (e.g., `POST, PUT "/"`).

### What is the expected behavior?

Routes defined without wildcards (e.g., `"/"`) should be matched and processed by their respective route handlers.

### What do you see instead?

Requests to routes without wildcards (e.g., `"/"`) result in a 404 Not Found error or do not match the expected route handler.

### Additional information

#  Screenshots 
 - "404 Not Found" PUT request without wildcard
![Screenshot (2023)](https://github.com/honojs/hono/assets/122847899/dfe567bc-f82a-4865-b635-e174b9e3c628)
# Requesting from Postman
![Screenshot (2022)](https://github.com/honojs/hono/assets/122847899/3f3f7cb5-8ea1-44f7-b40b-52b9e44302be)
- Successful PUT Request with Wildcard
![Screenshot (2024)](https://github.com/honojs/hono/assets/122847899/ce2983ff-71d2-4305-a920-6bb4afd75dc2)
# Requesting with Postman and Getting Response
![Screenshot (2025)](https://github.com/honojs/hono/assets/122847899/925fe567-595f-4374-932e-bd67e556cfaa)

**Comment by ryuapp** [comment]
This is not a bug. Paths are finely differentiated.
e.g) `/blog` and `/blog/` are different paths on default.

You can change [strict mode](https://hono.dev/api/hono#strict-mode) to to work as you expect.

```ts
import { Hono } from 'hono'

const app = new Hono({ strict: false }) // <= here
const blog = app.basePath("/blog")

blog.get("/", (c) => c.text("blog"))

export default app
```

**Comment by aakashsharma003** [comment]
I was stuck on this for quite a while, wondering why it wasn't working as expected, so I raised the issue. Thanks for clearing that up and explaining, @ryuapp ! 👍
