### ISSUE TITLE
c.req.json  json serialization ends with \r\ n. cannot be parsed

### ISSUE THREAD

**Issue by YANGLEDUO1** [honojs/hono#2990]
### What version of Hono are you using?

4.4.6

### What runtime/platform is your app running on?

bun

### What steps can reproduce the bug?

![image](https://github.com/honojs/hono/assets/51237368/f4688423-5511-4d1d-89fc-44b7c15e300c)

**Comment by EdamAme-x** [comment]
It seems to be working here.
Can you give me a minimal code?
@YANGLEDUO1 

https://github.com/honojs/hono/tree/b9799e4f45da70e1fe49957b7c29e35208405d91/src#L222
![image](https://github.com/honojs/hono/assets/121654029/3466ce7d-53b1-45c9-817a-72408c6dc06d)

**Comment by YANGLEDUO1** [comment]
> It seems to be working here. Can you give me a minimal code? @YANGLEDUO1
> 
> https://github.com/honojs/hono/tree/b9799e4f45da70e1fe49957b7c29e35208405d91/src#L222 ![image](https://private-user-images.githubusercontent.com/121654029/340901535-3466ce7d-53b1-45c9-817a-72408c6dc06d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njg1NzEsIm5iZiI6MTcxODc2ODI3MSwicGF0aCI6Ii8xMjE2NTQwMjkvMzQwOTAxNTM1LTM0NjZjZTdkLTUzYjEtNDVjOS04MTdhLTcyNDA4YzZkYzA2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMzM3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjEyMTdkZDRmNzQzNTE4MTAzZjBlNTAyYTJiYzRkNTY3ZWVkOGQyMzRmNDQwNWQxYzM1YzQzMzY1YWJmMGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pniPv4vebyzbsAzFSkUjbRLoPKFTWOf1ICSc-0TKKSw)

This is the smallest project I've ever created 

https://github.com/YANGLEDUO1/hono-bug-2990.git

**Comment by EdamAme-x** [comment]
thanks @YANGLEDUO1.
It works in Bun, so it appears to be a Hono issue.

**Comment by EdamAme-x** [comment]
details
![image](https://github.com/honojs/hono/assets/121654029/19992651-a151-4ace-a0ac-6a2620fe5032)

**Comment by EdamAme-x** [comment]
SyntaxError: JSON Parse error: Unrecognized token '\'

**Comment by EdamAme-x** [comment]
problems of escape characters...? hmm

**Comment by yusukebe** [comment]
Hi. @YANGLEDUO1 

It's not a bug. The same problem occurs with a raw request object, which is Web Standards API, not Hono implementation:

```ts
hono.post('/test', async (c) => {
  const data = await c.req.raw.json()
  return c.json(data)
})
```

This is because your `curl` command has not been escaped correctly. Please try the following:

```
curl --request POST http://localhost:6789/test -d $'{ "foo":"bar" }\r\n'
```

Ref: https://stackoverflow.com/questions/3872427/how-to-send-line-break-with-curl
