### ISSUE TITLE
bun create hono@latest got error: Error running hook for x-basic: No such file or directory

### ISSUE THREAD

**Issue by axww** [honojs/hono#2992]
### What version of Hono are you using?

create-hono version 0.9.0

### What runtime/platform is your app running on?

Windows 11, Bun 1.1.13

### What steps can reproduce the bug?

こんにちは、私はWindows環境でBunの最新バージョン1.1.13を使用しており、`bun create hono@latest` コマンドを実行するとエラーが発生します。`cloudflare-pages`の作成が失敗するだけでなく、`x-basic`の作成も同様に失敗します。

```
D:\>bun create hono@latest test
create-hono version 0.9.0
✔ Using target directory … test
? Which template do you want to use? cloudflare-pages
√ Cloning the template
22377 |       projectDependenciesHook.applyHook(templateName, {
22378 |         directoryPath: targetDirectoryPath
22379 |       })
22380 |     );
22381 |   } catch (e) {
22382 |     throw new Error(
                  ^
error: Error running hook for cloudflare-pages: No such file or directory
      at C:\Users\C\AppData\Local\Temp\bunx-3838493032-create-hono@latest\node_modules\create-hono\bin:22382:11

Bun v1.1.13 (Windows x64)
```

`C:\Users\C\AppData\Local\Temp\bunx-3838493032-create-hono@latest\node_modules\create-hono`
エラーディレクトリを確認しましたところ、以下のファイルが存在するのみでした：
```
bin
package.json
README.md
```
どうかご確認いただけますでしょうか。
よろしくお願いいたします。

### What is the expected behavior?

Successfully create template

### What do you see instead?

エラーがある

**Comment by yusukebe** [comment]
Hi @axww 

Is `git` installed on your machine?

**Comment by axww** [comment]
> Hi @axww
> 
> Is `git` installed on your machine?

Hi @yusukebe 
Yes, git installed.

```
C:\Users\C>git -v
git version 2.45.2.windows.1
```

Thank you for confirm!
Best

**Comment by axww** [comment]
@yusukebe I figured out where the issue is!
I haven't install Node.js, NPM and NPX.
After I installed all these, issue solved.

The only development kit I installed before is Bun.
And I followed: https://hono.dev/docs/getting-started/bun
Should there be a warning for Bun users telling them to install Node.js as well?

Thank you!
Best

**Comment by yusukebe** [comment]
Hi, @axww, That's good news.

> Should there be a warning for Bun users telling them to install Node.js as well?

I've tested it on the Linux docker container, which is installed only `bun`. But it woks well. It's weird. I'll close this issue now, but if someone faces this issue, I will reopen it and investigate.

Anyway, thanks!

**Comment by axww** [comment]
@yusukebe
The Bun I ran is Windows version. (Bun supports Windows now)
Maybe it's different with Linux. Whatever now it's fine on my side.
Thank you very much!
Best regards

**Comment by ryuapp** [comment]
I also use Window, and when I uninstalled Node.js and tried it, this problem reproduced, so I opened the issue in create-hono.

**Comment by yusukebe** [comment]
@ryuapp 

Thanks!
