### ISSUE TITLE
Suggestion for Improving Test Coverage of utils/buffer.ts

### ISSUE THREAD

**Issue by yasuaki640** [honojs/hono#2995]
### What is the feature you are proposing?

The equals function in utils/buffer.ts does not appear to be used.

https://app.codecov.io/github/honojs/hono/blob/main/src%2Futils%2Fbuffer.ts#L9

If it is a function used on the user side, I would suggest adding test code.
Or, if it is not going to be used in the future, it would be better to remove it.

If either of these fixes are needed, I will send out a pull request!
If no modifications are needed, the issue should be closed!

**Comment by yusukebe** [comment]
Hi @yasuaki640 

Thank you for your suggestion. It may be no problem to remove it if it's not used anywhere in the `hono` package. But someone may use it (initially, though utils are created for internal use only), and it's not hard to maintain it. So, let's keep it.

Can you write tests? I would really like you to write the whole test for `utils/buffer.ts`.

**Comment by yasuaki640** [comment]
@yusukebe 

> Can you write tests? I would really like you to write the whole test for utils/buffer.ts.

Understood. I will try.
