### ISSUE TITLE
Development dependencies update

### ISSUE THREAD

**Issue by Jayllyz** [honojs/hono#3024]
### What is the feature you are proposing?

I noticed while testing my PR that tools like Vitest were no longer up to date.
Configuring Dependabot or Renovate to update dependencies such as eslint, Prettier, Vitest could improve DX.

**Comment by fzn0x** [comment]
It is breaking changes for Hono development tools, for example [this file](https://github.com/honojs/hono/blob/main/build.ts).

As long as it have no vulnerabilities when package audit, I think we can deprioritize this.
