### ISSUE TITLE
`c.req.valid` does not work in route without path

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#3027]
### What version of Hono are you using?

4.4.7

### What runtime/platform is your app running on?

any

### What steps can reproduce the bug?

```ts
const app = new Hono()

app
  .get('/', (c) => {
    return c.json(0)
  })
  .post(
    validator('json', () => {
      return {
        foo: 'bar',
      }
    }),
    (c) => {
      const foo = c.req.valid('json')
      return c.json(1)
    }
  )
```

### What is the expected behavior?

It does not throw a type error.

### What do you see instead?

![CleanShot 2024-06-24 at 04 24 58@2x](https://github.com/honojs/hono/assets/10682/0ac0d3a0-0219-4546-8985-4ce9705e90f0)

### Additional information

This will be fixed when changing the order for overloading in `HandlerInterface`.

```diff
diff --git a/src/types.ts b/src/types.ts
index 7c9ba8c..ce95d6b 100644
--- a/src/types.ts
+++ b/src/types.ts
@@ -121,22 +121,6 @@ export interface HandlerInterface<
     handler: H<E2, P, I, R>
   ): Hono<IntersectNonAnyTypes<[E, E2]>, S & ToSchema<M, P, I, MergeTypedResponse<R>>, BasePath>

-  // app.get(path, handler)
-  <
-    P extends string,
-    MergedPath extends MergePath<BasePath, P> = MergePath<BasePath, P>,
-    R extends HandlerResponse<any> = any,
-    I extends Input = BlankInput,
-    E2 extends Env = E
-  >(
-    path: P,
-    handler: H<E2, MergedPath, I, R>
-  ): Hono<
-    IntersectNonAnyTypes<[E, E2]>,
-    S & ToSchema<M, MergePath<BasePath, P>, I, MergeTypedResponse<R>>,
-    BasePath
-  >
-
   // app.get(handler x2)
   <
     P extends string = ExtractKey<S> extends never ? BasePath : ExtractKey<S>,
@@ -153,6 +137,22 @@ export interface HandlerInterface<
     BasePath
   >

+  // app.get(path, handler)
+  <
+    P extends string,
+    MergedPath extends MergePath<BasePath, P> = MergePath<BasePath, P>,
+    R extends HandlerResponse<any> = any,
+    I extends Input = BlankInput,
+    E2 extends Env = E
+  >(
+    path: P,
+    handler: H<E2, MergedPath, I, R>
+  ): Hono<
+    IntersectNonAnyTypes<[E, E2]>,
+    S & ToSchema<M, MergePath<BasePath, P>, I, MergeTypedResponse<R>>,
+    BasePath
+  >
+
   // app.get(path, handler x2)
   <
     P extends string,
```

**Comment by yusukebe** [comment]
Hi @NamesMT 

What do you think about this? It will be fixed by changing overload the order them in `HandlerInterface`. But do you have any other ideas?

**Comment by NamesMT** [comment]
Hi @yusukebe,

This is very weird, in my IDE for both the before and after the fix, it's still hinting that the same overload (currently line 140) is used, but after the fix there is no TS error.
Also the overload that is relocated down in the fix won't match with the handler that we're defining, why would it causes an issue, I'll try to put some time investigating it.

**Comment by NamesMT** [comment]
With no changes to the type this also works and have no error:
```
// Pre-create validator middleware
const vad = validator('json', () => {
  return {
    cd: 'bar',
  }
})

const testApp = app
  .post(
    vad,
    (c) => {
      const foo = c.req.valid('json')
      return c.json(1)
    }
  )
```

**Comment by NamesMT** [comment]
The reproduction could further be limited to if validator is used as first middleware:
```ts
const testApp = app
  .post(
    validator('json', () => {
      return {
        cd: 'bar',
      }
    }),
    (c) => {
      const foo = c.req.valid('json') // Error here
      return c.json(1)
    }
  )

const testApp2 = app
  .post(
    validator('json', () => {
      return {
        cd: 'bar',
      }
    }),
    cors(),
    (c) => {
      const foo = c.req.valid('json') // Error here also
      return c.json(1)
    }
  )

const testApp3 = app
  .post(
    cors(),
    validator('json', () => {
      return {
        cd: 'bar',
      }
    }),
    (c) => {
      const foo = c.req.valid('json') // No error here, validator isn't the first middleware
      return c.json(1)
    }
  )
```

**Comment by NamesMT** [comment]
It seems like when using validator as first middleware, the response handler's `Context` cannot infer the validator's `Env` and `Input` and is typed as `<BlankEnv, string, BlankInput>`, this does not happen with other middleware like `cors`, and introducing `cors` into the middleware chain, the context is able is infer `cors`'s types as well.

**Comment by yusukebe** [comment]
@NamesMT 

Thank you for investigating! Hmm, TypeScript is too magical.

If so, in the above case, would it be a good way to encourage users to specify the path as the first argument?

```ts
app
  .get('/', (c) => {
    return c.json(0)
  })
  .post(
    '/', // <=== "Please add it to infer types correctly!"
    validator('json', () => {
      return {
        foo: 'bar',
      }
    }),
    (c) => {
      const foo = c.req.valid('json')
      return c.json(1)
    }
  )
```

**Comment by NamesMT** [comment]
Hi @yusukebe,

Sorry for the delay gap, a bit busy this week,  
Still can't find the root cause yet, could also be a weird TS bug, I think for now maybe we can go with the original workaround, and reorder the overloads one level down.

**Comment by EmmettM** [comment]
Still getting this error if I add explicit typing to c

const validateLogin = validator('json', (value: any) => {
    const { email } = value;
    // validation logic
    return { email }
})

app.post('/login', validateLogin, async (c: Context) => { // added :Context type
    const { email } = c.req.valid('json') // Error: Argument of type 'string' is not assignable to parameter of type 'never'.ts(2345)
})

**Comment by NamesMT** [comment]
Hi @EmmettM,  
This is expected and is normal TypeScript behavior, when you explicitly type `c: Context`, it means that `c` is now an empty default `Context`.  
Thus it cannot access the validate context added by the validator middleware.

You should not explicitly type `c` to let it automatically infer the context composed from the current instance & chain.

**Comment by sergioxro** [comment]
Hey @yusukebe, I'm finding the same bug on zValidator, do you want me to investigate? or do you know what can be the root cause of this?

<img width="841" alt="Image" src="https://github.com/user-attachments/assets/ba451334-f454-4562-b497-32647ad430f0" />

**Comment by yusukebe** [comment]
@sergioxro, Can you create another issue with instructions on how to reproduce it?
