### ISSUE TITLE
`factory.createApp()` will initApp every time it get called and cause some middleware error

### ISSUE THREAD

**Issue by zoubingwu** [honojs/hono#3040]
### What version of Hono are you using?

4.4.8

### What runtime/platform is your app running on?

node.js

### What steps can reproduce the bug?

minimal repro is here: https://stackblitz.com/edit/stackblitz-starters-mj3bxo?file=index.js

after app starts, refresh the page, you'll see `Hello hono!`, this works fine but when you visit or refresh the `/v1/feature` page, you will see errors on console: `Timer "total" does not exist!`.

Is this unexpected bug or am I using this `factory.createApp()` api wrong way?

### What is the expected behavior?

There should be no errors.

### What do you see instead?

errors on console: `Timer "total" does not exist!`

### Additional information

This relates to the implementation of timing middleware; the second createApp call will initialize an empty map and set it on the context, so the first map gets overwritten.

Considering this injecting variables on context behavior is very common for middlewares, the implementation of `factory.createApp()` might need some refine.

**Comment by zoubingwu** [comment]
This relates to the implementation of timing middleware; the second `createApp` call will initialize an empty map and set it on the context, so the first map gets overwritten.

**Comment by zoubingwu** [comment]
considering this injecting variables on context behavior is very common for middlewares, the implementation of `factory.createApp()` might need some refine.

**Comment by yusukebe** [comment]
Hi @zoubingwu 

Thank you for creating the issue. I've investigated it. It is not `factory.createApp()` matter, but it may be Timing Middleware's bug. We can reproduce the bug with the following code:

```ts
import { timing } from 'hono/timing'
import { Hono } from 'hono'

const app = new Hono()
app.use(timing())

const a = new Hono()
a.use(timing())
a.get('/', (c) => c.text('a'))

app.route('/a', a)

export default app
```

I'll continue to fix it.

**Comment by zoubingwu** [comment]
thanks, that was quick!

**Comment by yusukebe** [comment]
Created the another issue #3053. We can close this now. Thanks!
