### ISSUE TITLE
hono/compress throws TypeError: Can't modify immutable headers

### ISSUE THREAD

**Issue by abhishiv** [honojs/hono#3041]
### What version of Hono are you using?

3.3.1

### What runtime/platform is your app running on?

Cloudflare workers

### What steps can reproduce the bug?

Hey all

I just noticed that while using hono@3.3.1 the server returns 500 when hono/compress is enabled

import { compress } from "hono/compress";

const app = new Hono();
app.use(compress());

app.get("/*", serveStatic());
I wondering if anyone else had this issue occurred? Or can suggest a workaround.

**Comment by NicoPlyley** [comment]
Hi @abhishiv,
On Cloudflare Workers, the response body is automatically compressed, so there is no need for this middleware. That is noted as well in the docs [here](https://hono.dev/docs/middleware/builtin/compress#:~:text=On%20Cloudflare%20Workers%2C%20the%20response%20body%20will%20be%20compressed%20automatically%2C%20so%20there%20is%20no%20need%20to%20use%20this%20middleware.)

**Comment by abhishiv** [comment]
Hey @NicoPlyley 

Thanks for your quick reply. I'll close this issue. 

Just FYI, I was able to make it work, but to me it seems that you need to set the "Content-Encoding": "gzip" header first in order for compression to kick in. Otherwise it returns data with no compression. Just mentioning in case it's helpful to someone else.

**Comment by NicoPlyley** [comment]
@abhishiv Good to note. I think this is because Cloudflare only compresses under a certain size otherwise compression is practically useless. I'll check if Cloudflare has docs on this and we can link it to middleware docs as well
