### ISSUE TITLE
npm create hono@latest error at #assembleAndUpdateConfig

### ISSUE THREAD

**Issue by UROjQ6r80p** [honojs/hono#3063]
### What version of Hono are you using?

^4.4.10

### What runtime/platform is your app running on?

Cloudflare pages

### What steps can reproduce the bug?

just running `npm create hono@latest` and then `npm run dev`, it does not work due to error:

`[vite] Internal server error: The Workers runtime failed to start. There is likely additional logging output above.
      at #assembleAndUpdateConfig`

**Comment by NicoPlyley** [comment]
Hi @UROjQ6r80p
What command is being used to run the application in your package.json? If it's wrangler you might need to run the build step to run wrangler.

**Comment by UROjQ6r80p** [comment]
> Hi @UROjQ6r80p What command is being used to run the application in your package.json? If it's wrangler you might need to run the build step to run wrangler.

Hi,
it's just `npm run dev` after creating clean project with `npm create hono@latest`

**Comment by UROjQ6r80p** [comment]
@NicoPlyley I think the problem might be in the wrangler itself and unrelated to hono, i tried older version and it works.

**Comment by NicoPlyley** [comment]
I'm glad it's working now. If there's no else, go ahead and close this issue @UROjQ6r80p
