### ISSUE TITLE
Max Even Listeners Exceeded: Possible Memory Leak -> On Not Found Route

### ISSUE THREAD

**Issue by acropolis11** [honojs/hono#3070]
### What version of Hono are you using?

4.4.6

### What runtime/platform is your app running on?

Vercel

### What steps can reproduce the bug?

My code looks like the following

```typescript
// init hono app
const app = authenticatedApp.createApp().basePath("/api");

// List of API Routes

// Customer
app.route("/", createCustomerApp);
app.route("/", deleteCustomerApp);
app.route("/", updateCustomerApp);

// Item
app.route("/items", createItemApp);
app.route("/", deleteItemApp);
app.route("/", updateItemApp);

// Variant
app.route("/", createVariantApp);
app.route("/", deleteVariantApp);
app.route("/", updateVariantApp);

// Uom
app.route("/", createUomApp);
app.route("/", updateUomApp);

// Webhooks
app.route("/webhooks/clerk", clerkApp);

// Error handler
app.onError(errorHandler);
app.notFound((c) => {
  return c.json({ error: "Not Found" }, 404);
});

// Export the app
export const GET = handle(app);
export const POST = handle(app);
export const PUT = handle(app);
export const DELETE = handle(app);
export const PATCH = handle(app);
``` 

Each one of the apps (e.g createCustomerApp) uses an app generated from 

```typescript
createFactory<Env>()
``` 
 This generated app is different from the main app shown below

```typescript
const app = authenticatedApp.createApp().basePath("/api");
``` 

Visit a route that is not listed in the above routes.

### What do you see instead?

Whenever i visit a route that does not exist, i receive the error

**MaxListenersExceededWarning: Possible Memory Leak.**

### Additional information

I am using the approach indicated on the docs
https://hono.dev/docs/api/routing#grouping-without-changing-base

**Comment by EdamAme-x** [comment]
you can use this

```ts
export default handle(app)
```

and

sry, I cannot reproduce it in my environment.
Can you please provide a minimum project?

**Comment by acropolis11** [comment]
I was able to remove the issue by changing the path "/" denoted in all app.route calls to unique values.

**Comment by EdamAme-x** [comment]
I don't think this is what was intended by Hono-side

**Comment by EdamAme-x** [comment]
https://github.com/honojs/hono/blob/main/src/hono-base.ts#L207

**Comment by yusukebe** [comment]
Hi @acropolis11 

Can you provide a minimal project/repo to reproduce it?

**Comment by yusukebe** [comment]
I'll close this issue because there is no response.
