### ISSUE TITLE
Facing error when using multiple get in a subrouter.

### ISSUE THREAD

**Issue by Manujdixit** [honojs/hono#3086]
### What version of Hono are you using?

4.4.10

### What runtime/platform is your app running on?

Cloudflare workers

### What steps can reproduce the bug?

//get blogs

```jsx
blogRouter.get("/:id", async (c) => {
  const id = Number(c.req.param("id"));
  try {
    return c.json("id endpoint", 200);
  } catch (error) {
    return c.json({ error }, 500);
  }
});
```

//get all bulk blogs

```jsx
blogRouter.get("/bulk", async (c) => {
  try {
    return c.json("bulk endpoint", 200);
  } catch (error) {
    return c.json({ error }, 500);
  }
});
```

### What is the expected behavior?

Result of ‘/bulk’ endpoint must be ‘bulk endpoint’

### What do you see instead?

but i am getting result as ‘id endpoint’ instead.

### Additional information

when i commented out '/:id' endpoint , 'bulk' endpoint is working fine.

**Comment by yusukebe** [comment]
Hi @Manujdixit 

You should write `blogRouter.get("/bulk", ...` above of `blogRouter.get("/:id", ...`.

**Comment by Manujdixit** [comment]
Hi @yusukebe Why was it not working that way?

**Comment by yusukebe** [comment]
@Manujdixit 

I might not say the correct answer, but `blogRouter.get("/:id,"...` will also handle accessing the `/bulk` endpoint.

**Comment by yusukebe** [comment]
I think we can close this issue. If you have any problem related to this, feel free to reopen.
