### ISSUE TITLE
status 204 gives a no response "text" regardless of context message

### ISSUE THREAD

**Issue by amansson** [honojs/hono#3098]
### What version of Hono are you using?

4.4.11

### What runtime/platform is your app running on?

node

### What steps can reproduce the bug?

app.get("/test", (c) => {
    return c.text("Hello Hono!", 204);
});

### What is the expected behavior?

A response body with "Hello Hono!"

### What do you see instead?

no response body

### Additional information

Same with HTTPException(204, { message: "No search data found" });

Also if you enable hono/logger and use it like:
`app.use(logger());`
status: 204 will instead give "internal server error with status: 500"

**Comment by EdamAme-x** [comment]
hmm...
c.text does not change its behavior depending on the statusCode.
Please try it with other runtimes or in a web-enabled environment.

**Comment by EdamAme-x** [comment]
<img width="662" alt="image" src="https://github.com/honojs/hono/assets/121654029/90ec66ab-c667-469a-a421-ff1ffde99d61">
My enviroment

**Comment by KaelWD** [comment]
500 is expected, try `new Response('hello', { status: 204 })` and you'll get a "Response with null body status cannot have body" error.

**Comment by EdamAme-x** [comment]
https://developer.mozilla.org/en/docs/Web/HTTP/Status/204

**Comment by EdamAme-x** [comment]
i think Hono does not have a function/feature to change the response depending on the statusCode, 
I think it is a specification of Response.

**Comment by EdamAme-x** [comment]
<img width="290" alt="image" src="https://github.com/honojs/hono/assets/121654029/7727f3da-b843-4c24-9a11-3b206874a1b7">
in Deno

@amansson 
StatusCode "204" expects the response to be empty.

**Comment by EdamAme-x** [comment]
<img width="204" alt="image" src="https://github.com/honojs/hono/assets/121654029/7f081b03-4f64-41b8-86ce-3d9ca9ae3865">
![image](https://github.com/honojs/hono/assets/121654029/9c6f67dc-daac-40f4-85c6-03cd421b7d13)

**Comment by EdamAme-x** [comment]
@amansson 
Does this solve the problem?

**Comment by amansson** [comment]
I see thanks for the reply and suggestions, will close this as I can see the intent now.
