### ISSUE TITLE
Hono Client infer types

### ISSUE THREAD

**Issue by leognmotta** [honojs/hono#3109]
### What version of Hono are you using?

4.4.9

### What runtime/platform is your app running on?

Nodejs

### What steps can reproduce the bug?

Create a pnpm mono repo, make a simple api with hono and a react project with vite

### What is the expected behavior?

I expect to be able to import AppType and have it typed on react project as shown in the docs

### What do you see instead?

everything is typed incorrect like:

```js
) type AppRoutes = OpenAPIHono<HonoEnv, {
    [x: `/api/workflows/${string}`]: {
        [x: `$${Lowercase<string>}`]: {
            input: Partial<ValidationTargets>;
            output: any;
            outputFormat: string;
            status: StatusCode;
        };
    };
} & {
    ...;
}, "/api">
```

### Additional information

if I create a hc instance in the hono index.ts file it is typed correct, but when I import the AppType to react client it does not, I have `strict: true` in both react/hono project, it is weird because in the backend the interface is perfect.

```js
type AppRoutes = OpenAPIHono<HonoEnv, {
    "/api/workflows/version/:versionId/step/:stepId": {
        $patch: {
            input: {
                param: {
                    versionId: string;
                    stepId: string;
                };
            } & {
                json: {
                    status?: "Failure" | "Pending" | "Success" | undefined;
                    definition?: Record<...> | ... 1 more ... | undefined;
                    actionId?: string | undefined;
                    stepOrder?: number | undefined;
                };
            };
            output: {
                ...;
            };
            outputFormat: "json";
            status: 422;
        } | {
            ...;
        };
    };
    ... 4 more ...;
    "/api/workflows": {
        ...;
    };
} & {
    ...;
}, "/api">

```

**Comment by yusukebe** [comment]
Hi @leognmotta 

This may be caused by the fact that they may not be able to refer to the same `hono` package. We can investigate if you share a minimal project to reproduce it. This may be related to https://github.com/honojs/hono/issues/2955

**Comment by NamesMT** [comment]
This is a known TS limitation, in a monorepo, if you use alias in your `backend` package, you must use [TS Project Reference](https://www.typescriptlang.org/docs/handbook/project-references.html), i.e: enable `composite` in the package where you exports hono and add `reference` in the package that you consume it.

**Comment by leognmotta** [comment]
> This is a known TS limitation, in a monorepo, if you use TS alias, you must use [TS Project Reference](https://www.typescriptlang.org/docs/handbook/project-references.html), i.e: enable `composite` in the package where you exports hono and add `reference` in the package that you consume it.

Thanks for letting me know, I was not aware of this, so I believe we may close this issue since it is not related to hono

**Comment by GabrielHangor** [comment]
> This is a known TS limitation, in a monorepo, if you use TS alias, you must use [TS Project Reference](https://www.typescriptlang.org/docs/handbook/project-references.html), i.e: enable `composite` in the package where you exports hono and add `reference` in the package that you consume it.

Due, your comment saved me couple of days figuring out why types are not working in my repo. MANY THANKS
