### ISSUE TITLE
`File` to `Blob`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#3119]
### What is the feature you are proposing?

This is not a bug or a new big feature but a minor change that will be `fix`.

As @nakasyou said in [this comment](https://github.com/honojs/hono/pull/3117#issuecomment-2218927090), `FormData` can accept `Blob` object as a value. It's better than `File`, that subclass of `Blob`. We have to replace `File` to `Blob`.

**Comment by EdamAme-x** [comment]
hmm.. 

As @nakasyou  said, `File` extends `Blob`

[playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAhlC8UBiBLANtCAPYEB2AJgM5QBCaA9gEZQD8UwATgK7QBcUAZjGkRANwAoUJCg1E5alGy5CJVBjoMW7Ljz5DBAYwp4iwLumiI8EAO7IjACgDaAIgAWuinYC6AGiiPnAOmA47AEptXX0xSioiDkkqG1cEKBtOI1dNHT0DKgiE0wsY2288F1dAoXSw5Iwoyww4hJss6lTBFqA)

But, Node.js is using `string | File`.
So I think current types is better.

https://github.com/nodejs/node/blob/b4e8f1b6bb3616ba222c4513218aa1fa9d543d8e/deps/undici/src/types/formdata.d.ts#L10

**Comment by EdamAme-x** [comment]
According to this jsdoc, if a Blob object is passed to `formData`, it will be a File object named `blob`.

```md
@param value The field's value. This can be [`Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob)
    or [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File). If none of these are specified the value is converted to a string.
@param fileName The filename reported to the server, when a Blob or File is passed as the second parameter. The default filename for Blob objects is "blob". The default filename for File objects is the file's filename.
```

**Comment by nakasyou** [comment]
@EdamAme-x, it's a used in output only.
In your URL, `get` receives `unknown`, and it says that you can receive Blob.[^unknown]

FormValue in Hono is for input, so we should change it.

[^unknown]: https://github.com/nodejs/node/blob/b4e8f1b6bb3616ba222c4513218aa1fa9d543d8e/deps/undici/src/types/formdata.d.ts#L39

**Comment by EdamAme-x** [comment]
@nakasyou 
> FormValue in Hono is for input
  
Can you elaborate on this part?

After parsing, it appears to be treated as just a Record object. [^1]

[^1]: [https://github.com/honojs/hono/blob/ec58511247d7b9c33fff92ea992c127c6363eec0/src/validator/validator.ts#L114](https://github.com/honojs/hono/blob/ec58511247d7b9c33fff92ea992c127c6363eec0/src/validator/validator.ts#L114)

**Comment by nakasyou** [comment]
@EdamAme-x 
> Can you elaborate on this part?

[Client](https://github.com/honojs/hono/blob/ec58511247d7b9c33fff92ea992c127c6363eec0/src/client/client.ts#L45C12-L45C29) uses `ValidationTargets` as input.
BodyData can receive `Blob`, so client should receive `Blob`

**Comment by EdamAme-x** [comment]
Thanks @nakasyou 
I think this requires a change of type between Client and Server.
I'll create PullRequest about this.

**Comment by fzn0x** [comment]
I've been using Hono with Bun in production apps, and I'm using just `Blob` to upload files! so I think it is necessary to do this changes 🚀
