### ISSUE TITLE
4.4.12 breaks client typing when using use with a path

### ISSUE THREAD

**Issue by BryanAbate** [honojs/hono#3122]
### What version of Hono are you using?

4.4.12

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

Stackblitz of the reproduction: https://stackblitz.com/edit/hono-client-typing-issue-middleware?file=src%2Fapp.ts

When using `.use` with a path like `.use('*', myMiddleware)` hono client typings will break. Removing the path `'*'` solves the typing issue.

I suppose https://github.com/honojs/hono/pull/3087 introduced the regression.

**Comment by EdamAme-x** [comment]
types is breaking? or `.use` is breaking?

**Comment by EdamAme-x** [comment]
`.use` always generate `{ [x: string]: never }` 
![image](https://github.com/honojs/hono/assets/121654029/192c4532-58e2-4146-a6c1-50ad41c44d8b)

**Comment by EdamAme-x** [comment]
generics of `.use` was marked at `any`
![image](https://github.com/honojs/hono/assets/121654029/8ea73316-cf79-4503-82f8-70da7e496d36)

**Comment by EdamAme-x** [comment]
`createMiddleware` breaks
![image](https://github.com/honojs/hono/assets/121654029/4b64eaf6-abad-4c00-b250-bcd529df49cf)

**Comment by EdamAme-x** [comment]
I will try to work on this issue.
https://github.com/honojs/hono/blob/main/src/types.ts#L680

**Comment by EdamAme-x** [comment]
tmp
![image](https://github.com/honojs/hono/assets/121654029/24d1e183-31e0-4cf3-9a24-49c643d95d1b)

**Comment by EdamAme-x** [comment]
fixed? I'll add tests
![image](https://github.com/honojs/hono/assets/121654029/fdc0fe3c-0ed0-4372-b163-2db7c430580b)

**Comment by BryanAbate** [comment]
Thank you for looking into the issue @EdamAme-x !
