### ISSUE TITLE
Support SPA like express

### ISSUE THREAD

**Issue by ckken** [honojs/hono#3124]
### What is the feature you are proposing?

app.use(express.static(staticRoot))//dist
app.get('*', (req, res) => res.send(html))//html in dist

**Comment by EdamAme-x** [comment]
Hi @ckken 
hmm....

I think it was already implemented in Hono.

```ts
app.use(serveStatic({ root: staticPath }) }) // dist
app.get('*', (c) => c.html(html)) // html in dist
```

**Comment by ckken** [comment]
we use hono replace express in webpack cli,Absolute root path must be use in express.static

**Comment by EdamAme-x** [comment]
hmm...
I think it's  unnecessary.
You can use a relative path.
```ts
app.use(serveStatic({ root: "./dist" }) }) // dist
app.get('*', (c) => c.html(html)) // html in dist
```

**Comment by ckken** [comment]
The cli does not exist in the project, but is installed through npm, while hono is integrated into the cli, so there are similar demos

**Comment by EdamAme-x** [comment]
I may be mistaken.
Do you want to migrate express to hono?
Do you want to migrate hono to express?
Or another?　@ckken

**Comment by ckken** [comment]
like this https://github.com/honojs/hono/issues/3107

**Comment by EdamAme-x** [comment]
hmm...
I'm not quite sure what the intent is. sorry

please explain the details?

**Comment by ckken** [comment]
fixed it!
```js
import {serveStatic} from 'hono/serve-static'
app.use(
      '*',
      serveStatic({
        root: '/',
        pathResolve(filePath: string) {
          return path.resolve(store.outDir, filePath)
        },
        getContent(filePath, c) {
          return fsp.readFile(filePath)
        },
      }),
    )

```

**Comment by EdamAme-x** [comment]
Good, I'm relieved.
