### ISSUE TITLE
Export type "StatusCode"

### ISSUE THREAD

**Issue by maou-shonen** [honojs/hono#3125]
### What is the feature you are proposing?

I'm creating something like this.

```ts
import { HTTPException } from 'hono/http-exception'

// This is the fastest way I've found so far to get the `StatusCode` type.
import type { Endpoint } from 'hono/types'
type StatusCode = Endpoint['status']

class MyException extends HTTPException {
  constructor(status: StatusCode, something: any) {
    const res = createMyResponse(something)
    super(status, {
      res
    })
  }
}
```

Perhaps you could export StatusCode in /type to make it easier to access? :)

```ts
import type { StatusCode } from 'hono/types'
```

**Comment by EdamAme-x** [comment]
hi @maou-shonen 
thanks for creating this issue.

you can use this
```ts
import type { StatusCode } from 'hono/utils/http-status';
```

**Comment by EdamAme-x** [comment]
types of all
https://github.com/honojs/hono/blob/ec58511247d7b9c33fff92ea992c127c6363eec0/src/utils/http-status.ts#L63
![image](https://github.com/honojs/hono/assets/121654029/2b38969f-9c45-46e7-8ac1-b3168549a10f)

**Comment by maou-shonen** [comment]
> 你好@maou-shonen 感謝您創建此問題。
> 
> 你可以用這個
> 
> ```ts
> import type { StatusCode } from 'hono/utils/http-status';
> ```
Thank you!
I miss ./utils/* exports, it seems that it's not mentioned in the documentation? Perhaps could add this to the docs so that others can find it quickly. :)
