### ISSUE TITLE
[BREAKING] Make JSX middleware `import` more simple

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#313]
Currently, to use JSX middleware, we have to do:

* import `h` and `jsx`
* `app.use` with `jsx()`
* `c.render` to return HTML.

```ts
import { Hono } from 'hono'
import { h, jsx } from 'hono/jsx'

const app = new Hono()

app.use('*', jsx())

app.get('/', (c) => {
  const Layout = (props) => (
    <html>
      <body>{props.children}</body>
    </html>
  )

  return c.render(
    <Layout>
      <p>foo</p>
    </Layout>
  ) // Add <!doctype html>  automatically
})
```

I think it's not so simple.

* We don't need to use `app.use`. When `h` is imported, JSX will be enabled.
* We don't need to use `c.render`. We can use `c.html` with writing `<!doctype html>` instead of it. It's not a bad idea to explicitly declare `<!doctype html>`.
* `h` may be the initial character of a `hyperscript`. I think it's not suitable for SSR.

How about writing like below with `html` template literal tag #312 

```ts
import { Hono } from 'hono'
import { jsx, html } from 'hono/jsx' // `html` is alias of `utils/html`

const app = new Hono()

app.get('/', (c) => {
  const Layout = (props) =>
    html`<!DOCTYPE html>
      <html>
        <body>
          ${props.children}
        </body>
      </html>`

  return c.html(
    <Layout>
      <p>foo</p>
    </Layout>
  )
})
```

These are breaking changes. But, JSX middleware has only just been released, so not many people are using it.

**Comment by usualoma** [comment]
I think it is a good specification. 👍 

It looks concise, easy to understand, and performs well enough, so I think being able to write in this way will be one of Hono's most attractive features.

**Comment by usualoma** [comment]
I feel that this pattern... could be a good option with both well DX and well performance, even when considered as a template engine for JavaScript in general.

**Comment by yusukebe** [comment]
Okay, I'll implement it later.
