### ISSUE TITLE
Function to generate HtmlEscapedString

### ISSUE THREAD

**Issue by usualoma** [honojs/hono#314]
From: https://github.com/honojs/hono/pull/312#issuecomment-1153038921

I am wondering if we should prepare something like `mark_raw`.

https://metacpan.org/pod/Text::Xslate#mark_raw($str-:Str)-:RawStr

Rarely, it may be necessary.

#### Overload `html`

```
const name = 'John &quot;Johnny&quot; Smith' // already escaped
html`I am ${html(name)}`
```

#### Introduce `markRaw` ( or a better name such as `raw` or `escaped`. )

```
const name = 'John &quot;Johnny&quot; Smith' // already escaped
html`I am ${markRaw(name)}`
```

**Comment by yusukebe** [comment]
indeed. How about naming `raw`?
