### ISSUE TITLE
'client' is of type 'unknown' when using route

### ISSUE THREAD

**Issue by bellanoid** [honojs/hono#3148]
### What version of Hono are you using?

4.5.0

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

I have a very basic application structure, which I was hoping to be able to use the client to interact with in next.js to make simple requests. This is with turborepo, `apps/api` and `apps/admin`. The `apps/admin` imports `api` using the workspaces.

This is the api package.json:

```json
{
  "name": "api",
  "types": "./src/app.ts",
  "module": "index.ts",
  "type": "module",
  "scripts": {
    "start": "bun index.ts",
    "dev": "dotenv -e ../../.env -- bun --watch ./**/*.ts"
  },
  "devDependencies": {
    "@types/bun": "latest",
    "dotenv-cli": "^7.4.2",
    "drizzle-orm": "^0.32.0"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "hono": "^4.5.0",
    "@repo/database": "workspace:*"
  }
}
```

This is my api/apps.ts file, very very barebones:

```typescript
import { Hono } from 'hono';
import { logger } from 'hono/logger';
import { usersRouter } from './routes/users';

const app = new Hono();

app.use('*', logger());

const apiRoutes = app
    .basePath('/api')
    .route('/users', usersRouter);


export default app;

export type ApiRoutes = typeof apiRoutes;
```

Now even here doing it within this file:

```typescript
import { hc } from 'hono/client'

const client = hc<ApiRoutes>('');

client // this is now unkown
```

### What is the expected behavior?

The client should have type properties which hints to what is attached to the apiRoutes constant like the following:

```
client.api.users.$get
```

### What do you see instead?

`'client' is of type 'unknown'.`

### Additional information

If I hardcore a .get('/users') then the client seems to pick it up, however, I'm hoping to do this via the routes option.

**Comment by bellanoid** [comment]
You know, I think I actually figured this out and think it's something I've done wrong and wanted to post for the visibility of other users who may come across this issue:

Inside of my `usersRouter` file, I was doing the following:

```typescript
const usersRouter = new Hono();

usersRouter.get(...);
```

Changing this to be chained rather than another line seems to infer the types:

```typescript
const usersRouter = new Hono()
     .get(...)
```

Is this how it has to be defined?

Reading the documentation and best practices, I know it says not to use it like a controller but I would determine that this isn't the same as that and is following the way in which it is set out:

```typescript
import { Hono } from 'hono';
import { z } from 'zod'

import { zValidator } from '@hono/zod-validator';

const usersSchema = z.object({
    name: z.string().min(3),
    email: z.string().email(),
    password: z.string().min(8)
})

export const usersRouter = new Hono();

usersRouter.get(
    '/',
    c => {
        return c.json({ })
    }
)
```

Apologies for the confusion but any guidance would be much appreciated.

**Comment by cybercoder-naj** [comment]
I have the same question but in a different situation. I am building a very big application and I have divided the projects into different "modules", e.g. the `auth` module, the `profile` module, etc. The routes are all accessed on a role-based authentication, hence I need to be able to check if the user has certain permissions. 

---

### Initial Code

```ts
export interface Module {
  name: string;
  routes: Hono;
  accessMap: AccessMap;
}

export const installModule = (app: Hono<Env>, module: Module) => {
  /* some required code to check code invariants */
  
  // The app should use a middleware to throw 403 errors
  // if the role can't access a route.
  app.use(accessMiddleware());

  // group the routes
  app.route(module.name, module.routes);
};
```

There is no way I can actually chain any routes from this code. From `index.ts`, I do:

```ts
const app = new Hono<Env>()

/* setup some middlewares */

installModule(app, auth)
installModule(app, profile)

export default app // <- app: Hono<Env, BlankEnv, "/">
```

---

### Situation 2

I tried changing my approach by introducing an array;

```ts
// index.ts
const app = new Hono<Env>();

/* setup some middlewares */

var routes = new Hono<Env>();
const installedModules: Module[] = [auth, profile];
for (const module in installedModules) {
  routes = routes.route("/", routes).route(module.name, module.routes);
}

export default app;
export type AppRoutes = typeof routes; <- Hono<Env, BlankEnv, "/">
```

--- 

With a modular-based approach to building a big server, it seems very difficult to chain routes together in order to use RPC for testing, and client-side network requests.

**Comment by EdamAme-x** [comment]
Hi @cybercoder-naj 
I think `.route` will inherit types.
But, your code won't inherit types.
Cloud you show me a types of installedModules?

**Comment by cybercoder-naj** [comment]
> Could you show me a types of installedModules?

I am sorry I don't follow; what exactly do you want to see? 

Sorry OP if I am overshadowing your issue here. Should I create a new issue for this?

**Comment by EdamAme-x** [comment]
Sry, I talking about typescript types

**Comment by bellanoid** [comment]
Sorry having had another look through the documentation, I can see that this is described here in the way which I didn't do it originally, you can find that here:

https://hono.dev/examples/grouping-routes-rpc

Happy for this issue to be closed as it is quite evidently an oversight from myself. 

Thanks for all the input!

**Comment by yusukebe** [comment]
Hi @bellanoid 

Can we close this issue?

**Comment by bellanoid** [comment]
> Hi @bellanoid 
> 
> 
> 
> Can we close this issue?
> 
> 

Of course. Many thanks!
