### ISSUE TITLE
Chaining routes in modular application seems impossible

### ISSUE THREAD

**Issue by cybercoder-naj** [honojs/hono#3149]
I am building a very big application and I have divided the projects into different "modules", e.g. the `auth` module, the `profile` module, etc. The routes are all accessed on a role-based authentication, hence I need to be able to check if the user has certain permissions. 

---

### Initial Code

```ts
export interface Module {
  name: string;
  routes: Hono;
  accessMap: AccessMap;
}

export const installModule = (app: Hono<Env>, module: Module) => {
  /* some required code to check code invariants */
  
  // The app should use a middleware to throw 403 errors
  // if the role can't access a route.
  app.use(accessMiddleware());

  // group the routes
  app.route(module.name, module.routes);
};
```

There is no way I can actually chain any routes from this code. From `index.ts`, I do:

```ts
const app = new Hono<Env>()

/* setup some middlewares */

installModule(app, auth)
installModule(app, profile)

export default app // <- app: Hono<Env, BlankEnv, "/">
```

---

### Situation 2

I tried changing my approach by introducing an array;

```ts
// index.ts
const app = new Hono<Env>();

/* setup some middlewares */

var routes = new Hono<Env>();
const installedModules: Module[] = [auth, profile];
for (const module of installedModules) {
  routes = routes.route("/", routes).route(module.name, module.routes);
}

export default app;
export type AppRoutes = typeof routes; <- Hono<Env, BlankEnv, "/">
```

--- 

With a modular-based approach to building a big server, it seems very difficult to chain routes together in order to use RPC for testing, and client-side network requests.

_Originally posted by @cybercoder-naj in https://github.com/honojs/hono/issues/3148#issuecomment-2231959360_

**Comment by cybercoder-naj** [comment]
By @EdamAme-x 's suggestions, I changed the line to `const installedModules: Module[] = [auth, profile] as const satisfies Module[];` but route did not inherit the type.

The types (function signature) of `installModule` is given already in the comment.

**Comment by EdamAme-x** [comment]
Playground

As you said, not typed routes...

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAcgAt0JiBuAKBuDRgFMpcBDAYybgFkIATAK4AbbghpxJcNGxBMAXHADOMKAwDmEqQUHMli1BhpY6HdCrgAjNku4BeaUwDuKCgAoAlLRpm0FhipswqL8fEKiSnAOANpakuJSidKyCnAARAD0bLqkaQA0cUk6eopozq4YngB06kwwbpn5cG4cHlEAfHAcVcwAHvVpyEzBmNkwuR4ehVgFiQlJkjJyiplgBLjAovmFicVM+o4uhhDVtQMZTS1tdp3dfQMAQgCe3GsQG1uT0zQAunA2XXM8CUbBgwCUG32vAEIiY0R+3lE8D2kQc1ls3lw0GavgsIAEcHecACMCCITCsKUbXmkhRUTgKKqezc+P4VSWTDycFZTIgun2UxMNBgTzA3BFYv4ACU+cx6RKmESUVQgA

**Comment by EdamAme-x** [comment]
Explicitly specifying it would solve this problem, but it's not what you're looking for...

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAcgAt0JiBuAKBuDRgFMpcBDAYybgFkIATAK4AbbghpxJcNGxBMAXHADOMKAwDmEqQUHMli1BhpY6HdCrgAjNku4BeaUwDuKCgAoAlLRpm0FhipswqL8fEKiSnAOANpakuJSidKyCnAARAD0bLqkaQA0cUk6eopozq4YngB06kwwbpn5cG4cHlEAfHAcVcwAHvVpyEzBmNkwuR4ehVgFiQlJkjJyiplgBLjAovmFicVM+o4uhhDVtQMZTS1tdp3dfQMAQgCe3GsQG1uT0zQAunA2XXM8CUbBgwCUG32vAEIiY0R+3gyGTgonge0iDmsthqdQaFzyzVaHS6PSY-QayGAcAIEBgaUmiORuGghKBcBAAjg7zgARgQRCYVhSja4iRRQguihDnRVT2bg5-CqSyYBIVsoleimYpMPjZ6KiVhsTEKOPOlyJNxJ9wpVJpdK+iXVkrcvP5TFCMIi0QADD8lSkCa7gu7BV7fU7NSa5UGBZ79tEAIx+5WBvx84Me8LxpMR-ZTGgwJ5gbiF4v8ABKGvscFLTG56KoQA

**Comment by EdamAme-x** [comment]
I think I can create these types (MergeSchema).

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAcgAt0JiBuAKFEljhgE8wBTROAWTagHM2AZQDGpNiACGABQkxS2PASJkKAehbsAztRp00MXrgnCOXCABMArgBsOCGnEdwws0gC44mmFGBo+DpwJLA00PVAwaLF1hdC84ACMJTQ4AXjg0NgB3FAoACgBKWhoYtDjfLwlrW3MzK1tNODSAbQDHeycO51cPACJVCWDSHoAaVs6gkI8M7PCIAoA6ARhcvpG4XOF8xoA+OGF5gwAPZZ7kNirMAbke-PyxrFGO9s7HFzle1TACXGBbEbGOhM2KF0lkchgFksVqo1hstildvsjicAELMDhfCA-P63e40AC6cCSe1i8E0smAmh+wO4FhsbCa+KKtngQIaaUSyUWbBOMOG602Oz2BzYxxWyGAcAIEBgN0Kulw0AFpLgIAscCxcHKMEq1Vq9M0W2ejjZjSlEGCwPmQNyavM8zepH5dutFpCdyiNA0pl4AgAPAAVXZpXIBuCigxocwNCRoZhwAD860OHgD8N2ADcIMBzHApmwM7wthG2FGGrlcimtWhcLw4AAldNwLM5rZJ+t50GFqBFb3cX1CUTiCSB8PHUvRolxxnB-v8NiBppoSwgeK8QklsvV2tQVV02xwBxJu30seRydIR0eXw7uAAOX5bOvNbryAUSYcb83k9mfpvdYAfX5f9d0EbYjznAQRDESQZDkP1BH5O8zwnBovB8PxE3vTsMm7cCcILXgHHzbtDwIvCiiYVgOBAAdzGg4czR4ecGMkP1vU1bVdTYGp92BbYgA

**Comment by NamesMT** [comment]
To use RPC you must chain/register the routes on the initialization of the Hono variable that you exports, like:
```ts
const app = new Hono()
  .get('/', (c) => c.json('list books'))
  .post('/', (c) => c.json('create a book', 201))
  .get('/:id', (c) => c.json(`get ${c.req.param('id')}`))

export type HonoApp = typeof app
```

As you can see in the example, I register the routes at the line of defining/initialization of the `app` variable.

This is a general limitation of TypeScript.

**Comment by NamesMT** [comment]
This is a modular pattern that I am using:
```
const app = honoFactory.createApp()
  // // $Auth
  .route('/auth', authApp)

  // Health check
  .get('/hello', c => c.text(`Hello from Hono \`/api/hello\`! - ${Date.now()}`))

  // Banner app
  .route('/banner', bannerApp)

  // User app
  .route('/user', userApp)

  // Calendar app
  .route('/calendar', calendarApp)

export {
  app as apiApp,
}
```

Generally you should add a middleware to check permission (authentication) at the root of your app or at the registering of each route, in your `Initial Code` pattern, if you register the middleware with a simple `app.use`, it will leak to all routes registered after that, that is not inside the module.

This is my pattern of implementing auth check:
```ts
const app = honoFactory.createApp()
  .get(
    '/highlighted',
    checkAuth('user'),
    async (c) => {
      //
    },
  )

  .get(
    '/banners',
    checkAuth('user'),
    async (c) => {
      //
    },
  )
```

**Comment by cybercoder-naj** [comment]
> Explicitly specifying it would solve this problem, but it may be not what you're looking for.

@EdamAme-x yeah.. I understand that if I manually setup the routes, it would work. But considering the application is big, there may be 10-15 of such modules. A for loop is desired. 

You had a post regarding the MergeSchema type which looked interesting, what made you retract that?

**Comment by EdamAme-x** [comment]
> > Explicitly specifying it would solve this problem, but it may be not what you're looking for.
> 
> @EdamAme-x yeah.. I understand that if I manually setup the routes, it would work. But considering the application is big, there may be 10-15 of such modules. A for loop is desired.

I think this could be solved by creating a dedicated function.
It takes multiple `routes` as arguments and returns merged and typed well instances.
 
> You had a post regarding the MergeSchema type which looked interesting, what made you retract that?

Thanks, But
I thought it might be better to set this up manually if you are going to use this feature.
I didn't explain the use case for MergeSchema very well...

**Comment by EdamAme-x** [comment]
Rewrited
@cybercoder-naj 

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAcgAt0JiBuAKFElkTlIGNs8CiyKB6FgG2ABTNDGp1w0eDACeYIUwCyQqAHMhAZRakhIAIYAFPTFIAaOMrVCjJ8wFE0AN3Nad+9vkIlyGHrPkAzuJ0oiq4eiwKihAAJgCu-AoINHCpcGDGpABccAEwUMBoqilpBHEwQgE5qBg0WDQ0LOh5cABGegEKALxwaEIA7igUABQAlLSNzfCFeXr8iTHR8YkBcD0A2iWpyWm76Zk5AEQ8euWkh6Zbe2UVVb0DQxhjAHTqMMPHF3DDLKNrAHxwFjPCoAD3eh2QQnmmFOJkOo1GVywl12Oz2qQyJiOPDABFwwESFyuuxulRyfUGNQgLzeHx4Xx+fy6gOBYIhACEZAo8RACUTEciaABdOAdIFTXLGYABAmVCyxBJCdbCiY8HhwEAqdQ0XBxNAsGDAdCa7VCABKEHKlQAPAAVOBCcEiGKrJZKlXmZCO51oV2PCD-YbtTrVczPCNku52v7o1K4aDfJpoFpkuB8uBR2MktIhoTPMnDMnPLFmTNWioFiuVJG7eqkoQwOJQNBtDoKcX6gDWGH6rfF3qdFT9q2pNsKuBUcDs5gnU40s7Qk6gcA5gIA-BYzZbrQF7fZzByXICKUJHCpaPUaP4omaAKpoY1oe2AnrDB1Dl2rPRoGRwTfDKCOQxgCcCOBAwAxHAp7nlAfyfiO3yATkc4ruazKAuBkF-Ju5rQfcsETDeW5WK4uh6PaPrDv6P4yJ6q5UV+uT5IUqiviR6gPk+9rrGgcQgK0Kiigh-qoZqiqJHAKSbiAEkKCJqxIKWKFLlOABy5hRipy4oOwm4pIOvr+mOYkAPqLjpGj-NJHGaNo5E2KQNoLrZjk2kecBqYxiF5AURT-p5+F9LB-zWUFZ4qCkMFTlFBEqP8RFyLeVg7rclEKWKv70XY3n+g4zgMRlvmsS4uWrGR+jsWOM62RVFF2oegIAGRwC5a4NMmqbVqsPRail3XBu2ryNvSjK-KBbJDh8UIwnAADq0D8DECKjOGEYzDAcwLO6KzjA0ToMNISVwAAgmAYB2sdPQ3hmUYdZKAjCKIazMCwNpnRdSVBp8e2TCm8BwqQ5qVGAL2PSIMDPIDzwACR0qMQA

**Comment by cybercoder-naj** [comment]
@EdamAme-x thanks man! you are an actual legend for this. Kudos.

**Comment by yusukebe** [comment]
Thanks @EdamAme-x @NamesMT 

@cybercoder-naj Can we close this issue?

**Comment by hafidzlvm** [comment]
its amazing to use what our bros doin about mergeRoutes big thanks to @EdamAme-x  , but it's kind a bit confused while using openAPIRouteHandler, it seems the module that i merge is not appears on the docs, anyone who face issue as me?
