### ISSUE TITLE
hono/client hc<>() breaks when using with BunJS build

### ISSUE THREAD

**Issue by AlbertSabate** [honojs/hono#3150]
### What version of Hono are you using?

4.5.0

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

import the hono/client hc to a file and build it using BunJS Bun.build(). Then try to consume it, this will crash the execution.

### What is the expected behavior?

No errors.

### What do you see instead?

BunJS crash.

### Additional information

Bun related issues:
https://github.com/oven-sh/bun/issues/11079
https://github.com/oven-sh/bun/issues/11880

Migrating the client class ClientRequestImpl to a function fixes the issue.

**Comment by yusukebe** [comment]
Hi @AlbertSabate 

If it's not solved, please provide a minimal project to reproduce it and show an instruction.

**Comment by AlbertSabate** [comment]
Hello, @yusukebe problem is solved. The code is good and working, but check the PR, there are some type improvements and I left one comment on one line which I think is a bug on the scenario where there is a searchParam which is a string[].

Other than that comment and some type improve everything is working fine. I think you can review the PR and if there is something you like I'll keep only those lines.

**Comment by yusukebe** [comment]
@AlbertSabate 

Thanks! For now, we can close this issue.
