### ISSUE TITLE
i want the feature to list all routes like `rails routes`.

### ISSUE THREAD

**Issue by y-okamoto-1113** [honojs/hono#3156]
### What is the feature you are proposing?

hi, i love hono 🔥 
Thank you for your reading 😉 

I want the feature to list all routes like `rails routes`.
This helps new comer to understand a project.

**Comment by yusukebe** [comment]
Hi @y-okamoto-1113 

You can use the `showRoutes` in the Dev helper:

https://hono.dev/docs/helpers/dev#showroutes

**Comment by EdamAme-x** [comment]
@y-okamoto-1113 you can close this issue.

**Comment by yusukebe** [comment]
@EdamAme-x Thank you for pining.

I'll close this issue now.
