### ISSUE TITLE
Issue tracking for experimental features

### ISSUE THREAD

**Issue by cybercoder-naj** [honojs/hono#3159]
### What is the feature you are proposing?

I wish to use `factory.createApp()` but I see it is still experimental (in the docs). I was wondering to what extent is the instability of the function. Is there any issue track for this? What are the known bugs of using `factory.createApp()`?

**Comment by EdamAme-x** [comment]
I have seen people using this in production on several occasions.

**Comment by cybercoder-naj** [comment]
Here's another related issue, i think it would be great [middleware#652](https://github.com/honojs/middleware/issues/652)

**Comment by yusukebe** [comment]
Hi @cybercoder-naj 

It is heavily used, the feeling is good, and we can confirm the design of API is good! I think we can remove the experimental flag. Just wait a bit to make the plan to do it. Thanks!
