### ISSUE TITLE
Output of testClient returns a status function

### ISSUE THREAD

**Issue by cybercoder-naj** [honojs/hono#3166]
### What version of Hono are you using?

4.4.9

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

1. Create a hono app
2. And then test it with `testClient` helper.

The test:
```ts
// TEST
const res = await testClient(app).auth.create.$post(
  {
    json: {
      name: 'test',
      email: 'test@example.org',
      role: 'hacker'
    }
  },
  {
    headers: {
      Cookie: 'auth_session=god_session'
    }
  }
);

console.log(typeof res.status);
expect(res.status).toBe(201);
```

### What is the expected behavior?

I expect `res.status` to give me a `number`

### What do you see instead?

1. `console.log(res.status) ==> [Function]`
1. `console.log(typeof res.status) ==> function`
1. `console.log(res.status.toString()) ==> (status) => {
    this.#isFresh = !1;
    this.#status = status;
  }`
1. `console.log(res.status()) ==> "typescript error" ==> undefined`

### Additional information

This may be very dumb but what is wrong?

**Comment by EdamAme-x** [comment]
I'm checking the issue.

**Comment by EdamAme-x** [comment]
It is correctly inferred types in my environment (v4.5).

```ts
import { Hono } from "../src/hono";
import { testClient } from "../src/helper/testing";

const app = new Hono().post("/auth/create", (c) => c.text("OK"));

const res = await testClient(app).auth.create.$post(
    {
      json: {
        name: 'test',
        email: 'test@example.org',
        role: 'hacker'
      }
    },
    {
      headers: {
        Cookie: 'auth_session=god_session'
      }
    }
);
  
console.log(typeof res.status);
//                                 ^ number
```

**Comment by yusukebe** [comment]
Hi @cybercoder-naj 

I've also tried it. But it works correctly.

**Comment by cybercoder-naj** [comment]
Okay, the issue was *I forgot to end the handler's body in return*.

```ts
new Hono()
  .post('/create', async (c) => {
    /* my funny business */

   return c.json({}, 201) // <<---- THE RETURN
  })
```

![image](https://github.com/user-attachments/assets/59b42eae-c259-43ee-b4d8-3fe69c3ff736)

That was me for the past hour.
