### ISSUE TITLE
Deno throws on `useRequestContext` call

### ISSUE THREAD

**Issue by JakobHock** [honojs/hono#3186]
### What version of Hono are you using?

4.4.11

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

`useRequestContext` doesn't work with the provided example in the documentation [here](https://hono.dev/docs/middleware/builtin/jsx-renderer#userequestcontext) and instead throws `Error: RequestContext is not provided.`

Here a minimal reproduction:
```tsx
import { FC } from "jsr:@hono/hono@^4.5.1/jsx";
import { Hono } from "jsr:@hono/hono@^4.5.1";
import { useRequestContext } from "jsr:@hono/hono@^4.5.1/jsx-renderer";

const app = new Hono();

const RequestUrlBadge: FC = () => {
  const c = useRequestContext();
  return <b>{c.req.url}</b>;
};

app.get("/page/info", (c) => {
  return c.render(
    <div>
      You are accessing: <RequestUrlBadge />
    </div>,
  );
});

Deno.serve(
  {
    port: 8000,
  },
  app.fetch,
);
```

### What is the expected behavior?

It is expected that the user has access to the request context and does not throw in the line:
```ts
const c = useRequestContext();
```

### What do you see instead?

`Error: RequestContext is not provided.`

**Comment by yasuaki640** [comment]
Hi @JakobHock.

If you are using [the official template](https://github.com/honojs/starter/tree/main/templates/deno), what happens if you change deno.json as follows?

```diff
   "compilerOptions": {
-    "jsx": "precompile",
+    "jsx": "react-jsx",
     "jsxImportSource": "hono/jsx"
   }
 }
```

**Comment by yasuaki640** [comment]
In my environment, the jsxRender middleware does not seem to be working properly when jsx is precompiled.

**Comment by JakobHock** [comment]
Hello @yasuaki640,

sadly this doesn't fix the issue.
Tested with deno version 1.45.3.

**Comment by yusukebe** [comment]
Hey @JakobHock !

You have to change the JSX config, as @yasuaki640 said, and add a JSX Renderer middleware:

```tsx
import { jsxRenderer } from 'jsr:@hono/hono@^4.5.2/jsx-renderer'

const app = new Hono()
//...

app.use(jsxRenderer())
```

**Comment by JakobHock** [comment]
Hey @yusukebe,

Still running into the issue running this code: 
```ts
import { FC } from "jsr:@hono/hono@^4.5.1/jsx";
import { Hono } from "jsr:@hono/hono@^4.5.1";
import {
  jsxRenderer,
  useRequestContext,
} from "jsr:@hono/hono@^4.5.1/jsx-renderer";

const app = new Hono();

app.use(jsxRenderer());

const RequestUrlBadge: FC = () => {
  const c = useRequestContext();
  return <b>{c.req.url}</b>;
};

app.get("/page/info", (c) => {
  return c.render(
    <div>
      You are accessing: <RequestUrlBadge />
    </div>,
  );
});

Deno.serve(
  {
    port: 8000,
  },
  app.fetch,
);

```

**Comment by yasuaki640** [comment]
https://github.com/yasuaki640/test-deno-issue-20240725

**Comment by yasuaki640** [comment]
In my environment, the following repository works well.

https://github.com/yasuaki640/test-deno-issue-20240725

**Comment by yusukebe** [comment]
@JakobHock 

Can you add this change?

```diff
   "compilerOptions": {
-    "jsx": "precompile",
+    "jsx": "react-jsx",
     "jsxImportSource": "hono/jsx"
   }
 }
```

**Comment by JakobHock** [comment]
This seems to work.
I think i made a mistake when i tied it before.

I guess there should be an annotation for the middleware when using deno as the documentation mentions that you _need_ to set `jsx` to `precomplie`.
