### ISSUE TITLE
Support for for a wildcard param?

### ISSUE THREAD

**Issue by danawoodman** [honojs/hono#3190]
### What is the feature you are proposing?

I'm wondering, in cases where you have a wildcard in your pathname, could it be named, e.g. `param("*")` or perhaps name it in the path somehow `/some/:path{*}`? 

I understand the first option is problematic if you have multiple wildcards, but having a way to name a wildcard would mean you don't have to parse the URL and extract the values out of the wildcard.

Sorry, if I'm missing a feature that already exists, I did search the docs and issues.

**Comment by yusukebe** [comment]
Hi @danawoodman 

How about the following?

```ts
app.get('/:path{.+}', (c) => {
  return c.text(c.req.param('path'))
})
```

**Comment by danawoodman** [comment]
@yusukebe that should work! should have thought of using regex here!
