### ISSUE TITLE
Custom context type within `bearerAuth`'s `verifyToken` function

### ISSUE THREAD

**Issue by McAllaster** [honojs/hono#3191]
### What is the feature you are proposing?

The current implementation of `bearerAuth` middleware does not seem to support utilizing custom Context typing within its `verifyToken` function.

For example:

```typescript
bearerAuth({
  verifyToken: async (token, c) => {
    const result = c.get('someVariable').whatAmI; // result is `any`
    return result;
  },
});
```

If, similar to custom middleware, we could supply a type for context to utilize, `result` could instead throw a type error if `someVariable` was not expected to be found within the context.

**Comment by codewithvk** [comment]
Can we not write code `c.get<MyObjectType>('somevar').xyz` ?

**Comment by McAllaster** [comment]
> Can we not write code `c.get<MyObjectType>('somevar').xyz` ?

With that I get an error `Type does not satisfy the constraint 'never'.`, perhaps I am trying that incorrectly.

However, and I'm unsure why I didn't think about this before, supplying the typing for context next to the `c` context parameter does work. I was previously only thinking in the headspace of custom middleware being able to supply it sooner .

For example, this approach works currently:
```typescript
type MyVariables = {
  someVariable: {
    whatAmI: boolean;
  };
};

bearerAuth({
  verifyToken: async (token, c: Context<{ Variables: MyVariables }>) => {
    const result = c.get('someVariable').whatAmI; // result is `boolean`
    return result;
  },
});
```

Contrasting to a `customMiddleware` declaration, it's not _too_ different
```typescript
createMiddleware<{ Variables: MyVariables }>(async (c, next) => {
  const result = c.get('someVariable').whatAmI; // result is `boolean`
  await next()
});
```

All that being said, it _might_ still be nice to add support for declaring context for built-in middleware the same was as documented for custom middleware. But it seems much less important to me now than when I opened the issue 😅

**Comment by McAllaster** [comment]
Going to close this since the basic functionality is present.
