### ISSUE TITLE
JSX conflict with React email components

### ISSUE THREAD

**Issue by vickyRathee** [honojs/hono#3197]
### What version of Hono are you using?

4.5.2

### What runtime/platform is your app running on?

Cloudflare pages

### What steps can reproduce the bug?

The JSX has lots of conflicts with `@react-email/components` and unable to build the email templated using `react-email`. Here is my `tsconfig.json`

![image](https://github.com/user-attachments/assets/ed0a1934-ed99-4123-a90d-5eb8c8044fbf)

```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "skipLibCheck": true,
    "lib": [
      "ESNext"
    ],
    "types": [
      "@cloudflare/workers-types",
    ],
    "jsx": "react-jsx",
    "jsxImportSource": "hono/jsx"
  },
}
```

### What is the expected behavior?

There should not be any conflict I guess

### What do you see instead?

JSX conflict with other library compnents

**Comment by yusukebe** [comment]
Hi @vickyRathee 

How about adding the declaration at the top of the code?

```ts
/** @jsxImportSource react */
```

**Comment by vickyRathee** [comment]
@yusukebe Awesome, working fine with that.

**Comment by vickyRathee** [comment]
@yusukebe the latest version of react-email doesn't work. It throws an `Uncaught ReferenceError: MessageChannel is not defined Error`

<img width="983" height="240" alt="Image" src="https://github.com/user-attachments/assets/efb0e87c-e44c-4a20-b2a3-8bc95264f223" />
