### ISSUE TITLE
bearerAuth always giving "Unauthorized"

### ISSUE THREAD

**Issue by waptik** [honojs/hono#320]
I have been spending some time playing around with the `bearerAuth` middleware and it only worked on the first try out of many trials.
I don't know how it worked on first the first try.

Here are some snippets from the worker source code:
- portion of wrangler file
```toml
# workers/product/wrangler.toml

[vars]
CACHE_CONTROL = "max-age=86400"
API_KEY = "abcdefg12345-._~+/="

```
- another portion belonging to the typescript codebase
```ts

// workers/product/bindings.d.ts
export interface Bindings {
  API_URL: string;
  CACHE_CONTROL: string;
  API_KEY: string;
  SECRET_KEY: string;
  CACHE: KVNamespace;
}

declare global {
  function getMiniflareBindings(): Bindings;
  interface Crypto {
    randomUUID(): string;
    randomBytes(num?: number): Buffer;
  }
}


// workers/product/src/api/index.ts
.....

const apiRoute = new Hono<Bindings>();
let token = " ";

const TOKEN_STRINGS = "[A-Za-z0-9._~+/-]+=*";
const PREFIX = "Bearer";

apiRoute.use(
  "*",
  async (ctx, next) => {
    if (ctx.env.API_KEY) {
      // update token with secrets value
      token = ctx.env.API_KEY;
    }

    // below(copied from https://github.com/honojs/hono/blob/master/src/middleware/bearer-auth/index.ts) is to see if the conditions pass
    const headerToken = ctx.req.headers.get("Authorization");
    const regexp = new RegExp("^" + PREFIX + " +(" + TOKEN_STRINGS + ") *$");
    const match = regexp.exec(headerToken!)!;
    const equal = await timingSafeEqual(token, match[1]);

    console.log({ token, headerToken, regexp, match, equal }); // see output in screenshot 1

    await next();
  },
  cors(),
  bodyParse(),
  prettyJSON(),
  bearerAuth({ token })
);

....
```

Now, some snippets from my frontend where I'm using the worker's API:
- I created a utility function to call the api
```ts
// utils/api.ts
....
import * as fetch from "./fetch-wrapper"; //@see https://github.com/calcom/cal.com/blob/855aa56e7766e37773c07e8e77924fe144c171f5/apps/web/lib/core/http/fetch-wrapper.ts
import { BanksApiResponse } from "./types";

export async function getBanks(type: "wallets" | "banks" = "wallets") {
  const token = "abcdefg12345-._~+/=";
  // const token = process.env.WORKERS_PAYSTACK_API_KEY;
  const apiUrl = "http://localhost:8787/api"; //
  // const apiUrl = PAYSTACK_WORKER_API;
  const res = await fetch.get(`${apiUrl}/banks/gh/${type}`, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });
  console.log({ res });

  const json = res as BanksApiResponse;

  return json;
}
```

- Now using the utility function in a nextjs page:
```tsx
// pages/testing.tsx
...
import { getBanks } from "@lib/apis";

export async function getStaticProps() {
  const banks = await getBanks("banks");
  return { props: { banks } };
}


function Home({  banks }: { banks: any }) {
  console.log({ banks });

  return (
    <div className="max-w-xl mx-auto py-8">
      <h1 className="text-3xl font-bold mb-8 text-center">Next.js Example</h1>

    </div>
  );
}
export default Home;

```

Screenshots
![error in cli for worker](https://user-images.githubusercontent.com/1687551/173902465-1391fc31-490a-42b3-b86e-49c201291d42.png)
![error from nextjs page](https://user-images.githubusercontent.com/1687551/173904840-e6342eb3-6ded-46f6-a3db-606b1685f677.png)

**Comment by yusukebe** [comment]
Hi @waptik !

Did you try like a below? You don't have to copy the code inside of Bearer auth middleware.

```ts
app.use(
  '*',
  async (ctx, next) => {
    if (ctx.env.API_KEY) {
      token = ctx.env.API_KEY
    }
    const auth = bearerAuth({ token })
    await auth(ctx, next)
  },
  cors(),
  bodyParse(),
  prettyJSON()
)
```

**Comment by waptik** [comment]
> Hi @waptik !
> 
> Did you try like a below? You don't have to copy the code inside of Bearer auth middleware.
> 
> ```ts
> app.use(
>   '*',
>   async (ctx, next) => {
>     if (ctx.env.API_KEY) {
>       token = ctx.env.API_KEY
>     }
>     const auth = bearerAuth({ token })
>     await auth(ctx, next)
>   },
>   cors(),
>   bodyParse(),
>   prettyJSON()
> )
> ```

The code I copied was just to double-check if the code worked as it should.

Using `bearerAuth` inside the first middleware as you suggested works. Is there a reason why using it as a `chained middleware` didn't work?

**Comment by yusukebe** [comment]
Thank you for trying.

> Is there a reason why using it as a chained middleware didn't work?

I think that the `token` is blank??

```ts
apiRoute.use(
  "*",
  async (ctx, next) => {
    if (ctx.env.API_KEY) {
      // update token with secrets value
      token = ctx.env.API_KEY;
    }
   // ....
  },
  cors(),
  bodyParse(),
  prettyJSON(),
  bearerAuth({ token }) // <------- token is blank????
);
```

**Comment by waptik** [comment]
> Thank you for trying.
> 
> > Is there a reason why using it as a chained middleware didn't work?
> 
> I think that the `token` is blank??
> 
> ```ts
> apiRoute.use(
>   "*",
>   async (ctx, next) => {
>     if (ctx.env.API_KEY) {
>       // update token with secrets value
>       token = ctx.env.API_KEY;
>     }
>    // ....
>   },
>   cors(),
>   bodyParse(),
>   prettyJSON(),
>   bearerAuth({ token }) // <------- token is blank????
> );
> ```

I see. Thanks anyway.
