### ISSUE TITLE
JSX DOM render extremely slow

### ISSUE THREAD

**Issue by luaVolk** [honojs/hono#3201]
### What version of Hono are you using?

4.5.2

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```jsx
import { render } from "hono/jsx/dom";

const root = document.getElementById("root");

render(
	<>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
		<div><span></span></div>
	</>
, root);

```

### What is the expected behavior?

Rendering something of that complexity should be immediate

### What do you see instead?

It takes about 12 seconds to render the code above. Twice as much if I add one more `<div><span></span></div>`

### Additional information

The time it takes for the `render` function to complete increases exponentially with the amount of nodes.
From what I gathered it seems to get stuck in the [findInsertBefore](https://github.com/honojs/hono/blob/cdd48f4fd45633bf9e04a474c3c0d696c365e592/src/jsx/dom/render.ts#L273) function

**Comment by usualoma** [comment]
Hi @luaVolk, Thanks for the report.
I am now investigating!
