### ISSUE TITLE
Durable Object not triggered with Hono

### ISSUE THREAD

**Issue by Soabbar** [honojs/hono#3206]
### What version of Hono are you using?

4.5.2

### What runtime/platform is your app running on?

Cloudflare Worker

### What steps can reproduce the bug?

Here is my route
```javascript
route.get("/ws/:id", ...rideController.getAllWS);
```

Here is the controller
```javascript
export const getAllWS = factory.createHandlers(
	upgradeWebSocket(async (c) => {
		const upgradeHeader = c.req.header("Upgrade");
		if (!upgradeHeader || upgradeHeader !== "websocket") {
			return new Response("Durable Object expected Upgrade: websocket", {
				status: 426,
			});
		}
		const id = c.env.WEBSOCKET_MANAGER.idFromName("global");
		const stub = c.env.WEBSOCKET_MANAGER.get(id);
		return await stub.fetch(c.req.raw);
	}),
);
```

Here is my durable Object coming from Cloudflare docs... https://developers.cloudflare.com/durable-objects/examples/websocket-hibernation-server/

```javascript
import { DurableObject } from "cloudflare:workers";

export class WebSocketManager extends DurableObject {
	async fetch(request) {
		// Creates two ends of a WebSocket connection.
		const webSocketPair = new WebSocketPair();
		const [client, server] = Object.values(webSocketPair);

		// Calling `acceptWebSocket()` informs the runtime that this WebSocket is to begin terminating
		// request within the Durable Object. It has the effect of "accepting" the connection,
		// and allowing the WebSocket to send and receive messages.
		// Unlike `ws.accept()`, `state.acceptWebSocket(ws)` informs the Workers Runtime that the WebSocket
		// is "hibernatable", so the runtime does not need to pin this Durable Object to memory while
		// the connection is open. During periods of inactivity, the Durable Object can be evicted
		// from memory, but the WebSocket connection will remain open. If at some later point the
		// WebSocket receives a message, the runtime will recreate the Durable Object
		// (run the `constructor`) and deliver the message to the appropriate handler.
		this.ctx.acceptWebSocket(server);

		return new Response(null, {
			status: 101,
			webSocket: client,
		});
	}

	async webSocketMessage(ws, message) {
		// Upon receiving a message from the client, reply with the same message,
		// but will prefix the message with "[Durable Object]: " and return the
		// total number of connections.
		ws.send(
			`[Durable Object] message: ${message}, connections: ${this.ctx.getWebSockets().length}`,
		);
	}

	async webSocketClose(ws, code, reason, wasClean) {
		// If the client closes the connection, the runtime will invoke the webSocketClose() handler.
		ws.close(code, "Durable Object is closing WebSocket");
	}
}

```

Here is my wrangler.toml
```toml
[durable_objects]
bindings = [{ name = "WEBSOCKET_MANAGER", class_name = "WebSocketManager" }]

[[migrations]]
tag = "v1"
new_classes = ["WebSocketManager"]
```

### What is the expected behavior?

I am suppose to connect, send a message through websocket and receive an answer back from it.

### What do you see instead?

I can connect to the websocket, but if I send anything, I have no answer back or any errors.

### Additional information

I have deployed this Durable object online, but still having the same behaviour.
Does Hono go through some specific process I am not aware of?

Is the controller part correct?

**Comment by yusukebe** [comment]
Hi @Soabbar 

You don't have to use `upgradeWebSocket()`. What about the following code:

```ts
import { Hono } from 'hono'
import { DurableObject } from 'cloudflare:workers'

const app = new Hono<{
  Bindings: {
    WEBSOCKET_MANAGER: DurableObjectNamespace
  }
}>()

app.get('/ws/:id', async (c) => {
  const upgradeHeader = c.req.header('Upgrade')
  if (!upgradeHeader || upgradeHeader !== 'websocket') {
    return new Response('Durable Object expected Upgrade: websocket', {
      status: 426
    })
  }
  const id = c.env.WEBSOCKET_MANAGER.idFromName('global')
  const stub = c.env.WEBSOCKET_MANAGER.get(id)
  return await stub.fetch(c.req.raw)
})

export class WebSocketManager extends DurableObject {
  async fetch() {
    const webSocketPair = new WebSocketPair()
    const [client, server] = Object.values(webSocketPair)
    this.ctx.acceptWebSocket(server)

    return new Response(null, {
      status: 101,
      webSocket: client
    })
  }

  async webSocketMessage(ws: WebSocket, message: ArrayBuffer | string) {
    ws.send(`[Durable Object] message: ${message}, connections: ${this.ctx.getWebSockets().length}`)
  }

  async webSocketClose(ws: WebSocket, code: number, reason: string, wasClean: boolean) {
    ws.close(code, 'Durable Object is closing WebSocket')
  }
}

export default app
```

**Comment by Soabbar** [comment]
Thanks a lot for reply @yusukebe 
That solved the issue, I thought the entry point still need to enable WS, but actually it wasn't the case.
Misunderstanding from me, thanks for the clarification !

**Comment by Soabbar** [comment]
Thanks a lot for reply @yusukebe
That solved the issue, I thought the entry point still need to enable WS, but actually it wasn't the case.
Misunderstanding from me, thanks for the clarification !

**Comment by 345ml** [comment]
Thank you, everyone.
Does anyone know about this error?

I am using a simple code that is almost the same as the comment above.
Reference: https://developers.cloudflare.com/durable-objects/examples/websocket-hibernation-server/

The situation did not change even when I started the wrangler dev command with the `--remote` option.

If anyone has encountered the same situation and found a solution, I would appreciate it if you could let me know.

```
RangeError: Responses may only be constructed with status codes in the range 200 to 599, inclusive.
```

**Comment by yusukebe** [comment]
@345ml 

Hmm. I can't reproduce it with the codes of the above comment and the [WebSocket Hibernation example](https://developers.cloudflare.com/durable-objects/examples/websocket-hibernation-server/).

**Comment by 345ml** [comment]
@yusukebe 
Thanks!!
I will try continue some way.

**Comment by 345ml** [comment]
I encountered the same error even when I deployed it to Cloudflare Workers for testing.
I might be making some silly mistake.
I will share any updates if I find something.

**Comment by 345ml** [comment]
I tried make new simple project by
`npm create hono@latest my-app`

And here is the code.

```ts
import { Hono } from 'hono'

const app = new Hono()

app.get('/', (c) => {
  return c.text('Hello Hono!', 101) // <--- Add status code
})

export default app
```

I added status code 101 here and accessed localhost:8787 in the browser.
This returns the same RangeError that I was facing.

Am I making some huge misunderstanding…? 🤔

**Comment by yusukebe** [comment]
@345ml 

Basically, the `Response` object can't accept the `101` status code. So it throws the error. You have to implement WebSockets in other ways.

**Comment by 345ml** [comment]
@yusukebe 
Thank you.
It seems my understanding of WebSockets is insufficient.

When I used the sample code in your comment, it worked.
https://github.com/honojs/hono/issues/3206#issuecomment-2269013293

I’ll compare it with my original code and investigate what’s wrong.
Thank you for your support.

**Comment by Stradi** [comment]
@345ml, had the same issue. Turns out that `cors` middleware was the culprit. Once I removed cors middleware from my websocket endpoint, everything started working correctly.

**Comment by 345ml** [comment]
@Stradi 
Maybe my situation is same reason.
I'm using `cors` middleware to entire app.
Thanks!!!

**Comment by khakimov** [comment]
Aha, in https://github.com/honojs/hono/blob/a2ec84866b21fe830d88ebb5f69e32b3bdfe71fc/src/middleware/cors/index.ts

The CORS middleware is intercepting WebSocket upgrade requests (which should have status 101) and trying to handle them as regular CORS requests. Is it the right place to impliment? 

```typescript
  return async function cors(c, next) {
    function set(key: string, value: string) {
      c.res.headers.set(key, value)
    }

    // const allowOrigin = findAllowOrigin(c.req.header('origin') || '', c)
    const isWebSocket = c.req.header('Upgrade')?.toLowerCase() === 'websocket'
    const origin = c.req.header('origin') || ''
    const allowOrigin = findAllowOrigin(origin, c)

    if (isWebSocket) {
      // For WebSocket, only check origin and let it through
      const origin = c.req.header('origin') || ''
      const allowOrigin = findAllowOrigin(origin, c)
      if (!allowOrigin) {
        return new Response('Forbidden', { status: 403 })
      }
      // Don't set any CORS headers for WebSocket - let the upgrade proceed normally
      return next()
    }
...
```

**Comment by SDIjeremy** [comment]
is there a fix for this? because this wasn't always the case if you use the CORs middleware on a Websocket endpoint

**Comment by bolasblack** [comment]
This is a temporary workaround to fix the issue:

```typescript
export const honoEnableCors = (): MiddlewareHandler => {
  const middleware = cors({...})

  return async (c, next) => {
    const isWebSocket = c.req.header("Upgrade")?.toLowerCase() === "websocket"

    if (isWebSocket) {
      return next()
    }

    return middleware(c, next)
  }
}
```
