### ISSUE TITLE
Support for Cloudflare Pages?

### ISSUE THREAD

**Issue by ryker2000** [honojs/hono#321]
https://developers.cloudflare.com/pages/platform/functions/

**Comment by yusukebe** [comment]
Hi @ryker2000 

Yes. You can write "Functions" with [Module Worker syntax](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#syntax-module-worker). There is an example for Cloudflare Pages. See the below URL:

<https://github.com/honojs/examples/tree/master/pages>
