### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Bobetti** [honojs/hono#3211]
### What version of Hono are you using?

4.5.1

### What runtime/platform is your app running on?

vercel

### What steps can reproduce the bug?

I’m trying to create a simple Vercel function running on a node environment using the Hono framework.

Using these steps: https://hono.dev/docs/getting-started/vercel

`npm create hono@latest my-app

npm i`

instead of “npm run dev” I must call “npm run start,” not according to Hono documentation, strange.

npm i @hono/node-server

replacing handle from

import { handle } from 'hono/vercel’ to
import { handle } from “@hono/node-server/vercel”;

Creating .env file and adding: NODEJS_HELPERS=0

Also adding to package.json “type”: “module”

starting the server: npm run start

opening the browser: http://localhost:3000/api and seeing “{“message”:“Hello Hono!”}”

Everything looks great.

Now I’m adding the test.ts file into /api

Contents: export const myName = "Bob";

In /api/index.ts changing

return c.json({ message: "Hello Hono!" });

to

return c.json({ message: Hello ${myName} });

and adding

import { myName } from "./test";

starting the server: npm run start

no errors

Opening in browser: http://localhost:3000/api

and getting the error: Error: Cannot find module ‘…\test\vercel\my-app\api\test’ imported from …\test\vercel\my-app\api\index.ts

Just stuck for a whole day and don't know what to do next.

Any help is greatly appreciated.

### Additional information

source code: https://github.com/Bobetti/vercel-test

**Comment by EdamAme-x** [comment]
Is there any possibility that an extension (.ts, .js) may be needed?  
There is a possibility that it is necessary depending on the configuration.

**Comment by EdamAme-x** [comment]
Hello @Bobetti 

I added the `.ts` extension and it works fine.  
Perhaps this is a vercel specification.  
Please change tsconfig as follows  

```json
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "ESNext",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "skipLibCheck": true,
        "strict": true,
        "noEmit": true,
        "allowImportingTsExtensions": true
    }
}
```

And you should rewrite
```ts
import { myName } from "./test.ts";
```

**Comment by Bobetti** [comment]
Not working for me at all:
![image](https://github.com/user-attachments/assets/dc0f43b1-eb59-44b7-ac8f-230a5e2d5d58)

**Comment by Bobetti** [comment]
Windows 10 machine, Node v21.7.1

**Comment by EdamAme-x** [comment]
I'm using Linux.
Sorry, I can't seem to reproduce this in my environment.

**Comment by EdamAme-x** [comment]
Hello @Bobetti 
Try running tsconfig again without changing anything.
That should work.

**Comment by EdamAme-x** [comment]
@Bobetti 
This problem is a limitation of Node.js and can be solved by adding `.js` to the extension. It is an odd way to write it, but give it a try. No need to rename the file.

```ts
import { Hono } from "hono";
import { handle } from "@hono/node-server/vercel";
import { myName } from "./test.js";

// export const config = {
//   runtime: 'edge'
// }

const app = new Hono().basePath("/api");

app.get("/", (c) => {
    return c.json({ message: `Hello ${myName}` });
});

export default handle(app);
```

**Comment by Bobetti** [comment]
No suggestion worked. Still get the same error as above. But you gave me idea that the problem is inside tsconfig.json.
After googling and testing many different tsconfig.json variations, finally the following tsconfig.json content did the trick:

`{
    "compilerOptions": {
        "target": "es2021",
        "module": "es2022",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "skipLibCheck": true,
        "strict": true,
        "baseUrl": "./api",
        "resolveJsonModule": true,
        "allowJs": true,
        "checkJs": false,
        "noEmit": true,
        "isolatedModules": true,
        "allowSyntheticDefaultImports": true,
        "forceConsistentCasingInFileNames": true,
        "paths": {
            "@lib/*": ["/src/lib/*"]
        }
    },
    "ts-node": {
        "experimentalSpecifierResolution": "node",
        "transpileOnly": true,
        "esm": true
    },
    "include": ["api/**/*.ts"],
    "exclude": ["node_modules"]
}
`

Don't know what it all means, but at least on my machine, now I can see the proper result:
`{"message":"Hello Bob"}`

Thank you for your effort!

**Comment by EdamAme-x** [comment]
@Bobetti 
I'm glad it works.
Please close this issue.
