### ISSUE TITLE
CORS No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by Bobetti** [honojs/hono#3214]
### What version of Hono are you using?

4.5.1

### What runtime/platform is your app running on?

Vercel, node

### What steps can reproduce the bug?

I have two applications running on the local machine:
- client: static svelte application: http://localhost:5001/
- server: vercel function with honojs: http://localhost:3000/api/pricing

When client application sends POST request to the server from browser, getting error regarding cors.
Of course, no errors using Postman windows app. Server responds with needed data.

Client side code:
![image](https://github.com/user-attachments/assets/2f3edfc8-e914-4423-824c-5d432f015ab9)

Server side code, post method just not on the screenshot, but it is present . Showing cors configuration:
![image](https://github.com/user-attachments/assets/76eb2030-f88f-4f41-ac20-3bbc54bcd42e)

Errors from browser: 
![image](https://github.com/user-attachments/assets/6606b430-14df-4e8d-b976-6588d0de7023)
![image](https://github.com/user-attachments/assets/f0f63093-c92c-4c88-898e-61c0053c2e1e)
![image](https://github.com/user-attachments/assets/7785e95e-4ace-411e-a436-cf02d68b698e)

I tried all solutions suggested here:
https://github.com/honojs/hono/issues/895
https://github.com/honojs/hono/issues/2318
https://github.com/honojs/hono/issues/1872

Nothing working out. 
Spent several days and can' get it working.

### Additional information

Package.json file:

{
    "name": "my-app",
    "type": "module",
    "_moduleAliases": {
        "$lib": "src/lib"
    },
    "scripts": {
        "start": "vercel dev",
        "deploy": "vercel"
    },
    "dependencies": {
        "@azure/data-tables": "^13.2.2",
        "@hono/node-server": "^1.12.0",
        "hono": "^4.5.1",
        "luxon": "^3.4.4"
    },
    "devDependencies": {
        "vercel": "^32.4.1"
    }
}

**Comment by yusukebe** [comment]
Hi @Bobetti 

Can you provide a minimal project to reproduce it?

**Comment by Bobetti** [comment]
@yusukebe 

https://www.dropbox.com/scl/fi/cbp6d6yc81vbsmu67vxr0/minimal-projects.zip?rlkey=eazzklgmxswd7e8pbarthiqyt&e=1&dl=0

Top right Download button (arrow down).

Removed node_modules folders
In the server app - removed vercel folder.

Thank you for your efforts

**Comment by Bobetti** [comment]
any updates for me?

**Comment by yusukebe** [comment]
Hi @Bobetti 

I've investigated. It's not an Hono-side issue. Please upgrade the `vercel` package:

```bash
npm i vercel@latest
```

After that, you may face another issue: https://github.com/honojs/hono/issues/1695, but this issue can be closed.

**Comment by Bobetti** [comment]
@yusukebe thank you for your help, very much!
