### ISSUE TITLE
ZodEffects are converted into unknown types for RPC

### ISSUE THREAD

**Issue by cybercoder-naj** [honojs/hono#3217]
### What version of Hono are you using?

4.4.9

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```ts
const zodDate = z.preprocess(arg => {
  if (typeof arg === 'string' || arg instanceof Date) {
    return new Date(arg)
  }
  return arg
}, z.date())

const app = new Hono()
  .post('/date', zValidator('json', z.object({ date: zodDate })), async c => c.text('Hi'))

const client = hc<typeof app>('http://localhost:3000')
const res = await client.date.$post({
  json: {
    date: new Date() // but date is of type 'unknown'
  }
})
```

### What is the expected behavior?

The `json` should still show the type `Date`.

### What do you see instead?

The `json` in the request body is of type `unknown`.

### Additional information

The reason I need the preprocessing from Zod is because the `Date` instance is serialised into a string when it is sent from the client to the server. So `zValidator` receives a string and fails the request body. 

But in doing so, I have lost the type-safety from the RPC

**Comment by cybercoder-naj** [comment]
Current workaround is to use `.coerce`.

```ts
const app = new Hono()
  .post('/date', zValidator('json', z.object({ date: z.coerce.date() })), async c => c.text('Hi'))

const client = hc<typeof app>('http://localhost:3000')
const res = await client.date.$post({
  json: {
    date: new Date() // date is of type 'Date' and the request works
  }
})
```

**Comment by yusukebe** [comment]
Hi @cybercoder-naj 

First, this is not a `hono` core bug. It's a Zod Validator issue. And I think it's not a bug.

If you use the function with `z.preprocess`, the input type will be `unknown`:

```ts
const zodDate = z.preprocess((arg) => {
  if (typeof arg === 'string' || arg instanceof Date) {
    return new Date(arg)
  }
  return arg
}, z.date())

type Input = z.input<typeof zodDate> // unknown!
type Output = z.output<typeof zodDate> // Date
```

This means it can't detect the type that will come to, whether `string` or `Date`. So it will be `unknown`. The `hc` uses the type created by `z.input` (this is expected), so the type will be `unknown`. I think this is more of a Zod problem, not a Zod Validator problem.

**Comment by cybercoder-naj** [comment]
Understood! Thanks for the clarification.
