### ISSUE TITLE
Re-think route order

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#322]
Hmm... I got in trouble.

I was writing an application using Hono, and I realized I couldn't do what I wanted to do. I wrote like that:

```ts
app.get('/foo/bar', (c) => {
  return c.text('/foo/bar')
})

app.get('*', (c) => {
  return c.text('*')
})
```

And access `/foo/bar`.

```http
GET /foo/bar
```

I got `*`, but I want `/foo/bar`!! However, this is a natural part of the specification. **It's expected**. Because we scored as a following:

```ts
app.get('/foo/bar', a()) // 2.1
app.get('*', b()) // 0.2
```

I found this is not friendly to use. If `b()` is a *middleware*, this behavior is good, but if *both are handlers*, it's not good that the `b()` is executed. Should we re-think the route order?

**Comment by yusukebe** [comment]
We've discussed this extensively, but there is one way to score them in order of registration simply.

```ts
app.get('/foo/bar', a()) // 1
app.get('*', b()) // 2
```

**Comment by usualoma** [comment]
Hmmm...

Basically, I think it would be a better specification if it **didn't depend on registration order**, but this is a difficult problem.

I suppose we could come up with a new, more complex and sophisticated specification, but that would be **too difficult**, so it might be more intuitive for users to use **a simple registration order**.

**Comment by yusukebe** [comment]
Hi @usualoma !

I'm thinking the same things. Difficult problem. And, I think Hono must provide three points:

1. We must be able to do what we want.
2. It should be easy to understand.
3. Implementation should not be so complex.

We spent a long time discussing it and implementing the code. **But** how about making it with "**simple registration order**"?

```ts
app.get('/foo/bar', a()) // 1
app.get('*', b()) // 2
```

In this order, the rules are below:

* Handlers or middleware will be executed in registration order.
* When a handler is executed, the process is finished.
* If you have the middleware that you want to execute, write the code above the handler.
* If you want a "fallback" handler, write the code below the other handler.

It fulfills what we want to do, it's simple, and it's not difficult to implement.

**Comment by usualoma** [comment]
@yusukebe 
I agree with those specs!
