### ISSUE TITLE
Types: `zValidator` `param` validation makes input optional where it should be required

### ISSUE THREAD

**Issue by MonsterDeveloper** [honojs/hono#3227]
Reproduction:
1. Given the exact same schema with 1 required field, create 2 validators: one for `param`, the other one for `json`:
  ```ts
const schema = z.object({ id: z.string() })

const paramValidator = zValidator("param", schema)

const jsonValidator = zValidator("json", schema)
```

2. For the `jsonValidator`, the `input` type is inferred correctly: `id` is required
![CleanShot 2024-08-01 at 22 48 50@2x](https://github.com/user-attachments/assets/ac3a8dbb-fc7c-4f8f-9d57-ce139029b4ce)

3. For the `paramValidator`, however, the `id` field in the `input` type is optional for an unknown reason, while it should be marked as required since the schema says it is not optional and not nullable:
![CleanShot 2024-08-01 at 22 50 45@2x](https://github.com/user-attachments/assets/be4a3fe0-ab03-438c-8be1-94a4d5d07ea4)

This example is not working as expected, i.e. accepts `undefined` as a param:
![CleanShot 2024-08-01 at 22 51 52@2x](https://github.com/user-attachments/assets/77442fd5-7ee5-4581-a6ea-3d5e680e638f)

Suspected commit: https://github.com/honojs/middleware/commit/4875e1c53146d2c67846b8159d3630d465c2a310

[Link to TS Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgCQgOwgGjgSTQMwFMoAlQgRwFdCBnGAFQE8xC4BfOfKCEOAIgAW6CHwBQoSLERwAXgDUAhgBtgAEwUxoHLj34ABIRgD0MiKoC0AN2VqN0MROjwkM9p268+p1Q-BPpAgDGbjqehhBGgSqEaDBiooHodHA0gQKEIApwALyyAHQQAEYAVoSBMAAUSGoAXPl0UMBoAOYVAJTsbaIJSfBgClAKIIoq6ppQObIjtuMVfP2DIHzYqemZXT1oycU06NNj0JPyNgdQczvoyylpGQobiVvwCmBgk2iEAO4owu15zYSVPhGXYgQhGGpqK6iOBwBZDfZ2KCYaFwBQ0RhoYIPGCEAAe8GyAD44Ni8TA8hc0HMIABrPhdDYwZisEgQSg4miTJksCD4VEvboPZJRYAxAlwIIAHlZ7NohLm9MF0VieRBhAA2nwIT4ALp5AAk-0qCBRcJAdRNMJhtTglDQqkI+CahFUcCMRjgEAEcAwKyElCUqjQAHJ4IVWMolBAPi6UWxRGw2kA)

**Comment by yusukebe** [comment]
Hi @MonsterDeveloper 

Thank you for raising the issue. This is not only the Zod Validator issue. It is `hono` issue. I've transferred it as `hono`'s issue.
