### ISSUE TITLE
File upload (c.req.parseBody) returns 403 Forbidden

### ISSUE THREAD

**Issue by cyrusyan021** [honojs/hono#3265]
### What version of Hono are you using?

4.0.9

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

1. Set up a POST endpoint with `c.req.parseBody`
2. Frontend fires api cal: POST Request with headers `'Content-Type': 'multipart/form-data'` & new FormData() - file (i.e. PDF)
3. Response shows 403 Forbidden

### What is the expected behavior?

- Be able to see the file uploaded
- Response should be 200 OK

### What do you see instead?

- 403 Forbidden, don't think `c.req.parseBody` is working properly

**Comment by EdamAme-x** [comment]
All cases in Hono
https://github.com/search?q=repo%3Ahonojs%2Fhono%20403%20Forbidden&type=code

**Comment by cyrusyan021** [comment]
> All cases in Hono
> 
> CSRF or IPRest
> 
> https://github.com/search?q=repo%3Ahonojs%2Fhono%20403%20Forbidden&type=code

Thanks, File upload works properly. I'll close the issue

**Comment by mrkendrick** [comment]
> > All cases in Hono
> > CSRF or IPRest
> > https://github.com/search?q=repo%3Ahonojs%2Fhono%20403%20Forbidden&type=code
> 
> Thanks, File upload works properly. I'll close the issue

how did you fix the issue? I am experiencing the same thing

**Comment by EdamAme-x** [comment]
@mrkendrick What middleware are you using?
