### ISSUE TITLE
Types not available on Deno with Hono v4.5.5

### ISSUE THREAD

**Issue by alexgleason** [honojs/hono#3267]
### What version of Hono are you using?

4.5.5

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

After upgrading to Hono v4.5.5, types are no longer working in Deno:

![image](https://github.com/user-attachments/assets/e7192096-f2b8-47e9-847f-a1ea0f932104)

I am using Hono with JSR, and I can see that `types.ts` is clearly available: https://jsr.io/@hono/hono/4.5.5/src/types.ts

So I'm not sure if this is a bug with Hono, with JSR, or with Deno.

If I ctrl+click the types in VSCode, I cannot click into types.ts, even though I can for other files. It's like types.ts does not exist on my filesystem.

https://github.com/user-attachments/assets/3ae8dfbf-d7cb-458e-91ff-3bb68822b378

**Comment by nakasyou** [comment]
@alexgleason probably you can resolve if you run
```
deno cache --reload src/app.ts
```

**Comment by alexgleason** [comment]
@nakasyou That was exactly the problem. Thank you!
