### ISSUE TITLE
Using c.req.formData(), bodyLimit and original middleware, it's loading all the time

### ISSUE THREAD

**Issue by taisan11** [honojs/hono#3271]
### What version of Hono are you using?

4.5.5

### What runtime/platform is your app running on?

Bun 1.1.23

### What steps can reproduce the bug?

```ts
import { Hono } from 'hono'
import { bodyLimit } from 'hono/body-limit'

const app = new Hono()

app.use(bodyLimit({maxSize: 1024 * 1024 * 10}))

const sleep = (time:number) => new Promise((resolve) => setTimeout(resolve, time));

app.use(async (c,next) => {
  await sleep(1)// Anything that uses "await
  await next()
})

app.post('/', async (c) => {
  const body = await c.req.formData()
  return c.text(String(body.get('test')))
})

export default app
```
Execute this code.send form data with the key "test".

### What is the expected behavior?

return "test"

### What do you see instead?

It loads all the time.

**Comment by rjoydip** [comment]
@taisan11 This is not a bug. You are calling the `next()` function after `sleep()`, which is incorrect. This means that the middleware is introducing a delay before processing the subsequent middleware and routes, potentially blocking the request processing.

The right way is👇
```ts
app.use(async (c,next) => {
  await next()
  await sleep(ms)// Anything that uses "await
})
```
In this case, the `next()` function is called first, which allows the subsequent middleware and routes to be executed. After that, the `await sleep(ms)` is executed, which introduces a delay of 2 seconds before the middleware finishes its execution. This approach ensures that the middleware doesn't block the request processing and allows other parts of the application to continue while the delay is in effect.

**Comment by taisan11** [comment]
thank you!!
