### ISSUE TITLE
`trimTrailingSlash` doesn't work for `POST`, `PATCH`, `DELETE` request 

### ISSUE THREAD

**Issue by sparrowsl** [honojs/hono#3272]
### What version of Hono are you using?

4.5.5

### What runtime/platform is your app running on?

node

### What steps can reproduce the bug?

create any basic app and add/test this snippet
```js
import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { trimTrailingSlash } from "hono/trailing-slash";

const app = new Hono();
app.use(trimTrailingSlash());

app.post("/names", (c) => {
  return c.json({ names: [ "jack" ] });
});

serve({ fetch: app.fetch, port: 3000 });
```

`curl -X POST localhost:3000/names/` gives `404 Not Found` error

### What is the expected behavior?

expected it to work with or without trailing slash like it does for `GET` requests

### What do you see instead?

`404 Not Found` error

**Comment by yusukebe** [comment]
Hi @sparrowsl 

This is not a bug. Trailing Slash Middleware is enabled only in the `GET` request.

https://hono.dev/docs/middleware/builtin/trailing-slash#note

**Comment by sparrowsl** [comment]
@yusukebe based on the name "trimTrailingSlash" I would expect for it to trim all trailing slashes.
I just tested the same endpoints on an express code and it works with and without trailing slash.

also coming from express I would expect that it should just work if I use the middleware

**Comment by sparrowsl** [comment]
also I only found out about it, when the frontend dev asked me if the endpoints are wrong because they can choose to add a trailing slash if they want _(it may even be a mistake too)_, and they are expecting it to just work without having to know all the side effects of adding/removing the slashes for each method.

**Comment by yusukebe** [comment]
This Trailing Slash Middleware will make the target request that has `/` in the end *redirect* to the endpoint without `/`. If it allows `POST`, redirecting to another URL is weird since it will be `GET` request for the endpoint. I think it's a bad to allow the other method.

**Comment by sparrowsl** [comment]
Coming from express it will feel weird to have to always explain to my consumers that they need to omit the trailing slashes when they call my endpoint.
_(I have had multiple complaints concerning these and they mostly just bash me mainly due to this issue, and asking why did I chose Hono)_

can we still just trim the slash without redirecting??

**Comment by yusukebe** [comment]
@sparrowsl 

Can your problem be solved with the `strict` option of the `Hono` constructor?

https://hono.dev/docs/api/hono#strict-mode

**Comment by sparrowsl** [comment]
@yusukebe It seems to work well with `strict` to false.
thanks a lot for the guide and patience.

I feel like this needs to be somewhere at the top of the docs for most devs coming from express and are expecting this.
