### ISSUE TITLE
Flat Routing with Regex Not Working

### ISSUE THREAD

**Issue by nickreese** [honojs/hono#3277]
### What version of Hono are you using?

4.5.5

### What runtime/platform is your app running on?

Bun/Node (tested both)

### What steps can reproduce the bug?

```ts
import { showRoutes } from "hono/dev";
import { Hono } from "hono";

const app = new Hono();

export const VALID_STATES = ["alabama", "alaska", "arizona"] as const;

// state
app.get(`/:state{${VALID_STATES.join("|")}}/`, (c, next) => {
  return c.text("Hello Hono!" + c.req.param("state"));
});

//city
app.get(`/:state{${VALID_STATES.join("|")}}/:city{[a-z]+}/`, (c, next) => {
  return c.text("Hello Hono!" + c.req.param("state") + c.req.param("city"));
});

// provider
app.get(
  `/:provider{^(?!(${VALID_STATES.join("|")})$)[a-z0-9-]+$}/`,
  (c, next) => {
    return c.text("Hello Hono!" + c.req.param("provider"));
  }
);

showRoutes(app, {
  verbose: true,
});
export default app;
```

### What is the expected behavior?

We'd expect `http://localhost:3000/alabama/somewhere/` and `http://localhost:3000/alabama/` to be available... but they aren't unless the trailing slash on the state definition is removed. 

When the trailing slash is removed from the `state` route is suddenly causes the side effect of the `city` route getting super greedy and matching: `http://localhost:3000/alabama/somewhere/asdf`.

Not a regex ninja, but this seems off. 

### What do you see instead?

I'd like to see it respecting trailing slashes.

### Additional information

Big blocker from being able to adopt hono. I'm sure there is a workaround, looking for one as we speak.

**Comment by ryuapp** [comment]
It looks like you forgot to group them.
`{${VALID_STATES.join("|")}}` => `{(${VALID_STATES.join("|")})}`
