### ISSUE TITLE
[Feature Request]: Automatic Port Switching for Local Development Servers

### ISSUE THREAD

**Issue by binlf** [honojs/hono#3279]
### What is the feature you are proposing?

It would be beneficial to implement automatic port fallback for local development servers. If the default port is in use, the server should switch to the next available port automatically. This enhancement would streamline development workflows and prevent manual port configuration or conflicts -  _ChatGPT_ 😅

### Context
I tried running a **Next.js** app(_which typically starts at `localhost:3000`_) alongside a **Hono** app/server(_which also starts at `localhost:3000`_) only that in my case, I ran the **Next.js** app first and then the **Hono** app. I was initially stunned when I tried to test the **Hono** app(which was a simple API) and the response was **Next.js**'s payload instead...I realized what was going on and thought it'd be a nice enhancement to add automatic port switching when the default port is in use.
**Next.js** handles it this way:
![Code_ZrdvkrMSg8](https://github.com/user-attachments/assets/6c959c51-5b93-4b55-898c-243f2706221e)

_Apologies if I missed anything._

**Comment by yusukebe** [comment]
Hi @binlf 

Which dev server do you use?

**Comment by yusukebe** [comment]
If you mean it's about the Next.js dev server, this is out of Hono's scope.

**Comment by Di-void** [comment]
Hello @yusukebe 
I think what @binlf is saying is that since hono starts on port 3000 by default, it is possible that another program may already be using that port at the time. So, he's suggesting that a better experience may be that when hono server starts, it will at least prompt the dev that the port is already in use by something else and not just "false start" on that port. Similar to how Next.js does it, like in the image he shared.

**Comment by binlf** [comment]
> Hello @yusukebe
> 
> I think what @binlf is saying is that since hono starts on port 3000 by default, it is possible that another program may already be using that port at the time. So, he's suggesting that a better experience may be that when hono server starts, it will at least prompt the dev that the port is already in use by something else and not just "false start" on that port. Similar to how Next.js does it, like in the image he shared.

Thanks @Di-void. My apologies @yusukebe if I wasn't initially clear enough. I'm willing to provide more context if needed.

**Comment by yusukebe** [comment]
Hi @binlf 

Thank you for your explanation.

If so, the issue is unrelated to `hono`'s core. Anyway, I want to know if you run the Hono app on the [**Node.js adapter**](https://github.com/honojs/node-server).

**Comment by binlf** [comment]
Alright. 
I'm using **bun** to run the Hono app -- I'm using the [bun](https://github.com/honojs/starter/tree/main/templates/bun) starter template to be precise, bootstrapped by [create-hono](https://github.com/honojs/create-hono) .

**Comment by yusukebe** [comment]
This issue is outside Hono's scope. Hono only provides the application and is not involved in setting up the server.

If you want to solve that problem, write your own code to select the port before the `Bun.serve` command. Or Bun or other libraries could solve it.

```ts
// choose the port

Bun.serve({
  port: selectedPort,
  fetch: app.fetch,
})
```

**Comment by binlf** [comment]
Alright. Thank you, appreciate the help✊...
