### ISSUE TITLE
Any way to do `return context.file("some/static.file")`

### ISSUE THREAD

**Issue by matthewrobb** [honojs/hono#329]
As the title asks. I'd like to be able to return a file from a route handler. To be fair my primary use case would ALSO be covered by something like this: https://github.com/cloudflare/kv-asset-handler#servesinglepageapp

**Comment by yusukebe** [comment]
Hi @matthewrobb !

You can use `serve-static` middleware: <https://github.com/honojs/hono/tree/master/src/middleware/serve-static>

Example: <https://github.com/honojs/examples/blob/master/serve-static/src/index.ts>

**Comment by matthewrobb** [comment]
Yes I am using that middleware but there are other routes I would like to force to use the default document file like so:
```ts
app.get("/:some_resource_id", (c) => c.file("/"))
```

**Comment by yusukebe** [comment]
Hi @matthewrobb 

In PR #331 , we can write "fallback pattern" with the `path` option.

```ts
app.get('/foo', (c) => {
  return c.text('/foo')
})

// fallback
app.get('*', serveStatic({ path: './static/index.html' }))
```

I think this feature answers your expectations.
