### ISSUE TITLE
Stop using `any`

### ISSUE THREAD

**Issue by akku1139** [honojs/hono#3290]
### What version of Hono are you using?

4.5.6

### What runtime/platform is your app running on?

any

### What steps can reproduce the bug?

1. Open the Hono source code
2. You will see
- `any`
- `/* eslint-disable @typescript-eslint/no-explicit-any */`
- `// eslint-disable-next-line @typescript-eslint/no-explicit-any`

![image](https://github.com/user-attachments/assets/c4f44384-e1a6-43d6-a54d-4ac33c263cf7)

Ignoring any error 125 times!?

### What is the expected behavior?

`any` should be excluded from all codes.
Use other safe types or `unknown` instead.

**Comment by EdamAme-x** [comment]
Some of them are used by necessity due to typescript limitations, but you are right.

**Comment by yusukebe** [comment]
Hi @akku1139 

Of course it is better not to use `any`, but inside libraries, especially having complex type declarations, we have to use `any` for the ***implementation***. For instance, you can see a lot of `any`s in the source code of Zod. More details will be explained later.
