### ISSUE TITLE
Body is not forwarded

### ISSUE THREAD

**Issue by monstermichl** [honojs/hono#3298]
### What version of Hono are you using?

4.5.6

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

I'm listening to a specific POST route and want to forward the request to another service. However, the body doesn't get forwarded. I found [this](https://github.com/honojs/hono/issues/1491#issuecomment-1734381215) issue in which forwarding should be possible using fetch. The request itself gets forwarded, but the body in the receiving handler is empty.

## Forwarding
```typescript
import type { Context } from 'hono';

export async function newUserHandler(context: Context) {
    return fetch('http://auth-service/users', context.req.raw);
}
```

## Auth service handler
```typescript
import type { Context } from 'hono';
import type { ErrorDto } from '../dtos/error-dto';
import { StatusCodes } from 'http-status-codes';
import type { AnyObject, InferType, Maybe, ObjectSchema, ValidationError } from 'yup';
import { createError } from '../helpers/error-helper';

export function httpHandler<T extends ObjectSchema<Maybe<AnyObject>>>(schema: T, handler: (object: InferType<T>, context: Context) => any) {
    return async (context: Context) => {
        let validatedObject: InferType<T>;
        let error: ErrorDto | undefined;

        if (!schema) {
            error = createError('No schema has been provided');
        } else if (!handler) {
            error = createError('No handler has been provided');
        } else {
            /* Make sure a valid JSON has been received. */
            try {
                const object = await context.req.json();

                try {
                    validatedObject = await schema.validate(object);
                } catch (validationError) {
                    error = {
                        messages: (validationError as ValidationError).errors,
                    } as ErrorDto;
                };
            } catch (e) {
                error = createError(e!.toString());
            }
        }
        return error ? context.json(error, StatusCodes.INTERNAL_SERVER_ERROR) : handler(validatedObject!, context);
    }
}
```

## Output
```bash
auth-service         | ----------> 
```

### What is the expected behavior?

Maybe I misunderstood the mentioned approach but from what I understand the whole request should be forwarded, including the body.

### Additional information

I also checked if the forwarding services receives the body and there I can see it.

_No response_

**Comment by yusukebe** [comment]
Hi @monstermichl 

It's too complicated to reproduce the behavior on my machine. Can you simplify it, describe the instructions, and create a GitHub repository that includes this?

**Comment by monstermichl** [comment]
Hey @yusukebe 

thanks for your response. Yeah, understandable. Actually, in the complicated part only the *await context.req.json()* part is relevant, everything else can be ignored. So all you'd need to do is create a handler that forwards the request (probably to another service/URL) and a handler there that parses the body. Maybe something like this:

```typescript
import type { Context } from 'hono';

export async function forwardHandler(context: Context) {
    return fetch('http://another-service', context.req.raw);
}
```

```typescript
import type { Context } from 'hono';

export async function receivingHandler(context: Context) {
    return await context.req.json();
}
```

However, honestly I think this is a Bun, not a Hono problem as I commented [here](https://github.com/oven-sh/bun/issues/12701#issuecomment-2301168177). Unfortunately, I haven't received an answer yet.

**Comment by yusukebe** [comment]
Understood. This is not a Hono-side matter. We can reproduce the bug without Hono:

`forward.ts`:

```ts
export default {
  fetch: async (req: Request) => {
    return await fetch('http://localhost:3000', req)
  }
}
```

`receive.ts`:

```ts
export default {
  fetch: async (req: Request) => {
    return Response.json(await req.json())
  }
}
```

```bash
bun run receive.ts
bun run --port 3001 forward.ts
```

```bash
curl 'http://localhost:3001/' --data '{ "foo":"bar"}'
```

**Comment by monstermichl** [comment]
Perfect, thanks for your time. I thought so too after opening the issue.
