### ISSUE TITLE
Interface 'ClientResponse<T, U, F>' incorrectly extends interface 'Response'.

### ISSUE THREAD

**Issue by osameyy** [honojs/hono#3312]
### What version of Hono are you using?

4.5.8

### What runtime/platform is your app running on?

Cloudflare Worker

### What steps can reproduce the bug?

hono: 4.5.8

### Additional information

`node_modules/.pnpm/hono@4.5.8/node_modules/hono/dist/types/client/types.d.ts:46:18 - error TS2430: Interface 'ClientResponse<T, U, F>' incorrectly extends interface 'Response'.
  The types returned by 'clone().json()' are incompatible between these types.
    Type 'Promise<unknown>' is not assignable to type 'Promise<T>'.
      Type 'unknown' is not assignable to type 'T'.
        'T' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.

46 export interface ClientResponse<T, U extends number = StatusCode, F extends ResponseFormat = ResponseFormat> extends globalThis.Response {
                    ~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/hono@4.5.8/node_modules/hono/dist/types/client/types.d.ts:46`

**Comment by osameyy** [comment]
@yusukebe any help here?

**Comment by yusukebe** [comment]
Hi @osameyy 

I never understood your problem with just your information. Please provide a minimal project to reproduce it.

**Comment by yusukebe** [comment]
Closing this issue. If you will have still problem, feel free to reopen.
