### ISSUE TITLE
Return a piped response with compression enabled causes an unexpected error

### ISSUE THREAD

**Issue by ceifa** [honojs/hono#3316]
### What version of Hono are you using?

4.5.8

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

Enable the built-in compression:

```js
app.use(compress());
```

Inside a hono route, do the following:

```js
return await fetch(targetUrl, {
    method: req.method,
    headers,
    body: req.raw.body,
    duplex: 'half',
});
```

### What is the expected behavior?

Response piped correctly.

### What do you see instead?

TypeError: immutable
    at _Headers.delete (node:internal/deps/undici/undici:3303:17)
    at set res [as res] (file:///D:/whitewall/proxy/node_modules/hono/dist/context.js:62:31)
    at compress2 (file:///D:/whitewall/proxy/node_modules/hono/dist/middleware/compress/index.js:12:13)

### Additional information

It works on latest version of 3.x. Stopped in 4.x.

**Comment by nitedani** [comment]
Related lines:

https://github.com/honojs/hono/blob/main/src/context.ts#L477
https://github.com/honojs/hono/blob/main/src/middleware/compress/index.ts#L43-L44

Potential solutions:
1. implement a proxy for modifying response.headers (recreating the response)
2.
```js
    const headers = new Headers(res.headers)
    headers.delete('Content-Length')
    headers.set('Content-Encoding', encoding)
    // Compress the response
    const stream = new CompressionStream(encoding)
    ctx.res = new Response(res.body.pipeThrough(stream), {
      status: res.status,
      statusText: res.statusText,
      headers
    })
```
and rework https://github.com/honojs/hono/blob/main/src/context.ts#L477 to avoid overwriting the headers

**Comment by yusukebe** [comment]
This was closed by https://github.com/honojs/hono/pull/3318. Thanks.
