### ISSUE TITLE
hono/logger has annoying spaces when using a custom PrintFunc

### ISSUE THREAD

**Issue by marceloverdijk** [honojs/hono#3328]
### What version of Hono are you using?

4.5.9

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

When using `hono/logger` with a custom `PrintFunc` like:

```
app.use(logger((message: string, ...rest: string[]) => {
  ctx.var.logger.debug(message, ...rest);
}));
``` 

the log statements are prefixed with 2 spaces which does look annoying.

### What is the expected behavior?

No spaces. 

### What do you see instead?

Spaces:

```
[23:14:11.215] DEBUG (90875f1e-6a22-4f38-ba2c-d5ea16b9ac1d):   <-- GET /customers/1
[23:14:11.232] DEBUG (90875f1e-6a22-4f38-ba2c-d5ea16b9ac1d): Some other log statement
```

### Additional information

Reason is:

```
  const out =
    prefix === LogPrefix.Incoming
      ? `  ${prefix} ${method} ${path}`
      : `  ${prefix} ${method} ${path} ${colorStatus(status)} ${elapsed}`
  fn(out)
```

https://github.com/honojs/hono/blob/main/src/middleware/logger/index.ts#L58-L59

There is a easy workaround to `trim()` the message:

```
app.use(logger((message: string, ...rest: string[]) => {
  ctx.var.logger.debug(`${message.trim()}`, ...rest);
}));
```

but why does Hono add these spaces? 
\

**Comment by marceloverdijk** [comment]
PS: if it's considered to remove the spaces, I can create a PR.

**Comment by yusukebe** [comment]
Hi @marceloverdijk thank you for raising the issue.

@metrue Do you know why we added the three spaces to it? If there is no specific reason, I think we can remove it.

**Comment by marceloverdijk** [comment]
If they can removed, I already prepared a PR: https://github.com/honojs/hono/pull/3334

**Comment by metrue** [comment]
Everyone's preferences are different, I just felt the leading spaces gave me a better feeling than no spaces left between log and edge. 
```
  <-- GET /
  --> GET / 200 4ms
  <-- GET /
  --> GET / 200 1ms
  <-- GET /
  --> GET / 200 1ms
```

```
<-- GET /
--> GET / 200 4ms
<-- GET /
--> GET / 200 1ms
<-- GET /
--> GET / 200 1ms
```
But it's true, when you add a custom printing, it's not perfect looking.
```ts
export const customLogger = (message: string, ...rest: string[]) => {
  console.log(message, ...rest)
  console.log('some other logs')
}
```
```
  <-- GET /
some other logs
  --> GET / 200 5ms
some other logs
```

I am ok to remove the spaces, @yusukebe you can make decision.

**Comment by yusukebe** [comment]
@metrue Thank you for your explanation.

So, let's remove the spaces. I'll merge the #3334 by @marceloverdijk .
