### ISSUE TITLE
trpc type is any

### ISSUE THREAD

**Issue by 814351846** [honojs/hono#3329]
### What version of Hono are you using?

4.5.5

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

Sorry, I can't upload the code to github
[test.zip](https://github.com/user-attachments/files/16774480/test.zip)

### What is the expected behavior?

I want it to be normal

### What do you see instead?

![1](https://github.com/user-attachments/assets/4a5b3e3f-5fad-4d77-aa0a-a12127c680b6)
![2](https://github.com/user-attachments/assets/2dcabc4a-a2f9-4827-9822-6f066309108d)

**Comment by yusukebe** [comment]
Hi @814351846 

I've tried the project. But it can't be reproduced. It works good for me.

![CleanShot 2024-08-30 at 15 46 42@2x](https://github.com/user-attachments/assets/1eb66c45-6f9d-456e-8ad6-ef2c795e499c)

Did you install `@trpc/client`?

**Comment by 814351846** [comment]
> 你好@814351846
> 
> 我试过这个项目。但无法重现。对我来说效果很好。
> 
> ![CleanShot 2024-08-30 15 46 42@2x](https://private-user-images.githubusercontent.com/10682/363069952-1eb66c45-6f9d-456e-8ad6-ef2c795e499c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNzEyMTIsIm5iZiI6MTcyNTA3MDkxMiwicGF0aCI6Ii8xMDY4Mi8zNjMwNjk5NTItMWViNjZjNDUtNmY5ZC00NTZlLThhZDYtZWYyYzc5NWU0OTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDAyMjE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYTRmZTdhNWJlNGEwZWZhZWUzOThjNDZhYjQxNjFhYmU2NzYyNzIyNmQxZjk1MDk0OWQ5N2QzZDg5MGI3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5kKeRNXIcaNuwbmjc1SY33M4VUyMFCcXDiIF6-r2Icg)
> 
> 你安裝了`@trpc/client`嗎？

In the frontend folder, there is a file named trpc

**Comment by yusukebe** [comment]
@814351846 

Is Hono matter? I think this is just for the tRPC problem.

**Comment by 814351846** [comment]
Thank you for your response.
