### ISSUE TITLE
Generic over `object` in `Context.prototype.json`

### ISSUE THREAD

**Issue by equt** [honojs/hono#334]
Currently, the `json` method of the context is like

https://github.com/honojs/hono/blob/1282473f85e2a0648331b94507c3ae019beed4a4/src/context.ts#L104-L110

However, the `JSON.stringify` can, actually, stringify primitives. The `object` type used here represents anything else other than [primitives](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) in JS, which makes the code like `c.json(1)` a compile-time error.

---

What we could do is to have something like

```ts
type JsonRecord = {
  readonly [key: string]: Json
}

type JsonArray = ReadonlyArray<Json>

type Json = boolean | number | string | null | JsonArray | JsonRecord
```

And I'm suggesting typing the `json` method like

```ts
 json<O extends Json>(object: O, status: StatusCode = this._status, headers: Headers = {}): Response { 
   const body = this._pretty 
     ? JSON.stringify(object, null, this._prettySpace) 
     : JSON.stringify(object) 
   headers['Content-Type'] ||= 'application/json; charset=UTF-8' 
   return this.body(body, status, headers) 
 } 
```

which improves the developing experience.

P.S., great work, glad to help

**Comment by yusukebe** [comment]
Hi @equt !

You are right, `c.json(1)` throw an error. What about not using Generics and just using Union?

```ts
type Json = boolean | number | string | null | object

//...
json(object: Json, status: StatusCode = this._status, headers: Headers = {}): Response {
  const body = this._pretty 
    ? JSON.stringify(object, null, this._prettySpace) 
    : JSON.stringify(object) 
//...
}
```

**Comment by equt** [comment]
Well, honestly what I really want is to type the object passed in, say I want my response JSON will always be in the form of

```ts
type Resp = {
  message: string,
  // ...
}

json<Resp>(/* ... */)
```

If we make the `json` accept a generic param, we could avoid `as`, the current only option.

**Comment by yusukebe** [comment]
Thank you. I understood it well. I think we can write by a more simple way. What do you think?

```ts
json<T>(object: T, status: StatusCode = this._status, headers: Headers = {}): Response {
 const body = this._pretty
   ? JSON.stringify(object, null, this._prettySpace)
   : JSON.stringify(object)
//...
```

**Comment by equt** [comment]
I've tried to type it with the previously mentioned `Json`, while the error in the GraphQL middleware seems to require some extra attention.

Maybe it's ok for now to just type it as a simple `T`.

**Comment by yusukebe** [comment]
Yes! If you can, could you create PR for this issue?

**Comment by equt** [comment]
Sure
