### ISSUE TITLE
`Context<Env>` is not inferred in Middleware

### ISSUE THREAD

**Issue by lifeiscontent** [honojs/hono#3341]
### What version of Hono are you using?

4.5.6

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

```ts
app.use(
  basicAuth({
    verifyUser: (username, password, context) => {
      // this should be inferred, but it is not
      const hash = context.var.users.get(username);
      if (!hash) {
        return false;
      }

      return verifyPassword(password, hash);
    },
  }),
);
```

### What is the expected behavior?

I'd expect the context to use inferred typing

### What do you see instead?

`Env` is any

**Comment by yusukebe** [comment]
Hi @lifeiscontent 

This is a known issue. Related to #3202 #3198

**Comment by lifeiscontent** [comment]
@yusukebe thanks for the context :)

**Comment by yusukebe** [comment]
Hi @lifeiscontent 

It's just an idea. How about the code below? If you can, try it.

```ts
app.get(
  '/',
  async (c, next) => {
    return basicAuth({
      verifyUser: (username, password, _c) => {
        const hash = c.var.users.get(username)
        if (!hash) {
          return false
        }

        return verifyPassword(password, hash)
      },
    })(c, next)
  }
)
```

**Comment by lifeiscontent** [comment]
@yusukebe I'll be able to check in a week or so, currently on vacation, but thank you for following up! :)
