### ISSUE TITLE
Allow serving pre-compressed files with `serveStatic`

### ISSUE THREAD

**Issue by inetol** [honojs/hono#3363]
### What is the feature you are proposing?

Adding an option to prioritize pre-compressed files with *.br, .zst* or *.gz* extensions and in case they do not exist serve the file as usual. When compressing the assets of a web page in CI, this would help to reduce the server load by avoiding the need to use `compress` middleware.

**Comment by inetol** [comment]
I tried to use it before but it does not expose the request/response context, so I cannot set the necessary headers nor do the logic to check if the client is accepting compressed files.

**Comment by MathurAditya724** [comment]
So, will it be better if the API passes `context` as the next param? like this - 
```ts
serveStatic({
  root: './',
  rewriteRequestPath: (path, c) =>
    path.replace(/^\/static/, '/statics'),
})
```
And also with the new API coming (https://x.com/yusukebe/status/1829780618626146513) it will get much easier
