### ISSUE TITLE
[Feature Request] Use Hono RPC with Cloudflare Service Bindings

### ISSUE THREAD

**Issue by AdiRishi** [honojs/hono#3365]
## Proposal

At the moment, there are three ways Cloudflare workers can talk to each other
1. Direct HTTP fetch call
2. Using service bindings via `http` - https://developers.cloudflare.com/workers/runtime-apis/bindings/service-bindings/http/
3. Using service bindings via `rpc` - https://developers.cloudflare.com/workers/runtime-apis/bindings/service-bindings/rpc/

Currently RPC service bindings have a downside that they do not respect[ smart placement](https://developers.cloudflare.com/workers/runtime-apis/rpc/#limitations), which makes them less than ideal for communicating with workers that are bound to resoruces like D1.

Using HTTP serivce bindings have the downside of a lot of boilerplate code when it comes to dealing with typing requests properly.

In the ideal scenario, we would be able to leverage Hono's RPC client which wrapes fetch (I assume) with http service bindings, giving us the best of both worlds when it comes to RPC communication.

## Sample Interface

```ts
import { AppType } from '.'
import { hc } from 'hono/client'

const client = hc<AppType>(env.BOUND_SERVICE.fetch) // pass in the custom bound fetcher

const res = await client.posts.$post({
  form: {
    title: 'Hello',
    body: 'Hono is a cool project',
  },
})
```

**Comment by yusukebe** [comment]
Hi @AdiRishi 

I'll consider it later.

cc: @naporin0624 @sor4chi @chimame and others. Any thoughts?

**Comment by sor4chi** [comment]
Hi @AdiRishi.

You can actually achieve this with the following code:

`hc<AppType>('/', { fetch: env.BOUND_SERVICE.fetch.bind(env.BOUND_SERVICE) })`

However, I find this approach a bit unintuitive.

**Comment by naporin0624** [comment]
I often use the same approach as sor4chi. I made modifications to use `c.req.url` only for the URL part.

```ts
const client = hc<AppType>(new URL('/', c.req.url).toString(), {
  fetch: env.BOUND_SERVICE.fetch.bind(env.BOUND_SERVICE),
});
```

Since the communication via `http` with ServiceBinding is internal, the full URL is not exposed. Therefore, I feel this is the only viable approach. Additionally, with a interface for the custom fetch, it can also support DurableObjects, so this method could cover many cases, making it an acceptable solution as is.

However, as sor4chi mentioned, it’s not very intuitive. It would be helpful if the documentation included methods for connecting ServiceBinding and DurableObjects.

Reference implementations:
https://github.com/napolab/y-durableobjects/blob/main/src/index.ts#L19-L22
https://github.com/napolab/durabcast/blob/main/src/index.ts#L24-L26

**Comment by chimame** [comment]
Hi @adiRishi

If you need to use Service Bindings on Cloudflare's internal network, I think the method mentioned by sor4chi and naporin0624 is the best way to use Service Bindings with Hono.

Of course, if you don't mind exposing it to the external network, that's not the case.

However, I understand the method you are requesting. It might be possible if there is something that wraps hono/client and realizes Service Bindings over http.

**Comment by AdiRishi** [comment]
Oh wow I didnt't realise we could override the fetch function used. I'll test this over the next few days, if it works fine I'll close this issue.

Actually, I might raise a PR to document this if that's ok with everyone. Could be worthwile adding a note here - https://hono.dev/docs/guides/rpc

**Comment by yusukebe** [comment]
@sor4chi @naporin0624 @chimame You are cool! Thank you!

> Actually, I might raise a PR to document this if that's ok with everyone. Could be worthwile adding a note here - https://hono.dev/docs/guides/rpc

Already documented? https://hono.dev/docs/guides/rpc#custom-fetch-method

But that you couldn't find it means the document is bad. Or we can add the example to this section: https://hono.dev/examples/

**Comment by AdiRishi** [comment]
> Already documented? https://hono.dev/docs/guides/rpc#custom-fetch-method

You're totally right, it is documented, I'm clearly blind 🤦

**Comment by lucaspieran** [comment]
hi @AdiRishi  I am trying to make worker bindings with [RPC ](https://developers.cloudflare.com/workers/runtime-apis/bindings/service-bindings/rpc/) but I cannot implement the method in worker A and consume it in worker B, that is, how do I implement WorkerEntryPoint. Do you have any example to guide me?

**Comment by sor4chi** [comment]
How about this?
https://github.com/sor4chi/minimun-workers-service-bindings-rpc

**Comment by lucaspieran** [comment]
> HI, @lucaspieran. How about this? https://github.com/sor4chi/minimun-workers-service-bindings-rpc

hi, yeah i see but i was thinking to do it with hono, i mean to consum the methods in my hono app

**Comment by sor4chi** [comment]
Cloudflare RPC supports two types of connections:

1.	Fetch-based
2.	Method-based (without using fetch)

For the first type, you can use Hono Client with the approaches mentioned above. However, for the second type, it’s not possible to use Hono Client because its I/O interface does not rely on Request/Response objects.

**Comment by AdiRishi** [comment]
Hey all, sorry I kept this open for so long. I've just finished testing the Hono RPC connection using a custom fetcher and it works great 😄 

I did have a few issues / points of confusion, which I think is good to give as feedback here.

### Point 1: It's not clear that we need to chain requests when defining our Hono router

I personally always used to write my app definitions like this
```ts
const app = new Hono<{ Bindings: Env }>();
app.get('/test-one', (c) => c.text('hello'));
app.post('test-two', (c) => c.text('hello'));
type AppType = typeof app;
```
However, this won't work anymore since the type of `app` is 
```ts
const app: Hono<{
    Bindings: Env;
}, BlankSchema, "/">
```

We actually need to chain requests at initializaton for this to work correctly
```ts
const app = new Hono<{ Bindings: Env }>()
  .get('/test-one', (c) => c.text('hello'))
  .post('test-two', (c) => c.text('hello'));
```

Now `AppType` will be correct
```ts
type AppType = Hono<{
    Bindings: Env;
}, {
    "/test-one": {
        $get: {
            input: {};
            output: "hello";
            outputFormat: "text";
            status: StatusCode;
        };
    };
} & {
    "test-two": {
        $post: {
            input: {};
            output: "hello";
            outputFormat: "text";
            status: StatusCode;
        };
    };
}, "/">
```

This is not a huge issue, it's just not obvious in the docs that this needs to happen.

## Issue 2: RequestInit types seem to conflict

When defining the Hono client in my client like so
```ts
  const apiClient = hc<AppType>('https://website-api.com', {
    fetch: args.context.cloudflare.env.WEBSITE_API.fetch.bind(args.context.cloudflare.env.WEBSITE_API),
  });
```
Typescript shows the following error
```
app/routes/_index.tsx:14:5 - error TS2322: Type '(input: RequestInfo, init?: RequestInit<CfProperties<unknown>> | undefined) => Promise<Response>' is not assignable to type '((input: RequestInfo | URL, requestInit?: RequestInit<CfProperties<unknown>> | undefined, Env?: any, executionCtx?: ExecutionContext | undefined) => Response | Promise<...>) | { ...; } | undefined'.
  Type '(input: RequestInfo, init?: RequestInit<CfProperties<unknown>> | undefined) => Promise<Response>' is not assignable to type '(input: RequestInfo | URL, requestInit?: RequestInit<CfProperties<unknown>> | undefined, Env?: any, executionCtx?: ExecutionContext | undefined) => Response | Promise<...>'.
    Types of parameters 'input' and 'input' are incompatible.
      Type 'RequestInfo | URL' is not assignable to type 'RequestInfo'.
        Type 'URL' is not assignable to type 'RequestInfo'.

14     fetch: args.context.cloudflare.env.WEBSITE_API.fetch.bind(args.context.cloudflare.env.WEBSITE_API),
       ~~~~~
```

Again, not a huge issue, we can easily `ts-expect-error`

-----------

That's about it. I'm happy to close this issue since Hono RPC with Service bindings works :)
Thanks everyone for the quick responses and your help!

**Comment by willsmanley** [comment]
First of all awesome that we can do this! Thank you all for putting this together.

I do think a guide to type-safe cloudflare RPC calls would be an awesome thing to highlight in the docs.

However I noticed that strong typing breaks when using `.use(*, ...)` as a middleware that runs before all of the HTTP methods. This seems to be irrespective of the cloudflare workers part. Any solution for this?

Finally, any thoughts on the chaining and RequestInit type conflicts?

**Comment by mgandolfi7** [comment]
In my case, I just wanted to expose method-based RPC handlers in my Hono app so I just did (with help from the Discord):



EDIT 8/23/25 - this is a much better way:

```typescript
export class SumService extends WorkerEntrypoint<Env> {
	sum(nums: number[]) {
		const sum = nums.reduce((a, b) => a + b, 0);

		const someBinding = this.env.SOME_BINDING;

		return sum;
	}
}

const app = new Hono<{ Bindings: Env }>().get("/hono", async (c) => {
	const someBinding = c.env.SOME_BINDING;

	return c.json("hello from hono");
});

export default app;
```

Old way:

```typescript
import { Hono } from "hono";
import { WorkerEntrypoint } from "cloudflare:workers";

const app = new Hono().get("/hono", async (c) => {
    return c.json("hello from hono");
});

export default class extends WorkerEntrypoint {
    async fetch(request: Request) {
        return app.fetch(request);
    }

    sum(nums: number[]) {
        const sum = nums.reduce((a, b) => a + b, 0);

        return sum;
    }
}
```

**Comment by osseonews** [comment]
@mgandolfi7 Thank you! This is exactly what I was looking for. Recommend Hono add this to their docs, as I spent hours trying to figure out how to do this simple set up, so the app that is running hono can expose RPC handlers to other workers.

**Comment by ngdbao** [comment]
> In my case, I just wanted to expose method-based RPC handlers in my Hono app so I just did (with help from the Discord):
> 
> import { Hono } from "hono";
> import { WorkerEntrypoint } from "cloudflare:workers";
> 
> const app = new Hono().get("/hono", async (c) => {
>     return c.json("hello from hono");
> });
> 
> export default class extends WorkerEntrypoint {
>     async fetch(request: Request) {
>         return app.fetch(request);
>     }
> 
>     sum(nums: number[]) {
>         const sum = nums.reduce((a, b) => a + b, 0);
> 
>         return sum;
>     }
> }

This is a  bad move, you'll lost all the env since you have to define **Env** by **this.env** in fetch.

My recommended approach:
```ts
async fetch(request: Request) {
		return app.fetch(request, this.env, this.ctx);
	}
```

**Comment by osseonews** [comment]
> 
> This is a bad move, you'll lost all the env since you have to define **Env** by **this.env** in fetch.
> 

No, that's not accurate. You can use ``` import { env } from "cloudflare:workers"; ``` to import the env and pass it thru.

**Comment by lumpinif** [comment]
> > In my case, I just wanted to expose method-based RPC handlers in my Hono app so I just did (with help from the Discord):
> > import { Hono } from "hono";
> > import { WorkerEntrypoint } from "cloudflare:workers";
> > const app = new Hono().get("/hono", async (c) => {
> > return c.json("hello from hono");
> > });
> > export default class extends WorkerEntrypoint {
> > async fetch(request: Request) {
> > return app.fetch(request);
> > }
> > ```
> > sum(nums: number[]) {
> >     const sum = nums.reduce((a, b) => a + b, 0);
> > 
> >     return sum;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> This is a bad move, you'll lost all the env since you have to define **Env** by **this.env** in fetch.
> 
> My recommended approach:
> 
> async fetch(request: Request) {
> 		return app.fetch(request, this.env, this.ctx);
> 	}

here's how I do this.

both ways you talked about work, but for me it's better and more robust to also keep the CloudflareBindings in fetch() 


```
export default class extends WorkerEntrypoint<CloudflareBindings> {
  async fetch(request: Request) {

    return app.fetch(request, this.env, this.ctx);
  }

  sum(nums: number[]) {
    const sum = nums.reduce((a, b) => a + b, 0);

    return sum;
  }
}
```

```
import { env } from "cloudflare:workers"
```
