### ISSUE TITLE
`trimTrailingSlash` does not work when setting `.notFound()` handler

### ISSUE THREAD

**Issue by mikestopcontinues** [honojs/hono#3385]
### What version of Hono are you using?

4.5.11

### What runtime/platform is your app running on?

Node

### What steps can reproduce the bug?

1. Add `trimTrailingSlash()` ware
2. Add `.notFound(console.log)`

### What is the expected behavior?

Hono redirects to the matching route, sans trailing slash.

### What do you see instead?

Hono returns 400 error.

**Comment by EdamAme-x** [comment]
I cannot reproduction this

https://stackblitz.com/edit/stackblitz-starters-ppsbwe?file=index.ts

**Comment by mikestopcontinues** [comment]
Here's a repro. `/route/` will not work.

https://stackblitz.com/edit/stackblitz-starters-46kyu4

**Comment by ryuapp** [comment]
`trimTrailingSlash()` doesn't work if the status code is not 404.
https://hono.dev/docs/middleware/builtin/trailing-slash#note
https://github.com/honojs/hono/blob/f9a23a9992979fed79b0703ab8b3a3ce49f7175f/src/middleware/trailing-slash/index.ts#L28

Therefore, by setting 404 status code in `notFound` method, it will work.
```ts
import { Hono } from 'hono';
import { trimTrailingSlash } from 'hono/trailing-slash';
import { serve } from '@hono/node-server';

const app = new Hono({strict: true});

app.use(trimTrailingSlash());
app.get('/route', (c) => c.text('/route'));
app.notFound((ctx) => {
  console.log(ctx.req.url);
  return ctx.text('not found', 404);
});

serve({
  fetch: app.fetch,
});
```

**Comment by mikestopcontinues** [comment]
Thanks, that was it!
