### ISSUE TITLE
Hono stops accepting requests and ignores the requests after a certain amount of requests have been sent.

### ISSUE THREAD

**Issue by itztiva** [honojs/hono#3408]
### What version of Hono are you using?

4.1.0

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

Just send a ton of requests. 

### What is the expected behavior?

It ignores requests then my cloudflare just says the webserver is down.

### What do you see instead?

Web server is down.

**Comment by itztiva** [comment]
well im not sure exactly, but its over 1000 atleast and the requests would come in every like second or 2 as i had over 10 users online.

**Comment by MathurAditya724** [comment]
Can you share a reproduction of the code you are using?

**Comment by itztiva** [comment]
import { Hono } from "hono";
import { cors } from "hono/cors";
import { logger } from "hono/logger";
import path from "node:path";
import EnvBuilder from "./Builders/EnvBuilder";
import routes from "./utils/routing/loadRoutes";
import { startHttps } from "./https/setup";
import Database from "./database/database";
import Logger from "./utils/logging/logger";
import { Selena } from "./utils/functions/errors";

const app = new Hono({ strict: false });

export default app;

EnvBuilder.Validate();
export const config = EnvBuilder.Register();

app.use("*", cors());

app.use(logger());

app.use(async (c, next) => {
  if (c.req.url.includes("https://public.celestiafn.com")) {
    if (c.req.path !== "/shop") {
      return c.text("Not Found", 404);
    }
  }

  if (c.req.path == "/shop") {
    if (c.req.url.includes("https://public.celestiafn.com")) {
      await next();
    } else if (c.req.url.includes("prod-api-external")) {
      return c.text("Not Found", 404);
    } else {
      return c.json(Selena.basic.notFound.apply(c), 404);
    }
  } else {
    await next();
  }
});

const loadedRoutes = await routes.loadRoutes(path.join(__dirname, "routes"), app);

if (loadedRoutes == undefined) {
  Logger.startup("error");
} else {
  Logger.startup("All Routes Loaded");
}

app.notFound((c) => {
  if (c.req.url.includes("prod-api-external")) {
    return c.text("Not Found", 404);
  }
  if (c.req.path.includes("/game/v2/profile")) {
    return c.json(Selena.mcp.operationNotFound.apply(c), 404);
  } else {
    return c.json(Selena.basic.notFound.apply(c), 404);
  }
});

app.onError((err, c) => {
  console.log(err);
  return c.json(Selena.internal.serverError.apply(c), 500);
});

**Comment by itztiva** [comment]
i switched to a different version of hono and it has started to work. i am on version 4.4.10

**Comment by yusukebe** [comment]
I think we can close this issue. Closing.
