### ISSUE TITLE
importing app from other file give no types

### ISSUE THREAD

**Issue by hrithiqball** [honojs/hono#3417]
### What version of Hono are you using?

4.6.1

### What runtime/platform is your app running on?

Nodejs

### What steps can reproduce the bug?

import booksApp hovered
![image](https://github.com/user-attachments/assets/32a071ee-c2e0-49de-8d38-7a25a7ed7dce)

// server side
```ts
import { serve } from '@hono/node-server'
import { Hono } from 'hono'
import { booksApp } from '@/routes/books'

const authorsApp = new Hono()
  .get('/', async c => c.json({ result: 'list authors' }))
  .post('/', async c => c.json({ result: 'create an author' }, 201))
  .get('/:id', async c => c.json({ result: `get ${c.req.param('id')}` }))

const app = new Hono()
  .route('/authors', authorsApp)
  .route('/books', booksApp)
  
  serve({
  fetch: app.fetch,
  port: env.PORT
})

export type AuthServiceType = typeof app
```

// client side
```ts
const client = hc<AuthServiceType>('/api')
```

### What is the expected behavior?

![image](https://github.com/user-attachments/assets/4249167f-cbf9-4edd-beb2-dffc90c61f15)

expecting this kind of intellisense

### What do you see instead?

![image](https://github.com/user-attachments/assets/da26a2f2-2188-4800-801d-b203ce1365e4)

not showing when importing from other file

### Additional information

it would be insane for me to dump everything in index.ts file for 20 routes. is this known issue or im implementing it wrongly

**Comment by yusukebe** [comment]
Hi @hrithiqball 

Your `tsconfig.json` has `strict: true`?

https://github.com/honojs/hono/issues/2270#issuecomment-2143745118

**Comment by hrithiqball** [comment]
> Hi @hrithiqball
> 
> Your `tsconfig.json` has `strict: true`?
> 
> [#2270 (comment)](https://github.com/honojs/hono/issues/2270#issuecomment-2143745118)

yes both in backend and front end. im using pnpm workspace if that helps. imported AppType from '@app/auth-service' and my package.json is '@app/auth-service' : 'workspace:*'

**Comment by yusukebe** [comment]
@hrithiqball 

I can't understand if it a matter of a TypeScript performance issue or if the setting is wrong. If you will provide a minimal project to reproduce it, I may investigate it.

**Comment by hrithiqball** [comment]
> @hrithiqball
> 
> I can't understand if it a matter of a TypeScript performance issue or if the setting is wrong. If you will provide a minimal project to reproduce it, I may investigate it.

https://github.com/hrithiqball/pos-system you can try pnpm install, cd apps/auth-service and pnpx prisma generate then cd to root again and pnpm build. you will see the vite react cant build because of the type problems

**Comment by yusukebe** [comment]
Hi @hrithiqball 

Thank you! I've investigated it and found the solution. It can't correctly infer the types with using the `rateLimitMiddleware` from `@app/auth-service/middlewares/rate-limit`. Though it's not documented clearly the implementation of the middleware is not good. Try to use `createMiddleware` function like this:

```ts
import { redis } from '@app/auth-service/lib/redis'
import { createMiddleware } from 'hono/factory'

export const rateLimitMiddleware = createMiddleware(async (c, next) => {
  // ...
  await next()
})
```

**Comment by hrithiqball** [comment]
@yusukebe works like a charm! thanks!

**Comment by puerschel93** [comment]
@yusukebe 

I also have a nested router and the intellisense works fine so far. 

In one of my nested routers I have an endpoint like this

Server:
``` typescript
const users = new Hono()
.patch("/language", zValidator("json", languageSchema), async (c) => {
	/** Data */
	const { userId, language } = c.req.valid("json");

	/** Action */
	await clerk.users.updateUser(userId, {
		publicMetadata: { language },
	});

	/** Response */
	return c.json({ success: true });
});
```

``` typescript
export const languageSchema = z.object({
     userId: z.string(),
     language: z.string().length(2),
})
```

So I assume (since the intellisense in vscode works and suggests all available endpoints on client) that I get an error when I don't pass the values required by the languageSchema to my `$patch` function right?

``` typescript
await client.users.language.$patch({
	json: {
		language,
		userId: user?.id,
	},
});
```

but when I hover the `$patch` function it shows that `args = {} | undefined`:
``` typescript
(property) $patch: (args?: {} | undefined, options?: ClientRequestOptions) => Promise<ClientResponse<{
    success: boolean;
}, ContentfulStatusCode, "json">>
```

and not as expected the shape of my schema.

Further Notes:
* It is also not working if I remove all my middlewares.
* I created all middlewares (if applied) with `createMiddleware`
* `"strict": true` is set in every tsconfig

I would really appreciate some help here since this lack of type safety for the inputs really drives me crazy.
Thanks so much in advance!
