### ISSUE TITLE
JSX `renderToReadableStream` has redundant `await`?

### ISSUE THREAD

**Issue by imcotton** [honojs/hono#3422]
### What version of Hono are you using?

4.6.1

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

https://github.com/honojs/hono/blob/dfbd717263ab8ecd7bf495fbd2c32d8c79854284/src/jsx/streaming.ts#L123-L130

### What is the expected behavior?

should not `await` on the `str.toString()`

### What do you see instead?

`await str.toString()`

**Comment by usualoma** [comment]
Hi @imcotton.
Thanks for creating the issue!

It's not without sense, since `renderToReadableStream` can take a jsx node in hono, and a jsx node could return a `Promise<string>` from `.toString()`, but in #3344, which came in v4.6, `resolveCallback` now resolves `Promise`.
https://github.com/honojs/hono/blob/dfbd717263ab8ecd7bf495fbd2c32d8c79854284/src/jsx/base.ts#L150

I believe you are correct that `await` is currently unnecessary. I think the following changes would simplify things.

```diff
diff --git a/src/jsx/streaming.ts b/src/jsx/streaming.ts
index 9c475b50..4b167f95 100644
--- a/src/jsx/streaming.ts
+++ b/src/jsx/streaming.ts
@@ -127,10 +127,12 @@ export const renderToReadableStream = (
   const reader = new ReadableStream<Uint8Array>({
     async start(controller) {
       try {
-        const tmp = str instanceof Promise ? await str : await str.toString()
-        const context = typeof tmp === 'object' ? tmp : {}
+        if (!(str instanceof Promise)) {
+          str = str.toString() as HtmlEscapedString | Promise<HtmlEscapedString>
+        }
+        const context = typeof str === 'object' ? str : {}
         const resolved = await resolveCallback(
-          tmp,
+          str,
           HtmlEscapedCallbackPhase.BeforeStream,
           true,
           context
```

**Comment by imcotton** [comment]
Thanks for the explanation, I was following the `HtmlEscapedString` type over:

https://github.com/honojs/hono/blob/dfbd717263ab8ecd7bf495fbd2c32d8c79854284/src/utils/html.ts#L17-L21

Before make any changes to `renderToReadableStream`

- Do you think adding `toString(): string | Promise<string>` to `HtmlEscaped` would make any senses here?
- Does override `Object.prototype.toString` in `JSXNode` purposely for string coercion or just happened to bump into prototype chain?

**Comment by usualoma** [comment]
Thanks for your comment. By the way, are you having any specific trouble with this? If you have, I'd like to make sure ahead of time.


> Do you think adding toString(): string | Promise<string> to HtmlEscaped would make any senses here?

The possibility of `toString()` returning `Promsie<string>` is not a feature of `HtmlEscaped`, so if type clarification is needed, I would change it as follows.

```diff
diff --git a/src/jsx/streaming.ts b/src/jsx/streaming.ts
index 9c475b50..23acf594 100644
--- a/src/jsx/streaming.ts
+++ b/src/jsx/streaming.ts
@@ -6,6 +6,7 @@
 import { raw } from '../helper/html'
 import { HtmlEscapedCallbackPhase, resolveCallback } from '../utils/html'
 import type { HtmlEscapedString } from '../utils/html'
+import type { JSXNode } from './base'
 import { childrenToString } from './components'
 import { DOM_RENDERER, DOM_STASH } from './constants'
 import { Suspense as SuspenseDomRenderer } from './dom/components'
@@ -121,7 +122,7 @@ const textEncoder = new TextEncoder()
  * The API might be changed.
  */
 export const renderToReadableStream = (
-  str: HtmlEscapedString | Promise<HtmlEscapedString>,
+  str: HtmlEscapedString | JSXNode | Promise<HtmlEscapedString>,
   onError: (e: unknown) => string | void = console.trace
 ): ReadableStream<Uint8Array> => {
   const reader = new ReadableStream<Uint8Array>({
```

> Does override Object.prototype.toString in JSXNode purposely for string coercion or just happened to bump into prototype chain?

Although it is not clear that it is currently being used effectively enough, the original intent was to allow it to behave as a string, as shown below.

```tsx
`
<html>
  <head>
    <title>Hello</title>
  </head>
  <body>
    ${<h1>Hello</h1>}
  </body>
</html>
`
```

**Comment by imcotton** [comment]
Understood.

I haven't running into any trouble from here, it only occurred to me from "Go to Type Definition" in vscode, because I'm using **Deno** & **JSR** it led me right into the TypeScript source code of `renderToReadableStream` (instead of d.ts), thus where the `await str.toString()` jumps out to me at first glance.

All above been said, I think it is OK to close the ticket if those awaits were not oversight or left over during code refactor. It's up to the authors to decides whether further clarification required there, thank you for the answers.

**Comment by usualoma** [comment]
Thank you! Your explanation helped me understand the situation too.

I think your point is valid, as I think it is important that users are not confused when they read the library code.

Please give me some time to think about how I should fix it.
