### ISSUE TITLE
Type error on tsx file

### ISSUE THREAD

**Issue by rohanBagchi** [honojs/hono#3424]
### What version of Hono are you using?

4.6.2

### What runtime/platform is your app running on?

nodejs

### What steps can reproduce the bug?

This is my package.json

```json
{
  "name": "hono-app-19-sept-2024",
  "scripts": {
    "dev": "tsx watch src/index.tsx"
  },
  "dependencies": {
    "@hono/node-server": "^1.13.0",
    "hono": "^4.6.2"
  },
  "devDependencies": {
    "@types/node": "^20.11.17",
    "tsx": "^4.7.1"
  }
}
```

This is my tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "skipLibCheck": true,
    "types": [
      "node"
    ],
    "jsx": "react-jsx",
    "jsxImportSource": "hono/jsx",
  }
}
```

Finally this is my index.tsx:

```tsx
import { Hono } from 'hono'
import type { FC } from 'hono/jsx'
import { serve } from '@hono/node-server'

const app = new Hono()

const Layout: FC = (props) => {
  return (
    <html>
      <body>{props.children}</body>
    </html>
  )
}

const Top: FC<{ messages: string[] }> = (props: {
  messages: string[]
}) => {
  return (
    <Layout>
      <h1>Hello Hono!</h1>
      <ul>
        {props.messages.map((message) => {
          return <li>{message}!!</li>
        })}
      </ul>
    </Layout>
  )
}

app.get('/', (c) => {
  const messages = ['Good Morning', 'Good Evening', 'Good Night']
  return c.html(<Top messages={messages} />)
})


const port = 3000
console.log(`Server is running on port ${port}`)

serve({
  fetch: app.fetch,
  port
})

export default app
```

The application runs fine in the browser:
<img width="205" alt="Screenshot 2024-09-19 at 11 11 03 AM" src="https://github.com/user-attachments/assets/9a4f493b-c85c-409f-9934-920027c515c2">

However, TS errors out in the editor like this:
`Cannot find name 'React'.ts(2304)`

### What is the expected behavior?

There should not be a TS error

### What do you see instead?

<img width="758" alt="Screenshot 2024-09-19 at 11 12 19 AM" src="https://github.com/user-attachments/assets/53a015ed-3723-4343-82fa-0dbf978439c3">

**Comment by yusukebe** [comment]
Hi @rohanBagchi 

I can't reproduce it.

![CleanShot 2024-09-20 at 19 26 01@2x](https://github.com/user-attachments/assets/c025d740-5d94-4ffb-aa50-142c011f879d)

This is not a bug.
