### ISSUE TITLE
`style=` objects do not work with `jsx: precompile` on Deno

### ISSUE THREAD

**Issue by r-thomson** [honojs/hono#3427]
### What version of Hono are you using?

4.5.9

### What runtime/platform is your app running on?

Deno 1.45.5

### What steps can reproduce the bug?

When using the `"precompile"` JSX option in Deno, passing an object to the `style` attribute does not work correctly. Instead, it always outputs `[object Object]`.

```jsx
return c.render(
  <div style={{ display: 'none' }} />
);
```

### What is the expected behavior?

With `"jsx": "react-jsx"`:

```html
<div style="display:none"></div>
```

### What do you see instead?

With `"jsx": "precompile"`:

```html
<div style="[object Object]"></div>
```

**Comment by usualoma** [comment]
Hi @r-thomson.
Thanks for the report. I'll fix it!
