### ISSUE TITLE
Add Authorization header when testing using request

### ISSUE THREAD

**Issue by ikrom** [honojs/hono#3431]
### What version of Hono are you using?

4.5.11

### What runtime/platform is your app running on?

cloudflare worker + bun

### What steps can reproduce the bug?

when I want to create unit test using app.request, I can't add authorization header to check JWT is valid or not 

![code](https://github.com/user-attachments/assets/498baccb-540c-4e8d-8cd3-37cec2bdd5be)

### What is the expected behavior?

It should not error and unit test can run successfully

### What do you see instead?

unit test error and can't run it

**Comment by yusukebe** [comment]
Hi @ikrom 

I can't reproduce it. Please provide a minimal project to reproduce it.

**Comment by ikrom** [comment]
Hi @yusukebe 

Actually I want to create unit testing, I have app with route `/home`
```
import { Hono } from "hono";
const app = new Hono<{ Bindings: Bindings }>().basePath("/v1");
app.get("/home", async (c) => {
  return c.json({ env: c.env.ENVIRONMENT, message: "Hello World!" });
});
```
Then I create file `home.test.ts` to test the route `/home`
```
import { describe, test, expect } from "bun:test";
import { Bindings, MOCK_ENV } from "@type";

describe("Index Test", () => {
  test("GET /home", async () => {
    const res = await app.request(
      "/home",
      {
        headers: {
          authorization: `Bearer token`,
        },
      },
      MOCK_ENV
    );
    expect(res.status).toBe(200);
  });
});
```
But the result is like picture below
<img width="291" alt="image" src="https://github.com/user-attachments/assets/d3a220dc-ec56-47c8-be60-c0a63e231ad0">

Could you help how to create unit test with authorization header jwt?

**Comment by yusukebe** [comment]
@ikrom 

You should access `/v1/home`:

```ts
const res = await app.request(
  '/v1/home',
  {
    headers: {
      authorization: 'Bearer token',
    },
  },//...
)
```

**Comment by ikrom** [comment]
thank you for the correction @yusukebe 
<img width="458" alt="image" src="https://github.com/user-attachments/assets/099bc7c3-49d8-4f35-96d3-b4131f61f3ff">
but there is another error, the res is undefined

**Comment by yusukebe** [comment]
@ikrom 

I don't know, but the following code is working well:

```ts
const app = new Hono().basePath('/v1')

app.get('/home', async (c) => {
  return c.json({})
})

const res = await app.request(
  '/v1/home',
  {
    headers: {
      authorization: 'Bearer token',
    },
  } //...
)

console.log(res.status) // 2000
```

**Comment by ikrom** [comment]
should the `const app = new Hono()` in the same file with unit test? because the unit test can't run if the app in different file with unit test

**Comment by yusukebe** [comment]
> should the `const app = new Hono()` in the same file with unit test? 

No.

**Comment by gerhardcit** [comment]
Not sure if this helps, but I had to do a fallback in middleware.ts for env to work in production as well in tests.

`app.ts`

```typescript
import { Hono } from "hono";
import { configureAppMiddleware } from "./middleware";
import { configureAppRoutes } from "./router";

export function getHonoApp() {
    const app = new Hono();
    configureAppMiddleware(app);
    configureAppRoutes(app);
    return app;
}
```
`middleware.ts`
```typescript
import { Hono } from "hono";
import { env } from "hono/adapter";
import { bearerAuth } from "hono/bearer-auth";

export const configureAppMiddleware = (app: Hono) => {
app.use('/api/*', bearerAuth({
        verifyToken: async (token, c) => {
            // this works in runtime/production with the hono/adapter as per hono docs
            let { API_KEY } = env<{ API_KEY: string }>(c);

            // in testing when MOCK_ENV is passed in, we need to do this as a fallback
            if (!API_KEY) {
                API_KEY = c.env.API_KEY;
            }

            return token === API_KEY
        }
    }))
}
```

the test looks like this:
`app.authed.test.ts`
```typescript
import { beforeAll, describe, expect, test } from "vitest";
import { getHonoApp } from "./app";

const MOCK_ENV = {
    API_KEY: 'test_api_key',
}

describe('App - authed routes', () => {
    let app = getHonoApp(); 
    let headers: Record<string, string>;

    beforeAll(() => {
        headers = {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${MOCK_ENV.API_KEY}`
        }
    });

    test('should return 200 and You are authorized on /api/page', async () => {
        // there is a /api/page route that returns some json
        const res = await app.request('/api/page', { headers }, MOCK_ENV);
        // this succeed because of the fallback (hack?) in middleware.ts
        expect(res.status).toBe(200);
        expect(await res.json()).toEqual({ message: 'You are authorized' })
    })
})

```

**Comment by Soviut** [comment]
@gerhardcit thanks for this example. It's what finally clarified the approach I should take for swapping middleware during tests.

I now have a `createApp(db?)` function that takes an optional db client. If it's present, override the normal database middleware before returning the app instance.

```typescript
export function createApp(db?) {
  const app = new Hono()
  if (db) {
    app.use((c, next) => {
      c.set('db', db)
      return next()
    })
  } else {
    app.use(databaseMiddleware)
  }
  return app
}

const appPostgres = createApp() // this one for live
const appPGlite = createApp(drizzle(new PGlite())) // this one for tests
```

**Comment by hdformat** [comment]
[the official testing document](https://hono.dev/docs/guides/testing) is saying like below
```js
const res = await app.request('/posts', {
    method: 'POST',
    body: JSON.stringify({ message: 'hello hono' }),
    headers: new Headers({ 'Content-Type': 'application/json' }),
  })
```

but when i write my testing like this
```js
const res = await app.request('/posts', {
    method: 'POST',
    body: JSON.stringify({ message: 'hello hono' }),
    headers: new Headers({ 'Content-Type': 'application/json', 'Authorization': 'Bearer ...' }),
  })
```

the middleware says `invalid credential structure`, it seems that the headers are interpreted in wrong way
```js
{
   authorization: 'Bearer ...',
  'content-type': 'application/json'
}
```

so, i should rewrite my testing like this to pass the testing.
```js
const res = await app.request('/posts', {
    method: 'POST',
    body: JSON.stringify({ message: 'hello hono' }),
    headers: {contentType: 'application/json', authorization: 'Bearer ...' }),
  })
```

**Comment by Soviut** [comment]
@hdformat This is a closed issue, you should open a new issue if you think there are mistakes in the docs.
