### ISSUE TITLE
When making zValidator a shared variable, type inference occasionally fails on the client side

### ISSUE THREAD

**Issue by mayone-du** [honojs/hono#3435]
### What version of Hono are you using?

4.6.2

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

I have some code where an authorization header validator is being shared like this:

```ts
export const authHeaderValidator = zValidator(
  'header',
  z.object({
    authorization: z.string(),
  })
)
```

When calling this, type inference always works on the backend (e.g., const { authorization } = c.req.valid('header') // ok), but on the frontend, I occasionally get an error saying that the header parameter cannot be specified.

Defining the validator inline on the backend resolves the issue, but I’m curious why this error occurs sporadically. Since I want to use this validator across almost all routes, I would prefer to keep it shared. I would appreciate any guidance on how to resolve this issue.

**Comment by yusukebe** [comment]
Hi @mayone-du 

This depends on the structure of your project. For example, whether it is monorepo or not. And this may be related to https://github.com/honojs/hono/issues/2955

**Comment by mayone-du** [comment]
Thanks for the reply, seems to be the same problem as 2955, so I'll close it.
