### ISSUE TITLE
Cloudflare Workers `onOpen` WebSocket event is not triggered

### ISSUE THREAD

**Issue by imLymei** [honojs/hono#3448]
### What version of Hono are you using?

4.6.3

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

The `onOpen` websocket event is not called

steps:

1. `npm create hono@4.6.3`
2. Select cloudflare workers
3. paste code:
```ts
import { Hono } from 'hono';
import { upgradeWebSocket } from 'hono/cloudflare-workers';

const websocketClients: WebSocket[] = [];

const app = new Hono();

app.get(
  '/ws',
  upgradeWebSocket((c) => {
    console.log('WebSocket upgrade requested');

    return {
      onOpen(event, ws) {
        console.log('WebSocket connection opened');
        websocketClients.push(ws.raw!);
      },
      onError(evt, ws) {
        console.error('WebSocket error:', evt);
      },
      onMessage(event, ws) {
        console.log(`Message from client: ${event.data}`);
        websocketClients.forEach((client) => {
          if (client !== ws.raw) {
            client.send(event.data + ' ' + JSON.stringify(websocketClients));
          }
        });
      },
      onClose: (_, ws) => {
        console.log('WebSocket connection closed');
        const index = websocketClients.indexOf(ws.raw!);
        if (index > -1) {
          websocketClients.splice(index, 1);
        }
      },
    };
  })
);

export default app;

```

### What is the expected behavior?

console to print "`WebSocket connection opened`"

### What do you see instead?

no "`WebSocket connection opened`"

![image](https://github.com/user-attachments/assets/1c6c17ad-7216-4a65-a615-1fdbf34a3cf7)

**Comment by yusukebe** [comment]
Hi @imLymei 

If I remember correctly, Cloudflare Workers does not support the `open`. For instance, the `open` is not listed the below doc:

https://developers.cloudflare.com/workers/runtime-apis/websockets/#events

Hey @naporin0624 Is it right?

**Comment by imLymei** [comment]
Well, that sucks. Thank you for clarifying things up!

**Comment by tripolskypetr** [comment]
That definitely look awful as the API: it going to produce a lot of shitcode. And after you fix that confirmed bug, the Hone shitcode not going anywhere from the projects codebases

**Comment by tripolskypetr** [comment]
I found a lot of fake documentation materials about `onOpen` callback. For example, this one

https://dev.to/yutakusuno/hono-simple-messaging-app-using-bun-and-websocket-mnk

How do I get the ws instance to send the message from the server side first?

```tsx
  upgradeWebSocket((_) => ({
    onOpen(_, ws) {
      const rawWs = ws.raw as ServerWebSocket;
      rawWs.subscribe(topic);
      console.log(`WebSocket server opened and subscribed to topic '${topic}'`);
    },
```

**Comment by EdamAme-x** [comment]
That is bun code and seems to have nothing to do with cf workers, is it not?
Also, I think the restrictions on cf workers is not an issue that Hono can do anything about.

**Comment by NathanFlurry** [comment]
Not having the `onOpen` event makes the Hono WebSocket adapter borderline unusable.

We modified the adapter to call `onOpen` like this:

```typescript
const wsContext = new WSContext<WebSocket>({
  // ...etc...
});

if (events.onClose) {
  server.addEventListener("close", (evt: CloseEvent) =>
    events.onClose?.(evt, wsContext),
  );
}
if (events.onMessage) {
  server.addEventListener("message", (evt: MessageEvent) =>
    events.onMessage?.(evt, wsContext),
  );
}
if (events.onError) {
  server.addEventListener("error", (evt: Event) =>
    events.onError?.(evt, wsContext),
  );
}

server.accept?.();

events.onOpen?.(new Event("open"), wsContext);
```

([Full Source](https://github.com/rivet-gg/actor-core/blob/1dbc287707c933c5730f934ef96d2250cde1786d/packages/platforms/cloudflare-workers/src/websocket.ts#L60))

`wsContext.send` works as expected after `server.accept()` is called, so you can use `onOpen` like you would in any other application.

The only caveat is that it's called _before_ the handshake is successfully completed – which differs from other drivers. However, I think this slight difference in behavior is preferable to having `onOpen` be unimplemented.

Happy to make a PR if maintainers agree with this decision.

**Comment by EdamAme-x** [comment]
I think it's a good suggestion.
