### ISSUE TITLE
ConnInfo from Hono/Bun outputting ip of localhost instead of remote address

### ISSUE THREAD

**Issue by vinay-khatri** [honojs/hono#3454]
### What version of Hono are you using?

4.6.3

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```ts
import { Context, Next } from "hono";
import { getConnInfo } from 'hono/bun';

function getMyIpAddress(c: Context, next: Next) {
        const info = getConnInfo(c)

        console.log(`Your remote address is ${info.remote.address}`)
        console.log(info)

        c.status(200)
        return c.json({ success: true, data: info.remote.address })
}

```

### What is the expected behavior?

Your remote address is 11:235:10:130:

### What do you see instead?

Your remote address is ::ffff:127.0.0.1
{
    address: "::ffff:127.0.0.1",
    addressType: "IPv6",
    port: 37424,
}

### Additional information

I am running my hono.js server behind Nginx. If its because of nginx then please tell me which headers do i need to pass to hono server. I have already set the X-Forward-For header :
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $host;
proxy_pass http://127.0.0.1:8080;
```

But I am able to get the remote ip address using : 
```ts
const ip = c.req.header('x-forwarded-for');
console.log(ip)
```

**Comment by yusukebe** [comment]
Hi @vinay-khatri 

`getConnInfo()` does not look up a `X-Forwarded-For` header. Please use `c.req.header('x-forwarded-for')`.

**Comment by amjed-ali-k** [comment]
If you use cloudflare dns and proxied connection use `c.req.header("cf-connecting-ip")`
