### ISSUE TITLE
Multiple parts in Response Header

### ISSUE THREAD

**Issue by exoego** [honojs/hono#3462]
### What is the feature you are proposing?

While implementing #3461, I couldn't find a way to set multiple parts in response header.
For partial contents response, a Response may contain [multiple parts for partial contents](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206#receiving_a_206_response_for_multiple_requested_ranges) like this:

```
HTTP/1.1 206 Partial Content
Date: Wed, 15 Nov 2015 06:25:24 GMT
Last-Modified: Wed, 15 Nov 2015 04:58:08 GMT
Content-Length: 1741
Content-Type: multipart/byteranges; boundary=BOUNDARY
ETag: "abc123"
Accept-Ranges: bytes

--BOUNDARY
Content-Type: application/pdf
Content-Range: bytes 234-639/8000

# content of first range (406 bytes)
--BOUNDARY
Content-Type: application/pdf
Content-Range: bytes 4590-7999/8000

# content of second range (3410 bytes)
--BOUNDARY--
```

Another example of multiple parts is [multipartform data](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#multipartform-data).

**Comment by yusukebe** [comment]
Hi @exoego 

We may use `FormData` for a body of `Response`? `Response` can accept an instance of `FormData`: https://developer.mozilla.org/en-US/docs/Web/API/Response/Response

And `FromData` will add proper boundaries.

```ts
app.get('/', (c) => {
  const data = new FormData()
  data.append('foo', 'bar')
  return new Response(data)
})
```

**Comment by exoego** [comment]
Thanks.
I was able to use `ReadableStream` to set multiple parts in response body, in https://github.com/honojs/hono/pull/3461 for future reference
