### ISSUE TITLE
cf properties in request is broken

### ISSUE THREAD

**Issue by vickyRathee** [honojs/hono#3463]
### What version of Hono are you using?

4.6.3

### What runtime/platform is your app running on?

Cloudflare pages

### What steps can reproduce the bug?

The `cf` properties are not exported in `req.raw` ?

![image](https://github.com/user-attachments/assets/4e9f1ff8-337f-4d35-90de-a73b9d1c0be1)

**tsconfig.json**

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "Bundler",
    "strict": false,
    "skipLibCheck": true,
    "lib": ["esnext", "dom"],
    "types": ["@cloudflare/workers-types", "vite/client"],
    "jsx": "react-jsx",
    "jsxImportSource": "hono/jsx"
  }
}

```

### What is the expected behavior?

The TS should not complain

### What do you see instead?

TS error

**Comment by yusukebe** [comment]
Hi @vickyRathee 

There is a conflict of definition of `Response` between Cloudflare's and DOM's. Remove the `dom` from your `tsconfig.json`:

```json
"lib": ["esnext"],
```

**Comment by vickyRathee** [comment]
@yusukebe that doesn't made any difference, still TS error.
Already tried closing vscode > reopen etc.

**Comment by yusukebe** [comment]
@vickyRathee 

I can't reproduce it. Please provide a minimal project to reproduce it if you want to help us.

**Comment by vickyRathee** [comment]
@yusukebe Sure, I will create one
