### ISSUE TITLE
`notFound` handler not called when routed via another Hono instance

### ISSUE THREAD

**Issue by ainz-95** [honojs/hono#3465]
### What version of Hono are you using?

4.6.3

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

The `notFound` handler is not called when the request is routed through another `Hono` instance:

```
import { Hono } from "hono";

const app = new Hono();

app.get("/", c => {
  return c.text("hello app");
});

const subApp = new Hono();

subApp.get("/", c => {
  return c.text("hello subapp");
});

subApp.notFound(async c => {
  return c.text("subapp not found", 404);
});

app.route("/subapp", subApp);

app.notFound(async c => {
  return c.text("app not found", 404);
});

export default app;
```
Navigate to `/subapp/hello` and see the output.

### What is the expected behavior?

Response should be `subapp not found`.

### What do you see instead?

Response was `app not found` instead.

**Comment by yusukebe** [comment]
Hi @ainz-95 

It's not a bug. `notFound` handler is not passed into a parent app when you use `app.route()`. So, add a fallback route instead of `subApp.notFound`:

```ts
subApp.all('*', (c) => {
  return c.text('subapp not found', 404)
})
```

**Comment by ainz-95** [comment]
Thanks @yusukebe for the workaround. That's unfortunate to hear, as in my situation `subApp` is exported by a third party vendor. I don't have control over their code, and to me it seems a bit counterintuitive to tell them to not use `notFound` for handling their 404 responses when they are just following what the documentation says.

For now I've opted for `app.mount("/subapp", subApp.fetch)` instead to retain their correct behavior.

**Comment by yusukebe** [comment]
@ainz-95 

We have been working on this problem for a long time: https://github.com/honojs/hono/pull/866. But this is a very difficult issue, and it's difficult or impossible to make it enabled while keeping current performance and code size.

Basically `app.route()` is designed for just adding the child routes to parent app without `notFoundHandler`. In this case, it's good to use `app.mount()` as you have done.

**Comment by ainz-95** [comment]
Understandable 👍 I appreciate the explanation and reasoning.
