### ISSUE TITLE
Hono RPC client - types inferred incorrectly

### ISSUE THREAD

**Issue by pjeziorowski** [honojs/hono#3485]
### What version of Hono are you using?

4.6.2

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```ts
export type PreferencesDTO = {
  userId: string
  newMessages: boolean
  newConnectionRequests: boolean
  matchSuggestionsOrUpdates: boolean
  productUpdates: boolean
  createdAt: string
  updatedAt: string | null
}

const preferences: PreferencesDTO = {...}

return c.json({
  data: preferences
}, 200) ----> The "output" of this gets inferred as "any" in the client:
```

### What is the expected behavior?

Types for the basic JS types are inferred correctly

### What do you see instead?

Output type in the RPC client is of type `any`

<img width="440" alt="image" src="https://github.com/user-attachments/assets/9944acff-c75e-4a5f-a69a-a815ca8aafe8">

### Additional information

If you cast your output type like this

```
return c.json({
  data: preferences
}, 200) as {
        newMessages: boolean
        newConnectionRequests: boolean
        matchSuggestionsOrUpdates: boolean
        productUpdates: boolean
      } 
 ```
 
 then it's fine, but it's super inconvenient to be forced to cast types like this

**Comment by pjeziorowski** [comment]
I found the issue!

I'm using a monorepo with this structure:

- apps
  - backend
  - frontend
- packages
  - shared

In the shared package, I had stored some basic utility types. It turned out that importing these into the backend and returning data that had been wrapped or transformed by these types/functions was causing problems with type inference. Relocating the shared code directly into the backend resolved the issue.

Question - Do I have to set something up for the type inference to work fine without moving the shared code directly to the backend part?

**Comment by yusukebe** [comment]
HI @pjeziorowski 

I need to look into your actual project to find the answer. But, it's not a bug of `hono` and the problem of setting the project though it's a bad issue for us. So, honestly, I was hoping you could talk about this on [Discussions](https://github.com/orgs/honojs/discussions) or Discord.

**Comment by detarkende** [comment]
I have a similar situation in [this repo](https://github.com/detarkende/stremio-ncore-addon/tree/f5ca898299de1c29593235b3d3dc8204095f16e1).

When I create a file `src/client/api/api-client.ts`, with this content:
```ts
import { hc } from 'hono/client';
import type { ApiRoutes } from 'src/server/index';

export const client = hc<ApiRoutes>('/');
```
then I see this issue:
<img width="559" alt="image" src="https://github.com/user-attachments/assets/0ed9e614-12a8-46ca-b8cd-040d3f8fbb1e">
even though `ApiRoutes` is working in `src/server/index.ts`.
<img width="513" alt="image" src="https://github.com/user-attachments/assets/0bcb7c90-d803-4bd1-ac46-5f9ff5773703">

Does anyone know what could be the issue? I tried changing the import to make sure that the `index.ts` resolution isn't the issue and played around with the tsconfigs, but it didn't change.

**Comment by pjeziorowski** [comment]
@detarkende, have you set up [composite](https://www.typescriptlang.org/tsconfig/#composite) and references in your monorepo tsconfigs?

I found out that setting this up properly makes the inference work reliably.

**Comment by detarkende** [comment]
@pjeziorowski You're right, that fixed it! Thank you, I have been stuck on this issue for days now 🎉 

Btw, if anyone is in the same situation, this video helped me: https://www.youtube.com/watch?v=S-jj_tifHl4

**Comment by zxt-tzx** [comment]
> @pjeziorowski You're right, that fixed it! Thank you, I have been stuck on this issue for days now 🎉
> 
> Btw, if anyone is in the same situation, this video helped me: https://www.youtube.com/watch?v=S-jj_tifHl4
> 
> I needed to set the "composite" config to `true` in the backend, and reference the backend project in the frontend's tsconfig.

just wanna say thanks, this helped solve my problem! just wanna add for anyone else who ran into additional error that [this has been helpful](https://github.com/microsoft/TypeScript/issues/49844) (TLDR: you cannot use `tsc --noEmit`, just let it emit to a gitignored folder)

**Comment by cramosc** [comment]
Something seems to have changed in version 4.6.5. Version 4.6.4 infers correctly the type of the hono client but not anymore in version 4.6.5

**Comment by yusukebe** [comment]
@cramosc 

Can you share a minimal project to reproduce it? In my understanding, this issue is solved.

**Comment by cramosc** [comment]
@yusukebe 
Sure, here is a minimal example: https://github.com/cramosc/hono-client-example
when running `npx tsc --build` I get following error:

```
client/api.ts:6:23 - error TS2339: Property 'api' does not exist on type '{ "*": ClientRequest<{ $get: { input: {}; output: {}; outputFormat: string; status: StatusCode; }; }>; }'.

6 const api = apiClient.api;
```

If I install hono@4.6.4 instead, then typescript runs without errors.

**Comment by yusukebe** [comment]
@cramosc 

Thank you very much! It's reproduced.


Hi @m-shaka Can you take a look at this?

**Comment by m-shaka** [comment]
can't believe this, but the behavior differs before and after compilation. I have no clue about the reason. 

```typescript
import { App as OriginalApp } from "./server/app";
import { App as Compiled } from './dist/server/app';
import { hc } from 'hono/client'

const cliFromOriginal = hc<OriginalApp>(window.location.origin);
const cliFromCompiled = hc<Compiled>(window.location.origin);
cliFromOriginal.api
cliFromCompiled.api // error
```

`hcWithType` is a workaround to it for now
https://hono.dev/docs/guides/rpc#compile-your-code-before-using-it-recommended

**Comment by m-shaka** [comment]
Or, making your app end with `.route` will fix it.

```typescript
const app = new Hono()
  .get("/*", c => c.html("<html/>"))
  .route(
    "/api",
    new Hono().route(
      "",
      new Hono().get("a", async c => {})
    )
  )
```

The output type of [the original version](https://github.com/honojs/hono/issues/3485#issuecomment-2439937337) is:

```typescript
import { Hono } from "hono";
declare const app: Hono<import("hono/types").BlankEnv, (import("hono/types").BlankSchema | import("hono/types").MergeSchemaPath<import("hono/types").BlankSchema | import("hono/types").MergeSchemaPath<{
    a: {
        $get: {
            input: {};
            output: {};
            outputFormat: string;
            status: import("hono/utils/http-status").StatusCode;
        } | {
            input: {};
            output: {};
            outputFormat: string;
            status: import("hono/utils/http-status").StatusCode;
        };
    };
}, "/">, "/api">) & {
    "/*": {
        $get: {
            input: {};
            output: {};
            outputFormat: string;
            status: import("hono/utils/http-status").StatusCode;
        };
    };
}, "/">;
```

The one of the modified version is:
```typescript
declare const app: import("hono/hono-base").HonoBase<import("hono/types").BlankEnv, {
    "/*": {
        $get: {
            input: {};
            output: {};
            outputFormat: string;
            status: import("hono/utils/http-status").StatusCode;
        };
    };
} | import("hono/types").MergeSchemaPath<import("hono/types").BlankSchema | import("hono/types").MergeSchemaPath<{
    a: {
        $get: {
            input: {};
            output: {};
            outputFormat: string;
            status: import("hono/utils/http-status").StatusCode;
        } | {
            input: {};
            output: {};
            outputFormat: string;
            status: import("hono/utils/http-status").StatusCode;
        };
    };
}, "/">, "/api">, "/">;
```

The difference is that the type of `app` is `Hono` or `HonoBase`.

**Comment by yusukebe** [comment]
> can't believe this, but the behavior differs before and after compilation. I have no clue about the reason.

So, it's super weird. Indeed, it was introduced in `4.6.5`, but I don't know why well.

**Comment by haexyh** [comment]
Might be useful. In my case I didn't throw an [HTTPException](https://hono.dev/docs/api/exception)and just return a different object like `c.json({},401)` after changing this:
```
  if (response.error) {
    return c.json({},401);
  }
  return ok(c, response.data);
```
to
```
  if (response.error) {
    throw new HTTPException(401)
  }
  return ok(c, response.data);
```
everything went right
