### ISSUE TITLE
Jest fails to import `createBunWebSocket`

### ISSUE THREAD

**Issue by amadodiazjr** [honojs/hono#3490]
### What version of Hono are you using?

4.6.1

### What runtime/platform is your app running on?

bun

### What steps can reproduce the bug?

`bun run test`

### What is the expected behavior?

test succeeds

### What do you see instead?

```
 FAIL  src/index.spec.ts
  ● Test suite failed to run

    ReferenceError: Bun is not defined

    > 1 | import { createBunWebSocket } from 'hono/bun'
        | ^
      2 |
      3 | describe('index', () => {
      4 |   it("should not FAIL", () => {

      at Object.<anonymous> (node_modules/hono/dist/cjs/adapter/bun/ssg.js:26:19)
      at Object.<anonymous> (node_modules/hono/dist/cjs/adapter/bun/index.js:29:18)
      at Object.require (src/index.spec.ts:1:1)
```

### Additional information

Isolated issue

https://github.com/amadodiazjr/bun-not-defined

Please read README.md for more info.

**Comment by yusukebe** [comment]
Hi @amadodiazjr 

It runs on a `jest` with a `bun run test` command. Execute a `bun test` command.

**Comment by amadodiazjr** [comment]
`bun test` works.  Thank you.

**Comment by amadodiazjr** [comment]
Hi @yusukebe - one more question.

I noticed this [roadmap](https://github.com/honojs/hono/issues/514) includes migration from CommonJS to ESM.

If this is the case, why are the cjs files being referenced? 

```
      at Object.<anonymous> (node_modules/hono/dist/cjs/adapter/bun/ssg.js:26:19)
      at Object.<anonymous> (node_modules/hono/dist/cjs/adapter/bun/index.js:29:18)
```

Are these files that have not been migrated yet?

**Comment by yusukebe** [comment]
@amadodiazjr 

I'm not investigating it well, but I think Bun preferred to use CJS.

**Comment by amadodiazjr** [comment]
appreciate your response.  Bun tester still does not support many features I use in Jest.

I found a workaround to use two different test runners in my project.
