### ISSUE TITLE
CORS does not work with found endpoints

### ISSUE THREAD

**Issue by deestt** [honojs/hono#3493]
### What version of Hono are you using?

4.6.3

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

Creating a GET endpoint and adding cors as middleware to all endpoints

### What is the expected behavior?

A header `Access-Control-Allow-Origin` on all endpoints

### What do you see instead?

It shows a header on a non-working endpoint, but not on a found one

**Comment by safwanyp** [comment]
Middlewares should be registered before the route. Can you provide a code example?
