### ISSUE TITLE
wild card for multiple routes does not work

### ISSUE THREAD

**Issue by skandasoft** [honojs/hono#3502]
### What version of Hono are you using?

4.6.3

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

Multiple wild card fails.
```
app.get(
  '/*.html',
  async (c, next) => {
    console.log('in html');

    await next();
  }
// this next route overrides the wildcard 
app.get(
  '/css/*.css',
  async (c, next) => {
    console.log('in css');

    await next();
  }


```

### What is the expected behavior?

when requesting for '/index.html' -> both console should work

### What do you see instead?
none of the console is working. looks like the second wild card must have overridden and messed up everything.
_No response_

**Comment by safwanyp** [comment]
You have two different routes, with no closing parentheses. It seems like a syntax issue? Try this:
```js
app.get("/*.html", async (c, next) => {
  console.log("in html");

  await next();
});

app.get("/css/*.css", async (c, next) => {
  console.log("in css");

  await next();
});
```

> when requesting for '/index.html' -> both console should work

This doesn't really make sense unless a call to `index.html` somehow makes a call to a `/css/*.css` route.

**Comment by yusukebe** [comment]
Hi @skandasoft 

It's not a bug. Use a regexp: https://hono.dev/docs/api/routing#regexp
