### ISSUE TITLE
In 4.6.4, after setting variables in createMiddleware, c.set got type error.

### ISSUE THREAD

**Issue by maou-shonen** [honojs/hono#3512]
### What version of Hono are you using?

4.6.4

### What runtime/platform is your app running on?

This issue is unrelated to the runtime

### What steps can reproduce the bug?

See this example https://github.com/orgs/honojs/discussions/3499#discussioncomment-10926890

### What is the expected behavior?

Tpye check pass.

### What do you see instead?

Get type error:
```
Type 'string' is not assignable to type 'never'.ts(2769)
```

![image](https://github.com/user-attachments/assets/237f417b-b0ec-42aa-8684-5c01ac9c9cfd)

### Additional information

It was working fine before 4.6.4.  
Related #3498

**Comment by yusukebe** [comment]
Hi @maou-shonen 

Thank you for the issue. I can't reproduce it with [the code](https://github.com/orgs/honojs/discussions/3499#discussioncomment-10926890). It does not throw a type error. Did you try the same code?

**Comment by maou-shonen** [comment]
Yes, I discovered it when entering the example in a completely new environment.
The image attached to this issue is exactly what I see on my VSCode.

[reproduction](https://github.com/maou-shonen/bug-hono-3512)

Here is the tsconfig.json (Bun's default values)."
```json
{
  "compilerOptions": {
    // Enable latest features
    "lib": ["ESNext", "DOM"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleDetection": "force",
    "jsx": "react-jsx",
    "allowJs": true,

    // Bundler mode
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "noEmit": true,

    // Best practices
    "strict": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true,

    // Some stricter flags (disabled by default)
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noPropertyAccessFromIndexSignature": false
  }
}

```

**Comment by yusukebe** [comment]
@maou-shonen 

Thanks! It's reproduced. I'm investigating.

**Comment by yusukebe** [comment]
Hmm.

This may be caused because the type definition is too complex. The type below:

```ts
(undefined extends { [key in ContextKey]: Redis; } ? any : { [key in ContextKey]: Redis; })[ContextKey]
```

should be infered as `Redis`. But it can't do that. I'll keep to the investigation.

@m-shaka Sorry for the sudden ping. Do you have any idea about this?

**Comment by m-shaka** [comment]
no solutions yet, but I found another breaking change
```typescript
import { Hono } from 'hono'
import { createMiddleware } from 'hono/factory'

type Bindings = {
  MY_VAR_IN_BINDINGS: string
}

type Variables = {
  MY_VAR: string
}

const app = new Hono<{ Bindings: Bindings }>()

app.get(
  '/',
  createMiddleware<{ Variables: Variables }>(async (c, next) => {
    await next()
  }) ,
  createMiddleware(async (c, next) => {
    await next()
  }),
  async (c) => {
    const v = c.get('MY_VAR') // string in 4.6.3, but any in 4.6.4 😢 
  }
)
```

**Comment by yusukebe** [comment]
@m-shaka 

Oooops. You may already know it, but what I want to do is described here: https://github.com/honojs/hono/pull/3498#issue-2573463937

**Comment by yusukebe** [comment]
I created the PR #3515 to revert the PR #3498. I'll merge it and release a new patch version tomorrow if we can't find a good way.

**Comment by m-shaka** [comment]
I don't think I can find it for now😢
