### ISSUE TITLE
`$url` return doesn't include query params

### ISSUE THREAD

**Issue by alex-grover** [honojs/hono#3532]
### What version of Hono are you using?

4.6.5

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

run `bun src/client.ts` in this repository: https://github.com/alex-grover/hono-rpc-url-query

output is included in the `client.ts` file in a comment as well.

### What is the expected behavior?

I would expect the returned URL object to include query params.

Specifically, I want to use the $url as a key for SWR, and the query params are necessary for this to work correctly. It’s particularly confusing since it’s a full URL object that doesn’t fully match the URL of the request being sent.

### What do you see instead?

The URL object contains the origin and pathname, but not the query params.

### Additional information

It looks like this can be fixed by applying [this logic](https://github.com/honojs/hono/blob/90833d24670a8a679112fbcae0b8b0a09683333d/src/client/client.ts#L52-L66) in `$url()` [here](https://github.com/honojs/hono/blob/90833d24670a8a679112fbcae0b8b0a09683333d/src/client/client.ts#L174-L179)

If this is a desired change, I'm happy to open a PR!

**Comment by yusukebe** [comment]
Hi @alex-grover 

That's a good point. `$url` should accept `query`.

> If this is a desired change, I'm happy to open a PR!

Please create a PR!

I think we should update the type definition here:

https://github.com/honojs/hono/blob/90833d24670a8a679112fbcae0b8b0a09683333d/src/client/types.ts#L38-L44

It's a little complicated, so I can implement it if it's difficult for you.

**Comment by alex-grover** [comment]
will give it a shot on Monday and let you know, thanks for the pointer!
