### ISSUE TITLE
Etag middleware generating the same weak etag for different body content.

### ISSUE THREAD

**Issue by markusahlstrand** [honojs/hono#3536]
### What version of Hono are you using?

4.6.5

### What runtime/platform is your app running on?

Cloudflare workers

### What steps can reproduce the bug?

Generate a large response (20kb) with the etag middleware using weak etags, change a character in the response again.

### What is the expected behavior?

When changing the response body the etag should be different

### What do you see instead?

Different response bodies generate the same etag

### Additional information

When output'ing the respons body used for generating the hash it looks like this:
```
body ReadableStream {
  locked: false
}
```

This is the section in the middleware that we had a look at:
```
  const hash = await sha1(res.clone().body || '')
      etag = weak ? `W/"${hash}"` : `"${hash}"`
```

I'm guessing that hono starts to stream the body at some size of response body which breaks the etag functionality. I'm not sure what the best fix is in this case. Is it possible to disable the streaming or to read the entire stream into a string at this point?

**Comment by usualoma** [comment]
Hi @markusahlstrand

Thank you for your report. This is a known issue and is currently stuck, but there is a pull request.

https://github.com/honojs/hono/pull/2911
https://github.com/honojs/hono/pull/2918

I would like to fix it with one of these, so please wait a little.
