### ISSUE TITLE
Next.js 15: `Type "FetchEventLike" is not a valid type for the function's second argument.`

### ISSUE THREAD

**Issue by devjmetivier** [honojs/hono#3548]
### What version of Hono are you using?

4.6.5

### What runtime/platform is your app running on?

Node/Vercel

### What steps can reproduce the bug?

<img width="873" alt="Screenshot 2024-10-22 at 2 09 38 PM" src="https://github.com/user-attachments/assets/59166a06-ae1c-4a3f-ab50-10ba7d1c1c33">

☝️ The above error occurs when upgrading to Next.js 15. This, of course, uses `hono/vercel`'s handler with the Route Handler convention. Example:

```ts
import { api } from '@repo/api/hono';

import { handle } from 'hono/vercel';

export const DELETE = handle(api);
export const GET = handle(api);
export const POST = handle(api);
export const OPTIONS = handle(api);
```

Like the error indicates, it has to do with the `FetchEventLike` type from Hono:

https://github.com/honojs/hono/blob/3d8abbc2392277a2026ac09fb3929d9cb1ef2065/src/adapter/vercel/handler.ts#L5-L9

I don't know if simply removing the `requestContext` argument along with its type is sufficient, but when I remove it locally and try to build all seems to work just fine. I don't see anything in the [Route Handlers documentation](https://nextjs.org/docs/canary/app/building-your-application/routing/route-handlers) that says it can't be removed, but I defer to the maintainers.

### Additional information

I'm using this in a monorepo context, for clarity, but I don't think that's relevant for this specific error.

**Comment by yusukebe** [comment]
Hi @devjmetivier 

This is a bug. I'll fix it.

**Comment by AIEPhoenix** [comment]
@yusukebe Could you please release a new version soon? 🙏🏻
