### ISSUE TITLE
Cannot initialize starter template

### ISSUE THREAD

**Issue by Nanome203** [honojs/hono#3551]
### What version of Hono are you using?

4.6.6

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```pwsh
bun create hono@latest hono-tutorial
```

Choose cloudfare-workers template
Agree to install dependencies
Choose bun as package manager

### What is the expected behavior?

Starter template should get initialized

### What do you see instead?

```pwsh
create-hono version 0.14.2
✔ Using target directory … hono-tutorial
? Which template do you want to use? cloudflare-workers
? Do you want to install project dependencies? yes
? Which package manager do you want to use? bun
✔ Cloning the template
⠋ Installing project dependencies31234 |     afterCreateHook.applyHook(templateName, {
31235 |       projectName,
31236 |       directoryPath: targetDirectoryPath
31237 |     });
31238 |   } catch (e) {
31239 |     throw new Error(
                  ^
error: Error running hook for cloudflare-workers: No such file or directory
      at C:\Users\ME\AppData\Local\Temp\bunx-791187370-create-hono@latest\node_modules\create-hono\bin:31239:11
⠙ Installing project dependencies
Bun v1.1.32 (Windows x64)
```

### Additional information

When `cd hono-tutorial`, there was only the src folder, which contains nothing inside.
Also, if i choose bun as template, i get this error:
```pwsh
create-hono version 0.14.2
? Target directory my-app
? Which template do you want to use? bun
? Do you want to install project dependencies? yes
? Which package manager do you want to use? bun
✔ Cloning the template
× Failed to install project dependencies
```

**Comment by ryuapp** [comment]
If you don't have Node.js installed, this issue is the same as https://github.com/honojs/create-hono/issues/51.
This is a bug in Bun. Node.js is currently required when running `create-hono` with Bun on Windows.

**Comment by Nanome203** [comment]
> If you don't have Node.js installed, this issue is the same as [honojs/create-hono#51](https://github.com/honojs/create-hono/issues/51). This is a bug in Bun. Node.js is currently required when running `create-hono` with Bun on Windows. Ref: [oven-sh/bun#12150](https://github.com/oven-sh/bun/issues/12150)

Hi @ryuapp 
I just installed Node.js, and now it works like a charm. Thanks for your reply

**Comment by yusukebe** [comment]
@ryuapp Thanks for the response.

@Nanome203 I'll close this issue!
