### ISSUE TITLE
WebSocket on Bun throws an error after hot reloading

### ISSUE THREAD

**Issue by moroshko** [honojs/hono#3559]
### What version of Hono are you using?

4.6.6

### What runtime/platform is your app running on?

Bun 1.1.32

### What steps can reproduce the bug?

Consider the following web socket endpoint:
```ts
import type { ServerWebSocket } from 'bun'
import { Hono } from 'hono'
import { createBunWebSocket } from 'hono/bun'

const { upgradeWebSocket, websocket } =
  createBunWebSocket<ServerWebSocket>()

const app = new Hono().get(
  '/ws',
  upgradeWebSocket((c) => {
    return {
      async onMessage(event, ws) {
        console.log(`Message from client: ${event.data}`)
        ws.send("hello")
        await Bun.sleep(1000)
        ws.send("world")
      },
      onClose: () => {
        console.log('Connection closed')
      },
    }
  })
)

export default {
  fetch: app.fetch,
  port: 4355,
  websocket
}
```

When I start the server (`bun run --hot src/index.ts`), establish a web socket connection and send a message, the endpoint responds with "hello", and after 1 second "world". This is what I expect it to do.

However, if I now make a change in the code, e.g. change "world" to "bug", and save the code, the server reloads, but it doesn't work as expected from this point.
If I now send a message from the client, I see this error in the server, and I don't get back "hello" and "bug":
> TypeError: undefined is not an object (evaluating 'websocketListeners.onMessage')

![CleanShot 2024-10-25 at 16 56 09@2x](https://github.com/user-attachments/assets/01ecbba7-8b02-4860-bec3-d08af2ab55e7)

### What is the expected behavior?

After the server hot reloads, it should not throw an error and respond with "hello" and after 1 second "bug".

### What do you see instead?

Error above.

**Comment by yusukebe** [comment]
Hi @moroshko 

Thank you for raising the issue. Exactly, it is reproduced.

@nakasyou Sorry for pinging again. Can you take a look? But I don't know if it's a Hono-side matter or a Bun-side matter.

**Comment by nakasyou** [comment]
I think this is happening according to Bun's specifications.

When hot updated, Bun works as follows:
1. Revaluations all files
2. Global variable and WebSocket connections aren't lost.

From 1, `createBunWebSocket` is recalled and `websocketConns` is recreated. So Hono recognizes that the connection has been lost.
However, as I wrote in 2, WebSocket connections aren't lost. So if any event happens, helper inquire lost connection in `websocketConns`. Therefore error is thrown.

In order to resolve this problem, I have some idea:

1. Make able to receive `websocketConns` like:
```ts
globalThis.websocketConns ??= []
const { websocket, upgradeWebSocket } = createBunWebSocket({ websocketConns })
```

2. Handle lost connection id
This is easy. Just add undefined checking. But connection will continue in background.

**Comment by yusukebe** [comment]
@nakasyou 

Thank you! I'm working on it.

**Comment by yusukebe** [comment]
@nakasyou 

I'm not sure it's the perfect solution, but prefer "1"; putting the `websocketConns` value on the global like this:

```diff
diff --git a/src/adapter/bun/websocket.ts b/src/adapter/bun/websocket.ts
index 34b5b1ef..0c6b08cd 100644
--- a/src/adapter/bun/websocket.ts
+++ b/src/adapter/bun/websocket.ts
@@ -46,7 +46,8 @@ export const createWSContext = (ws: BunServerWebSocket<BunWebSocketData>): WSCon
 }

 export const createBunWebSocket = <T>(): CreateWebSocket<T> => {
-  const websocketConns: WSEvents[] = []
+  globalThis.__websocketConns ??= []
+  const websocketConns: WSEvents[] = globalThis.__websocketConns

   // eslint-disable-next-line @typescript-eslint/no-explicit-any
   const upgradeWebSocket: UpgradeWebSocket<any> = defineWebSocketHelper((c, events) => {
```

I don't feel so good about defining the value on the global, but it is okay to make it work correctly.

**Comment by nakasyou** [comment]
@yusukebe I agree. And I think `__websocketConns` should be more unique such as `__hono_bun_ws_websocketConns`.

**Comment by yusukebe** [comment]
@nakasyou 

Good. `__hono_bun_ws_websocketConns` makes sense!

**Comment by nakasyou** [comment]
@yusukebe, global variable is not needed. This problem is able to resolve to substitute event to data, without array indexes.

**Comment by yusukebe** [comment]
@nakasyou 👀 Can you create a PR?
