### ISSUE TITLE
Type error: Type '{ __tag__: "GET"; __param_position__: "second"; __param_type__: FetchEventLike; }' does not satisfy the constraint 'ParamCheck<RouteContext>'.

### ISSUE THREAD

**Issue by abhi123vj** [honojs/hono#3560]
### What version of Hono are you using?

4.6.6

### What runtime/platform is your app running on?

Bun and Next Js 15

### What steps can reproduce the bug?

![image](https://github.com/user-attachments/assets/da30b4cb-47f6-4923-ab69-dd794b5dab03)
On upgrading to nextjs 15 build fails
`.next/types/app/api/[...route]/route.ts:49:7
Type error: Type '{ __tag__: "GET"; __param_position__: "second"; __param_type__: FetchEventLike; }' does not satisfy the constraint 'ParamCheck<RouteContext>'.
  Types of property '__param_type__' are incompatible.
    Property 'params' is missing in type 'FetchEventLike' but required in type 'RouteContext'.

  47 |     Diff<
  48 |       ParamCheck<RouteContext>,
> 49 |       {
     |       ^
  50 |         __tag__: 'GET'
  51 |         __param_position__: 'second'
  52 |         __param_type__: SecondArg<MaybeField<TEntry, 'GET'>>
   Linting and checking validity of types  ...error: script "build" exited with code 1`

**Comment by shakibdshy** [comment]
I also facing the same issue.

**Comment by yusukebe** [comment]
Hi @abhi123vj 

This issue may be fixed in the latest version `4.6.7`. Can you try it?

**Comment by yusukebe** [comment]
This may be the same issue of #3548 .

**Comment by abhi123vj** [comment]
> Hi @abhi123vj
> 
> This issue may be fixed in the latest version `4.6.7`. Can you try it?

Yes the issue has been resolved in the version 4.6.7
