### ISSUE TITLE
Route Patterns: Inconsistency between `/a/*` and `/a/*/z` 

### ISSUE THREAD

**Issue by matthewrobb** [honojs/hono#360]
When routing with a trailing wildcard it is effectively matching against the leading pattern (`/a`). When routing with a nested wildcard it is matching against the leading pattern (`/a`) a single inner segment (`/*`) and a trailing segment (`/z`).

In the first case the wildcard can match any number of segments, in the second case it will only match a single segment. I'd suggest this is very confusing and limiting if intentional. These will both match the same things: `/a/:wild/z` and `/a/*/z` yet there is no way to match agains the trail end of the pattern. Perhaps I want to handle specific file types in a very particular way no matter what folder they are in.

My proposal would be to make `*` explicitly `0 or more segments` but using RegExp non-greedy semantics (`/(?:\/(.+?))?/`) and use that everywhere it could appear. So in my examples here it would look like `/^\/a(?:\/(.+?))?\/z$/`.

Bonus: Named wildcard patterns `"/a/*:path/z"`

**Comment by yusukebe** [comment]
Hi @matthewrobb, Thank you for your proposal.

I know the inconsistency, it's intentional.

Basically, we think the wildcard `*` should not match slash `/`:

```ts
app.get('/a/*/z')

// GET /a/b/z  => match
// GET /a/b/c/z => not match
```

But, wildcard `*` put on the last like `/a/*` will be *special* wildcard. The reason for making *special* wildcard is to make it easier to use middleware and to adapt the fallback pattern.

```ts
app.use('/admin/*', basicAuth())

// GET /admin/a => match
// GET /admin/a/b => match
```

In some cases, this may be confusing, but this is the specification.

**Comment by matthewrobb** [comment]
Does Hono plan on having any method of wildcarding multiple path segments preceding a literal or trailing named param? It would be WORKABLE if the regex pattern could be allowed to match on separators e.g. `app.get(":dirname{.*?}/:filename.:extension", ...)` as `/^(?<dirname>.*?)(?:\/(?<filename>[^/?#]*))(?:\.(?<extension>[^/?#]+))$/`

<img width="762" alt="image" src="https://user-images.githubusercontent.com/387251/178501904-ccbea3b9-039e-46a5-a4d6-9cdc19d8716d.png">

**Comment by matthewrobb** [comment]
@yusukebe curious if you "bless" the idea of building custom Router implementations? There aren't a ton of frameworks that offer such a feature but looking through it seems the interface is pretty simple. Alternatively possibly allow a function as the pattern argument: `app.route((req) => {}, )` so that we could write very specific matching logic to branch into sub routers or durable objects.

**Comment by yusukebe** [comment]
@matthewrobb 

> curious if you "bless" the idea of building custom Router implementations?

No. It's not so easy to implement, and we do not want to change specifications for the purpose.

**Comment by acrodrig** [comment]
Related to this, how should one specify "all paths ending in `.jpeg`" (as in *.jpeg) for example. Nothing I have tried seems to work.
