### ISSUE TITLE
The onOpen method of upgradeWebSocket cannot be triggered

### ISSUE THREAD

**Issue by TinsFox** [honojs/hono#3610]
### What version of Hono are you using?

4.6.8

### What runtime/platform is your app running on?

cloudflare workers

### What steps can reproduce the bug?

Just clone my repo https://github.com/TinsFox/webrtc-worker and run it

open http://localhost:3001/client

### What is the expected behavior?

The onOpen method runs normally and I can get the newly established link

### What do you see instead?

The onOpen method is unresponsive, as if it doesn't exist.

Can't see any output from the onOpen method.
```ts
   onOpen(evt, ws) {
          console.log("WebSocket opened")
          console.log("ws: ", ws)
          console.log("evt: ", evt)
          try {
            clients.add(ws)
            console.log("Client connected. Total clients:", clients.size)
          } catch (error) {
            console.error("Error in onOpen:", error)
          }
        },
```
<img width="811" alt="image" src="https://github.com/user-attachments/assets/e3f25a7c-c3e3-43a1-9048-14dfd12ca347">

### Additional information

I'm building a small project to share projects, here is an [example](https://github.com/codetheworld-io/remote-assistant-system) of implementation using node express, I want to implement it using hono, and that's using Cloudflare worders

The principle of implementation is to initialize a parameter in the client and then propagate it to the admin through ws. The admin uses this parameter to create an instance to display the client's screen.

**Comment by TinsFox** [comment]
Additional info, what I'm trying to accomplish is to build a ws server using hono and exchange data via ws.

client => ws => client

**Comment by nakasyou** [comment]
Hi @TinsFox, it is not Hono's bug. It is wrangler/Cloudflare Workers bug.
Look at https://hono.dev/docs/helpers/websocket#upgradewebsocket and https://github.com/honojs/hono/pull/2265#issuecomment-1962797843.

**Comment by EdamAme-x** [comment]
It is true that `open` is not called an event.  
You may need to remove `onOpen` from the available methods

https://developers.cloudflare.com/workers/runtime-apis/websockets/#methods

**Comment by TinsFox** [comment]
> Hi @TinsFox, it is not Hono's bug. It is wrangler/Cloudflare Workers problem. Look at [hono.dev/docs/helpers/websocket#upgradewebsocket](https://hono.dev/docs/helpers/websocket#upgradewebsocket) and [#2265 (comment)](https://github.com/honojs/hono/pull/2265#issuecomment-1962797843).

Thank you very much 🙏
