### ISSUE TITLE
Cloudflare workers error when caching large response: TypeError: ReadableStream.tee() buffer limit exceeded

### ISSUE THREAD

**Issue by JustJoostNL** [honojs/hono#3612]
### What version of Hono are you using?

4.6.8

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

You can use the below code to reproduce

```ts
const passthroughHeaders = [
  "content-disposition",
  "content-type",
  "content-length",
];

export const downloads = new Hono();

async function fetchAsset(owner: string, repo: string, assetId: number) {
  const url = `https://api.github.com/repos/${owner}/${repo}/releases/assets/${assetId}`;

  const response = await fetch(url, {
    headers: {
      Authorization: `token ${githubToken}`,
      Accept: "application/octet-stream",
      "User-Agent": userAgent,
    },
  });

  return response;
}

downloads.get(
  "/download/:assetId",
  cache({
    cacheName: "downloads",
    cacheControl: `public, max-age=${cacheTtl}, immutable`,
  }),
  async (c) => {
    const { assetId } = c.req.param();

    const originalResponse = await fetchAsset(
      "xxx",
      "xxx",
      parseInt(assetId),
    );

    if (originalResponse.status === 404) return c.notFound();
    if (!originalResponse.ok) {
      return c.json({ message: "Failed to fetch asset", status: 500 });
    }

    const headers = new Headers();
    passthroughHeaders.forEach((header) => {
      const value = originalResponse.headers.get(header);
      if (value) headers.set(header, value);
    });

    return new Response(originalResponse.body as BodyInit, {
      status: originalResponse.status,
      statusText: originalResponse.statusText,
      headers,
      cf: { cacheEverything: true, cacheTtl },
    });
  },
);
```

### What is the expected behavior?

The asset will download and cache correctly, without any error.

### What do you see instead?

For assets smaller than ~130MB, it does download and cache correctly. 

For assets bigger than ~130MB, it downloads until almost the end, and then errors (probably while trying to cache):

```txt
TypeError: ReadableStream.tee() buffer limit exceeded. This error usually occurs when a Request or Response with a large body is cloned, then only one of the clones is read, forcing the Workers runtime to buffer the entire body in memory. To fix this issue, remove unnecessary calls to Request/Response.clone() and ReadableStream.tee(), and always read clones/tees in parallel.
```

### Additional information

I think the 130MB is related to the [Cloudflare Workers memory limit](https://developers.cloudflare.com/workers/platform/limits/#memory), which is 128MB. 

I think it should still be possible to cache assets bigger than 128MB though. as the cache limit is 512MB. But this probably requires changes in the current cache middleware.

**Comment by yusukebe** [comment]
Hi @JustJoostNL 

> I think it should still be possible to cache assets bigger than 128MB though. as the cache limit is 512MB. But this probably requires changes in the current cache middleware.

I've never investigated the details, but my understanding is that Cache Middleware uses [the Cache API](https://developers.cloudflare.com/workers/runtime-apis/cache/) in the Workers runtime. So, the limit is 128MB. Cache Middleware can't support more than 128MB.

But, you can use "Cache using fetch":

https://developers.cloudflare.com/workers/examples/cache-using-fetch/

Please use this method instead of the Cache Middleware.

**Comment by JustJoostNL** [comment]
Hi @yusukebe,

Thanks for your reply. I've tried the Cache API, but unfortunately the caching seems to be a lot slower (almost 3 seconds of waiting time), whereas before (with assets slightly under 128MB), it was basically instant. It also doesn't seem to work with the `Age` header. Thanks for the suggestion though.

Do you have any other proposals?

**Comment by yusukebe** [comment]
@JustJoostNL 

As I wrote above, please use the "Cache using fetch" pattern.

> But, you can use "Cache using fetch":
> https://developers.cloudflare.com/workers/examples/cache-using-fetch/
> Please use this method instead of the Cache Middleware.

**Comment by JustJoostNL** [comment]
Hi @yusukebe,

Thanks, however, as mentioned earlier, I did try the "Cache using fetch" approach, but it has a few drawbacks:

**Performance**: The caching process becomes slower, with around 3 seconds of waiting time, compared to near-instant caching with the Cache Middleware.
**Age Header**: It doesn’t seem to work with the Age header, which I need for cache control.

Do you have any ideas on how to optimize the performance when using the "Cache using fetch" pattern, or are there other alternatives for caching larger assets efficiently while still leveraging Cloudflare Workers?
