### ISSUE TITLE
Timeout middleware missing from jsr.json

### ISSUE THREAD

**Issue by avihavai** [honojs/hono#3635]
### What version of Hono are you using?

4.6.5 (applies for 4.6.9 as well)

### What runtime/platform is your app running on? (with version if possible)

Deno 2.0.2 (applies to newer versions as well)

### What steps can reproduce the bug?

Using the code following code reproduces the issue:

```javascript
import { timeout } from "jsr:@hono/hono@4.6.5/timeout";
```

### What is the expected behavior?

The expected behavior is that the timeout middleware would be available.

### What do you see instead?

The timeout middleware is not available. 

### Additional information

Adding the following line to `jsr.json` should fix it.

```
    "./timeout": "./src/middleware/timeout/index.ts",
```

Thank you for your work on Hono! :)

**Comment by EdamAme-x** [comment]
thanks
