### ISSUE TITLE
[Document] Highlight Cloudflare Workers Environment Differences

### ISSUE THREAD

**Issue by catnaut** [honojs/hono#3646]
### What is the feature you are proposing?

I attempted to modify the HonoRequest headers directly via c.req.raw.headers, but encountered an error: TypeError: Can't modify immutable headers. This functionality works as expected on Bun. After reviewing the Cloudflare Workers documentation, I discovered that the Request object is entirely immutable in this environment, including its headers.

To help developers understand such differences, I propose adding a note to the documentation that highlights the immutability of the Request object in Cloudflare Workers and encourages awareness of environment-specific behaviors in Cloudflare Workers versus other environments.
## Reference

[Request | Cloudflare Workers docs](https://developers.cloudflare.com/workers/runtime-apis/request/#background#_top:~:text=You%20may%20also%20want%20to%20construct%20a%20Request%20yourself%20when%20you%20need%20to%20modify%20a%20request%20object%2C%20because%20the%20incoming%20request%20parameter%20that%20you%20receive%20from%20the%20fetch()%20handler%20is%20immutable.)
> You may also want to construct a `Request` yourself when you need to modify a request object, because the incoming `request` parameter that you receive from the [`fetch()` handler](https://developers.cloudflare.com/workers/runtime-apis/handlers/fetch/) is immutable.

## Code Examples

This code will fail in Cloudflare Workers due to the immutability of the Request headers. (Adapted from #2847)
```ts
app.use(async (c, next) => {
  c.req.raw.headers.set('x-username', '6km')
  await next()
})

app.get('/', (c) => {
  return c.json(c.req.header())
}) 
```

This code works in Cloudflare Workers by creating a new Request instance with modified headers.

```ts 
app.use(async (c, next) => {
  const newHeader = new Headers(c.req.raw.headers);
  newHeader.append("test", "test");

  c.req.raw = new Request(c.req.raw, {
    headers: newHeader,
  });
  await next();
});
```

**Comment by yusukebe** [comment]
Hi @catnaut 

I think this is not only a matter of Cloudflare Workers. The same behavior has occurred on Deno. There are different implementations, but perhaps the specification is that the header should be immutable.

By the way, we are working on discussion the Proxy Helper for the proxy use case to avoid the user writing code for copying headers: https://github.com/honojs/hono/pull/3589

**Comment by yusukebe** [comment]
We already added the caution for it on our website: https://hono.dev/examples/proxy#proxy

**Comment by catnaut** [comment]
> Hi @catnaut
> 
> I think this is not only a matter of Cloudflare Workers. The same behavior has occurred on Deno. There are different implementations, but perhaps the specification is that the header should be immutable.
> 
> By the way, we are working on discussion the Proxy Helper for the proxy use case to avoid the user writing code for copying headers: #3589

awesome work on this! 👍
