### ISSUE TITLE
`every` middleware does not pass `param` to the wrapped middleware if global middleware is present

### ISSUE THREAD

**Issue by paolostyle** [honojs/hono#3657]
### What version of Hono are you using?

4.6.9

### What runtime/platform is your app running on? (with version if possible)

Node, but same thing happens on Bun and Deno

### What steps can reproduce the bug?

Consider this test:

```ts
  it('Should pass the path params to middlewares', async () => {
    const app = new Hono();
    app.use('*', nextMiddleware)
    const paramMiddleware: MiddlewareHandler = async (c) => {
      return c.json(c.req.param(), 200)
    }

    app.use('/:id', every(paramMiddleware))
    app.get('/:id', (c) => {
      return c.text('Hello World')
    })

    const res = await app.request('http://localhost/123')
    expect(await res.json()).toEqual({ id: '123' })
  })
```

This test will currently fail, the result will be `{}`. Somehow because of the global middleware (`app.use('*', nextMiddleware)`) `c.req.param` returns an empty object when used on a route with route params. It only happens when it's wrapped in `every` middleware.

### What is the expected behavior?

`c.req.param()` should return `{ id: '123' }` in the example above.

### What do you see instead?

`c.req.param()` returns `{}` despite being used in a route with route params.

### Additional information

The test will pass if we either remove the middleware applied to every route, or remove the `every` middleware (i.e. use `paramMiddleware` directly. This is naturally a trivial example, but a real life example would be if we e.g. wrapped a bunch of `validator` middlewares in `every`. Validation will fail in that case.

I'm pretty sure this is caused by `combine` but I don't know how to fix it myself; I'm wondering if passing `c.req.param` in `every` to `combine` might've been related to this issue but it's not used in `combine` at all.

**Comment by usualoma** [comment]
Hi @paolostyle, Thanks for the report. I'll fix it, so wait a minute.
