### ISSUE TITLE
Cannot access invalid private field 'app.#errorHandler'

### ISSUE THREAD

**Issue by TiBianMod** [honojs/hono#3671]
### What version of Hono are you using?

4.6.10

### What runtime/platform is your app running on? (with version if possible)

bun

### What steps can reproduce the bug?

related of using `bull-board` with `Hono`
`open issues`: https://github.com/felixmosh/bull-board/issues/843

### What do you see instead?

```sh
84 |   #errorHandler = errorHandler;
85 |   route(path, app) {
86 |     const subApp = this.basePath(path);
87 |     app.routes.map((r) => {
88 |       let handler;
89 |       if (app.#errorHandler === errorHandler) {
               ^
TypeError: Cannot access invalid private field (evaluating 'app.#errorHandler')
      at /Users/tt/Code/bull-board/examples/with-hono/node_modules/hono/dist/hono-base.js:89:11
      at map (1:11)
      at route (/Users/tt/Code/bull-board/examples/with-hono/node_modules/hono/dist/hono-base.js:87:16)
      at /Users/tt/Code/bull-board/examples/with-hono/index.js:55:7
```

**Comment by yusukebe** [comment]
@TiBianMod 

This is not a bug. The `errorHandler` was a `private` function, though it was introduced in #3596:

https://github.com/honojs/hono/pull/3596/files#diff-f42b11987a9538ff250a31ba4eb66ee557f7512860fae88c5020a83b5e97c28cL187

Users should not use it.

**Comment by TiBianMod** [comment]
i know is introduced in https://github.com/honojs/hono/pull/3596
`#errorHandler` is not accessible from `app`
https://github.com/honojs/hono/blob/96006d733a3bfe27f5215f7304a85da5859ec0d9/src/hono-base.ts#L219

**Comment by TiBianMod** [comment]
@yusukebe please checkout PR https://github.com/honojs/hono/pull/3673
