### ISSUE TITLE
type inference for `c.req.json()`

### ISSUE THREAD

**Issue by tmokmss** [honojs/hono#3679]
### What is the feature you are proposing?

When I define a route handler with the following code, the variable `foo` is infered as `any`, where I want it to be `string` without additional type annotation.

```ts
{
  const route = createRoute({
    method: 'post',
    path: '/',
    request: {
      body: {
        content: {
          'application/json': {
            schema: z.object({
              foo: z.string(),
            }),
          },
        },
      },
    },
    responses: {
      200: {
        description: 'success',
      },
    },
  });

  app.openapi(route, async (c) => {
    const { foo } = await c.req.json();
    return c.json({}, 200);
  });
}
```

It appears the HonoRequest type already has enough information to infer the json type:

<img width="989" alt="image" src="https://github.com/user-attachments/assets/c2ad47d5-ec2d-4709-9cff-e88f3893b8a7">

However `foo` is inferred as any:

<img width="550" alt="image" src="https://github.com/user-attachments/assets/bfe6801d-3ffc-4b05-a63e-6500b63b68e6">

`c.req.json<{foo:string}>()` works, but it would be great if we can avoid adding (seemingly) redundant type annotation, like how `c.req.valid('query')` works.

Let me know if I'm misusing something, thanks!

**Comment by tmokmss** [comment]
I found `c.req.valid('json')` seems to work as expected, but not sure why c.req.json is async whereas c.req.valid is sync function? Is there any behavioural difference?

**Comment by EdamAme-x** [comment]
@tmokmss 
Already called internally
https://github.com/honojs/hono/blob/main/src/validator/validator.ts#L78

**Comment by tmokmss** [comment]
@EdamAme-x @yusukebe Thanks for the guidance!
Still not sure how the async function works in sync call but I'll look into the code 🙏

**Comment by EdamAme-x** [comment]
> Still not sure how the async function works in sync call but I'll look into the code later 🙏

The `c.req.json` is called and validated in the asynchronous middleware before `c.req.valid` is called.  
After that, the validated data is kept in the Context so that it can be called synchronously.

**Comment by tmokmss** [comment]
@EdamAme-x That makes sense! I just started learning hono and you helped me a lot :) thank you so much!
