### ISSUE TITLE
403 when multipart/form-data is added as content-type

### ISSUE THREAD

**Issue by adex-codez** [honojs/hono#3684]
### What version of Hono are you using?

4.5.8

### What runtime/platform is your app running on? (with version if possible)

Cloudflare workers

### What steps can reproduce the bug?

So when i try to upload files on my upload endpoint and i make the content-type of the request to be multipart/form-data a 403 status code is thrown

This the code snippet for cors
``` typescript
app.use("*", cors({
  origin: "*",
  credentials: true,
  allowHeaders: ["Content-Type", "Authorization"],
  allowMethods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE'],
}))
```

This is the code snippet for the upload route
```ts
productRoutes.post(
  "/upload-image",
  async (c) => {
   // Use the formData() method to parse the form data
    const body = await c.req.parseBody();
    const file = body["file"]

    // Access the uploaded file (assuming form field is named "file")
    //if (!file) return c.json({error: "No file uploaded!"}, 400)

    // File metadata
    console.log(file);
    return c.json({})
 }
)
```

### What is the expected behavior?

the expected behaviour is to allow my api to upload the file and give status code based on the success of the file upload

**Comment by EdamAme-x** [comment]
The list of middleware that returns 403 on Hono, but you do not appear to be using it, so I think it does not seem to be Hono problem.

https://github.com/search?q=repo%3Ahonojs%2Fhono%20403&type=code

**Comment by EdamAme-x** [comment]
Same issue
https://github.com/honojs/hono/issues/3265
https://github.com/honojs/hono/issues/2226

**Comment by yusukebe** [comment]
@adex-codez Can you share a minimal project to produce it? If you can't, I'll close this issue.

**Comment by yusukebe** [comment]
I'll close this since there has not been a reaction.
