### ISSUE TITLE
env(c) does not get overridden Bindings sent via app.request() but c.env does

### ISSUE THREAD

**Issue by Soviut** [honojs/hono#3706]
### What version of Hono are you using?

4.6.11

### What runtime/platform is your app running on? (with version if possible)

Node

### What steps can reproduce the bug?

Start the following with a `DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres` already defined at the system level

```typescript
import { Hono, Context, Next } from 'hono'
import { env } from 'hono/adapter'

interface Bindings {
  DATABASE_URL: string
}

const app = new Hono<{ Bindings: Bindings }>()

app.use(async (c: Context<{ Bindings: Bindings }>, next: Next) => {
  const { DATABASE_URL } = env(c)

  console.log('Middleware env(c) DATABASE_URL', DATABASE_URL)
  console.log('Middleware c.env.DATABASE_URL', c.env.DATABASE_URL)

  return next()
})

app.get('/', async (c) => {
  const { DATABASE_URL } = env(c)

  console.log('Route env(c) DATABASE_URL', DATABASE_URL)
  console.log('Route c.env.DATABASE_URL', c.env.DATABASE_URL)

  c.text('ding!')
})

// override the Bindings
app.request('/', undefined, { DATABASE_URL: 'postgres://xxx:yyy@localhost:5432/zzz' })
```

### What is the expected behavior?

I expect `env(c)` to get its values from the Bindings sent through `app.request()` the same way `c.env` does.

```
Middleware env(c) DATABASE_URL postgres://xxx:yyy@localhost:5432/zzz
Middleware c.env.DATABASE_URL postgres://xxx:yyy@localhost:5432/zzz

Route env(c) DATABASE_URL postgres://xxx:yyy@localhost:5432/zzz
Route c.env.DATABASE_URL postgres://xxx:yyy@localhost:5432/zzz
```

### What do you see instead?

`env(c)` gets the old system defined `DATABASE_URL` while `c.env` gets the updated overridden Bindings passed by `app.request()`

```
Middleware env(c) DATABASE_URL postgres://postgres:postgres@localhost:5432/postgres
Middleware c.env.DATABASE_URL postgres://xxx:yyy@localhost:5432/zzz

Route env(c) DATABASE_URL postgres://postgres:postgres@localhost:5432/postgres
Route c.env.DATABASE_URL postgres://xxx:yyy@localhost:5432/zzz
```

**Comment by EdamAme-x** [comment]
I think it seems to be expected result
https://github.com/honojs/hono/blob/main/src/helper/adapter/index.ts#L10

**Comment by Soviut** [comment]
@EdamAme-x This isn't documented so it was unexpected behaviour.

**Comment by yusukebe** [comment]
That is documented in this section: https://hono.dev/docs/api/context#env. Or can you create a PR for a document for it?

**Comment by Soviut** [comment]
@yusukebe sounds good. I'll probably try to have their docs reference each other and explain the slight differences in behaviour. Now to think how to word it correctly...
