### ISSUE TITLE
ipRestriction not catching ::ffff:127.0.0.1

### ISSUE THREAD

**Issue by jnatmorris** [honojs/hono#3723]
### What version of Hono are you using?

4.6.12

### What runtime/platform is your app running on? (with version if possible)

Node

### What steps can reproduce the bug?

import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { logger } from "hono/logger";
import { ipRestriction } from "hono/ip-restriction";
import { getConnInfo } from "@hono/node-server/conninfo";

const app = new Hono()
	.use(logger())
	.use(async (c, next) => {
		console.log(getConnInfo(c));
		await next();
	})
	.use(
		"*",
		ipRestriction(getConnInfo, {
			denyList: [],
			allowList: ["127.0.0.1", "::1", "::ffff:127.0.0.1"],
		}),
	)
	.get("/", (c) => {
		return c.text("will not reach");
	})

### What is the expected behavior?

HTTP requests from any of the allowed list shall be able to reach the `.get("/",(c)=>{...}`.

### What do you see instead?

When making HTTP requests from the same computer (localhost), a 403 is returned. 

![Screenshot 2024-12-04 at 20 37 44](https://github.com/user-attachments/assets/48dc10f6-dfb6-4a6a-931a-9d647885dd52)

### Additional information

At first I was only making my HTTP requests from a nextjs server component. This did not work. I then used an HTTP making client, and am running into the same issue.

**Comment by EdamAme-x** [comment]
In internal, `::ffff:127.0.0.1` converted to `::ffff:127`
maybe this is bug
