### ISSUE TITLE
Hono RPC Type Inference Issue in Frontend Client with generic types

### ISSUE THREAD

**Issue by edproton** [honojs/hono#3738]
### What version of Hono are you using?

4.6.13

---

### What runtime/platform is your app running on? (with version if possible)

Bun 1.1.38

---

### What steps can reproduce the bug?

1. Define reusable types in an external file, such as:
   ```typescript
   export interface PaginatedResponse<T> {
     items: T[];
     metadata: {
       total: number;
       page: number;
       limit: number;
       pages: number;
     };
   }

   export type BookingWithRelations = Prisma.BookingGetPayload<{
     select: {
       startTime: true;
       endTime: true;
       title: true;
       status: true;
       host: {
         select: {
           id: true;
           name: true;
           image: true;
         };
       };
       participants: {
         select: {
           id: true;
           name: true;
           image: true;
         };
       };
     };
   }>;
   ```

2. Use these types in a handler and route file:
   - **Handler**:
     ```typescript
     export class GetBookingsCommandHandler {
       static async execute(command: GetBookingsCommand): Promise<PaginatedResponse<BookingWithRelations>> {
         // Logic here
       }
     }
     ```
   - **Route**:
     ```typescript
     export const bookingRoutes = new Hono()
       .get("/", async (c) => {
         const bookings: PaginatedResponse<BookingWithRelations> =
           await GetBookingsCommandHandler.execute(command);

         return c.json(bookings, 200);
       });
     ```
3. Use the client on the frontend to interact with the API:
   ```typescript
   import { AppType } from "../backend/src/index";
   import { hc } from "hono/client";

   const client = hc<AppType>("http://localhost:8787/");

   client.bookings.$get({}).then(async (bookings) => {
     const r = await bookings.json();

     console.log(r.total);
   });
   ```

4. Observe that:
   - The generic types (`PaginatedResponse<BookingWithRelations>`) are not correctly enforced unless explicitly redefined or cast within the route file.
   - On the client, type inference does not work, and TypeScript cannot infer the structure of the `bookings` response.

---

### What is the expected behavior?

- The `PaginatedResponse` and `BookingWithRelations` types should be seamlessly recognized and enforced when imported from an external file, both on the server and the client.
- TypeScript should correctly infer the response type when using the `hc` client to interact with the backend.

---

### What do you see instead?

- The types are not correctly inferred or enforced unless they are explicitly redefined or cast within the route file.
- On the client, TypeScript does not infer the response type when interacting with the backend using the `hc` client.

---

### Additional information

- This issue affects the usability of `Hono` when structuring code with external type definitions, especially in larger projects where reusability and maintainability are crucial.
- Example of an unwanted workaround on the server:
  ```typescript
  const bookings = await GetBookingsCommandHandler.execute(command) as PaginatedResponse<BookingWithRelations>;
  ```
- Example of an unwanted workaround on the client:
  ```typescript
  client.bookings.$get({}).then(async (bookings: PaginatedResponse<BookingWithRelations>) => {
    const r = await bookings.json();
    console.log(r.total);
  });
  ```

**Comment by yusukebe** [comment]
I'll close this issue because there is no reaction.
