### ISSUE TITLE
`charaset` parameter is not required for JSON MIME type

### ISSUE THREAD

**Issue by SaekiTominaga** [honojs/hono#3739]
### What version of Hono are you using?

4.6.13

### What runtime/platform is your app running on? (with version if possible)

Node.js 22

### What steps can reproduce the bug?

When a static JSON file is displayed with `serveStatic()`, `application/json; charset=utf-8` is returned.

### What is the expected behavior?

The `charset` parameter is not required for the MIME type of a JSON.

The current JSON specification (RFC 8259) does not allow anything other than UTF-8 to begin with.

In IANA, `application/json` is “Optional parameters: n/a”.

- [RFC 8259 – Section 11](https://www.rfc-editor.org/rfc/rfc8259.html#section-11)
- [Media Types – application/json](https://www.iana.org/assignments/media-types/application/json)

Therefore, the MIME type should be only `application/json`.

### Additional information

I am ready to do PR !

**Comment by yusukebe** [comment]
Hi @SaekiTominaga 

You are right. It does not need the `charset`.

> I am ready to do PR !

Please!
