### ISSUE TITLE
Requests getting stuck in pending

### ISSUE THREAD

**Issue by uxkjaer** [honojs/hono#374]
I'm trying to use Hono together with Bun as a local dev server. I want to serve my resources through the server. 
Currently when I run the app, it is trying to serve the resources, but requests are getting stuck in pending.
It seems to random which requests freezes in pending.
![image](https://user-images.githubusercontent.com/8186370/178664840-5d49acc6-8a9e-4a3a-ae74-be698c213365.png)

Any suggestions?

**Comment by yusukebe** [comment]
Hi @uxkjaer !

I want to know your code or snippets. Serving static files is not implemented in the current version (*serve-static* middleware for Bun will be available in the next version *v2.0.0*).

Do you use the code like in the example folder at the Bun repository?
<https://github.com/oven-sh/bun/blob/main/examples/http-file.ts#L5>

**Comment by yusukebe** [comment]
I'll close this issue. Feel free to reopen it.
