### ISSUE TITLE
middleware [logger] & [requestId] logger does not include requestId

### ISSUE THREAD

**Issue by valerii15298** [honojs/hono#3744]
### What is the feature you are proposing?

There is *logger* and *requestId* middleware inside hono. But *logger* middleware does not include `requestId` into logs. And it(*logger* middleware) is pretty much useless in any app where monitoring by requests is needed.
When you log request elapsed time you wanna know for which request is it. I do not see any reason to have it separate. Logging `requestId` is essential key part for tracing and monitoring an app.

I would suggest to combine these to things or make it possible to include `requestId` into logs.

**Comment by hls-app** [comment]
How about a customLogger?

```ts
export const customLogger = (message: string, ...rest: string[]) => {
  console.log(message, ...rest)
}

app.use(logger(customLogger))
```

**Comment by valerii15298** [comment]
@hls-app and how would you log requestId in this way?
you can't access `requestId` from custom logger in your example. It is just for different formatting, there is no access to the context from it.

**Comment by EdamAme-x** [comment]
I think I can make the entire middleware myself.
You can refer to it.

**Comment by hls-app** [comment]
@valerii15298 you could call `customLogger(`Request ID: ${c.get('requestId')}`)` from any route or you could create your own custom logger as @EdamAme-x suggested.

If you need access to context outside, you can refer to https://hono.dev/docs/middleware/builtin/context-storage

**Comment by valerii15298** [comment]
@hls-app thanks, yeah you are right I can access it from context storage. But it is just simpler to create custom middleware instead which I have done for myself. The idea of this issue was somehow to combine logger and requestId middlewares so that user would not need much configuration. Using context storage seems just overkill for me for this task.

And also it is not intuitive for me how context storage works, how it detects which context to return if there could be multiple requests processing at the same time, but that is just my skill issue. Closing this as I do not clearly see how to resolve it and will just use custom middleware.

**Comment by bestickley** [comment]
copy and paste solution:
```ts
import type { MiddlewareHandler } from "hono";

import type { AppContext } from "../types/context";

/**
 * Logger middleware that prefixes logs with the request ID (from c.get('requestId')).
 * Similar to Hono's default logger, but adds request ID prefix to each log line.
 *
 * Usage: app.use(logger())
 */
export function logger(): MiddlewareHandler<AppContext> {
  return async (c, next) => {
    const req = c.req;
    const start = Date.now();
    await next();
    const end = Date.now();
    const method = req.method;
    const path = req.path;
    const status = c.res.status;
    const requestId = c.get("requestId") ?? "-";
    // Format: [requestId] <method> <path> <status> <ms>ms
    // Example: [123e4567-e89b-12d3-a456-426614174000] GET /api/foo 200 12ms
    // You can add more fields as needed
    // Use console.log for output (matches Hono default)
    console.log(`[${requestId}] ${method} ${path} ${status} ${end - start}ms`);
  };
}

```
