### ISSUE TITLE
Param parsing with a dot in the path doesn't capture all the parameters

### ISSUE THREAD

**Issue by kingmesal** [honojs/hono#3745]
### What version of Hono are you using?

4.6.12

### What runtime/platform is your app running on? (with version if possible)

Local

### What steps can reproduce the bug?

Using the standard default Hono configuration...

Use this route `"/e/:type/:batch/:hash.:dest"`
curl localhost:8080/e/o/123/echo-bravo-delta.location

It will get properly routed, but a call to `c.req.param()` yields the following:
```json
{
  "hash.:dest": "echo-bravo-delta.location",
  "batch": "123",
  "type": "o"
}
```

### What is the expected behavior?

It should yield this:
```json
{
  "dest": "location",
  "hash": "echo-bravo-delta",
  "batch": "123",
  "type": "o"
}
```

**Comment by EdamAme-x** [comment]
I think that this is not a bug.
Path param should one param by one part

**Comment by kingmesal** [comment]
if someone needed to capture the filename separate from the extension of a path, like `/images/:imageName.:imageExtension`

How would they do that?

**Comment by EdamAme-x** [comment]
Hi @kingmesal 

Can the router capture it?

Perhaps, I think it is capturing even if there is no ".

Try the following
https://hono.dev/docs/api/routing#regexp

Hono support regex path

**Comment by kingmesal** [comment]
I tested trying to get regexp to do it and no luck. That example in the docs doesn't show capture a following example.

Others have tried looked at this as well and no one has found a way to make it work. There is a thread in the discord
https://discord.com/channels/1011308539819597844/1316803274548056125

I feel like my ask is fairly simple and VERY common, yet no one can make it work. I would say this is a severe limitation of the param parser.

**Comment by EdamAme-x** [comment]
Is that true?
Is the router you are using the default (smart router with regexp, trie)?

**Comment by EdamAme-x** [comment]
I may have been able to reproduce the problem.

https://stackblitz.com/edit/vitejs-vite-jq3yet4e?file=index.js

**Comment by EdamAme-x** [comment]
This is working
```ts
import { Hono } from 'hono';
import { testClient } from 'hono/testing';

const app = new Hono().get('/files/:filename{[a-z]+\\.[a-z]+}', async (c) =>
  c.json({ filename: c.req.param('filename') })
);

const tc = testClient(app);

(async () => {
  console.log(
    await (
      await tc.files[':filename{[a-z]+\\.[a-z]+}'].$get({
        param: {
          filename: 'hono.js',
        },
      })
    ).text()
  );
})();
```

but, this is not working
```ts
import { Hono } from 'hono';
import { testClient } from 'hono/testing';

const app = new Hono().get('/files/:filename{\\.}', async (c) =>
  c.json({ filename: c.req.param('filename') })
);

const tc = testClient(app);

(async () => {
  console.log(
    await (
      await tc.files[':filename{\\.}'].$get({
        param: {
          filename: 'hono.js',
        },
      })
    ).text()
  );
})();
```

**Comment by yusukebe** [comment]
This is not a bug. It's expected behavior.

**Comment by EdamAme-x** [comment]
@kingmesal 
This may be the optimal solution.
`/files/:filename{[a-zA-Z0-9]\\.[a-zA-Z0-9]}`

**Comment by kingmesal** [comment]
I feel like I tried a regex very similar to that and it didn't work.... how
do you capture the filename separately from the extension?

2 separate parameters separated by the dot.

**Comment by EdamAme-x** [comment]
hi @kingmesal 
i believe that is best handled on the javascript side.
`const [filename, ext] = c.req.param("filename")`

**Comment by EdamAme-x** [comment]
hi @kingmesal 
i believe that is best handled on the javascript side.
`const [filename, ext] = c.req.param("filename").split(".")`

**Comment by kingmesal** [comment]
Here is where I am.

Route: `app.get("/e/:type/:batch/:filename.ext", zValidator("param", Params), ....`

ZodSchema:
```typescript
const Params = z
  .object({
    type: z.string().,
    batch: z.string().,
    "filename.ext": z.string().transform((val) => {
      const [filename, ext] = val.split(".");
      return { filename, ext };
    }),
    filename: z.string().optional(),
    ext: z.string().optional(),
  })
  .transform((data) => ({ ...data, ...data["filename.ext"] }));
type Params = Required<z.infer<typeof Params>>;
```

I'm fine moving forward with this, but...

Something should be added to the documentation for this type of use case because other routers out there do support param parsing/splitting with more than just '/' characters. People who were using Cloudflare Pages and convert to working and use Hono are likely to run into this problem (I am that person) and more people will come along.

Other people I had asked in Cloudflare said 
> That sounds like a Hono bug to me and is worth reporting

If this is expected behavior, I think documentation improvement is VERY well warranted for this.

**Comment by ambergristle** [comment]
i've found hono's api for standard params and queries to be really intuitive, but i agree that it would be helpful to include some specs on the regex used by each router in order to highlight edge cases. i believe that `LinearRouter`, for example, won't work for this use-case at all.

@kingmesal fwiw, i think you could simplify the schema a bit:
```typescript
const Params = z
  .object({
    type: z.string(),
    batch: z.string(),
    "filename.ext": z.string().regex(/\w+\.\w+/), // or whatever is relevant
  })
  .transform(({ 'filename.ext': extendedName, ...data }) => {
    const [filename, ext] = extendedName.split('.')

    return {
      ...data,
      filename,
      ext,
    }
  });
```

**Comment by SamuelGaona** [comment]
+1

**Comment by SamuelGaona** [comment]
> [@kingmesal](https://github.com/kingmesal) This may be the optimal solution. `/files/:filename{[a-zA-Z0-9]\\.[a-zA-Z0-9]}`

Resolved like this, had to use RegExp Groups, but working fine.

**Comment by kingmesal** [comment]
Great! But, I think maybe you didn't read the problem I posted...

Use this route `/e/:type/:batch/:hash.:dest`

there are 4 variables to capture.
