### ISSUE TITLE
Not able to pass the bearer token as a headers not working

### ISSUE THREAD

**Issue by anishkumar127** [honojs/hono#3754]
### What version of Hono are you using?

^4.6.12

### What runtime/platform is your app running on? (with version if possible)

Node

### What steps can reproduce the bug?

```ts
import { client } from '@/lib/hono';
import { useQuery } from '@tanstack/react-query';
export const useGetTickets = (token: string) => {
  const query = useQuery({
    queryKey: ['tickets', token],
    queryFn: async () => {
      if (!token) throw new Error('No token provided');

      const response = await client.api.v1.tickets.read.$get({
        headers: {
          Authorization: `Bearer ${token ?? ''}`,
        },
      });
      if (!response.ok) throw new Error('Failed to fetch tickets');

      const { data } = await response.json();
      return data;
    },
  });

  return query;
};
```

### What do you see instead?

it's should pass the headers but it's not taking the headers bearer token

### Additional information

i want to jwt verification in my each api and it's can be different so that i passing as a useGetTickets (token) and that passing into the $get() method inside it's not working not taking token also it's not working in $post also.

**Comment by EdamAme-x** [comment]
Please logging token, and it's logged?

**Comment by anishkumar127** [comment]
> Please logging token, and it's logged?

actually 

```ts
  const response = await client.api.v1.tickets.read.$get({
        headers: {
          Authorization: `Bearer ${token ?? ''}`,
        },
      });
```
in this line.  ```ts  headers: {
          Authorization: `Bearer ${token ?? ''}`,
        }, ``` this headers are not working it's not supported this way.

**Comment by yusukebe** [comment]
Hi @anishkumar127 

It's no a bug. The way to add headers is [documented](https://hono.dev/docs/guides/rpc#headers). Try the following code: 

```ts
const response = await client.api.v1.tickets.read.$get(undefined, {
  headers: {
    Authorization: `Bearer ${token ?? ''}`
  }
})
```

**Comment by anishkumar127** [comment]
> Hi @anishkumar127
> 
> It's no a bug. The way to add headers is [documented](https://hono.dev/docs/guides/rpc#headers). Try the following code:
> 
> ```ts
> const response = await client.api.v1.tickets.read.$get(undefined, {
>   headers: {
>     Authorization: `Bearer ${token ?? ''}`
>   }
> })
> ```

Oh ok thank you so much ❤️ I will try & as of now I'm closing this issue. 😅
