### ISSUE TITLE
RPC Client does not maintain the Date type

### ISSUE THREAD

**Issue by cybercoder-naj** [honojs/hono#3771]
### What version of Hono are you using?

4.5.5

### What runtime/platform is your app running on? (with version if possible)

Bun 1.1.38

### What steps can reproduce the bug?

```ts
// server code
import { Hono } from 'hono';

const app = new Hono()
  .get('/date', async c => {
    const date = new Date();
    const resBody = {
      msg: 'The time is:',
      date: date
    }; // <-- This is typed as {msg: string, date: Date}
    return c.json(resBody, 200);
  })

// client code
const client = hc<typeof app>(BASE_URL);
const response = await client.$get();
const body = await response.json(); // <-- this is typed as {msg: string, date: string}
```

### What is the expected behavior?

The expected behaviour is:

```ts
// client code
const client = hc<typeof app>(BASE_URL);
const response = await client.$get();
const body = await response.json(); // <-- this is typed as {msg: string, date: Date} <<< 
```

### What do you see instead?

The Date type from the return of the handler is converted to a string. In how I see this, the client does not de-serialize the string from the network request back to the Date class, as it should.

### Additional information

The same behaviour is seen from the `testClient()` function.

```ts
// in server test files
const client = testClient(app);
const response = await client.$get();
const body = await response.json(); // <-- this is typed as {msg: string, date: string}
                                    // It should be {msg: string, date: Date}
```

**Comment by yusukebe** [comment]
@askorupskyy is right. This is not a bug.

**Comment by cybercoder-naj** [comment]
True, I understand the reason why it is a string. However, the term RPC (Remote Procedure Call) should essentially, to the developer, be like calling a regular function, in this case, calling `await client.$get(...)` should return a Date regardless how it works behind the scenes. 

In my understanding of RPC, not only the request payload is sent but also some optional metadata, which can be used to decipher how to serialize/de-serialize objects, which isnt universal to all languages/architectures.

**Comment by askorupskyy** [comment]
@cybercoder-naj I agree, but tbh I don't think this should be a part of Hono's core functionality. Even tRPC does not have this out of the box.

Instead what Hono should aim for is the support for `superjson` – a more complex JSON serializer that allow for rgx, date, map, set (de)serialization. You can try to play around with this and build your own solution. Luckily, extensive Hono context API and custom `fetch` override should do it.

Here's a rough example of what this could look like:

```typescript
import { Context } from 'hono';

const sendSerializedJson<P extends Record<string, unknown>>(c: Context, payload: P){
  c.status(200);
  return c.json(superjson.stringify(payload) as P); // should give you RPC type completion, haven't tested
}

app.get('/users', async (c) => {
  const users = await db.getUsers();
  return sendSerializedJson(c, { users });
})

export const client = hc<AppType>('localhost:whatever', {
  fetch: async (req: RequestInfo | URL, init?: RequestInit) => {
    const req = await fetch(req, init);
    const raw = await req.json();
    return superjson.deserialize(raw);
  }
})
```

**Comment by cybercoder-naj** [comment]
Understood, thanks for the detailed explanation.

**Comment by mamlzy** [comment]
so @askorupskyy, from what you said, serializing date is a bad idea right? but i'm curious how you handle this, are you okay with date string on client?

**Comment by askorupskyy** [comment]
@mamlzy having `Date` as a string is fine for me & I just delegate that to the client. Like I mentioned above, using complex serializers will most likely solve your issue but will bring many more as your software scales. Probably the most annoying thing I had to do with dates on the client is having to `const dates = records.map(r => new Date(r.created_at));` when drawing a chart or something like that.

Yes, it's annoying, but so much better than having to rewrite the entire project because a new service written in rust for example, does not have support for `superjson`

**Comment by mamlzy** [comment]
> @mamlzy having `Date` as a string is fine for me & I just delegate that to the client. Like I mentioned above, using complex serializers will most likely solve your issue but will bring many more as your software scales. Probably the most annoying thing I had to do with dates on the client is having to `const dates = records.map(r => new Date(r.created_at));` when drawing a chart or something like that. There's also libraries such as `moment.js` to make it even easier.
> 
> Yes, it's annoying, but so much better than having to rewrite the entire project because a new service written in rust, for example, does not have a `superjson` library. JSON is a standard, (de)serialization is not.

Got it! thanks for your insight!

**Comment by Rick-Phoenix** [comment]
How do we avoid type errors in the client then, when using types that contain dates?

**Comment by banool** [comment]
I would expect this to work out of the box too. The server has knowledge of the type of the request field so it should know how to deserialize. To me it seems definitely like a bug if you can define a request type, have it pass type checking, but then the server fails to deserialize it.

**Comment by rayli09** [comment]
same painpoint here, i've been really looking at alternatives since without proper deserialization this is not really an RPC layer.

Been thinking about [orpc which has a hono adapter](https://orpc.unnoq.com/docs/adapters/hono), has anyone had good experience for such migration?

**Comment by danieldeichfuss** [comment]
It makes sense to me to receive the Date as a string. But in that case the the resulting type of `InferResponseType` is not correct. I can see that it returns a type of `Date` while the response for that field is actually a `string`

**Comment by yusukebe** [comment]
@danieldeichfuss I don't have time to dive into it deep, but if you feel it is a bug, can you create another issue? Thanks.

**Comment by danieldeichfuss** [comment]
@yusukebe, thanks for your response! Sorry about that. I tried to replicate the issue in a new Hono project, and it works fine (`Date` is a `string` in `InferResponseType`). I found that it only works if you return `c.json()` right in the route handler. 

In my project, I have a reusable wrapper that returns the response, and the inferred response is surprisingly different; `Date` is inferred as `Date`, even though the response is actually a `string`. Surprising, but not a general problem.

**Comment by adam-kov** [comment]
I had a similar issue to the one described above, and I ended up converting `Date` fields to strings manually. The decision is debatable, but to make the conversion type safe, I created some helper types which might help others, so here they are:

```typescript
type Key = string | number | symbol;

/**
 * 1. `Extract<Type, Search>` extracts the Search type from potential union types (eg: `Search | null`)
 * 2. If the extracted type is `never`, it's a miss, so the original type is returned
 * 3. If the extracted type is `Search`, it's a hit, so it's excluded and `Replace` is added
 */
type Replace<Type, Search, Replace> = Extract<Type, Search> extends never
	? Type
	: Exclude<Type, Search> | Replace;

/** Recursively replace all `Date` types with strings in a record */
type DatesToStrings<T extends Record<Key, unknown>> = {
	[K in keyof T]: T[K] extends Record<Key, unknown> ? DatesToStrings<T[K]> : Replace<T[K], Date, string>;
};
```
