### ISSUE TITLE
GraphQL Server middleware as third-party

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#406]
Create GraphQL Server middleware as third-party middleware.

That was provided in this main repository. But from v2.0.0, we'll make the middleware that depends on other libraries as third-party middleware. It will be hosted on the `gitthub.com/honojs/grahql-server` repository and published as `@honojs/graphql-server`.

**Comment by yusukebe** [comment]
Hi @metrue 

Please see the contribution guide: https://github.com/honojs/hono/blob/main/docs/CONTRIBUTING.md#third-party-middleware

I think it will not be enough, you may have questions, then tell me them.

**Comment by metrue** [comment]
Thanks @yusukebe it's helpful, I am building the [honojs/graphql-server](https://github.com/honojs/graphql-server), will follow the guide and feedback if need.

**Comment by yusukebe** [comment]
Hi @metrue !

Great work! It looks mostly good, but there were some minor issues. I've created PRs to fix them. Please check.
And, I want to know your npm repository account name such as "*[yusukebe](https://www.npmjs.com/~yusukebe)*".

**Comment by metrue** [comment]
Hi, @yusukebe , your PR are merged,  and my npm account is "[metrue](https://www.npmjs.com/~metrue)"

**Comment by metrue** [comment]
I will setup the GitHub action to do the package publish automatically soon.

**Comment by yusukebe** [comment]
@metrue Thanks.

I've invited you to honojs org in npm repository.

**Comment by metrue** [comment]
Somehow the invitation link you send to me is not handled correctly by npmjs.org. let me trying after minutes.
<img width="467" alt="Screen Shot 2022-07-27 at 21 34 29" src="https://user-images.githubusercontent.com/1001246/181260455-63fc7768-9a97-411d-8ad2-e4574120f38d.png">

**Comment by metrue** [comment]
@yusukebe 
It worked, I am in the org now.

**Comment by metrue** [comment]
https://github.com/honojs/graphql-server is live, I think we can close this issue now.

**Comment by yusukebe** [comment]
Yes, close now.
