### ISSUE TITLE
Prepare to building third-party middleware

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#407]
We've released v2.0.x with pleasure. Then, let's go to the next step.

With v2.0.x, it became that we make the third-party middleware more easily. For Deno, separating main `mod.ts` and `middleware.ts` is good. And removed the `graphql-server` and `mustache` middleware. It's time to make third-party middleware.

I'm making the template project [github.com/honojs/middleware-template](https://github.com/honojs/middleware-template) and planning to make `graphql-server` middleware after the template repository is completed.

If you ( @Code-Hex or @metrue or others? )  want to make other third-party middleware, please wait a minute until they are built. And after that, let you make the middleware by yourself or with my help.

**Comment by yusukebe** [comment]
Hi @metrue @Code-Hex !

Can you see this message?

I've written the contribution guide. It includes how to make a third-party middleware:

https://github.com/honojs/hono/blob/main/docs/CONTRIBUTING.md#third-party-middleware

If you want to make the middleware such as "graphql-server" or "firebase-auth", please refer to this article. This may still be not enough, so improve the documents together.

**Comment by Code-Hex** [comment]
@yusukebe Thanks for preparing the guide!

I've read it. I have question about this.

> Tell us your username of the npm repository.

Where should we do it? Maybe case by case?

**Comment by yusukebe** [comment]
Hi @Code-Hex!

Yes "case by case". I think it's better to do it on the issues.

**Comment by Code-Hex** [comment]
@yusukebe Thanks!
Could you invite me to your organization to develop firebase-auth middleware if you feel free?

My npm account is here

https://www.npmjs.com/~codehex

Thank you!

**Comment by yusukebe** [comment]
@Code-Hex 

I've sent the invitation to you!

**Comment by Code-Hex** [comment]
@yusukebe Thank you so much!
I accepted the invitation.

So... my next action is develop the middleware. Can I join also honojs organizations in GitHub?

**Comment by yusukebe** [comment]
Hey  @Code-Hex 

I've made the repository from the template and sent you the invitation to maintain it.
https://github.com/honojs/firebase-auth

Note: Now, we don't add you to the organization, make you a collaborator.

**Comment by Code-Hex** [comment]
@yusukebe Amazing!

Thank you again. I understand current permission. It's suitable to me for now!

Thanks!

**Comment by yusukebe** [comment]
@Code-Hex 

Thank you too, happy coding!

**Comment by yusukebe** [comment]
We did it!
