### ISSUE TITLE
Adding to context via middleware

### ISSUE THREAD

**Issue by RichiCoder1** [honojs/hono#410]
Howdy! I'd like to add support to hono for https://github.com/RichiCoder1/opentelemetry-sdk-workers. As part of that, I'd like to make some context variables available like `log` and `trace`.

It looks like the current shape of hono is fixed so I'd have to make a new type. Is there plans to allow middleware to extend context in the future?

**Comment by yusukebe** [comment]
Hi @RichiCoder1 !

That's very good to make the middleware for "Open Telemetry". We are planning that other developers can make third-party middleware in "honojs org" in such a "github.com/honojs/open-telemetry" and provide named "@honojs/open-telemetry" from npm repository. #407  If you want please do that.

> Is there plans to allow middleware to extend context in the future?

I was just thinking about that one! But, I don't have a good idea to implement it. We'll think about it in another issue (If you want, please join the discussion!).

That feature may be implemented, so wait until then!

**Comment by yusukebe** [comment]
Discussing at #414, close this Issue.
