### ISSUE TITLE
Extending Context

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#414]
There is a request to extend Context. Discussed at #410 and https://github.com/honojs/honojs.dev/pull/1
The possibility of adding `c.afunction()` by the middleware is a good feature, I think.

But I don't have any idea to implement it. One idea is using `declare module`:

```
declare module 'hono' {
   interface Context {
     afunction()
   }
 }
```

It seems to be not smart. Is there someone have other ideas?

**Comment by RichiCoder1** [comment]
A recent pattern in typescript is something called the "builder" pattern, in which you expose methods which return the base type plus some additional type information:

https://stackoverflow.com/questions/69853720/using-builder-pattern-to-create-a-strongly-typed-diverse-record-like-redux-too

A possibility is something like [this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gO2BAHsKBeKBvAvgWACgjRIoBZASwBNqAbCAdwEMAnCAMQFcEBjAHgAq8JKnRYRyNAD5MUABS9gKAFxRhiKcAA0UBGLXyAlJlkAFVnAC2lAM4R+ANzg1pJjOcs37-AEoRbMER7KAAfKGdXAG4ScGgqWgYWdm4+AHVKYAALSTEhXLQ5Ap11YoBBWkzKYLk8WSxsIgBIXk0DUra0Cuoq4JjCJqzmBHoIVjUE0eTOHgENUUKAMg6F4G7ehFtpftx+2LIACUQ4MrAwfM7xWEv6nGbW1bV5rX6mrnt5Sy5kNVtgVkoCAA5robIkmGwIBMaFNIak5sU3GojggTmcLqtts13g5nmJ1sBqptarhpJ84N8oVA-gDgaCYUlIdDwdN4RlssUMVpdHiupVCcEkVAUWjzrz0MtxQSiVsdntCA8-lBmGdkcdTmA5AguHQ6MrbMqECB5SqwAA6HHyADkACorbpGgMHlo1I6mk1kH81Farc1cNpmkMRgxxvqQHwFO5ZHgA4RcEYLR9bfawxHFMpdPo0FG7k7gnAGGa6HAgfJSBA4AAzKBKFBmz3iDBYABENMBQObRiiUAA9D2oP8uBBmswWJk9GJjDsjEQiEA) though that's a very simplified implementation.

**Comment by migueloliveiraz** [comment]
It must be something good thinking. it implies in all design philosophy of project

**Comment by Code-Hex** [comment]
Hi, @yusukebe 👋  I saw this #410 and I came in here.

I want to set any values to the context in the middleware. and use it on main handler.

In my middleware (firebase-auth) is example here.

```ts
  async (c: Context, next: Next) => {
    const authorization = c.req.headers.get(config.AuthorizationHeaderKey);
    if (authorization === null) {
      return new Response(null, {
        status: 400,
      });
    }
    const jwt = authorization.replace(/Bearer\s+/i, "");
    const auth = Auth.getOrInitialize(
      c.env.PROJECT_ID,
      config.KeyStore ??
        WorkersKVStoreSingle.getOrInitialize(
          c.env.PUBLIC_JWK_CACHE_KEY,
          c.env.PUBLIC_JWK_CACHE_KV
        )
    );

    try {
       // I want to set "firebaseToken" value to the context. (but I can't do it now?)
      const firebaseToken = await auth.verifyIdToken(jwt, c.env);
      await next();
    } catch (err) {
      console.error({
        message: "failed to verify the requested firebase token",
        err,
      });
      return new Response(null, {
        status: 401,
      });
    }
  }
```

[Go has this way](https://pkg.go.dev/context#example-WithValue).

**Comment by yusukebe** [comment]
Hi @Code-Hex !

In fact, there is such the feature that is not documented:
https://github.com/honojs/hono/pull/226

```ts
const v = c.get('key')
c.set('key', 'value')
```

How about using these methods? If they are used often, I would like to document them.

**However**

The `value` will be `any`. I want to add the types. Can we do that by using Generics?

And, also we want to implement adding "*function*" to Context, such as `c.afunction()`.

Do you have a good idea? cc: @usualoma @metrue

**Comment by Code-Hex** [comment]
@yusukebe Nice API!! It's enough for me.

Personally, I can't agree with extending context after adding some functions because if we use some middleware and their middleware extends the context, it has the potential to cause unexpected behavior by overriding same name methods.

I think it would be easier for users to understand if the context was as simple as possible to implement.

I wonder though maybe get method should return any or unknown and the user should use typeguard if want a specific type.

**Comment by yusukebe** [comment]
@Code-Hex 
Thank you for telling me your thought.

Exactly, extending the context will make that user confused. It should be easy to understand and should be a simple implementation.

Hmm. We may not have to implement "*extending context*"...

We can make the most of "get/set" method instead.

**Comment by RichiCoder1** [comment]
> And, also we want to implement adding "function" to Context, such as c.afunction().

I would like this ability, but mostly because I would like to add something like a `ctx.auth()` or `ctx.trace()`.

That said, I'm fine creating a helper like `getAuth(ctx)` or `getTrace(ctx)` that uses `get/set` under the covers.

**Comment by RichiCoder1** [comment]
> Could you share more about the ctx.auth() and ctx.trace() ? what are they for and how are you going to design it? are you going to make some special keys ___auth___ to read and write the authorization information inside ctx.auth() and getAuth(ctx) ? if so, I think it's something the user should do in their codes, instead of hono.

There would a `jwt` middleware for example that would expose the `jwt`'s claims via `.auth()` for example. Or for tracing, an Open T racing Middleware which would expose the current active trace information via something like a `trace().spanId` and expose a helper for tracing downstream requests via `trace.fetch(....)`.

**Comment by yusukebe** [comment]
Hi @metrue !

> Could you provide some use cases for this

For example, I'm planning to make the "*Validator Middleware*" https://github.com/honojs/hono/issues/425.  In this middleware, the user must get the results in a handler. So, I thought that `ctx.getResult()` is a helpful method to do it:

```ts
app.use('/', validator(...))

app.get('/', (c) => {
  const result = c.getResult()
  return c.json(result)
})
```

**BUT**, I notice we don't have to extend the Context. We can write it without `validatorResult()` method:

```ts
app.use('/', validator(...))

app.get('/', (c) => {
  const res = validatorResult(c)
  return c.json(res)
})
```

Let's see implementation. In the "*validator*" method, set the result using `ctx.set()` method:

```ts
ctx.set('validatorResult', result)
```

And, the `validatorResult()` method will get the result using `ctx.get()` method:

```ts
const validatorResult = (ctx: Context): Result => {
  return ctx.get('validatorResult')
}
```

I think this way is better than extending Context. For instance, @Code-Hex 's "*Firebase Auth Middleware*" is using this method:

https://github.com/honojs/firebase-auth/blob/main/src/index.ts#L77-L84

**Comment by usualoma** [comment]
Hi @yusukebe

I also think it is not a good practice for middleware to add methods to Context object.
I agree with the use of helper functions, as in "Firebase Auth Middleware."

However, I think that in some cases it is not a bad idea for middleware to extend type definitions.

For example, making changes like the following PR...
https://github.com/honojs/hono/pull/429

Middleware will be able to add types as follows...

```typescript
declare module 'hono' {
  interface ContextVariableMap {
    calculationResults: number
  }
}
```

This allows users to benefit from type definitions.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/30598/181645255-3466bb2d-b79e-490a-921e-a08a9f6c93f7.png">

It can also detect before execution if the same key is already in use by other middleware.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/30598/181646362-40101ec4-636f-4724-93ca-df923b8dd649.png">

I think helper functions are the best practice for this issue, so #429 will be an adjunct, but I think it will help solve some of the problems.

**Comment by yusukebe** [comment]
@usualoma Ultra Great!

I've tried it for "*Validator Middleware*" which is WIP, it worked, and I've felt fine DX.

<img width="525" alt="スクリーンショット 2022-07-29 8 34 38" src="https://user-images.githubusercontent.com/10682/181654405-842bdc62-c194-4a15-ae7a-2d7651467602.png">

It seems that writing `declare module...` is trouble, but this is just for the developer of the middleware. @Code-Hex will be able to use this feature for "*Firebase Auth Middleware*" soon.

Let's get this feature in!

And, we need to consider...
The middleware can provide two syntaxes for getting "results", "variables pattern" and "function pattern".

```ts
const result = c.get('validatorResults') // function pattern
const result = validatorResult(c) // method pattern
```

We/Middleware developers can provide both patterns, but should we choose one? or both?

**Comment by usualoma** [comment]
> We/Middleware developers can provide both patterns, but should we choose one? or both?

I think that is what bothers me too.

While being able to declare type to values of set/get is an interesting feature, I believe the following is often the good pattern for users (who are not middleware developers).

```typescript
const result = validatorResult(c)
```

**Comment by yusukebe** [comment]
Hi @usualoma !

> I believe the following is often the good pattern for users 

Agree. I think it would be easier for users to understand if there is an explicit method.
So, the author of the middleware should provide a method like "*validatoResult*" if wants to get some values from Context.

Though we have this guideline, feature #429  is good for us. I'll merge it.

**Comment by matthewrobb** [comment]
@yusukebe Thinking about this stuff I had a thought. What if there was a way to provide the initializer for a context key:

```ts
app.var("validatorResults", (c) => {
  return ...
})
```
With some internal handling of get calls:
```ts
class Context {
  ...
  var(key: string) {
    let value = this.get(key)
    if (!value && this._initializers[key]) {
      this.set(key, value = this._initializers[key](this))
    }
    return value
  }
}
```

**Comment by KeKs0r** [comment]
Not yet big experience with Hono, but from my superficial usage I have 2 thoughts:
**Extending Context is not too crazy**
Mainly because, I am using cloudflare and I manually overwrite the environemnt anyway, to access those globals / services. Doing something like this is maybe not perfect, but seems fine. Considering that for "some" global services (e.g. KV) I am doing this anyway.

**Alternative: Infer additional types from middleware**
This is just a general thought, not sure about the details, but think would be possible. That "using" the middleware extends the request. 
This would look something like this (very pseudo code)
```typescript

type ContextExtend = {
  foo: string
}
const myMiddleware: Middleware<ContextExtend> = ...
app.get('/my-endpoint-with-middleware', myMiddleware, c => {
  // context was extend by middleware, via generic inference on the myMiddleware argument
  c.context.foo
})
```
 
And in the case when the middleware is defined on the app level, we could try to use a fluent interface or inject middlewares during construction, to give the extend context in the resulting type
```typescript

const app = createHono(...middlewares)
// alternative
const app = createHono()
  .use(middleware)
  .use(middelware2)

```

I hope I could communicate the base ideas. This is just high level idea and they probably require some typescript trickery, but theoretically possible.

**Comment by eikooc** [comment]
I just spend a short while on doing a demo of how something like this could be achieved. I do not think it you should be scared of letting the middleware changing the `Context` type, since adding something to the context is a common thing to do in the middleware.

```ts
type Context<Type> = {
  [Property in keyof Type]: Type[Property]
}

type App<T> = {
  use: <U>(a: (ctx: Context<T>) => Context<T> & Context<U>) => App<U> & App<T>
  get: (path: string, callback: (ctx: Context<T>) => void) => void
}

const app: App<unknown> = {} as any

const x = (ctx: Context<any>) => {
  ctx.hello = 'world'
  const newContext: typeof ctx & Context<{ hello: 'world' }> = ctx
  return newContext
}

app.use(x).get('', (ctx) => {
  ctx.hello // Exists
  return ctx
})

app.get('', (ctx) => {
  ctx.hello // Doesn't exist
  return ctx
})
```

As you can see from the example, when using `get` on a app that has uses the middleware, the variable `hello` is now exposed. This demo is solely to show what's possible and a brain storm idea of how to do it.

**Comment by eliezedeck** [comment]
Hi, I'm interested in this too. I'm using Prisma with Hono for Cloudflare Workers target. It would be cool to have a property `c.prisma` that is `PrismaClient` and is also typed properly for good DevX. Or, is there already a method to do that, without having to do `c.set()` and `c.get()`?

**Comment by yusukebe** [comment]
@eliezedeck 

While it's true that writing `c.prisma` is shorter, I avoid extending `Context` directly. Hence, I recommend using `c.set()` and `c.get()` or `ContextVariableMap`:

```ts
declare module 'hono' {
  interface ContextVariableMap {
    prisma: PrismaClient
  }
}

const prismaMiddleware: MiddlewareHandler = async (c, next) => {
  // ...
  c.set('prisma', prismaClinet)
  await next()
}

app.get('/list', prismaMiddleware, (c) => {
  const prisma = c.get('prisma')
  // ....
})
```

**Comment by eliezedeck** [comment]
Thanks @yusukebe.

Is there a specific reason why extending the `Context` is not recommended?

I'm using Cloudflare Workers and facing issues with the Prisma client library. Instantiating the client outside of a request is not possible due to limitations with Cloudflare Workers or the library itself. The values required for client instantiation are only accessible through `c.env.PRISMA_URL`. Considering this, I thought about extending the `Context` to avoid the verbosity of additional functions like `getPrismaClient(c: Context)`.

**Comment by eliezedeck** [comment]
Thank you @yusukebe

**Comment by ewrogers** [comment]
> @eliezedeck
> 
> While it's true that writing `c.prisma` is shorter, I avoid extending `Context` directly. Hence, I recommend using `c.set()` and `c.get()` or `ContextVariableMap`:
> 
> ```ts
> declare module 'hono' {
>   interface ContextVariableMap {
>     prisma: PrismaClient
>   }
> }
> 
> const prismaMiddleware: MiddlewareHandler = async (c, next) => {
>   // ...
>   c.set('prisma', prismaClinet)
>   await next()
> }
> 
> app.get('/list', prismaMiddleware, (c) => {
>   const prisma = c.get('prisma')
>   // ....
> })
> ```

I have been trying to write a similar dependency injection middleware, and while it does work... I still get type errors/warnings in my IDE (latest WebStorm 2023.2.1).

I have tried various methods, including the one described on the [docs](https://hono.dev/api/context#set-get) but still get type errors on `c.get()` access.

```typescript
type Variables = {
  container: Record<string, any>
}

const app = new Hono<{Variables: Variables}>()

const containerMiddleware = async (c, next) => {
  const container: Record<string, any> = {
    // ... register various services here
  }
  c.set('container', container)
  await next()
}

app.use('*', containerMiddleware)

app.get('/test', containerMiddleware, (c) => {
  const container = c.get('container')
                        // ^-- "Argument types do not match parameters"
  
  return c.text(`${container.message}: ${container.name}`)
})
```

Considering the code works fine, I am okay ignoring it but it seems like I am not getting any type-safety since it still thinks `container` is `any` unless I explicitly state the type... which kind of defeats the purpose.

**Comment by vassbence** [comment]
> @eliezedeck
> 
> While it's true that writing `c.prisma` is shorter, I avoid extending `Context` directly. Hence, I recommend using `c.set()` and `c.get()` or `ContextVariableMap`:
> 
> ```ts
> declare module 'hono' {
>   interface ContextVariableMap {
>     prisma: PrismaClient
>   }
> }
> 
> const prismaMiddleware: MiddlewareHandler = async (c, next) => {
>   // ...
>   c.set('prisma', prismaClinet)
>   await next()
> }
> 
> app.get('/list', prismaMiddleware, (c) => {
>   const prisma = c.get('prisma')
>   // ....
> })
> ```

Is there a way to only declare the attribute on ContextVariableMap if the given middleware is used on the path? So only allow c.get("foo") when FooMiddleware is actually used in the chain before the request.

**Comment by yusukebe** [comment]
Hi @vassbence , 

You can do it with this code:

```ts
import { createMiddleware } from 'hono/factory'

const echoMiddleware = createMiddleware<{
  Variables: {
    echo: (str: string) => string
  }
}>(async (c, next) => {
  c.set('echo', (str) => str)
  await next()
})

app.get('/echo', echoMiddleware, (c) => {
  return c.text(c.var.echo('Hello!'))
})
```

**Comment by vassbence** [comment]
> Hi @vassbence ,
> 
> You can do it with this code:
> 
> ```ts
> import { createMiddleware } from 'hono/factory'
> 
> const echoMiddleware = createMiddleware<{
>   Variables: {
>     echo: (str: string) => string
>   }
> }>(async (c, next) => {
>   c.set('echo', (str) => str)
>   await next()
> })
> 
> app.get('/echo', echoMiddleware, (c) => {
>   return c.text(c.var.echo('Hello!'))
> })
> ```

Lovely, thanks!

**Comment by vsviridov** [comment]
The variable types do not seem to get propagated if the middleware is wired up via `.use` call.
```ts
const someMiddleware = createMiddleware<{ Variables: { foo: string } }>(...);

const app = new Hono()
  .use(someMiddleware())
  .get('/', c => {
    c.var.foo // <- fails here
  })
  .get('/other', someMiddleware(), c => {
    c.var.foo // <- works here
  })
```

I feel like `.use` should compose the Environment type to the existing environment.

**Comment by yusukebe** [comment]
@vsviridov 

That is a thing which is not implemented or a just bug. But we may be enable to fix it.

**Comment by jazoom** [comment]
Is there a reason not to do it similar to Express with `.locals`?

https://expressjs.com/en/5x/api.html#res.locals

Could you make the `locals` property of type `object` and allow any fields to be added and still satisfy its type?

I feel like this is easier to reason about and easier to debug. If I want to know what's been added by mine or any other middleware I just log `c.locals`.

**Comment by vsviridov** [comment]
> Is there a reason not to do it similar to Express with `.locals`?
Express is not a typescript native. Those types were added after.

> Could you make the `locals` property of type `object` and allow any fields to be added and still satisfy its type?
> 
> I feel like this is easier to reason about and easier to debug. If I want to know what's been added by mine or any other middleware I just log `c.locals`.

In typescript we like to be precise.

**Comment by jazoom** [comment]
@vsviridov I'm not a Typescript expert, so please forgive my ignorance, but I don't see how the black box of `set` and `get` is better?

**Comment by alvinsw** [comment]
Is there a way to get this working with JSDoc-annotated JavaScript project in VSCode? I tried adding the module thing in a .d.ts file, but ti does not work.

**Comment by RealOFF** [comment]
Don't you think this system looks unsafe especially on large applications? If the application gets large enough and you have multiple services in the context that depend on each other, there could be problems. Especially after refactorings when you need to swap some middlewares. The fastify plugin/decoration system also has typing problems in this respect, but you can explicitly describe that for example to initialize a context in this plugin you need a plugin with a certain name. Perhaps hono should also add something like that?

**Comment by iveshenry18** [comment]
> ```ts
> import { createMiddleware } from 'hono/factory'
> 
> const echoMiddleware = createMiddleware<{
>   Variables: {
>     echo: (str: string) => string
>   }
> }>(async (c, next) => {
>   c.set('echo', (str) => str)
>   await next()
> })
> 
> app.get('/echo', echoMiddleware, (c) => {
>   return c.text(c.var.echo('Hello!'))
> })
> ```

Thanks a ton for this—just spent an hour trying to track this down. Made PR #460 to add it to the docs.

**Comment by romoguill** [comment]
> Hi @vassbence ,
> 
> You can do it with this code:
> 
> ```ts
> import { createMiddleware } from 'hono/factory'
> 
> const echoMiddleware = createMiddleware<{
>   Variables: {
>     echo: (str: string) => string
>   }
> }>(async (c, next) => {
>   c.set('echo', (str) => str)
>   await next()
> })
> 
> app.get('/echo', echoMiddleware, (c) => {
>   return c.text(c.var.echo('Hello!'))
> })
> ```

I think this is the best solution for now. The only issue I see is that the Context has the echo var before it's set, so forgeting the to add c.set('echo', (str) => str) and calling c.get('echo') in a handler would be ok for TS but will break at runtime.

**Comment by bombillazo** [comment]
Hey, we wanted to add a global logger via context and we could definitely use set/get, but its a bit more verbose than simply doing `c.log()`

**Comment by treeder** [comment]
With a few extra characters you can do `c.var.log()`

**Comment by StephenHaney** [comment]
I noticed that when using `app.fetch` anything you pass for the `Env` is assumed to be a `Binding`. It doesn't seem possible to pass `Variables`, which would be quite useful if you're validating a session before the Hono app (as I can in Bun.serve)

Example:
```
const user = someSessionValidation();
return app.fetch(req, { user });
// user is now available as `c.env.user` but I believe a Variable would be a better choice? 
```

**Comment by yusukebe** [comment]
@StephenHaney 

Using both `Bindings` and `Variables` is okay. But I recommend `Variables` in that case. The `Bindings` are used to access an external resource. For example, it's used not only for Cloudflare Workers but also for Node.js adapter servers. You can access the Node.js API with `c.env.incoming` or `c.env.outgoing`. This information is not related to the application but to external resources.

https://github.com/honojs/node-server?tab=readme-ov-file#accessing-nodejs-apiv

**Comment by yusukebe** [comment]
We can close this issue because we now have the `c.var` feature. Thanks!

**Comment by StephenHaney** [comment]
Yes, it makes sense to use `Variables` to add the `User`.

I was pointing out that you can't add `Variables` from `app.fetch`, you can only add Bindings

`return app.fetch(req, { user });` adds `user` as a Binding.

**Comment by ben-xD** [comment]
It's really nice we can already enhance context with middlewares:
```typescript
import { createMiddleware } from 'hono/factory'
import { Hono } from "hono";
import type { User } from "@supabase/supabase-js";

const echoMiddleware = createMiddleware<AppContext & {
  Variables: {
    echo: (str: string) => string
  }
}>(async (c, next) => {
  c.set('echo', (str) => str)
  await next()
})

const addUserMiddleware = createMiddleware<AppContext & {
  Variables: {
    user: User
  }
}>(async (c, next) => {
  c.set('user', {} as unknown as User)
  await next()
})

const app = new Hono<AppContext>()
app.get('/echo', echoMiddleware, addUserMiddleware, (c) => {
  // echoMiddleware enhances the context with "echo" function and "user" object
  return c.text(c.var.echo('Hello!'))
})
```

However, that doesn't work with `@hono/zod-openapi`. However I got it working with **hono-openapi** instead
