### ISSUE TITLE
Named Parameters applying to routes differently with TrieRouter than RegExpRouter

### ISSUE THREAD

**Issue by erhlee-bird** [honojs/hono#418]
Hey, thank you for the work on the library.

I was following some of the instructions in the docs and changed one of the examples and noticed some unexpected behavior.

```
// Snippet changed slightly from the docs here.
// https://honojs.dev/docs/api/routing/#routing-priority

app.get("/book/a", (c) =>
  c.text(c.req.param("slug") || "no-slug"))
)
app.get("/book/:slug", (c) =>
  c.text(c.req.param("slug") || "no-slug-at-slug-endpoint")
)
```

Hitting the endpoints, I get the following results.

```
$ curl http://localhost:8787/book/a
a
$ curl http://localhost:8787/book/foo
foo
```

The TrieRouter unexpectedly seems to be applying the Named Parameter parsing rule from the second route to the first.

If I use the `RegExpRouter` instead, I get the results I expect.

```
$ curl http://localhost:8787/book/a
no-slug
$ curl http://localhost:8787/book/foo
foo
```

**Comment by yusukebe** [comment]
Hi @erhlee-bird !

It's a bug! I've fixed it at #419 . I will release the next version later including this fix.
Thank you for your report.
