### ISSUE TITLE
Sentry Middleware

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#423]
We can make "Sentry Middleware" using "Toucan". It will be as a third-party middleware.

<https://github.com/robertcepa/toucan-js>

If we decide to make it, the repository and package name will be:

```
github.com/honojs/sentry
@honojs/sentry
```

Below is the description of how to make third-party middleware:

<https://github.com/honojs/hono/blob/main/docs/CONTRIBUTING.md#third-party-middleware>

**Comment by Zerebokep** [comment]
That would be awesome.

**Comment by nathanclevenger** [comment]
@yusukebe this is something that @sam-lippert and I would like to work on.  It should be fairly straightforward.

**Comment by yusukebe** [comment]
Oh, that's a pleasure! Please wait a minute, I'll set up the template project.

**Comment by yusukebe** [comment]
Hi @nathanclevenger @sam-lippert

I made the repository for Sentry Middleware and sent the invitation to you.

https://github.com/yusukebe/sentry

You can develop the middleware right now! If you have any questions, let me know.

**Comment by yusukebe** [comment]
Hi @nathanclevenger @sam-lippert

I made a mistake! That repository I wrote the comment above is wrong! I made the correct repository and sent the invitation to you.

https://github.com/honojs/sentry

I set your access role as "write". Later, if you want to have a "maintain" role, please tell me. Let's go!

**Comment by Daniel-Ash** [comment]
If anyone is searching, this package can now be found at: https://github.com/honojs/middleware/tree/main/packages/sentry

**Comment by NeoPrint3D** [comment]
So I am writing my hono api using cloudflare what would be the best way to pass the env variable as the dsn?

**Comment by yusukebe** [comment]
Hi @NeoPrint3D ,

You can write like the following:

```ts
app.use('*', async (c, next) => {
  const sentryMiddleware = sentry({ dsn: c.env.SENTRY_DSN })
  return await sentryMiddleware(c, next)
})
```

**Comment by NeoPrint3D** [comment]
Thanks so much!! And dang was that fast support, kudos to you
