### ISSUE TITLE
Validator Middleware

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#425]
I have an idea, "*Validator Middleware*".

I plan that I'll make it with [validator.js](https://github.com/validatorjs/validator.js), which is used in [express-validator](https://express-validator.github.io/docs/). So, it will depend on the external library, which will be a "third-party" middleware.

The express middleware is helpful, but it's a bit fat, and it seems not too easy to implement. And "just do porting" is not like Hono. I want to make the "*Validator Middleware*" simpler than the express middleware. Below is the synopsis that on my head now:

```ts
const app = new Hono()

app.use(
  '/',
  validator((v) => [
    {
      rule: v.isAlpha,
      field: 'query',
      name: 'q',
    },
  ])
)

app.get('/', (c) => {
  const res = validatorResult(c)
  return c.json(res)
})

export default app
```

I'll try to build it on `github.com/honojs/validator` repository. So if it's ready, please take a look!

**Comment by usualoma** [comment]
It is very good for the framework to have a nice validation library.
However, I think that functions should be context object independent if at all possible.

I may not be able to achieve the same thing as your code, but I think it would be better if it were as follows.

```typescript
import { buildValidator } from "middleware/validator"

const validatorSearch = buildValidator((v) => [
  {
    rule: v.isAlpha,
    name: 'q',
  },
])

app.get('/', (c) => {
  const res = validatorSearch(c.query())
  return c.json(res)
})

export default app
```

**Comment by metrue** [comment]
> It is very good for the framework to have a nice validation library.
However, I think that functions should be context object independent if at all possible.

Second on this, and what's in my mind is like this,

```js

const schema  = {
  type: 'object',
  required: ['requiredKey'],
  properties: {
    someKey: { type: 'string' },
    someOtherKey: { type: 'number' },
    requiredKey: {
      type: 'array',
      maxItems: 3,
      items: { type: 'integer' }
    },
    nullableKey: { type: ['number', 'null'] }, // or { type: 'number', nullable: true }
    multipleTypesKey: { type: ['boolean', 'number'] },
    multipleRestrictedTypesKey: {
      oneOf: [
        { type: 'string', maxLength: 5 },
        { type: 'number', minimum: 10 }
      ]
    },
    enumKey: {
      type: 'string',
      enum: ['John', 'Foo']
    },
    notTypeKey: {
      not: { type: 'array' }
    }
  }
}

app.get('/',  validate({ schema }), handler)
```

**Comment by usualoma** [comment]
Oh, sorry, I finally understood what it means to register as middleware using `app.use` when I saw this.

```
app.get('/',  validate({ schema }), handler)
```

I'll reconsider for a moment.

**Comment by usualoma** [comment]
I would like the following API.

```typescript
import validator from 'middleware/validator'

const validatorSearch = validator((v) => [
  {
    rule: v.isAlpha,
    field: 'query',
    name: 'q',
  },
])

app.get('/', validatorSearch, (c) => {
  const q = c.req.query('q') // get value if q is alphabetic only, otherwise throws error
  const unknownParam = c.req.query('unknownParam') // throws error
  const qFromCookie = c.req.cookie('q') // throws error

  // fetch result...

  return c.json(result)
})

app.onError((err, c) => {
  // handle validation error
})

export default app
```

Since validation failures are literally **exceptional**, it would be nice to be able to handle them in app.onError, etc., without writing explicit error handling in the normal handler.

Supporting JSON Schema might be good, but I think there are some things that are difficult to describe using only regular expressions, such as validation of email addresses. Ah, but if we decide that "the only validations that can be specified are those that can be expressed in JSON Schema," then we might be able to make it middleware without external dependencies.

**Comment by yusukebe** [comment]
Hi! @usualoma @metrue 

This is in my head!:

<https://gist.github.com/yusukebe/b9b48e910f45ac7cb88f72b998bfc8b8>

To make the error message such "*query : q is invalied*", `Validation` object must have `field` and `name` parameters.

> @metrue:
> Second on this, and what's in my mind is like this,

That code @metrue wrote is based on "JSON Schema".  It's the same validator, but I think these are different things. How about make both validators, "traditional style" and "JSON Schema style"?

First I want to make the "traditional style" on 'github.com/honojs/validator' and '@honojs/validator' namespace. And, it's OK to make `github.com/honojs/json-schema` and `@honojs/json-schema`. Addition, to implement JSON Schema, we can use this library:
https://www.npmjs.com/package/@cfworker/json-schema

> @usualoma:
> Since validation failures are literally exceptional, it would be nice to be able to handle them in app.onError, etc., without writing explicit error handling in the normal handler.

It's a good idea that users don't have to handle results, but
So, I like to handle the "Result" object in the handler. although it's verbose...

I think it's difficult handling the validation error and separate processing for each errors. We dare not implement custom Error objects, using only `Error` object.

So, I like to handle the "Result" object in the handler. although it's verbose...

**Comment by yusukebe** [comment]
Hi! @usualoma @metrue 

This is in my head!:

<https://gist.github.com/yusukebe/b9b48e910f45ac7cb88f72b998bfc8b8>

To make the error message such "*query : q is invalid*", `Validation` object must have `field` and `name` parameters.

> @metrue:
> Second on this, and what's in my mind is like this,

That code @metrue wrote is based on "JSON Schema". It's the same validator, but I think these are different things. How about making both validators, "traditional style" and "JSON Schema style"?

First, I want to make the "traditional style" on `github.com/honojs/validator` and `@honojs/validator` namespace. And, it's OK to make `github.com/honojs/json-schema` and `@honojs/json-schema`. In addition, to implement JSON Schema, we can use this library:
https://www.npmjs.com/package/@cfworker/json-schema

> @usualoma:
> Since validation failures are literally exceptional, it would be nice to be able to handle them in app.onError, etc., without writing explicit error handling in the normal handler.

It's a good idea that users don't have to handle them in handlers. The code in the handler tends to be complicated.
If we handle validation error on `app.onError`,  how we separate processing. We have not dared make custom Error objects.

**Comment by metrue** [comment]
>@usualoma:
Since validation failures are literally exceptional, it would be nice to be able to handle them in app.onError, etc., without writing explicit error handling in the normal handler.

>> @yusukebe:
It's a good idea that users don't have to handle them in handlers. The code in the handler tends to be complicated.
If we handle validation error on app.onError, how we separate processing. We have not dared make custom Error objects.

I think the validation exception handling should be inside the validation middleware itself. or we just simply put them into `ctx.validationResult`, then in the handler we can check it just like @yusukebe did in the gist.
```js
const res = c.get('validatorResult') 
if (res.hasError) {
  ...
}
```

> That code @metrue wrote is based on "JSON Schema". It's the same validator, but I think these are different things. How about making both validators, "traditional style" and "JSON Schema style"?
>First, I want to make the "traditional style" on github.com/honojs/validator and @honojs/validator namespace. And, it's OK to make github.com/honojs/json-schema and @honojs/json-schema. In addition, to implement JSON Schema, we can use this library: https://www.npmjs.com/package/@cfworker/json-schema

Agree, we can have both of them. and the current interface of validation middleware @yusukebe designed is just simple and enough. 
```js
type Field = 'query' | 'param' | 'header' | 'body'

type Validation = {
  rule: Function
  field: Field
  name: string
  message?: string
  isError?: boolean
}

type Result = {
  hasError: boolean
  validations: Validation[]
}

const validationMiddleware = (option: (validator: Validator) => Validation[]): Handler {}
```
One minor thought, is `Validation.rule` need to be an array, like `Validation.rules` to support the multiple rule on one field?

**Comment by yusukebe** [comment]
@metrue 

> One minor thought, is Validation.rule need to be an array, like Validation.rules to support the multiple rule on one field?

Ah, yes! It's good to be array to support the multiple rules.

**Comment by usualoma** [comment]
@metrue Thank you for your comment!

> I think the validation exception handling should be inside the validation middleware itself. or we just simply put them into ctx.validationResult, then in the handler we can check it just like @yusukebe did in the gist.

I don't have a particular insistence that "onError should be handled as an exception".  but I didn't want to write the following code over and over again anyway. 

```typescript
  const res = validatorResult(c)
  // It's verbose...
  if (res.hasError) {
    res.validations.map((v) => {
      if (v.isError && v.field === 'query') {
        return c.notFound()
      }
    })
  } else {
    // ...
  }
```

Also, after thinking about it for a moment, I can achieve what I want to accomplish with the current implementation of @yusukebe , since we can summarize the error handling as follows

```typescript
const app = new Hono()
app.use(
  '*',
  validationMiddleware((v) => [
    {
      rule: v.isAlpha,
      field: 'query',
      name: 'q',
    },
  ]),
  function handleValidationError(c, next) {
      const res = validatorResult(c)
      if (hasError) {
        return c.json({message: 'Invalid request'}, 400)
      }
      else {
        next()
      }
  }
)

app.get('/', (c) => {
  return c.json(res)
})
```

**Comment by metrue** [comment]
> @usualoma 
> but I didn't want to write the following code over and over again anyway.

Totally agree on this, to make life easier, maybe we make it like this,

```js
const app = new Hono()

type ValidationErrorHandler = (ctx, next) => Promise<void>
type Validation = {
  rule: Function
  field: Field
  name: string
  onError: ValidationErrorHandler,
}

app.use(
  '*',
  validationMiddleware((v) => [
    {
      rule: v.isAlpha,
      field: 'query',
      name: 'q',
      onError: (ctx, next) => {
          return c.json({message: 'Invalid request'}, 400)
       }
    },
  ]),
)
  

app.get('/', (c) => {
  return c.json(res)
})
```
But if we still need the validation results, we have to save them into the ctx in the validation middleware.

**Comment by yusukebe** [comment]
> Also, after thinking about it for a moment, I can achieve what I want to accomplish with the current implementation of @yusukebe , since we can summarize the error handling as follows

Oh, that's cool! Why didn't I notice it? This is taking advantage of Hono's middleware structures.

**Comment by yusukebe** [comment]
@metrue @usualoma 

Thank you both! Referring to this discussion, I'll make the prototype of "Validator Middleware" this weekend (or after).

**Comment by digitalmio** [comment]
I actually thought that this ticket will be about JSON-Schema type validator. If some of you will be working on the non-JSON-Schema one, I can try and tinker a bit for the other one...

**Comment by nathanclevenger** [comment]
@digitalmio I'm also interested in a validation middleware for JSON Schema and/or JSON Type Definition, and since AJV supports both of those I was thinking about creating a middleware for that.  What library were you thinking of using?

**Comment by digitalmio** [comment]
Hey, AJV might be a good option, I would also check what library Fastify is using. I'm going on holiday soon, will be able to take a look into this in about week and a bit.

**Comment by yusukebe** [comment]
Hi!

I think the first thing we have to do is look into whether the AJV works on Cloudflare Workers fine.

**Comment by yusukebe** [comment]
Hi there! especially @metrue and @usualoma .

I'm creating "Validator Middleware" and  almost done:

<https://github.com/honojs/validator/tree/develop>

This is what I consider to be the Ideal API. I would like to go with this, but if you must have an opinion, please let me know.
