### ISSUE TITLE
await c.req.parseBody, 500 internal server error

### ISSUE THREAD

**Issue by Zerebokep** [honojs/hono#428]
Calling

`const body = await c.req.parseBody()`

results in a 500 internal server error if no body is submit. c.req.bodyUsed can be used to bypass this, but imo this should be checked inside parseBody()

**Comment by yusukebe** [comment]
Hi @Zerebokep 

I can't reproduce your issue. Could you tell me how about the `Request` did you send to your application?
Is it `form-data` or `x-www-form-urlencoded`? What is the content inside the body?

**Comment by Zerebokep** [comment]
Hi,

content type of the request header is application/json.

middleware:

`app.use('*', async (c, next) => {
  const body = await c.req.parseBody()

  await next()
})`

content is json, but the error below is thrown at any request


error log:

`SyntaxError: Unexpected end of JSON input
GET /any/route 500 Internal Server Error (1.78ms)`

using 
"wrangler": "2.0.23"
"hono": "2.0.5"

**Comment by yusukebe** [comment]
@Zerebokep 

Thank you!

I understood. I've fixed it on #433 , make it return the blank object `{}` if the body is nothing.
