### ISSUE TITLE
GitHub Sponsorship

### ISSUE THREAD

**Issue by nathanclevenger** [honojs/hono#431]
[Drivly](https://github.com/drivly) would like to sponsor Hono.  @yusukebe would you be open to that?

We offer simple unified APIs to buy and sell cars online, and we're funded by some of the [biggest names](https://twitter.com/TurnerNovak) in [automotive](https://fontinalis.com/team/#bill-ford) and [finance & insurance](https://www.detroit.vc)

Our entire infrastructure is also built on Cloudflare Workers, and we're using Hono extensively.

**Comment by yusukebe** [comment]
Hi @nathanclevenger !

Please give me a moment to summarize what I want to say!

**Comment by yusukebe** [comment]
Thank you @nathanclevenger !

Honestly, I thought that I/we didn't need sponsors. I don't like to be political. I've heard that some people are forcing developers to add features because "we are sponsoring you":( Although that, of course, I think you are not :)

**BUT**, I also believe that we can guarantee the quality of our software when I/we have sponsors.

Thus, I'm struggling with this, so please wait until I get an answer.

I/we are very happy with your offer.

**Comment by nathanclevenger** [comment]
We would sponsor $100/mo, no strings attached

**Comment by yusukebe** [comment]
Hi @nathanclevenger !

I want to know how do you think about sponsoring individuals, such as sponsoring me not Hono.

If we start a sponsor program for the Hono organization, there is a difficult problem. That is how I/we distribute the money or something for the organization members. If sponsoring for individual, I/we do not have to think about it.

**Comment by nathanclevenger** [comment]
For sure, @yusukebe, for the other projects we are sponsoring, I believe it's all going directly to the individual primary maintainer.

I think all you have to do is set up your personal account for GitHub Sponsors, then you can create the `funding.yaml` file in the hono repo as documented [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository):
```
github: yusukebe
```

**Comment by yusukebe** [comment]
Hi @nathanclevenger !

I've just started the individual GitHub Sponser program!
Here: https://github.com/sponsors/yusukebe

If you will sponsor me, it's glad!

**Comment by nathanclevenger** [comment]
Thanks @yusukebe - @drivly just sponsored you!  We really appreciate all the amazing work you’re doing for this community!!!

**Comment by yusukebe** [comment]
@nathanclevenger Thanks a lot!
