### ISSUE TITLE
parseBody not working in Middleware?

### ISSUE THREAD

**Issue by Zerebokep** [honojs/hono#432]
`await c.req.parseBody()` seems not to be defined if used inside `app.use('*', async (c, next) => {`

**Comment by yusukebe** [comment]
Hi @Zerebokep !
It will work well in middleware. Give me the code or snippets to reproduce this issue.

**Comment by Zerebokep** [comment]
Similar to the other bug report.

`app.use('*', async (c, next) => {
  const body = await c.req.parseBody()

  await next()
})`

body always seems to be undefined in a middleware, it works perfectly fine in routes.

**Comment by yusukebe** [comment]
Hmm. It works well my enviroment.

Code:

```ts
import { Hono } from 'hono'

const app = new Hono()

app.use('*', async (c, next) => {
  const body = await c.req.parseBody()
  const bar = body['foo']
  c.set('bar', bar)
  await next()
})

app.post('/', async (c) => {
  return c.text(c.get('bar'))
})

export default app
```

Command:

```
curl -X POST "localhost:8787" -H "Content-Type: application/json" --data '{"foo":"bar"}'
bar%
```

With Postman:

![SS](https://user-images.githubusercontent.com/10682/182012438-3db919b9-283c-433e-ab48-ba0dcbbc3b0e.png)

**Comment by Zerebokep** [comment]
Must be my code then, I'll double-check everything again and report back.

Btw. is it allowed to use multiple wildcare middlewares?

e.g.

`
app.use('*', async (c, next) => {
  /* custom code A */
  await next()
})
`

`
app.use('*', async (c, next) => {
  /* custom code B */
  await next()
})
`

**Comment by yusukebe** [comment]
> Btw. is it allowed to use multiple wildcard middleware?

Yes! You can try this code:

```ts
import { Hono } from 'hono'

const app = new Hono()

app.use('*', async (_, next) => {
  console.log('foo')
  await next()
})

app.use('*', async (_, next) => {
  console.log('bar')
  await next()
})

app.get('/', async (c) => {
  return c.text('handler')
})

export default app
```

**Comment by techwebdocs** [comment]
Can anybody help me?
Please follow this issue https://github.com/honojs/hono/issues/440

**Comment by yusukebe** [comment]
This may be can be closed.

**Comment by socketopp** [comment]
> 

In the docs, you don't await parseBody(). Why?
https://honojs.dev/docs/api/context/#creq
