### ISSUE TITLE
JWT Middleware to Support Cookies?

### ISSUE THREAD

**Issue by nathanclevenger** [honojs/hono#437]
Today the JWT middleware only works with authorization headers and not cookies
```
const credentials = ctx.req.headers.get('Authorization')
```

What if an optional param to the options:
```
export const jwt = (options: { secret: string; alg?: string; cookie?: string }) => {
```

Then the above code could be modified to something like:
```
const credentials = ctx.req.headers.get('Authorization') ?? ctx.req.cookie[cookie]
```

What do you think?

**Comment by yusukebe** [comment]
Hi! I think it's OK.

@metrue How about you?

**Comment by metrue** [comment]
@yusukebe @nathanclevenger 

Yes, I think it's a great proposal,  let me check it.
