### ISSUE TITLE
Honojs shows 404 Not Found in Postman on app.delete() route with sqlite db

### ISSUE THREAD

**Issue by techwebdocs** [honojs/hono#440]
I have used the url in Postman is http://localhost:3000/user/1 on my local bun server.
In case id 1 already exists in database.
My Code: 
app.delete("/user/:id", async (c)=> {
  const id  = await c.req.param('id');
  console.log(id);
  db.run("DELETE FROM users WHERE id=?",id);
  return c.json({message: 'Deleted'});
});

but other routes are working well.

**Comment by yusukebe** [comment]
Hi @techwebdocs 

This error occurred by this bug of Bun.
https://github.com/oven-sh/bun/issues/677

The only one thing that we can do is wait to fix the bug.

**Comment by fernandolguevara** [comment]
hey! you can move the delete verb to the url in the middletime 


```js
app.delete("/user/:id/delete", async (c)=> {
const id = await c.req.param('id');
console.log(id);
db.run("DELETE FROM users WHERE id=?",id);
return c.json({message: 'Deleted'});
});
```

**Comment by yusukebe** [comment]
This seems to be closed.
