### ISSUE TITLE
Write about third-party MW on `honojs.dev`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#442]
We have to write about third-party middleware on `honojs.dev`.

**Comment by nathanclevenger** [comment]
This is great @yusukebe because there are several that I would love to work on, but I'm still trying to wrap my head around best practices and approach on these.

**Comment by ThatOneBro** [comment]
Hi @yusukebe ! I'll try to work on some documentation like you asked in the next few days. Which middleware should I start with first? Do you have a list that you will think will be most helpful for users?

**Comment by yusukebe** [comment]
Hi @ThatOneBro 

I'm glad you said you'd help!

I've reconsidered. The documentation of third-party middleware will be written by the author in the REAMDE.md of GitHub repository. Not on `honojs.dev`. Only listed. It would be better because the author can write that way freely. What is missing now is the Built-in middleware documentation.

Could you write that? I've created the issue about it on another repository. See: https://github.com/honojs/honojs.dev/issues/6

**Comment by yusukebe** [comment]
@ThatOneBro 

Also, my English isn't good 🥲  , so please rewrite everything if it's wrong and not sufficient.

**Comment by ThatOneBro** [comment]
Yes I'll get to it starting later today! 😄

**Comment by yusukebe** [comment]
Closing this, but we will continue to improve the documentation. Thanks, @ThatOneBro!
