### ISSUE TITLE
Suggestion: use `unknown` instead of `any` for parseBody

### ISSUE THREAD

**Issue by gkiely** [honojs/hono#447]
Unknown is safer and avoids this typescript-eslint error.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/1948935/182282205-e48f9cfe-8d9c-4cf0-94fc-61e3f01d64a6.png">

**Comment by yusukebe** [comment]
Hi @gkiely !

That's a good point! I've added the type `Body` to parsedBody/parseBody. Fixed in #448 

Thank you.

**Comment by gkiely** [comment]
Thank you! I'll try it out in the next version.
