### ISSUE TITLE
Crypto createHash function is not type safe, breaking eTag middleware & timingSafeEqual

### ISSUE THREAD

**Issue by CaptainYarb** [honojs/hono#451]
The [createHash](https://github.com/honojs/hono/blob/main/src/utils/crypto.ts#L26) function in the provided utils is not typesafe for any non-string based data. Any Object that does not natively cast itself to a string, such as JSON, will result in a hash of `[object Object]` which is `c1d44ff03aff1372856c281854f454e2e1d15b7c`. This value is found on one of the [Etag Tests](https://github.com/honojs/hono/blob/main/src/middleware/etag/index.test.ts#L27) as well.

You can replicate this with a basic eTag example where the content always changes:

```javascript
import {Hono} from 'hono';
import {etag} from 'hono/etag';

const app = new Hono();

app.use('*', etag());
// will never respond with a 304, as expected
app.get('/text', async context => context.text(JSON.stringify({random: crypto.randomUUID()})));
// will unexpectedly respond with a 304 on subsequent, despite content changing
app.get('/json', async context => context.json({random: crypto.randomUUID()}));

export default app;
```

This affects:
 - eTag Middleware
 - Buffer util: `timingSafeEqual` comparison

**Comment by yusukebe** [comment]
Hi @CaptainYarb !

It's a bug. I've fixed it in this PR: #452 

Thank you for reporting!!

**Comment by Cherry** [comment]
Thanks @yusukebe!

It appears this impacts other built-ins too, like `ArrayBuffer`.  `String(new ArrayBuffer(1))` will always return just `[object ArrayBuffer]`, which makes comparing them for ETags affected here too.

`return c.body(new ArrayBuffer(1))` vs `return c.body(new ArrayBuffer(2))` should return different ETags with the middleware enabled, but do not. This is obviously a contrived example, but it's common to deal with types like `ArrayBuffer`, etc. in Workers when handling responses, and if these can be passed to `context.body`, should probably also be more safely type checked before being coerced to a string and hashed.

Other things this might impact that I've not tested include `UInt8Array` (and other similar), `ReadableStream`, and maybe more.

**Comment by yusukebe** [comment]
Hi @Cherry 

I see; it's not enough. I'll reopen this issue and will fix it!

**Comment by CaptainYarb** [comment]
Thanks for your quick turnaround on this! You did a great job!
