### ISSUE TITLE
v2.0.6 npm package does not contains committed source code

### ISSUE THREAD

**Issue by NekoPengin** [honojs/hono#455]
`src/middleware/jwt/index.ts` in v2.0.6 Release is older version

new version contains  JWT Middleware to Support Cookies 

hono is great

**Comment by yusukebe** [comment]
Hi @NekoPengin !

Just now, [https://github.com/honojs/hono/releases/tag/v2.0.7](2.0.7) has been shipped! Enjoy!

**Comment by NekoPengin** [comment]
Thank you! I'll try it out in v2.0.7
