### ISSUE TITLE
Documentation on Types?

### ISSUE THREAD

**Issue by TriangularCube** [honojs/hono#456]
There doesn't seem to be documentation for Types, but several types are unclear, specifically

This is what a handler looks like:
```js
(c: Context<string>) => ...
```
except I don't really understand what the Type passed to Context actually is doing, especially since it's defined as `RequestParamKeyType extends string`

**Comment by yusukebe** [comment]
Hi @TriangularCube !

Yes, indeed, there is no documentation for Types. It makes you confusing.

`RequestParamKeyType` is used for getting a string to make literal types for named parameter with `c.req.param()`. See below:

![SS](https://user-images.githubusercontent.com/10682/183289304-d7d50cc6-8d4a-4f7f-b542-cafeaceca601.png)

But, if wrting `a.get('/user/:userId', (c) => ...`, it will be set automatically:

![SS](https://user-images.githubusercontent.com/10682/183289409-8e963ee4-e5a9-4075-b5de-999633b7ed5b.png)

Usually, you don't have to be aware of passing the generics to the Context object.

**Comment by TriangularCube** [comment]
Ah, yes I understand now. Thank you!
