### ISSUE TITLE
Cannot download/stream file greater than 128mb using hono

### ISSUE THREAD

**Issue by Divkix** [honojs/hono#458]
My team and I have been using hono in many services and loving it a lot.
However recently we made a worker to download our files from an r2 bucket, but whenever we tried, it gave errors.

Whenever I try to download a large file:
```
GET https://mybucket.mydomain.com/get/test200m - Ok @ 08/08/2022, 20:06:00
  (log)   <-- GET /get/test200m
  (error) TypeError: Memory limit would be exceeded before EOF.
    at parseBody (index.js:334:35)
    at index.js:970:49
    at async index.js:884:9
    at async index.js:793:9
    at async index.js:902:9
    at async Hono2.dispatch (index.js:733:21)
  (log)   --> GET /get/test200m 500 155ms
``` 

The URL `/get/test200m` gives me `Internal Server Error`.

I tried working around it and found that normal module workers were able to easily perform this operation.

Hono code to download file, which *does not work*:
https://github.com/divideprojects/cdn/blob/6f1c5178ea33b2f19e7cdd72bbdc9873e538aafc/src/_fileOperations.ts#L6...L32
hono routes:
https://github.com/divideprojects/cdn/blob/6f1c5178ea33b2f19e7cdd72bbdc9873e538aafc/src/index.ts#L21

Without hono, which *works*:
https://github.com/divideprojects/cdn/blob/21550bb848fc016c3a83338236fe4700681e8df9/src/index.ts#L36..L75

I was able to download the file without hono but with hono I'm running into issues.

**Comment by yusukebe** [comment]
Hi @Divkix !

This error was caused that the ETag Middlwara did not support large files. I've fixed it by changing the hash algorithm.
We'll release the next version, including this fix, soon. Your code may work well.
