### ISSUE TITLE
Setup twitter account `@honojs`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#464]
I've already got twitter account `@honojs`. This account will be helpful in promoting Hono.

**Comment by metrue** [comment]
Awesome !!!

**Comment by ThatOneBro** [comment]
Great! I was just thinking about this too. It may also be good to make a Discord or some other place for the community to talk in a more freeform but still topic-focused manner. I think Hono community development could go pretty far with only Twitter and Discord! And maybe an English blog as well, about Hono philosophy and approach/ technical learnings from developing Hono. 🤔 

I would like to help on such a blog if the idea sounds good to you. After finishing some documentation first of course :smile:

**Comment by yusukebe** [comment]
Blog!! I really want it!!

Of course, I'm considering making a Discord. However, I fear that it will become a "closed hangout". I think the discussion should be open. So, I also think it would be best to discuss this on GitHub Issues and Discussions. (we have not used Discussions yet) You may change your mind. Let me leave it for a while.

Blog is a good idea. After that, please help me/us!

**Comment by ThatOneBro** [comment]
Ah I understand about the Discord, I haven't thought about it that way but I understand the reasoning. It's a lot of work to manage a Discord too, so maybe not worth it for now; but at least starting using Discussions is a good idea! It can serve as a place for more openly talking about use cases and future of Hono!

**Comment by yusukebe** [comment]
Hi @ThatOneBro !

We've got the request for creating the Discord channel at #483 . So I reconsidered and created a Discord channel of Hono to try it out!

Please join the Discord from this URL!: https://discord.gg/KMh2eNSdxV

**Comment by yusukebe** [comment]
I've done. This is the first tweet!

https://twitter.com/honojs/status/1563048674673864704

**Comment by ThatOneBro** [comment]
Great! Glad to see you decided to try Discord! It should be a great place to have discussions around Hono and build the community 🔥

**Comment by yusukebe** [comment]
Completely done! Closing.
