### ISSUE TITLE
Akamai EdgeWorkers support

### ISSUE THREAD

**Issue by AustinGil** [honojs/hono#471]
I'd love to see support for Akamai EdgeWorkers. I think it might be a stretch considering the difference in supported APIs, but it would be great to have a tool like this for building with. Maybe we can keep this issue as a future feature, or feel free to close it.

**Comment by yusukebe** [comment]
Hi @AustinGil !

You are right, the Akamai EdgeWorkers API looks much different from Web Standard API.
I think it's IMPOSSIBLE :(

I'll close this issue, but a suggestion is welcome. Thanks!
