### ISSUE TITLE
Types for `c.set` and `c.get`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#472]
By #429, we can set the Type for `c.set` and `c.get` functions. This is a fine way to set/get the specific property used in the Middleware.

```ts
type WebClient = {
  user: string
  pass: string
}

declare module 'hono' {
  interface ContextVariableMap {
    client: WebClient
  }
}

//...

app.use('*', async (c, next) => {
  const client: WebClient = { user: 'foo', pass: 'bar' }
  c.set('client', client)
  await next()
})

app.get('/foo', (c) => {
  const client = c.get('client') // client is `WebClient`
  return c.text('foo')
})
```

![SS](https://user-images.githubusercontent.com/10682/185519526-5700022b-ca41-49a2-aaa4-14dac5f4bfe4.png)

It's a great feature, thanks to @usualoma .

Now I want that this could be made more portable and easy to use for users, not the library author. Specifically, it's good if the following code is all needed to complete the project. The point is "without `declare module`".

```ts
app.use('*', async (c, next) => {
  const client: WebClient = { user: 'foo', pass: 'bar' }
  c.set('client', client)
  // OR
  c.set<WebClient>('client', client)

  await next()
})

app.get('/foo', (c) => {
  // show the "type hint" like above in VSCode
  const client = c.get('client') // client is `WebClient`
  return c.text('foo')
})
```

This is very short, and every user can use `set/get` with Types.

**BUT**

I think this is too difficult to implement, or **no way** to implement it exists. We can't treat "Type" this way. I know this is an optimistic thought. But I want to do that. Does anyone know how to make it come true, or do you know other similar API designs to ?

**Comment by mglikesbikes** [comment]
I'm solving this problem with well-named middleware and variables, if that's helpful:

```
// src/handlers/stytch.ts
import type { User } from "stytch/types/lib/shared";

export const useStytchSession = () => {
  return async (c: Context, next: Next) => {
    try {
      const authResponse = await client.sessions.authenticate({ … });
      c.set("stytchUser", authResponse.user as User);
      await next();
    } catch (e) {}
  };
};

// src/handlers/hello
import type { User } from "stytch/types/lib/shared";

app.post('/private', useStytchSession());
app.post('/private', (c:Context) {
  const user: User = c.get('stytchUser');
}
```

**Comment by yusukebe** [comment]
Hi @mglikesbikes !
Thanks, but I still want a Types 🙂

**Comment by yusukebe** [comment]
I made the new feature to add Types to `c.set`/`c.get` by passing Generics to Hono object. #478 

@usualoma 
I want to know your opinion. And please review the PR if you can.
