### ISSUE TITLE
can you give sample request Bearer and JWT with curl

### ISSUE THREAD

**Issue by bobwatcherx** [honojs/hono#474]
i use Bearer auth in hono
my code :
app.use(
  '/*',
  bearerAuth({
    token: 'redss', // Required
    realm: 'redss.com',
    prefix: 'Bot',
    hashFunction: (d: string) => SHA256(d).toString() // For Fastly Compute@Edge
  })
)
app.get('/', (c) => c.text('Hello! 123!'))
Curl Command  = ????

and JWT
my code :
app.use(
  '/*',
    jwt({
    secret: 'tolol123'
  })
)
app.get('/', (c) => c.text('Hello! 123!'))
CURL command = ?????

sorry noob

**Comment by metrue** [comment]
You can check this https://stackoverflow.com/questions/25969196/how-to-define-the-basic-http-authentication-using-curl-correctly

**Comment by bobwatcherx** [comment]
for BASIC i understand , but for Bearer token not work and show unauthorized
```
import { serve } from 'https://deno.land/std/http/server.ts'
import { Hono } from 'https://deno.land/x/hono/mod.ts'
import { bearerAuth } from 'https://deno.land/x/hono/middleware.ts'
const app = new Hono()
app.use(
  '/*',
  bearerAuth({
    token: '123123',
  })
)
app.get('/', (c) => c.text('Hello! Hono!'))

serve(app.fetch)
```
Curl Command : curl -X GET -H 'Bearer: 96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e' 'http://localhost:8000/'
 
and 96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1 is Sha256 encode from 123123
Is unAuthorized 

thanks

**Comment by yusukebe** [comment]
Hi @bobwatcherx !

Try this command:

```
curl -H 'Authorization: Bearer 123123' http://localhost:8000/
```

We have to set the bearer token in the `Authorization` header value.

**Comment by bobwatcherx** [comment]
why i get message error : BAD REQUEST after curl
my server.ts
```
import { serve } from 'https://deno.land/std/http/server.ts'
import { Hono } from 'https://deno.land/x/hono/mod.ts'
import { bearerAuth } from 'https://deno.land/x/hono/middleware.ts'

const app = new Hono()
app.use(
  '/api/get/',
  bearerAuth({
    token: '123123', // Required
    realm: 'example.com',
    prefix: 'Bot',
    hashFunction: (d: string) => SHA256(d).toString(), // For Fastly Compute@Edge
  })
)

app.get('/api/get/', (c) => c.text('Hello! Hono!'))

serve(app.fetch)
```
and curl command :curl -H 'Authorization: Bearer 123123' http://localhost:8000/api/get/
NOT WORK (BAD REQUEST)
and i hash 123123 to sha256 = 96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e

and curl  curl -H 'Authorization: Bearer 96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e' http://localhost:8000/api/get/
NOT WORK ( BAD RERUEST)

Thx

**Comment by yusukebe** [comment]
@bobwatcherx 

You don't need the options below:

* `prefix`
* `hashFunction`

Just write this:

```ts
const app = new Hono()
app.use(
  '/api/get/',
  bearerAuth({
    token: '123123', // Required
    realm: 'example.com',
  })
)

app.get('/api/get/', (c) => c.text('Hello! Hono!'))

serve(app.fetch)
```

**Comment by bobwatcherx** [comment]
Thanks
