### ISSUE TITLE
Deno: serveStatic streams

### ISSUE THREAD

**Issue by deckchairlabs** [honojs/hono#475]
Would be great to have an option for the Deno serveStatic middleware to use streams as the response.

https://deno.land/std@0.152.0/streams/mod.ts?s=readableStreamFromReader

**Comment by yusukebe** [comment]
Hi @deckchairlabs !

We can't handle this right away, but it's an interesting suggestion.

This is not just a Deno issue.

Hono does not support returning Readable Stream from the Context. If it's HTML, there is `c.html()`. If it's JSON, there is `c.json()`. But we don't have `c.stream()` method. This might be a good time to consider supporting Readble Stream. I'll try to make some plans to support Readable Stream and make the Stream option for Serve Static middleware.

Let's keep this issue open. Thank you!

**Comment by deckchairlabs** [comment]
Oh, I've just been using `c.body()` and that seems to be handling streams fine... But thank you regarding the serve static middleware, I've just copied and modified in my project source for now.

**Comment by yusukebe** [comment]
Ah, that's right, we can do it with `c.body`. But I wanted a specialized ReadableStream method. You can use `c.body` for now. Thanks!

**Comment by yusukebe** [comment]
Hi @deckchairlabs 

Maybe we can do it with custom Middleware. If you have time, please try the following code and let me know the results.

```ts
app.get(
  '/static/*',
  async (c, next) => {
    await next()
    const { readable, writable } = new TransformStream()
    c.res.body?.pipeTo(writable)
    c.res = new Response(readable, c.res)
  },
  serveStatic({
    root: './',
  })
)
```
