### ISSUE TITLE
Parsebody return type

### ISSUE THREAD

**Issue by janat08** [honojs/hono#479]
Apparently, if you'd like to type the request body you type the request which is currently a string. Meanwhile, parseBody is a Body type which doesn't have generic.

**Comment by janat08** [comment]
I believe the body type isn't appropriate here, and should be any type rather than unknown since body type has json method which produces any result.

**Comment by yusukebe** [comment]
Hi @janat08 !

You are right parseBody has a problem. How about below? 

```ts
const body = await c.req.parseBody() // body is any

type Post = { message: string }
const postBody = await c.req.parseBody<Post>() // postBody is Post
```
If you do not pass Generics, all objects will be any; if you pass Generics, they will be cast to that type.

**Comment by janat08** [comment]
Yes that works.

**Comment by yusukebe** [comment]
@janat08 

All right! I would fix the code to work this way.
