### ISSUE TITLE
Question/Proposal Multipart form data

### ISSUE THREAD

**Issue by PodaruDragos** [honojs/hono#480]
Hello, 

This is such an awesome project, really good work.
I do have one question. Are there any plans to add a middleware for parsing multipart form data, something like [busboy](https://www.npmjs.com/package/busboy) or [express-fileupload](https://www.npmjs.com/package/express-fileupload) ?

**Comment by yusukebe** [comment]
Hi @PodaruDragos !

Parsing form data is almost available in the current version. You can write like below:

```ts
import { Hono } from 'hono'

const app = new Hono()

type Body = {
  message: string
  logoImage: File
}

app.post('/foo', async (c) => {
  const body = (await c.req.parseBody()) as Body
  return new Response(await body.logoImage.arrayBuffer())
})

export default app
```

Example request:

![SS](https://user-images.githubusercontent.com/10682/186371430-6d85feee-7437-4684-bdbe-8f43619166e8.png)

**Comment by PodaruDragos** [comment]
hey @yusukebe  thanks for the response.
