### ISSUE TITLE
Discord/chat channel for the community

### ISSUE THREAD

**Issue by rishavs** [honojs/hono#483]
Hi

is there a discord channel or equivalent for the Honojs community to hang about and ask questions?
Right now, there doesn't seems to be anywhere we can discuss things which are not strictly library issues.

Having a Discord channel will also help grow the community.

**Comment by yusukebe** [comment]
Hi @rishavs !

I've created the Discord channel just now! Please join https://discord.gg/KMh2eNSdxV

**Comment by yusukebe** [comment]
@metrue @usualoma 
You, also join the Discord channel! https://discord.gg/KMh2eNSdxV
