### ISSUE TITLE
Should `parseBody` only parse FormData?

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#484]
Currently, `req.parseBody()` parses any objects according to content type.

<https://github.com/honojs/hono/blob/main/src/utils/body.ts>

But, I think it would be better just to restrict it to FormData / `req.formData()`.

The first reason, the type we receive will be obscured; thus, it will be `any`. `parseBody` definition is below:

```ts
parseBody<T = any>(r: Request | Response): Promise<T>
```

If it only parses FormData, it will be restricted:

```ts
Record<string, string | File>
```

The second reason, it has the possibility of opening Security Vulnerability because we receive unexpected values. "*Plack*" rejected the PR for the same reason: <https://github.com/plack/Plack/pull/678>.

Consider the following code referred from the PR comment:

```ts
app.post('/foo', async (c) => {
  const body = await c.req.parseBody()
  const id = body.itemId
  const item = shopQuery(id)
  // ~> ['SELECT * FROM shop_item WHERE item_id = ?', id]
  // ...
```

In this case, `body.itemId` is expected `string` but, if receive Request that the body is JSON like below:

```ts
new Request(JSON.stringify({
  itemId: [1, 2, 3],
}), {
  headers: {
    'Content-Type': 'application/json',
  },
})
```

`body.itemId` will be `[1, 2, 3]`. If `shopQuery` behaves differently when it receives a string than when it receives an array, this could be a problem.

```ts
// ~> ['SELECT * FROM shop_item WHERE item_id IN (?,?,?)', id ]
```

This would not happen if `shopQuery` does the type check on the input value, but it would be better to reduce the possibility of this happening. Fortunately, the Request object has a `req.json()`, `req.text()`,  and an `req.arrayBuffer()` method in addition to the `req.formData`. Users can explicitly body parse using those methods. So, `parseBody` should support only FormData. This fix includes breaking changes, but I think we should do it.

---

@metrue @usualoma 
I want to know your opinion.

**Comment by miyagawa** [comment]
> it's the same issue as the "Plack" https://github.com/plack/Plack/pull/678.

Well this statement sounds like Plack does have the issue, while it does not, since the PR has been rejected.

If you need a reference for similar JS vulnerabilities https://flattsecurity.medium.com/finding-an-unseen-sql-injection-by-bypassing-escape-functions-in-mysqljs-mysql-90b27f6542b4 would be a great example.

**Comment by yusukebe** [comment]
@miyagawa 

I apologize for making misunderstanding. I know Plack does/did not have the issue. The description for avoiding the vulnerabilities in the PR is easy to understand, so I referred to it. 

Thank you for sharing the reference!

**Comment by usualoma** [comment]
@yusukebe 

I, too, agree that we should make `parseBody` target only `FormData` and return `Record<string, string | File>`.
