### ISSUE TITLE
Is scheduled support planned?

### ISSUE THREAD

**Issue by dn-l** [honojs/hono#492]
https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/#syntax-module-worker

**Comment by yusukebe** [comment]
Hi @dn-l !

Sorry for the delay in responding. There are no plans to support scheduled event. This is because "fetch event" and "scheduled event" are completely different. Thank you!

**Comment by dn-l** [comment]
Oh I know they are different but if I would like to put both fetch and scheduled events into the same default export I'll have to extend hono's instance. Which is a bit hacky and can be done in a more elegant manner.

**Comment by yusukebe** [comment]
I see, How about the following code? However, I have not used both fetch and scheduled events same time, so it may not be suitable for your use case.

```ts
import { Hono } from 'hono'

export interface Env {}

const app = new Hono<{ Bindings: Env }>()
app.get('/', (c) => c.text('Hello from fetch!'))

export default {
  fetch: app.fetch,
  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    console.log(`Hello form scheduled!`)
  },
}
```

**Comment by dn-l** [comment]
Yes this works

**Comment by AustinZhu** [comment]
Hi @lilienblum 
You may want to take a look at this project! It's inspired by Hono but for Cloudflare Workers cronjobs. I hope it's useful to you.
https://github.com/AustinZhu/kuron
