### ISSUE TITLE
initialize middleware with env variable

### ISSUE THREAD

**Issue by Zerebokep** [honojs/hono#500]
I've tried it with the following:

```
app.use('*', async (c, next) => {
  sentry({ environment: c.env.ENVIRONMENT })

  await next()
})

```
But this seems to cause that sentry isn't properly initialized, any idea how I could achieve that?

**Comment by MaryHal** [comment]
I just ran into this issue myself with one of the other built-in middlewares. As it is now, you're preparing the sentry middleware handler function, but you're not calling it yet.
It should look something like this:
```
app.use('*', async (c, next) => {
  const handler = sentry({ environment: c.env.ENVIRONMENT })
  await handler(c, next)
})
```

**Comment by yusukebe** [comment]
@MaryHal You are right! Thank you.

**Comment by Zerebokep** [comment]
Awesome, thank you @MaryHal.

**Comment by a2xchip** [comment]
Thanks
