### ISSUE TITLE
[Proposal] Allow cors multiple origins

### ISSUE THREAD

**Issue by Tc-001** [honojs/hono#503]
This has been one of the pain points of cors, because without special logic it is usually impossible to allow multiple origins. 

My proposal is to allow:
 ```js
app.use(
  '*',
  cors({
    origin: ['https://example.com', 'https://example.org'],
    //...
  })
)
```

And for the server to respond with the correct entry based on the [`Referrer`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) header. (Falling back to `origin[0]` if empty/none apply)

**Comment by yusukebe** [comment]
Hi @Tc-001 !

Thank you for your proposal! I think this is a good idea and we are able to implement it as the specification you tell us.

I'll try to make it later.
