### ISSUE TITLE
improve documentation on bun + serveStatic

### ISSUE THREAD

**Issue by eitanavgil** [honojs/hono#515]
took me a while and with a bit of frustration to catch this one :) 

When running hono via bun - and trying to serve static files from `assets/static` the example on the website is not working. This line 
```app.use('/static/*', serveStatic({ root: './' }));```
Should be changed to 
```app.use('/static/*', serveStatic({ root: './assets' }));``` 
So we point to the correct folder. 

( I think that the example is cool if you uses `wrangler`)

**Comment by yusukebe** [comment]
Hi @eitanavgil !

Sorry, you're frustrated. I've added some explanations if you would like to take a look.

https://honojs.dev/docs/builtin-middleware/serve-static/
