### ISSUE TITLE
feat: get/set statusCode on Context

### ISSUE THREAD

**Issue by deckchairlabs** [honojs/hono#522]
Hi,

In [Ultra](https://github.com/exhibitionist-digital/ultra) we have a way of rendering your React app with context from Hono, which is useful for setting HTTP response codes during server render using `context.status(404)` for instance.

eg.

```tsx
function RouteNotFound() {
  useServerContext((context) => {
    context.status(404);
  });
  return <div>Not found</div>;
}
```

The problem is, there is no way of then reading that status code so that we can keep the server rendered content.

**Comment by yusukebe** [comment]
Hi @deckchairlabs !

There is `c.status()` method for setting status code already:

```ts
const app = new Hono()

app.get('/foo', (c) => {
  c.status(404)
  return c.text('foo') // status code is 404
})
```

Is this not good enough?

**Comment by deckchairlabs** [comment]
Hi @yusukebe yes, setting status is fine, it's during our response construction that we want to be able to READ that statusCode that the user has set.

So, any of the response builder methods on context, will use the status code set? example

```ts
/** Client code **//
function RouteNotFound() {
  useServerContext((context) => {
    context.status(404);
  });
  return <div>Not found</div>;
}

/** Server code **/
const body = await render()
return context.body(body, status /* this will be what was set above? */)
```

**Comment by deckchairlabs** [comment]
Aha! Yes that does work
