### ISSUE TITLE
c.json naked parameters vs object parameter

### ISSUE THREAD

**Issue by Zerebokep** [honojs/hono#525]
Is there currently any way to use an object parameter for the c.json function? I would like to use the return value(s) of a custom error function, including a default status code.

e.g. 

```
public static sample(props: Props) {
    const { error, status = 400 } = props

    const object = {
      message: error
    }

    return { object, status }
  }
```

**Comment by yusukebe** [comment]
Hi @Zerebokep !

I don't know if I understand your question correctly.

I know I'm wrong but like this?

```ts
const { object, status } = sample(props)
return c.json(object, status)
```

**Comment by Zerebokep** [comment]
Yes, that would work, however, I would like to have it as one-liner. I've put the c.json inside the sample function now, which also works for me. Thank you :)
