### ISSUE TITLE
Hono 2.2.0 throws errors upon initialisation.

### ISSUE THREAD

**Issue by SwatDoge** [honojs/hono#548]
When starting up my project using 2.2.0 on Bun, I get the following error. This issue was instantly resolved upon downgrading from 2.2.0 to 2.1.4.
```
ReferenceError: Cannot access uninitialized variable.
      at /ezlyf/node_modules/hono/dist/context.js:1:0
1 | __require
2 | } from "bun:wrap";
3 | import * as $a8086364 from "/ezlyf/node_modules/hono/dist/hono.js";
4 | 
5 | var { defaultNotFoundMessage} = __require($a8086364);
   ^
   ```

OS:
`jarredsumner/bun:0.1.11` docker container. Upgrading to bun 0.1.13 also does not work.

`Linux 4ebf36805ce1 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 Linux`

I am not using any other dependencies than `bun-types` and `hono`

**Comment by yusukebe** [comment]
Hi @SwatDoge !

This is reproduced in my environment too. I'll investigate this problem. Thank you!

**Comment by yusukebe** [comment]
Hi @SwatDoge !

This issue may be fixed by this release: <https://github.com/honojs/hono/releases/tag/v2.2.1>

Please try it and let me know if there are any problems. Thank you!

**Comment by SwatDoge** [comment]
@yusukebe Works great, thank you for the fast intervention
