### ISSUE TITLE
Better error message in async api handler function

### ISSUE THREAD

**Issue by mishra-prabhakar** [honojs/hono#554]
If you do not write a return statement in the async api handler function we get below error in the console which is I think can be improved

Sample code:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/28021552/192162391-ec0901a6-67a8-47fe-b2ed-f04c02ff2be2.png">

Error message:

![image](https://user-images.githubusercontent.com/28021552/192162231-02f6e8a0-3f0c-4fb4-90a2-eab4c5c42aff.png)

Reason: In the errorHandler function we print the stack and if it is empty then the message.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/28021552/192162437-cab08fd8-fccb-4a27-998a-f952552b43b2.png">

Solution:

What about using `console.trace(err.message)` instead?

Result:

![image](https://user-images.githubusercontent.com/28021552/192162555-bcbbd158-cdcc-40bf-8b44-bec177f9a6ce.png)

Happy to create a PR if this makes sense.

**Comment by yusukebe** [comment]
Hi @mishra-prabhakar !

`console.trace`!! Nice!!

Indeed, current error messages are not friendly. Your proposal may improve Hono. Could you create the PR?

**Comment by mishra-prabhakar** [comment]
Hi @yusukebe 
Absolutely, I will create a PR.

I tried pushing a new branch for creating the PR and it got denied, anything I need to do more?

> ERROR: Permission to honojs/hono.git denied to mishra-prabhakar.

**Comment by mishra-prabhakar** [comment]
Yes, created the PR. Thanks
