### ISSUE TITLE
Can't add hono with bun

### ISSUE THREAD

**Issue by ariefsn** [honojs/hono#560]
Hi,
I try to use Bun, but its fail when try to add hono.
please check [this](https://github.com/oven-sh/bun/discussions/1282).
thanks

**Comment by yusukebe** [comment]
Hmm... I can't reproduce it.

**Comment by ThatOneBro** [comment]
@ariefsn Hello! It's unfortunate it's not working for you, I'm also able to get it to work. I have a few questions to help debug maybe...

1. Which version of bun are you using? 
2. On which OS are you running?
3. Have you installing any other npm package in the same project?
4. Have you been able to use bun install before on this version (of bun)?

Hope we can help you after we are able to get more info on your problem 😄

**Comment by ariefsn** [comment]
hi guys,
yea actually I don't know where is the issue come from 😢
1. bun v.0.1.13
2. Ubuntu 22.04
3. yea, only hono was not installed
4. yes and its fine, only with hono 😭 

![image](https://user-images.githubusercontent.com/33569737/192664740-fc64069e-bd38-47c5-ac32-27c30d513efc.png)
![image](https://user-images.githubusercontent.com/33569737/192664903-ad159977-b3e9-4c0c-97ac-b85214170b1f.png)

**Comment by ThatOneBro** [comment]
Hmm, it definitely could be a bun issue, it may be worth posting an issue in the bun repo. 

I know I saw some issues about installer failing to install some packages sometimes. I think most core bun devs are using Mac, so even though Linux distros are tested, it sometimes takes longer to fix the bugs on Linux. Maybe ask in the bun Discord if this is a known issue first, that may be a good place to start if you haven't already.

Let me know if you get stuck again after asking about the issue on the bun side 😄

**Comment by ariefsn** [comment]
@ThatOneBro ahh yes it's correct, so I try to borrow Mac 😆 
and it's working fine.
so I guess its happened on bun with linux env.
but I'll raise an issue on bun side 😄 
thanks man

**Comment by zhusupq** [comment]
same error in windows +ubuntu wsl
