### ISSUE TITLE
Feature request: Custom error responses for hono/validator

### ISSUE THREAD

**Issue by Skye-31** [honojs/hono#561]
Currently, when using the validator middleware, there's no (nice) way of providing your own error responses when the request passes validation, resulting in a plaintext response that looks something like ```Invalid Value: the JSON body "name" is invalid - undefined```. This isn't ideal for an API where the main format is JSON.

This feature request is to allow people to deal with formatting the error themselves.

**Comment by ThatOneBro** [comment]
Hey @Skye-31 , I agree, this is a necessary feature! I actually have patch, however it's for the old external validator middleware and will need to be ported to the new built-in middleware. I have been planning on creating a PR with this but this issue gives me a good cue that it is time! 

The system I made allows you to pass a `defaultMessageFunc` to the middleware like this:
```ts
{
  ...
  defaultMessageFunc: (ruleName: string, key: string, value: string) =>
          createApiErrorObject(key, getErrorByRuleName(ruleName), value),
}
```

Then in the done function, I'm able to do something like this to return the errors as a json response:
```ts
{
  ...
  done: (result, c) => {
     if (result.hasError) {
       return c.json({ errors: result.messages }, 400);
     }
  },
}
```
I also have thought of allowing this system to be extended at each field, but this would be able to overwrite the default validation error message directly (at least for the json type, maybe separate functions could be specified for each type of validated input source for incoming requests).

@yusukebe What do you think of such a solution? 😄 

If you think it's good, I can modify my existing patch for the new middleware and create a PR for feedback.

**Comment by yusukebe** [comment]
Hi!
I have a few ideas on this matter. Please wait a moment, as I will introduce them later.

**Comment by Skye-31** [comment]
The syntax of this looks good to me 🙂

**Comment by Skye-31** [comment]
Any news on this? 🙂 
I currently have to do a really hacky workaround to get this working for production

**Comment by yusukebe** [comment]
Hi @Skye-31 

Sorry for the late response! Sorry for the late response. I'm just implementing a new way to show the error messages.

By the way, do you know the "done" option? Possibly it will help you get what you want to do.

```ts
app.post(
  '/posts',
  validator(
    (v) => ({
      title: v.body('title').isRequired(),
      body: v.body('body').isRequired(),
    }),
    {
      done: (res, c) => {
        if (res.hasError) {
          return c.json({
            errors: res.messages,
          })
        }
      },
    }
  ),
  (c) => {
    return c.text('Valid!')
  }
)
```

If it has errors, this will return like this:

```json
{
    "errors": [
        "Invalid Value: the request body \"title\" is invalid - undefined",
        "Invalid Value: the request body \"body\" is invalid - undefined"
    ]
}
```

If you haven't already, try it.

**Comment by Skye-31** [comment]
Oh that's perfect, I didn't see it documented anywhere! Thanks

**Comment by ThatOneBro** [comment]
> ```json
> {
>     "errors": [
>         "Invalid Value: the request body \"title\" is invalid - undefined",
>         "Invalid Value: the request body \"body\" is invalid - undefined"
>     ]
> }
> ```

I think one critique I have of this approach is I would like to be able to tell the user of the API which validator rule failed. After that is possible (via a data structure that contains the rule, invalid value, and can tell you even which exact path failed validation), then it will be perfect 😄

**Comment by yusukebe** [comment]
Hi @ThatOneBro !

Exactly. I am thinking the same thing and implementing it. For example, the result objects might look like this:

```ts
    [
      {
        isValid: true,
        message: undefined,
        target: 'header',
        key: 'x-number',
        value: '12345',
        ruleName: 'asString',
        ruleType: 'type',
        jsonData: undefined
      },
      {
        isValid: false,
        message: 'Invalid Value [12345]: the request header "x-number" is invalid - isEqual',
        target: 'header',
        key: 'x-number',
        value: '12345',
        ruleName: 'isEqual',
        ruleType: 'value',
        jsonData: undefined
      }
    ]
```

**Comment by ThatOneBro** [comment]
@yusukebe This looks great! Excited to see how it works.

**Comment by Skye-31** [comment]
> By the way, do you know the "done" option? Possibly it will help you get what you want to do.
Just got around to testing this and it's very useful! Unfortunately it isn't applied when the body is empty (or there's a json.parse error), so I'm still getting text responses there 😞 

For responses with a valid body, this is perfect though!

**Comment by yusukebe** [comment]
Hi @Skye-31 !

Yes, you are right. We can't handle the error in the validator if the body is empty. So, I made the PR to make it possible to handle "Malformed JSON in request body" errors in `done` method. Your problem may be resolved.

https://github.com/honojs/hono/pull/635

@ThatOneBro 

Could you talk a look at the PR and review it?

**Comment by Skye-31** [comment]
With that I'd happily close this 🙂

**Comment by Skye-31** [comment]
Thanks for the fixes😄
