### ISSUE TITLE
Hono/validator: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Skye-31** [honojs/hono#562]
When using something like the following, and there being an invalid request body (e.g. malformed json, or no body at all), the library throws an unexpected end of json error, with status 500.
```js
validator((v) => ({
  email: v
    .json("email")
    .isRequired()
}))
```

It should probably throw a 400 error instead 🙂

**Comment by yusukebe** [comment]
Hi @Skye-31 !

Yes, you are right. It should throw 400. I'll fix it later.

Thank you!

**Comment by yusukebe** [comment]
@Skye-31 

The new version has been released: https://github.com/honojs/hono/releases/tag/v2.2.4

Now, it supports returning 400 when it has a malformed JSON body. Thank @ThatOneBro
