### ISSUE TITLE
Cache middleware broke in 2.2.*

### ISSUE THREAD

**Issue by alinoil** [honojs/hono#564]
Honojs cache middleware broke since 2.2.*
Using the middleware and publishing or running dev in wrangler does not give any errors. Once the route is called it will return a 500 with `Trace: This context has no ExecutionContext` in the worker log.

Running a very simple honojs Cloudflare Workers will reproduce this error:
```js
import { Context, Hono, Next } from 'hono';
import { cache } from 'hono/cache'

const app = new Hono();

app.get('*', cache({ cacheName: 'my-app', cacheControl: 'max-age=3600' }))
app.get('/', (c) => c.text('Pretty Blog API'));

app.fire();
```

**Comment by yusukebe** [comment]
Hi @alinoil !

We've fixed this issue and released a new version "v2.2.3". Try it and let us know if you have any more problems.
