### ISSUE TITLE
Middleware ergonomics with CFW

### ISSUE THREAD

**Issue by qw-in** [honojs/hono#565]
Hello, thanks for the cool library!

I've run into this issue a couple of times where I'd like to use the jwt middleware on CFW but routing the secret in is a bit of a pain. Maybe I'm missing something?

Basically, how do I route my secret located in my `Env` (`new Hono<{ Bindings: Env }>`) to the middleware?

```js
app.get('/hello', jwt({ secret: '...need to pull secret off of context...' }, () => undefined)
```

My proposed solution would be to support a second form of options. If you are interested I'd be happy to make a pr for it!

```js
app.get('/hello', jwt((c) => ({ secret: c.env.SECRET })), () => undefined)
```

**Comment by yusukebe** [comment]
Hi @qw-in !

We recommend writing like this:

```ts
app.get('/auth', async (c, next) => {
  const jwtHandler = jwt({ secret: c.env.SECRET })
  await jwtHandler(c, next)
})
```

It is a little confusing, but this will work correctly without changing the existing API.

**Comment by justinnoel** [comment]
I think the solution above means you can't use the JWT, Basic Auth, or Bearer Auth middleware patterns at all, right?

```
app.use(
  '/auth/*',
  jwt({
    secret: 'it-is-very-secret'
  })
)

app.get('/auth/page', (c) => {
  return c.text('You are authorized')
})
```

Since each route will need to validate the auth secrets themselves.

It's doable for now, but is there no way to use JWT, Basic Auth, or Bearer Auth middleware globally unless secrets are exposed to the code?

**Comment by yusukebe** [comment]
> I think the solution above means you can't use the JWT, Basic Auth, or Bearer Auth middleware patterns at all, right?

We can use that pattern for JWT, Basic AUth, or Bearer Auth middleware.

```ts
app.use('/auth/*', async (c, next) => {
  const jwtHandler = jwt({ secret: c.env.SECRET })
  await jwtHandler(c, next)
})

app.get('/auth/page1', (c) => {
  return c.text('Hello!')
})

app.get('/auth/page2', (c) => {
  return c.text('Night!')
})
```

**Comment by justinnoel** [comment]
Thanks so much for the clarification. I was thinking it you were suggesting the jwt check would have to be done individually on each route.
