### ISSUE TITLE
Cache middleware throws warnings on Cloudflare Workers

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#567]
It throws the warnings:

```
Your worker called response.clone(), but did not read the body of both clones. This is wasteful, as it forces the system to buffer the entire response body in memory, rather than streaming it through. This may cause your worker to be unexpectedly terminated for going over the memory limit. If you only meant to copy the response headers and metadata (e.g. in order to be able to modify them), use `new Response(response.body, response)` instead.
```

**Comment by ThatOneBro** [comment]
Yes I noticed a similar error before, if you terminate the request before reading the body with either `.json()` or `.body()` after cloning in the middleware (as we are doing), then it gives this error on Cloudflare. We probably need to look to see what are the resource/ performance impacts of this and if we should handle this another way or if there is an optimization to be added here.

**Comment by implicit-invocation** [comment]
`zod-validator` (and `typebox-validator`) still calls to `'hono/validator'` and we are still having `value = await c.req.raw.clone().json()` inside `'hono/validator'`, so the warnings are still thrown when using those middlewares.

**Comment by micromashor** [comment]
When using a validator, I don't see why it's necessary to clone the request. You would get the validated request body with `c.req.valid('json')`, leaving no reason to read the request stream in the route handler itself.

To cover odd cases where one wants to read the request stream directly, perhaps an option could be added to explicitly enable cloning.

**Comment by yusukebe** [comment]
This may be fixed. If not, feel free to reopen. Thanks.
