### ISSUE TITLE
Duplicate param name

### ISSUE THREAD

**Issue by gatesn** [honojs/hono#569]
Hono 2.2.2

It seems like the TrieRouter doesn't like the same param name at different levels of the trie:

```typescript
const test = new Hono();
test.get('/:foo', ctx => ctx.json('bar'));
test.get('/abc/:foo', ctx => ctx.json('bar'));
```

```
Error: Duplicate param name, use another name instead of 'foo' - GET /test/abc/:foo <--- 'foo'
    at Node2.insert (/.../node_modules/.pnpm/hono@2.2.2/node_modules/hono/dist/router/trie-router/node.js:54:35)
    at TrieRouter.add (/.../node_modules/.pnpm/hono@2.2.2/node_modules/hono/dist/router/trie-router/router.js:15:19)
```

**Comment by yusukebe** [comment]
Hi @gatesn !

Yes. This is a specification. The same names cannot be used. So, please use different parameter names.

**Comment by gatesn** [comment]
Thank you for the quick response!

That seems a little odd given the endpoints are in theory unrelated to one another? For instance, could the param name be combined with the node level (order) in the implementation to create unique names?

Regardless, that helps me work around my current problem. Happy to make a PR to the docs if it's helpful?

Just to confirm though, this would be allowed?
```
test.get('/abc/:foo', ctx => ctx.json('bar'));
test.get('/abc/:foo/bar', ctx => ctx.json('bar'));
```

**Comment by yusukebe** [comment]
> Just to confirm though, this would be allowed?

No. We can not use the same names. Hono routers support matching multiple handlers, so there is a possibility of name conflicts. Therefore, it throws an error at startup.

This has been discussed on below:
https://github.com/honojs/hono/issues/189#issuecomment-1121704793

**Comment by gatesn** [comment]
Ah that very clear, thank you!
