### ISSUE TITLE
Path templates with parameter prefix

### ISSUE THREAD

**Issue by gatesn** [honojs/hono#570]
Sort of a follow up from #569 but figured it was a subtly different issue. Having renamed the parameter, I've found the router doesn't match a longer path template if it first matches a shorter one.

I've put together a failing test here: https://github.com/honojs/hono/compare/main...gatesn:hono:ngates/prefix-params?expand=1

I believe this can be fixed by removing this `break`: https://github.com/honojs/hono/blob/13ce2eef950f8eb11fe219280b0d5f61bd4fbec1/src/router/trie-router/node.ts#L190

But I'm not familiar enough with the code base to know whether that's correct, or just happens to work in this case.

Many thanks for this project, it's incredibly useful and a pleasure to use :)

**Comment by yusukebe** [comment]
@gatesn 


Wow, that's exactly a bug!! And you are right!! The problem can be solved by deleting the `break`.

Please make the PR. Please!
