### ISSUE TITLE
Regression of `.all()` between 2.1.4 and 2.2.0

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [honojs/hono#574]
Using Cloudflare Workers

Example Code:
```typescript
app.get('/cf', CFEndpoint)
app.get('/version', VersionEndpoint)
app.all(`/cors`, CORSHandle)

app.all('/', async (c) => {
    if (c.env.PRODUCTION === 'true') {
        return c.redirect(
            'https://github.com/Cyb3r-Jak3/workers-serverless-api',
            301
        )
    } else return await c.notFound()
})
app.all('*', (c) => c.notFound())

export default app
```
On 2.1.4 a request to `/cors` goes to the `/cors` endpoint. On 2.2.0 it will return a 404. If `app.all(`/cors`, CORSHandle)` is replaced with `app.get(`/cors`, CORSHandle)` then it gets handled.

**Comment by yusukebe** [comment]
Hi @Cyb3r-Jak3 !

Thank you for creating the issue. It seems to be a bug with the router.

@usualoma 

The following test for RegExpRouter does not pass, can you investigate?

```ts
describe('All', () => {
  const router = new RegExpRouter<string>()

  router.add('GET', '/hello', 'get hello')
  router.add('ALL', '/all', 'get all')

  it('get, all hello', async () => {
    const res = router.match('GET', '/all')
    expect(res).not.toBeNull() // <--- fail!
  })
})
```

**Comment by usualoma** [comment]
Sorry, I’m investigating...

**Comment by yusukebe** [comment]
Hi @Cyb3r-Jak3 

It will be fixed in the new version that has been released now!:

https://github.com/honojs/hono/releases/tag/v2.2.4

**Comment by Cyb3r-Jak3** [comment]
Thanks for the quick work!
