### ISSUE TITLE
Cron Triggers

### ISSUE THREAD

**Issue by acrogenesis** [honojs/hono#581]
Hello, I'm not sure how to setup [Cron Triggers](https://developers.cloudflare.com/workers/platform/cron-triggers) that includes the context.
I want to add/update some values in the KV store but need the context so I can do `context.env.KV.put(key, value)`

**Comment by yusukebe** [comment]
I have not tried this, but how about the following?

```ts
const app = new Hono()

app.get('/', (c) => c.text('foo'))

export default {
  fetch: app.fetch,
  scheduled: async (event, env, ctx) => {
    const value = env.KV.get('foo')
    // ...
    ctx.waitUntil(someTask())
  },
}
```

**Comment by Cherry** [comment]
This works, but you lose the `context` object from Hono, so you can't easily combine this paradigm with other Hono modules like `@honojs/sentry`.

**Comment by yusukebe** [comment]
> but you lose the context object from Hono, so you can't easily combine this paradigm with other Hono modules like @honojs/sentry for error logging, etc.

Ah, yes. Indeed it is good if we can use `@honojs/sentry` in Trigger Event. However, it seems difficult because the `event` object used in Scheduled Event and the one used in`fetch` are different. Or we can create a feature for Cron Trigger, but It will be a long time coming or not coming.

**Comment by yusukebe** [comment]
I'll close this issue.
