### ISSUE TITLE
Questions: Middleware

### ISSUE THREAD

**Issue by socketopp** [honojs/hono#587]
Got two questions:

1. Middleware is set like this: 
`middleware.use('*', prettyJSON())`

What's the argument going against the pattern?
`app.post('/posts', prettyMW, (c) => c.text('Created!', 201))`

2. I can specify a middleware for a specific route but not a specific method. In question one, it's possible to put middleware where you want to. But when using this way, it's only possible to specify what route it should be applied to?

**Comment by ThatOneBro** [comment]
Hi @socketopp , thanks for asking these interesting questions!

I'm not sure if I quite understand your *exact* questions are, but I will try to clarify.

1. `app.use('*',  middleware())` or `app.use('*', (c, next) => customFn(c, next))` are for middleware that are intended to be applied uniformly across a set of routes. This is useful for things that add metadata to all requests -- something like a request logger or the `cors` package. I think it just comes from the pattern that originated in `express`, of declaring middleware on a router using `app.use(...)`. I this the `.use` syntax feels natural for people who used `express` over the years, and that's probably the only reason.

2. You **should** be able to define middleware for a specific method. For example, the `cache` middleware is applied primarily to GET routes. You can see the example in the docs: https://honojs.dev/docs/builtin-middleware/cache
```ts
app.get('*', cache({ cacheName: 'my-app', cacheControl: 'max-age=3600' }))
```
If you are having trouble using this syntax for certain middleware, it may be a bug and we could definitely help solving that if it seems to not be working! Feel free to open an issue for any bug like that and we will get to it as soon as possible!

I hope this answers your questions sufficiently, but if you still have further questions, feel free to address anything you think I misunderstood with your original questions, or any questions that my answers provoked! We are here to help.

**Comment by socketopp** [comment]
Huge thanks for the thorough answer. I consider my questions very answered!

**Comment by ThatOneBro** [comment]
Great! 

We are still trying to improve our documentation now, so can I ask did you look through some of the pages of the documentation or the README and feel like this information could have been easier to find? 

Do you think it would be helpful to have an explanation about the different signatures on this page? https://honojs.dev/docs/api/middleware/ Or how do you think we can make it easier for newcomers to the project to find this info? 

I would appreciate any feedback and if you consider this issue resolved, then feel free to close it after 😄

**Comment by socketopp** [comment]
I think, this time, I read the docs just a little bit too fast to actually see how middleware could be applied.
However, having examples of both ways of applying the middleware would definitely not hurt, if any, that's my feedback on that.

I have a new issue that I would love for you to answer, this time, it's all about the documentation 😄
https://github.com/honojs/hono/issues/588
