### ISSUE TITLE
Documentation of body is most likely wrong, please correct me.

### ISSUE THREAD

**Issue by socketopp** [honojs/hono#588]
[Documentation is very explicit how you parse the body of an incoming post request.](https://honojs.dev/docs/api/context/#creq)

Code: 1
```
// Parse Request body
 app.post('/entry', (c) => {
   const body = c.req.parseBody()
   ...
 })
```
Code 1, with async and await returns `Object {}`

It does not work in hono v.2.2.5. 
After some time and some reading [here](https://github.com/honojs/hono/issues/362) to try the following which actually worked.

Code: 2
```
// Parse Request body
 app.post('/entry', async (c) => {
   const data = await c.req.json()
 })
```

Please tell me that I did something wrong when trying Code: 1, I highly doubt you would have wrong documentation of how to retrieve the body. 

Edit: [Just found this x)](https://github.com/honojs/hono/blob/406c2ee438ed9b4fd92079bb13ad7fd78dcf05aa/docs/MIGRATION.md)

Word of advice, always push updated documentation when doing breaking changes like that in the future [😄](https://emojipedia.org/grinning-face-with-smiling-eyes/)

**Comment by ThatOneBro** [comment]
Good catch! I will update the appropriate documentation. I will try to watch out for any breaking changes like that in the future and make sure the docs stay in sync. We definitely have a lot of catching up to do on the docs, so I appreciate you figuring this out! We can leave this open until I resolve this on the docs repo.

**Comment by yusukebe** [comment]
Hi @socketopp !

> Word of advice, always push updated documentation when doing breaking changes like that in the future

Sorry! I will try to do it!

**Comment by ThatOneBro** [comment]
Hey @socketopp , thanks again for finding this issue with the docs! We just merged the changes that describe the current way to do thing. If you think this is sufficient for this issue, please feel free to close this issue. And please, let us know any other difficulties you may run into!

**Comment by socketopp** [comment]
I think it's definitely much more explicit now. Thanks! 
Got another issue coming up regarding the env while working with Cloudflare worker and KV, hopefully this isn't due to lacking documentation [😉](https://emojipedia.org/winking-face/)

**Comment by chromashirts** [comment]
Could the use case of parsing POST request body content with .json() also be showcased on the "Getting Started" page? It took me literally hours of debugging until I realized it. :(
