### ISSUE TITLE
Parameter for unknown amount of segments

### ISSUE THREAD

**Issue by b3ngg** [honojs/hono#591]
Hi there! Very cool project!

I'm currently migrating an API from SvelteKit Endpoints to a standalone Cloudflare Worker and would love to use Hono for this! With the current API, we rely heavily on a SvelteKit feature called Rest parameters (https://kit.svelte.dev/docs/advanced-routing#rest-parameters) which basically allows you to define a parameter for an unknown amount of path segments. Or in other words a wildcard as a parameter. 

I was wondering if something like this is possible with Hono: 
```ts
app.get('/block/:(...path)', (c) => {
  return c.text(c.req.param('path'))
})

// GET http://localhost:8787/block/key1/key2/key3/key4 -> key1/key2/key3/key4
```

I guess a workaround would be to use a wildcard and manually try to extract this from `c.req.url`. But this wouldn't be very elegant as this method would always require information about the other route parameters. Resulting in defining the parameters twice. 

Is there a better way? Thanks in advance!

**Comment by yusukebe** [comment]
Hi @b3ngg !

Thank you for creating the issue. It's an interesting thing.

Currently, the routers used in Hono don't support "unknown amount of segments". We cannot do what you want at the router level.

> I guess a workaround would be to use a wildcard and manually try to extract this from `c.req.url`. 

Yes, this is one of the ways left to do it. If you use Middleware, you can write it this way:

```ts
import { Hono } from 'hono'
import { getPathFromURL } from 'hono/utils/url'

type Variables = {
  pathWithSegments: string
}

const app = new Hono<{ Variables: Variables }>()

app.get('/block/*', async (c, next) => {
  const path = getPathFromURL(c.req.url)
  c.set('pathWithSegments', path.replace(/^\/block\//, ''))
  await next()
})

app.get('/block/*', (c) => {
  const path = c.get('pathWithSegments')
  return c.text(`The path you are accessing is: ${path}`)
})
```

It is possible that routers will support this in the future, but now I think this is the best way.

**Comment by b3ngg** [comment]
Hey @yusukebe thank you for the response. 

Using Middleware makes things definitely a bit cleaner. Also, the `getPathFromURL` util is quite handy!

Luckily our endpoints all follow a similar pattern (`/<version>/<project-id>/<endpoint>/<...path>`), so I think I can get a generic middleware for all endpoints working by counting the segments. 

Router support for this would be pretty cool in my opinion. But I have of course no idea how often this would be used and the implication of this. 

Thank you!

**Comment by matthewrobb** [comment]
This keeps popping up as problematic for me. Wanting to forward the wildcard path portion to a Durable Object in cloudflare but have to parse it out uniquely each time :/
