### ISSUE TITLE
`c.set` & `c.get` variable types are not enforced

### ISSUE THREAD

**Issue by justinnoel** [honojs/hono#597]
**UPDATE**: I actually think this might not be a problem. It seems to be because I don't really have linting in this project.

On another project, I have linting and am warned with `@typescript-eslint/no-unsafe-assignment` when I try to access a variable that was not in the `CustomVariables` type.

Does that seem right to you? If so, I'll just close this.

**/Update**

---

I'm trying to using types for variables as implemented in #478.

In this example (https://github.com/justinnoel/hono-cloudflare-pages-ssr), I've modified as follows;

• **/src/types.ts:**

```
export type CustomVariables = {
	counter: string;
}
```

---

• **src/index.tsx:**

```
const app = new Hono<{ Bindings: Env; Variables: CustomVariables }>();

...

app.get("/post/:id{[0-9]+}", async (c) => {
	const id = c.req.param("id");

	const counter = Number(c.get("counter") || "1");
	const conter = c.get("conter");

	console.log("counter = ", counter)
	console.log("conter = ", conter)

	const post = await getPost({ id, namespace: c.env.HONO_PAGES_BLOG_POSTS });
	if (!post) {
		return c.notFound();
	}

	return c.html(<Page post={post} counter={counter} />);
});
```

---

As I'm typing, Code does properly hint that `counter` is available for `c.get()`. However, it does not prevent use of variable names that **don't** exist. It does not show `conter` as an invalid variable.

This screenshot shows that TypeScript is perfectly happy with a correct **and** and incorrect variable name.

![hono-variables-not-enforced](https://user-images.githubusercontent.com/81643826/194851012-0b64f5f9-fa36-47e2-b5f6-91c029516202.jpg)

Is there any way to enforce the correct variables?

**Comment by yusukebe** [comment]
Hi @justinnoel !

> On another project, I have linting and am warned with @typescript-eslint/no-unsafe-assignment when I try to access a variable that was not in the CustomVariables type.

This seems to be caused by that the value not defined in CustomVariables will be "any". It's not a bug, this is expected behavior. I don't use `@typescript-eslint/no-unsafe-assignment` in my environment, so I don't get that warning. If you want to continue using it, you can cast it to the appropriate type using `as`.
