### ISSUE TITLE
How can I get the clone of original request?

### ISSUE THREAD

**Issue by xoosye** [honojs/hono#599]
Hi there,

Thank you to everyone in this community, you have inspired me a lot.

I'm working on proxy feature with Hono, is there possible to get original request object ? then I don't have to parsebody and set the header manually , 
 just like: https://developers.cloudflare.com/workers/examples/bulk-origin-proxy/

`const ORIGINS = {
  'starwarsapi.yourdomain.com': 'swapi.dev',
  'google.yourdomain.com': 'www.google.com',
};

function handleRequest(request) {
  const url = new URL(request.url);
  // Check if incoming hostname is a key in the ORIGINS object
  if (url.hostname in ORIGINS) {
    const target = ORIGINS[url.hostname];
    url.hostname = target;
    // If it is, proxy request to that third party origin
    return fetch(url.toString(), request);
  }

  // Otherwise, process request as normal
  return fetch(request);
}

addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request));
});`

**Comment by yusukebe** [comment]
Hi @xoosye !

We can get the original request by using `c.req` like this:

```ts
app.all('*', (c) => {
  const url = new URL(c.req.url)
  if (url.hostname in ORIGINS) {
    const target = ORIGINS[url.hostname]
    url.hostname = target
    return fetch(url.toString(), c.req)
  }
  return fetch(c.req)
})
```

Try it and let me know if you still have problems.

**Comment by xoosye** [comment]
> Hi @xoosye !
> 
> We can get the original request by using `c.req` like this:
> 
> ```ts
> app.all('*', (c) => {
>   const url = new URL(c.req.url)
>   if (url.hostname in ORIGINS) {
>     const target = ORIGINS[url.hostname]
>     url.hostname = target
>     return fetch(url.toString(), c.req)
>   }
>   return fetch(c.req)
> })
> ```
> 
> Try it and let me know if you still have problems.

That works! 
Thank you @yusukebe ! 
Hono is awesome!
