### ISSUE TITLE
Hono Bun jsx displays [object Object]

### ISSUE THREAD

**Issue by llad** [honojs/hono#606]
I cannot get the jsx middleware to render HTML using the examples provided, the page always displays: [object Object] .

I am using the exact code from: https://github.com/honojs/examples/blob/main/bun/jsx.tsx

I am using the same tsconfig.json

Any ideas?

**Comment by yusukebe** [comment]
HI @llad !

It seems that the JSX transformation way used inside Bun has changed. Try writing `tsconfig.json` as follows:

```ts
{
  "compilerOptions": {
    "jsx": "preserve",
    "jsxFragmentFactory": "Fragment",
    "jsxImportSource": "hono/jsx"
  }
}
```

I think it will work well.

**Comment by llad** [comment]
Hi @yusukebe — that worked perfectly. Thank you! I am really enjoying learning Hono. Keep up the good work.
