### ISSUE TITLE
Too many subrequests.

### ISSUE THREAD

**Issue by tolgaand** [honojs/hono#616]
Hi,

on a blockchain, I'm trying to get the information that the transaction has been approved.
```javascript
const confirmation = await connection.confirmTransaction({
        signature,
        blockhash,
        lastValidBlockHeight,
    },
    "finalized"
);
```

The `confirmTransaction` function assigns multiple get requests in the background to verify whether the transaction has been confirmed or not.

in this case "error: Too many sub-requests. Thus, employees can submit up to 50 sub-requests per request."

the error returns. I don't get errors when I do the same with Expressjs.
What am I doing wrong?

**Comment by yusukebe** [comment]
Hi @tolgaand !

Which platform do you run on? I think it's not Hono matter but the platform matter.

**Comment by tolgaand** [comment]
Hi @yusukebe , thanks for your comment.

For two days I thought it wasn't about hono.
But then I realized that when I try with frontend(next) and backend(express), there is no problem.
The code of the `confirmTransaction` function is [here](https://github.com/solana-labs/solana/blob/1fbd818647e7e87b9c706ddb26a28572d19a44c8/web3.js/src/connection.ts#L3347)

**Comment by yusukebe** [comment]
@tolgaand 

I've investigated. If you are running on Cloudflare Workers, then you can only make up to 50 external `fetch` sub-requests in the free plan.

https://developers.cloudflare.com/workers/platform/limits/

Maybe this is the issue.

**Comment by tolgaand** [comment]
@yusukebe thanks for your comment.

The '@honojs/node-server' library worked.
One last question; where can I deploy my project using this library?

**Comment by yusukebe** [comment]
> The `@honojs/node-server` library worked.

Good!

> One last question; where can I deploy my project using this library?

You can deploy it anywhere Node.js works. Version 16.x or 18.x would be good. If you like "serverless", maybe it will work on AWS lambda or Google Cloud Functions. Or you can make it runs on VPS or containers...

**Comment by KailasMahavarkar** [comment]
Hi, thank you for creating Hono,
do you have any example of how to use "@honojs/node-server" with AWS lambda (serverless)?

**Comment by yusukebe** [comment]
Hi @KailasMahavarkar !

> do you have any example of how to use "@honojs/node-server" with AWS lambda (serverless)?

Not yet. I have never heard about Hono running on AWS. Let me know if you get it to work :)
