### ISSUE TITLE
[Validator] Support `default()`

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#623]
How about setting the default value with `default()`.

```ts
v.query('page').isNumeric().default('1')
```

**Comment by ThatOneBro** [comment]
Makes sense to me 👍

**Comment by digitalmio** [comment]
I'm not sure if I understand this correctly - so you're passing `'1'` as default, as string, but you're checking that it should be numeric, so default in this case will fail validation, or should it be
```js
v.query('page').isNumeric().default(1)
```

**Comment by yusukebe** [comment]
Hi @digitalmio !

This is a bit confusing, but `isNumeric` does not mean the `number` type, but rather the numeric "0 - 9" of `string`.

**Comment by digitalmio** [comment]
Ah, of course! As this is query param, so everything is a string. Makes sense
