### ISSUE TITLE
[Validator] It will be invalid if the key exists but the value is blank

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#628]
The validation rule:

```ts
page: v.query('page').isNumeric().isOptional()
```

Request:

```
GET http://localhost:8788/?query=foo&page=
```

It will be invalid:

```ts
Invalid Value []: the query parameter "page" is invalid - isNumeric
```

I think it should be "valid" where the key exists or not.

**Comment by digitalmio** [comment]
For me current behaviour is as expected. You have param that is not numeric, hence not valid.
