### ISSUE TITLE
Mocking c.env

### ISSUE THREAD

**Issue by gkiely** [honojs/hono#630]
I'm writing a test that reads/writes to cloudflare kv. I'm using `c.env.KV.put` and `c.env.KV.get` for example.

Instead of read/writing to it, I would like to mock the context env.

Is there a way to do this?

**Comment by yusukebe** [comment]
Hi @gkiely !

How about using `jest-environment-miniflare`? Or already using it?

**Comment by gkiely** [comment]
Found a way for anyone else that comes across this.
```ts
const request = new Request('http://localhost/auth/google/callback?code=123');
const response = await app.fetch(request, {
  kv: {
    delete: () => Promise.resolve(),
    getWithMetadata: () =>
      Promise.resolve({
        value: null,
        metadata: null,
      }),
    list: () =>
      Promise.resolve({
        keys: [],
        list_complete: true,
      }),
    get: () => Promise.resolve(null),
    put: () => Promise.resolve(),
  },
});
```
