### ISSUE TITLE
Use Wrangler secrets for basic auth?

### ISSUE THREAD

**Issue by cd-slash** [honojs/hono#639]
The docs examples for basic auth store the basic auth username and password in the `index.ts` in plain text, which is not ideal since it will be visible in the code base. An alternative is to use the Wrangler secrets command to store these as an environment variable with a slight modification to the auth code:
```
app.use('*', async (c, next) => {
  const auth = basicAuth({
    username: c.env.BASIC_AUTH_USERNAME,
    password: c.env.BASIC_AUTH_PASSWORD
  })
  return await auth(c, next)
})
```

Storing the secrets can be done with:
```
echo 'supersecretpassword' | npx wrangler secret put BASIC_AUTH_PASSWORD
```

Is there any reason this approach should not be taken or that it's not recommended?

**Comment by yusukebe** [comment]
Hi @cd-slash !

> Is there any reason this approach should not be taken or that it's not recommended?

No! It's better to use environment variables. Your way is correct.

In the "Blog" example, the same way is used:

https://github.com/honojs/examples/blob/main/blog/src/index.ts#L13

```ts
middleware.use('/posts/*', async (c, next) => {
  if (c.req.method !== 'GET') {
    const auth = basicAuth({ username: c.env.USERNAME, password: c.env.PASSWORD })
    return auth(c, next)
  } else {
    await next()
  }
})
```

(However, this code is old and may need to be improved. Regardless, your code is correct!)

**Comment by cd-slash** [comment]
Thanks! I created [this PR](https://github.com/honojs/honojs.dev/pull/22) in the docs repo to show an example of this as it took me quite a while to work it out, so it may be helpful to others.

**Comment by yusukebe** [comment]
I think this can be closed.
