### ISSUE TITLE
New worker- types and ambient types

### ISSUE THREAD

**Issue by stefanmaric** [honojs/hono#671]
Cloudflare has released a new major version of their worker types: https://blog.cloudflare.com/improving-workers-types/

This new version adds exported types, so using ambient types are not required. See: https://github.com/cloudflare/workers-types/issues/195

Right now Hono pulls `@cloudflare/worker-types@3`'s ambient types into its own types, and since references are added globally in TypeScript's compilation context, consumers of Hono get their context polluted with Cloudflare's types as well.

This is a bit of problem if either your project doesn't target workers as a runtime or if you want to create re-usable Hono middlewares.

Would it be an option for Hono to upgrade to the `v4` of `@cloudflare/worker-types`, use imports types to reference Cloudflare's types, and remove the global Hono `Request` declaration?

The caveat is that this would be a breaking change for those creating handlers/middlewares without explicitly using Hono's Handler/Middleware types. That's it, those setting the types for their functions like:

```typescript
export const myHandler = (ctx: { req: Request }, next: () => Promise<void>): Response => {
  const thing = req.param('thing')
  //----------------^
  // TS would complain here since browser/workers Request doesn't have Hono's methods.
  ...
}
```

I wouldn't expect many to be using this syntax as it is very verbose.

**Comment by yusukebe** [comment]
Hi @stefanmaric !

Thanks for telling us. This is a serious issue. I am thinking about which is the best way while creating prototypes.
