### ISSUE TITLE
[2.5.5] Argument of type 'Context<string, Environment, Schema>' is not assignable to parameter of type 'Context<string, Environment, ValidatedData>'.

### ISSUE THREAD

**Issue by Zerebokep** [honojs/hono#675]
After the upgrade to 2.5.5 I get the following error:

<img width="933" alt="Screenshot" src="https://user-images.githubusercontent.com/15731988/203602980-c9b87721-b598-48fd-a8d9-6b6eaa59dc59.png">

<img width="294" alt="Screenshot" src="https://user-images.githubusercontent.com/15731988/203603053-b8709d0d-9f20-4f8c-88f0-be704fa99d84.png">

Same for using getSentry()

**Comment by yusukebe** [comment]
This minimal project works well.

https://gist.github.com/yusukebe/e3be7859f2c174b1785b0481907bd472

Please refer to.

**Comment by Zerebokep** [comment]
> Hi @Zerebokep !
> 
> Is this error only when using Sentry Middleware?

Yes, it only applies to this route, all other routes are working fine.

> This minimal project works well.
> 
> https://gist.github.com/yusukebe/e3be7859f2c174b1785b0481907bd472
> 
> Please refer to.

Can confirm that, I don't understand why this error is shown on my project.

It seems sentry() returns `Handler<string, Environment, ValidatedData>` instead of `Context<string, Environment, Schema>` which is handler() looking for. 🤔

**Comment by Zerebokep** [comment]
Weird, it seems my @honojs/sentry dist folder does not contain a types.d.ts file, that seems to be the issue. It falls back to the hono.d.ts.

**Comment by Zerebokep** [comment]
`yarn upgrade @honojs/sentry` fixed my issue, but I have no idea why. I used `yarn upgrade` and even `yarn upgrade-interactive --latest`, both had no effect on the mentioned issue.

Anyways, thank you for the help. @yusukebe

**Comment by yusukebe** [comment]
Good news! Thanks!
