### ISSUE TITLE
Middleware is bypassed when get("*") is used

### ISSUE THREAD

**Issue by AlexDicy** [honojs/hono#681]
Hello! I'm not sure if this is expected behavior or not, but I'm having an issue with a middleware not executing for a specific path:

```typescript
app.use("/v1/p/*", async (c, next) => {
  console.log("Middleware called");
  return c.text("OK");
});

app.get("*", async (c) => {
  return c.text("GET called");
})
```

What happens?
Calling `/` -> `GET called`, expected
Calling `/v1/p` -> `GET called`, expected
Calling `/v1/p/test` -> `GET called`, expected value: `OK` + console.log

If I remove the get route, the middleware works for the last two cases

**Comment by yusukebe** [comment]
Hi @AlexDicy !

Thank you for the issue. Our expected behaviors are below:

1. GET `/` -> GET called
2. GET `/v1/p` -> OK + console.log
3. GET `/v1/p/test` -> OK + console.log

"2" may be confusing, but the `/*` in `/v1/p/*` has a special meaning and is supposed to match `/v1/p`. So, in your code, "2" and "3" not work well. This is happen when using `RegExpRouter` which is used in your application. But, if I've tried to use `TrieRouter`, it works well.

Hi @usualoma !

Could you check this issue for `RegExpRouter`?

**Comment by AlexDicy** [comment]
Thank you!
What do I lose for switching to TrieRouter instead of RegExpRouter if I'm not using regex in my routes?

**Comment by yusukebe** [comment]
@AlexDicy 

`RegExpRouter` is one of the "routers" which is used inside Hono. It is used whether or not regexp is used in your routes (In some cases, however, `StaticRouter` or `TrieRouter` may be used. Sorry for the complication:). This is an internal thing you may not need to know about.

**Comment by usualoma** [comment]
investigating...
