### ISSUE TITLE
[Validator] validate named parameters

### ISSUE THREAD

**Issue by Tc-001** [honojs/hono#682]
Currently it is not possible to validate named (path) parameters using the `validator` middleware.

Something similar to:
```js
app.get(
	"/user/:id/posts/:page",
	validator((v) => ({
		v.param("id").asNumber(),
		v.param("page").asNumber()
	}),
	async (c) => ...
)
```

There are a few questions I think (for example how would `isRequiered` function), but overall this should greatly help the route's readability.

I could give a shot at making a PR if this is something that is possible/needed

**Comment by yusukebe** [comment]
Hi @Tc-001 !

Thank you for creating the issue.

I thought the same thing about validating named path parameters. But, after considering it, it's enough to capture path parameters with regexp.

```ts
app.get('/users/:id{[0-9]+}/posts/:page{[0-9]+}', (c) => {
  const { id, page } = c.req.param()
  ...
})
```

How do you feel about this?

**Comment by Tc-001** [comment]
Wow, I did not know that was possible. 
That is definetly enough for my usecase, and I can't really see anything more advanced being necessary.

So ye, unless there is a usecase I haven't thought about this issue can be closed :+1:

**Comment by yusukebe** [comment]
Okay! I'll close this issue. Thank you!
