### ISSUE TITLE
`c.runtime === 'node'` does not work well

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#685]
`c.runtime === 'node'` does not work well. It is because the `global.process.title` is such as`/Users/yusuke/.n/bin/node` in my environment. We have to detect which is `node` or not in another way.

**Comment by yusukebe** [comment]
Hi @yujong-lee !

If you have time, could you consider this issue?

**Comment by yujong-lee** [comment]
@yusukebe 

I think `(typeof process !== 'undefined') && (process.release.name === 'node')` is reliable solution.
https://nodejs.org/api/process.html#processrelease

Could you test if it works for your environment?

**Comment by yusukebe** [comment]
@yujong-lee 

Yes! `process.release.name` become `node` in my environment! It's good.

So, could you make the PR to fix this issue?
