### ISSUE TITLE
Handler `Schema` does not allow normal types

### ISSUE THREAD

**Issue by ryan-mars** [honojs/hono#689]
Middleware must extend the validator Schema type to provide type safety for middleware specific properties or data. This requires middleware to map normal types to the Hono validator types:
https://github.com/honojs/hono/blob/07efdb5103c4cdb37585724945e26d93f33de383/src/validator/schema.ts#L13-L24

For instance, the following middleware results in a type error.
```typescript
const validateMe = () => {
  const handler: MiddlewareHandler<
    string,
    { Bindings: Bindings },
    { post: { id: string } } // <--- Type '{ post: { id: string; }; }' does not satisfy the constraint 'Partial<Schema>'.
> = async (c, next) => {
   // validation ... 
    await next();
  };
  return handler;
};
```

If one were to implement a Zod based validator one would need to map to the validator specific types which seems unnecessary.

**Comment by yusukebe** [comment]
Hi @ryan-mars !

Thank you for creating the issue.

To be honest, I hadn't really thought about extending the validation scheme. So, it has been such the implementation.

If possible, can you show some more snippets of validation using a Zod?

**Comment by ryan-mars** [comment]
I'm currently using Zod for input validation and I'm also using it with another library to generate our OpenAPI spec. 

Here's an example of Zod schema usage. 
```typescript 
const UserSchema = z.object({
  id: z.string(),
  name: z.string(),
  age: z.number(),
});

// You can extract the TypeScript type of any schema
type User = z.infer<typeof UserSchema>;
//   ^? type User = {  id: string;  name: string;  age: number;}

// To parse a request you might do this...
const user: User = UserSchema.parse(await request.json());
//                 ^? const UserSchema: z.ZodObject<{  id: z.ZodString;  name: z.ZodString;  age: ...

```

All I want is to pass normal TypeScript types from my validation middleware to the handler, but without using the Hono validator specific types.

**Comment by yusukebe** [comment]
@ryan-mars 

I understood the usage of Zod schema. And I would like to know how to pass the validated results from the middleware to the handler.

Is the solution, for example, this?

```ts
const validateMe = () => {
  const handler: Handler<User> = async (c, next) => {
    const user = UserSchema.parse(await c.req.json())
    c.req.valid(user) // or like: c.setValidatedData(user)
    await next()
  }
  return handler
}

app.get('/', validateMe(), (c) => {
  const user = c.req.valid() // <--- user will be `User`
  //...
})
```

Or you can use `c.set()`/`c.get()` in the current version to get it done.

```ts

type Env = {
  Variables: {
    user: User
  }
}

const api = new Hono<Env>()

const validator: Handler<Env> = async (c, next) => {
  const user = UserSchema.parse(await c.req.json())
  c.set('user', user)
  await next()
}

api.post('/post', validator, (c) => {
  const user = c.get('user') // <--- user will be `User`
  //...
  return c.text('Created', 201)
})

app.route('/api', api)
```

**Comment by yusukebe** [comment]
Hi @ryan-mars !

I've made PR #700 . I think this may resolve this issue. Please check it!

**Comment by ryan-mars** [comment]
Thank you. Will review this evening.

**Comment by ryan-mars** [comment]
#700 Looks great! Please merge.
