### ISSUE TITLE
cors middleware vulnerability

### ISSUE THREAD

**Issue by dagnelies** [honojs/hono#692]
Hi, 

Currently, the cors middleware is vulnerable and has a few culprits.

- the `next` callback is directly invoked, even before the cors checks if the request is allowed or not
- the `next` callback is invoked twice, once for the preflight request and once for the actual request
- by default, all methods are allowed, which differs from the standard which allows only get/head/post by default
- some other defaults are overridden

As a practical example, it would quite be disastrous to first apply `POST /delete-account` before noticing that the origin/method is not allowed. 

Now, this *should* not happen because the preflight request already forbids the browser to send further requests. However, if the preflight request itself triggers some "any method" route (including `OPTIONS`) due to the `next` callback, you may unintentionally trigger the corresponding code instead of having the request blocked.

**Comment by yusukebe** [comment]
This is fixed by #693
