### ISSUE TITLE
Sending JSON to Hono without content-type set returns a 500

### ISSUE THREAD

**Issue by OultimoCoder** [honojs/hono#695]
Surely this error should be at least propagated to the app.onError or handled better?

**Comment by yusukebe** [comment]
Hi @OultimoCoder !

It depends on the case. If you want to handle all errors in the same way, you can use only `app.onError()`. If you want to divide it by whether it is a JSON error or not, you need to handle it in the handler.

**Comment by yusukebe** [comment]
This can be closed.
