### ISSUE TITLE
Caches on Deno Deploy

### ISSUE THREAD

**Issue by ndaidong** [honojs/hono#698]
Hello,

I got this error while running on Deno Deploy, had to stop using cache middleware.

![205103158-a9e71ea6-84dd-4109-953b-1222ea29a3c9](https://user-images.githubusercontent.com/1809619/205196836-24193592-3a89-432e-94ba-3f7f3e46c5dc.png)

It may relate to [this part](https://github.com/honojs/hono/blob/main/src/middleware/cache/index.ts#L18), where the global `caches` variable isn't available as Cache API has not been supported by Deno Deploy. I guess that.

**Comment by yusukebe** [comment]
Hi @ndaidong !

Ah, yes. It seems so. We'll have to make that clear in the document. Thanks!

**Comment by heysolomon** [comment]
Hello, I would like to jump on to fix this issue

**Comment by yusukebe** [comment]
@heysolomon 

I had not done it yet. Yes, just add a note there.

**Comment by heysolomon** [comment]
> @heysolomon
> 
> I had not done it yet. Yes, just add a note there.

okay

**Comment by heysolomon** [comment]
> @heysolomon
> 
> I had not done it yet. Yes, just add a note there.

After going through the repo, I couldn't find the folder/file relating to the [hono.dev](https://hono.dev/middleware/builtin/cache) document, I checked other repositories in the `honojs` organization and found the `website` repo, which is the repository for [hono.dev](https://hono.dev/middleware/builtin/cache).

I will create an issue similar to the title here, and add the note there.

This is fine right?

**Comment by yusukebe** [comment]
@heysolomon 

Yeah, thank you for the PR! This issue can be closed!
