### ISSUE TITLE
Empty `body` and `headers` on POST requests

### ISSUE THREAD

**Issue by serban-mihai** [honojs/hono#701]
I don't get any headers or body data during a POST request.

My code intercepts the request and returns a `.json()` of the `c` context and even though I've been passing a JSON body and headers they are not included within the request.

![Screenshot_2022-12-04_23-02-04](https://user-images.githubusercontent.com/34487580/205516458-39bebcbb-cde5-4a5d-ae5e-6c1ca0cd3eea.png)

I've tried with `parseBody()` `body` and `bodyData` over `c.req` the examples also feature a [parsedBody](https://github.com/honojs/examples/blob/main/basic/src/index.ts#L103) that doesn't exist anymore according to worker types and the confusion goes on for such an essential thing.

The code looks like this:
```javascript
bookmarks.post("/:domain", async (c) => c.json({ status: 200, code: "Success", data: c });
```
I can see by console logging that the value of the `body` key is `{ stream: undefined, source: null, length: null }`

I've tested it on localhost with Cloudflare Workers over both `Wrangler` and `Miniflare`, they both return an empty object.
Currently using the latest Hono `2.5.7` and [Thunder](https://www.thunderclient.com/) for sending requests, I also tried to use `curl` to be sure it's not a Thunder problem and it's still reproducing.

Is this normal?
Is there a correct way to collect the body for a `POST` request? Didn't find anything about it in the docs.

**Comment by serban-mihai** [comment]
Ok, after 2 hrs of head-breaking I realized my stupidity 😅 
If anyone gets in this situation you can just:
```javascript
const body = await c.req.json()
```
I'll solve this issue, but the docs need a refactor, might have some ideas as feedback if needed.

**Comment by yusukebe** [comment]
Hi @serban-mihai !

I feel sorry to have cost you two precious hours of your time.

> I'll solve this issue, but the docs need a refactor, might have some ideas as feedback if needed.

Yes, we need to improve the documents. If you can help, PR is always welcome. The repository  for the website is here:

https://github.com/honojs/honojs.dev

Thanks!
