### ISSUE TITLE
Feature: Middleware execution order

### ISSUE THREAD

**Issue by PietervdWerk** [honojs/hono#703]
The hono middleware is great, but I think the execution order should be different.

As stated in the Routing Priority documentation: "Handlers or middleware will be executed in registration order."
Though, middlewares don't execute according to that rule. 

```typescript
const router = new Hono()

router.use(async (context, next) => {
  console.log('first middleware before next')
  await next()
  console.log('first middleware after next')
})
router.use(async (context, next) => {
  console.log('second middleware before next')
  await next()
  console.log('second middleware after next')
})
router.use(async (context, next) => {
  console.log('third middleware before next')
  await next()
  console.log('third middleware after next')
})


router.get('/', (context) => context.json({ hello: 'world' }))
```

The console will look like the following:
1. first middleware before next
2. second middleware before next
3. third middleware before next
4. third middleware after next
5. second middleware after next
6. first middleware after next

What I expected because of the Routing Priority
1. first middleware before next
2. second middleware before next
3. third middleware before next
4. first middleware after next
5. second middleware after next
6. third middleware after next

I propose a change in the execution order, to match the expected execution order.

**Comment by PietervdWerk** [comment]
A valid point could be made of course, that the execution order should indeed look like this.

middleware 1 start
  middleware 2 start
    middleware 3 start
      request here
    middleware 3 end
  middleware 2 end
middleware 1 end

Maybe we could think of an api where we can opt into a different execution order? Does that make sense?

**Comment by yusukebe** [comment]
Hi @PietervdWerk !

> As stated in the Routing Priority documentation: "Handlers or middleware will be executed in registration order."
Though, middlewares don't execute according to that rule.

You are right, this wording on the website is confusing. However, we do not intend to change the current routing order. Because it will make big breaking changes. And this is implementation reasons. So, it is good to tell developers in an easy-to-understand way so that there is no confusion.

```
middleware 1 start
  middleware 2 start
    middleware 3 start
      request here
    middleware 3 end
  middleware 2 end
middleware 1 end
```

This way you wrote is very easy to understand and I want to use it.

Thank you!

**Comment by PietervdWerk** [comment]
Alright, totally understand. Thanks for your response, appreciate it.
