### ISSUE TITLE
Suggestion: validator as part of the handler

### ISSUE THREAD

**Issue by dagnelies** [honojs/hono#713]
Hi, sorry to bother you again with this but I still profoundly dislike putting the validator as middleware.
I would still prefer by far to use it in the handler directly.

That's why I would suggest the following modification, to be able to use it in the `c.req.valid(validator_function)`.

It would look like this:

```ts
const myData = c.req.valid((v) => ({
    post: {
      id: v.json('post.id').isRequired().asNumber(),
      title: v.json('post.title').isRequired().isLength({ max: 100 }),
      body: v.json('post.body').isOptional(),
    },
  }))
```

It would also be nice that in case of errors, it throws an exception with a clear message so that a nice HTTP 400 can be returned.

I tried to look a bit in the source code, but I could not find my was around regarding this validator.

**Comment by yusukebe** [comment]
Hi @dagnelies !

I understand what you are saying, but I am not going to follow your suggestion at this point. Because:

* For middleware, it is easy to return a 400 response. But, if it is a handler, we have to write the procedure to catch the error. We don't want to do that.
* We can separate the concerns by doing Validation in front of the handler.
* If we do that, there are problems with handling Types.
* It will be a breaking change, but it will not be worth it.

If you do not like that the code will become verbose, you can do the following:


```ts
const userSchema = (v: Validator) => ({
  id: v.json('id'),
  name: v.json('name'),
})

app.post('/foo', validator(userSchema), (c) => {
  const user = c.req.valid()
  return c.text(`Your name is ${user.name}`)
})
```

**Comment by dagnelies** [comment]
I think the main issue I have with this is related to my code organisation.
Currently, every endpoint is within its own file, with its own data types and validation stuff.

The main file looks like this:

```ts
import endpointA from './endpointA'
//...
import endpointZ from './endpointZ'

const app = new Hono()

app.get('/enpointA', endpointA)
//...
app.get('/enpointZ', endpointZ)
```

and in `endpointA.ts`:

```ts
type MyReqParams {
    foo: string,
    bar: string,
}

type MyResponse {
   id: string,
   timestamp: string,
   message: string
}

export default async function handler(c :Context) {
   // ...
}
```

...and it sounded just neat to put the validation there since it fits well there.

---

Otherwise I have to use to export / import / rename all validator functions and it would look like this:

```ts
import {validator as endpointA_validator, handler as endpointA_handler } from './endpointA'
//...
import {validator as endpointZ_validator, handler as endpointZ_handler } from './endpointA'

const app = new Hono()

app.get('/enpointA', endpointA_validator, endpointA_handler)
//...
app.get('/enpointZ', endpointZ_validator, endpointZ_handler)
```

It's just ugly IMHO since it does not fit well in how I structure the code. Or alternatively, pass the `app` directly to the endpoint file to self add the validator and handler, but this sounds dirty too.

I don't know how people split up their codebase using hono, but in my case this validator gets in the way, I would much more like to call it in the handler. But it's your choice, I respect that, so I closed the issue accordingly.
