### ISSUE TITLE
Should use Official Cloudflare Types

### ISSUE THREAD

**Issue by JustinGrote** [honojs/hono#716]
Now that the official cloudflare types allow separate importing rather than solely as global types, Hono should support them as handler responses.
https://unpkg.com/@cloudflare/workers-types@4.20221111.1/2022-08-04/index.ts

Currently if I use these types to build for instance a `Response`, they are not accepted by the router.

## Workaround
Import the Cloudflare `Response` type as `CfResponse` and then do `return myCfResponseObject as unknown as Response` which is technically unsafe.

**Comment by yusukebe** [comment]
Hi @JustinGrote !

> Now that the official cloudflare types allow separate importing rather than solely as global types, Hono should support them as handler responses.

I know it, but I think we should not do that. Because Hono must support Deno, Bun, and other runtimes, not only Cloudflare Workers. And even if we don't use Cloudflare's Response inside Hono, we can use it with `tsconfig.json` configuration.

```js
{
  "compilerOptions": {
    ...
    "types": ["@cloudflare/workers-types"]
  }
}
```

Perhaps I understand what you are saying incorrectly. If so, I would appreciate it if you could show us a specific code example.

**Comment by JustinGrote** [comment]
So the problem with doing the Cloudflare ambient types in compilerOptions is that a lot of stuff conflicts with Deno global types like `Blob` so you can't really use them, instead you can bring them in directly. In my case I need to submit the `cf` property that only exists on the CloudFlare response, but Hono won't let me return that response to the worker in a type safe way without overriding it using the syntax above.

**Comment by yusukebe** [comment]
Are you using `dom` in the `lib` section in `tsconfig.json`?

```json
{
  "compilerOptions": {
    "lib": [
      "dom", // <--- remove it
      "esnext",
    ],
    "types": [
      "@cloudflare/workers-types"
    ]
  }
}
```

If we use "`dom`", it will not support Cloudflare Workers' types. So I often remove the `dom` in the `lib` section and it will have the code completion like below:

<img width="764" alt="SS" src="https://user-images.githubusercontent.com/10682/207258776-bce2d116-ea61-4f02-bdfd-d0afae36f8df.png">

**Comment by JustinGrote** [comment]
Oh good tip, I just assumed you couldn't work around having the deno types in there! Closing with this as a valid workaround.
