### ISSUE TITLE
`Internal Server Error` when putting to R2 bucket if etagNotDoesMatch is false

### ISSUE THREAD

**Issue by rjocoleman** [honojs/hono#718]
I have noticed that I can reliably get an internal server error from Cloudflare R2 when uploading if `R2PutOptions` uses the `R2Conditional` `onlyIf` `etagDoesNotMatch` 

for example in this basic test case. This call will succeed the first time and fail with `Internal Server Error` the second time. 

```ts
app.post('/upload', async (c) => {
  const formData = await c.req.formData()
  const file = formData.get('file')
  const arr = await file.arrayBuffer()
  const etag = await md5(arr)

  const options = {
    onlyIf: { etagDoesNotMatch: etag },
    httpMetadata: { contentType: file.type },
  }

  const resp = await c.env.EXAMPLE_BUCKET.put('key-name', arr, options)

  return c.json(resp)
})
```

I am using Hono 2.6.1 and Wrangler 2.6.2.

I don't understand how to trace this to see what's going wrong, are you able to point me in the right direction please

**Comment by yusukebe** [comment]
Hi @rjocoleman 

This may not be Hono's matter. The following code without using Hono will throw same errors:

```ts

export default {
  async fetch(request: Request, env) {
    const formData = await request.formData()
    const file = formData.get('file')

    if (!file) {
      return new Response('failed')
    }

    if (!(file instanceof File)) {
      return new Response('failed')
    }

    const arr = await file.arrayBuffer()
    const etag = await md5(arr)

    const options = {
      onlyIf: { etagDoesNotMatch: etag },
      httpMetadata: { contentType: file.type },
    }

    const resp = await env.BUCKET.put('key-name3', arr, options)
    return Response.json(resp)
  },
}
```

Therefore, I don't know how to solve it, you may ask in the forum or Discord for Cloudflare.

**Comment by rjocoleman** [comment]
Thank you @yusukebe I will dig deeper

**Comment by yusukebe** [comment]
Okay, I'll close this issue.
