### ISSUE TITLE
Validator - File Type in Formdata

### ISSUE THREAD

**Issue by rjocoleman** [honojs/hono#724]
In the validator is there any way to validate a specific such as `File` within FormData? 

I see the `v.body` is already using `req.parseBody()` which does support `File`.

e.g. 

```js
app.put(
  '/form/:id',
  validator((v) => ({
    file: v.body('file').isRequired(),
    name: v.body('name').isOptional(),
  })),
  async (c) => {
    const res = c.req.valid()

    const id = c.req.param('id')
    const file = res.file
    const name = res.name || 'foo'
    c.text('Valid')
})
```

**Comment by yusukebe** [comment]
Now, Hono has a new validator mechanism. We can close this issue.

**Comment by Jdruwe** [comment]
I am not sure how we can do this now, any example @yusukebe ?

**Comment by yusukebe** [comment]
@Jdruwe 

Here. This is an example using Zod Validator:

```ts
import { Hono } from 'hono'
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'

const app = new Hono()

app.post(
  '/upload',
  zValidator(
    'form',
    z.object({
      file: z.instanceof(File)
    })
  ),
  async (c) => {
    const { file } = c.req.valid('form')
    console.log(file) // File | string
    return c.text('Get your file!')
  }
)

export default app
```

**Comment by abdurezakfarah** [comment]
> @Jdruwe
> 
> Here. This is an example using Zod Validator:
> 
> ```ts
> import { Hono } from 'hono'
> import { z } from 'zod'
> import { zValidator } from '@hono/zod-validator'
> 
> const app = new Hono()
> 
> app.post(
>   '/upload',
>   zValidator(
>     'form',
>     z.object({
>       file: z.instanceof(File)
>     })
>   ),
>   async (c) => {
>     const { file } = c.req.valid('form')
>     console.log(file) // File | string
>     return c.text('Get your file!')
>   }
> )
> 
> export default app
> ```

the file in the client is an instance of File, but in the server, the file is an instance of Blob. Why is this, and how can it be resolved?
