### ISSUE TITLE
TrieRouter should support . (period) as a variable name delimiter like in Express

### ISSUE THREAD

**Issue by JustinGrote** [honojs/hono#737]
Pattern
`/:id/:page.json`
Request:
`mysite.com/103/test.json`

## Expected
`id` will be `103` and `page` will be `test`

## Actual
`page.json` is `test.json`

**Comment by yusukebe** [comment]
Hi @JustinGrote !

I know exactly what you want to do,  but I don't want to implement it. I don't want to complicate the code anymore, and it will cause performance degradation.

We may address this feature if we get a few more requests. I will leave this Issue open for a while.

**Comment by JustinGrote** [comment]
Fair, I will just work around it for now.

**Comment by surprisetalk** [comment]
Workaround that works for me:

`/:id/:page{\\.json$}`

**Comment by JustinGrote** [comment]
@surprisetalk thank you!

**Comment by JustinGrote** [comment]
@surprisetalk this doesn't work for me...

```typescript
router.get('/test/:page{\\.json$}', c => c.text(c.req.param('page')))
```

![image](https://github.com/honojs/hono/assets/15258962/452cdec5-3da4-4f8d-b972-7bd0c3ef4603)
