### ISSUE TITLE
`@honojs` to `@hono` !

### ISSUE THREAD

**Issue by yusukebe** [honojs/hono#738]
`@hono` name scope on npm registry has been already taken, so I had to use `@honojs` namespace. Like `@honojs/sentry`.

BUT!

Now, I've received the email from the support, now, we can use `@hono` name scope and transfer the `@honojs` to that!
Right now, I am asking if the transfer will redirect from the old name to the new name.
If it is OK, let's move to `@hono`.

**Comment by yusukebe** [comment]
I've been the owner of `hono` org!

The existing packages, such as `@honojs/sentry` are still available.

**Comment by JustinGrote** [comment]
Exciting! Time to update my references

**Comment by yusukebe** [comment]
Already done!
