### ISSUE TITLE
[Question] Request type for fetch in cloudflare worker bindings

### ISSUE THREAD

**Issue by TorbjornHoltmon** [honojs/hono#740]
This issue is not be related to Hono types, and fits more as a question in a discussion.

We are currently refactoring our request gateway/proxy to use Hono.
We use worker bindings to route request to different workers on the same domain.

Reproduction:
https://codesandbox.io/s/determined-scott-rf4sqc?file=/src/main.ts

The request type seems to not be compatible, the request works fine. But the typing is wrong.

**Comment by yusukebe** [comment]
Hi @TorbjornHoltmon 

Currently, we have to set the `@cloudflare/workers-types` in `tsconfig.json`.

```json
{
  "compilerOptions": {
    "moduleResolution": "Node",
    "target": "ES2022",
    "module": "ES2022",
    "lib": [
      "ES2022"
    ],
    "types": [
      "@cloudflare/workers-types"
    ],
  }
}
```

It will be improved in the next major version so that it can be used without configuration.

**Comment by TorbjornHoltmon** [comment]
@yusukebe After investigation I think the worker types for `@cloudflare/workers-types` v4 is not 100% correct.

There are some differences in types in v3 to v4 that does not sense.

**Comment by yusukebe** [comment]
@TorbjornHoltmon 

This issue does not seem to be specific to Hono.

The `Request` object, which is defined in "Fetch API" is not matched with `Request` in `@cloudflare/workers-types`.

```ts
// request.ts
export const newRequest = () => new Request('http://localhost')
```

```ts
import { Request } from '@cloudflare/workers-types'
import type { ServiceWorkerGlobalScope } from '@cloudflare/workers-types'
import { newRequest } from './request'

declare const worker: ServiceWorkerGlobalScope

worker.fetch(new Request('http://localhost')) // OK

const request = newRequest()
worker.fetch(request) // NG
```

<img width="601" alt="SS" src="https://user-images.githubusercontent.com/10682/209146008-119fd9f2-53a6-49d7-99cc-4f6740de592e.png">

So, we have to use `tsconfig.json` and add `@cloudflare/workers-types` into `types`.
