### ISSUE TITLE
How to use JWT and CORS with secrets via Cloudflare

### ISSUE THREAD

**Issue by VR-Architect** [honojs/hono#756]
Hi,
The documentation shows how to use a secret for validating a JWT but it doesn't show how to use a secret variable stored in a Cloudflare worker. Also, could you please show had to add CORS when using JWT? 

This is what I have so far. But access to the environment variable is out of scope at this point and not sure how to combine with CORS.
Thanks.

```
import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { jwt } from 'hono/jwt'

const app = new Hono()
app.use('/*', cors());
app.use(
    '/*',
    jwt({
        secret: c.env.JWT_TOKEN_KEY,
    })
)
```

**Comment by yusukebe** [comment]
Hi @VR-Architect !

You can use secret variables with writing this way:

```ts
type Bindings = {
  JWT_TOKEN_KEY: string
}

const app = new Hono<{ Bindings: Bindings }>()
app.use('/*', async (c, next) => {
  const jwtMiddleware = jwt({
    secret: c.env.JWT_TOKEN_KEY,
  })
  return jwtMiddleware(c, next)
})
```

> Also, could you please show had to add CORS when using JWT?

I think you don't have to use CORS with JWT.

**Comment by yusukebe** [comment]
I'll close this issue. If you have any problem related to this issue, feel free to reopen.
