### ISSUE TITLE
.env files not loaded into c.env

### ISSUE THREAD

**Issue by hclj37** [honojs/hono#799]
I found the `.env` files are not loaded into `c.env`:

Runtime: Bun 0.4.0

```js
// index.ts

import { Hono } from 'hono'

interface Bindings {
  API_KEY: string
  API_SECRET: string
}

const app = new Hono<{ Bindings: Bindings }>()

app.get('/', async (c) => {
  console.log(c.env.API_KEY) // <--- undefined
  return c.text('hello')
})

export default {
  port: 3000,
  fetch: app.fetch,
}
```

```
# .env

API_KEY=hono
API_SECRET=123
```

**Comment by yusukebe** [comment]
Hi @hclj37 !

This is expected, not a bug.`c.env` is not designed for handling `.env` values. It's only for variables in Cloudflare Workers.

But, we might consider adding the possibility to look at the value of `.env,` i.e., the value of `process.env` for Bun or Node.js.

**Comment by hclj37** [comment]
@yusukebe 

Thanks for explaining the API design.

And I think it may be nice to automatically load `.env` files, just like Bun do. I think it is convenient and consistent.

> Bun Documentation:
> `.env` files automatically load into `process.env` and `Bun.env`

**Comment by yusukebe** [comment]
But, I think if we could get the values from `process.env` or `Bun.env` we wouldn't have to force it to be implemented. In the case of Cloudflare, it is not possible to get environment variables from the global, so this is the only way to do so.

@ThatOneBro 

What do you think about it?

**Comment by ThatOneBro** [comment]
Yes loading from `process.env` should allow us to get env vars for both Bun and Node environment. I guess `Deno.env.get()` (or whatever the API is) could also be included, although I think Deno Deploy provides a way to load the env vars already right?

**Comment by muhaimincs** [comment]
> Hi @hclj37 !
> 
> This is expected, not a bug.`c.env` is not designed for handling `.env` values. It's only for variables in Cloudflare Workers.
> 
> But, we might consider adding the possibility to look at the value of `.env,` i.e., the value of `process.env` for Bun or Node.js.

It's this possible?

**Comment by yusukebe** [comment]
Hi @muhaimincs 

Now, we can use the `env()`: https://hono.dev/helpers/adapter#env

**Comment by guoxiangke** [comment]
hi, I am a newbie of hono,
when I 
import { env } from 'hono/adapter'
then console.log(env(),'env() in app')
I got error:
TypeError: Cannot read properties of undefined (reading 'env') 

I also have a .env file and some variablies and edit Environment Variables in cloudfare works
same error when deploy to works:

**Comment by yusukebe** [comment]
@guoxiangke 

Did you include `c` as a argument?

```ts
app.get('/env', (c) => {
  const { NAME } = env(c)
  return c.text(NAME)
})
```

**Comment by maxjoygit** [comment]
How I can get env in cloudflare worker, without c argument,

**Comment by yusukebe** [comment]
@maxjoygit 

You can't it. `c` is needed.

**Comment by leoAshu** [comment]
Hi, I followed this thread for reading variables from a `.env` file. 
I try reading the env variables using `env(c)`, where `c` is the context, however, it returns an empty object.

```javascript
app.get('/', (c) => {
    return c.json({
        message: 'Live!',
        env: env(c)
    })
})
```

This is the output that I get:
```json
{
    "message": "Live!",
    "env": {}
}
```

Can anyone please point out what I am missing?

**Comment by maxjoygit** [comment]
hello,
@leoAshu 
you can get env variable by specifying in wrangler.toml file,
like this:
[vars]
MY_VARIABLE = "my env value"
 you will get output like this:

{ MY_VARIABLE: 'my env value' }

**Comment by leoAshu** [comment]
Thank you for the prompt response, @maxjoygit. This solution is effective, and I'm obtaining the desired outcome.

However, I do have a related concern regarding the approach.
- Can we safely assume that `wrangler.toml` can be ignored in Git, similar to a `.env` file?
- How can we guarantee that secure environment variables like api keys, database connection strings do not end up being committed to a public repository?

**Comment by maxjoygit** [comment]
I guess wrangler.toml use for local development, so you can gitignore it, and put your env varibales like this wrangler secret put SECRET_KEY

**Comment by knileshh** [comment]
> also be included, although I think Deno Deploy provi

Can you share how you're accessing your environment variable on local and deployed workers?
I'm having a lot of difficulty but after reading through this thread, I hope it works.

**Comment by knileshh** [comment]
```
import { Hono } from 'hono';
import { env } from 'hono/adapter';

const app = new Hono();

app.get('/', (c) => {

  const {GEMINI_AI} = env(c)
  const hi = GEMINI_AI
  console.log("my key:" +GEMINI_AI)
  return c.json({
      message: 'Live!',
      env: GEMINI_AI
  })
})

export default app;

```
OUTPUT:
```

⎔ Reloading local server...
my key:undefined
[wrangler:inf] GET / 200 OK (11ms)
```

I'm using cloudflare workers. I set my key using `wrangler secret set GEMINI_AI`

Please help.

**Comment by yusukebe** [comment]
@knileshh 

> Edit: Sorry for the inconvenience guys, but it's working it wasn't working on the local dev environment, when I deployed and checked the keys were being shown. Thankyou.

Yeah. We have to write it into `.dev.var` for local development: https://developers.cloudflare.com/workers/configuration/secrets/#secrets-in-development

> Q. Is there a way to use the .env without using the `c` ??

If you are using Cloudflare Workers, the answer is no. To get the variables, "*Env*" variables are needed in `c`.

**Comment by mingjinglu** [comment]
> hello, @leoAshu you can get env variable by specifying in wrangler.toml file, like this: [vars] MY_VARIABLE = "my env value" you will get output like this:
> 
> { MY_VARIABLE: 'my env value' }

working in cloudflare workers, **not working in cloudflare pages.**

Preconditions：
setting vars in cloudflare pages

code:
```
c.env // return like 

{
    "ASSETS": {},
    "CF_PAGES": "1",
    "CF_PAGES_BRANCH": "production",
    "CF_PAGES_COMMIT_SHA": "",
    "CF_PAGES_URL": "xxx.pages.dev",
    "SOME_VAR": "86400"
}
```
```
env(c) // aways return empty object {}
```

**Comment by yusukebe** [comment]
Hi @mingjinglu 

If you set up your project properly, you can get the env variables correctly. It will be a question. You can ask the [discussions](https://github.com/orgs/honojs/discussions).

**Comment by Soviut** [comment]
> * Can we safely assume that `wrangler.toml` can be ignored in Git, similar to a `.env` file?
> * How can we guarantee that secure environment variables like api keys, database connection strings do not end up being committed to a public repository?

The wrangler.toml file is an important config file for local development. You SHOULD commit it, however, you should NOT include any sensitive variables in it.

Instead, create a `.dev.vars` file, gitignore it, and put your sensitive variables there.

**Comment by shigurenimo** [comment]
for Bun runtime, we can pass Env (Bindings) to the second argument of hono fetch.

```ts
// index.bun.ts

import { type Serve, env } from "bun"

import app from "./index.ts"

export default {
  fetch(request) {
    return app.fetch(request, env)
  },
} satisfies Serve
```

index.ts works on Cloudflare.

```ts
// index.ts

type HonoEnv = {
  Bindings: {}
  Variables: {}
}

const app = new Hono<HonoEnv>()

export default app
```
