### ISSUE TITLE
named route param is undefined

### ISSUE THREAD

**Issue by navtoj** [honojs/hono#804]
| Platform | Issue | Details |
| :- | :- | :- |
| Deno `v3.0.0-rc.5` | Correct type for named optional parameter is not working. | See screenshots below. |

| Not working | Working |
| :- | :- |
| There is no error but term is `undefined`. | Term is `202209` but there is a type error. |
| ![image](https://user-images.githubusercontent.com/20136585/212521276-784893a2-c8f9-44b8-a3a1-9be531aee470.png) | ![image](https://user-images.githubusercontent.com/20136585/212521110-78ec4397-7035-40a4-b135-d1302a47ca0c.png) |

I'm currently using `@ts-ignore` for the error to get it working. Is there any proper way to fix this?

**Comment by yusukebe** [comment]
Hi @navtoj !

How about removing `?` like `app.get('/json/:term', ...)`?

**Comment by navtoj** [comment]
It works without any errors when the `?` is removed but then the `term` is not optional anymore.

I'm trying to use this feature: https://honojs.dev/docs/api/routing/#optional-parameter

**Comment by yusukebe** [comment]
Alright, it's a bug, or it's not implemented. I'll investigate it later.

**Comment by yusukebe** [comment]
Hi @navtoj 

Fixed it and released [v2.7.3](https://github.com/honojs/hono/releases/tag/v2.7.3) including this fix.
