### ISSUE TITLE
Support for decoding JWT

### ISSUE THREAD

**Issue by jeddeloh** [honojs/hono#810]
I wonder if the JWT middleware should have the option to decode the token and push it onto the context after verifying?

**Comment by yusukebe** [comment]
Hi @jeddeloh , thank you for the opinion. I'll consider it.

@metrue , how about this feature? I think we can do it with `c.get/c.set` functions.

**Comment by cd-slash** [comment]
@jeddeloh I've put together a quick example for decoding asymmetric JWT [here](https://github.com/honojs/hono/issues/672) - that puts the JWT payload into the context. You could maybe reuse that pattern for the existing (symmetric) JWT middleware?

**Comment by jeddeloh** [comment]
Thank you, @cd-slash! I've already written a small middleware for my needs, so I'm good to go. This ticket was only intended to propose a possible change to current JWT middleware.
