### ISSUE TITLE
undefined durable object 

### ISSUE THREAD

**Issue by hanumanjiblog** [honojs/hono#818]
how to use durable object in honojs?

https://developers.cloudflare.com/workers/learning/using-durable-objects/#accessing-persistent-storage-from-a-durable-object

**Comment by hanumanjiblog** [comment]
any easy way is available for creating durable object

**Comment by yusukebe** [comment]
HI @hanumanjiblog !

Have you ever seen the example below?

<https://github.com/honojs/examples/tree/main/durable-objects>

**Comment by zianwar** [comment]
Hi @yusukebe, in the example you provided, only the `c.req.url` is being passed to the Durable Object, is there way to pass down the whole request including the body? 

https://github.com/honojs/examples/blob/a377d4002199c44559cb48036f5ba7d3c9e1be83/durable-objects/src/index.ts#L13

**Comment by yusukebe** [comment]
Hi @zianwar !

I haven't checked it properly, but how about passing `c.req.raw`?

**Comment by zianwar** [comment]
That works but I have this use case where I need to do some validation before passing down the request to the Durable Object. 

I probably can't do this, and should delegate the whole request to the Durable Object to handle, but would love if you have a workaround?

```typescript
app.post("/api", zValidator("json", s), async (c) => {

  // 1. do some pre processing (looking up worker KV for example)
  c.req.valid() // ← this consumes the request :(
  
  //  2. pass the request to Durable Object
  const obj = c.env.DO.get(c.env.DO.newUniqueId());
  const response = await obj.fetch(c.req.raw) // ← this throw the following error ↓
  /* 
    Trace: TypeError: Cannot reconstruct a Request with a used body.
        at index.js:5326:26
        at dispatch (index.js:864:17)
        at index.js:865:33
        at index.js:5143:11
        at async index.js:5314:5
        at async index.js:1764:50 {
  */
  
  // 3. post processing (save data to KV)
  return c.json({ success: true })
})
```
