### ISSUE TITLE
Optional Route parameter has wrong type

### ISSUE THREAD

**Issue by pmbanugo** [honojs/hono#821]
Given the following route `/api/animal/:type?`, the `type` parameter is optional and can be undefined. However, the type returned from `req.param().type` is `string` instead of an optional string (i.e `type?: string`)

**Comment by yusukebe** [comment]
Ah, maybe the type should be `string` and if it this not much, the value should be `''` though it is `undefined` currently.

**Comment by yusukebe** [comment]
Okay, I think your opinion is indeed right. I will consider it a little more carefully.

**Comment by pmbanugo** [comment]
@yusukebe Thank you so much!
