### ISSUE TITLE
CORS breaks Content-Type header

### ISSUE THREAD

**Issue by moooji** [honojs/hono#835]
It appears that using the CORS middleware will always set the response Content-Type header to `text/plain` even when returning `c.json()` for example.

**Comment by moooji** [comment]
It seems that it broke between 2.7.3 and 2.7.4. My guess is that it has to do with this change here:
https://github.com/honojs/hono/compare/v2.7.3...v2.7.4#diff-0cd594dddd6a9f2e3e26afebbb92716434437d7001c2416252aa7531e7f2b8d4R68

**Comment by benton-droplab** [comment]
This seems to be happening with all middleware, including custom ones.

**Comment by yusukebe** [comment]
Thanks. I'll fix it soon.

**Comment by yusukebe** [comment]
Hi @moooji @benton-droplab !

I've fixed this issue and released v2.7.5. If you still have the problem, please reopen the issue. Thanks!
