### ISSUE TITLE
[Question] Can we use Deno instead of Node on CF Workers?

### ISSUE THREAD

**Issue by silvioprog** [honojs/hono#839]
Hi.

Can we use Deno+Hono instead of [Node+Hono](https://honojs.dev/docs/getting-started/cloudflare-workers/#npm-install-hono) at Cloudflare Workers platform? 🤔

TIA for any help!

**Comment by silvioprog** [comment]
Refs:

- [denoflare.dev](https://denoflare.dev)
- [deno.land/manual/advanced/deploying_deno/cloudflare_workers](https://deno.land/manual@v1.29.1/advanced/deploying_deno/cloudflare_workers)

**Comment by yusukebe** [comment]
Hi @silvioprog !

Do you mean you want to write the code with Deno and deploy it to Cloudflare Workers? I've never done it, but I think you can use Hono in Denoflare.

**Comment by silvioprog** [comment]
Exactly. I'll try this ASAP and let you know if that worked... In case of success, we should document that. WDYT?

**Comment by yusukebe** [comment]
> In case of success, we should document that.

I believe it is not necessary to put it on the web site.
