### ISSUE TITLE
[Dark mode] for the docs page

### ISSUE THREAD

**Issue by silvioprog** [honojs/hono#840]
Please support dark mode at https://honojs.dev/docs 🙏

**Comment by yusukebe** [comment]
Hi @silvioprog !

Yes, we are planning it. Will support the dark mode soon!

**Comment by yusukebe** [comment]
Fixed!

**Comment by silvioprog** [comment]
Amazing job. Thank you very much @yusukebe! 👏👏👏👏👏👏
