### ISSUE TITLE
Send 204 response

### ISSUE THREAD

**Issue by socketopp** [honojs/hono#849]
Hi, me again, still great library, just curious how you send 204 request, i.e. 'No Content'.

Using "hono": "^2.7.5"

[Documentation ](https://honojs.dev/docs/api/context/#shortcuts-for-response)says `c.status()` should set status so I thought returning context when status equal 204 would work.

Tried returning `ctx.status(204)`

However I get this error:

```
 Context is not finalized. You may forget returning Response object or `await next()`
    at index.js:1240:17 {
  stack: Error: Context is not finalized. You may forget reÔÇª object or `await next()`
    at index.js:1240:17,
  message: Context is not finalized. You may forget returning Response object or `await next()`
}
onError: ctx Context {
  error: undefined,
  _status: 204,
  _pretty: false,
  _prettySpace: 2,
  header:
  ...
}
```

The only thing that I observed that works is:
```
return ctx.text(undefined, 204)
or
ctx.status(204);
return ctx.text(undefined);
```

The voice of reasons states that content ought to be undefined unless we specifically set it to be something? Or what do you guys think?

**Comment by yusukebe** [comment]
Hi @socketopp !

How about writing the following?

```ts
app.get('/no-content', (c) => {
  return c.body(null, 204)
})
```
