### ISSUE TITLE
Can't get working 404 handler with honojs and CloudFlare Pages

### ISSUE THREAD

**Issue by caracal7** [honojs/hono#855]
Trying simple CloudFlare Pages example 

```javascript
import { Hono } from 'hono';
const app = new Hono();

app.get('*', async ctx => await ctx.env.ASSETS.fetch(ctx.req));

app.notFound(ctx => {
    return ctx.text('Custom 404 Message', 404);
})

export default app;
```

but don't have 404 message on missing assets

**Comment by yusukebe** [comment]
Hi @caracal7 !

In Cloudflare Pages, we can't handle 404 not found in the route returns `c.env.ASSETS.fetch()` . But you can put the `404.html` in the directory, and it will be shown.

**Comment by caracal7** [comment]
Working!

@yusukebe thanks a lot :)

**Comment by caracal7** [comment]
Working!

@yusukebe thanks a lot :)

**Comment by yusukebe** [comment]
Great! I'll close this issue.
