### ISSUE TITLE
Remove StaticRouter from default candidates ( or remove StaticRouter completely )

### ISSUE THREAD

**Issue by usualoma** [honojs/hono#868]
### Reasons for removing StaticRouter from the default list of candidates

With the optimization by #845 #867, I believe RegExpRouter can now perform as well as StaticRouter in a static path only application.

With https://github.com/usualoma/hono/commit/866a84ba2688367cb1b12ce270299971c451c1c6, The result is as follows.

```
$  npm run bench-static:node
...
summary for all together
  Hono RegExpRouter
   1.14x faster than Hono StaticRouter
   2.78x faster than koa-tree-router
   2.97x faster than @medley/router
   4.07x faster than trek-router
   4.24x faster than find-my-way
   8.91x faster than Hono TrieRouter
   34.19x faster than express (WARNING: includes handling)
   75.49x faster than koa-router

$ npm run bench-static:bun
...
summary for all together
  Hono RegExpRouter
   1.16x faster than Hono StaticRouter
   2.86x faster than koa-tree-router
   3.11x faster than @medley/router
   4.27x faster than trek-router
   9.83x faster than Hono TrieRouter
   34.08x faster than express (WARNING: includes handling)
   79.63x faster than koa-router
```

Whether RegExpRouter or StaticRouter is the winner can change if you swap the order in https://github.com/usualoma/hono/commit/866a84ba2688367cb1b12ce270299971c451c1c6#diff-1454672c9673414d6a1726ce738b4f2dddae2f99ad5a806d69185ff7a813f2a1R12-R20. Based on these results, I would consider the two to be of equal performance in static path routing.

The bundle size can be reduced by removing StaticRouter as the default candidates.

### If so, should we even remove StaticRouter from repository?

If an application that uses static paths wants to reduce the size of the application to the extreme, specifying a StaticRouter is an effective way to do so. It is worth leaving it if we recommend this type of use.

```typescript
const app = new Hono({ router: new StaticRouter() })
```

However, since Hono is small enough by default and is almost never used in such a way, I feel that StaticRouter can be removed from the repository.

**Comment by yudai-nkt** [comment]
This might be a bit off-topic, but what are the trie router's advantages over regexp router other than bundle size (2.8kB v.s. 3.9kB minified)? If regexp router is most performant and fattest but we don't seriously care about size, then it seems Hono only needs to have it instead of the other two.

I know the historical context; Hono only had trie router in the early days and you later introduced regexp router. As I'm not familiar with Hono's internal, it's nice to know what trie router is especially good at.

I don't want to sound rude or offensive. I really appreciate Yusuke's devotion into this project but want to understand the pros/cons between routers just out of curiosity.

**Comment by yusukebe** [comment]
Hi @yudai-nkt 

Yes, RegExpRouter looks perfect, it's fast and small. However, it does not support complex routing patterns for optimization. Just look at this PR by @usualoma.

https://github.com/honojs/hono/pull/519

Yes, so the way TrieRouter covers all routing and falls back to it is a very good strategy.

**Comment by yudai-nkt** [comment]
Thanks for the PR reference @yusukebe! I didn't know regexp router has some unsupported routing patterns.

While users usually don't need to understand the difference between routers thanks to the smart router, documenting those comparisons might help people with similar questions in the future. It's off course up to you whether to add the documentation or not.

**Comment by yusukebe** [comment]
@yudai-nkt 

You are right! Actually, I'm working on a new `honojs.dev` (which is built with VitePress!), and I'm planning to add more descriptions of routers there 👍
