### ISSUE TITLE
Use ENV parameters in CORS middleware

### ISSUE THREAD

**Issue by justinwride** [honojs/hono#895]
I have been trying to access `c.env` to inject my environment variables into the CORS configuration. However, it does not work as expected.
```javascript
import { Hono } from 'hono';
import { cors } from 'hono/cors';

const app = new Hono();

app.use('*', async (c, next) => {
    cors({
        origin: c.env.APP_URL,
        allowedHeaders: ['Origin', 'Content-Type', 'Authorization'],
        allowMethods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'],
        credentials: true
    });
    await next();
});
```
This code above returns the following error when trying to access the local worker (http://localhost:8000) from the browser (http://localhost:3000):

> Access to XMLHttpRequest at 'http://localhost:8000/test' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

When I hardcode this value, it works fine:
```javascript
app.use('*', cors({
    origin: 'http://localhost:3000',
    allowedHeaders: ['Origin', 'Content-Type', 'Authorization'],
    allowMethods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'],
    credentials: true
}));
```

Is there any way to use my environment variables from `c.env` in the CORS configuration middleware?

**Comment by yusukebe** [comment]
Hi @justinwride !

How about writing like the following?

```ts
app.use('*', async (c, next) => {
  const corsMiddleware = cors({
    origin: c.env.APP_URL,
    allowedHeaders: ['Origin', 'Content-Type', 'Authorization'],
    allowMethods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'],
    credentials: true,
  })
  await corsMiddleware(c, next)
})
```

**Comment by justinwride** [comment]
> Hi @justinwride !
> 
> How about writing like the following?
> 
> ```ts
> app.use('*', async (c, next) => {
>   const corsMiddleware = cors({
>     origin: c.env.APP_URL,
>     allowedHeaders: ['Origin', 'Content-Type', 'Authorization'],
>     allowMethods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'],
>     credentials: true,
>   })
>   await corsMiddleware(c, next)
> })
> ```

@yusukebe thanks, this is perfect! I couldn't find this pattern in the documentation for middleware, but it would be very helpful to add here: https://honojs.dev/docs/api/middleware

**Comment by justinwride** [comment]
I was getting a 404 error from the code above when the browser made an OPTIONS request.

Also this error:
> Error: Context is not finalized. You may forget returning Response object or `await next()`

Adding a `return` at the end fixed that issue:
```javascript
app.use('*', async (c, next) => {
  const corsMiddleware = cors({
    origin: c.env.APP_URL,
    allowedHeaders: ['Origin', 'Content-Type', 'Authorization'],
    allowMethods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'],
    credentials: true,
  })
  return await corsMiddleware(c, next)
})
```

**Comment by Rishiraj8** [comment]
Actually there are some simple issues I have faced "giving the locolhost with slash on the end (avoid that)"
which is not a big issue but it took me a half busy day :)
and also try to specify return await as previous contriubutors says 👍 
```javascript
app.use('*', async (c, next) => {
  const corsMiddleware = cors({
    origin: "http://localhost:5173",
    allowMethods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'],
    credentials: true,
  })
  return await corsMiddleware(c, next)
})

**Comment by Soviut** [comment]
Something else worth mentioning is you don't need to await the middleware. The function being async means it will already return a promise, so awaiting the middleware and then immediately returning just doubles up the promise unnecessarily.

Instead you can do the following

```javascript
app.use('*', async (c, next) => {
  const corsMiddleware = cors({
    origin: "http://localhost:5173",
    allowMethods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'],
    credentials: true,
  })
  return corsMiddleware(c, next) // <-- no need to await
})
```

**Comment by LRboyz** [comment]
Please tell me how to solve this problem. I encountered the same problem.

**this is client:**
```typescript
  const sendHeartbeat = useCallback(async () => {
    try {
      await ofetch(`${BASE_URL}/api/v1/heart/${userId}`, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${authToken}`, // 添加授权头
        },
        body: { message: "ping" },
      });
    } catch (error) {
      console.error("Failed to send heartbeat:", error);
    }
  }, [userId]);
```
**backend:**
```typescript
import { cors } from "hono/cors";

const app = new Hono().basePath("/api");

// 添加 CORS 中間件
app.use(
  "/api/*",
  cors({
    origin: ["http://localhost:6035", "http://localhost"],
    allowHeaders: ["Origin", "Content-Type", "Authorization", "X-Custom-Header", "Upgrade-Insecure-Requests"], // 允許的 headers
    allowMethods: ["OPTIONS", "GET", "POST", "PATCH", "PUT", "DELETE"], // 允許的 HTTP 方法
    exposeHeaders: ["Content-Length"], // 暴露的 headers
    maxAge: 600, // 預檢請求的結果可以被快取多久（秒）
    credentials: true // 是否允許發送 cookies
  })
);
```
**result**:
![image](https://github.com/user-attachments/assets/bc5f3a9a-632d-4de3-b053-f607f88b8874)

And the front end still displays CORS errors：
![image](https://github.com/user-attachments/assets/b3b3a071-ed3d-4e17-8a0b-b00075d4b437)

🙏Could you please give me an answer to solve the problem
