### ISSUE TITLE
`.get()` is undefined in Durable Object

### ISSUE THREAD

**Issue by subhendukundu** [honojs/hono#896]
As app is using get request directly like `this.app.get("/api/v1/activities", async (c) => {`, context does not have access to context setters from middleware. Is there a way to get access to `c.get("user")` in DO? Also is there a way to use the nested routes we do normally we use `Grouping`?

**Comment by yusukebe** [comment]
Hi @subhendukundu !

If you have the following application, are you referring to `c.get('key')`?

index.ts

```ts
import { Hono } from 'hono'

export class Do {
  state: DurableObjectState
  app: Hono = new Hono()

  constructor(state: DurableObjectState) {
    // ...
    this.app.get('/foo', async (c) => {
      c.get('key') // <--- Here??
      return c.text('foo')
    })
  }

  async fetch(request: Request) {
    return this.app.fetch(request)
  }
}
```

do.ts

```ts
import { Hono } from 'hono'
export { Do } from './counter'

type Bindings = {
  DO: DurableObjectNamespace
}
type Variables = {
  name: string
}

const app = new Hono<{ Bindings: Bindings; Variables: Variables }>()

app.use('*', async (c, next) => {
  c.set('name', 'Foo')
  await next()
})

app.get('/', (c) => c.text('Welcome'))

export default app
```

If so, you cannot refer to the value because it is a different instance of Hono.

**Comment by subhendukundu** [comment]
yes, that is exactly it, as I am using `app: Hono = new Hono()` it does not have the value added to the `app` instance. Now I tried to pass the `app` instance in `class Do`, but it did not work, is there a workaround to do this?
