### ISSUE TITLE
Hono's context in Deno's registry does not have `jsonT`

### ISSUE THREAD

**Issue by yudai-nkt** [honojs/hono#906]
Hono's context on deno.land/x doesn't have `jsonT` and the following Deno program doesn't compile (see [this page](https://deno.land/x/hono@v3.0.0-rc.16/mod.ts?s=Context#prop_json)).

```ts
import { Hono } from "https://deno.land/x/hono@v3.0.0-rc.16/mod.ts";

const app = new Hono();
app.get("/", (c) => c.jsonT({}));
```

```console
$ deno check index.ts
Check file:///Users/ynkt/tmp/hono-typedresponse/deno/index.ts
error: TS2551 [ERROR]: Property 'jsonT' does not exist on type 'Context<string, Environment, unknown>'. Did you mean 'json'?
app.get("/", (c) => c.jsonT({}));
                      ~~~~~
    at file:///Users/ynkt/tmp/hono-typedresponse/deno/index.ts:4:23

    'json' is declared here.
      json = <T>(object: T, status: StatusCode = this._status, headers: Headers = {}): Response => {
      ~~~~
        at https://deno.land/x/hono@v3.0.0-rc.16/context.ts:188:3
```

Importing from `npm:hono@3.0.0-rc.16` will solve the error, but neither Deno Deploy nor Fresh doesn't support npm specifier right now.

I'm not sure if this is caused by Hono or other tools (e.g., package registry or denoify) because `deno_dist` in this repo has `jsonT` indeed. I wanted to let you know anyway.

https://github.com/honojs/hono/blob/433ed530fcb010d90e52f0db132f6059694ce7be/deno_dist/context.ts#L240-L250

**Comment by yudai-nkt** [comment]
Just noticed #905. I'll see if a stable v3 release fixes this problem.

**Comment by yusukebe** [comment]
OK, please do so.

**Comment by yudai-nkt** [comment]
Now v3 on Deno has [`jsonT`](https://deno.land/x/hono@v3.0.0/mod.ts?s=Context#prop_jsonT) properly. I don't know what happened here but will close the issue. 

More than that, congrats on the major release! I'm currently busy with moving to a new house but will definitely try the RPC feature in my apps after that!

**Comment by yusukebe** [comment]
> Now v3 on Deno has jsonT properly.

Sounds good!

> More than that, congrats on the major release!

Yes! Now, I'm writing the release note

Good luck on your moving!
