### ISSUE TITLE
How to mock Context?

### ISSUE THREAD

**Issue by AliKaanT** [honojs/hono#911]
Hey, how can i mock Context constructor for unit testing my controllers?

**Comment by yusukebe** [comment]
For testing, you don't have to mock `Context` intentionally. But we recommend strongly the following way:

https://hono.dev/guides/testing

**Comment by AliKaanT** [comment]
Ok let me explain what im trying to do.
Im trying to write an enpoint test but i need to mock the functions that are using in the controller.
Im using jest & cf-workers
In the example below, im trying to mock the function 'sum' that used by 'multiply'. And then test the '/test' route and 'multiply' function.

./sum.ts:
```
const sum = (a:number, b:number):number => a+b;
export default sum;
```
./multiply.ts
```
import sum from './sum';

const multiply = (a: number, b: number): number => {
  let result = 0;
  for (let i = 0; i < b; i++) {
    result = sum(result, a);
  }
  return result;
};

export default multiply;
```
./index.ts
```
app.get('/test', async (c) => {
  return c.json(multiply(2, 3));
});
```
./test.test.ts
```
import multiply from './multiply';
import { unstable_dev } from 'wrangler';
import type { UnstableDevWorker } from 'wrangler';

jest.mock('./sum', () => {
  const originalModule = jest.requireActual('./sum');
  return {
    __esModule: true,
    ...originalModule,
    default: jest.fn((a, b) => a - b),
  };
});

describe('deneme1', () => {
  let worker: UnstableDevWorker;
  beforeAll(async () => {
    worker = await unstable_dev('src/index.ts');
  });
  afterAll(async () => {
    await worker.stop();
  });
  it('first', () => {
    const aa = multiply(2, 3);
    expect(aa).toBe(6);
  });
  it('second', async () => {
    const resp = await worker.fetch('/test');
    expect(resp.status).toBe(200);
    const data = await resp.json();
    expect(data).toBe(6);
  });
});
export {};

```

If i run the test. The first test fails as expected but the second one passes. The mocked functions are not effecting wranglers unstable_dev server.

Im not able to mock my functions and test endpoint. So i thought if i can create an Context object to myself, i can pass it to the controller of my route as parameter and test the endpoint indirectly.

If you have any better ideas. Can you please share with me. Thanks for your time.

**Comment by yusukebe** [comment]
Try this:

```ts
// index.ts
import { Hono } from 'hono'
import multiply from './multiply'

const app = new Hono()

app.get('/test', (c) => {
  return c.json({ result: multiply(2, 3) })
})

export default app
```

```ts
// index.test.ts
import multiply from './multiply'
import app from './index'

jest.mock('./sum', () => {
  const originalModule = jest.requireActual('./sum')
  return {
    __esModule: true,
    ...originalModule,
    default: jest.fn((a, b) => a - b),
  }
})

describe('mutiply', () => {
  it('first', () => {
    const aa = multiply(2, 3)
    expect(aa).toBe(6)
  })
  test('second', async () => {
    const res = await app.request('http://localhost/test')
    expect(res.status).toBe(200)
    expect(await res.json()).toEqual({ result: 6 })
  })
})
```

<img width="654" alt="SS" src="https://user-images.githubusercontent.com/10682/220148948-de712fad-e891-4d81-b46e-fb4131bebbdf.png">

**Comment by AliKaanT** [comment]
I appreciate your help so much. I spent a lot of time with this but it was that easy 🥲.
