### ISSUE TITLE
Router - Base path 

### ISSUE THREAD

**Issue by yassinrais** [honojs/hono#912]
is It possible to set a base path for the router?

instead of handling endpoints like`domain.com/v1/auth` as`/v1/auth`, it should handles it as `/auth`

Thanks!

**Comment by yusukebe** [comment]
Hi @yassinrais !

You can use `app.route()`.

https://hono.dev/api/routing#grouping

**Comment by yassinrais** [comment]
does it support url format ?

ex: `app.route('http://domain.com/v1')`

**Comment by yusukebe** [comment]
No. Treating a domain is not Hono matter.

**Comment by yassinrais** [comment]
Okey, thanks you 🙏🏻
