### ISSUE TITLE
[Feature Suggestion] `c.stream` Response helper

### ISSUE THREAD

**Issue by geelen** [honojs/hono#914]
Working on CF Workers and occasionally I find myself wanting to stream chunks of text down to cURL. There are a couple of steps to make it work, but I've wrapped it up in a little util that might make sense for inclusion into Hono?

```ts
app.get("/", async (c) => {
  return c.stream(async (stream) => {
    for (let i = 0; i < 3; i++) {
      stream.writeln(i).flush();
      await new Promise((res) => setTimeout(res, 1000));
    }
  });
});
```

&nbsp;

https://user-images.githubusercontent.com/23264/220233752-98d2abe5-5f9a-4813-80ac-ec45fc23d933.mov

&nbsp;

^ That's an example worker without Hono or Typescript. Source code, if you want to copy/paste it into the CF Workers editor:

<details>

```js
class StreamingApi {
  constructor(writable) {
    this.bytesWritten = 0;
    this.writer = writable.getWriter();
    this.encoder = new TextEncoder();
  }

  write(str) {
    const bytes = this.encoder.encode(str);
    this.bytesWritten += bytes.length;
    this.writer.write(bytes);
    return this;
  }

  writeln(str) {
    return this.write(str + "\n");
  }

  flush() {
    const bytes_needed = 4096 - (this.bytesWritten % 4096);
    const BACKSPACE = 8;
    this.writer.write(new Uint8Array(bytes_needed).fill(BACKSPACE));
    this.bytesWritten = 0;
  }

  close() {
    this.writer.close();
  }
}

const textStream = (cb) => {
  const { readable, writable } = new TransformStream();
  const stream = new StreamingApi(writable);
  cb(stream).finally(() => stream.close());
  return new Response(readable, {
    headers: {
      "content-type": "text/plain",
      "Transfer-Encoding": "chunked",
    },
  });
};

export default {
  async fetch(request, env) {
    return textStream(async (stream) => {
      for (let i = 0; i < 3; i++) {
        console.log(i);
        stream.writeln(i).flush();
        await new Promise((res) => setTimeout(res, 1000));
      }
    });
  }
}
```

</details>

### How does it work?

To do this kind of chunked-streaming from CF Workers, you need a couple of things:

* To create a `ReadableStream` and `WritableStream` using `new TransformStream()`
* Return a `Response` with the `readable` as the body, and `Transfer-Encoding: chunked` header.
* Use `writable.write()` to push content onto the stream
* 🚨 **DANK HAX ALERT** 🚨 Pad out chunks to the nearest 4096 bytes so CF sends them immediately, otherwise they're buffered (thx [this post](https://community.cloudflare.com/t/streaming-responses/106683/4)). I send `ASCII 8 (BACKSPACE)` because cURL ignores this.
* Remember to `writable.close()` to end the stream & close the response.
* Hit it with cURL, potentially with `-N` flag. Browsers don't seem to stream things correctly, and also the backspaces make Chrome download it as a file and Firefox displays them as little hex chars. But curl works great.

I've made a `textStream` function that gives this API:

```ts
return textStream(async (stream) => {
  for (let i = 0; i < 3; i++) {
    stream.writeln(i).flush();
    await new Promise((res) => setTimeout(res, 1000));
  }
});
```

It sets up the TransformStream invokes the callback (without awaiting it) and returns the Response:

```ts
type TextStream = (cb: (stream: StreamingApi) => Promise<void>) => Response;
const textStream: TextStream = (cb) => {
  const { readable, writable } = new TransformStream();
  const stream = new StreamingApi(writable);
  cb(stream).finally(() => stream.close());
  return new Response(readable, {
    headers: {
      "content-type": "text/plain",
      "Transfer-Encoding": "chunked",
    },
  });
};
```

The `stream` property that's passed into the callback is an instance of this `StreamingApi` class, which provides helpers like `.write`, `.writeln`, `.flush` etc. This could be expanded with a bunch of helpers, but here is the implementation as-is:

```ts
class StreamingApi {
  private bytesWritten: number;
  private writer: WritableStreamDefaultWriter;
  private encoder: TextEncoder;

  constructor(writable: WritableStream) {
    this.bytesWritten = 0;
    this.writer = writable.getWriter();
    this.encoder = new TextEncoder();
  }

  write(str) {
    const bytes = this.encoder.encode(str);
    this.bytesWritten += bytes.length;
    this.writer.write(bytes);
    return this;
  }

  writeln(str) {
    return this.write(str + "\n");
  }

  flush() {
    const bytes_needed = 4096 - (this.bytesWritten % 4096);
    const BACKSPACE = 8;
    this.writer.write(new Uint8Array(bytes_needed).fill(BACKSPACE));
    this.bytesWritten = 0;
  }

  close() {
    this.writer.close();
  }
}
```

I'm going to wrap this up into its own little library and publish it, but thought I'd raise an issue here first as I'm curious what you think of the API?

**Comment by geelen** [comment]
FWIW, after a few more hours on this I made a couple of tweaks. For one, using `BACKSPACE` isn't great if you want to pipe it to JQ, but that swallows `SPACE`s anyway. So I added `log` to emit JSON and `pipe` if you want to compose streams together:

```ts
  log(obj: any) {
    return this.write(JSON.stringify(obj)).flush(SPACE);
  }

  async pipe(body: ReadableStream) {
    this.writer.releaseLock();
    await body.pipeTo(this.writable, { preventClose: true });
    this.writer = this.writable.getWriter();
  }
```

So you can do:

```ts
return textStream(async (stream) => {
  stream.log("Normal line of text")
  for (let i = 0; i < 3; i++) {
    stream.log({i});
    await new Promise((res) => setTimeout(res, 1000));
  }
});
```

<img width="521" alt="image" src="https://user-images.githubusercontent.com/23264/220259898-ce27c4f6-12d6-483c-9699-1672b17250c5.png">

Works beautifully!

**Comment by yusukebe** [comment]
Hi @geelen !

This is very interesting! I would like to consider this feature more deeply, so give me some time.

And I want to know some use cases for this `c.stream` in the real world. I know the [`renderToReadableStream()`](https://reactjs.org/docs/react-dom-server.html#rendertoreadablestream) in React is effective, but if we want to do such "React Streaming SSR", we can use the React's function. I think you know other cases to use `c.stream`. Thanks!

**Comment by kiancyc** [comment]
chatGPT has a stream mode which sends a EventSource stream as response.

**Comment by HeyITGuyFixIt** [comment]
I am working on a project where I need to take an MJPEG video stream, crop it, and pass that along. Something like this may allow me to much more easily implement this.

**Comment by sor4chi** [comment]
eg: ChatGPT streaming proxy

```ts
import { Hono } from 'hono'

const app = new Hono()

const PROMPT = (message: string) => [
  {
    role: 'system' as const,
    content:
      'You are an Web developer. If you receive a question about Web-related technologies, you can answer it.',
  },
  {
    role: 'user' as const,
    content: message,
  },
]

app.post('/', async (c) => {
  const body = await c.req.json()
  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY })

  return c.stream(async (stream) => {
    const chatStream = await openai.chat.completions.create({
      messages: PROMPT(body.message),
      model: 'gpt-3.5-turbo',
      stream: true,
    })

    for await (const message of chatStream) {
      stream.write(message.choices[0]?.delta.content || '')
    }
  })
})
```

Proxying ChatGPT streaming would allow for authentication, rate limiting, and other protections.

**Comment by sor4chi** [comment]
Hello, @yusukebe, @geelen

I agree with this issue as well.
Since I didn't write the code about `c.stream`, if geelen can afford it, he can submit a PR and I can actually create some use cases for it.
How about it?

**Comment by gunta** [comment]
+1
This is a must for any GPT-related project since streaming is expected by the user

**Comment by yusukebe** [comment]
The PR #1437 to implement a `c.stream` has been created.

**Comment by sor4chi** [comment]
Hi, @yusukebe 
Shall I write a docs for the website about `c.stream()` and `c.textStream`?

**Comment by yusukebe** [comment]
@sor4chi 

Yes, pleeeese! If you create the PR, I'll merge it after releasing v3.7.0.

**Comment by yusukebe** [comment]
We can fix this! Thanks!!!
