### ISSUE TITLE
Fetch a Cloudflare service binding with Hono Client

### ISSUE THREAD

**Issue by JonasHiltl** [honojs/hono#917]
It would be great if the Hono client could be used to send a fetch request to a service binding. 
With service bindings you have to call the `fetch` method on the binded `Fetcher` like this:
```toml
services = [
  { binding = "auth", service = "authentication" }
]
```
```javascript
export default {
  async fetch(request, env) {
    const authResponse = await env.auth.fetch(request.clone());
    ...
  }
};
```
Since Hono client uses the default `fetch` implementation this does not work, it would be great if we could pass our own fetch function which could default to the normale environment `fetch` implementation and the Hono Client would just call this fetch parameter.

**Comment by yusukebe** [comment]
Hi @JonasHiltl !

I am not familiar with Service Bindings, but it is not necessary to use Hono Client. How about the following code?

```ts
import type { Fetcher } from '@cloudflare/workers-types'
import { Hono } from 'hono'

type Bindings = {
  auth: Fetcher
  application: Fetcher
}

const app = new Hono<{ Bindings: Bindings }>()

app.all('*', async (c) => {
  const authResponse = await c.env.auth.fetch(c.req.raw.clone())
  if (authResponse.status !== 200) {
    return authResponse
  }
  return await c.env.application.fetch(c.req.raw)
})

export default app
```

**Comment by JonasHiltl** [comment]
Hi @yusukebe,
yes it is not necessary to use Hono Client since I could just use the normal fetch call, but I want the advantages of the full route types that come with Hono Client. 

The service I want to call has validation built in with the honos `zValidator`, so I can get the types for the route. But since the service is a Cloudflare Worker I can only call it through a service binding from a different worker. This currently does not work with Hono Client since it uses the default fetch method. I would be able to call the service binding if the [fetch](https://github.com/honojs/hono/blob/main/src/client/client.ts#L95) method could be passed as an argument to the client (it could default to the normal fetch API). 
That way I can have the full types that come with Hono Client while still being able to call service bindings through their fetch method.
