### ISSUE TITLE
Hono.js not working on Supabase Edge function

### ISSUE THREAD

**Issue by Akash187** [honojs/hono#923]
I tried using [Hono.js](https://hono.dev/) with the edge function but it failed to work.

Function Code:
```
import { Hono } from 'https://deno.land/x/hono@v3.0.1/mod.ts'
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

console.log('Notion Parser Method Functions!')

const app = new Hono()

app.get('/', (c) => c.text('Hello Deno 123!'))

serve(app.fetch)
```
The code is building but giving a 404 Not Found error both locally and after deployment.

I have created a ticket regarding this issue on the Supabase repo https://github.com/supabase/supabase/issues/12629.

Posting it here to get help.

**Comment by yusukebe** [comment]
Hi @Akash187 !

Actually, I have never run Hono in Supabase. I will try later.

**Comment by Akash187** [comment]
@yusukebe Issue is fixed Supabase team helped me.
For future reference Solution Link - https://github.com/supabase/supabase/issues/12629

**Comment by yusukebe** [comment]
Wow, cool!
