### ISSUE TITLE
Hono Client type is `unkown` when validator schema has boolean field

### ISSUE THREAD

**Issue by JonasHiltl** [honojs/hono#932]
I played around with some `zod` schemas and Hono Client, when specifying a query field as`z.boolean()` with `zValidator` the type of the client is `unkown`. See this example:
```typescript
export const route = new Hono().get(
  '/',
  zValidator(
    'query',
    z.object({
      bool: z.boolean(),
    }),
  ),
)

type AppType = typeof route;

const client = hc< AppType >('/api');
```

Is this expected, or should it be possible to pass a boolean as a query field?

I know boolean parsing in JS is a bit weird to this might be expected.

**Comment by yusukebe** [comment]
Hi @JonasHiltl !

It may be difficult to understand. That's because `query` only allows `string`.

**Comment by JonasHiltl** [comment]
Ok, that makes sense, I thought it might be possible to handle the `string` to `boolean`/`number` parsing under the hood in Hono Client so that the user could also pass a `boolean` or `number` to the request. 
But that's just an idea I can also just handle the parsing in the application.

**Comment by yusukebe** [comment]
Maybe this can be closed.
