### ISSUE TITLE
[v3.0.2] await handler(c, next); typescript error

### ISSUE THREAD

**Issue by Zerebokep** [honojs/hono#940]
Please check this repo: https://codesandbox.io/p/sandbox/naughty-sunset-sewpnb?selection=%5B%7B%22endColumn%22%3A17%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A17%2C%22startLineNumber%22%3A11%7D%5D&file=%2Findex.ts

<img width="929" alt="Screenshot" src="https://user-images.githubusercontent.com/15731988/221658454-2dae4138-7445-4fe9-b779-f4c10876eb4b.png">

This error popped up after upgrading to v3

**Comment by yusukebe** [comment]
Hi @Zerebokep !

I can't find the error in your codesanbox. Can you paste the snippet codes as a comment?

**Comment by yusukebe** [comment]
@Zerebokep 

Sorry, it reproduced. This is caused by the sentry middleware did not support the latest Hono version.

Now, I've released `@hono/sentry@0.2.0`, please use it!

**Comment by Zerebokep** [comment]
Works fine now, thank you @yusukebe
