### ISSUE TITLE
Returning `Array<T>` response makes `jsonT` think it as `T` type

### ISSUE THREAD

**Issue by kissge** [honojs/hono#950]
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCQgOwnAvnAZlCEOAcgAt0JiBuAKFElkTlIGNs8CiyKB6FgG2ABTNDGo0aLdAGd4AQzBg4AXjhohAdxQUAFAEoAdAHMhMHcR64IlADRwdLPSoB8cFgYBW09ABUdSYAATAC44AG1iK1s4ABYAJgBdbD09Wh4eOEy4AD0AfgkpNFk3QRF4VVYAHhgATzAhCFw4BTBncx5iVMkZeCghaRVmjTlgeAFhUQMogwASEzMuwuLAuRg5Qblh0bg+6U9vNH00jKy8iSA

![image](https://user-images.githubusercontent.com/4177010/222666095-087f379e-62dd-4418-8c5d-857078ef916b.png)

**Comment by yusukebe** [comment]
This is already fixed.
