### ISSUE TITLE
Testing when using the 'cache' middleware is difficult due to missing execution context

### ISSUE THREAD

**Issue by grempe** [honojs/hono#953]
When utilizing the `cache` middleware it assumes that the context and `caches` will be present.

https://github.com/honojs/hono/blob/main/src/middleware/cache/index.ts#L18

It might be helpful if this was a no-op when used in environments that don't have access to the cache API? Otherwise, it becomes difficult to run any unit tests against the API without a workaround.

The discussion here provides a helpful utility method. If cache can't be a no-op in test environments, then perhaps this utility could be fleshed out to provide a testing helper that Hono would provide to handle this situation in a more official way.

https://github.com/honojs/hono/issues/678#issuecomment-1364578058

I extended it a little bit so I could extract it and use it across the test suite by passing in the `Hono` app object.

```typescript
/**
 * A helper function to easily make GET requests against
 * the hono router with a dummy ExecutionContext. This is needed
 * because the 'cache' middleware requires an ExecutionContext
 * to be present, which is not present in the unit tests. This
 * function will create a dummy ExecutionContext and pass it to
 * the app.fetch() function. Use this for GET requests instead of
 * 'await app.request('http://localhost/')' in unit tests.
 * @param app The hono app
 * @param url The URL to fetch
 * @param environment The environment to pass to the app
 * @param mockContext The mock context to pass to the app
 * @returns The response
 * @see: https://github.com/honojs/hono/issues/678#issuecomment-1364578058
 * */
export function get(
  app: Hono<{ Bindings: Bindings }>,
  url: string | URL,
  environment?: any,
  mockContext?: ExecutionContext,
) {
  const request = new Request(url)
  mockContext ??= {
    passThroughOnException: () => {},
    waitUntil: () => {},
  }
  return app.fetch(request, environment, mockContext)
}
```

Thanks for guidance on a better way to handle this if there is one.

**Comment by yusukebe** [comment]
Hi @grempe !

Very good point of view, good suggestion!

The `app.request` is a helper to make testing easier, I think we can add the feature you suggest:

https://github.com/honojs/hono/blob/64956cb57ded4f8b7833afd9a9059e6dac3bfaac/src/hono.ts#L287-L299

It has not been a PR yet, but this might be a good way that we write it like below:

```ts
  request = async (
    input: Request | string | URL,
    requestInit?: RequestInit,
    env?: {},
    executionCxt?: ExecutionContext
  ) => {
    executionCxt ??= {
      passThroughOnException: () => {},
      waitUntil: () => {},
    }
    if (input instanceof Request) {
      if (requestInit !== undefined) {
        input = new Request(input, requestInit)
      }
      return await this.fetch(input, env, executionCxt)
    }
    input = input.toString()
    const path = /^https?:\/\//.test(input) ? input : `http://localhost${mergePath('/', input)}`
    const req = new Request(path, requestInit)
    return await this.fetch(req, env, executionCxt)
  }
}
```

**Comment by yusukebe** [comment]
Hi @bdsoha 

While it refactored but, you can still you these methods:

```ts
const app = new Hono()
const res = await app.request('/')

// Or

const app = new Hono()
const req = new Request('/')
const res = await app.fetch(req, { key:'val', executionContext })
```

**Comment by bdsoha** [comment]
@yusukebe Thanks for the quick response.

I was reffering to something a little bit more involved.

How would you go about testing the routes below *(the `BEARER_TOKEN` is not mockable)*:

```js
const app = new Hono()

app.use('*', bearerAuth({ token: env('BEARER_TOKEN') }))
```

**Comment by yusukebe** [comment]
You should use the following approach:

```ts
app.use('*', (ctx, next) => {
    return bearerAuth({ token: ctx.env.BEARER_TOKEN })(ctx, next);
});
```

Currently, this is the only method to handle values like `ctx.env.xxx` in middlewares such as `bearerAuth` and `basicAuth`.

**Comment by yusukebe** [comment]
We can close this issue. Thanks.
