### ISSUE TITLE
A way to completly overwrite response from middleware after next()

### ISSUE THREAD

**Issue by TorbjornHoltmon** [honojs/hono#960]
This is a very niche issue.

We use Hono for many things, including our Cloudflare workers' proxy. 
The proxy sits on top of our domain and routes traffic to different workers and other external servers.

When you proxy a request from a worker, the response that Hono gets is a fetch response, and you cannot change headers.

When we use middleware in our proxy, there is no way for us to re-write the response since ´contex.res´ has a `set` that manipulates the headers.

https://github.com/honojs/hono/blob/fea78f29bd681350ce61dd71b33042aa6ec7db5c/src/context.ts#LL101-L110C4

```typescript
  set res(_res: Response) {
    if (this._res) {
      this._res.headers.delete('content-type')
      this._res.headers.forEach((v, k) => {
        _res.headers.set(k, v)
      })
    }
    this._res = _res
    this.finalized = true
  }
```

Not many people will have this issue, but we could really use some type of overwrite on the response so that we can write middleware that does something like this:

```typescript
export const cookieMiddleware: MiddlewareHandler<HonoEnv> = async (c, next) => {
    await next()
    if(c.res.headers.has("special-header")) {
      // We cannot use res.headers, so we clone the headers
      const clonedHeaders = cloneResponseHeaders(c.res)
      clonedHeaders.append('Set-Cookie', "cookie goes here")
        
      // create a new response from the old
      const newResponse = new Response(c.res.body, {
        headers: clonedHeaders,
        status: c.res.status,
      })
      // some way to overwrite response, just an example
      c.overwriteResponse(newResponse)
    }
}
```

If only the `set` did not change headers we could have used that

```typescript
 set res(_res: Response) {
    this._res = _res
    this.finalized = true
  }
```

Maybe this is something that should be contained in its own world. "hono/proxy". Which is meant to handle things as a proxy and not api.

**Comment by yusukebe** [comment]
Hi @TorbjornHoltmon !

I have ideas about this "middleware matter". I'll let you know later.

**Comment by yusukebe** [comment]
Hi @TorbjornHoltmon !

I've created PR #970 . With this PR, you can do it by putting `undefined`:

```ts
app.use('*', async (c, next) => {
  await next()
  c.res = undefined
  c.res = new Response('New Response')
})
```

This way does not include breaking changes and makes it possible what you want to do.

**Comment by yusukebe** [comment]
I think we can close this issue. Thanks.

**Comment by fzn0x** [comment]
Hi, can you document this feature ? @yusukebe I think this is really helpful for custom middleware. I just found the feature was implemented here.
