### ISSUE TITLE
hono/cloudflare-pages 404 handler doesn't work

### ISSUE THREAD

**Issue by Skye-31** [honojs/hono#966]
As shown in the snippet below, when using hono's cloudflare pages handler, it doesn't inherit the 404 handler of the original app, so it responds with Hono's generic plaintext 404 (thanks to `new Hono().route(...)`)

```js
export const onRequest = handle(app, '/api');
```

https://github.com/honojs/hono/blob/fea78f29bd681350ce61dd71b33042aa6ec7db5c/src/adapter/cloudflare-pages/handler.ts#L17-L22

**Comment by yusukebe** [comment]
Hi @Skye-31 !

Yes, you are right. `app.route()` does not inherit the Not Found handler of "subApp". So we were about to deprecate passing pass as the second argument. Instead that, we can specify base path with `basePath` method that is not merged:

```ts
const app = new Hono().basePath('/api')

//...

export const onRequest = handle(app)
