### ISSUE TITLE
`etag` middleware returns incorrect headers

### ISSUE THREAD

**Issue by navtoj** [honojs/hono#972]
The [**IETF** standards](https://datatracker.ietf.org/doc/html/rfc9110#name-304-not-modified) say the following[^1] about `304 Not Modified` responses...

> The server generating a 304 response MUST generate any of the following header fields that would have been sent in a [200 (OK)](https://datatracker.ietf.org/doc/html/rfc9110#status.200) response to the same request:
> * [Content-Location](https://datatracker.ietf.org/doc/html/rfc9110#field.content-location), [Date](https://datatracker.ietf.org/doc/html/rfc9110#field.date), [ETag](https://datatracker.ietf.org/doc/html/rfc9110#field.etag), and [Vary](https://datatracker.ietf.org/doc/html/rfc9110#field.vary)
> * Cache-Control and Expires (see [[CACHING](https://datatracker.ietf.org/doc/html/rfc9111)])

However, the `etag` middleware does not return the `ETag` header for 304 responses.

https://github.com/honojs/hono/blob/fea78f29bd681350ce61dd71b33042aa6ec7db5c/src/middleware/etag/index.ts#L20-L30

[^1]: https://datatracker.ietf.org/doc/html/rfc9110#section-15.4.5-2

**Comment by yusukebe** [comment]
Hi @navtoj !

Thanks for creating the issue.

You are right. We have to include the "Etag" header into the `304` response. I've made the PR #973 which may resolve this issue. Could you see it?
