### ISSUE TITLE
hc index route

### ISSUE THREAD

**Issue by Tarnadas** [honojs/hono#979]
Hey,

I encountered a bug when using `route` with a nested index route:

```ts
import { Hono } from 'hono';
import { hc } from 'hono/client';

const api = new Hono().route('/api');
const route = api.get('', c => c.jsonT({ ok: true }));

type AppType = typeof route;

const client = hc<AppType>('/');

// this will create a request against `/api/index` instead of `/api`
client.api.index.$get();
```

The request is run against `/api/index` instead of `/api` in this example.

**Comment by Tarnadas** [comment]
thx @yusukebe I will try this out. However I don't seem to be able to upgrade easily, because I get a type error when using `@hono/zod-validator` `zValidator`. I assume this dependency would need an update as well?

**Comment by yusukebe** [comment]
Note that you should specify `/` instead of an empty path or you will get unexpected behavior.

```ts
const route = api.get('/', (c) => c.jsonT({ ok: true }))
```

**Comment by yusukebe** [comment]
@Tarnadas 

Ah, yes, you are right. You need Zod Validator that is compatible with Hono v3.1.0. I will release it after v3.1.0 is generally released.

But I think you don't want to wait until then, so I'll paste the code I'm writing now (Zod Validator's code is tiny).

```ts
import type { Context, MiddlewareHandler, Env } from 'hono'
import { validator } from 'hono/validator'
import type { z } from 'zod'
import type { ZodSchema, ZodError } from 'zod'

type ValidationTargets = 'json' | 'form' | 'query' | 'queries'
type Hook<T> = (
  result: { success: true; data: T } | { success: false; error: ZodError },
  c: Context
) => Response | Promise<Response> | void

export const zValidator = <
  T extends ZodSchema,
  Target extends ValidationTargets,
  E extends Env,
  P extends string
>(
  target: Target,
  schema: T,
  hook?: Hook<z.infer<T>>
): MiddlewareHandler<
  E,
  P,
  { in: { [K in Target]: z.input<T> }; out: { [K in Target]: z.output<T> } }
> =>
  validator(target, (value, c) => {
    const result = schema.safeParse(value)

    if (hook) {
      const hookResult = hook(result, c)
      if (hookResult instanceof Response || hookResult instanceof Promise<Response>) {
        return hookResult
      }
    }

    if (!result.success) {
      return c.json(result, 400)
    }

    const data = result.data as z.infer<T>
    return data
  })
```

**Comment by christophemarois** [comment]
Thanks for the updated `zValidator`, @yusukebe — the speed at which you work is incredible. Looking forward to a stable 3.1.x release!

**Comment by Tarnadas** [comment]
Thx @yusukebe! I managed to update and it's all working now. Looking forward to the next release
