### ISSUE TITLE
ConnectionClosed: fetch() failed

### ISSUE THREAD

**Issue by Landris18** [honojs/hono#994]
Hello, I'm using npm package yt-search in my bun hono project.

```
import * as yts from "yt-search";
const videos = await yts.search("Alan walker");
```

And this throw me this error:

![image](https://user-images.githubusercontent.com/47665507/226099315-dff812fc-4c02-48ac-a0fb-c398568c7d07.png)

Note: The package work well in nodeJS express project.

**Comment by yusukebe** [comment]
Hi @Landris18 !

This seems to be not Hono matter. Please try running the application without Hono.

**Comment by Landris18** [comment]
Yes this is a problem with bun itself , thank you 🙏👊
