### ISSUE TITLE
Setting a cookie partially breaks HTML content type

### ISSUE THREAD

**Issue by ir-g** [honojs/hono#995]
Applying a cookie appears to break calls to the `c.html` method. The below code erroneously returns a plain text content type.
```ts
app.get('/cookietest', (c: Context) => {
    c.cookie("COOKIE", "cookieString");
    return c.html("<h1>This rendered fine</h1>");
})
```
If the code is changed to the below code, it works as expected and returns an html content type.
```ts
app.get('/cookietest', (c) => {
    c.cookie("COOKIE", "cookieString");
    c.header('Content-Type', 'text/html');
    return c.html("<h1>This rendered fine</h1>");
})
```
If a return call uses `c.html`, the `Content-Type` should not need to separately specified.

**Comment by yusukebe** [comment]
Hi @ir-g !

Thanks for creating the issue.

I've fixed this issue with PR #997 . We'll ship the next version including it soon.
